### ISSUE TITLE
Uploads: Implement Versioning for Data Files

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1007]
**Description:**
Originally when uploads were planned to be done via S3 Pre-Signed URLs the frontend was generating a unique UUID for use as a `slug` which would be the filename in S3 to prevent any collisions and allow repeated uploads without overriding files. Once https://github.com/raft-tech/TANF-app/pull/861 is merged we will have moved instead to django-storages for these uploads and the `slug` field is currently unused, with the files instead being uploaded to a unique path per STT and quarter with the original filename at the end of the path. The purpose of this ticket is to determine the best route forward for implementing the versioning feature out of the options we have available.

**Utilize [S3 built in object versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/versioning-workflows.html)**

If we instead move to using S3's built in versioning capabilities we would spend a little more up front dev time but be able to reap additional benefits and better structure our models.

From the S3 side the only work to do for this is enabling versioning on the bucket via API call or service instance configuration. However, on the Django side due to the way django-storages works only the latest version of a file will be retrieved for each ReportFile entry. The ability to retrieve the correct file for previous versions from the associated ReportFile model is what we would need to build out here.

Pros:
* AWS handles versioning for us
* Less information needs to be supplied with the payload to create a new Data File
* Ability to restore files accidentally deleted or overwritten
* Ability to apply granular lifecycle policies to handle things like deleting old versions after time

Cons:
* More dev effort

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Uploaded Data Files are versioned
- [x] Latest file version is displayed in `data-files` via "Download"
- [ ] Previous versions are retained in S3 and accessible via their associated models
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] TODO: Once an option from above is chosen by the team add the relevant tasks
- [ ] Implement lifecycle as per updated SORN
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Regardless of the option chosen here - we can still serve the files as downloads to users under any filename we wish.

**Supporting Documentation:**

**Open Questions:**

**Comment by jtwillis92** [comment]
An additional option to implement this which could tie in with #755 would be to restructure the models such that there is only ever 1 DataFile instance for a given STT, year, quarter and section which itself stores no files but instead links to a separate model `DataFileVersion` via a foreign key. This `DataFileVersion` model would store the actual file along with the metadata like `original_filename`, `extension`, etc. From the high level `DataFile` instance we would simply call a property `latest_version` which would then allow reading the file as usual from that linked model instance. This would not rely on S3's built in versioning but would allow us to easily reference any version of a file without needing to override internal functionality of django-storages.

cc @abottoms-coder

**Comment by abottoms-coder** [comment]
@lfrohlich @amilash Putting a pin in this for next week's backlog refinement

**Comment by lfrohlich** [comment]
Either we need to update the SORN or we need to delete State/Territory files after 30 days

**Comment by stevenino** [comment]
> Either we need to update the SORN or we need to delete State/Territory files after 30 days

SORN dependency no longer applicable per backlog refinement on 4/12/22

**Comment by ADPennington** [comment]
@n0remac @jtimpe ---can you confirm that with the implementation of this ticket, each data file submitted will be saved in S3 by program (TANF/SSP), section, fiscal year, and quarter? Currently, for example, we see that the directory location of files saved in S3 does _not_ distinguish quarterly files by fiscal year. See example below:

```
tdp-backend-prod/data_files/2/Q1/test_Section1
```
This made us wonder, if an STT submitted a file for FY23 Q1 and then later submitted a file for FY24 Q1, would the latest submission overwrite the previous one in S3? 

cc:@ttran-hub

**Comment by jtimpe** [comment]
@ADPennington we haven't touched the `s3_upload_path` so your assumption is correct, uploading a submission for a different year would overwrite the same file (given the the stt_id, quarter, and file name all match). Both files would still be individually accessible by the `s3_version_id`, but we should still throw the year in the file path and create versions for the correct files. I think it's a fairly easy change. 

@n0remac @ttran-hub
