### ISSUE TITLE
Remove/refactor Unused Dockerfiles

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1008]
**Description:**
After moving to buildpacks for the deployed environments there are some unused Dockerfiles in the project which adds unnecessary confusion to local development along with additional efforts needed to synchronize changes across files.

**Backend Dockerfiles**
Currently we have 3 for the backend: Dockerfile, Dockerfile.dev, and Dockerfile.local. The only one being used right now is Dockerfile.local. We should copy Dockerfile.local into Dockerfile and remove all other files and update references in the docker-compose.

**Frontend Dockerfiles**
The frontend also has 3 files, but only 2 are used currently (Dockerfile.dev and Dockerfile.local). Using multi-stage docker builds we can get this down to a single Dockerfile that has the `nginx` stage as an additional named target. Then in docker-compose files we would just reference the appropriate stage for the given environment (CI or Local)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Both the frontend and the backend each only have one Dockerfile to manage
- [x] CI can still use nginx for frontend, while local will use yarn start directly
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Consolidate Dockerfiles
- [x] Update references in docker-compose
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
