### ISSUE TITLE
(UX Sprint 24) Current State Analysis of Error Communication and Regional Staff Workflow Validation

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#1018]
**Description:**

(Sprint 24) (June 23 - July 6) The focus for this ticket is in two parts. 

- The first part focuses on understanding the extent of errors that are technical blockers to submission (and back end parsing) or other types of validation, and how they are currently being communicated to STT Users who are grantees. We also want to learn how error communication is currently impacting the larger workflow within TDP. (Release 3)

**Note: If the number of parsing blocking errors turns out to be fewer than X, widen the net with X error slice.**
(Start with blocking parsing errors, report back on how many are seen often then we can widen the net).

- The second part shifts gears to first validate 'current state journey map' how regional managers currently engage with TDP and then we want to understand what processes will be needed to enable regional staff to confirm the identities of grantee users. (Release 1) This will be validated by user validation of design mock ups.

**AC:**

- PO and PM are able to use the error analysis and workflow to agree on the error communication to be released in release 3. 

- Research and design opportunities can be ticketed from the validated RM journey maps. Opportunities and touch points can be agreed upon and features defined and prioritized.

- Insights from regional staff's process for confirming identities of grantee users are understood and new questions illuminated, and can be further researched in future sprints.

**Tasks:**

*Analysis of all parsing blocker errors / their meanings*
- [x] (Miles & Dmitri) (8 pts each) Analyze DIGIT parsing notebooks
- [x] (Miles) (5pt) Gather metrics associated to parsing blockers to measure against after release
- [x] (Dmitri) (5 pt) Create/confirm a full list of non-legacy parsing blockers

*Analysis of related instructions and current state workflow documentation for parsing blockers (Bring to sprint 25 ideation workshops)*
- [x] (Miles / Dmitri) (8 pts each) Document how each parsing blocker is being communicated to grantees
- [x] (Dmitri) (5 pts) Create a current state workflow for how parsing blockers will impact the larger workflow within TDP
- [x] (Dmitri) (8pts) Topline synthesis of data error analysis

*Regional manager journey map and request process workshop*
- [x] **(Miles) (8 pts) Invite participants (Sync with lauren)** 
- [x] (Dmitri / Miles) (13 pts) Create workshop board
- [x] (Dmitri / Miles) (5 pts each) Conduct workshop
- [x] (Dmitri / Miles) (8 pts) Topline synthesis of the workshop
- [x] (Dmitri) (5 pt) Update Journey Maps based on feedback
- [x] (Miles) (3 pt) Update request access process workflow based on feedback

**DoD:**
- [x] Parsing blocker top-line synthesis, parsing blocker workflow, and regional manager top line synthesis are presented at UX sync
- [x] @lfrohlich sign off

**Deliverables**
[Analysis of parsing blockers & associated guidance](https://app.mural.co/t/raft2792/m/raft2792/1624455269095/a03c7a41f537ee50530451e7cb2a26fa11d2c9e6)
[Regional manager journey map and request process workshop board](https://app.mural.co/t/raft2792/m/raft2792/1624900952389/c71e6f49d6e30badaa8beaa43c18061d958df67c?sender=dknapp0725)

**Comment by amilash** [comment]
@dk-ui @reitermb  will you both please add estimates for the tasks, this will help us track progress and commit to the size of work in a sprint. Thanks!

"Task name" - ( Append Estimate)
20 pts = 1 sprint for 1 person

**Comment by dk-ui** [comment]
@lfrohlich for review

**Comment by lfrohlich** [comment]
Reviewed parsing blockers board and added comments

**Comment by lfrohlich** [comment]
These both look good, thanks!
