### ISSUE TITLE
(UX Sprint 25) Ideation for Parsing Blocker Communication

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#1019]
**Description:**
(Sprint 25) (July 7 - July 20) In sprint 24 we discovered what errors block parsing and how they are currently being communicated to grantees. In this sprint, we ideate on new ways to communicate what these errors mean and how to fix them. We then bring them to the DIGIT team to understand gaps in our knowledge and what revisions should be tested with grantees in future sprints.

**AC:**

- Refined Lofi mockups can be tested with grantees
- Additional error insights from grantees are captured for future error prioritization

**Tasks:**

*External Ideation Workshop Part 1 (with DIGIT team)*
- [x] (Miles) (3 pts) **Invite 4-5 participants**
- [x] (Dmitri & Miles) (8 pts each) Internal ideations of parsing blocker communication
- [x] (Dmitri) (8 pts) Create ideation workshop board
- [x] (Dmitri & Miles) (5 pts each) Conduct error workshop part 1

*External Ideation Workshop Part 2 (with DIGIT team)*
- [x] (Dmitri & Miles) (5 pts) Conduct error workshop part 2
- [x] (Miles & Dmitri) (13 pts) Top Line Synthesis of Workshop

**DoD:**
- [x] Topline synthesis are presented at UX sync
- [x] @lfrohlich sign off

**Deliverables**
[Ideation Workshop Board with DIGIT](https://app.mural.co/t/raft2792/m/raft2792/1625859924911/4c37f4b0377d433d509dd5555a8c04086c16d08f?sender=dknapp0725)

**Comment by dk-ui** [comment]
@amilash All set to review

**Comment by amilash** [comment]
@dk-ui  do you have a link to the board or place to review?

**Comment by dk-ui** [comment]
@amilash Good question! For every ticket, we put the reviewable items in the deliverables section. There is a link for "Ideation workshop board with digit" that will lead to the reviewable content. Let me know if the link doesn't work or if you have trouble finding the content.

**Comment by ADPennington** [comment]
@reitermb lgtm. left a few minor comments in the mural.

**Comment by lfrohlich** [comment]
@reitermb have @ADPennington 's comments been noted/addressed?

**Comment by reitermb** [comment]
> @reitermb have @ADPennington 's comments been noted/addressed?

Yes, we're tracking a lot of them as research questions for (mainly) the remaining error related research epics—some others were corrected in the context of the round 7 synthesis doc, I'll go ahead and reflect those in the mural too for consistency!
