### ISSUE TITLE
(UX Sprint 26) Test Error Communication for Parsing Blockers

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#1020]
**Description:**
(Sprint 26) (July 23 - August 3) In sprint 25 we met with the DIGIT team to run a series of workshops to diagnose our current understanding and iterations of error communication. In sprint 26 we start by implementing that feedback into updated error copy concepts. We then concept test with grantees to determine if the new communication is easier to understand and is more actionable than previous communication. These concepts will then be refined for further validation in upcoming sprints.

**AC:**

- [x] Error copy has been concept tested with grantees
- [x] Documented Error copy can be used by developers or to refine ongoing errors research
- [x] Additional error insights from grantees are captured for future error research

**Tasks:**

*Internal Refinement Workshop* 
- [x] (Dmitri & Miles) (13 pts each) Refine Lofi Mockups based on feedback for content test

*Content test error copy and workflow with grantees (potentially 1:1)*
- [x] (Team) **Align on recruitment criteria (higher error rate for T1-501, T1-513, T1-516, Other Errors, and tribal inclusion)**
- [x] (Miles) (3 pts) **Invite 4-5 grantee participants (Risk -  Need recruitment criteria alignment)**
- [x] (Miles) (8 pts) Create Content Test Guide
- [x] (Dmitri) (8 pts) Create Content Test Materials
- [x] (Miles & Dmitri) (8 pts each) Conduct Content Test
- [x] (Miles) (8pts) Topline Synthesis

**DoD:**
- [x] Content test topline synthesis is presented to team
- [x] @lfrohlich sign off

**Deliverables**
Content Test Conversation Guide
[Error Workshop #1](https://app.mural.co/t/raft2792/m/raft2792/1627324002127/5923c0a550ba559b3fb6a61d54b6a7dacbd964e9?sender=dknapp0725)
[Error Workshop #2](https://app.mural.co/t/raft2792/m/raft2792/1627482784739/72c905b1fa5f39839b86b3a241a31f432f964285?sender=dknapp0725)
[Error Workshop #3](https://app.mural.co/t/raft2792/m/raft2792/1627566660744/623517beb8c38644cc613691cae5ca5779c5cc4f?sender=dknapp0725)

**Comment by lfrohlich** [comment]
This is complete
