### ISSUE TITLE
Dependabot Mass Merge / Improvements

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1023]
**Description:**
Since Dependabot was implemented we have been churning through a significant backlog of package updates that were previously missed. Per our [documented git flow](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Architecture%20Decision%20Record/009-git-workflow.md) we have been reviewing these PRs one at a time and putting them through the regular QASP review process. However, in the case of large volumes of these PRs this is very time consuming and a lot of these updates are minor version increases which don't change any of our functionality.

We have discussed a process where these dependency PRs could be bulk merged into a single branch and reviewed as a whole whenever they exceed a certain volume. Once all dependency updates were in one branch the typical review process would be followed. After the backlog has been cleared these dependency updates should be a much lower frequency so they could be handled in the typical git flow as needed.

Additionally, Dependabot PRs currently are created with no reviewers - we should update the configuration so PRs are opened with reviewers from the Raft team.

Another issue seen with Dependabot PRs on the Python side specifically, is that many of our dependencies don't have a strict equality setting for the version number - leading to unintended upgrades of unrelated packages when generating a lock file for a distinct package update. After we have merged all of these updates in we should set all the versions to strict release numbers and allow Dependabot to handle upgrading them individually.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Dependabot update backlog is cleared out - ie all dependencies are up to date
- [x] Dependabot ADR is updated to cover this option in case it needs to be done again in the future
- [x] The app has been manually tested and confirmed to work after upgrading all dependencies queued by Dependabot
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Open a PR to update the Dependabot ADR to document this process
- [x] Create a temporary branch to hold all dependabot updates - branched from raft-tdp-main
- [x] Close/Merge any open Dependabot updates
- [x] Open a PR to update the Dependabot config to target the branch from the first task and increase the open PR limit to 50
- [x] Update the Dependabot config to set reviewers to @raft-tech/tdrs-developers
- [x] Merge all Dependabot PRs into the branch from the first task
- [x] Revert the Dependabot config prior to merging
- [x] Open a new PR to raft-tdp-main with all dependency updates
- [x] Update versions in the Pipfile to use strictly equals (==) 
- [x] Thoroughly test the application before submitting to QASP
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

- [Dependabot target branch config](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#target-branch)
- [Dependabot open PR limit config](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit)
- [Dependabot reviewers config](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#reviewers)

**Open Questions:**

**Comment by kniz-raft** [comment]
@jtwillis92 or @abottoms-coder can you do an ADR for Alex to review that outlines the process?

**Comment by ADPennington** [comment]
@jtwillis92 I noticed that there is a high severity security vulnerability addressed in [django 3.2.5](https://docs.djangoproject.com/en/3.2/releases/3.2.5/), but I didn't see the security advisory in this repo (also didnt find this vulnerability in github's advisory db). The method referenced here appears in at least a couple places in our codebase.

**Comment by jtwillis92** [comment]
> @jtwillis92 I noticed that there is a high severity security vulnerability addressed in [django 3.2.5](https://docs.djangoproject.com/en/3.2/releases/3.2.5/), but I didn't see the security advisory in this repo (also didnt find this vulnerability in github's advisory db). The method referenced here appears in at least a couple places in our codebase.

Our Pipfile.lock currently has us at Django 3.2.5 :D 

https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/tdrs-backend/Pipfile.lock#L189
https://github.com/raft-tech/TANF-app/network/dependencies
