### ISSUE TITLE
As a dev, I want a unified environment variable driven configuration for logging in Django

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1036]
**Description:**
Currently the log level for the logging performed by Django is hardcoded to a specific log level in 8 different files across the backend, with varying levels of verbosity. (Based on a search for the line `logger.setLevel` across the python files in the repo). Additionally, the handlers defined in our various settings modules are all hardcoded to specific levels, which leaves little flexibility for debugging both locally and in production.

Per the Django [logging configuration docs](https://docs.djangoproject.com/en/3.2/topics/logging/#configuring-logging) the default way to handle this is to use the Django settings handlers to set log levels. If we remove the `logger.setLevel` calls from the codebase and allow these settings to be configured via environment variable(s) we will get a lot more flexibility in log level granularity.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Django log level can be set via environment variable
- [ ] Django logging handlers are used for all cases that adjust log level
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add a new environment variable and utilize it in Django settings configuration for logging
- [ ] Remove all uses of `logger.setLevel` in the code base
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by valcollignon** [comment]
@abottoms-coder based on comments during this morning's stand up, do you think this ticket should still be pointed 3?

**Comment by valcollignon** [comment]
Demo by @abottoms-coder - 12.21.21
