### ISSUE TITLE
[Devops] Allow pa11y to scan views that require authorization

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1044]
**Context**

login.gov requires an OTP
We can't simulate it, even with a headless browser like initially suggested, because of  it
We shoudn't be testing 3rd party services any way

**Description:**

In working on #872, we realized that pa11y can't properly test the pages that require authorization. The images generated currently are all of the home page with a message indicating that a login is required.

Perform pa11y scans on all other pages on the site other than the homepage, which is already done. The goal is to create a puppeteer function that will log into login.gov and create a context for the pa11y to navigate authenticated pages using the puppeteer context. 

**Acceptance Criteria:** 

- [ ] The images generated by pa11y on screens that require authorization showing the correct page
- [ ] The images are still uploaded as artifacts during CI as implemented in #872
- [ ] All end points are mocked
- [ ] All mocks, except those without implementations, are only used when the app is built with an ENV var set to true
- [ ] Testing Checklist has been run and all tests pass
- [ ] In CI, run the mocked version of the frontend
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Mock all unmocked API endpoints on the frontend
- [ ] Put the mocks behind an ENV flags if they have an implementation on the backend
- [ ] Setup CI to run mocked version of frontend
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

The mechanism we'd use to login through puppeteer would also be useful for writing more meaningful integration tests.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
