### ISSUE TITLE
As tech lead, I want to know the steps that will be followed to use updated buildpacks for TDP apps

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1045]
**Description:**

Periodically, we will receive emails like the following from cloud.gov informing that buildpacks have been updated. The steps for restaging are below. Before proceeding, it is important that we document our process for ensuring  these updates do not introduce any breaking changes for TDP. 

The email below was sent on 6/23/2021, so this most recent update is relevant for TDP 😄 

---
Hi cloud.gov user,

cloud.gov frequently updates the programming language buildpacks available to our customers. Buildpack updates include programming language updates and often include security fixes.

We recently updated buildpacks in use by your applications. You should restage or redeploy your applications to take advantage of the update. 

Keep in mind that restaging is the quickest way to upgrade, but causes downtime so you may want to leverage your deployment infastructure if you have set up zero-downtime deploys.

You can restage your applications by opening the command line and entering the following commands.

  cf target -o hhs-acf-prototyping -s tanf-dev ; cf restage tdp-backend

  cf target -o hhs-acf-prototyping -s tanf-dev ; cf restage tdp-frontend

For more information on keeping your application updated and secure, see: 
https://cloud.gov/docs/getting-started/app-maintenance/

If you have questions, you can email us at cloud-gov-support@gsa.gov.

Thank you,
The cloud.gov team

---

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Process for testing and restaging apps to leverage updated buildpacks documented for TDP_
- [ ] _updated buildpacks tested for TDP_
- [ ] _TDP apps restaged_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _This should be addressed prior to tribal mvp release (preferably soon after prod env is set-up so the whole process from testing to restaging prod apps can be carried out)_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
