### ISSUE TITLE
Teardown inactive deployments

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1050]
**Description:**
Make these deployments automatically tear down after a certain period of inactivity - to prevent wasting unused resources on Cloud.gov

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] TBD
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Implement tear down mechanisms
- [ ] Tie tear down to system timer(s)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
- Define period(s) of inactivity
- Do these timers depend per resource/app?

**Comment by abottoms-coder** [comment]
Dupe of #1060
