### ISSUE TITLE
Nested grouping attributes for Regions

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1052]
**Description:**
To accommodate the role of "Regional Manager", we'll need to create nested group logic within Django's Model-based permissions. For example, the STT user for the state of Florida would be under the Southeast region, as would a user for state of Georgia. Currently, we do this sort of lookup via [class-based permissions](https://github.com/raft-tech/TANF-app/blob/e99eae020de33bf32988a4d07103a3a8b4db8cc3/tdrs-backend/tdpservice/users/permissions.py#L75).

**Acceptance Criteria:** 
- [ ] Regional Manager has higher-level control only inside their region
- [ ] STT users only have relevant permissions inside their STT
- [ ] STT users are automatically associated to their region and Regional Manager
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Create an exhaustive mapping of all regions and their child STTs per the [data directory](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/tdrs-backend/tdpservice/stts/management/commands/data)
- [ ] Ensure the above mapping is accessible via the database/Models
- [ ] Update STT user permissions abstractly based on STT lookup
- [ ] Create Regional Manager role and assign permissions based on Region lookup
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Regional Map:
![image.png](https://images.zenhubusercontent.com/60abc3a8916bb9149afff73e/aeeb50db-d39f-4514-8f08-920de3ffb3c8)
- While spread out over 3 files, the [data directory](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/tdrs-backend/tdpservice/stts/management/commands/data) does contain all associations. 

**Supporting Documentation:**

**Open Questions:**

**Comment by abottoms-coder** [comment]
Listed as blocked by #1011 because we still need to finalize all tribe names.

**Comment by amilash** [comment]
remaining estimate 3.
