### ISSUE TITLE
As a dev, I want Terraform changes to be reflected in label driven deployments (GitHub Action)

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1059]
**Description:**
Following https://github.com/raft-tech/TANF-app/pull/977 we will need to update the `Deploy with CircleCI` GitHub Action to also call the `deploy-infrastructure-dev` job in Circle CI prior to running the deployment job for the target environment as implemented in https://github.com/raft-tech/TANF-app/pull/1056

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] PR Label based deployments perform any Terraform changes needed before deploying the application
- [x] Any remnants of previous gitflow based deployments to dev are removed
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add a step to the `deploy-on-label.yml` GH Action configuration that calls `deploy-infrastructure-dev` before issuing the call to deploy to a particular environment.
- [x] Remove `deploy-dev` job from Circle CI config and workflows
- [x] Remove old label `Deploy with CircleCI` from GH label choices.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by abottoms-coder** [comment]
Closing as dupe as it will be resolved in #1260.
