### ISSUE TITLE
As an STT user, I want to be invited to participate in research (round 3)

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#106]
**Description:**
For round 3 of user research, plan, recruit and schedule interviews.

**AC:** 
- [x] 5-9 STTs have been contacted (ccing RO contacts) to schedule interviews for Round 3. 
- [x] Email template from #170 is followed

**Note**
- This may not be completed in sprint 5. The first step is to contact the ROs which might run outside of this sprint based on their availability. The grantees are most likely going to be contacted next sprint.

**Tasks:** 

- [x] Collect contact information for OFA regional offices
- [x] Send out emails asking for STT contacts
- [x] Confirm STT interviewees with RO contacts
- [x] Schedule interviews (ccing RO contacts)

**DoD:**
- [ ] Interviewees have been contacted to schedule interviews.
- [ ] Team knows when interviews are generally happening. 

**Resources**
#228 Email for STT Participation: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B645fcfdc-c65d-474a-9c57-d51f3c68ac96%7D&action=view))
STT Contact List: ([Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B4d2b3627-7439-4c8a-91a3-9f896bda0f2a%7D&action=view))
STT Attributes Spreadsheet: ([Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7Be83f84f1-71a0-459f-80a4-0d39bc250be9%7D&action=view&cid=54888b6c-fc09-46e2-9bab-53a6ffbc57a3))
Interview Logistics: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/doc2.aspx?sourcedoc=%7B0333313B-0F88-406B-B894-07687D32921B%7D&file=%23170%20STT%20Interview%20Protocol%20DRAFT.docx&action=default&mobileredirect=true))

**Comment by cmajel** [comment]
@shubhi-raft @matthewjdoty - wondering if this should be moved up to the backlog as we round the corner on round 3 research planning.

**Comment by dk-ui** [comment]
@cmajel Moved to this sprint. In progress now.

**Comment by dk-ui** [comment]
10/7/20 All OFA regional offices have been contacted. Waiting on a reply to complete this ticket. If a reply is not generated in time, this ticket will roll over to next sprint.

**Comment by dk-ui** [comment]
@matthewjdoty @shubhi-raft 9 emails were sent out to STTs. The final date and times offered can be found in the interview logistics (shown below).

Note: I took out any PII of the STT in the timeline for interviews.

Interview Logistics: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/doc2.aspx?sourcedoc=%7B0333313B-0F88-406B-B894-07687D32921B%7D&file=%23170%20STT%20Interview%20Protocol%20DRAFT.docx&action=default&mobileredirect=true))

**Comment by lfrohlich** [comment]
This was completed in Sprint 5 #63
