### ISSUE TITLE
Automate inactivity teardown for Cloud.gov deployments in the dev space

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1060]
**Description:**
Following https://github.com/raft-tech/TANF-app/issues/848 we have several targets available for deployments in the Cloud.gov `tanf-dev` space which can exist simultaneously for different testing flows. However, since we have a set quota for resource usage in Cloud.gov and are charged based on memory usage we could potentially run into quota limitations or increased costs if we leave all of these targets up all the time. Instead we should find a way to automatically tear down or otherwise deactivate these applications when they have not been in use for a set period of time (an hour, a day, etc). 

Additionally, when these are "initial" deployments (the app was removed or non-existent) a new JWT_KEY/JWT_CERT combination will be generated which leaves the app non-functional until Login.gov is updated or the old key combination is restored. This will be relevant when tearing down the application - as actually deleting it also resets any environment variables. We will need to find some way to handle this automatically so we don't have to log in to Login.gov for each new deployment event.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Deployed apps in the Cloud.gov dev space tear down or deactivate after not being used for a designated period of time
- [ ] Login.gov integration remains correctly configured after a tear down and restore event
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate and implement a way to automatically tear down or disable Cloud.gov applications
- [ ] Determine a way to retain JWT_KEY/JWT_CERT configuration between tear downs
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
