### ISSUE TITLE
System Admin group by default

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1065]
**Description:**
Create the "System Admin" group by default.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] On a fresh deploy, this group is selectable. 
- [ ] Users with this group/role have appropriate permissions
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create the "System Admin" group by default
- [ ] Ensure this is true for both cloud and local deployments
- [ ] Associate correct permissions to group
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Are the permissions captured in the matrix in OneNote/parent epic correct?

**Comment by amilash** [comment]
Remaining estimate sprint 28: 2
