### ISSUE TITLE
Groups: Rename `Data Prepper` to `Data Analyst`

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1071]
**Description:**
The Data Prepper group needs to be renamed to accurately reflect artifacts about permissions. This includes references across the frontend and backend code which checks for a user's membership in the group.

Ideally, all group names would be defined in a single constant which could be imported across the code base so any future renaming will only have to be done in one place.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Data Prepper should be renamed to Data Analyst
- [ ] All existing and newly added permissions should still work correctly
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update any existing migrations that add this group to use the correct group name
- [ ] Update any code references that utilize the old name to point to the new one
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
