### ISSUE TITLE
Fix state issues with Data Files Download button

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1108]
**Description:**
Currently after successfully submitting a Data File to the API the UI does not associate the `id` of the created `DataFile` instance with the returned report in the Redux state/reducers. This results in two separate unexpected behaviors:
* The download button doesn't appear for the submitted sections until the search is re-submitted.
* Attempts to upload additional sections after a successful upload result in re-uploading previously sent files with no change.

This is because the presence of the `id` field is used to determine if the Data File has already been successfully submitted and since it isn't updated in the Redux state until the next search is completed the UI is unaware it was already submitted and tries to submit again.

We should add a new Redux reducer or refactor the existing ones to properly set this value after uploads.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] The download button appears immediately after successfully submitting sections in the Data Files UI.
- [x] Further submissions without refreshing the page don't resend previously submitted Data Files.
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add or update existing Redux reducers to set the `id` in the Redux state store for a successfully submitted DataFile.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Some more context can be found in the comment history for [this PR](https://github.com/raft-tech/TANF-app/pull/1061)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Redux docs](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by abottoms-coder** [comment]
Pending description rewrite by John

**Comment by valcollignon** [comment]
Demo by @jtwillis92 - 11.23.21
