### ISSUE TITLE
As an STT data analyst, I want to select/define which type of file I am submitting

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1112]
**Description:**
SSP users will submit 
- active data
- closed data
- aggregate data
- sample data

_Provide a brief background and justification for this issue_
Prior to uploading a file for parsing, data analysts must select the data type (TANF, SSP, Tribal TANF). 

Tribes must use Tribal TANF and no other STT will use this type so this is a default -- tribal data analysts will not have a dropdown.

There are current 22 states which *may* submit SSP data and these are the primary use-case for this ticket as they also sometimes submit straight TANF data. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Relevant SSP users receive the prompt for a required dropdown for content type 
- [ ] Tribal and TANF-only users do not see a dropdown
- [ ] Uploaded data file is tagged with content type metadata
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [ ] If STT is categorically tribal, force content type to be Tribal TANF
- [ ] If user's STT is approved to submit SSP data, allow them choice on choosing TANF or SSP
- [ ] If user's STT may not submit SSP, force content type to be TANF
- [ ] Include content type as part of file's metadata
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
@ADPennington Is there a list of the 22 STTs that use SSP data for supporting doc?

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- If SSP submission allowance is requested externally, how will TDP be kept up to date?
- Do we need separate frontend and backend tickets?

**Comment by ADPennington** [comment]
@abottoms-coder On the STTs.json file, there is an indicator called SSP which = 1 for any STT that submits SSP data. currently there are 16. This could change over time. 

On the same file, there is an indicator called Sample which = 1 for any STT that submits sample data. there are currently 22. this could also change over time.

**Comment by andrew-jameson** [comment]
@reitermb Is there duplication in this ticket vs #1757 ?

**Comment by stevenino** [comment]
Duplicate of #1755
