### ISSUE TITLE
Tribal TANF Active Data (01) File Parsing - As a data analyst, I want my data files to be parsed so that my submission can be validated/accepted by TDP

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1114]
**Description:**
_Provide a brief background and justification for this issue_
Upon file upload, we expect TDP to attempt parsing per the spec outlined:
https://www.acf.hhs.gov/sites/default/files/documents/ofa/tribal_layout_for_section1.pdf

[Tribal TANF workbook](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BE2AC0A70-95B2-4887-95C0-3F9B17C46CEB%7D&file=TDP_Validation_TribalTANF_Section1.xlsx&action=default&mobileredirect=true)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Data File parsing logic is in place such that data file submission can be completed by user and parsed by system for full submission once errors are resolved.
- [ ] Data Errors tell user specifically where in the file they occur, and therefore what exactly needs to be fixed in order for the submission to be complete
- [ ] TDP gives the user all data errors for a submission in a way they can easily save or export so they can take the issues back to their case management software and fix the issues then recreate an export for resubmission to TDP.
- [ ] Data Errors must be issued in human readable plain language so that an English speaker can easily understand what is needed. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [ ] Ensuring file content type is tribal TANF. 
- [ ] Correctly formatted input data can be built into a Python data structure
- [ ] Completed Python data structure can be translated to database model(s)
- [ ] Incorrectly formatted data is identified and mistake(s) are logged.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by lfrohlich** [comment]
@Smithh-Co can we retool this for parsing after SSP?

**Comment by Smithh-Co** [comment]
> 

Hey @lfrohlich , confirming we have this slotted to be pulled following SSP (Parsing and Validation) and will refresh it prior to pick up in BL and dev review.

**Comment by ADPennington** [comment]
@elipe17 tribal tanf section 1 workbook is ready. please note a few things to look out for:

- the expected record length for tribal tanf section 1 record types (T1, T2, T3) is 123. for tanf it is 156, so this is something that will need to be accounted for here. 
- variable names are slightly different for some T2 records.
- also, range of possible values may also differ for elements that are common for TANF and Tribal TANF (e.g. work participation status).
