### ISSUE TITLE
Tribal TANF Aggregate Data (03) File Parsing - As a data analyst, I want my data files to be parsed so that my submission can be validated/accepted by TDP

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1116]
**Description:**
_Provide a brief background and justification for this issue_
Upon file upload, we expect TDP to attempt parsing per the spec outlined:
https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_report_section3.pdf

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Allow Tribes to submit Closed Data based on the TANF data parsing spec
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [ ] Ensuring file content type is tribal TANF. 
- [ ] Correctly formatted input data can be built into a Python data structure
- [ ] Completed Python data structure can be translated to database model(s)
- [ ] Incorrectly formatted data is identified and mistake(s) are logged.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
This is the same as TANF section 3. 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
