### ISSUE TITLE
As a dev, I need to store my parsing log (TANF Section 1)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1121]
**Description:**
As the input is being parsed, we need a standardized way to log.

**Acceptance Criteria:** 

- [x] The parser's output data must be linked to the input file and user in Django Admin Console
- [x] The output data should be transformed to a flat csv file
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Create a modular and reusable message format template which includes: line no., column no., input file reference, error type (out of range, pre-parsing, etc.), item number, and field name
- [x] Save the error output to a new model's JSON-blob field
- [x] Create a function to transform JSON data to csv file
- [ ] Update relevant foreign keys/links via User, STT, and DataFile models such that the error log output is easily accessible and retrievable
- [ ] Enhance the codebase from #132 to utilize the msg template and linking
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**

https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_fatal_edits_sections_1_and_4.pdf
https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_warning_edits_section_1.pdf
https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_warning_fatal_edits_sections_2_3.pdf
https://hackmd.io/J9mD0jeUSVm3QgJucSo5_g

**Open Questions:**

**Comment by andrew-jameson** [comment]
Need to rewrite this ticket, will likely not be initially storing as a flat file but will store as JSON database field and perhaps convert to flat file when user wants to see/download errors.

**Comment by raftmsohani** [comment]
Decided to add a parsing error model to keep track of errors instead of simple message. This ensures we can recreate error message format later as needed
