### ISSUE TITLE
As a data analyst, I can see the validation errors for a file so that I can remedy them (TANF Section 1)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1122]
**Description:**
_Provide a brief background and justification for this issue_
After parsing of an input file, the user needs a feedback loop to correct their file for resubmission vis a vis #84. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_
- [x] Users can access a link to the error report for a specific file submission once validated
- [x] Users see a message "Currently Unavailable" when no error report yet exists per @reitermb 
- [x] Data analysts can view parser output csv file for an already-uploaded file
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [x] Creation of new column: "Error Reports"
- [x] From the data files search page, users have a link to the parser's output file for relevant section(s)
- [x] Create the frontend function/component for querying/testing this API
- [x] Populate Error Report link in column from metadata of the respective filename (e.g. `2023-Q4-Active.xlsx`)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
![Screenshot 2023-03-02 at 9 42 54 AM](https://user-images.githubusercontent.com/84722778/222460799-a145744d-f403-44ad-94bb-5b4267a299fc.png)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- How are the backend messages from the previous tickets transformed into user-facing messaging? Do we have a database lookup of error codes to user-facing messages?
- No lookup table is required. Backend messages will be the same as the user facing messages (plain english messages).

**Comment by stevenino** [comment]
Requires additional UX design. Need tix.

**Comment by stevenino** [comment]
Requires UX research for report format. Tix is still pending.

**Comment by andrew-jameson** [comment]
^^ Added as blocker because when we add this column in submission history we need the frontend function to be able to generate/download that error report.
