### ISSUE TITLE
SPIKE: Find anything that needs to be renamed or refactored for consistency in Data Files code

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1132]
**Description:**
As mentioned in https://github.com/raft-tech/tanf-app/issues/755 we still need to update the backend to rename `ReportFile` and associated code to `DataFile`. However, this also needs to be done for the frontend code and as found in #1061 there are a number of inconsistencies between the frontend and the backend. This ticket serves the purpose to identify everything that needs to be refactored or renamed across the frontend and backend so that we can accurately determine scope of work in renaming.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] We have a complete list of everything that needs to be refactored or renamed in the frontend and backend
- [ ] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Investigate all code relating to the Data Files and identify a list of what needs to be renamed and/or refactored.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by riatzukiza** [comment]
Not sure where to place this now, there won't be a pr for this, if this comment is good enough. Let me know @abottoms-coder how I should proceed

**Comment by abottoms-coder** [comment]
My apologies that this has slipped through the cracks -- I missed the tag. @riatzukiza , I'd like if you could provide an exhaustive list of the filenames and potentially line numbers if the file is rather long. When done, please assign this ticket to me and I'll create a new ticket for actually refactoring to follow-on to this spike.

**Comment by riatzukiza** [comment]
```
tdrs-frontend/src/index.scss 1
tdrs-frontend/src/mirage.data.js 1
tdrs-frontend/src/mirage.js 6
7,18,37,38,41
tdrs-frontend/src/actions/reports.test.js 2

tdrs-frontend/src/components/FileUpload.jsx 2

tdrs-frontend/src/components/Reports/index.js 3
tdrs-frontend/src/components/Reports/Reports.jsx 10
12,18,23,24,25,26,28,29,284
tdrs-frontend/src/components/Reports/Reports.test.js 26
7,8,10,12,88,106,133,142,146,171,174,175,184,199,202,203,212,238,239,248,265,266,277,311,376

tdrs-frontend/src/components/Routes/Routes.jsx 3
tdrs-frontend/src/components/Routes/Routes.test.js 3

tdrs-frontend/src/components/UploadReport/UploadReport.jsx 6
9,11,15-19
tdrs-frontend/src/components/UploadReport/UploadReport.test.js 2

tdrs-frontend/src/reducers/index.js 3
tdrs-frontend/src/reducers/reports.js 3
tdrs-frontend/src/reducers/reports.test.js 3
```

**Comment by riatzukiza** [comment]
<img width="526" alt="Screen Shot 2021-11-12 at 2 14 36 PM" src="https://user-images.githubusercontent.com/10676925/141522635-e0685df7-b468-4a89-964f-f70aeae74c1a.png">

**Comment by abottoms-coder** [comment]
#1438 created to implement findings in this ticket.
