### ISSUE TITLE
[Backend] Accept AMS OpenId

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1136]
**Description:**
_Provide a brief background and justification for this issue_
Backend is currently setup for Login.gov including environment variables and fields in the return payload and these will need to be adjusted in a abstracted way to allow our use of ACF's AMS. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Authentication and Authorization can pass through successfully using AMS.
- [ ] User's request is redirected back to our frontend
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Abstract environment variables, JWT, and payload items to authentication source
- [x] Refactor authentication API functions in tdpservice/users/api for multiple sources
- [x] Ensure all transactions and relevant data events are logged to the server.
- [x] Write new tests for AMS authentication
- [x] Implement new OpenID requests for users who choose AMS
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- We will likely have to add significant rework to testing.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
Please see parent epic.

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by lfrohlich** [comment]
from @ADPennington want to confirm that we'll get comparable information in the user profile for acf and non-acf users. cc: @abottoms-coder

**Comment by lfrohlich** [comment]
> from @ADPennington want to confirm that we'll get comparable information in the user profile for acf and non-acf users. cc: @abottoms-coder

(via OneNote) 
o	AB – The current data points we have for a user from the authentication source are typically only first, last, e-mail, and unique token. Only once inside the app will we be able to assign an STT. Other possible data pieces we can get from openid providers for example are phone number, address, birthday, gender, website, etc... but what exactly do we *need* for a profile? I would venture a guess that TDP won't utilize that.
o	AM – Lets use the common denominator that requires the least amount of user info and leverages the standards set forth by the integration provider. Which is also to say that I assume there is a pattern established by the ACF/ Login.gov/NextGen. Will we have to build this validation or is it out of the box with the solution.

**Comment by jorgegonzalez** [comment]
We are currently working through some issues in the outgoing login request payload to AMS which may need review from OCIO. We will be providing a request metadata shortly so that it may be attempted to be debugged on their side.

**Comment by jorgegonzalez** [comment]
During our 1136 Tabletop today, we discovered some encoding issues with parts of the payload as well as a missing trailing slash in the redirect URI in some requests. We worked past those issues and were able to make a connection from our login page to the HHS page for the first time. These most recent updates are committed to #1369

<img width="1046" alt="Screen Shot 2021-11-23 at 6 10 52 PM" src="https://user-images.githubusercontent.com/12901172/143143357-0a73310a-73d7-445a-819a-a42e5bdbf288.png">
 
<img width="1233" alt="Screen Shot 2021-11-23 at 6 11 12 PM" src="https://user-images.githubusercontent.com/12901172/143143368-c2615bfd-d8ad-4ea1-adeb-8f53affee199.png">

**Comment by valcollignon** [comment]
@abottoms-coder and @riatzukiza to work on the tests and @jorgegonzalez to work on the flow. Continuing work into the next sprint.

**Comment by abottoms-coder** [comment]
Removing some assigned sprints from Sept -- the gun was jumped here as the ticket was not yet fully refined and sprint automation got the better of us.

**Comment by ADPennington** [comment]
just documenting for the record that we connected with acf ocio today and they noted that they would follow-up this week re: `hhs_id` request. cc: @jorgegonzalez

**Comment by jorgegonzalez** [comment]
I spoke with Leonid; he explained that their SSO is currently talking to another IDP that then talks to AMS, and that middleman IDP does not pass the `hhs_id` through. Therefore we will not be able to authenticate with the `hhs_id` until we make the switch to using AMS directly (which Leonid suggested could be after February). So for the time being we will continue using the `email` received from AMS for auth, although I'd like to keep the `hhs` logic and stuff in place to be ready for the switch @abottoms-coder . The only lingering risk of using `email` is the rare case of a user's email changing externally in AMS and not being able to auth into TDRS. Given our current user count of 0, I don't think this is much of a concern at the moment.

**Comment by valcollignon** [comment]
Almost complete. Pending testing. Would like to get in review before holidays, per sprint planning/backlog 12.21.
CC: @jorgegonzalez @abottoms-coder

**Comment by valcollignon** [comment]
Demo by @abottoms-coder, @jorgegonzalez, and @ADPennington - 1.18.22
