### ISSUE TITLE
Rewrite frontend Enzyme tests with React Testing Library

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1141]
**Description:**

Dependabot opened a PR (https://github.com/raft-tech/TANF-app/pull/1139) to update `react-dom` that brought up an issue. Currently we are using two testing frameworks on the frontend, React Testing Libary, and Enzyme. In trying to update our React dependencies, all Enzyme tests in the app will break as Enzyme does not support React 17.

[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) is better supported and more lightweight than Enzyme. All existing Enzyme tests should be re-written with React Testing Library, and it should be removed as a dependency. This should not be as monumental as it sounds as the Enzyme and RTL APIs are quite similar.

**Acceptance Criteria:** 

- [ ] All existing frontend tests that depend on Enzyme are re-written with React Testing Library
- [ ] Enzyme is no longer a dependency is `package.json` and `yarn.lock`
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Go through frontend application and rewrite tests that use Enzyme
- [ ] `yarn remove enzyme` and related packages
- [ ] Ensure tests pass in CI
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by valcollignon** [comment]
low priority per @jorgegonzalez at backlog refinement 12.21.21.

**Comment by robgendron** [comment]
@andrew-jameson and I deemed no longer needed, not aligned with the roadmap.
