### ISSUE TITLE
Django Admin: CORS errors loading fonts from S3

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1143]
**Description:**
Following the merge of #1123 Django Admin staticfiles will be correctly generated and placed into the relevant S3 bucket for the `tdp-staticfiles-{env}` service. However, there are some CORS errors still present which impact the loading of the appropriate fonts as seen below:
![Screenshot from 2021-07-22 16-56-51](https://user-images.githubusercontent.com/22626085/126715892-4f3add68-d826-4ada-8a22-927ef7b2f553.png)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Fonts load correctly with no CORS errors
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] confirm that this is still an issue (updated 12/9/21)
- [ ] Resolve CORS errors when loading fonts in the Django Admin for deployed sites
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by ADPennington** [comment]
updated tasks to first confirm that this is still an issue.

**Comment by jorgegonzalez** [comment]
This is an easy fix in django-admin-508 related to the loading of those remote fonts; going to have it use the set of default browser fonts, tracking here: https://github.com/raft-tech/django-admin-508/issues/2

**Comment by valcollignon** [comment]
Demo by @jorgegonzalez - 12.21.21
