### ISSUE TITLE
As a data prepper, I want to evaluate conceptual mockups (v.1) simulating TANF report metadata input

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#115]
**Description:** 

Evaluate how grantees react to a concept prototype(s) simulating TANF report metadata input . To do so, we will create wireframes for evaluative testing during Round 3 of the user research with STTs. 

**What will not be done in this issue**:

Formal mockups will not be created as deliverables for Dev team and may not meet all of the USWDS guidelines. 

**Note**

These mockups will be further explored after #170 (conversation guide) is complete in future sprints.
These mockups will be finalized after interviews are completed with STTs in future sprints.

**AC:** 

- [x] Wireframes are created and reviewed 
- [x] This is a artifact that can be shared for user research conversations
- [x] Follow on issues are spun up, incorporated into research goals, interview protocol

**Tasks:** 

- [x] Review what is known about report creation
- [x] Mockup layout 
- [x] Review layout with Dev for any functionality issues and update mockup as appropriate (focus on functionality)
- [x] Update mockup per dev review
- [x] Hold a workshop w/ OFA + 18F to review mockup and gather any feedback (Conceptual focus: instead of meeting all of the USWDS guidelines)
- [x] Update mockup per workshop
- [x] Mockups are added to #63

**Supporting Documentation:**

User research findings: 
- STT Spring 2020 ([Link](https://github.com/HHS/TANF-app/wiki/2020,-Spring:-Understanding-the-local-experience))
- OFA Interview Raw Notes ([Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7Bd21147f1-5fb3-472d-9acd-98fe2d7ffdb0%7D&action=view))
- OFA Interview Synthesis ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B588709de-fe1f-49e5-8d52-cbc6e25fa9cd%7D&action=view))

**DoD:**

 - [x] Documentation: Conceptual mockups simulating TANF report creation has been shared with the PO and team for feedback
 - [ ] @cmajel has reviewed and signed off
 - [x] @lfrohlich has reviewed and signed off

**Deliverables:**

Conceptual Mockup 1 (Edit Data within App): ([Link](https://www.figma.com/proto/y15co5xc7MIZXBnWBOF6hJ/Conceptual-Mockups-for-STT-Feedback?node-id=1%3A940&viewport=3235%2C1127%2C1.049489974975586&scaling=min-zoom))
Conceptual Mockup 2 (Edit Data within Flat File): ([Link](https://www.figma.com/proto/y15co5xc7MIZXBnWBOF6hJ/Conceptual-Mockups-for-STT-Feedback?node-id=9%3A332&viewport=914%2C679%2C0.48327112197875977&scaling=min-zoom))

**Comment by dk-ui** [comment]
Just wanted to call out here for increased transparency that: 

- These mockups will be further explored after #170 (conversation guide) is complete in future sprints.
- These mockups will be finalized after interviews are completed with STTs in future sprints.

**Comment by dk-ui** [comment]
Resulting from discussion and feedback on these conceptual mockups, additional design iterations were created #295, further questioning TDP functionality. These iterations will be revisited in later sprints.

**Comment by cmajel** [comment]
@dk-ui this is looking good and I think is ready for demo. It'll be good to test this with STTs 

A few notes:
* I agree with Alex's comment about providing an example of what we mean by encrypted SSN. It's not clear to me what we mean here so it'll be good to clarify. 
* The only field I see missing from [the header layout](https://www.acf.hhs.gov/sites/default/files/ofa/transmission_file_header_trailer_record.pdf) is the update indicator. s this meant to simulate a new data upload? Do we have thoughts on the other indicators yet?
* Love including the months as helpers with the quarter selector. 
* Minor note on headings. I noted that avoiding abbreviations like "info" will help with readability.

**Comment by cmajel** [comment]
and per this AC:
`This is a artifact that can be shared for user research conversations`

Do y'all have a clickable prototype link that could be shared with a participant? Could you include it in the issue description?

**Comment by dk-ui** [comment]
@cmajel Thank you!! 

Hopefully this will help:

- Didn't show this in the demo but we added an information icon to that field. We were curious on if the user will click on that for more information and if so then we were planning on having the conversation about what additional information would you want to see as a helper.
- Yes, this is a new upload screen. We are planning on doing something different for re-upload.
- Thanks! As per feedback from the demo, we might change the header of this field slightly to indicate calendar year / fiscal year so that users know what kind of information will be in the dropdown before they select it. 
- Changed this (Info to Details), good catch!


AC Question

- Ticket is updated with links to each conceptual mockup

**Comment by lfrohlich** [comment]
I made some comments in the mockups, some of which are also pasted here. 
- I think it would make sense to include the STT name as as part of the table in the Validate File Details screen. In the header above it may be more easily skipped over. Another question related to the metadata summary doc, would the system check the STT (who signed in vs. what the FIPS code shows)?

- Maybe instead of "Data Type" on the first screen it could be "Data Submission"? As we discussed in the mockup walkthrough, it would be great if which they selected determined whether there was a section 4 drop box. 

- I think it would make sense to include the STT name as as part of the table in the Validate File Details screen. In the header above it may be more easily skipped over. Another question related to the metadata summary doc, would the system check the STT (who signed in vs. what the FIPS code shows)?

- Maybe instead of "Data Type" on the first screen it could be "Data Submission"? As we discussed in the mockup walkthrough, it would be great if which they selected determined whether there was a section 4 drop box. 

Q for Alex -- do we care about the encrypted indicator because it means the system would need to decrypt (which the Tim prototype did)? I agree this could be confusing and people may mark it as encrypted when it really isn't, but this will be good to explore in the interviews and to better understand the purpose of the indicator.

**Comment by ADPennington** [comment]
Re: encryption indicator--yes that's why. If any STTs are still using FTANF, their SSNs will be encrypted. Since Tim already de-coded, I wonder if TDP can automatically check for this and do the decryption. that might be a way around asking/confusing STTs.

**Comment by lfrohlich** [comment]
This was completed in Sprint 4 #58
