### ISSUE TITLE
[Frontend] Remove upper "Sign In" link

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1152]
**Description:**
_Provide a brief background and justification for this issue_
We should remove the upper sign-in link and solely focus users on the primary sign-in options.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_
- [ ] Users must use center-screen login buttons
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Remove sign-in link from main page
- [ ] Remove sign-in link from relevant front-end tests
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
![image.png](https://images.zenhubusercontent.com/60abc3a8916bb9149afff73e/b2a81c20-1e20-48f6-b091-473a40d3ea77)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by jtwillis92** [comment]
The button that is intended to be removed is currently the only one that works due to: https://github.com/raft-tech/TANF-app/issues/1257

We should either fix that issue first or at the same time as this one.
