### ISSUE TITLE
As technical lead, we need to accept NextGen OpenId responses

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1154]
**Description:**
_Provide a brief background and justification for this issue_
Backend is currently setup for Login.gov including environment variables and fields in the return payload and these will need to be adjusted in a abstracted way to allow our use of NextGenXMS

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Authentication and Authorization can pass through successfully using NextGen's sandbox.
- [ ] Application can handle and parse inbound response from NextGen XMS on `/v1/loginXMS/` route
- [ ] Both existing and first-time users can utilize NextGenXMS
- [ ] Code must pass all checks from #1558 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create XMS structure with associated environment variables, JWT, payload items, etc. like in #1136
- [ ] Implement redirect class(es) and route(s) for NextGen XMS responses
- [ ] Implement functions to decode, validate, and parse openid payload
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- While code is one aspect of this ticket, we will be tracking NextGen XMS administration/configuration in a follow-on ticket

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- Please reference parent epic for documentation links.
- https://openid.net/specs/openid-connect-basic-1_0-32.html Sec 2.1.6.1

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by stevenino** [comment]
Blocked until we can meet with NexGen XMS team on 5/12
