### ISSUE TITLE
As OFA staff, when I login with NextGen XMS, I am redirected to use ACF AMS

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1155]
**Description:**
_Provide a brief background and justification for this issue_
Non-Data Analyst roles (OFA staff) should not be allowed to utilize NextGen XMS and should be informed that their authentication source selection was incorrect and that they must use ACF AMS.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] OFA-staff user is not actually authenticated by XMS (not able to browse/utilize TDP)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Redirect user to ACF AMS login
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Consider adding UX elements - visual design and text - for error messages here for those how try, but do not qualify for ACF/AMS login.A couple of good resources on error message design and content best practices

https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4
https://uxdesign.cc/creating-error-messages-best-practice-in-ux-design-cda3be0f5e16

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Do we redirect them to ACF AMS right away to login a second time or pause and tell them why they're being redirected? Yes they are redirected
  - The redirect right away is the preferred behavior but does this introduce an accessibility issue? No accessibility issue
- Can we pass message to frontend on why authentication failed for the role-based failure case? N/A

**Comment by lfrohlich** [comment]
from @ADPennington : o	#1155 is related to #1135. seems like the ACs and tasks need to be consistent since acf users only have one option?  cc: @abottoms-coder

**Comment by sreedevip** [comment]
Adding UX error messaging notes as per @ADPennington's recommendation to my suggestion on MM

**Comment by stevenino** [comment]
Not technically required for v1.0

**Comment by stevenino** [comment]
Will not integrate with NexGen XMS
