### ISSUE TITLE
As a dev, I need a testable NextGen XMS sandbox

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1156]
**Description:**
_Provide a brief background and justification for this issue_
Work with their support team to setup and configure a sandbox so we can implement backend authentication.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] We have a unique sandbox for our application testing
- [ ] Test user accounts can go through full authentication flow
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Perform basic tests via curl/bash to ensure it operates per their documentation
- [x] Make sure NextGenXMS has a firewall rule which allows our requests to go through either locally and/or from cloud.gov endpoints
- [ ] Add comments to this ticket with request:responses/payload dictionaries from their endpoint(s)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- [ ] This likely will not yield a pull request but is groundwork for later tickets.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
- Please reference parent epic documentation sources.

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Will this be accessible from Cloud.gov, CircleCI, locally?

**Comment by ADPennington** [comment]
3/1 update: confirmed that the lower environments are available so we can proceed with this ticket when `dev` is ready. cc: @abottoms-coder

**Comment by abottoms-coder** [comment]
Solved in #1561
