### ISSUE TITLE
As OFA Technical Lead, I need Nextgen XMS user flows configured

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1157]
**Description:**
_Provide a brief background and justification for this issue_
After completion of #1156 and #1154 we must remember to switch to their production server url(s) as well as ensure configurations support our required approval processes. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] TDP not longer directs use to a sandbox authentication service
- [ ] New users can request to be able to login to TDP but this will need approvals
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update any references for XMS sandbox to utilize production
- [ ] Work with their support team to ensure we have production properly configured for user flows
- [ ] Ensure configurations and user flows are well documented
- [ ] Ensure existing tests can still hit sandbox
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- See parent epic for documentation

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- What configuration do we need to make the switch to production for user request flows?
- Can XMS be configured for pass-through so we can avoid any sort of administrative user flow?

**Comment by lfrohlich** [comment]
from @ADPennington  should this be specific to nextgen? we need to move out of sandboxes regardless?  also user flows probably need to be figured out as a fast follow after we choose whether or not to adopt nextgen. cc: @abottoms-coder

**Comment by stevenino** [comment]
No longer required per backlog refinement on 2/29/22
