### ISSUE TITLE
Resolve Cache Control header error by ZAP

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1165]
**Description:**
One new [issue](https://9055-281707402-gh.circle-artifacts.com/0/tdrs-frontend/reports/owasp_report.html#10015) that can be addressed as part of a follow-up ticket, if needed. we weren't able to see this before since we weren't scanning against deployed site. 

**NOTE: This does trigger on both frontend and backend.**

Description in case link becomes invalid:
```
Low
	Incomplete or No Cache-control Header Set
Description 	
The cache-control header has not been set properly or is missing, allowing the browser and proxies to cache content.
URL 	https://tdp-frontend-staging.app.cloud.gov/
Method 	GET
Parameter 	Cache-Control
Attack 	
Evidence 	
URL 	https://tdp-frontend-staging.app.cloud.gov/manifest.json
Method 	GET
Parameter 	Cache-Control
Attack 	
Evidence 	
Instances 	2
Solution 	
Whenever possible ensure the cache-control HTTP header is set with no-cache, no-store, must-revalidate.
Reference 	https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#web-content-caching
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
CWE Id 	525
WASC Id 	13
Plugin Id 	10015
```

**Acceptance Criteria:** 

- [x] Zap report no longer features this error.
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Set cache header as outlined in the ZAP result.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
demo by @jtwillis92 12.7.21
