### ISSUE TITLE
(Sprint 27) UX Research Support & Comms

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#1166]
**Description:**
(Sprint 27) Continued Focus on PreParsing Errors + UX for Access Request Workflow items

**AC:**
PO, Gov Tech Lead, PM, and Research and Design Team use the roadmap to agree on the actionable insights of the prior research round and also agree on the goals, outputs, and research methods that we will incorporate into the roadmap. 
Next Sprint related tickets/epics are ready for backlog refinement. 

**DoD:**
- [x] presentation of synthesis, research plan, live comms presentation, and tickets
- [x] PM/PO have reviewed findings and user stories proposed or additional are added into the roadmap/backlog as actionable tickets by @amilash  and @lfrohlich 
- [x] @lfrohlich sign off

**Deliverables**
Round 7 - PreParsing Errors Research Synthesis Board: [Link](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1629404764806/8081a78f0c82a6632027c8e9a1a7d43a7a457908?sender=mreiter1745)
Round 7 PreParsing Errors Research Synthesis summary in docs: [Link](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/2021%2C%20Summer%20-%20Communicating%20Errors%20in%20TDP%20%26%20Validations%20With%20Regional%20Staff.md)
Research Plan Workshop Board: [Link](https://app.mural.co/t/raft2792/m/raft2792/1625686926916/9f6413882a991d025bc7c68b884726798f379f15?sender=dknapp0725) 
Live Comms Presentation: [Link](https://hhsgov.sharepoint.com/:b:/r/sites/TANFDataPortalOFA/Shared%20Documents/Design/STT%20Comms/TDRS_STT%20Comms%20Aug%2016%20Draft%202.pdf?csf=1&web=1&e=lbzgJu)

**Comment by lfrohlich** [comment]
I assume under AC it's supposed to be Sprint 28? I added Gov Tech Lead.

**Comment by lfrohlich** [comment]
can we add specific to DOD? e.g. research plan **for next 3 sprints**, and tickets **for next sprint?**

**Comment by amilash** [comment]
@lfrohlich can you clarify your ask. What do you mean "can we add specific to DOD? e.g. research plan for next 3 sprints, and tickets for next sprint?" . We have acceptance criteria and Definition of done- both of which describe what needs to be complete for this to be done.

**Comment by amilash** [comment]
We actually dont need the next three sprints decided. This is a relic from the old planning approach.
