### ISSUE TITLE
[Round 7] Follow-on research sessions to capture Tribe input on error copy

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1177]
**Description:**
Revisits Round 7 content testing with research participants from Tribal TANF programs.

**AC:**
- [ ] Findings are documented (added to Round 7 synthesis document in code docs)
- [ ] Findings are shared with the team
- [ ] Any new user stories are documented in future error-related tickets or the research roadmap

**Tasks:**

- [ ] Update round 7 synthesis
- [ ] Recruit participants for tribes
- [ ] Facilitate research synthesis workshop to align on next step validations
- [ ] Create a round Synthesis in [Hack MD](https://hackmd.io/@mreiter/B1Q1RE3eY) documenting the actionable insights from the prior Research Round
- [ ] Update research roadmap as needed
- [ ] Create/Refine tickets for accepted stories/future research (combo of updates to research roadmap and TDP <UX :: Product> PreParsing Errors meeting

**Deliverables:**
- [Round synthesis doc draft]()
- [Updated round synthesis doc](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/2021%2C%20Summer%20-%20Communicating%20Errors%20in%20TDP%20%26%20Validations%20With%20Regional%20Staff.md)
- [Synthesis board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1629404764806/8081a78f0c82a6632027c8e9a1a7d43a7a457908?sender=mreiter1745)

**DoD:**
- @lfrohlich has reviewed & signed off

**Comment by stevenino** [comment]
Closed as not required per backlog refinement on 7/19/22
