### ISSUE TITLE
Codecov: Frontend uploads fail to find coverage report

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1191]
**Description:**
Following #1149 there is an uncaught error performing the frontend upload of the testing coverage report to Codecov:
```
Codecov report uploader 0.1.0
[2021-08-02T20:56:13.323Z] ['info'] => Project root located at: /home/circleci/tdp-apps
[2021-08-02T20:56:13.324Z] ['info'] ->  Token set by arguments
[2021-08-02T20:56:13.341Z] ['info'] Processing ./tdrs-frontend/coverage/lcof.info...
[2021-08-02T20:56:13.342Z] ['error'] There was an error reading the coverage file: Error: ENOENT: no such file or directory, open './tdrs-frontend/coverage/lcof.info'
[2021-08-02T20:56:13.342Z] ['info'] Could not read coverage file (./tdrs-frontend/coverage/lcof.info): Error: There was an error reading the coverage file: Error: ENOENT: no such file or directory, open './tdrs-frontend/coverage/lcof.info'
[2021-08-02T20:56:13.344Z] ['info'] Detected CircleCI as the CI provider.
[2021-08-02T20:56:13.344Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=uploader-0.1.0&token=*******&branch=backend/970-django-settings-cg-envs&build=9196&build_url=&commit=b55015d230567b844d7eb924bb28e438080cca60&job=0&pr=&service=circleci&slug=raft-tech/TANF-app&name=&tag=&flags=dev-frontend&parent=
[2021-08-02T20:56:13.777Z] ['info'] Uploading...
[2021-08-02T20:56:13.897Z] ['info'] {"status":"success","resultURL":"https://codecov.io/github/raft-tech/TANF-app/commit/b55015d230567b844d7eb924bb28e438080cca60"}
```

Furthermore, this error does not cause a non-zero exit code to be returned to Circle CI so the step does not register as failed when it should.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Coverage reports for the frontend are uploaded to Codecov for every new commit
- [ ] Errors uploading the coverage report should cause a CI failure
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update the `test-frontend` invocation of `upload-codecov` such that the coverage report can be found by the uploader
- [ ] Update the `upload-codecov` command to return a non-zero exit code if there is an error during the upload
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- There are no evident issues on the backend, so this may just be an incorrect path passed for the frontend report.

**Supporting Documentation:**

**Open Questions:**

**Comment by jtwillis92** [comment]
@amilash @abottoms-coder this would be a good candidate for the next sprint. We're currently not getting any coverage reports in Codecov for the frontend.

**Comment by amilash** [comment]
Thanks @jtwillis92 I'll pull it into next sprint backlog.
