### ISSUE TITLE
Set CSP Header for Backend

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1192]
**Description:**
_Provide a brief background and justification for this issue_
This is a follow-on for #907 as we discovered OWASP was alerting on the backend as well but as the investigation was non-trivial, we wanted to move further troubleshooting of that solution to this separate ticket.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] OWASP scan no longer alerts on http://web:8080
- [x] No significant overhaul to codebase 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate CSPMiddleware not setting header values
- [ ] Ensure CSP Headers are set correctly
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- We can also inspect locally by running a curl command to fetch headers.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [This](https://django-csp.readthedocs.io/en/latest/installation.html) is the current solution we are using.

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
