### ISSUE TITLE
Round 7 PreParsing Errors Research Synthesis

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1193]
**Description:**
Delivers updates to research documentation and loops in team to key findings.

**AC:**
- [x] PR is opened to raft-tech for round synthesis
- [x] Team is synced on round findings
- [x] PO/PM has accepted user stories from this work and they are input to the roadmap/backlog ticket(s)

**Tasks:**
- [x] Add each top-line synthesis from the past 3 sprints to the research synthesis workshop template
- [x] Schedule synthesis workshop
- [x] Facilitate research synthesis workshop to align on next step validations
- [x] Create a round Synthesis in [Hack MD](https://hackmd.io/@mreiter/B1Q1RE3eY) documenting the actionable insights from the prior Research Round
- [x] Update research roadmap as needed
- [x] Create/Refine tickets for accepted stories/future research (combo of updates to research roadmap and TDP <UX :: Product> PreParsing Errors meeting

**Deliverables:**
- [Round synthesis doc draft](https://hackmd.io/@mreiter/B1Q1RE3eY)
- [Round synthesis final docs](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/2021%2C%20Summer%20-%20Communicating%20Errors%20in%20TDP%20%26%20Validations%20With%20Regional%20Staff.md)
- [Synthesis board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1629404764806/8081a78f0c82a6632027c8e9a1a7d43a7a457908?sender=mreiter1745)

**DoD:**
- @lfrohlich has reviewed & signed off

**Comment by lfrohlich** [comment]
Should updating the roadmap and creating tickets be tasks as part of this ticket/
/

**Comment by reitermb** [comment]
> Should updating the roadmap and creating tickets be tasks as part of this ticket/
> /

Added! We'd captured that to a degree in the enhancements to docs ticket, but I like having it specified here too to reflect the potential for specific research impacting the roadmap (and future research) in various ways!

**Comment by amilash** [comment]
Remaining estimate sprint 28: 2

**Comment by lfrohlich** [comment]
@reitermb I don't see the synthesis doc hack.md link -- can you share and add above? Thanks!

**Comment by reitermb** [comment]
> @reitermb can you add the doc link above and to #166?

#1066? Sure thing, both should be updated now! Noting that there are minor differences between the hackmd docs and the final ones that have been merged into code docs. Fixes to get linking working properly within GitHub/embed images, etc...

**Comment by lfrohlich** [comment]
Yes, #1066. Thanks!
