### ISSUE TITLE
Round 7 PreParsing Errors Live Comms w/ Regional Staff

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1194]
**Description:**
Delivers updates to ROs encompassing research findings from Round 7 and relevant project updates.  Scheduled for 8/16/21

**AC:**
- [x] Live comms complete
- [x] Recording / presentation artifact emailed to ROs

**Tasks:**
- [x] Create a presentation that can be sent to OFA RO staff (include research synthesis link to github)
- [x] Ensure that format of presentation is 508 accessible
- [x] (Lauren) Schedule meeting for live communications
- [x] Conduct presentation with stakeholders
- [x] Lauren will send presentation recording and presentation link to ROs

**DoD:**
- [x] @lfrohlich sign off

**Deliverables:**
- [x] [Presentation artifact](https://github.com/raft-tech/TANF-app/files/7001839/TDRS.Project.Update.Aug.16.2021.pdf)
- [x] [Live comms recording]()

**Comment by lfrohlich** [comment]
Do we think there is enough to also share with grantees at this time? e.g. by creating an alternative, shareable version for STT?

**Comment by reitermb** [comment]
[TDRS Project Update Aug 16 2021.pdf](https://github.com/raft-tech/TANF-app/files/7001839/TDRS.Project.Update.Aug.16.2021.pdf)

**Comment by reitermb** [comment]
[TDRS Project Update Aug 16 2021.pdf](https://github.com/raft-tech/TANF-app/files/7009971/TDRS.Project.Update.Aug.16.2021.pdf)

Version with slide 12 fixed (to capture it here too)
