### ISSUE TITLE
Research Docs readme & misc documentation enhancements

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1195]
**Description:**
Delivers ease of use/readability improvements to research code docs and supports design team changes. 

**AC:**
- [x] PR is opened to raft-tech adding a README to the User Research folder of code docs
- [x] Mural board list exists in a shared place

**Tasks:**
- [x] Draft a [hack.md](https://hackmd.io/@mreiter/rksVBWjgK) README for ticket feedback purposes
- [x] Miles / Dmitri pair to align on and document ideas relevant to future research, features, other project context we don't want to lose
- [x] Update research roadmap methods and research questions for pertinent research epics
- [x] Create TOC- Need a Table of Contents page in OFA One Note and in ReadMe docs that says where all the mural + figma links and project research design docs are that are titled and dated so both internal teams can find it and repo readers can know where things are and easily find them.
- [x] Open PR for README

**DoD:**
- [x] @lfrohlich + @amilash sign off

**Deliverables**
- [User Research README](https://github.com/HHS/TANF-app/tree/main/docs/User-Research)
- [Updated Research Roadmap](https://app.mural.co/t/raft2792/m/raft2792/1627058877512/7514d3617f4bc241d3f70ff6e61253e1ce09f880?sender=mreiter1745)

Estimate Remaining Sp 28:5

**Comment by lfrohlich** [comment]
Can you explain task #4 more?

**Comment by reitermb** [comment]
> Can you explain task #4 more?

It essentially amounts to making sure Dmitri and I capture as much as we can of our shared project context before he rolls off. Ideas we've put a pin in for future research, feature ideas, etc... Capturing that in methods/research questions/how might we's on the roadmap wherever it's still relevant. Kind of a mental research backlog refinement.

**Comment by amilash** [comment]
Adding criteria that didn't get capture from my closed duplicate ticket. 
- Need a Table of Contents page in OFA One Note and ideally in ReadMe docs that says where all the mural  + figma links and project research design docs are that are titled and dated so both internal teams can find it and repo readers can know where things are and easily find them.

**Comment by lfrohlich** [comment]
@reitermb do you still plan to add a TOC?

**Comment by reitermb** [comment]
@lfrohlich links should be updated! GitHub > OneNote is a smooth transfer so I ended up copying over the whole readme rather than just the Mural Links—let me know if you'd like me to shave it down at all in OneNote!
