### ISSUE TITLE
Update/Create Target and Aspirational State Journey Maps Based on New Research and Roadmap Discovery

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#1196]
**Description**
Delivers updated journey maps to the main journey map Mural board to encompass Round 6 and 7 findings and add useful context from research roadmap discussions

**AC:**
- [x] Journey maps in Mural are updated/expanded

**Tasks:**
- [x] Update target state and aspirational state maps based on any applicable research discoveries from rounds 6 and 7—particular focus on updating now-validated Regional Staff journey maps

**DoD:** 
- [x] @lfrohlich has reviewed and signed off

**Deliverables:**
- [x] [Journey maps in Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1608238114372/191c53b8ef538838bc8c179daa238dd5c5dcc9e8?sender=mreiter1745) (Bottom half of the board with the reference to #1196 is for review)

**Comment by amilash** [comment]
Remaining estimate Sp 28: 1

**Comment by lfrohlich** [comment]
Thanks @reitermb ! These are looking really good. I made some comments in the mural. I like where you're going with the other journey maps too.

**Comment by ADPennington** [comment]
lgtm too @reitermb  made a couple of comments.

**Comment by reitermb** [comment]
@ADPennington @lfrohlich 

For some reason Mural isn't playing nice and letting me reply to the actual comments, but the content should now all be updated accordingly! I got a kick out of our accidental aspirational promotion of Zanthus too 😃

**Comment by lfrohlich** [comment]
Oh I think that's because it's in OFA's murals. Revised content looks good!
