### ISSUE TITLE
[Research Planning] Error Content Testing v3.0

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1197]
**User Story**
As a member of the DIGIT team, I would like to gain insight into how Grantees are interpreting the error content/copy so that I can reduce the turnaround time for troubleshooting errors between Grantee and OFA. 

**Business Value**
Delivers research plan to execute on Section 1 error content testing with a group of STTs

**Tasks:**
- [x] Identify the top 10 most frequent error codes for States and Tribes to inform how we prioritize the research scenarios
- [x] Create a hack.md for research plan drafting
    - [x] A research plan has been created which includes:
    - [x] Background
    - [x] Research goals
    - [x] Research questions
    - [x] Recruitment criteria
    - [x] Recruitment target participants tracker
    - [x] Recruitment/participation email templates
    - [x] Timeline (for recruitment and for research sessions)
    - [x] Ethics, privacy concerns 
- [x] Create a Mural to facilitate the research with participants

**Supporting Documentation:**
- [Research Plan](https://hackmd.io/hFrD2ozgRFW8Bj3YOg4yig?view)
- [Mural for Facilitation](https://app.mural.co/t/raft2792/m/raft2792/1627580788916/eb8315faa575faed34ce1fcaa96cbd2aabb83d58?sender=u3ca60168b5ac4eb17bf92804)

**Comment by valcollignon** [comment]
@reitermb to create description and will bring to next UX backlog refinement to build AC with team
CC: @sreedevip

**Comment by reitermb** [comment]
Note for myself to capture/discuss any pertinent detail from #1177 when we sync on this

**Comment by lilybl1** [comment]
@stevenino @ADPennington - I've got the Research Plan in a place that I think it's worth a discussion before I keep going. Take a look in the story for the supporting links. Thanks!

**Comment by lilybl1** [comment]
@stevenino We discussed this in this morning's stand-up - this story is ready for QASP and a new ticket will be created for the work on writing the human-readable error messages. This requires more time with DIGIT as well. I can write that new ticket.

**Comment by stevenino** [comment]
@ADPennington Ready for QASP review

**Comment by ADPennington** [comment]
@lilybl1 this looks really good. I left some questions in the hackmd:

- does the timeline need to be updated?
- do we need to build in time for UX to meet with DIGIT about the error descriptions prior to research?
- how are we planning to incorporate the "header record" errors, if at all? my comments on this offer more background. 

Once we can confirm details on those questions, please tag me again here to sign off. happy to pair if needed.

**Comment by lilybl1** [comment]
@ADPennington Tag. Updated based on our conversation earlier. 

- Updated timeline - I did adjust it based on our currently sprint research synthesis
- Yes, add a line item for DIGIT review - is not meant to be a week long session, but some time during that week
- header - will not be tested in this research session

Thanks!
Diana

**Comment by ADPennington** [comment]
thank you @lilybl1 approved closing as completed. 👍🏾
