### ISSUE TITLE
[Dev-ready Design] In-app presentation of errors (Error Reports Page)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1200]
**Description:**

Design for how specific error reports will be visualized in TDP (in-app version of the downloadable reports. Captures original #1232 notes down in Supporting Documentation.

**Related User Stories:**

—As a [user type] I want the page to exist so that I can see it.—

**Recommended pa11y actions:**

—‘click element #error-report’,—

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] Design how the style guide should be realized in-app on an Error Reports page

**Supporting Documentation:**

Reports Epic:
Goal: V3 will have Parsing built in TDP and we will be able to automate reporting.
We have technical info on the current reports.
This is a research priority, but should be a low lift b/c mostly it will be based on the technical spec which we have, and we will need to create and/or update the (Data Model). Priority is Parity, then enhancements.
Approach: A.) Start with existing reports. Automate them and deliver them VIA TDP in app and via email.
b.) build enhanced reporting capabilities under 'analytics' epic.

Needed from UX/Design: For all User Types:
- [ ] Notional User Flow - of in app automation
- [ ] Reports Dashboard UI
- [ ] Report Notifications (in app + email)
- [ ] Current Reports spec- Technical have this from @ADPennington in the one note documents
- [ ] OFA + STT Report Current Journey Map/ User Flows (process, timing/cadence (and what thats based on - technical or compliance), delivery mechanisms)

+ Aspirational Reporting (See Analytics Epic)-> + Value Adds that support OFA in delivering value to Grantees and for programs. What kind of analytics and insights can we enable for OFA and Grantees once we have (Maybe this is separate an Analytics Epic)

Questions:
1. Do we need to have reporting built into TDP at the same time as production data being submitted?  Or can there be a delay and a stop gap for current reporting methods (analog?)? 
2. Do reports get automated currently or are they coming out of  a different system? 
3. Does Reporting need to be in Release 3 with parsing? or can it be V4? 

- Link to Reports research/specs from Alex in One Note [ ]

**Comment by valcollignon** [comment]
@reitermb to create description and will bring to next UX backlog refinement to build AC with team
CC: @sreedevip

**Comment by reitermb** [comment]
Closing as old after adding note to keep useful historical context in in-app error reports epic
