### ISSUE TITLE
[Dev-ready Design] Grantee program manager team management

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1201]
**Description**
This ticket delivers design spec for an added (optional) step in the user experience for a grantee program manager to enter staff/coworker information that would end up being displayed to regional staff admins to enhance confidence in whether a particular user should in fact be granted TDP access. 

> A shortlist of "pre-approved" users who will be requesting access.

**Notes**

**AC:**
- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks**
- [ ] Evaluate whether we need to collect more than email addresses
- [ ] Write content to accompany UI (e.g. by providing information on your staff you can help us keep the system secured and speed up their approval process)
- [ ] Draft UI in Figma
- [ ] Share for feedback (UX sync stakeholders)

**Deliverables**
- Figma page

**Comment by valcollignon** [comment]
@lfrohlich If this is going to be a later enhancement, should we move this issue back to the product backlog?

**Comment by valcollignon** [comment]
Moving to product backlog since this will be in Release 4.
CC: @reitermb @sreedevip @lfrohlich @ADPennington

**Comment by reitermb** [comment]
Setting this to V3 for the moment given that its counterpart ticket is V3 (#214)

**Comment by reitermb** [comment]
Keeping this one on the backburner. Potentially relevant to future enhancements & TDP admin

**Comment by ADPennington** [comment]
Closed this because this is really old and seems unrelated to FRA-related user management.
