### ISSUE TITLE
[Research-Planning] Interviews Grantee Program Directors to assess in user access request processes

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1202]
**Description:**
Validates the access request flow delivered in #652. Identifies any elements of our notional flow that might be difficult to implement for grantees or falls short of potential practices already in use by other federal programs. 

**Notes:**
This research tests our assumption that our proposed flow represents the best approach to the challenge of adding security and clarity to an access request/approval process where administrators have limited transparency into the makeup of grantee teams. 

>update user flows and user journey
>present notional best practice flow to folks to validate
>ask users if our notional approach maps to their operational model or if we need to add anything based on their ops user journey.

**AC:**
- [ ] A research plan has been created which includes:
    - [ ] Research goals, relevant research questions.
    - [ ] Recruitment criteria & target participants.
    - [ ] Recruitment/participation email templates.
    - [ ] Timeline (for recruitment and for research sessions).
    - [ ] Testable Designs/Content (if applicable).
    - [ ] Ethics, privacy concerns 

**Tasks:**
- [ ] Draft research planning, 
- [ ] Schedule sessions with grantee program directors (recruitment criteria being those who interact with other federal systems such as grants.gov)
- [ ] Schedule sessions with gov stakeholders from other federal-grantee systems (recruitment criteria being those who administer federal systems such as grants.gov or are otherwise familiar with their account/access management policies)
- [ ] Ticket research synthesis/other needed follow-on design tickets

**Supporting Documentation:**
- *---Link to hack.md, Mural, Figma, or other relevant planning documentation---*

**Comment by amilash** [comment]
@reitermb 
This ticket needs an update. We agreed that the approach here should be:
- update user flows and user journey 
- present notional best practice flow to folks to validate
- ask users if our notional approach maps to their operational model or if we need to add anything based on their ops user journey.

**Comment by reitermb** [comment]
Outdated post user onboarding
