### ISSUE TITLE
As a tech lead, I don't want dependabot spam for awscli

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1209]
**Description:**
_Provide a brief background and justification for this issue_
Dependabot is getting spammed by awscli updates so I think we want to relax how quickly we stay up to date. Right now we are updating on patch and we want to update only on minor version.

(e.g.,
M.m.p
Major
minor
patch)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Dependabot only opens PRs on minor version updates for the awscli dependency
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update dependabot config
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
