### ISSUE TITLE
As an STT Data Analyst, I want to know if my file upload had a virus

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1215]
### Description 

TDP scans files for viruses to ensure we don't accept any infected files into S3. Currently the message displayed to the user says "Request failed with status code 400" (see video below) when an infected file is submitted.  This is not an actionable error message for the user.  Instead, we need to tell the user that they have attempted to submit an infected file. 

https://user-images.githubusercontent.com/63075587/175654982-3326777f-1add-4448-8977-d7851cac9ada.mov

### Acceptance Criteria
 - [ ] when a user uploads an infected file, an error message indicating such is displayed

### Tasks
- [ ] update logic to conditionally display infected error message to user if infected file submitted
- [ ] inline error messaging should read "We detected a corrupt file upload. Please review this section and re-submit the data file."
- [ ] error message should appear inline to the section it is referring to

### Design
- See attachment
![1215 - TDP scans files for virus to ensure we don't accept any infected files into S3](https://user-images.githubusercontent.com/104451160/197866240-c3814239-d1a5-4001-a235-67d8a4d038c2.png)

**Comment by reitermb** [comment]
Noted that we have[ patterns for related upload errors,](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4124%3A0) though it sounds like we might need to revisit a few of them for blank file. Does a malicious file need a dedicated message or does the wrong format error work for that (cc @ADPennington)

**Comment by amilash** [comment]
Will let @ADPennington  confirm, but I think the idea is for the user to have a specific knowledge of why the error happened and the resulting non upload. More along the lines of..
"your file was not submitted b/c we detected a risk issue with the file type and we don't accept that kind of file"
or 
"your file was not submitted because we detected that it is an empty file and we do not accept that type of file".

**Comment by abottoms-coder** [comment]
@reitermb Should I tag this as 'research and design' or should dev team decide on the messaging here?

**Comment by stevenino** [comment]
@ADPennington @ttran-hub what is the system admin ask here?

**Comment by ADPennington** [comment]
updated this ticket to focus on error message for submitting infected files.

**Comment by ADPennington** [comment]
updated notification
![Screenshot 2024-11-18 at 3 02 12 PM (2)](https://github.com/user-attachments/assets/80e40b2f-bba2-450b-b9b4-a08c8b028afa)

**Comment by lhuxraft** [comment]
Video captured is no longer appearing in production
