### ISSUE TITLE
As a data analyst I can see my submission history

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1216]
**Description** 
As a data analyst, I can access my submission history for a given Quarter/FY.

**Notes**

**AC**
- [ ] Users can determine when a given submission was submitted
- [ ] Users can download all previous versions of the files they've provided
- [ ] Users have insight into summary data for each submission (# of cases, # of errors, etc...)

**Tasks**
- [ ] Design

**Comment by valcollignon** [comment]
Duplicate of #1274. Recommend to close @lfrohlich 
CC: @ADPennington @sreedevip @reitermb

**Comment by ADPennington** [comment]
agree @valcollignon cc: @lfrohlich

**Comment by valcollignon** [comment]
Closed per backlog refinement 12.14.21
CC: @lfrohlich
