### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1233]
Analytics Epic: This is a follow on from "Reporting" re: Enhancements enabled by having better data quality and discoverability within TDP.

Goal: now that TDP is more automated and data is running through a more secure and robust platform where data is normalized and more accessible, we can build data discovery and analytics capabilities for TANF and OFA that will add value in supporting OFA's mission of delivering value to TANF programs and Grantees. 

Research Questions:
What kind of analytics and insights can we enable for OFA and Grantees once we have?
- What would OFA and TANF love to know about STT's and programs usage? Get a list of specific reports or types of analysis that are desired.
- What 
- do we want to implement a series of reports that support specific questions? OR do we want to enable data discovery through a dashboard such as kibana or tableau to support the ability to ask questions and do data discovery and analysis outside of specified reports. The latter is ideal and is my recommendation, however if there are specific reports that are useful we should create them and deliver them first.

Needed from UX/Design:
- [ ]Aspirational User Stories for desired reporting
- [ ] Technical assessments of data needed for said ^ reports, update data model if needed.
- [ ] Dashboard UI- for data discovery enablement. If Kibana this is straightforeward.
- [ ] Analytics delivery user flow (Maybe already covered by 'Report' models)
