### ISSUE TITLE
Define List of STTs and plan for V2 pilot

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1239]
**Description:**
Previously "define list of Tribes for V2 (early release)". Updating to reflect that in addition to providing interesting tribes pilot access we should also recruit interested States/Territories. 

States using cyberfusion or otherwise invested in automated/semi automated SFTP transfer in particular may be good candidates. 

There was mention of one State whose cyberfusion is broken and they could benefit from being a part of the early release. This could save STTs who are migrating off of cyberfusion to not spend costs for the next year to fix or use a system that is being deprecated.
- Target a grantee who currently uses partial submission
- Consider: SORN may limit ability to include non-tribes

(Note: We could release V2 to more than 8 grantees. The original thinking of 8 tribes only was to try and keep it small. Actually there is no reason to limit it other than how many do we want to support initially.)

It needs to be easily supportable by OFA. It likely will be since the system for upload is very simple.

**Acceptance Criteria:**
- [x] List of potential pilot participant criteria is defined
- [x] Nearest associated resubmission/new submission date is documented
- [x] Pilot experience is defined (e.g. how to remain in contact with participants, receive feedback, provide support)
- [ ] Grantee contact information is documented for all potential candidates

**Tasks:**
- [x] Workshop to set goals and talk through hopes/fears for pilot
   - [x] Define goals
   - [x] Define (approximate) timeline
   - [x] Generate shortlist with consultation from @lfrohlich and @ADPennington. 
   - [x] Identify actions that could help deliver on hopes
   - [x] Identify actions that could mitigate fears
   - [x] Refine any remaining workshop items 

**Open Questions:**
- What kind of timeline do we envision for the first pilot (i.e. Pilot prior to any post-launch functionality additions). 
- What is the scope of pilot, which quarters will be being submitted? 
- Do we need to exclude states with SSP caseloads because TDP isn't currently equipped to handle SSP? 

**Documentation**
[Workshop Mural Board](https://app.mural.co/t/raft2792/m/raft2792/1651090645083/34ab63dca78931208cc45857eff163ce62dbd8a4?sender=mreiter1745)

**Comment by amilash** [comment]
@ADPennington @reitermb   will you add the tribes criteria here as we start to move towards this?

**Comment by stevenino** [comment]
@lfrohlich can we close this.

**Comment by lfrohlich** [comment]
@reitermb @lilybl1 can you add a link to the mural board in the issue description? also, it seems like all next steps will be captured in follow up tickets, correct?

**Comment by reitermb** [comment]
@lfrohlich Added! And yes on the next steps. We're capturing them first on the UX roadmap and then driving further ticketing/action on next steps from there.

**Comment by lfrohlich** [comment]
OK sounds good. In that case i'm fine to close
