### ISSUE TITLE
Change localstack Postgres password

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1247]
**Description:**
As we discussed in PR #1220 , we'd like to streamline the docker compose file and be able to remove or improve upon the line `POSTGRES_PASSWORD=something_secure`. As this password is only ever used for localstack testing and not in a deployed setting this is low priority at present and not a consideration for application security.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Postgres db configuration shall not have a non-plaintext password
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate difficulty of making this password encrypted via some docker/git secrets mechanism. 
- [ ] If low ROI, make DB passwordless and skip this password line altogether.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- If we find a way to make this password encrypted, how could we leverage this capability in other parts of the application?
- Can we ensure this is still simple to use for local testing?

**Comment by valcollignon** [comment]
Very low priority - per backlog refinement 12.21.21.

**Comment by robgendron** [comment]
@ADPennington @lfrohlich is this still needed?

**Comment by robgendron** [comment]
Deemed closed by team.
