### ISSUE TITLE
Resubmission UX/UI

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1269]
Acceptance Criteria:
- As an STT I cannot submit partial files for them to be accepted
- TDP will not accept partial submissions of files. 
- Files must be error free to be accepted. (see comment)
- TDP will allocate for states/statuses within submission whereby users can see errors, fix them and resubmit clean files.
- Users will be able to see the state and status of their submission/resubmissions
- Users will need to have errors displayed and be able to take them with/come back to view them during the resubmission process.
- TDP will need to save states of submission as well as dates of each submission attempt and log as/in both in status and history.
- STT Users will need to see history of submissions not only current submission quarter, but also history for past quarters.

~ Flow: Submit -> Parsing w Errors messages -> User fixes errors -> Resubmits data (till error free) -> Once data is error free it can be accepted.

NOTES:
Research Questions - 
1.  Does OFA need the opportunity to see and preview the data that is submitted (though it will not be accepted), but, does TDP still need to capture and therefore save the data that is submitted with errors?
2. How long do we allow for resubmissions- and how does this impact submission state/status. E.G. STT's have 45 days to resubmit until the current 1/4 is accepted, do we allow data to be resubmitted afterwards? if so what is the states called for this.
2. What is the ideal presentation/content of submission history? e.g. list of older files vs some transparency into summary data for each (# of records, records changed, which records changed, etc...) 
3. What is the impact to current grantee practices if partial resubmissions go away? What changes in their flow? Does it impact the lift of resubmission?
4. Impact to cognitive load of resubmissions? Are support materials needed to help address this? When should support materials be ready within the release schedule? Are there ways to address it earlier?
5. Comparative report / surfacing of # of cases changed by a resubmission.

Deliverables:
- [x] Resubmission user flow
- [x] Resubmission notification flow
- [x] Identify States for data submission: notional ( A. Submitted with errors, B. Submitted with errors n+1 C. Individual files submitted, error-free = accepted D. Individual Files submitted error free + all files needed for full submission (all of the 4 types of files) E. File quality approved (data within aggregate files that reference other files is the same or matching)  F. ?Q: is there a final human review here?))
- [x] Resubmission history updates based on current notional UX/Research
- [x] UI for Resubmission Flow (the beginnings of submission status UI)

Approach:
1. Develop notional UX/UI based on current specs and understanding
2. Internal Review with OFA Digit Team and Raft Leads
3. Validate UI/UX with users to finalize designs/UX.

**Comment by amilash** [comment]
@ADPennington , @sreedevip is refining the research approach for this, can you touch on any of the open questions in the epic level here in the comments? This will give us a good start.

**Comment by reitermb** [comment]
Re: 
>Files must be error free to be accepted. 

I think we need to refine this AC to reflect the following:
- Only parsable files can be submitted
- Resubmission should be capped at a certain date after the first submission deadline (does FY end make sense?)
- Acceptance is based upon some level of data completeness/error quantity measure. 

Thoughts on the above @ADPennington? One thing I think might be good for us to build into the research tasks for this sprint is a sync with you (and maybe the rest of the DIGIT team?) about "Acceptance" as a status for a submission. 

Pulling out some of the differences between received by OFA, reviewed by OFA, and approved as being sufficient to meet data reporting requirements, unlock the full block grant, and so on. 

Generally digging deeper on this conversation: ![image.png](https://images.zenhubusercontent.com/5f18c4478e7597370ff64fdd/6bbeee06-43b5-4995-b1aa-11b267e8d4a8)

**Comment by ADPennington** [comment]
@sreedevip @reitermb 

>1. Does OFA need the opportunity to see and preview the data that is submitted (though it will not be accepted), but, does TDP still need to capture and therefore save the data that is submitted with errors?

one benefit of keeping the rejected file is to facilitate a comparison to the re-submitted file. alternatively, collecting metadata on file submissions (rejected + accepted) would probably be sufficient--hopefully we're planning to collect these metadata either way. 

>2. How long do we allow for resubmissions- and how does this impact submission state/status. E.G. STT's have 45 days to resubmit until the current 1/4 is accepted, do we allow data to be resubmitted afterwards? if so what is the states called for this.

Ideally, we want to allow re-submissions through the end of the fiscal year reporting period, which is approx 2 years after the first quarter of data is due. This is because despite the abovementioned deadlines, STTs tend to re-submit multiple quarters of fiscal year data after the 4th quarter data deadline. 

There are also rare circumstances where STTs re-submit previously completed fiscal years due to  a state audit (or similar reason). So there may be scenarios where we want to exceptionally allow re-submissions after the 2-year period resubmission period. 

> 3. What is the ideal presentation/content of submission history? e.g. list of older files vs some transparency into summary data for each (# of records, records changed, which records changed, etc...) 

at a minimum, a table of metadata would be good here:
- section
- fiscal year and quarter
- submission date
- status (rejected, accepted w/ errors, etc.)
- # errors overall and by priority type 
- # total records
- # total cases overall and by month and record type (Sections 1 and 2) 

>6. Comparative report / surfacing of # of cases changed by a resubmission.
could be related to  4)

**Comment by ADPennington** [comment]
one thing that is also occurring to me is that we need to figure out how to define partial in order for TDP detect it. 

when I investigated this, i compared the number of cases in the submitted file to an average caseload count from a published report. this was mostly useful for a snapshot analysis but not really scalable. it may be sufficient to flag files that have obviously too few cases (e.g. 1 case), but this gets tricky for Section 2 (since it is possible to not have any closed cases in a month) and Tribal TANF (which sometimes have very small [caseloads](https://www.acf.hhs.gov/sites/default/files/documents/ofa/2018_tribal_families_data.pdf))

@sreedevip @reitermb

**Comment by reitermb** [comment]
[Submision History STT View Variation 2.pdf](https://github.com/raft-tech/TANF-app/files/7859591/Submision.History.STT.View.Variation.2.pdf)
[Submission History STT View Variation 1.pdf](https://github.com/raft-tech/TANF-app/files/7859592/Submission.History.STT.View.Variation.1.pdf)

**Comment by reitermb** [comment]
https://github.com/raft-tech/TANF-app/blob/1269-add-fall-2021-research-synthesis/docs/User-Experience/2021%2C%20Fall%20-%20Investigating%20Partial%20Submission%20%26%20Evaluating%20TDP%20Submission%20History.md

Branch is now open to begin checking in-document linking for GitHub compatibility.

**Comment by lfrohlich** [comment]
All tickets are complete -- closing this
