### ISSUE TITLE
Resubmission User Flow

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1270]
**Description**
Delivers a user flow capturing the submission/resubmission process. This may be delivered in one large flow or several more focused ones.

**AC**
- [x] Flow includes all needed steps/branching to support resubmission states (for more see #1272)
- [x] Flow either includes or annotates where the notification flow overlaps with it (for more see #1271)

**Tasks**
- [x] Draft user flow(s) in Figma
- [x] Ensure flow either includes or is compatible with data states 
- [x] Ensure flow includes or is compatible with the notification flow/[events](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Research/2021%2C%20Spring%20-%20Tribal%20MVP%20(Release%202)%20Design%20Sprint.md#we-validated-the-value-of-three-notification-events-as-well-as-the-hypothesis-that-a-reminder-of-reporting-due-dates-could-be-helpful)
- [x] Review flow in DIGIT pairing to support discussion of data states
- [x] Document any granular research questions/interview questions/tasks to test in [planning hack.md document](https://hackmd.io/@mreiter/HyXBLVaZK/edit)

**DoD**
- [x] OFA review/signoff
- [x] Flow is documented in Figma/marked for review

**Deliverables**
- Figma User Flows [page](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=1277%3A8087)

**Comment by reitermb** [comment]
Ensure we have parity with the in-app language, e.g. selects a file to upload instead of “upload button”
Fatal error/warning error paradigm is going away in TDP; current distinction is just pre parsing errors (stuff that blocks our ability to parse the entire file or specific records) > post parsing errors (all other types of error)
It stretches the definition of “Starting/ending place” but I wonder how we could capture the “OFA accepts submission and requests changes” state. Checking off reporting requirements but asking for data quality improvements/correction of some volume of remaining errors
