### ISSUE TITLE
Resubmission Notification Flow

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1271]
**Description**
Documents the flow of notification events associated to the resubmission flow. e.g. "OFA has reviewed and accepted your data for Q3 2021" could be a notification that a grantee receives after having resubmitted files. We're currently differentiating spec for notifications from the flow of notification events; we'll capture when a notification will occur in the context of the resubmission flow, not the final version of what that notification will look like/how it will be presented to the user. Note that we may include the notification flow as part of the resubmission flow itself. 

**Notes**
There will likely be a fair bit of overlap between data states (#1272) and notification events.

**AC**
- [x] All notifications related to resubmission are documented
- [x] All applicable data states have associated notification events
- [x] All applicable [validated notification events](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Research/2021%2C%20Spring%20-%20Tribal%20MVP%20(Release%202)%20Design%20Sprint.md#we-validated-the-value-of-three-notification-events-as-well-as-the-hypothesis-that-a-reminder-of-reporting-due-dates-could-be-helpful)) are captured in the flow

**Tasks**
- [x] Draft notification flow(s) in Figma / add to resubmission flow 
- [x] Ensure flow either includes or is compatible with data states 
- [x] Review flow in DIGIT pairing to support discussion of data states
- [x] Document any granular research questions/interview questions/tasks to test in [planning hack.md document](https://hackmd.io/@mreiter/HyXBLVaZK/edit)
- [x] Follow-on clean up task: annotate notification triggers alongside flow

**DoD**
- [x] OFA review/signoff
- [x] Flow is documented in Figma/marked for review

**Deliverables**
- Figma User Flows [page](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=1277%3A8087)

**Comment by lfrohlich** [comment]
Discussed post-parsing file rejection case at UX sync on 10/25/21

**Comment by lfrohlich** [comment]
Complete!
