### ISSUE TITLE
Resubmission Data States

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1272]
**Description**
Documents the states of data submissions (Quarter/FY files) that need to be distinguished and displayed in-app and/or in notifications. 

**Notes**
- A new definition will likely be needed for OFA acceptance (currently <500 fatal errors) due to the move away from the fatal/warning paradigm. 
- There will likely be a fair bit of overlap between data states (#1272) and notification events.

**AC**
- [ ] All states of data submissions have been documented
- [ ] Design/Dev/DIGIT aligned on a new definition of OFA acceptance or added a follow-on ticket to do so

**Tasks**
- [x] Draft prospective data states 
- [x] Schedule Design/Dev/DIGIT sync to validate/discuss potential new definitions of OFA acceptance
- [x] Design/Dev/DIGIT sync
- [x] Document insights/decisions/next steps from sync 
- [x] Revise data states documentation as necessary
- [x] Revise user and notification flow as necessary

**DoD**
- [x] OFA review/signoff
- [x] Flow is documented in [Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=5242%3A41328)/marked for review

**Comment by lfrohlich** [comment]
Looks good!
