### ISSUE TITLE
Resubmission UI (jumping off point for submission history)

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1273]
**AC:**
- [x] UI should be able to reflect all data states as identified in #1272 

**Notes:**
Variations of submission UI history may be further refined as needed to support research in Sprint 30. (#1275) 

**Tasks:**
- [x] Design Draft IA/page hierarchy to help plan how submission history could be structured / linked around the current Data Files design
   - [x] Design UI relating to how users would navigate the above
- [x] Design status indicator tables
- [x] Document related research/interview questions/participant concept or usability tests in research planning hack.md
