### ISSUE TITLE
Submission History UI (Resubmission epic)

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1274]
**AC:**
- [x] UI has been shared with the team
- [x] UI ideation should include:
   - [ ] section
   - [ ] fiscal year and quarter
   - [ ] submission date
   - [ ] status (rejected, accepted w/ errors, etc.)
   - [ ] errors overall and by priority type
   - [ ] total records
   - [ ] total cases overall and by month and record type (for sections 1 and 2)

**Notes:**
Variations of submission history may be further refined as needed to support research in Sprint 30. (#1275) 

**Tasks:**
- [x] Design Draft IA/page hierarchy to help plan how submission history could be structured / linked around the current Data Files design
- [x] Draft testable variations of resubmission history UI (for split testing)
- [x] Document related research/interview questions/participant concept or usability tests in research planning hack.md

**DoD:**
- [x] Design exists in [figma ](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=5242%3A41328
- [x] @lfrohlich has reviewed and approved

**Comment by reitermb** [comment]
@lfrohlich Noting for review here that we're holding off on further ideation re: AC "errors overall and by priority type" pending further discussion with DIGIT about what priority entails. The "For review" section of Figma has an early idea for how this might be presented but we wanted to hold off on testing it with grantees until we fully understood it.

**Comment by lfrohlich** [comment]
With few minor edits, looks good!

**Comment by ADPennington** [comment]
@reitermb agree w/ @lfrohlich i also left a few comments!
