### ISSUE TITLE
Resubmission Research/Usability & Concept Testing

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1275]
**Description:**
This ticket delivers research associated to the resubmission epic. This covers investigation of the impact of partial resubmission not being allowed in TDP & evaluative research concerning data state communications in TDP as well as submission history. 

**Notes:**
This may carry over into Sprint 31 depending on participant recruitment/scheduling. Synthesis of findings and revisions to UI/Flow/Product Decisions will be encompassed in follow on ticket: #1290 

**AC:**
- [x] Team is aligned on the research plan (recruitment criteria, methods, scope of testing)

**Tasks:**
- [x] Schedule DIGIT session for discussion of testable UI, summary/metadata presentation
- [x] Draft interview plan/guide in[ hack.md](https://hackmd.io/@mreiter/HyXBLVaZK)
   - [x] Draft interview questions, concept/usability testing guide
   - [x] Draft grantee-friendly flow as interview aid
   - [x] Update recruitment emails
   - [x] Share for feedback internally
- [x] Revise testable mockups as needed to support research as the plan/guide progresses
- [x] Reach out to potential participants & regional staff
- [x] Schedule grantee sessions
- [x] Facilitate sessions

**DoD**
- [x] Plan is drafted and shared with the team [Link](https://hackmd.io/@mreiter/HyXBLVaZK)
- [x] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
Research plan looks good to me!

**Comment by valcollignon** [comment]
@sreedevip @reitermb can you re-point this when you get a chance?

**Comment by valcollignon** [comment]
One more session today 12.21 and then should be complete.

**Comment by lfrohlich** [comment]
With all sessions completed this OK to close out
