### ISSUE TITLE
Updated SORN with backup retention policy

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1288]
### Description 

We need to update the System of Records Notice (SORN) to reflect how data flowing through TDP will be managed. In the absence of this update, the data flowing through TDP (beginning in release 3)  would need to be moved into cold storage and disposed at specific time intervals. Key parts that need to be addressed in update:

- the 30-day retention period that would apply to all versions of raw files to be stored in S3. 
- the 24-month retention period limit that would apply to parsed data to be stored in the ElasticSearch db.
- the 20-year retention period limit and disposal reqs that would apply to parsed data that would need to put into cold storage after the 24-month period expires. 

#### Suggestions for updating the SORN:
- remove time periods for retaining and disposing of raw and parsed data 
- remove cold storage methods (e.g. cd) for managing raw and parsed data 
- types of data described therein is general enough to cover any updates in reporting requirements 

#### Suggestions for managing data flowing through TDP:
- retain raw files in S3 for max of 5 years. Then dispose. 
- retain parsed data in ElasticSearch db for 5 years. Then move into cold storage, where only sys admins can access.  

### ACs:
- [ ] Management of data flowing through TDP is in compliance with SORN

### Tasks:
- [x] finalize draft of updated SORN and submit for HHS review [`OFA`]
- [ ] Upon approval of updated SORN, implement strategy for retaining+disposing raw files in S3. (#1007)
- [ ] Upon approval of updated SORN, implement strategy for retaining+cold storing+disposing parsed data in ES. 

### Open questions
- Parsed data is subject to overwriting since re-submissions will be allowed. Should we start the data retention clock after the reporting period is closed (i.e. after this period, TDP will not allow re-submissions)? If so, what should we do in exceptional scenarios where data is re-submitted after the reporting period? 
- How should we approach cold storing data after retention period? 
- How long should we retain data in cold storage format? And after this period, how should we dispose? 

### Supporting documentation 
- Updated SORN [documentation](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/SORN/SORN%20Template_OMB%20A-108%202016_OFA2021-11-08.docx?d=w6359b45e033b4377ba739bebda4f95d8&csf=1&web=1&e=VoxZRj)
- existing TANF [SORN](https://www.federalregister.gov/d/2015-07440/p-276) (also covers SSP data)
- existing Tribal TANF [SORN](https://www.federalregister.gov/d/2015-07440/p-221)
-  #798 
- #1007

**Comment by valcollignon** [comment]
@ADPennington to refine this ticket and #1007 and #798.

**Comment by ADPennington** [comment]
submitted draft sorn to OCIO for review on 4/8.

**Comment by ADPennington** [comment]
@abottoms-coder proposed retention policy for raw files in S3  in the summary of this ticket.

**Comment by lfrohlich** [comment]
Pinged and asked for a review timeline 5.3.22

**Comment by stevenino** [comment]
Moved this back to refined backlog since it is blocked and no active work is being done on it.

**Comment by ADPennington** [comment]
as of 5/16/2022, updated SORN draft has been forwarded on to HHS privacy officer and OGC for review.

**Comment by stevenino** [comment]
@blacklobo @ADPennington Any updates on this?

**Comment by ADPennington** [comment]
I emailed updates on the purpose of the updated SORN to ACF OCIO on 10/11/2022.

**Comment by lfrohlich** [comment]
Royce Nmorka (new SORN point person) sent revised TANF SORN to HHS point person -- Beth Kramer -- for review. 2/3

**Comment by lfrohlich** [comment]
We received feedback from Beth on 2/10

**Comment by lfrohlich** [comment]
Resubmitted revised SORN on 5/18

**Comment by lfrohlich** [comment]
Currently with the Office of the Federal Register for review

**Comment by ADPennington** [comment]
updated SORN is live now and here: https://www.federalregister.gov/documents/2024/04/12/2024-07823/privacy-act-of-1974-system-of-records 

cc: @lfrohlich @robgendron

**Comment by lfrohlich** [comment]
@ADPennington @robgendron at upcoming backlog/prodsync let's discuss what, if anything, needs to be done about: 
1.  strategy for retaining+disposing raw files in S3. (https://github.com/raft-tech/TANF-app/issues/1007)
2. strategy for retaining+cold storing+disposing parsed data in ES.

**Comment by robgendron** [comment]
@andrew-jameson let's discuss this further.

**Comment by lfrohlich** [comment]
To be continued with #1972
