### ISSUE TITLE
Spike: Investigate feasibility of Elasticsearch for parsed data storage

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1289]
**Description:**
In preparation of the upcoming parsing work outlined in #1101 we need to determine the best place to store the parsed data in a way that it can be both secure and easily searchable by OFA Admins for the purposes of generating reports and performing ad-hoc queries.

This issue will entail researching Elasticsearch's capabilities particular to our data sets and putting together a small demo using mock data to evaluate feasibility of hosting this service in Cloud.gov's managed service instance.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Evidence of Elasticsearch functionality with mock TANF data while deployed in Cloud.gov
- [x] Any potential development hurdles or security flaws should be identified
- [x] A list of pros/cons for this approach is created
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Create a managed service instance for AWS Elasticsearch in Cloud.gov
- [x] Determine methods of access and authorization to Elasticsearch and Kibana for OFA Admins
- [x] Create a mock data set matching one of the specified TANF data file formats, as it would be when fully decoded and parsed. Ingest that data into Elasticsearch.
- [x] Demonstrate running ad-hoc queries along with a report or dashboard in Kibana
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Cloud.gov Elasticsearch service](https://cloud.gov/docs/services/aws-elasticsearch/)

**Open Questions:**

**Comment by ADPennington** [comment]
@jtwillis92 if there is potential here for transitioning away from an RDS or using it differently than how OFA currently uses it, please include some pros/cons in this spike.

**Comment by jtwillis92** [comment]
> @jtwillis92 if there is potential here for transitioning away from an RDS or using it differently than how OFA currently uses it, please include some pros/cons in this spike.

Will do, if we chose to go this route we would still use RDS for storing Users and other Django models, the parsed data itself would be stored separately.

**Comment by amilash** [comment]
remaining 3

**Comment by jtwillis92** [comment]
Spike findings and demo procedure uploaded [here](https://gist.github.com/jtwillis92/a6840a412676fc2d3f58c0dccbf10da1)

[This script](https://gist.github.com/jtwillis92/50dd8f578b78ff1c4a9343a28958d338) was used to generate mock data, we can likely re-use some of this for unit testing later on.

Current status: Awaiting demo w/ DIGIT team, also need a deep dive into SQL analysis performed by OFA Staff to isolate what can be done with Elasticsearch.

**Comment by abottoms-coder** [comment]
@ADPennington Need to finalize decision and if relevant, create follow-on ticket(s).
