### ISSUE TITLE
Switch react-scripts for react-rewired-app

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1304]
**Description:**
To satisfy the results of the OWASP ZAP scan, we implemented a CSP header but ran into a wrinkle on style-src and opted to utilize a workaround of "unsafe inline". This is obviously still potentially vulnerable from a security standpoint but we couldn't immediately ascertain a solution which was investigated in #1208. 

Relevant code from the spike can be found in this branch: spike/1208-unsafe-inline-styles

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] 'Unsafe inline' is not used for any CSP policies
- [ ] ZAP scan does not have any CSP header failures
- [ ] Pages appear the same and retain all previous functionality
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update the core reactjs libraries to react-rewired-app
- [ ] Resolve yarn --frozen-lockfile CircleCI build issue
- [ ] Update relevant documentation
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Blog where solution was found](https://medium.com/@nrshahri/csp-cra-324dd83fe5ff)

**Open Questions:**
- Are trade-offs in maintenance worthwhile?
- Are there known security vulnerabilities for using these libraries?
- Are there known bugs in these libraries which could impact future development?
