### ISSUE TITLE
TANF Active Data (01) File Parsing - As a data analyst, I want my data files to be parsed so that my submission can be validated/accepted by TDP.

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#132]
**Description:**
_Provide a brief background and justification for this issue_
Parsing of TANF STT submissions for Active Case Data.

**Acceptance Criteria:** 
- [x] Data File parsing logic is in place such that data file submission can be completed by user and parsed by system for full submission once errors are resolved.
- [ ] Data Errors tell user specifically where in the file they occur, and therefore what exactly needs to be fixed in order for the submission to be complete.
- [ ] List of lessons learned from tackling corner-cases to be applied to other parsing tickets

Old AC within other tickets:
- [ ] TDP gives the user all data errors for a submission in a way they can easily save or export so they can take the issues back to their case management software and fix the issues then recreate an export for resubmission to TDP. #1122 
- [ ] Data Errors must be issued in human readable plain language so that an English speaker can easily understand what is needed. #1122

**Tasks:**
- [x] Using test-driven development, write unit tests for badly formatted files
- [x] Implement parsing for base-case small, error-free file
- [ ] Implement parsing to log error messages for use-cases for badly formatted files
- [x] Parsing classes/functions should return a data structure(s) with relevant fields containing data from the input file

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
DISAGGREGATED TANF DATA COLLECTION
TRANSMISSION FORMAT SECTION 1  
https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_report_section1_10_2008.pdf 
https://www.acf.hhs.gov/ofa/policy-guidance/final-tanf-ssp-moe-data-reporting-system-transmission-files-layouts-and-edits 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by ADPennington** [comment]
Some questions + comments included below:


> **Acceptance Criteria:**
> 
> * [ ]  Data File parsing logic is in place such that data file submission can be completed by user and parsed by system for full submission once errors are resolved.

Here, we should probably specify (at a high-level) the type of errors this ticket will detect. Because not all possible errors in the file will detectable. For example, some errors can only be detected by comparing data between Section 1 and Section 3. Are there any objections to focusing on [category 1 and 2 errors](https://github.com/raft-tech/TANF-app/issues/1101#issuecomment-891986055)? If so, we could close #1127 as a dupe. 

> * [ ]  Data Errors tell user specifically where in the file they occur, and therefore what exactly needs to be fixed in order for the submission to be complete

we should specify what we mean by "complete". it will not necessarily mean that the data are error-free or free of anomalies (which may not rise to the level of "error"). My goal for release 3 is to have data that is ready to be stored in the db. that will facilitate a more robust quality check for OFA data analysts.

**Comment by andrew-jameson** [comment]
> Some questions + comments included below:
> 
> > **Acceptance Criteria:**
> > 
> > * [ ]   Data File parsing logic is in place such that data file submission can be completed by user and parsed by system for full submission once errors are resolved.
> 
> Here, we should probably specify (at a high-level) the type of errors this ticket will detect. Because not all possible errors in the file will detectable. For example, some errors can only be detected by comparing data between Section 1 and Section 3. Are there any objections to focusing on [category 1 and 2 errors](https://github.com/raft-tech/TANF-app/issues/1101#issuecomment-891986055)? If so, we could close #1127 as a dupe.
> 
> > * [ ]   Data Errors tell user specifically where in the file they occur, and therefore what exactly needs to be fixed in order for the submission to be complete
> 
> we should specify what we mean by "complete". it will not necessarily mean that the data are error-free or free of anomalies (which may not rise to the level of "error"). My goal for release 3 is to have data that is ready to be stored in the db. that will facilitate a more robust quality check for OFA data analysts.

As discussed in 5.13.22 Cross Product Sync, we will attempt to scope this ticket to focus on category 1/2 "pre-parsing errors" as well as basic file parsing. To elaborate, these will result in outright rejection of submitted files but ideally we will be able to submit data from file into a data structure whether or not that data is internally consistent aka has "garbage values" (not saying you can insert wrong types e.g. SSN of form "this-is-myssn")

**Comment by ADPennington** [comment]
@andrew-jameson I included some notes [here](https://hackmd.io/AoLSVBStQtiZ3PzZjWONzA?view) about common issues in TANF Section 1 files. All of these issues should be detectable in the [`bad_TANF_S1.txt` ](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fdev%2FParsing%2Fdata%2Ftanf%2FSection1%2Fbad%2Fbad%5FTANF%5FS1%2Etxt&parent=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fdev%2FParsing%2Fdata%2Ftanf%2FSection1%2Fbad)on Sharepoint. ping me with any questions.
