### ISSUE TITLE
Resolve OWASP ZAP report

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1326]
**Description:**

This ticket is to track all work and meta-work addressing findings for the OWASP ZAP scan required for compliance in release one.

Latest prod frontend scan:
https://11066-281707402-gh.circle-artifacts.com/0/tdrs-frontend/reports/owasp_report.html
Latest prod backend scan:
https://11066-281707402-gh.circle-artifacts.com/0/tdrs-backend/reports/owasp_report.html

**Acceptance Criteria:** 
- [x] All items in the OWASP ZAP scan must be fixed, waived, or addressed.
- [x] For unfixed items, have a document detailing how/why it is mitigated.
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] #1258 
- [x] #1161 
- [x] #1208 
- [x] #1367
- [x] #1165
- [x] #1403
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
For all alerts not labelled as a false positive in 1258, create a ticket to address each:

Error|Severity|Count
-- | -- | --
Application Error Disclosure | Medium | 1
CSP: style-src unsafe-inline | Medium | 1
Proxy Disclosure | Medium | 12
Incomplete or No Cache-control Header Set | Low | 2
Information Disclosure - Suspicious Comments | Informational | 2
Modern Web Application | Informational|2
Timestamp Disclosure - Unix | Informational|20
User Agent Fuzzer | Informational|21

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by lfrohlich** [comment]
This is now complete 
Follow up: ZAP False Positives - Unexpected Content Type & Client Error response code#1455

**Comment by ADPennington** [comment]
we need to update this ticket's table just to capture the before and after. @jtwillis92
