### ISSUE TITLE
SPIKE: As a dev, I'd like to store our new splash page images within our domain

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1330]
**Description:**
As discussed with @jorgegonzalez , we need a way to store our paid-for images as to not be publicly accessible right in our github repo. This ticket is to explore options on how best to store this data and potentially others in a secure location.

**Acceptance Criteria:** 
- [ ] Image(s)/data must be accessible from the TDP front-end
- [ ] Solution is cost-effective (ideally free or within our existing stack(s)
- [ ] Solution is not burdensome in maintenance or complexity
- [ ] Solution allows updates as desired
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Investigate S3 as a solution
- [ ] Investigate buildpack web server as a solution
- [ ] Explore other open-source solutions
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- This is done to ensure we aren't storing non-code binary files like images in our github repo and to prevent client browsers from pulling from a non-cloud.gov domain.
- Time box for this is ~ 2 hours.

**Supporting Documentation:**

**Open Questions:**
- Can we simply piggyback off our current S3 infrastructure?
- Would storing the image(s)/data in a local-to-our-buildpacks-accessible web server docker container be simpler?
- If solution is compromised, what security risks does this pose? How can we mitigate them?

**Comment by jorgegonzalez** [comment]
We discussed this during dev sync. Given that we are only adding a set of 3 new images for the splash page, we decided to include them in the frontend app such that they are added to the frontend production bundle (result of `yarn build`). No additional S3 or WebPack work is needed.

Thus, this SPIKE can be closed @abottoms-coder.
