### ISSUE TITLE
Change splash page background image

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1331]
**Description:**
This is the follow-on operations task from #640 to actually change the image as is stored in #1330.

**Acceptance Criteria:** 
- [ ] New images are displayed on the front-end landing page.
- [ ] Frontend has a timed slideshow of the new images
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Store images in an image folder in the github repo
- [x] Update frontend to have a slideshow of background images
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by abottoms-coder** [comment]
@lfrohlich For the new landing page, do we want a timed "slideshow" effect where the frontend will transition between images or do we want a different image loaded on every refresh but otherwise stays static?

**Comment by abottoms-coder** [comment]
> @abottoms-coder is there a dev effort difference? I would have a slight preference for the slideshow but am fine with the refresh if the slideshow is a bigger lift.

Ok, we will do the slideshow. The effort isn't significantly different but we had conflicting memories on which was intended with the term "carousel" in the description and were just seeking clarification on which.

**Comment by jorgegonzalez** [comment]
We need access to the relevant assets to complete this issue, the new background images aren't linked anywhere @reitermb @sreedevip
