### ISSUE TITLE
As a TDP user, I want to receive an email notifying me that my request has been denied.

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1334]
### Description

#1679 will deliver functionality for admins to deny requests for access to TDP. When this  field (`account_approval_status`) is changed to `Denied`  in a user's profile, this should trigger an email notifying the user that their request has been denied. 

### ACs
- [x] When an `OFA System Admin` changes a user's `account_approval_status` status to `Denied` in the user's profile, this will trigger a `deny` email to the user. 
- [x] No other status changes to `account_approval_status`  will trigger a `deny` email to the user. 

### Tasks
- [x] add tests to check that appropriate type of email is sent. 

### Supporting Documentation
- #1679 
- [Deny Email Content](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg#I-want-to-receive-an-email-notifying-me-that-my-request-has-been-denied1)

### Notes
- Release 2.1

**Comment by abottoms-coder** [comment]
@abottoms-coder Flesh out ticket description w/ template.

**Comment by ADPennington** [comment]
@stevenino this ticket has been recycled to focus on the deny email notification for V2.1. it is unrefined and depends on #1679.

**Comment by stevenino** [comment]
@ADPennington and @andrew-jameson to discuss path forward at dev sync on 6/1. This and #1679 have to be refined and re-aligned.
