### ISSUE TITLE
[Design Deliverable] Email Template for Data Due Date Reminder

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1345]
**Description:**
Delivers content and compliant HTML email templates and documentation regarding email triggers for V3 notifications

**AC:**

- [x] Notification spec/templates exist for 
   - [x] Due date approaching (5 days)
   - [x] Due date passed with no submission
- [ ] New templates knowledge center / TANF support email section is consistent with the version in existing templates
- [ ] The design is usable, meaning it adheres to definition of done standards for project design work.
> <details>
>      <summary>Expand DoD Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines] and accessibility implementation notes are documented(https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>
> 

- [ ] Dev/Design sync has occurred; resulting tickets created.

**Tasks:**
- [x] Adapt Alex's current email into HTML template format for
   - [x] Due date reminder (5 days) 
   - [x] Past due reminder
- [ ] Make any content/template revisions
- [x] A11y review with @ttran-hub 

**Supporting Documentation:**
- [TDP-HTML-Email-Demo-Environment](https://github.com/reitermb/TDP-HTML-Email-Demo-Environment)
- Link to [HTML template.html](url)
- [hack.md](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg)

```This is a friendly reminder that the deadline for fiscal year (FY) 2024 Q1 (Oct - Dec, 2023) data submissions is February 14th, 2024.

For those of you who have already submitted your data files for FY 2024 Q1 via TANF Data Portal (TDP), thank you; there is no further action needed.

Action Requested:

Please sign in to the [TANF Data Portal](https://tanfdata.acf.hhs.gov/).
If you haven't signed into TDP in more than 170 days, please sign in to avoid having your account be deactivated due to inactivity.
Upload and submit data files for FY 2024 Q1 (Oct - Dec, 2023) by February 14th, 2024.
Need help?

Check out the [TDP Knowledge Center](https://tdp-project-updates.app.cloud.gov/knowledge-center/) for specific guidance on [Submitting Data Files](https://tdp-project-updates.app.cloud.gov/knowledge-center/uploading-data.html) and [Frequently Asked Questions](https://tdp-project-updates.app.cloud.gov/knowledge-center/faq.html).
Reach out to the [TDP support team](mailto:TANFData@acf.hhs.gov) by replying to this email and we will follow up with you directly.


Thank you,

The TDP Team```

**Comment by valcollignon** [comment]
@reitermb to circle back on this issue. Adding to Notifications and Comms epic during backlog refinement 10/12/21.

**Comment by stevenino** [comment]
Parsed data accepted, rejected notifications.

**Comment by reitermb** [comment]
Revisit in UX Sync before prioritizing to ensure we're slicing 3.0+ notifications correctly/previously spec'd notifications are still valid.

**Comment by victoriaatraft** [comment]
Pasting message here to track.

Hi @elipe17 @andrew-jameson this sends sends out emails to people when a deadline for submission is approaching and if the deadline has passed. From a convo with @ADPennington we'd like to track who has submitted data so that people who haven't submitted only receive said notifications. How and when we could go about implementing would be super great to work through. thank you :)

**Comment by robgendron** [comment]
4 points remaining.

**Comment by andrew-jameson** [comment]
> Pasting message here to track.
> 
> Hi @elipe17 @andrew-jameson this sends sends out emails to people when a deadline for submission is approaching and if the deadline has passed. From a convo with @ADPennington we'd like to track who has submitted data so that people who haven't submitted only receive said notifications. How and when we could go about implementing would be super great to work through. thank you :)

Relatedly, we should re-use "partial" determination logic between this and #2217 for STTs having missing submissions for differing sections.
* Does California/SSP states have to submit all sections in filenames?
* Is stratum/sec4 required? Do we have listing of optional sections?
* Do we notify non-submitters upon confirmation of submission? (e.g., Alice submits, bob gets email)

kudos to @jtimpe

**Comment by robgendron** [comment]
3 points remaining.

**Comment by reitermb** [comment]
> > Pasting message here to track.
> > Hi @elipe17 @andrew-jameson this sends sends out emails to people when a deadline for submission is approaching and if the deadline has passed. From a convo with @ADPennington we'd like to track who has submitted data so that people who haven't submitted only receive said notifications. How and when we could go about implementing would be super great to work through. thank you :)
> 
> Relatedly, we should re-use "partial" determination logic between this and #2217 for STTs having missing submissions for differing sections.
> 
> * Does California/SSP states have to submit all sections in filenames?
> * Is stratum/sec4 required? Do we have listing of optional sections?
> * Do we notify non-submitters upon confirmation of submission? (e.g., Alice submits, bob gets email)

I think we'll need a follow-on conversation with @ADPennington to fully confirm but I lean toward the logic here checking for ≥1 data file(s) for a given quarter. I don't believe we have a widespread problem with sections being left off when they're required so I think it's safe to assume that if any file has been submitted, others likely have as well. (We have future notifications backlogged for "You didn't submit section x" type messaging)

I like the idea of only notifying submitters, but I lean: notify everyone at an STT given that we'll never have a perfectly accurate handle on who those submitters will be given churn and coverage during leave for normal submitters.

**Comment by reitermb** [comment]
Just updating w/ some notes from internal UX sync:
- Two email templates: 
   - Due date approaching — 5 days out
   - Data past due — 1 day after? 45 after? Alex's input will be helpful for timing 
- Emails should include replacement tags in the subject & body to insert SSP when it's applicable. e.g. content would be "TANF data files are due" vs "TANF and SSP data files are due"

**Comment by robgendron** [comment]
UX is planning on syncing with Thomas on 4/29 for accessibility check.

**Comment by victoriaatraft** [comment]
Templates have been added and can be viewed on the [TDP-HTML-Email-Demo-Environment](https://github.com/reitermb/TDP-HTML-Email-Demo-Environment)

1. [deadline-approaching-no-submission-5days.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-approaching-no-submission-5days.html)
4. [deadline-approaching-part-submission-5days.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-approaching-part-submission-5days.html)
7. [deadline-passed-no-submission.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-passed-no-submission.html)
10. [deadline-passed-part-submission.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-passed-part-submission.html)
![Screenshot 2024-04-29 at 10 44 32 AM](https://github.com/raft-tech/TANF-app/assets/106103383/6393351d-a6fe-44b6-8ec1-607c9d7e88ba)
![Screenshot 2024-04-29 at 10 44 07 AM](https://github.com/raft-tech/TANF-app/assets/106103383/dc13fff6-8f22-4cc4-b159-d01963a0ac79)
![Screenshot 2024-04-29 at 10 43 46 AM](https://github.com/raft-tech/TANF-app/assets/106103383/6dd63600-7bff-41ac-972c-c36106572f2a)
![Screenshot 2024-04-29 at 10 43 13 AM](https://github.com/raft-tech/TANF-app/assets/106103383/e678ac38-6d37-463b-af61-5b83fea01de6)

**Comment by victoriaatraft** [comment]
> > > Pasting message here to track.
> > > Hi @elipe17 @andrew-jameson this sends sends out emails to people when a deadline for submission is approaching and if the deadline has passed. From a convo with @ADPennington we'd like to track who has submitted data so that people who haven't submitted only receive said notifications. How and when we could go about implementing would be super great to work through. thank you :)
> > 
> > 
> > Relatedly, we should re-use "partial" determination logic between this and #2217 for STTs having missing submissions for differing sections.
> > 
> > * Does California/SSP states have to submit all sections in filenames?
> > * Is stratum/sec4 required? Do we have listing of optional sections?
> > * Do we notify non-submitters upon confirmation of submission? (e.g., Alice submits, bob gets email)
> 
> I think we'll need a follow-on conversation with @ADPennington to fully confirm but I lean toward the logic here checking for ≥1 data file(s) for a given quarter. I don't believe we have a widespread problem with sections being left off when they're required so I think it's safe to assume that if any file has been submitted, others likely have as well. (We have future notifications backlogged for "You didn't submit section x" type messaging)
> 
> I like the idea of only notifying submitters, but I lean: notify everyone at an STT given that we'll never have a perfectly accurate handle on who those submitters will be given churn and coverage during leave for normal submitters.

Adding the questions that @andrew-jameson for @ADPennington on our next TDP UX Sync

**Comment by ttran-hub** [comment]
> Templates have been added and can be viewed on the [TDP-HTML-Email-Demo-Environment](https://github.com/reitermb/TDP-HTML-Email-Demo-Environment)
> 
> 1. [deadline-approaching-no-submission-5days.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-approaching-no-submission-5days.html)
> 2. [deadline-approaching-part-submission-5days.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-approaching-part-submission-5days.html)
> 3. [deadline-passed-no-submission.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-passed-no-submission.html)
> 4. [deadline-passed-part-submission.html](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/deadline-passed-part-submission.html)
>    ![Screenshot 2024-04-29 at 10 44 32 AM](https://private-user-images.githubusercontent.com/106103383/326535511-6393351d-a6fe-44b6-8ec1-607c9d7e88ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTM0NDMsIm5iZiI6MTcxNDQxMzE0MywicGF0aCI6Ii8xMDYxMDMzODMvMzI2NTM1NTExLTYzOTMzNTFkLWE2ZmUtNDRiNi04ZWMxLTYwN2M5ZDdlODhiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNzUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTFlZDhkODY0ZmM1ZmMxMzdiZjE5Mzg3YzY0MzlhYTk5ZDRmOGQwMmQ1YjM3MTgxODVkZGJiMWQ1MGIwZTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.USuf6WShpMI1cbnx-3YOUDkLdQblO3ECMcfDCNkckzc)
>    ![Screenshot 2024-04-29 at 10 44 07 AM](https://private-user-images.githubusercontent.com/106103383/326535527-dc13fff6-8f22-4cc4-b159-d01963a0ac79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTM0NDMsIm5iZiI6MTcxNDQxMzE0MywicGF0aCI6Ii8xMDYxMDMzODMvMzI2NTM1NTI3LWRjMTNmZmY2LThmMjItNGNjNC1iMTU5LWQwMTk2M2EwYWM3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNzUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjZhODNjMjdmZTQzOTVlZjBiMzRkYjYzMWY1MTU5MzM3OTZiYmNjMDFlMjRmMjc0ZTk0MDQ4MDU4Y2JkYjZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rIRzM13Q7E1MheSzryOjSzw2zUptzFnmW3Tv0xjosXk)
>    ![Screenshot 2024-04-29 at 10 43 46 AM](https://private-user-images.githubusercontent.com/106103383/326535533-6dd63600-7bff-41ac-972c-c36106572f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTM0NDMsIm5iZiI6MTcxNDQxMzE0MywicGF0aCI6Ii8xMDYxMDMzODMvMzI2NTM1NTMzLTZkZDYzNjAwLTdiZmYtNDFhYy05NzJjLWMzNjEwNjU3MmYyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNzUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjc0Y2Y2ZDQ1YTI3ODI2YjMwZGE2ZTI0YzE5ZjE3ZWViOTYwM2E4ZDYzYTRjYjgwMjAxOWJhZjBjZmQzYTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UYLy_UwSOWTS78C28x30IHZ30FAcfzy-RkuulQfihnc)
>    ![Screenshot 2024-04-29 at 10 43 13 AM](https://private-user-images.githubusercontent.com/106103383/326535538-e678ac38-6d37-463b-af61-5b83fea01de6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTM0NDMsIm5iZiI6MTcxNDQxMzE0MywicGF0aCI6Ii8xMDYxMDMzODMvMzI2NTM1NTM4LWU2NzhhYzM4LTZkMzctNDYzYi1hZjYxLTViODNmZWEwMWRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxNzUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2U1YTc3Y2I0ZmU4NmM1YTE3NjlkMDZiNzY0MDZkZmNkN2YzYWMxODNkNTQ4MzliNDVjYjRlNzM0NjEzY2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M98aHYp1npli1wP2z2mgTq7rVtZ6mxDBtelVejol0iA)

Thanks @victoriaatraft @reitermb for including the screenshots. a11y looks good! 🚀

**Comment by lfrohlich** [comment]
To discuss in implementation : when to send past-due notices? Notify everyone or just submitters?  Default to everyone. Ready to close when follow on dev tickets are spun up @reitermb @victoriaatraft

**Comment by victoriaatraft** [comment]
> To discuss in implementation : when to send past-due notices? Notify everyone or just submitters? Default to everyone. Ready to close when follow on dev tickets are spun up @reitermb @victoriaatraft

@lfrohlich follow on dev tickets: [#2984](https://github.com/raft-tech/TANF-app/issues/2984) and refined [#2473](https://github.com/raft-tech/TANF-app/issues/2473)

**Comment by lfrohlich** [comment]
Thank you! Good to close
