### ISSUE TITLE
SPIKE: Investigate using separate databases/buckets in shared services in the Cloud.gov dev space

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1347]
**Description:**
Currently the `tanf-dev` Cloud.gov space uses shared services for S3 and RDS across all 4 dev environments. This frequently causes issues with changes from one environment negatively affecting another. For example, if doing work on the Django Admin staticfiles any following deployments will overwrite the static files in S3 and cause errors on the working branch. Additionally, this happens for RDS when we run migrations against the shared DB and it causes errors on other deployments that don't have the matching models.

We have a service quota of 10 service instances per space so we're kinda locked into using shared services for all the dev environments. However, there's no reason that they couldn't use separate databases inside of the same RDS service or different buckets within the same S3 services.

The purpose of this spike will be to investigate the lift required to make this work, and determining whether or not it is worth the effort involved.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Development tasks needed to complete this have been identified
- [x] Time estimate of all work needed
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Determine if we could use Terraform to provision multiple databases and buckets within the respective services.
- [x] Determine if we need to use a database template for RDS databases to prevent needing to reconfigure users for each database or if there is an alternate path to do so.
- [x] Determine how to reference the correct databases/buckets in Django settings modules that pull information from Cloud.gov bound services
- [x] Create a diagram to document the proposed solution [link](https://github.com/raft-tech/TANF-app/tree/b72404fd3e8c65f28af44cc31f99f7a4812f4e18/docs/Technical-Documentation/diagrams
)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

Timebox: 4-6 hours

**Supporting Documentation:**

**Open Questions:**
- How do we ensure we don't need to recreate all role-permissions structures?
- How can we best templatize this?

**Comment by abottoms-coder** [comment]
Just realizing I haven't closed this out officially. I spoke with John Willis on these points and we do not intend to keep the databases in sync or anything. We could do a one-time table dump of the relevant users and associated permissions so we don't have to manually do that 4+ times for each new environment's database. We can then load in that dump so user-role relationships are maintained moving forward. Rather than having to figure out how to best get direct database access in our deployment scripts or something, we can just run a django migration in the dev spaces to set these data to our preferred state.

**Comment by ADPennington** [comment]
@abottoms-coder are there follow-on tickets beyond #1407 associated with this spike?

**Comment by abottoms-coder** [comment]
> @abottoms-coder are there follow-on tickets beyond #1407 associated with this spike?

Not presently, they should be created. I'll try to get them in before backlog refinement today
