### ISSUE TITLE
Elasticsearch Implementation

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1348]
**Description:**
As decided in https://github.com/raft-tech/TANF-app/issues/1289 we are going to utilize Elasticsearch to store parsed data from submissions uploaded by users. This epic will house all the required tasks to deploy and configure Elasticsearch within our Cloud.gov environments.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Elasticsearch is deployed to each Cloud.gov space and accessible by the relevant backend applications
- [ ] Elasticsearch can only be accessed directly from within Cloud.gov
- [ ] Kibana is accessible from outside of Cloud.gov to only authenticated users with the relevant permissions
- [ ] Data can be sent from tdrs-backend to Elasticsearch for ingestion
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

See issues linked to this Epic.

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by riatzukiza** [comment]
While working on 1545 we ran into a route limit, and we solved it by removing the currently unused elastic search demo route. http://tdp-elastic-demo.app.cloud.gov/

**Comment by raftmsohani** [comment]
@robgendron this is the grandfather epic for elastic search. We should attach the other issues here
