### ISSUE TITLE
Terraform: Automate Deployment of Elasticsearch

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1349]
**Description:**
For each Cloud.gov space we need to update the Terraform configuration files to deploy the [AWS Elasticsearch](https://cloud.gov/docs/services/aws-elasticsearch/) service. The plan used should be `es-dev` for `tanf-dev` and `tanf-staging`, while `tanf-prod` should use the `es-medium-ha` plan.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Terraform automatically provisions Elasticsearch for each Cloud.gov space
- [ ] Appropriate plans are used per space
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update Terraform configuration files to deploy Elasticsearch to Cloud.gov
- [ ] Bind the deployed service to any app in Cloud.gov and confirm it can be reached via cURL from the Cloud.gov app (ssh)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by stevenino** [comment]
This is data agnostic

**Comment by robgendron** [comment]
Preparing for QASP
