### ISSUE TITLE
As an OFA staff member, I want to be able to access Kibana from TDP

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1350]
**Description:**
The Cloud.gov AWS Elasticsearch service is hosted behind a VPC inside of the AWS GovCloud and as such is inaccessible to connections from outside of that internal network. In order to allow access to OFA staff we will need to deploy a proxy application to Cloud.gov alongside our regular app deployments. This proxy will need to handle authenticating users against our existing TDP authentication system(s) and confirm they have the relevant authorization to view the data. Since this service will only be exposed to the most privileged users, we should enforce PIV card usage before access is granted in production. Regardless of the user's role, the data stored in ES indices should be treated as *READ ONLY*.

For the purposes of this ticket, OFA staff members refers to the groups `OFA Admin` and `OFA System Admin`.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] In the `tanf-prod` space, Kibana can only be accessed by OFA staff members with a PIV card.
- [ ] Kibana can be accessed by OFA staff members with or without a PIV card *OR* members of the `Developers` group in the `tanf-dev` or `tanf-staging` space.
- [ ] No data stored within Elasticsearch indices can be modified by users.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create or implement a proxy that exposes a route to Kibana deployed in Cloud.gov
- [ ] Enforce authentication at the proxy layer before allowing the connection to Kibana
- [ ] Create a manifest to deploy the proxy in Cloud.gov
- [ ] Update Circle CI deployment jobs to also deploy the proxy
- [ ] Determine how to enforce read-only views of the data
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- This [proxy](https://github.com/santthosh/aws-es-kibana) is a very minimal implementation of what we are trying to do here, we could potentially fork it and extend it for our purposes.
- GSA provides an [example](https://github.com/GSA/datagov-logstack) we could utilize for inspiration here that utilizes the above linked proxy.

**Supporting Documentation:**
- [OIDC auth](https://www.elastic.co/guide/en/elasticsearch/reference/current/oidc-realm.html)
- [Native user](https://www.elastic.co/guide/en/elasticsearch/reference/current/native-realm.html)
- 
**Open Questions:**
- Do we need the proxy or can we use native users/OIDC?

**Comment by stevenino** [comment]
This is data agnostic

**Comment by jtimpe** [comment]
Notes on the proxy configuration: https://gist.github.com/jtwillis92/a6840a412676fc2d3f58c0dccbf10da1#aws-proxy-layer

**Comment by n0remac** [comment]
This could be useful 
https://www.codementor.io/@samueljames/using-django-with-elasticsearch-logstash-and-kibana-elk-stack-9l4fwx138
