### ISSUE TITLE
Elasticsearch - Define Index Mappings (TANF Section 1)

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1351]
**Description:**
For all of the file formats outlined in the [data validation epic](https://github.com/raft-tech/tanf-app/issues/86) we will need to define how we will store these in Elasticsearch. ES stores data in indices, roughly analogous to a table in SQL. Each of these has an associated mapping, which can be auto-generated on data ingestion. The purposes of this ticket will be to define what indices will be needed and what data type each of the fields stored within will be.

Fields for each submission type are defined in the relevant transmission format documents (ex. [Section 1](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_report_section1_10_2008.pdf)). However, the data stored will be parsed by this point so we needn't stick to the same data types used in the transmission formats. Instead we should normalize these types so they can better express the data stored in a human-friendly format.

An example of a JSON representation of parsed data can be found [in this gist](https://gist.github.com/jtwillis92/50dd8f578b78ff1c4a9343a28958d338) and may be helpful in deriving the final format.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Each section / transmission format has an associated [index template](https://opensearch.org/docs/opensearch/index-templates/)
- [ ] We have a way to automatically configure Elasticsearch with these templates
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

The easiest way to create these index templates would be to POST a JSON representation of the data to a new index and then modify the auto-generated template, but they could also be written manually.

- [ ] Determine all indices needed
- [ ] Determine fields wanted for each index along with their data type
- [ ] Ensure field definitions are consistent across indices (will lead to greater flexibility with wildcard index-patterns).
- [ ] Create index templates for each relevant transmission format
- [ ] Implement a mechanism to automatically configure Elasticsearch with the created index templates
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by jtimpe** [comment]
[#1289](https://github.com/raft-tech/TANF-app/issues/1289)
https://gist.github.com/jtwillis92/a6840a412676fc2d3f58c0dccbf10da1

**Comment by stevenino** [comment]
@ADPennington ready for QASP
