### ISSUE TITLE
Create ADR to document decision to move forward with Elasticsearch

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1353]
**Description:**
As discussed in [this comment](https://github.com/raft-tech/TANF-app/issues/1289#issuecomment-924973994) on the ES spike we need an ADR to document the decision to move forward with this solution.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Elasticsearch ADR is committed to the repo
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add a new ADR with findings from the ES spike
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
@abottoms-coder to work on this issue during current sprint. per backlog refinement 1.11.22.
