### ISSUE TITLE
Implement storage of parsed data in Elasticsearch

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1354]
**Description:**
Using the queuing system introduced in #1352 we will need to provide Django with the ability to index documents in Elasticsearch as they are parsed from uploaded Data Files. Once the file has been successfully parsed into a dictionary / JSON format the backend should queue a job which will ingest the data into Elasticsearch.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Parsed data gets ingested in to Elasticsearch via a queued job
- [ ] Parsed data is searchable immediately after ingestion
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement an Elasticsearch client in the Django backend
- [ ] Create a job that ingests data directly into Elasticsearch
- [ ] Update existing Data File processing to queue above job after the file has been successfully parsed
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- [Official ES Python client](https://elasticsearch-py.readthedocs.io/en/master/)

**Supporting Documentation:**

**Open Questions:**

**Comment by andrew-jameson** [comment]
How to get fancy with our data storage:
https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/advanced_usage_examples.html#sample-document

Credit to @jtimpe

**Comment by lfrohlich** [comment]
@Smithh-Co if a PR isn't merged, we should note why this was closed. Per @ADPennington it was covered in #1351 and #132 instead and we decided to close last week in backlog refinement

**Comment by Smithh-Co** [comment]
@lfrohlich Hey Lauren, great call out - apologies, missed adding the notation here.
