### ISSUE TITLE
Research questions around DIGIT teams query usage for parsed data

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1355]
**Description:**
The DIGIT team currently runs manual SQL queries to pull data from the legacy TANF systems. We'd like to determine the equivalent for each of these once the data will be stored in Elasticsearch. Ideally we could create Saved Searches in Kibana to fulfill these queries and then users would be able to simply select the data they want to see from a list of pre-defined searches.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Any manual SQL queries used by DIGIT staff have been identified
- [ ] Saved Searches are created for each of the above SQL queries
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Construct a list of research questions to send to the DIGIT team
- [ ] Using the answers provided, determine all manual SQL queries used
- [ ] Convert the SQL queries to the appropriate formats to work as Saved Searches in Kibana
- [ ] Implement a process to create these saved searches on each deployed ES instance.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by stevenino** [comment]
This will be a joint effort by Andrew, UX, Product, and Alex. It will be require an informal Q&A session being facilitated by Alex.

**Comment by stevenino** [comment]
This is data agnostic

**Comment by robgendron** [comment]
May be closed out after Research Synthesis (#3078) findings @reitermb.

**Comment by robgendron** [comment]
Deemed closed by team.
