### ISSUE TITLE
As tech lead, I need a new permissions group for ACF OCIO 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1358]
**Description:**
As we are now storing our ZAP scans, we need to give OCIO read access to them. The simplest way to do so is to create a new group with access only to our ZAP and ClamAV logs and objects.

**Acceptance Criteria:** 
- [ ] New ACF OCIO group is created in our database by default
- [ ] New group does not have STTs nor Regions associated to it
- [ ] ACF OCIO group should have read-only access to DAC security [scans](https://tdp-backend-staging.app.cloud.gov/admin/security/) (e.g. OWASP scans, ClamAV scans)
- [ ] ACF OCIO group should not have access to view other areas of DAC nor the Frontend where feasible
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Migration for creation of this new group by default
- [x] Exhaustive listing of relevant permissions for accessing backend security forms and objects
- [x] Relevant user instantiation excludes STTs and Regions
- [ ] Document group permissions matrix in [this Readme](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/user_role_management.md)
- [ ] User-facing documentation for how ACF OCIO staff can login to DAC/Security and access objects (scan pdfs, ClamAV log entries)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Current permissions matrix](https://github.com/raft-tech/TANF-app/issues/888#issuecomment-869937943)

**Open Questions:**
- Can these users be easily redirected straight to the backend after authentication?

**Comment by valcollignon** [comment]
This issue has been refined from the dev standpoint.

**Comment by jorgegonzalez** [comment]
> ACF OCIO users should be enforced to utilize PIV card via new AMS integration

Question about this AC, will ACF OCIO all have `@acf.hhs.gov` email addresses? In which case this AC may already be satisfied @ADPennington @abottoms-coder

**Comment by abottoms-coder** [comment]
> > ACF OCIO users should be enforced to utilize PIV card via new AMS integration
> 
> Question about this AC, will ACF OCIO all have `@acf.hhs.gov` email addresses? In which case this AC may already be satisfied @ADPennington @abottoms-coder

I would expect this assumption is valid and this AC is satisfied.

**Comment by abottoms-coder** [comment]
> Can that AC be removed from this ticket then, if we agree it is satisfied?

@ADPennington Are you ok with this?

**Comment by ADPennington** [comment]
removed @jorgegonzalez @abottoms-coder

**Comment by jorgegonzalez** [comment]
Just saw this

> Can these users be easily redirected straight to the backend after authentication?

If so, do we intend for users in this group to never see the frontend? Redirecting them straight to Django Admin reduces the added complexity of validating this on the frontend. So if that is the desired behavior, I'm updating the PR to support this shortly @ADPennington @abottoms-coder

**Comment by ADPennington** [comment]
@jorgegonzalez -- @lfrohlich and I just discussed and can confirm that this permission group can be redirected back to security url in DAC. they dont need to do anything on the frontend. maybe access to the profile page, but only if its easy. cc: @abottoms-coder

**Comment by reitermb** [comment]
Demoed by @jorgegonzalez  on 3/15/2022
