### ISSUE TITLE
As Tech Lead, I want secret keys automatically rotated for offboarding

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1362]
**Description:**
We want to rotate secret keys in an automated fashion when offboarding Raft staff.

**Acceptance Criteria:** 
- [ ] Automation trigger is via a merge to HHS main
- [ ] Rotation only occurs on tanf-staging space
- [ ] Terraform service account will perform our relevant Cloud Foundry tasks
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] DJANGO_SECRET_KEY, JWT_KEY, JWT_CERT env var are rotated with a new randomly generated string
- [ ] Add new terraform flow to redeploy staging with new env var upon HHS merge
- [ ] Add CircleCI flow/job to send email notification to update JWT_CERT in Login.gov manually
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- This is a follow-on from #1004  

**Supporting Documentation:**
- https://cloud.gov/docs/ops/runbook/rotating-iam-users/
- https://www.youtube.com/watch?v=86wfgNK_0o4

**Open Questions:**
- Would this need to be redone when we have a production space and not just staging?

**Comment by lfrohlich** [comment]
Reposting from @ADPennington's epic comment: #1362 is the final ticket to address to close out this epic, and there is a suggestion in this ticket about building off of #1379 work, which makes me wonder if more research is needed to develop a strategy for 1362. If so, then I would suggest also shifting it down in the roadmap and creating a new ticket for us to manually rotate all secret keys before closing out Release 1 and fully documenting our manual process to be implemented quarterly. The priority of this alternative ticket would be after we've completed all authentication-related integration work. Thoughts on this?

**Comment by robgendron** [comment]
Deemed no longer needed by @ADPennington
