### ISSUE TITLE
As Tech Lead, I want secret keys rotated quarterly

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1363]
**Description:**
As a best practice, we'd like to keep the application fresh and secure by rotating the secret key once a quarter.

**Acceptance Criteria:** 
- [ ] DJANGO_SECRET_KEY env var in cloud.gov is rotated once per quarter in the staging space
- [ ] JWT_KEY and JWT_CERT must be rotated as well
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] If possible, leverage the tooling in #1362 
- [ ] If ancillary tools are needed besides Terraform, create a CircleCI build to trigger timing
- [ ] Again, CircleCI send e-mail to dev team to update JWT_CERT in Login.gov
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] Document manual process for updating login.gov to be in the contents of the email

**Notes:**
JWT_KEY is only changed on initial deploy meaning that's more of a lift since we have rolling deploys by default.

**Supporting Documentation:**

**Open Questions:**
- Does Terraform have cron-like behavior?

**Comment by valcollignon** [comment]
Ticket should be updated to reflect manual process per backlog refinement 12.7.21
CC: @ADPennington

**Comment by jtwillis92** [comment]
Manual process is documented here: https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/jwt-key-rotation.md

**Comment by jtwillis92** [comment]
Discussed in dev sync and the practical way to approach this is by doing these rotations manually.

The process for DJANGO_SECRET_KEY rotation could be completed with the following command:
```
./scripts/set-backend-env-vars.sh $CGAPPNAME_BACKEND $CG_SPACE
```
example:
```
./scripts/set-backend-env-vars.sh tdp-backend-raft tanf-dev
```

NextGenXMS will likely follow a similar approach to ACF AMS where the JWK_KEY and JWT_CERT are managed by them and therefore the rotation cannot be automated from TDP.
