### ISSUE TITLE
Fine tune OWASP ZAP Scanner usage

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1367]
**Description:**
Currently we use the [ZAP Full Scan](https://www.zaproxy.org/docs/docker/full-scan/) for both the frontend and the backend ZAP reports. However, this leads to us not covering all potential URLs with ZAP scans - potentially causing missed alerts (that is unconfirmed though).

For the backend we are not effectively scanning all URLs present in the application. As noted [in this ZAP blog post](https://www.zaproxy.org/blog/2017-04-03-exploring-apis-with-zap/) APIs cannot be effectively crawled with standard spidering techniques. This leads to a large untouched attack surface for the backend specifically, as only 4 URLs are found by the ZAP full scan:
```
zap@6e73ead26b61:/zap$ ./zap-full-scan.py -t https://tdp-backend-staging.app.cloud.gov
2021-10-06 20:15:41,905 Could not find custom hooks file at /home/zap/.zap_hooks.py 
Got URLS: ['https://tdp-backend-staging.app.cloud.gov', 'https://tdp-backend-staging.app.cloud.gov/', 'https://tdp-backend-staging.app.cloud.gov/robots.txt', 'https://tdp-backend-staging.app.cloud.gov/sitemap.xml']
Total of 4 URLs
```
These URLs are mostly not even relevant to our API so they miss all of the major Django functionality. If we instead use the [ZAP API Scan](https://www.zaproxy.org/docs/docker/api-scan/) we can leverage the OpenAPI spec provided by drf-yasg2 at `/swagger.json` to define all of the URLs that ZAP will scan. This will cause it to run scan rules against relevant API endpoints and confirm that there are no vulnerabilities present. Note this scan takes much longer to complete than the backend scan typically does, which is a symptom of the scans not really doing much on the backend at this time.

For example, here are the URLs found with the API scanner:
```
zap@6e73ead26b61:/zap$ ./zap-api-scan.py -t https://tdp-backend-staging.app.cloud.gov/swagger.json -f openapi
2021-10-06 20:08:06,858 Could not find custom hooks file at /home/zap/.zap_hooks.py 
2021-10-06 20:08:17,920 Imported URLS: ['https://tdp-frontend-staging.app.cloud.gov', 'https://tdp-backend-staging.app.cloud.gov', 'https://tdp-backend-staging.app.cloud.gov/swagger.json', 'https://tdp-backend-staging.app.cloud.gov/v1', 'https://tdp-backend-staging.app.cloud.gov/v1/auth_check', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/?stt=1.2&quarter=quarter&year=1.2&page=10', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/10', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/10/', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/10/download', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/10/download/', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/years', 'https://tdp-backend-staging.app.cloud.gov/v1/data_files/years/stt', 'https://tdp-backend-staging.app.cloud.gov/v1/login', 'https://tdp-backend-staging.app.cloud.gov/v1/logout', 'https://tdp-backend-staging.app.cloud.gov/v1/logs', 'https://tdp-backend-staging.app.cloud.gov/v1/logs/', 'https://tdp-backend-staging.app.cloud.gov/v1/roles', 'https://tdp-backend-staging.app.cloud.gov/v1/roles/', 'https://tdp-backend-staging.app.cloud.gov/v1/stts', 'https://tdp-backend-staging.app.cloud.gov/v1/stts/', 'https://tdp-backend-staging.app.cloud.gov/v1/stts/alpha', 'https://tdp-backend-staging.app.cloud.gov/v1/stts/by_region', 'https://tdp-backend-staging.app.cloud.gov/v1/users', 'https://tdp-backend-staging.app.cloud.gov/v1/users/id', 'https://tdp-backend-staging.app.cloud.gov/v1/users/id/', 'https://tdp-backend-staging.app.cloud.gov/v1/users/set_profile', 'https://tdp-backend-staging.app.cloud.gov/v1/users/set_profile/']
2021-10-06 20:08:17,920 Number of Imported URLs: 29
Total of 152 URLs
```

On the frontend side we are not utilizing the [Optional AJAX Spider](https://www.zaproxy.org/docs/desktop/addons/ajax-spider/) which is fined tuned to work with Single Page Applications that make use of AJAX (Asynchronous JavaScript and XML) calls- which we do via the `axios` library usage. Per the [configuration options](https://www.zaproxy.org/docs/desktop/addons/ajax-spider/options/) this would allow us to crawl further depths in the application and test things like form submissions and button clicks for any potential vulnerabilities.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] ZAP performs an API Scan using the OpenAPI spec for the backend to scan the proper Django API URLs.
- [x] ZAP uses the AJAX Spider when running tests against the frontend.
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update the zap-scanner script to be able to call a different ZAP scan script based on the `$TARGET` argument passed to the script:
  - [x] `zap-full-scan.py` for the frontend
  - [x] `zap-api-scan.py` for the backend
- [x] Update the zap-scanner script to pass in additional arguments to the ZAP script to enable the AJAX spider for the frontend.
- [x] Update the zap-scanner script to pass in additional arguments needed to the ZAP API Scan script for the backend. 
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

- This is separate from using the baseline script for CI runs of this script and is mostly relevant to the nightly scans against deployed sites. The `zap-api-scan.py` script also has the ability to support baseline scans by passing the `-S` argument to the script invocation, which we should do as part of a forthcoming issue noted in #1326 

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
Demo by @jtwillis92 - 11.9.21
