### ISSUE TITLE
Split up circleCI config

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1373]
**Description:**
To facilitate more easily working on CircleCI in the future, we want to refactor the CircleCI config by splitting it into smaller files with cohesive vision on a set of functionality rather than one monolith file.

**Acceptance Criteria:** 
- [x] No changes in CircleCI flows and functionality
- [x] Main CircleCI configuration file line count is cut down significantly
- [x] New files are organized as logical/cohesive  set of related functionality
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [ ] Workflows and Parameters sections remain in the main config.yml
- [ ] Move Commands section into at least one utility library, where feasible
- [ ] Move all secrets-check definitions into a library
- [ ] Move all test-frontend and test-backend definitions into a common library
- [ ] Move nightly OWASP scan into library
- [ ] If possible, split deploy-* jobs into their own file with any necessary dependent definitions
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- We might be able to abstract certain parts into custom orbs via [this recent blogpost](https://circleci.com/blog/circleci-private-orbs/?utm_source=email&utm_medium=email-link&utm_campaign=private-orbs&utm_term=product&mkt_tok=NDg1LVpNSC02MjYAAAGEcReVcLlQy6ucTNzatb2DANixu6ERa-WJtVy_olQmQp7uxINvCexmtwdRemEfy82MX8_JjB5jXrJBRPsUjlsqbrrJhQSmiwE8vAUFAVSmQa9S0Q)

**Open Questions:**

- _Open Question 1_
- Can we simply nest includes like include secrets-check in test*ends library and no include needed in main config?
- What limitations are there for removing the Commands section?

**Comment by abottoms-coder** [comment]
@riatzukiza Fyi, ticket created
