### ISSUE TITLE
Resubmission Research Project Impact Session

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1376]
**Description:**
Completes resubmission research. Facilitates group synthesis of research, useful ticketing from validated user stories & project impacts, and dev/design syncing on any mockups generated from research. 

**AC:**
- [x] User stories are documented
- [x] Other project impacts are documented
- [x] Dev/Design have discussed new designs
- [x] Ticketing resulting from workshop is documented.

**Tasks:**
- [x] Transfer impacts/stories/post-research mockups to a workshop (likely Mural and/or Hack.md)
- [x] Schedule workshop with backlog refinement team
- [x] Facilitate workshop
- [x] Document any additional stories/tickets created in the workshop
- [x] Refine and/or close dev tickets in #84
- [x] Prepare outcome/research content for presentation & discussion with whole team
- [x] Schedule whole team session

**DoD:**
 - [x] [Documentation](url) showing which tickets were created from which project impacts, stories and any new stories / project impacts that were co-created in the workshop
 - [x] @lfrohlich has reviewed and signed off

**Notes**
- Tickets from the Project Impact Sessions are added to [84](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/84) and [1494](https://github.com/raft-tech/TANF-app/issues/1494)
- User stories, project impacts and related tickets are documented in a [hackmd](https://hackmd.io/@_1LS3pAARp6wGUAvDgp7UA/Bk4xf-yyq)

**Comment by valcollignon** [comment]
Issue refined but still blocked by resubmission research sessions.

**Comment by sreedevip** [comment]
Is this ticket ready to be pushed to QASP? @reitermb @valcollignon

**Comment by valcollignon** [comment]
> Is this ticket ready to be pushed to QASP?
Are the ACs completed?

**Comment by sreedevip** [comment]
> > Is this ticket ready to be pushed to QASP?
> 
> Are the ACs completed?

Yes, they are

**Comment by valcollignon** [comment]
@sreedevip If the DoD is met and you and @reitermb feel this is complete, it can go to QASP. Thanks!

**Comment by lfrohlich** [comment]
V3

#1613 As a developer, I need parsed file metadata
#1612 As a user, I want to see detailed case information from version to version
#1610 As a user, I want to receive topline information about the completeness of my data from version to version
V2

#1609 As a user, I want to see a list of prior submissions for a quarter.

**Comment by reitermb** [comment]
Demoed by @reitermb on 3/1/2022
