### ISSUE TITLE
As a tech lead, I want cloud.gov users managed via Terraform

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1379]
**Description:**
Set up user management via Terraform variable files per the linked video.

**Acceptance Criteria:** 

- [ ] We can add/update/delete cloud.gov users from the terraform variables file via merge
- [ ] User file e-mails is kept secret/encrypted
- [ ] Terraform will trigger on any Terraform file change
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Create Terraform user management file per linked youtube video
- [ ] Encrypt user emails via [gitcrypt](https://github.com/AGWA/git-crypt) or equivalent tool
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- https://www.youtube.com/watch?v=86wfgNK_0o4

**Open Questions:**
- Do we redeploy apps when any change is made to users/roles files?

**Comment by ADPennington** [comment]
per 11/10 dev sync, we have decided to pause additional work on this ticket, given unknowns re: the appropriate permissions to assign to the service accounts that would be used to manage users. TDP sys admins are currently able to manage cloud.gov users manually using CF CLI and/or cloud.gov UI, so this is not a priority to tackle right now. we can revisit this in R2 if work is light cc: @riatzukiza 

@valcollignon since we're pausing on this, does it make sense to close this or just move to backlog?

**Comment by valcollignon** [comment]
@ADPennington Can we make a new ticket for the remaining work and put it into product backlog with an estimate of 3 and V2 Release? Then remove the remaining work from this ticket and close this one out?

**Comment by abottoms-coder** [comment]
Closing this due to technical infeasibility --  cloud environment stability would also be impacted.
