### ISSUE TITLE
As a System Admin, I should not be able to set conflicting STT and region attributes for a user

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1387]
Currently users can be created through the Django admin panel with both an STT and a region, but existing users cannot have a region and STT added to them at once.

# Acceptance Criteria
- [x] Users cannot be created through the admin panel with both an STT and a region assigned by System Admin
- [x] STT Data Analysts will have permissions based on their STT location
- [x] OFA Regional Staff will have permissions based on their region location
- [ ] The admin panel does not have options for system administrator to try to create a user
- [x] All other roles should have a null location
- [x] Profile frontend page infers "Federal Government" based on user's role
- [x] "Federal Government" stt value is removed from data both locally and in deployed environments.

# Tasks
- [x] Refactor our user model to have a single "Location" field which is a [GenericForeignKey per linked documentation](https://docs.djangoproject.com/en/dev/ref/contrib/contenttypes/#generic-relations)
- [x] Validate location input based on role (stt/region/federal) 
- [x] Alter frontend profile page for regional/federal roles
- [ ] Write new batch of tests for assigning users to roles and updating STT/Region fields and transitioning user from one role type to each other role type.

# References
https://docs.djangoproject.com/en/dev/ref/contrib/contenttypes/#generic-relations
https://www.webforefront.com/django/admincustomlayout.html#custom-fields-and-methods
https://www.webforefront.com/django/adminpermissions.html

**Comment by valcollignon** [comment]
@abottoms-coder to break out tasks per backlog refinement 11.16.21

**Comment by abottoms-coder** [comment]
I'd like to add some refactoring to the user models to simply not have fields for certain groups like Sys Admin shouldn't have the STT field. Speaking with @jtwillis92 , django has polymorphism for our models as shown here:
https://realpython.com/modeling-polymorphism-django-python/
https://django-polymorphic.readthedocs.io/en/stable/

**Comment by valcollignon** [comment]
Devs need to meet to revisit approach to this ticket. Per backlog refinement 11.23.21. @abottoms-coder to coordinate a meeting.

**Comment by valcollignon** [comment]
Removed draft status and @abottoms-coder to schedule a meeting today 11/30 or tomorrow 12/1.

**Comment by valcollignon** [comment]
Needs further refinement, per dev sync 12.1.21

**Comment by valcollignon** [comment]
Will discuss at next dev sync 1.7
CC: @ADPennington @riatzukiza

**Comment by abottoms-coder** [comment]
Refined but blocked by #1183

**Comment by abottoms-coder** [comment]
Discussed in Dev Sync 1/12, no longer blocked by #1183 or #652 but would like to work this closely with #1495 as ultimately that ticket will be displaying data rendered by the new location field described herein. Could those #149X tickets be pulled into Release 1 or this pushed to Release 2?

cc: @valcollignon @ADPennington

**Comment by valcollignon** [comment]
@reitermb to sync with @abottoms-coder and @riatzukiza to discuss design around this issue. Technical work will be discussed in dev sprint review tomorrow 1/19.

**Comment by reitermb** [comment]
Sync happened 1/19/2022

Discussed the data model and produced one additional version of the mockups for #653 to visualize the another variation that could result from the data model. [Mockups ](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=5892%3A48657) now include a version for Grantee users, a version for OFA admins, and a version for OFA regional staff—the difference from OFA admins being that their profiles will surface which region they belong to as well as highlighting that they're Federal Government users. 

cc: @valcollignon @ADPennington @riatzukiza @abottoms-coder

**Comment by riatzukiza** [comment]
I started work on this today, I have a model and migrations that work, the work now is to fix the existing tests. I've made some progress on the tests, but I am currently stuck on abstracting the factories.

I believe this is the solution I need:
https://stackoverflow.com/questions/65938206/django-factory-for-model-with-generic-foreign-key

**Comment by riatzukiza** [comment]
The model and validation to my current understanding of the problem are done, the tests have all been updated, I can confirm the behavior is working in the django shell. I have to work on the django admin page still, to provide a more user friendly message when trying to set invalid values. The frontend still has to be worked on, will try to get to that tomarrow after I go over everything on the backend again and write the tests for role switching

**Comment by riatzukiza** [comment]
We need to do research on what happens when roles change.

**Comment by ADPennington** [comment]
> We need to do research on what happens when roles change.

Some additional  context from 1/26 dev sync where this was discussed:

the AC (`System Administrator should be able to easily change a user's role without altering STT/region fields`) was removed for now until we have research and design work done to visualize the expected behavior for change requests. Changes to a user's role or affiliation seem unlikely based on current practices, but there are some edge cases (noted below) that could be investigated and accounted for in a later release (v4+). 
 
- Users belonging to a federal permissions groups (i.e. those that begin with "OFA"):
  - do not need an STT assignment, and it is not expected that this will ever change. 
  - their region affiliation could potentially change, especially in the scenario where they are affiliated with multiple regions. More research is needed to understand what functions they need (e.g. _access to reports within their region(s) only?_) 
  
- Users belonging to a non-federal group:
  - may need an STT assignment change, but it seems unlikely if they are maintaining the same email address since most users will have an email address that includes the STT name (e.g. someone@dc.gov). In this scenario, we'd probably want to deactivate their _old_ STT account and activate their _new_ STT account. An exception might be vendor staff (someone@deloitte.com) who could theoretically move from one STT agency to another -- this seems like an edge case but another topic for research. Another edge case is when a user is submitting data on behalf of multiple STTs (e.g. state and a tribe). This can likely be resolved with onboarding training, but we will defer to research. 
  - when an STT does change for a user, the region should already be accounted for dynamically based on the [STTs model](https://tdp-backend-staging.app.cloud.gov/admin/stts/stt/2898/change/) 
- At some point, we're going to need a change request form for existing users to ask for a change in their account status, affiliation, or role. Most common scenario will likely be deactivation. Currently, for TDRS, the person requesting deactivation is usually also the person requesting activation for a new account, but since TDP requires account setup first for new requests, the request flow for TDP deactivation may require divorcing these two requests.  Another research topic. 

cc: @reitermb @abottoms-coder @riatzukiza @lfrohlich

**Comment by abottoms-coder** [comment]
Per tabletop discussion from #1495 , we will need to delete the "Federal Government" stt data value and handle it in this ticket. We might need to rework the frontend profile page from #1495 to infer "Federal Government" based on user's role. I have added this to the acceptance criteria of this ticket as well.

**Comment by ADPennington** [comment]
@riatzukiza @abottoms-coder do we know why this ticket is still open? the PR has been merged.

**Comment by lfrohlich** [comment]
This is complete with PR #1572

**Comment by reitermb** [comment]
Demoed by @riatzukiza on 3/1/2022
