### ISSUE TITLE
[Design] Notification Documentation for Deactivation

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1395]
**Description:**
We need to add two notifications to existing documentation to capture deactivation due to inactivity in TDP scenarios. 

**AC:**
- [ ] You're about to be deactivated notification is documented
- [ ] You've been deactivated notification is documented
- [ ] Details about what triggers each notification are documented 

**Tasks:**
- [ ] Find a place for this documentation to live (possibly an existing user flow?)
- [ ] Add notification documentation

**Notes:**
- Notifications for activation, access request confirmation covered in Access Req Epic

**Comment by reitermb** [comment]
Now closeable with the addition of #1462 @lfrohlich

**Comment by valcollignon** [comment]
Closing per backlog refinement 12.14.21
CC: @lfrohlich
