### ISSUE TITLE
git-secrets is not run

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1406]
**Description:**
Current runs show the following during the script runtime:
```git: 'secrets' is not a git command. See 'git --help'```

We need to correct this as a direct call to /tmp/git-secrets/git-secrets doesn't appear to be working and the local shell is trying to call the `git` binary in it's path instead.

Example of the failure [here](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/5682/workflows/48e62539-333e-40d2-b1ed-b807f5779410/jobs/12619/parallel-runs/0/steps/0-102).

**Acceptance Criteria:** 
- [ ] git-secrets is actually run in pipelines
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Correct pathing so git-secrets is called correctly
- [ ] Add check for failure of previous command (e.g., `if [ $? -ne 0 ]` or `set -e`)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
