### ISSUE TITLE
[Research] Code docs synthesis of Resubmission Research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1418]
**Description:**
Delivers written synthesis of Resubmission Epic research sessions

**AC:**

- [ ] PR has been opened to raft-tech
- [x] Synthesis doc reflects team practices documented in the [Design Guide](https://github.com/HHS/TANF-app/blob/main/docs/Design/Design-Guide.md#code-docs)
- [x] Synthesis doc contains sections overviewing who we talked to, what we did, what we tested, what we learned, and what's next.
- [ ] Project impacts (From UX and from cross functional project impact #1376 session) are mapped to synthesis themes

**Tasks:**
- [x] Gather all notes and fill in gaps with video recording
- [ ] Delete video recording once notes are complied
- [x] Anonymize data
- [x] Perform topline synthesis
- [x] Document synthesis - add sections for overviewing who we talked to, what we did, what we tested, what we learned, and what's next.
- [x] Draft in hack.md

DoD:
 - [ ] PR is opened to raft tech
 - [x] [Hack.md](https://hackmd.io/V97U7lN9RbGz-yUIaF1thQ) draft exists and has been shared with reviewers
 - [ ] @lfrohlich has reviewed and signed off

**Notes**
Sessions notes and synthesis on [Mural ](https://app.mural.co/invitation/mural/raft2792/1636553956757?sender=ubd396cc6b85e21cc46468665&key=2dee8424-0902-4cb4-b24e-ec30a40e24c6)board

**Comment by valcollignon** [comment]
All tasks are underway... pending at least one more research session.

**Comment by lfrohlich** [comment]
@reitermb @sreedevip please add the link to the hack.md to this ticket

**Comment by sreedevip** [comment]
Link added to the DoD section @lfrohlich

**Comment by lfrohlich** [comment]
@reitermb @sreedevip Alex has said she doesn't need to review. Can you open the PR?

**Comment by reitermb** [comment]
> @reitermb @sreedevip Alex has said she doesn't need to review. Can you open the PR?

Yes—we have I think three links to fix and it should be good to go (tested in this branch: https://github.com/raft-tech/TANF-app/blob/1269-add-fall-2021-research-synthesis/docs/User-Experience/2021%2C%20Fall%20-%20Investigating%20Partial%20Submission%20%26%20Evaluating%20TDP%20Submission%20History.md) 

I just wanted to confirm it makes sense to PR/Merge this into the current top level UX folder and then handle migrating _all_ syntheses at once into their new subfolder in a separate PR (alongside other docs changes we've discussed). Lots of PRs in the air so I didn't want to create any merge conflicts. cc @ADPennington

**Comment by lfrohlich** [comment]
Per Standup Alex is on board with opening the PR to where they usually live and then we'll move in bulk later.

**Comment by reitermb** [comment]
@lfrohlich PR is opened!

https://github.com/raft-tech/TANF-app/pull/1546

**Comment by valcollignon** [comment]
Demo'd 1.18.22 by @reitermb and @sreedevip

**Comment by valcollignon** [comment]
Closing per discussion at standup on 1.19.22. Linked to #1546.
