### ISSUE TITLE
Pa11y screenshots not reflecting correct pages

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1425]
**Description:**
As seen in this [Circle CI Build](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/5733/workflows/afb42356-66bb-4140-9779-b329f73ff85f/jobs/12761/artifacts) pa11y is showing success for builds but all of the stored artifacts are just screenshots of the "You must log in" page. It seems that the fixes we put in in #1044 are no longer working as they once did.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Pa11y screenshots all correlate to the correct pages
- [ ] If Pa11y cannot get the correct screenshot, we should investigate possibilities to fail the build
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Fix Pa11y screenshot errors
- [ ] Implement (Cypress?) unit test(s) to check for an element we can only see via "automatic" login to ensure pa11y can always get "logged in"
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
- Can we implement the unit test via an method other than Cypress to still allow #1427?

**Comment by riatzukiza** [comment]
update on the state of this, I tested everything and in the pr the bug is gone, and the pa11y checks appeared to catch problems, but after I created an error I haven't gotten it out of that state. I put it down to look at script readme, then we had ceremonies.

**Comment by riatzukiza** [comment]
The above problem was solved, we're just waiting on a review from @abottoms-coder

**Comment by valcollignon** [comment]
demo by @riatzukiza 12.7.21

**Comment by ADPennington** [comment]
closing per #1454

**Comment by ADPennington** [comment]
just realizing it isnt merged yet. re-opening.

**Comment by riatzukiza** [comment]
Where is this right now? I think its merged now @ADPennington @abottoms-coder

**Comment by abottoms-coder** [comment]
> Where is this right now? I think its merged now @ADPennington @abottoms-coder

Yes, was merged [here](https://github.com/raft-tech/TANF-app/pull/1454/commits/08e017ae22024e83dae676cc85c46f3522a2a23e)

**Comment by ADPennington** [comment]
i thought maybe this would close automatically upon merge. but closing now (again) @abottoms-coder @riatzukiza 🚀
