### ISSUE TITLE
Remove Cypress tests from the CI process

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1427]
**Description:**
While working through #880 with @ADPennington we discussed how the current Cypress tests aren't really testing any core functionality of the app and haven't been updated in over a year. These steps add extra overhead to the frontend build process and require coordinating the chromium package shared with the pa11y tests.

We suggest removing this step from CI for now, until a later date when we either add more Cypress tests or implement a replacement integration testing suite.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] CI builds no longer run Cypress tests or associated build steps
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Remove `test-frontend` step `Install lib bindings for Cypress`
- [x] Remove `test-frontend` step `Run Cypress Integration Tests`
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
lower priority. need to have a conversation on where this is going by the end of release 1. Pairing session between @jtwillis92 @ADPennington @abottoms-coder to discuss.

**Comment by lfrohlich** [comment]
@abottoms-coder  @jtwillis92  can you add a note about why this was moved up in priority re: #1459?

**Comment by jtwillis92** [comment]
> @abottoms-coder @jtwillis92 can you add a note about why this was moved up in priority re: #1459?

The error noted in #1459 was causing PRs to fail checks, which would prevent merging them. We discussed this internally and decided that it makes sense to prioritize this ticket first instead of fixing the tests only to remove them in a later sprint.

**Comment by valcollignon** [comment]
demo by @jtwillis92 12.7.21
