### ISSUE TITLE
SPIKE: Nail down process for when new security vulnerabilities are found

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1436]
**Description:**
Recently we found a possible vulnerability with a downstream package and resolved it in #1423. To ensure we have a consistent process going forward we should determine a specific process to follow in this event. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] A clear process is documented for what to do when you find a new security vulnerability.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Determine how we work when we find new security vulnerabilities.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
@ADPennington will open a new issue related to this spike.

**Comment by ADPennington** [comment]
closing since documentation of process is an AC for #885.
