### ISSUE TITLE
Refactor Data Files code

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1438]
**Description:**
As mentioned in #755 and #1061, we followed up in #1132 for getting a list of things we need to rename things for consistency. This ticket is to go through both the frontend and backend and refactor the relevant lines.

**Acceptance Criteria:** 
- [ ] No further mentions of `ReportFile` can be found and both frontend and backend reference the same `DataFile` notation.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary
- [ ] Change reports to data files in file names

**Tasks:**
- [ ] Update backend to rename `ReportFile` and associated code to `DataFile`. 
- [ ] Ensure frontend is also renamed to be consistent with backend `DataFile`.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
```
tdrs-frontend/src/index.scss 1
tdrs-frontend/src/mirage.data.js 1
tdrs-frontend/src/mirage.js 6
7,18,37,38,41
tdrs-frontend/src/actions/reports.test.js 2

tdrs-frontend/src/components/FileUpload.jsx 2

tdrs-frontend/src/components/Reports/index.js 3
tdrs-frontend/src/components/Reports/Reports.jsx 10
12,18,23,24,25,26,28,29,284
tdrs-frontend/src/components/Reports/Reports.test.js 26
7,8,10,12,88,106,133,142,146,171,174,175,184,199,202,203,212,238,239,248,265,266,277,311,376

tdrs-frontend/src/components/Routes/Routes.jsx 3
tdrs-frontend/src/components/Routes/Routes.test.js 3

tdrs-frontend/src/components/UploadReport/UploadReport.jsx 6
9,11,15-19
tdrs-frontend/src/components/UploadReport/UploadReport.test.js 2

tdrs-frontend/src/reducers/index.js 3
tdrs-frontend/src/reducers/reports.js 3
tdrs-frontend/src/reducers/reports.test.js 3
```

![img](https://user-images.githubusercontent.com/10676925/141522635-e0685df7-b468-4a89-964f-f70aeae74c1a.png)

**Open Questions:**

**Comment by riatzukiza** [comment]
Can we also include renaming the files as an AC? Several file names contain the term.

**Comment by valcollignon** [comment]
Added AC @riatzukiza

**Comment by robgendron** [comment]
No longer needed, deemed closed by team.
