### ISSUE TITLE
As tech lead, I want us using separate databases in shared RDS in the Cloud.gov dev space

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1439]
**Description:**
As noted in #1347, we need to split out databases instead of having a single shared database between all four dev environments. While we will continue to share the tdp-db-dev RDS service, we will simply have multiple named databases within.

**Acceptance Criteria:** 
- [ ] Each dev-space environment should have a separate database name within the shared tdp-db-dev RDS service.
- [ ] Migrations/deployments in one dev space should not impact another's database.
- [ ] The current users/roles data we have should remain a default through a Django migration.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Create a migration to capture and ensure the users/roles associations are maintained as a baseline in each new database
- [ ] Create mechanism in code to understand our cloud.gov space (local, dev, staging) and our application (staging, raft, qasp, local).
- [ ] Change the database name (`DB_NAME`) for the appropriate application (e.g., tdp-db-raft or tdp-db-a11y)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
- Do any special "create database" commands need to be run or should the `DB_NAME` rename be sufficent?

**Comment by valcollignon** [comment]
Putting into release 2 per backlog refinement 11.16.21. If this becomes a blocker for us, we can revisit release.

**Comment by abottoms-coder** [comment]
```
aj@raft-dev:~$ cf login -a api.fr.cloud.gov --sso
API endpoint: api.fr.cloud.gov

Temporary Authentication Code ( Get one at https://login.fr.cloud.gov/passcode )
: 
Authenticating...
OK


Targeted org hhs-acf-prototyping.

Select a space:
1. tanf-dev
2. tanf-staging

Space (enter to skip): 1
Targeted space tanf-dev.

API endpoint:   https://api.fr.cloud.gov
API version:    3.112.0
user:           abottoms@goraft.tech
org:            hhs-acf-prototyping
space:          tanf-dev

aj@raft-dev:~$ cf install-plugin https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-linux-386
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin https://github.com/cloud-gov/cf-service-connect/releases/download/1.1.0/cf-service-connect-linux-386? [yN]: y
Starting download of plugin binary from URL...
 8.59 MiB / 8.59 MiB [========================================================================================================================================================================] 100.00% 10s
Installing plugin ServiceConnect...
OK

Plugin ServiceConnect 1.1.0 successfully installed.
aj@raft-dev:~$ cf ssh-code # for connecting VScode via remote-dev guide so we can play with database settings in django's settings
#########
aj@raft-dev:~$ cf target -o hhs-acf-prototyping -s tanf-dev
API endpoint:   https://api.fr.cloud.gov
API version:    3.112.0
user:           abottoms@goraft.tech
org:            hhs-acf-prototyping
space:          tanf-dev
aj@raft-dev:~$ cf connect-to-service tdp-backend-sandbox tdp-db-dev
Finding the service instance details...
Setting up SSH tunnel...
SSH tunnel created.
Connecting client...
psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1), server 12.8)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

cgawsbrokerprodx9hbe1uy1srystc=> \l
                                                        List of databases
              Name              |      Owner       | Encoding |   Collate   |    Ctype    |           Access privileges           
--------------------------------+------------------+----------+-------------+-------------+---------------------------------------
 cgawsbrokerprodx9hbe1uy1srystc | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres                       | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 rdsadmin                       | rdsadmin         | UTF8     | en_US.UTF-8 | en_US.UTF-8 | rdsadmin=CTc/rdsadmin
 template0                      | rdsadmin         | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/rdsadmin                          +
                                |                  |          |             |             | rdsadmin=CTc/rdsadmin
 template1                      | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/ubinm0tax9919ama                  +
                                |                  |          |             |             | ubinm0tax9919ama=CTc/ubinm0tax9919ama
(5 rows)

cgawsbrokerprodx9hbe1uy1srystc=> create database tdp_db_dev_sandbox;
CREATE DATABASE
cgawsbrokerprodx9hbe1uy1srystc=> \l
                                                        List of databases
              Name              |      Owner       | Encoding |   Collate   |    Ctype    |           Access privileges           
--------------------------------+------------------+----------+-------------+-------------+---------------------------------------
 cgawsbrokerprodx9hbe1uy1srystc | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres                       | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 rdsadmin                       | rdsadmin         | UTF8     | en_US.UTF-8 | en_US.UTF-8 | rdsadmin=CTc/rdsadmin
 tdp_db_dev_sandbox             | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0                      | rdsadmin         | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/rdsadmin                          +
                                |                  |          |             |             | rdsadmin=CTc/rdsadmin
 template1                      | ubinm0tax9919ama | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/ubinm0tax9919ama                  +
                                |                  |          |             |             | ubinm0tax9919ama=CTc/ubinm0tax9919ama
(6 rows)

cgawsbrokerprodx9hbe1uy1srystc=> 
```

Next up is to automate this manual creation. There seem to be a few options but this looks the most in-house and least complicated.
https://django-extensions.readthedocs.io/en/latest/sqlcreate.html

Other options included [using psycopg2](https://stackoverflow.com/questions/19426448/creating-a-postgresql-db-using-psycopg2) or [pre-migrate](https://docs.djangoproject.com/en/1.11/ref/signals/#pre-migrate) or a total third-party tool like [Fabric](https://www.fabfile.org/).

**Comment by abottoms-coder** [comment]
Unfortunately, it doesn't appear that the environment our gunicorn_start shell script runs in has easy psql access -- there must be some non-traditional connector for the buildpack to allow django to connect to postgres. Attempting to run `sqlcreate` [here](https://github.com/raft-tech/TANF-app/blob/feat/1439-separate-rds-databases/tdrs-backend/gunicorn_start.sh#L6) resulted in these errors: 

```
tbd
```

Another DB creation Automator: https://github.com/Vacasa/django-db-auto-create

**Comment by reitermb** [comment]
Demoed by @abottoms-coder on 3/15/2022
