### ISSUE TITLE
Users can edit data

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#144]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by amilash** [comment]
@lfrohlich is this ticket about users being able to fix errors in the data IN TDP? (and then they would have to export the data file and upload it back to their case management software?). Or is this about allowing users to add missing data when an error is thrown, so they can completed thier submission without having to submit partial?

**Comment by stevenino** [comment]
Closed as not required.
