### ISSUE TITLE
As tech lead, I want us using separate prefixes in shared Cloud.gov S3 bucket for dev space

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1440]
**Description:**
As noted in #1347, we can prefix our S3 storage path and silo our file storage unique to application.

**Acceptance Criteria:** 
- [ ] Each dev-space environment should have a separate prefix name within the shared S3 service.
- [ ] File storage in one dev space should not show up in another application's logs.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Create mechanism in code to understand our cloud.gov space (local, dev, staging) and our application (staging, raft, qasp, local).
- [ ] Assign the s3 prefix for the appropriate application (e.g., tdp-db-raft or tdp-db-a11y)
- [ ] Ensure that these applications pull from their respective prefix/folder in S3 and this does not impact staging or local environments.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
 - https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html
 - 
**Open Questions:**

**Comment by valcollignon** [comment]
Putting into release 2 per backlog refinement 11.16.21. If this becomes a blocker for us, we can revisit release.

**Comment by stevenino** [comment]
Should be worked prior to #1007

**Comment by riatzukiza** [comment]
Currently I am getting:
```
09:43:59.954: [CELL.0] Downloaded droplet (100.3M)
09:43:59.955: [CELL.0] Starting health monitoring of container
09:44:00.300: [APP/PROC/WEB.0] Applying database migrations
09:44:01.281: [APP/PROC/WEB.0] SystemCheckError: System check identified some issues:
09:44:01.281: [APP/PROC/WEB.0] ERRORS:
09:44:01.281: [APP/PROC/WEB.0] ?: (urls.E006) The MEDIA_URL setting must end with a slash.
09:44:01.427: [APP/PROC/WEB.0] Exit status 1
09:44:01.429: [CELL/SSHD.0] Exit status 0
```
