### ISSUE TITLE
As a developer, I want to use an LTS version of Node in the project

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1447]
**Description:**
_Provide a brief background and justification for this issue_

The TANF frontend currently uses a Node `v12.18` docker image, which is blocking us from merging [dependency updates](https://github.com/raft-tech/TANF-app/pull/1426). We should be on at least an a latest LTS (long-term support) version of Node; `v12.18` is not even the latest Maintenance LTS release of version 12. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Node is updated to `v16.3.0` (latest LTS as of this writing)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
