### ISSUE TITLE
ZAP False Positives - Unexpected Content Type & Client Error response code

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#1455]
**Description:**
After https://github.com/raft-tech/TANF-app/pull/1448 is merged we will still have two remaining false positives in the backend ZAP alerts. However, we are currently unable to ignore these alerts. Surprisingly, these alerts do not show in the [ZAP Alert Details Page](https://www.zaproxy.org/docs/alerts/) which seems to indicate that they are not yet fully implemented.

Adding their plugin IDs (100000 and 100001) with the IGNORE directive does not work as the alerts still show in the HTML report (even when ignored through the zap_hook.py script). We may have to open an issue with zaproxy or wait for a further release to resolve this.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] False positives no longer show 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Find an alternate way to exclude these alerts
OR
- [ ] Open an issue with zaproxy
OR
- [x] Revisit this with a future release of zap and attempt ignoring the alerts again
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
>  Revisit this with a future release of zap and attempt ignoring the alerts again
 Run Testing Checklist and confirm all tests pass

Per backlog refinement 11.23.21, choosing these tasks. There are other priorities at this time.

**Comment by robgendron** [comment]
@andrew-jameson not feasible as is, need to reevaluate how ZAP is used.
