### ISSUE TITLE
Live Comms (Dec 2021) 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1461]
**Description:**
Delivers updates to ROs and grantees encompassing progress on TDP and upcoming research/collaboration opportunities.

**AC:**
- [ ] Live comms session complete
- [ ] Recording / presentation artifact emailed to ROs
- [ ] Emailed/linked-to materials are 508 compliant

**Tasks:**
- [ ] Create live comms presentation content
- [ ] Ensure content is 508 accessible
- [ ] (Lauren) Schedule meeting for live communications
- [ ] Conduct (and record) presentation
- [ ] Lauren will send presentation recording and presentation link to ROs

**DoD:**
- [ ] @lfrohlich sign off
- [ ] [Presentation content](url) is delivered

**Comment by reitermb** [comment]
Potentially blocked by at least a drafted synthesis of Resubmission research. 

If we want it in December: no later than the week of the 13th.

**Comment by reitermb** [comment]
Pulling into the sprint: 
May be pushed until January given research blockers but we'd like to create the new web-based live comms page in preparation for it regardless.

**Comment by reitermb** [comment]
Live comms content is live and ready for feedback here: https://reitermb.github.io/TANF-Data-Portal-Updates/

cc: @ADPennington @lfrohlich

**Comment by reitermb** [comment]
https://tdp-live-comms.app.cloud.gov/index.html is now live with final additions including:
- Link to the full synthesis
- Added alt text where it was missing
- Removed un-needed toggle on interactive Highchart table
- Version A & B resources that link to GitHub hosted PDFs
- GitHub hosting instead of imgur for all images.

**Comment by reitermb** [comment]
cc @lfrohlich @ADPennington

**Comment by lfrohlich** [comment]
Sent link to RO staff to disseminate on 2/8
