### ISSUE TITLE
[Design] V2 Notifications content 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1462]
**Description:**
Delivers V2 notification content to enable HTML templating and collaboration/testing with OFA regional staff to help validate.

Stories from research roadmap item:

As a TDP user:
- I want to be notified when my request for access to TDP has been submitted.
- I want to be notified when my request for access to TDP has been approved. 
- I want to be notified when my account will soon be deactivated (because of inactivity). 
- I want to be notified when my account is deactivated.

As an STT Analyst user: 
- I want to be notified when data for my program has been submitted.
   - Noting that this particular notification story is informed from research insights we've gathered from larger grantee TANF teams. In situations where staffing is able to support a divide and conquer approach to data preparation for various sections of TANF data, data analysts are careful to maintain detailed email communication to keep each other (and the program director) informed of changes to data. 

As a person who has been denied access: 
- I want to receive an email notifying me that my request has been denied.

[V3 or beyond] 
As a TDP user: 
- I want to be notified when my level of access to TDP has been changed.
- As a Regional OFA Analyst I want to be notified when a grantee in my region submits data. 

**AC:**
- [x] Designs encompass notifications for all stories captured above 
- [x] Email content includes:
   - [x] Subject line
   - [x] Body
   - [x] Links to the appropriate place within TDP if an action in TDP is suggested in the email
   - [x] A consistent approach to the above across all types of notifications
- [x] The design is usable, meaning... 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 

**Tasks:**
- [x] Document notification triggers and events in existing or new [Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=1277%3A8087) user flows
- [x] Draft email content in a [hack.md](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg)
- [x] Email content includes:
   - [x] Subject line
   - [x] Body
   - [x] Links to the appropriate place within TDP if an action in TDP is suggested in the email
   - [x] A consistent approach to the above across all types of notifications

**DoD:**
- [x] Documentation: [hack.md](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg) is linked to in this ticket.
- [x] @lfrohlich has reviewed and signed off

**Comment by reitermb** [comment]
Added denied email notification given conversation in 12/14/ Dev/Design handoff sync on #653. 

cc: @ADPennington @abottoms-coder

**Comment by reitermb** [comment]
Splitting this out into additional tickets:
- One for notification drafts
- One for sessions w/ DIGIT/Regional Staff
- One for HTML templates

**Comment by sreedevip** [comment]
Updated tasks to reflect Notification triggers in Figma user flows. This task was part of the original ticket, but was missing from the latest rewrite on 3.22
@reitermb @stevenino @lfrohlich

**Comment by lfrohlich** [comment]
@sreedevip  updates look good
@reitermb  can you add the numbers of the tickets that were split out?

**Comment by lfrohlich** [comment]
I added comments in the hack.md

**Comment by lfrohlich** [comment]
@sreedevip or @reitermb can you update the bullets of our user stories above to match the latest in hack.md?

**Comment by reitermb** [comment]
> @sreedevip or @reitermb can you update the bullets of our user stories above to match the latest in hack.md?

They should all match now!

**Comment by lfrohlich** [comment]
Added question to hack.md: move "I want to be notified when my level of access to TDP has been changed." to V3 or beyond

**Comment by lfrohlich** [comment]
Added a Table of Contents
