### ISSUE TITLE
As a Django Admin Console user, I want to bulk-download data files

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1466]
**Description:**
This is just an user experience improvement. In DAC, we want the ability for users like the OFA data analysts to be able to download files via a DAC action where they select all relevant files and can bulk download them.

**Acceptance Criteria:** 

- [ ] Relevant user roles
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Create new DAC action for all selected data files
- [ ] Link action to relevant roles
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by abottoms-coder** [comment]
Came out of discussions of #1441

**Comment by valcollignon** [comment]
Double check that there aren't dupe tickets per backlog refinement 12.7.21
CC: @riatzukiza @abottoms-coder

**Comment by valcollignon** [comment]
Need to discuss user story, research, and need for this ticket.
CC: @lfrohlich @ADPennington @sreedevip @reitermb

**Comment by lfrohlich** [comment]
See #1011 for more context SPIKE: File transfer options for Tribal MVP

**Comment by valcollignon** [comment]
Discussed @lfrohlich 's comment and decided we don't need a bulk download for v2; we just need a log of all files set up for transfer to the ACF server. We have added it as a task in #1133.

**Comment by robgendron** [comment]
Originally was created as an alternative to sftp files, deemed no longer needed by @lfrohlich and @ADPennington
