### ISSUE TITLE
As ACF tech lead, I need the docs/ subdir and readmes updated

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#1477]
### Context

_**This ticket has been revised to synthesize feedback and next steps outlined in the comments below.**_

The repo's documentation is in need of an overhaul, from the [main Readme](https://github.com/raft-tech/TANF-app) to all the other supporting docs that live within the [docs/](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs) subdir. The goal is to make it easier for the team and external stakeholders to find information about what we're building. 

This ticket will be addressed in stages:
- update main readme, `TANF-app/docs/` structure, and update ADRs (#1515)
- #1521 - `TANF-app/doc/Background/`
- #1522 - `TANF-app/doc/Product-Strategy/`
- #1523 - `TANF-app/doc/How-We-Work/`
- #1524 - `TANF-app/doc/Security-Compliance/`
- #1525 - `TANF-app/doc/Sprint-Review/`
- #1526 - `TANF-app/doc/Technical-Documentation/`
- #1527 - `TANF-app/doc/User-Experience/`

### ACs:
- [x] Main readme updated, per [hackmd](https://hackmd.io/@valeriecollignon/r1o0mTvFK/edit) (#1515)
- [x] Docs/ subdir restructured per [this comment](https://github.com/raft-tech/TANF-app/issues/1477#issuecomment-1003096463) (#1515)
- [x] ADRs audited and updated (#1082 to be addressed in #1515) 
- [x] All docs/ subdirs reviewed and updated accordingly
- [x] Ensure main readme points to the correct places
- [x] drop `/docs/` [readme](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/README.md)

**Comment by valcollignon** [comment]
@abottoms-coder and @valcollignon to work on first draft and then @sreedevip @reitermb @lfrohlich and @ADPennington to review.

**Comment by valcollignon** [comment]
HackMD for edits/collab available here: https://hackmd.io/@valeriecollignon/r1o0mTvFK/edit
CC: @abottoms-coder

**Comment by valcollignon** [comment]
Revised and drafted during Dev Sync 12.14.21.
@lfrohlich @reitermb and @sreedevip - please review and make comments/edits on any additions or changes. We are getting close! :)

**Comment by ADPennington** [comment]
> Revised and drafted during Dev Sync 12.14.21. @lfrohlich @reitermb and @sreedevip - please review and make comments/edits on any additions or changes. We are getting close! :)
@lfrohlich 
- decided to move up the content current in the product planning md into the main md, including the "what we are building" and the "table of contents"
- to moved down the table on the current build to after the abovementioned overview. this section should also include a link to the roadmap so people have a sense of what features the current build contains. 
- expanded on the table of contents list based on suggestions from @sreedevip's [doc hackmd](https://hackmd.io/xIs9tvk7S9eevqHPoydq3Q) as well as sections that we decided to drop from the main md
- we dropped sections on spinning up locally and manual deployments

**Comment by abottoms-coder** [comment]
In Tech sync 12/17, discussed the restructuring and incorporated changes from docs/README into main README in the pull request. Additionally, agreed to remove the team-charter folder and the prototype folder as it is redundant to the [archive repo](https://github.com/HHS/TANF-app-archive) which we will place a link to somewhere in the background folder. Will go file by file to slowly incorporate doc changes into this PR to prevent people from being inundated with a massive PR with 57 files all at once.

**Comment by valcollignon** [comment]
@ADPennington to work on during holiday sprint and pair with UX, but won't be able to get a team consensus to complete PRs until after the holidays.

**Comment by ADPennington** [comment]
12/29/2021 update:
- _for the record:_ we agreed during 12/9 knowledge transfer mtg to leave code-specific files and folders in rootdir(e.g. `tdrs-backend\`, `regexes.json`) untouched for now since it would take time to test the implications of re-organizing them and update internal references to dirs, so my review focuses specifically on directory changes proposed in #1505 in `TANF-app/design-assets/` and `TANF-app/docs/` 
- Any doc files/folders we've agreed to move will need to be accounted for when internally referenced in other docs (see example in next bullet). This feels like a follow-on ticket once the directory structure has been approved and merged because a lot of these docs need to be updated anyway. 
- agree with `TANF-app/design-assets/` being dropped and its contents moved but not necessarily  in `TANF-app/docs/User-Research/research-artifacts` because these files are referenced in other markdowns and will need to be updated (e.g. `acf_org_chart.png` is referenced in `TANF-app/docs/Background/Agency-Background.md`).
- agree with `TANF-app/docs/Acquisition/` being moved to `TANF-app/docs/Background/Acquisition/`
- agree with dropping `TANF-app/docs/Prototype/` and `TANF-app/docs/How-We-Work/team-charter/` per [this comment](https://github.com/raft-tech/TANF-app/issues/1477#issuecomment-997044217) and moving files to more appropriate folders. however:
  - `our-team-and-values.md` now replaces `team-composition.md` which is okay but is now missing section on our vision and values. 
  - Per [workflow sync](https://github.com/raft-tech/TANF-app/issues/1482#issuecomment-1000402462), we agreed to also add government priorities here. 
  - i think this is also a good place to add something about qasp (since `quality-expectations.md`) is dropped. and it should link to the PR template. I'd also like to see relevant content from [manual-checks.md](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/team-charter/manual-checks.md) described since its being deleted. important context for qasp. 
  - I'm okay with moving `Secrey-Key-Mgmt.md` to ADR subdir, but it needs to be updated into the proper ADR format per #1488. 
  - Not clear why `branching-strategy` is in technical documentation folder, since its redundant with ADR 009 and other places, outdated. suggest deletion. 
- I wonder if `Prodtastic-Resources.md` belongs better in `TANF-app/docs/How-We-Work/`?

**Comment by ADPennington** [comment]
12/30/2021 update:
- i think `TANF-app/docs/Prototype/` can be moved into `TANF-app/docs/Background/`. 
- I like @sreedevip's suggestion in the [main repo readme.md hackmd](https://hackmd.io/gqdLDoTXQvysIO4HMFfQNQ) about a user experience header. this suggests to me that `TANF-app/docs/How-We-Work/User-Research` could be renamed and that it could have subdirs for `research` and `design`. 
- `TANF-app/docs/Technical-Documentation/` needs a _deep audit_. I'm not sure some of this is still relevant, and i don't think the removal of the subdirs in here will suffice without renaming files to with more meaningful labels. this should be tracked in a separate ticket. 
- General suggestion for all subdirs in the repo: all should have a readme.md that briefly describes the contents of the subdir. 

This completes my review of the changes in #1505. Suggested next steps:
- full team reviews comments herein and decide on the following (once the structure is decided, we can move docs therein around) : 
   - are we in agreement that the [rootdir](https://github.com/raft-tech/TANF-app) is fine, minus `\design-assets\`?
   - Do we agree with the following structure of the `TANF-app/docs/` subdir?
> TANF-app/docs/
> > > README.md (with table of contents)
> > > Background/ (note: the proposed structure below is a template for how all other subdirs would be structured)
> > > > README.md (with table of contents)
> > > > Folders/
> > > > Files/

> > > How-We-Work/
> > > Security-Compliance/
> > > Sprint-Review/
> > > Technical-Documentation/
> > > User-Experience/
- #1505 revised with agreed upon structure
- follow-on ticket(s) created to address feedback herein re: where docs should live, doc labels, doc contents, etc. 

cc: @valcollignon

**Comment by ADPennington** [comment]
one more update: I made revisions to the [main readme hackmd](https://hackmd.io/gqdLDoTXQvysIO4HMFfQNQ):
- cleaned up the TOC to be consistent with above suggestions (note: i think we should have a dedicated subdir for product strategy, even if it sits within the `how-we-work` subdir)
- added a POC section at the bottom

**Comment by ADPennington** [comment]
1/3/2021: after syncing w/ @lfrohlich, we decided that we'd prefer to have a dedicated subdir within `/docs/` for `Product-Strategy`. the tree structure above has been updated to reflect this. @valcollignon @abottoms-coder @reitermb @sreedevip

**Comment by abottoms-coder** [comment]
> 1/3/2022: after syncing w/ @lfrohlich, we decided that we'd prefer to have a dedicated subdir within `/docs/` for `Product-Strategy`. the tree structure above has been updated to reflect this. @valcollignon @abottoms-coder @reitermb @sreedevip

Does this conflict with this draft?
https://github.com/raft-tech/TANF-app/pull/1505/files

**Comment by ADPennington** [comment]
> > 1/3/2022: after syncing w/ @lfrohlich, we decided that we'd prefer to have a dedicated subdir within `/docs/` for `Product-Strategy`. the tree structure above has been updated to reflect this. @valcollignon @abottoms-coder @reitermb @sreedevip
> 
> Does this conflict with this draft? https://github.com/raft-tech/TANF-app/pull/1505/files

yes.

**Comment by lfrohlich** [comment]
> 

This was my only comment, otherwise looks good

**Comment by lfrohlich** [comment]
@reitermb @sreedevip  any concerns with 
> I like @sreedevip's suggestion in the main repo readme.md hackmd about a user experience header. this suggests to me that TANF-app/docs/How-We-Work/User-Research could be renamed and that it could have subdirs for research and design.

**Comment by reitermb** [comment]
> @reitermb @sreedevip  any concerns with 
> > I like @sreedevip's suggestion in the main repo readme.md hackmd about a user experience header. this suggests to me that TANF-app/docs/How-We-Work/User-Research could be renamed and that it could have subdirs for research and design.

I'm open to that structure but it's worth noting that the change will definitely come with some broken links in both the current user research readme and a number of syntheses (where they reference and link to each other). 

That's not necessarily a concern but it is some extra lift and PR(s) to address.

**Comment by ADPennington** [comment]
> 

correct. this will be a consequence of the restructuring across the board.

**Comment by sreedevip** [comment]
> @reitermb @sreedevip any concerns with
> 
> > I like @sreedevip's suggestion in the main repo readme.md hackmd about a user experience header. this suggests to me that TANF-app/docs/How-We-Work/User-Research could be renamed and that it could have subdirs for research and design.

I like the proposed new structure for a User Experience header, as it reflects the entirety of the UX work we do

**Comment by ADPennington** [comment]
_this comment is still in-progress and will eventually replace the issue summary_

With the merge of #1515, we now need to clean-up the `TANF-app/doc/` directory and update reference links therein. 

### Tasks:
- [ ] Update `TANF-app/doc/Background/`
   -  Add README.md w/ TOC
   - Update any broken links within markdowns

- [ ] Update `TANF-app/doc/Product-Strategy/`
   - Add README.md w/ TOC
   - Add content from `Prodtastic-Resources.md` as an addendum section to `Considerations-and-Planning.md` and drop standalone md. 
   - `Vision-and-Stakeholders.md` should include descriptions of: vision, mission, stakeholders, and theory of change.
   -  Update any broken links within markdowns

ACs:
- [] Ensure main readme points to the correct places
-  tbd...

**Comment by valcollignon** [comment]
Converted #1477 to an epic, as discussed with @ADPennington on 1.5.21. Will break out tasks into separate issues and assign/point accordingly.

**Comment by valcollignon** [comment]
Documentation efforts as part of this epic were discussed during 1.18.22 demo by @valcollignon, @abottoms-coder, and @lfrohlich.
