### ISSUE TITLE
[Spike Research] Session with UX1-27 to better understand potential SFTP blocker

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1480]
**Description:**
We've heard from Grantee: UX1-27 that the particular way in which their data warehouse system is set up might make it difficult to get access to TANF data files on a computer capable of uploading to TDP. This research delivers answers to the below research questions, a system diagram/other documentation (if relevant for mapping the potential blocker here, and a top-line synthesis. 

**Research Questions:**
- Can we confirm whether this is a true blocker of submission via TDP? 
- If confirmed, what is the nature of the blocker? What system constraints/structures/processes have led to it?
- How might we work around it?

**AC:**
- [ ] A (lite) research plan exists and captures a more granular list of interview questions
- [ ] Findings are synthesized in a form shareable to the team
- [ ] Synthesis includes project recommendations, impact, next steps

**Tasks:**
- [ ] Draft research plan
- [ ] Schedule session with grantee data analyst(s) at UX1-27
- [ ] Facilitate session
- [ ] Synthesize findings 
- [ ] Open PR to raft-tech with markdown writeup of synthesis (if large enough to demand a document similar to [Flat File Metadata Guide](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/Flat%20File%20Metadata%20Guide.md))
- [ ] Share findings with the UX Sync team / other pertinent project team members

**Supporting Documentation:**
- [Synthesis]()
- [Research Plan]()

**Comment by reitermb** [comment]
Can be closed, follow-on conversation revealed that this wasn't a blocker.

**Comment by stevenino** [comment]
Closed as not required per backlog refinement on 7/19/22
