### ISSUE TITLE
Update Current TDRS documentation

### ISSUE THREAD

**Issue by sreedevip** [raft-tech/TANF-app#1483]
**Tasks**
Update [Current TDRS](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Background/Current-TDRS.md) by pulling from existing documentation to
- [ ] Create a document that explains the legacy TDRS system
- [ ] Explain various stages of the file transmission and error reporting in TDRS
- [ ] Provide a glossary of terms
- [ ] Answer FAQs
- [ ] Provide secure links to documents that live in HHS Sharepoint or other places (e.g transmission file example, parsing notebook etc.)

**Comment by ADPennington** [comment]
maybe this is an update to the existing [documentation](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Background/Current-TDRS.md) rather than creating a new one.

**Comment by sreedevip** [comment]
@ADPennington changed accordingly

**Comment by ADPennington** [comment]
could you also include your questions about tdrs? i think its a different hackmd than the one you shared this morning @sreedevip

**Comment by valcollignon** [comment]
@sreedevip and @ADPennington to pair on this per sprint planning/backlog 12.21.

**Comment by ADPennington** [comment]
closing as a dupe to #1521.
