### ISSUE TITLE
As tech lead, I want our team to leverage github-mattermost integration

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1484]
**Description:**
Everyone at sprint retrospective found the github private chanel great and would like to get access to it as well.

**Acceptance Criteria:** 

- [x] Team knows how to link their mattermost account with github for raft-tech:TANF-app
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Write a clean, easy-to-follow document for linking mattermost with the github plugin
- [ ] Follow up that everyone can/has run through it
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by ADPennington** [comment]
im good here @abottoms-coder 👍🏾
