### ISSUE TITLE
Django Admin – Broken Select all Action Link

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1487]
**Description:**

This is a followup issue from #1054 that we hoped the Django upgrade in #1405 would fix, but it did not so we split this up into a new issue.

https://github.com/raft-tech/TANF-app/pull/1223#issuecomment-945802883

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Select all Action is functional
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Resolve select all actions issue from #1223 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by jorgegonzalez** [comment]
![image](https://user-images.githubusercontent.com/12901172/145286223-6e4f043c-8312-4e82-9740-de437c87cd38.png)

**Comment by jorgegonzalez** [comment]
This is addressed in a [PR](https://github.com/raft-tech/django-admin-508/pull/23) in DA508 and will be added to TDRS shortly
