### ISSUE TITLE
Automate setting of default environment variables in Cloud.gov

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1489]
**Description:**
This is a follow on to #1036 where we discovered that the cloud.gov applications do not have consistent environment variables in the tanf-dev space and that `set-backend-vars.sh` does not set more than a couple by default. Some spaces like `sandbox` only had 9 variables while others like `raft` had 20+. Inspection of frontend applications reveal no environment variables are set or used presently so these can be ignored.

**Acceptance Criteria:** 
- [ ] All cloud.gov applications (both tanf-dev and tanf-staging) have a consistent set of variables between backends. 
- [ ] When used by the `deploy-backend.sh` or `deploy-frontend.sh`, these scripts perform as expected.
- [ ] Essential environment variables are included by default in these automated scripts and do not have to manually be added by running these scripts.
- [ ] Environment variables should persist across application rebuilds/restages.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Gather list of common/default backend variables from `tdrs-backend/docker-compose.yml`.
- [x] Update [`set-backend-env-vars.sh` ](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/scripts/set-backend-env-vars.sh#L38-L42) to include new default list
- [x] Update `set-backend-env-vars.sh` to fetch existing vars before an environment is deleted/recreated and ensure they are re-applied on start -- unsure on how this might conflict with "loaded" env vars from the .env files/local environment
- [ ] Ensure deployments remain functionally the same
- [ ] Remove extraneous environment variables from application spaces
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
- Which spaces have extraneous/obsolete environment variables?
- What is the core set of environment variables needed?
- Do any applications need these environment variables set to differing values? Yes, staging vs raft.

**Comment by abottoms-coder** [comment]
+1 On this. @jorgegonzalez found [a failure](https://circleci.com/workflow-run/99ee759e-48a0-4b2e-ac1a-dcba4893003a?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) today which resulted from missing env var.

**Comment by abottoms-coder** [comment]
Ran into failures yesterday, added some environment variables in [this PR](https://github.com/raft-tech/TANF-app/pull/1654):

```bash
cf set-env "$CGAPPNAME_BACKEND" JWT_KEY "$JWT_KEY"
cf set-env "$CGAPPNAME_BACKEND" DJANGO_SU_NAME "$DJANGO_SU_NAME"
cf set-env "$CGAPPNAME_BACKEND" LOGGING_LEVEL "$LOGGING_LEVEL"
```

**Comment by abottoms-coder** [comment]
If the local environment variable is empty, cloud.gov will say "OK" but not create the environment variable. This is required when running `deploy-backend.sh` you must set ALL environment variables locally.

**Comment by stevenino** [comment]
High priority DX tix

**Comment by stevenino** [comment]
Blocked by production env issues #1778
