### ISSUE TITLE
[Spike] As a developer, I want to run Pa11y integration tests from a test suite

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1492]
**Description:**

Some issues are difficult to unit tests, for example, on #1419, we went under 90% test coverage fixing an issue with keyboard nav, but it is not reasonable to test it in jest, so it was ignored. If we want to catch bugs like it more easily, we need a mechanism to run integration tests on a headless browser. Pa11y does this, but it is not configurable enough through its json file to meet all of our needs. We propose that we start running pa11y through its js interface, in conjunction with a test runner.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Pro/Con lists for available tools
- [ ] Proof of concept of test runner tool which leverages our existing Pa11y tests
- [ ] It is clear how we can continue to extend our test runner tool for future tests
- [ ] All existing pa11y tests pass after conversion
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create a script that runs pa11y through js api
- [ ] integrate with test runner like mocha, chai, or ava
- [ ] expose browser
- [ ] provide a single test to demonstrate keyboard pa11y/integration testability ([1419](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/1419) may be a good place to start on this)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_

**Comment by robgendron** [comment]
Update: Still needed.

**Comment by robgendron** [comment]
Follow-on conversation is needed @andrew-jameson

**Comment by robgendron** [comment]
Let's take this to an office hour - Explore if Cypress will give this and generate a pro/con list @andrew-jameson.
