### ISSUE TITLE
As UX lead, I want the user to have an organized first experience for the Profile page

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1495]
**Description:**
Per #653 , we are updating our UI for the Profile page for users requesting access.

**Acceptance Criteria:** 
- [ ] Any page that's visible in the nav bar should be within the users' _current_ permissions (e.g. If you don’t have a role you don’t get the ‘Data Files’ or ‘Admin’ nav items—If you haven’t requested access yet then you shouldn’t see ‘Profile’)
- [ ] Access request form should exist on “Home”, not “Profile”.
- [ ] Users should only submit request access form ONCE. Once submitted, their homepage content should be the status message confirming that they requested access. Once granted access, their homepage content should reflect their role/permissions in TDP.
- [ ] Once a request for access has been submitted, users should have access to their profile page
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] User is shown "request for access pending message until approved per Figma link below
- [x] User is shown their intake infomation as well
- [x] A11y review must be completed
- [x] Implement backend request access logic
- [ ] Will not show "STT analyst" role back to approved user, will only show OFA roles for approved users
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Figma Mock Ups](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=5892%3A48657)
- [![Video Demo](https://user-images.githubusercontent.com/28515874/146063861-57a9de59-8741-4517-8955-64138c470685.png)](https://user-images.githubusercontent.com/28515874/146063268-290ae9d2-9fd9-4db8-96cd-a7dae9169972.mp4 "Video Demo")

**Open Questions:**

**Comment by jorgegonzalez** [comment]
How will an admin ultimately "approve" pending users requesting access?

- Handle in django admin
- Create ticket to handle pending requests page

**Comment by abottoms-coder** [comment]
> How will an admin ultimately "approve" pending users requesting access?
> 
> * Handle in django admin
> * Create ticket to handle pending requests page

At this time, in Django admin.

**Comment by raftmsohani** [comment]
> Will add ability to admin page with no list, but ultimately have to add a page with list of all pending approvals

**Comment by reitermb** [comment]
Demoed by @jorgegonzalez on 3/1/2022
