### ISSUE TITLE
As UX lead, I want the user to have a organized first experience via tab visibility per user state

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1498]
**Description:**
Per #653 , we will want to improve on the initial user experience with TDP. Possible user states:

* Anonymous: Yet to request access (This term is likely inconsistent with what we use in the database)
* Pending: Have submitted form, no approval
* Active: OFA or sys admin have approved
* Denied/Inactive: Authentication fails, and redirects user to splash page

**Acceptance Criteria:** 
- [ ] When user has not yet requested access, they can only see "Home"
- [ ] When user has requested access, they can see "Home" and "Profile"
- [ ] When user has been approved, they can see "Home", "Profile", and "Data Files"
- [ ] When admin user has been approved, they can see all 4 tabs.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Create frontend logic for hiding visibility of tabs for user
- [ ] Create frontend > backend query for user status
- [ ] Create backend API call to return user status to frontend
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Figma Mockups](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=5892%3A48657)
- [![Video Demo](https://user-images.githubusercontent.com/28515874/146063861-57a9de59-8741-4517-8955-64138c470685.png)](https://user-images.githubusercontent.com/28515874/146063268-290ae9d2-9fd9-4db8-96cd-a7dae9169972.mp4 "Video Demo")
- 
**Open Questions:**
- Do we have to create a backend API to query user status data for the frontend?

**Comment by stevenino** [comment]
Closed as a duplicate of #1495  per backlog refinement 4/19/22
