### ISSUE TITLE
Upgrade django to version  3.2.10

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1502]
**Description:**
A vulnerability was introduced to django that is fixed in 3.2.10, details in the image below

![image](https://user-images.githubusercontent.com/10676925/146413919-005bd590-b950-49b6-a8e8-cfb79a853710.png)

**Acceptance Criteria:** 

- [ ] We are no longer vulnerable to the issue
- [ ] We are running at least django 3.2.10
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Upgrade dependency
- [ ] change anything that is broken by the update
- [ ] verify the issue is no longer present
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

run `pipenv install django==3.2.10` and commit `Pipfile` and `Pipfile.lock`

**Supporting Documentation:**

**Open Questions:**
