### ISSUE TITLE
As technical lead, I need ACF AMS integrated for direct DAC access

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1520]
**Description:**
_Provide a brief background and justification for this issue_
If an unauthenticated user browses to `https://tdp-backend-staging.app.cloud.gov/admin/`, they will be automatically redirected to our Login.gov sandbox prompt. This presents a third access method beyond the two buttons available on the frontend. While this third route may be unlikely, we want to ensure loose ends are tied up. We want to ensure ACF users aren't using Login.gov to access the DAC.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Accessing [DAC directly](https://tdp-backend-staging.app.cloud.gov/admin/) is handled gracefully and not railroad users into one authentication solution.
- [ ] All users in all environments who should have access to DAC do not have their experience complicated or disrupted.
- [ ] Developer user role in local stack or dev environments can continue to login to DAC via Login.gov method.
- [ ] ACF admin-level users per #1170 will continue to use ACF AMS in deployed environments (both tanf-staging and tanf-dev).
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] TBD
- [ ] Ensure users without DAC permissions continue to not have access.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- We cannot simply eliminate the route to `/admin/` as that is what the frontend link uses.
- The [url route for admin](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/tdrs-backend/tdpservice/urls.py#L42) directs users into the [LoginRedirectLoginDotGov class](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/tdrs-backend/tdpservice/users/api/login_redirect_oidc.py#L12) based on [LOGIN_URL](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/tdrs-backend/tdpservice/settings/common.py#L113). 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Django RedirectView Documentation](https://docs.djangoproject.com/en/4.0/ref/class-based-views/base/)
- [Django LOGIN_URL Doc](https://django-rest-swagger.readthedocs.io/en/latest/settings/)
- [Django `login_required` decorator](https://docs.djangoproject.com/en/3.2/topics/auth/default/#the-login-required-decorator)
- [Stackoverflow on login_required](https://stackoverflow.com/questions/29832576/django-rest-framework-redirect-to-login-with-next-parameter-if-authentication)
- 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Do we want to prompt unauthenticated users by directing them back to the frontend or simply return a 401 unauthorized page?
- Are there other solutions to this corner case?

**Comment by abottoms-coder** [comment]
Per dev sync 1/5, we believe that the `login_required` decorator is likely the best solution and should redirect users to the frontend with some work but will leave it until this ticket is in progress to decide on the best solution.

**Comment by valcollignon** [comment]
Brought into sprint per @ADPennington and @abottoms-coder.

**Comment by raftmsohani** [comment]
The easiest way to enforce authentication when request for admin urls are coming in, is to write a decorator and attach it to Admin View function. However, there are a couple of questions and notes that need to be cleared before going forward:

1) By hooking the admin site instance to URL conf, Django registers the URLs using the AdminSite default class. This automatically enforces login required for Admin site. In other words, if an unauthorize user hits '/admin', then django automatically routes back to 'admin/login' or settings.LOGIN_URL. This is the default action. As such, the easiest approach is to:

- Set LOGIN_URL to front end login page
- or hook /admin/login to a view and redirect to frontend login

2) Another approach is to override AdminSite and use Admin_View method to check the suer

**Comment by jorgegonzalez** [comment]
We decided to address this in #1136 here: https://github.com/raft-tech/TANF-app/pull/1369/commits/2e0476a34f2597704c942f4384686cbeba201816 as it was a small enough change that we didn't want to create a whole new PR for this issue.

**Comment by valcollignon** [comment]
Addressed during 1.18.22 demo by @abottoms-coder , but not a demo-able issue.
