### ISSUE TITLE
Update TANF-app/doc/Background/

### ISSUE THREAD

**Issue by valcollignon** [raft-tech/TANF-app#1521]
### Context

After #1515 is merged, `TANF-app/doc/Background/` subdirectory markdowns need to be reviewed and updated. 

### ACs:
- [x] Add README.md w/ TOC
- [x] Update `Current-TDRS.md` (#1483)
- [x] Update any broken links within markdowns

### Tasks:
- [x] Create [hackmd](https://hackmd.io/@valeriecollignon/SyQ_qOE2F/edit) for subdir `README.md`  w/ TOC (`valcollignon` )
- [x] Create [hackmd](https://hackmd.io/6zK6oaMPQEOKgCsidMcUaA) to update `Current-TDRS.md` (`sreedevip` ,`adpennington`)
- [x] delete `TANF-app/docs/Background/Prototype/`
- [x] update Agency-Background.md with embedded image (`acf_org_chart.png`) from `TANF-app/docs/User-Experience/Design/design-assets/research-artifacts/` (which will be deleted with #1527)
- [x] rename `Flatfile Metadata Guide.md` to `2020, Fall - Flatfile Metadata Guide.md`  and move to `TANF-app/docs/User-Experience/Research/`
- [x] move `2020, Fall - Understanding STT Roles, Source of Truth, and Metadata.md` to `TANF-app/docs/User-Experience/Research/`
- [x] Open draft PR with subdirectory updates (`adpennington`)
- [x] Review and update any broken links (`valcollignon`, `adpennington`)
- [x] Create Figma diagram for data reporting process flow and add to `Current-TDRS.md` (`sreedevip`)

### Notes:
Part of the #1477 documentation update epic

**Comment by valcollignon** [comment]
[Here](https://hackmd.io/@valeriecollignon/SyQ_qOE2F/edit) is the `README.md` draft for `TANF-app/doc/Background.

**Comment by ADPennington** [comment]
@valcollignon @lfrohlich hackmd

> [Here](https://hackmd.io/@valeriecollignon/SyQ_qOE2F/edit) is the `README.md` draft for `TANF-app/doc/Background`.

@valcollignon @lfrohlich this hackmd is ready for review.

**Comment by valcollignon** [comment]
> @valcollignon @lfrohlich this hackmd is ready for review.

LGTM

**Comment by lfrohlich** [comment]
I made a few edits and responded to comments. Looks good to me! @ADPennington

**Comment by ADPennington** [comment]
> I made a few edits and responded to comments. Looks good to me! @ADPennington

making a note here to address this in #1515.

**Comment by ADPennington** [comment]
@valcollignon @sreedevip the [tdrs hackmd](https://hackmd.io/6zK6oaMPQEOKgCsidMcUaA?view) is ready for your review and input. Please note:

- the links need to be double-checked. @valcollignon can you take the lead on this. 
- I revised the data flow mural @sreedevip and think it could be included since the structure of the content herein follows this flow. See what you think and if agree, please create a picture to embed. 
- @sreedevip there is a section herein that points to research about the dataflow. Can you check if there is a more appropriate link to include here? 

Please ping me when the hackmds have been finalized, so I can open the PR with changes to this subdir.

**Comment by sreedevip** [comment]
@ADPennington I love the level of detail on this document. I've left a couple of comments about
- creating a Figma version of the data flow
- adding a couple of sentences on wpr somewhere in the document. 
Also, question - is a WPR report generated at some point?

**Comment by ADPennington** [comment]
@sreedevip --
- yes, please go for it re: figma
- added couple sentences on WPR
- yes WPR report generated. see last FAQ.

**Comment by valcollignon** [comment]
All links have been updated/created.
@sreedevip -- I've added a few comments for your review/input

**Comment by sreedevip** [comment]
@valcollignon I've incorporated the GIthub link as requested, but also added a caveat to that in the comments section of hackmd

**Comment by valcollignon** [comment]
@ADPennington this should be good to go, unless you want to wait to merge until the subdir organization changes are complete in #1527, per @sreedevip's comment above.

**Comment by ADPennington** [comment]
> @ADPennington this should be good to go, unless you want to wait to merge until the subdir organization changes are complete in #1527, per @sreedevip's comment above.

@valcollignon i think this will be ready once the figma diagram is ready. also re: @sreedevip 's q about waiting to merge this until after #1527 is addressed, i'd like to get this one merged before the end of the week, so please let me know if we think 1527 will be ready before then. If not, we can create a clean-up ticket to fix the links.

**Comment by valcollignon** [comment]
Added task for @sreedevip to add Figma link to `Current-TDRS.md`.

@sreedevip - do you think #1527 can be completed by the end of this week?

**Comment by sreedevip** [comment]
Would this be better off in the Background folder?
 https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/Flat%20File%20Metadata%20Guide.md
@ADPennington @valcollignon @reitermb 
cc @lfrohlich

**Comment by ADPennington** [comment]
> Would this be better off in the Background folder? https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/Flat%20File%20Metadata%20Guide.md @ADPennington @valcollignon @reitermb cc @lfrohlich

since its based on research raft did, i don't think it needs to be moved  @sreedevip

**Comment by ADPennington** [comment]
figma diagram embedded in tdrs hackmd. standing by for 1527 PR before this one per @sreedevip

**Comment by sreedevip** [comment]
Based on @ADPennington's comment above, does this need to be somewhere else? https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/STT%20attribute%20guide.md
It doesn't seem to be a direct impact for research done by Raft. Could you confirm @reitermb ?
cc @valcollignon
