### ISSUE TITLE
Update TANF-app/doc/How-We-Work/

### ISSUE THREAD

**Issue by valcollignon** [raft-tech/TANF-app#1523]
### Context:
After #1515 is merged, `TANF-app/doc/How-We-Work/` subdirectory markdowns need to be reviewed and updated. 

### ACs:
- [x] Add README.md w/ TOC
- [x] Move `TANF-app/docs/Technical-Documentation/Heuristics.md` to `TANF-app/doc/How-We-Work/`
- [x] drop `TANF-app/docs/Technical-Documentation/how-government-will-test-a11y.md` (will be worked into `our-priorities-values-expectations.md`)
- [x] drop `Branching-Strategy.md` (redundant w/ git flow adr`)
- [x] drop `Vendor Kick Off Week.md` (obsolete)
- [x] drop `manual-checks.md` (will be worked into `our-priorities-values-expectations.md`)
- [x] drop `Quality-Expectations.md` (will be worked into `our-priorities-values-expectations.md`)
- [x] drop `definition-of-done.md` (will be worked into `our-priorities-values-expectations.md`)
- [x] drop `sprint-schedule.md` (see below)
- [x] promote all markdowns in `TANF-app/docs/How-We-Work/team-charter/ `one level up and delete `team-charter` subdir
- [x] `our-team-and-values.md` should be revised and renamed (to `our-priorities-values-expectations.md`) to exclude team structure details, mission, and vision, and include government priorities and quality expectations (referencing and synthesizing from across [contractual QASP](https://github.com/18F/tdrs-app-rfq/blob/main/Final-RFQ/FINAL-TDRS-software-development-RFQ.md), [PR template](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/.github/pull_request_template.md), and `manual-checks.md`)
- [x] `Team-Composition.md`, which should be updated to include mural re: team norms
- [x] merge `team-meetings.md` and `sprint-schedule.md` into one md. Add table displaying the schedule.
- [x] Update `TANF-app/.github/pull_request_template.md` to reflect updates in `our-priorities-values-expectations.md`
- [ ] Update any broken links within markdowns

### Tasks:
- [x] Create [hackmd](https://hackmd.io/@valeriecollignon/SJH5wi4hK/edit) for subdir `README.md` w/ TOC (`valcollignon`)
- [x] Create [hackmd](https://hackmd.io/@valeriecollignon/rJAeynNht/edit) for `our-priorities-values-expectations.md` and update/revise with information from `manual-checks.md`, `Quality-Expectations.md`, `definition-of-done.md` (`valcollignon`)
- [x] Create [hackmd](https://hackmd.io/@valeriecollignon/ByqCVhEnF/edit) for `Team-Composition.md` (`valcollignon`)
- [x] Create [hackmd](https://hackmd.io/@valeriecollignon/rJ_EHh42t/edit) for `team-meetings.md` and update/revise with information from `sprint-schedule.md`. (`valcollignon`)
- [x] Create [hackmd](https://hackmd.io/qkWpzzbdTwOBEL4Mj0Ikaw) to update pr template (`adpennington`)
- [ ] Review and update any broken links. (`valcollignon`, `lfrohlich`)
- [x] Open draft PR with subdirectory updates (`adpennington`)

### Notes:
Part of the #1477 documentation update epic

**Comment by ADPennington** [comment]
[hackmd](https://hackmd.io/@valeriecollignon/ByqCVhEnF/edit) for team composition updated and ready for review. @valcollignon @lfrohlich

**Comment by lfrohlich** [comment]
team comp looks good to me

**Comment by valcollignon** [comment]
team comp looks good to me as well

[Team Meetings](https://hackmd.io/@valeriecollignon/rJ_EHh42t/edit) is ready for refinement.

**Comment by ADPennington** [comment]
some notes on what i think? are next steps for this ticket:

- @valcollignon to address comments in meetings hackmd and double-check links
- i will focus on quality expections/values markdown. 
- @valcollignon to revise TOC.

**Comment by valcollignon** [comment]
@lfrohlich and @ADPennington - could you please take a look at the [Team Meetings](https://hackmd.io/@valeriecollignon/rJ_EHh42t/edit) HackMD and fill in any blanks, add any updates - specifically in the non-scrum meetings towards the bottom of the list.

**Comment by lfrohlich** [comment]
I made some edits and additions. Added a few comments about where it would be good to link to notes @valcollignon . Thanks!

**Comment by valcollignon** [comment]
@ADPennington - links have been checked. Once you are able to review the Team Meetings HackMD, this should be good to go.

**Comment by ADPennington** [comment]
> @ADPennington - links have been checked. Once you are able to review the Team Meetings HackMD, this should be good to go.

done

**Comment by ADPennington** [comment]
this is now ready for a draft PR.
