### ISSUE TITLE
Update TANF-app/doc/Sprint-Review/

### ISSUE THREAD

**Issue by valcollignon** [raft-tech/TANF-app#1525]
### Context
After #1515 is merged, `TANF-app/doc/Sprint-Review/` subdirectory markdowns need to be reviewed and updated. 

The Sprint Review directory currently does not have any context to how it is organized, why it is needed, or what is covered in the summaries. The creation of a README.md should add clarity and organization to this subdirectory.

### ACs:
- [x] Add README.md 

### Tasks:
- [x] Create [hackmd](https://hackmd.io/@valeriecollignon/HJ_GT6V2F/edit) for subdir `README.md` w/ TOC (`valcollignon`)
- [x] Open draft PR with subdirectory updates (`adpennington`)

### Notes:
Part of the #1477 documentation update epic

**Comment by valcollignon** [comment]
[hackMD] for `Sprint-Review` readme is ready for refinement. Not sure a TOC is needed for this section. 
@ADPennington @lfrohlich

**Comment by ADPennington** [comment]
@valcollignon this hackmd looks good. I'll open a PR for this today.
