### ISSUE TITLE
Update TANF-app/doc/User-Experience/

### ISSUE THREAD

**Issue by valcollignon** [raft-tech/TANF-app#1527]
### Context
After #1515 is merged, `TANF-app/doc/User-Experience/` subdirectory markdowns need to be reviewed and updated. 

### ACs:
- [x] Update existing [README.md](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/README.md) w/ TOC
- [x] This subdir needs a deeper dive audit. There is some outdated information in [here](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs/User-Research)
- [x] Update any broken links within markdowns
- [x] Create subdirectories for research and design, separately

### Tasks:
- [x] Create [hackmd](https://hackmd.io/v1R5-te1Qlq-Of3xpZc6mg) for subdir `README.md` w/ TOC (`sreedevip`)
- [x] Audit the User-Research subdir and determine what is outdated and can be removed (`reitermb`)
 -  **Drop**
    - [x]  `Open research questions.md`
    - [x]  `Overview of Research Activities.md`
    - [x]  `TANF-app/docs/User-Experience/2020, Winter - User Flow Validation/`
    - [x]  `TANF-app/docs/User-Experience/2020, Fall - Concept Prototypes/` 
    - [x]   `TANF-app/docs/User-Experience/Design/` 
- **Move**
  - [x] promote `Design-Principles.md` and `Style-Guide.md` (see below) one level up  into `TANF-app/docs/User-Experience/`
  - [x]  all research syntheses mds  in `TANF-app/docs/User-Experience/` to `TANF-app/docs/User-Experience/Research-Syntheses/` 
  - [x]  contents of `TANF-app/docs/User-Experience/2020, Fall - Concept Prototypes/` to `TANF-app/docs/User-Experience/Research-Syntheses/` and reference them in `2020,Fall Understanding STT roles, source of truth and metadata.md`
- **Change**
  - [x] readme should be converted to table of contents
  - [x] `Design-Guide.md` to `Style-Guide.md` and remove [`Code Docs` section](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/Design/Design-Guide.md#code-docs)
  - [x] `TANF-app/docs/User-Experience/Research/` to  `TANF-app/docs/User-Experience/Research-Syntheses/` 
  - [x]  `Stakeholders-and-Personas.md` to `2020, Summer - Understanding Stakeholders and creating personas.md`
  - [x] `2021, Spring - Evil User Journeys & TANF Data Errors (Round 6).md` to `2021, Spring - Evil User Journeys & TANF Data Errors.md`
  - [x] `Winter 2021, Round 4 Synthesis.md` to `2020, Fall - Understanding STT and OFA painpoints.md`
  - [x] include link to [hackmd version of `ST Workshop Facilitation Guide.md`](https://hackmd.io/0zVjk29lSMyngnzdgpZgqg) in `2020, Fall - Understanding STT and OFA painpoints.md`
  - [x]  `STT Attribute Guide` to `2020, Fall - STT Attribute Guide`
 - **Add**
   - [x] `UX-markdown-practices.md` and include [`Code Docs` section of `design-guide.md`](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/Design/Design-Guide.md#code-docs)
   - [x]  `readme.md` to `TANF-app/docs/User-Experience/Research-Syntheses/` 
   - [x]   `TANF-app/docs/User-Experience/Dev-Ready-Designs/`

- [x] Open draft PR with subdirectory updates (`adpennington`)
- [x] Review and update any broken links (`valcollignon`, `sreedevip`)

### Notes:
@sreedevip and @reitermb: Please be sure to let @ADPennington know which files should be research and which should be design. Once Alex moves things where they need to go, Miles and Sreedevi can update links in PR.

**Comment by valcollignon** [comment]
@reitermb to take the lead on this issue, along with @sreedevip. I estimated the tasks in this issue as a 3. Please re-point, if appropriate.

**Comment by sreedevip** [comment]
I'm wondering the relevancy of the content of design assets/research artifacts. https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs/User-Experience/Design/design-assets/research-artifacts
The artifacts look more suited to elsewhere in Docs like maybe Agency Background, Product Strategy and Project Impact folders. What are your thoughts? 
@ADPennington @lfrohlich  @reitermb @valcollignon

**Comment by valcollignon** [comment]
> The artifacts look more suited to elsewhere in Docs like maybe Agency Background, Product Strategy and Project Impact folders. What are your thoughts?

Would it make sense for these artifacts to move to `TANF-app/docs/Background`?
@ADPennington @lfrohlich @reitermb @sreedevip

**Comment by ADPennington** [comment]
> > The artifacts look more suited to elsewhere in Docs like maybe Agency Background, Product Strategy and Project Impact folders. What are your thoughts?
> 
> Would it make sense for these artifacts to move to `TANF-app/docs/Background`? @ADPennington @lfrohlich @reitermb @sreedevip

yes, if all the artifacts are linked to docs in that subdir. please confirm. @valcollignon @sreedevip cc: @lfrohlich

**Comment by ADPennington** [comment]
looked at this again -- i'm not sure it makes sense for these images to live anywhere other than in their native markdowns which are across a few subdirs. I'd recommend getting them into the appropriate hackmds as image embeds and modifying tasks as needed. @valcollignon can you take the lead on this? cc: @lfrohlich @sreedevip

**Comment by ADPennington** [comment]
@valcollignon @sreedevip update 😄 -- I've created image links for the following markdowns, so this [folder](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/docs/User-Experience/Design/design-assets/research-artifacts) can be deleted as part of the cleanup in this ticket:
- [Agency-Background.md](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Background/Agency-Background.md) will include `acf_org_chart.png`
- [Considerations-and-Planning.md](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Product-Strategy/Considerations-and-Planning.md) will include `TDRS product plan at four levels.png`, `considerations to the plan.png`, and `three product considerations.png`
- [Vision-and-Stakeholders.md](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Product-Strategy/Vision-and-Stakeholders.md) will include `TANF Theory of Change.png` and `TDRS-stakeholder-map.png`

**Comment by sreedevip** [comment]
User Experience subdir [hackmd](https://hackmd.io/v1R5-te1Qlq-Of3xpZc6mg) is ready for review. @ADPennington @reitermb @valcollignon  

Includes
- Proposed structure for TANF-app/docs/User-Experience/
- Suggested Name changes for Research syntheses + questions about a few filenames
- Open questions 
- Files to be deleted
cc @lfrohlich 

We may need to sync/async decide which Mural links to keep in the public repo and where the rest will live. See comment thread on hackmd

**Comment by sreedevip** [comment]
Mural links suggestions are now updated on hackmd](https://hackmd.io/v1R5-te1Qlq-Of3xpZc6mg) and is ready for review. Once everyone reviews content and suggestions, this will be ready to merge
@ADPennington @reitermb @valcollignon

**Comment by ADPennington** [comment]
decided on 1/19 at ux sync to hide mural links in readme and revisit and reorganize at later date.

**Comment by ADPennington** [comment]
[hackmd](https://hackmd.io/0zVjk29lSMyngnzdgpZgqg) that will replace [`ST Workshop Facilitation Guide.md`](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/User-Experience/2020%2C%20Winter%20-%20User%20Flow%20Validation/ST%20Workshop%20Facilitation%20Guide.md) and be linked in appropriate synthesis doc.
