### ISSUE TITLE
Optimize python container and remove redundant commands

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#1530]
**Description:**
Current backaned python container is built from Slim-Buster version (see Backend.Docekrfile line 1:  ``` FROM python:X.Y.Z-slim-buster```). The dockerfile also uses the following commands to fetch the latest package list available to container linux os and then upgrade the installed packages:

***Dockerfile:***
```
...
RUN apt-get -y update
# Upgrade already installed packages:
RUN apt-get -y upgrade
# Install a new package:
RUN apt-get install -y gcc && apt-get install -y graphviz && apt-get install -y graphviz-dev
...
```
however, the slim-buster python image already includes linux update/upgrade and gcc installation and the above commands are partially redundant. (see https://github.com/docker-library/python/blob/db32c7803dfc67e5a359514371e66d6405695e45/3.10/buster/slim/Dockerfile)

Removing the redundant commands should reduce the build time.

Caveat: It should be noted that if package update and upgrade are being removed from the dockerfile, any build from cached images will not be based on updated packages (latest version of installed packages).

**Acceptance Criteria:** 

- [ ] All python packages be installed with no errors in "web" container
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Remove apt-get update, upgrade and gcc install from Dockerfile
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] Make sure all python packages are installed without error
- [ ] Update documentation to reflect the difference between cached and non-cached builds

**Notes:**

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Slim Buster Docker File](https://github.com/docker-library/python/blob/db32c7803dfc67e5a359514371e66d6405695e45/3.10/buster/slim/Dockerfile)
- [Python official images](https://hub.docker.com/_/python?tab=tags)

**Open Questions:** 

- _Is there any need to update the packages between builds using cached images?_

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

@raftmsohani ?

**Comment by robgendron** [comment]
Deemed closed by Mo and Alex.
