### ISSUE TITLE
Update hero images 

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1532]
**Description:**
Update hero images with new widened versions from #1346 .

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Splash page for unauthenticated users displays use images from [these mockups](https://reitermb.github.io/TDP-Project-Update/)
- [ ] Images are not cut off by button text box
- [ ] No other frontend settings should be changed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update hero images used to those linked below.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- Please see [last time we updated them](https://github.com/raft-tech/TANF-app/pull/1383/files) for a reference.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Hero image 1](https://github.com/reitermb/TDP-Project-Update/blob/main/img/HI1.jpg)
- [Hero image 2](https://github.com/reitermb/TDP-Project-Update/blob/main/img/HI2.jpg)
- [Hero image 3](https://github.com/reitermb/TDP-Project-Update/blob/main/img/HI3.jpg)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
