### ISSUE TITLE
As a developer, I want to share tests across our authentication sources

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1540]
**Description:**
_Provide a brief background and justification for this issue_
While working on #1136, we didn't have bandwidth to refactor tests in the manner we'd like. As much as possible, we don't want duplicate basic tests between the authentication sources such as `test_login_with_valid_state_and_code()`. We can leverage [parameterize](https://docs.pytest.org/en/6.2.x/parametrize.html) to run the same test logic for multiple classes (LoginDotGov, AMS, and now NextGenXMS).

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] There are shared "common" tests between Login.gov, AMS, and NextGen for [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
- [x] We can easily see and justify unique-to-source tests.
- [x] New common tests correctly capture test functionality
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Exhaustively identify common tests and unique tests
- [x] Create new tests (perhaps w/ a TestAuth class) from existing tests
- [x] Remove obsolete tests
- [x] Retain unique tests in their current structure
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Parameterize](https://docs.pytest.org/en/6.2.x/parametrize.html)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by valcollignon** [comment]
@abottoms-coder to refine ticket further per backlog refinement 1.18.22

**Comment by raftmsohani** [comment]
The following tests need to be refactored: 

![image](https://user-images.githubusercontent.com/97037188/153001249-500252bd-729a-4746-8897-4a7517a72771.png)
![image](https://user-images.githubusercontent.com/97037188/153001386-1be4441a-fb89-4304-bda5-f635b2d8ce43.png)

**Comment by raftmsohani** [comment]
The parametrization is done using ["getfixturevalue"](https://docs.pytest.org/en/6.2.x/reference.html#pytest.FixtureRequest.getfixturevalue).
