### ISSUE TITLE
As technical lead, I want updated authentication documentation

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1541]
**Description:**
_Provide a brief background and justification for this issue_
Currently, our [authentication documentation](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/tdrs-backend/docs/api) is pre-[AMS](https://github.com/raft-tech/tanf-app/issues/1136) and was obsolete before that when we implemented SwaggerUI. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] This new doc(s) is linked in the Technical Documentation table of contents from #1526. 
- [ ] A UML class flow diagram is present w/ application file::class:function notation
- [ ] New documentation is up to date
- [ ] Obsolete documentation is updated or discarded
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- Please see [openid-connect.md](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/openid-connect.md)
- 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Should we make `tdrs-backend/docs/api` updated or should we throw that away and make new docs in `tdrs-backend/tdpservice/users/api/`?

**Comment by robgendron** [comment]
Updating re: KeyCloak and API tokenization @andrew-jameson

**Comment by lhuxraft** [comment]
Revisit in the next six months as we determine next steps for authentication

**Comment by lhuxraft** [comment]
No longer important
