### ISSUE TITLE
Migrate Design's Live Comms Site into the TANF-app repo. 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1545]
**Description:**
Design is experimenting with a move to a web format rather than a PDF format for live comms to take advantage of accessibility improvements offered by web that don't come as simply in PDF form.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] The existing live comms repo is moved from Miles' repo to an existing project repo (TANF-app)
- [ ] Design is still able to maintain the live comms site as they do on its current GitHub Pages hosting (e.g. no/minimal new code introduced to make it work, control over dependencies)
- [ ] Hosted via cloudfoundry cloud.gov route
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Refactor html files for general purpose static use (currently tied to github website) 
- [ ] setup static file Cloud foundry build pack for cloud.gov
- [ ] Add CI workflow for deploying changes
- [ ] Add commands to locally test changes via simple HTTP server on localhost
- [ ] Add documentation for local development and deployment of the application

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

Current code:
Link to site: https://reitermb.github.io/TANF-Data-Portal-Updates/
Link to repo: https://github.com/reitermb/TANF-Data-Portal-Updates/blob/main/index.html

**Open Questions:**

**Comment by reitermb** [comment]
cc: @abottoms-coder

**Comment by valcollignon** [comment]
@riatzukiza  to add tasks to this issue. This ticket can be pulled into the current sprint.

**Comment by riatzukiza** [comment]
I had a conversation with @reitermb  about the nav buttons, we found the changes he made and reintroduced the css file he'd originally changed. It got removed in the great cleansing.
