### ISSUE TITLE
[SPIKE] As tech lead, I need ACF AMS configured to work in multiple TDP envs and spaces

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1552]
Currently, authenticating via ACF AMS is _only_ possible via `https://tdp-frontend-raft.app.cloud.gov/`. Based on documentation provided by ACF AMS Ops team, it appears that only one root url can be used for the configuration (the one above). We need to follow-up with the Ops team to find out if this can be changed, and if so, how. 

In the  meantime, this limitation means that authentication via ACF AMS will not work in other envs within the `tanf-dev` space in cloud.gov, nor will it work in `tanf-staging` and `tanf-prod`. 

### Tasks:
- [x] reach out to ACF AMS Ops to inquire about feasibility for this. 
- [x] if feasible, confirm implementation strategy before closing this spike. (`jorgegonzalez`)
- [x] (Implementation strategy) update client ID and key in cloud.gov and restage staging applications (`adpennington`)
- [ ] create a new ticket if implementation requires a code change (`jorgegonzalez`)

**Comment by ADPennington** [comment]
@valcollignon please add this spike to acf ams epic.

**Comment by valcollignon** [comment]
@ADPennington to reach out to OCIO, possibly today 1.25.22

**Comment by ADPennington** [comment]
1/25/2022 Update:

- ACF OCIO indicated that we'll need to submit a service request to set up ACF AMS to work in the TDP staging environment. I submitted this request via email today. 
  - Once it is addressed, we can open a new ticket to track the implementation work as part of #1134 epic 
- They also indicated that a more involved process would be required when we are ready to set this up to work in the ACF and TDP prod environments. The change request template is saved [here](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/Authentication%20%26%20Authorization/ACF%20AMS%20docs/OCIO%20OPERATIONS%20REQUEST%20TEMPLATES.docx?d=w5332585c1ecf49a4aeda17674f687154&csf=1&web=1&e=uiUsHo) and is estimated to take 1-2 weeks to obtain approval. It will involve a presentation to ACF OCIO team. 
  - We will need a ticket to track this as part of #721. 

@jorgegonzalez provided a helpful diagram below to illustrate where these integrations will live. 
![Screen Shot 2022-01-25 at 12 38 17 PM](https://user-images.githubusercontent.com/63075587/151040419-d4f2a6b2-29ba-4a86-bb75-9bbc7c549068.jpg)


cc: @lfrohlich @valcollignon @abottoms-coder

**Comment by ADPennington** [comment]
### 1/27/2022 update

ACF OCIO:
-  provided a client id and key to use for TDP staging
- confirmed that the endpoint URLs used in TDP dev env will be the same for TDP staging env (since these are both leveraging ACF AMS staging)
- and confirmed our logout, callback, and callback redirect URLs for tdp staging. 

per @jorgegonzalez 's recommended next steps--I updated the client id and key in cloud.gov for our staging backend and restaged the apps as shown below. 

I confirmed that I can now authenticate via ACF AMS with my piv in [TDP staging](https://tdp-frontend-staging.app.cloud.gov/), so this spike can be closed. 

cc: @lfrohlich  @abottoms-coder @valcollignon @ttran-hub

```
apennington@HHSL9XYTF13 MINGW64 / (master)
$ cf login -a api.fr.cloud.gov  --sso
API endpoint: api.fr.cloud.gov

Temporary Authentication Code ( Get one at https://login.fr.cloud.gov/passcode ): <redacted passcode>

Authenticating...
OK


Select an org:
1. hhs-acf-prototyping
2. sandbox-hhs

Org (enter to skip): hhs-acf-prototyping
hhs-acf-prototyping
Targeted org hhs-acf-prototyping.

Select a space:
1. tanf-dev
2. tanf-prod
3. tanf-staging

Space (enter to skip): tanf-staging
tanf-staging
Targeted space tanf-staging.

API endpoint:   https://api.fr.cloud.gov
API version:    3.112.0
user:           alexandra.pennington@acf.hhs.gov
org:            hhs-acf-prototyping
space:          tanf-staging

apennington@HHSL9XYTF13 MINGW64 / (master)
$ cf apps
Getting apps in org hhs-acf-prototyping / space tanf-staging as alexandra.pennington@acf.hhs.gov...

name                   requested state   processes   routes
clamav-rest            started           web:1/1     tanf-staging-clamav-rest.apps.internal
tdp-backend-staging    started           web:1/1     tdp-backend-staging.app.cloud.gov
tdp-frontend-staging   started           web:1/1     tdp-frontend-staging.app.cloud.gov

apennington@HHSL9XYTF13 MINGW64 / (master)
$ cf restage tdp-backend-staging
This action will cause app downtime.

Restaging app tdp-backend-staging in org hhs-acf-prototyping / space tanf-staging as alexandra.pennington@acf.hhs.gov...

Staging app and tracing logs...

<redacted logs for length>
  
Restarting app tdp-backend-staging in org hhs-acf-prototyping / space tanf-staging as alexandra.pennington@acf.hhs.gov...

Stopping app...

Waiting for app to start...

Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...
Instances starting...

name:              tdp-backend-staging
requested state:   started
routes:            tdp-backend-staging.app.cloud.gov
last uploaded:     Thu 27 Jan 15:16:00 EST 2022
stack:             cflinuxfs3
buildpacks:
        name               version   detect output   buildpack name
        python_buildpack   1.7.48    python          python

type:           web
sidecars:
instances:      1/1
memory usage:   256M
     state     since                  cpu    memory           disk           details
#0   running   2022-01-27T20:16:41Z   0.4%   207.2M of 256M   406.2M of 2G
```
