### ISSUE TITLE
As a developer, I need the uswds update to comply with accessibility requirements

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1557]
**Description:**
_Provide a brief background and justification for this issue_
Per @jorgegonzalez 's comment on pull #1500, we need a secondary issue to track the manual changes required.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Frontend is deemed compliant with a11y standards
- [ ] Pull request for this ticket targets dependabot branch `dependabot/npm_and_yarn/tdrs-frontend/raft-tdp-main/uswds-2.13.0`
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Manual markup changes as dictated by compliance and uswds spec
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by valcollignon** [comment]
This should not be picked up before NextGen is completed. Per backlog refinement 1.25.22.

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
