### ISSUE TITLE
As OFA Product Owner, I want only Data Analysts to be able to use NextGenXMS for authentication

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1559]
**Description:**
_Provide a brief background and justification for this issue_
As we delineated use of authentication sources in #1170, we have a corollary here that we only want NextGenXMS to be used by Data Analyst users.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] User's authentication is redirected back to our frontend
- [ ] Users with OFA staff-related roles (or perhaps simply, does not have Data Analyst role) fail login
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement conditional checks for role during the login process akin to the `verify_email()` function written in #1170
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by stevenino** [comment]
Not technically required for v1.0

**Comment by stevenino** [comment]
Will not do NexGen XMS
