### ISSUE TITLE
Admin summary list of roles and user counts

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#156]
Description:
OFA Admins need high level information about the number of users in each role. This issue will deliver number of roles and user counts. 

### Acceptance Criteria:

- [ ] The list indicates which how many users in each role
- [ ] Adds a column in Django admin
- [ ]  Admin can view a summary list of roles and user accounts

### Frontend Tasks
- [ ] Get list of users from endpoint and store in Redux Store
- [ ] Total number of users by category 
- [ ] Add `Add Role` button
- [ ] Create table using USWDS table component (https://designsystem.digital.gov/components/table/)

Points:

#### Backend Tasks
- [ ] Test endpoint returns summary list
- [ ] Test that only OFA Admins or Superusers can get the list of all users
- [ ] Create endpoint to return summary list

Points: 3

Note:
- Django has a default mechanism for handling this and this issue will use the default way of implementing the Django permissions system. Adjusting the permission system will be addressed with a different ticket.
- 'Add a role' is post MVP. **For MVP, roles will be added via backend/database**
- Summary list of report to be pulled from the backend for OFA MVP. 
 
### Open Question(s):

- Given that this issues meets IA-04(04) a [security control](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/ATO/TDP-%20Selected-%20FedRAMP-Controls-MODERATE_CIS_20200916.xlsx?d=w14f87c6b61ec4c2da4b83d43c7427e38&csf=1&web=1&e=T146zo), do we need the UI? Or, roles added via backend/database suffice to meet the security control?
- Backend will suffice
**- Need to decide if to keep this in Django and or when to port to an app based UI.**
- V1 functionality desired, but can punt UX enhancements to V3/4

### Supporting Documentation:

![Screen Shot 2020-10-07 at 10.47.29 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/2287b48c-d410-4441-9d0d-4c085e4040ce)

**Comment by lfrohlich** [comment]
@carltonsmith FYI we merged #149 into this one

**Comment by lfrohlich** [comment]
@hilvitzs  can you fill frontend tasks before next sprint planning? Thanks!

**Comment by lfrohlich** [comment]
Per Backlog discussion 11.30.21 we are leaning towards keeping this in Django Admin as opposed to in-app UI but want @ADPennington to weigh in

**Comment by valcollignon** [comment]
Will discuss this epic in 12.3 product/tech sync
CC: @abottoms-coder @lfrohlich @abottoms-coder
