### ISSUE TITLE
As a Data Analyst user, I need to have a frontend button to direct me to XMS login portal

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1560]
**Description:**
_Provide a brief background and justification for this issue_
We will need to update our current Login.gov button to a NextGenXMS button.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Splash page will only have two buttons: one for login.gov via XMS and one for ACF AMS
- [ ] New button links to XMS portal
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update button and link to XMS
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- What is the NextGenXMS URL needed?
-- https://int.xms.hhs.gov/ABaaS/idp

- Does NextGenXMS have a logo we need to incorporate?
-- Yes they have a logo, but it's not required.

- Does XMS have to be explicitly mentioned on the button?
-- No. The reason to mention it would be that XMS eventually plans to have other means of logging in besides login.gov. We will change the label on the button if/when that becomes necessary.

**Comment by valcollignon** [comment]
Is this button actually going to lead to a NextGen portal or login.gov? 
CC: @ADPennington

**Comment by valcollignon** [comment]
@abottoms-coder to add NextGen XMS URL to open questions section of this ticket. Per backlog refinement 2.8.22
