### ISSUE TITLE
As a developer, I need to be able to form outgoing NextGenXMS requests 

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1561]
**Description:**
_Provide a brief background and justification for this issue_

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Ensure user is redirected back to our application (`/v1/loginXMS/` route) after authentication with NextGenXMS
- [x] Direct user to NextGenXMS with appropriate metadata
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary
- [x] [`openid-connect.md`](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/openid-connect.md) is updated to match these new requests for NextGenXMS.

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

 - [x] Perform basic tests on OpenID endpoint via curl/bash/etc.
 - [x] Create XMS structure with associated environment variables, JWT, payload items, etc. like in #1136
- [x] Package and encode request for NextGenXMS OpenID endpoint
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by valcollignon** [comment]
May pull this into Sprint 41 if there is bandwidth. Per backlog/sprint planning 2.15.22.
CC: @abottoms-coder

**Comment by raftmsohani** [comment]
Getting error using the [commit](https://github.com/raft-tech/TANF-app/commit/86f2c8a3edd7399bfa604b01a444a6f044c6b911) with XMS-1003 code.
![image.png](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/3414d2b9-8763-4c95-8adf-fb1e49898ec9)

Looks like the body data is not correct.

**Comment by abottoms-coder** [comment]
Emailed Michael Hugney at DeLoitte with above error and our url/configuration(s). Paired with Mo and got a WIP PR opened for deployment to recreate his local environment error in our dev env. Hope to see this needle move soon.

### Configuration/Solution:

```
URL: https://int.xms.hhs.gov/ABaaS/oidc/authorize

auth_params = {

            "acr_values": "http://idmanagement.gov/ns/assurance/ial/1",

            "client_id": "U2Xzpq6_ZA_5M~Z",

            "nonce": "####",

            "redirect_uri": "https://tdp-backend-raft.app.cloud.gov/oidc/xms",

            "response_type": "code",

            "state": "####",

        }

auth_endpoint_with_scope = encode_params(auth_params) + "&scope=openid+email"
```

### URL request:
```
https://int.xms.hhs.gov/ABaaS/oidc/authorize?acr_values=http%3A%2F%2Fidmanagement.gov%2Fns%2Fassurance%2Fial%2F1&client_id=U2Xzpq6_ZA_5M~Z&nonce=da288341fb51903523799162a66071aaf19d6204fd0c85a78080e7f46fd06e19&redirect_uri=https%3A%2F%2Ftdp-backend-raft.app.cloud.gov%2Fv1%2Foidc%2Fxms&response_type=code&state=0513703fa08b942038cb42bc9517014176643bedd5967232eb9757e11dbf4add&scope=openid+email
 
```

**Comment by abottoms-coder** [comment]
@raftmsohani 

The reason our logging "wasn't working" was due to the fact their request was a POST, not a get like the other authentication sources. Adding the post request and then forwarding over the request results in some useful logging:

```python
class TokenAuthorizationXMS(TokenAuthorizationOIDC):
    """Define methods for handling login request from login.gov."""

[omitted]

    def post(self, request):
        logger.info("test")
        logger.info(str(request))
        return self.get(request) # this sends the info over to our standard functions.
```

```python
    def get(self, request, *args, **kwargs):
        """Handle decoding auth token and authenticate user."""
        logger.info("tokenoidc::get")
        try:
            logger.info(dir(request.POST))
            logger.info(request.POST)
            logger.info(request.data)
            logger.info(request.POST.user)
        except AttributeError as e:
            logger.info("oops, tried member that doesn't exist")
            pass
```


Logging:
```
   2022-03-22T14:46:25.45-0400 [APP/PROC/WEB/0] ERR [2022-03-22 18:46:25 +0000] [517] [INFO] Booting worker with pid: 517
   2022-03-22T14:46:25.70-0400 [APP/PROC/WEB/0] ERR [2022-03-22 18:46:25 +0000] [516] [DEBUG] GET /v1/auth_check
   2022-03-22T14:46:25.91-0400 [APP/PROC/WEB/0] ERR INFO Auth check FAIL for user on 2022-03-22 18:46:25.913780+00:00
   2022-03-22T14:46:25.91-0400 [APP/PROC/WEB/0] OUT 10.255.182.29 - - [22/Mar/2022:18:46:25 +0000] "GET /v1/auth_check HTTP/1.1" 200 23 "https://tdp-frontend-raft.app.cloud.gov/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
   2022-03-22T14:46:25.91-0400 [RTR/3] OUT tdp-backend-raft.app.cloud.gov - [2022-03-22T18:46:25.698856954Z] "GET /v1/auth_check HTTP/1.1" 200 0 23 "https://tdp-frontend-raft.app.cloud.gov/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "127.0.0.1:41822" "10.10.1.17:61307" x_forwarded_for:"71.47.206.2, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"3ec3d46f-c6a3-48bc-4a95-105ed69058cd" response_time:0.216966 gorouter_time:0.000112 app_id:"982b2c9a-09ff-4c8b-93c5-b01aff53cc63" app_index:"0" instance_id:"e1b6cb7f-24b1-48ed-46ce-0211" x_cf_routererror:"-" x_b3_traceid:"0cb1e40e3d89bc096755d6e0893c973a" x_b3_spanid:"6755d6e0893c973a" x_b3_parentspanid:"-" b3:"0cb1e40e3d89bc096755d6e0893c973a-6755d6e0893c973a"
   2022-03-22T14:46:37.22-0400 [APP/PROC/WEB/0] ERR [2022-03-22 18:46:37 +0000] [516] [DEBUG] GET /v1/login/xms
   2022-03-22T14:46:37.22-0400 [APP/PROC/WEB/0] ERR INFO redirect:xms:get
   2022-03-22T14:46:37.22-0400 [APP/PROC/WEB/0] ERR INFO redirect:xms:get before urlencode
   2022-03-22T14:46:37.22-0400 [APP/PROC/WEB/0] ERR INFO redirect:xms:get after urlencode
   2022-03-22T14:46:37.22-0400 [APP/PROC/WEB/0] ERR INFO redirect:xms:get right before return
   2022-03-22T14:46:37.23-0400 [APP/PROC/WEB/0] OUT 10.255.182.29 - - [22/Mar/2022:18:46:37 +0000] "GET /v1/login/xms HTTP/1.1" 302 0 "https://tdp-frontend-raft.app.cloud.gov/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
   2022-03-22T14:46:37.23-0400 [RTR/1] OUT tdp-backend-raft.app.cloud.gov - [2022-03-22T18:46:37.221504377Z] "GET /v1/login/xms HTTP/1.1" 302 0 0 "https://tdp-frontend-raft.app.cloud.gov/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "127.0.0.1:65064" "10.10.1.17:61307" x_forwarded_for:"71.47.206.2, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"ba4e22c6-2be5-43d4-6d8b-fc121202708d" response_time:0.010301 gorouter_time:0.000125 app_id:"982b2c9a-09ff-4c8b-93c5-b01aff53cc63" app_index:"0" instance_id:"e1b6cb7f-24b1-48ed-46ce-0211" x_cf_routererror:"-" x_b3_traceid:"53f85033e540ee1b6032dc9b6a57b793" x_b3_spanid:"6032dc9b6a57b793" x_b3_parentspanid:"-" b3:"53f85033e540ee1b6032dc9b6a57b793-6032dc9b6a57b793"
   2022-03-22T14:46:37.73-0400 [APP/PROC/WEB/0] ERR [2022-03-22 18:46:37 +0000] [517] [DEBUG] POST /v1/oidc/xms
   2022-03-22T14:46:37.79-0400 [APP/PROC/WEB/0] ERR [2022-03-22 18:46:37 +0000] [518] [INFO] Booting worker with pid: 518
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO testy
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO <rest_framework.request.Request: POST '/v1/oidc/xms'>
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO tokenoidc::get
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO ['__class__', '__class_getitem__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_assert_mutable', '_encoding', '_getlist', '_mutable', 'appendlist', 'clear', 'copy', 'dict', 'encoding', 'fromkeys', 'get', 'getlist', 'items', 'keys', 'lists', 'pop', 'popitem', 'setdefault', 'setlist', 'setlistdefault', 'update', 'urlencode', 'values']
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO <QueryDict: {'code': ['QLwmpKvlCqqbL8P3Gpwy4xFn6aI8~9WDBbm3C4t20q5f8~yYIgTcfyQiMe8d~TP5TrkVe_-e2zH5TYBOuGDySJU7dO38NP1DgMkilDr4C0k7r.g6v-ex1VVS~GnWOWNf'], 'state': ['5a0f56c6f6ccda13b304bfc34d757157816c5f37e80628657b834f215f0fa150']}>
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO <QueryDict: {'code': ['QLwmpKvlCqqbL8P3Gpwy4xFn6aI8~9WDBbm3C4t20q5f8~yYIgTcfyQiMe8d~TP5TrkVe_-e2zH5TYBOuGDySJU7dO38NP1DgMkilDr4C0k7r.g6v-ex1VVS~GnWOWNf'], 'state': ['5a0f56c6f6ccda13b304bfc34d757157816c5f37e80628657b834f215f0fa150']}>
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO oops, tried member that doesn't exist
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] OUT state: None
   2022-03-22T14:46:37.99-0400 [APP/PROC/WEB/0] ERR INFO Redirecting call to main page. No code provided.
   2022-03-22T14:46:38.00-0400 [APP/PROC/WEB/0] OUT 10.255.182.29 - - [22/Mar/2022:18:46:37 +0000] "POST /v1/oidc/xms HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
   2022-03-22T14:46:38.00-0400 [RTR/2] OUT tdp-backend-raft.app.cloud.gov - [2022-03-22T18:46:37.733243111Z] "POST /v1/oidc/xms HTTP/1.1" 302 212 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "127.0.0.1:55510" "10.10.1.17:61307" x_forwarded_for:"71.47.206.2, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"a790a711-97db-4408-6868-5a98dee924ce" response_time:0.267908 gorouter_time:0.000158 app_id:"982b2c9a-09ff-4c8b-93c5-b01aff53cc63" app_index:"0" instance_id:"e1b6cb7f-24b1-48ed-46ce-0211" x_cf_routererror:"-" x_b3_traceid:"6b0183b75b9048b4497a6d09a6b2441a" x_b3_spanid:"497a6d09a6b2441a" x_b3_parentspanid:"-" b3:"6b0183b75b9048b4497a6d09a6b2441a-497a6d09a6b2441a"
```

**Comment by abottoms-coder** [comment]
Pushing commit which results in this backend response for the user:

```
{"error":"Email verified, but experienced internal issue with login/registration."}
```

**Comment by raftmsohani** [comment]
Screenshots from XMS login:
After pushing the button on the frontend to login:

![xms1.PNG](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/22b78cd9-fd0b-4b2b-9cf5-e7d5f3a8365c)

![xms2.PNG](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/0a1fab1f-73c2-40f2-be2e-1f13ca09a02e)

![xms3.PNG](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/417b8c03-5735-46b2-81c6-39f73a56349d)

**Comment by raftmsohani** [comment]
TODO: We still need to add the conde to handle login
