### ISSUE TITLE
[Spike] As a developer, we need to make model changes for users to utilize NextGenXMS

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1562]
**Description:**
_Provide a brief background and justification for this issue_
We need to be certain that the user model can handle being processed by NextGenXMS authorization -- we discovered this during implementation of ACF AMS that updates were needed and wanted to ensure this work was carved out for this epic.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] User models can be updated with relevant NextGenXMS metadata
- [x] Changes should be backwards compatible and/or additive
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Research provided documentation for what is provided in the payload (see parent epic description for documentation links)
- [x] Update model code and/or migrations if necessary for new identifier field(s)
- [x] Update CustomAuthentication to handle the new model
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Can we utilize current users past login_uuid? If not, what is the equivalent unique identifier?

**Comment by valcollignon** [comment]
Add to agenda for kickoff meeting
CC: @lfrohlich @ADPennington
