### ISSUE TITLE
As tech lead, I need Django vulnerabilities addressed. 

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1563]
**Description:**
_Provide a brief background and justification for this issue_
From a dependabot security alert, Django 3.2.10 has a known vulnerability and needs to be updated to 3.2.11.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Bump Django version
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Security release](https://www.djangoproject.com/weblog/2022/jan/04/security-releases/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
