### ISSUE TITLE
Add check box to template for table top review

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1567]
**Description:**

In order to keep track of what work has had a satisfactory table top, we would like to add a check box to the requirements before the qasp requirements.

**Acceptance Criteria:** 

- [ ] There is a checkbox for pre-qasp table top review
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Add to github pr template before qasp section
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by ADPennington** [comment]
revisions to this ticket:
------
tabletop checkbox should be in the PR template. between `how to test` and `deliverables`
@riatzukiza to revise issue

Priority of this ticket:
------
low. bring it into this sprint.
