### ISSUE TITLE
As tech lead, I need the Dependabot config updated to allow for more PRs to be opened

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1568]
**Description:**

After stumbling into the Django security alert provided by Dependabot (#1563), we noticed that a PR was not automatically opened by Dependabot. The reason is noted [here](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit):

>By default, Dependabot opens a maximum of five pull requests for version updates. Once there are five open pull requests, new requests are blocked until you merge or close some of the open requests, after which new pull requests can be opened on subsequent updates.

Our limit is usually reached quickly by our frontend dependencies. See [here](https://github.com/raft-tech/TANF-app/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies+author%3Aapp%2Fdependabot). Because of this, it is unclear how much of a backlog  (both for our front- and backend dependencies) of dependency updates are accumulating. 

The dependabot documentation above suggests that we can increase this limit by `package-ecosystem` which at a minimum provide us with some visibility into dependencies needing updates for both sides of our application. But we may also want to consider revisit ing our temporary [dependabot backlog-clearing workflow](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/Architecture-Decision-Record/014-dependabot-dependency-management.md#consequences)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _dependabot config updated to increase limit by `package_ecosystem`_
- [ ] _TBD_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Decide whether or not to revisit backlog-clearing workflow. If so, we need to document process)_
- [ ] _Decide on open-pull-requests-limit_
- [ ] _Update config_
- [ ] _TBD..._

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _[Example task list used in previous dependabot backlog-clearing](https://github.com/raft-tech/TANF-app/issues/1023)_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Should we investigate and clear the backlog? or just increase the `open-pull-requests-limit`?_
- _What should our `open-pull-requests-limit` be? What is reasonable for `dev` team to manage?_

**Comment by valcollignon** [comment]
Discuss in next dev sync.
CC: @ADPennington

**Comment by ADPennington** [comment]
per dev sync 2/2:
- no need for a temporary backlog clearing exercise because backlog currently not an issue. 
- dependency PRs mgmt: @abottoms-coder  + @valcollignon  will check dependency PRs daily to confirm assignments to dev team
- PR limit increase: 10 per package-ecosystem
- if non-trivial work required in dependency review, new issues created with point estimates assigned. 
- confirmed that if conflicting dependencies, PRs will not be automatically opened.

**Comment by stevenino** [comment]
No longer required per backlog refinement on 9/27/22
