### ISSUE TITLE
Upgrade react-router packages and refactor related components

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1576]
**Description:**

[This](https://github.com/raft-tech/TANF-app/pull/1506) dependabot PR was opened with an upgrade for `react-router-dom`, however `react-router` and `react-router-dom` need to be upgraded in parallel. These upgrades include breaking changes, and are incompatible with any version of `connected-react-router`, so that package must be replaced with an alternative, [`redux-react-router`](https://github.com/lagunovsky/redux-react-router).

https://github.com/supasate/connected-react-router/issues/543

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `react-router` and `react-router-dom` are upgraded to latest major version
- [ ] package.json is updated
- [ ] package-lock.json is updated
- [ ] All existing behavior and application functionality should remain identical
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Upgrade `react-router`, `react-router-dom` with npm
- [x] Refactor usages of `react-router` and `react-router-dom`
- [x] Replace `connected-react-router` with `redux-react-router`
- [x] Refactor all relevant tests (probably the failing ones)
- [x] Run Testing Checklist and confirm all tests pass
