### ISSUE TITLE
Spike - Dependabot - Upgrade react-scripts to 5.0

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1577]
**Description:**

Dependabot opened an upgrade to `react-scripts@5.0.0.` which includes breaking changes, and likely some unknown unknowns.

https://github.com/facebook/create-react-app/issues/11756

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `react-scripts` is updated to latest major version
- [ ] `file-type` is updated to latest major version
- [ ] package.json is updated
- [ ] package-lock.json is updated
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Upgrade `react-scripts` to latest major version with npm
- [ ] Manually install required polyfills
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] Generate follow-on tickets with identified improvements (e.g., compliance, ally refactor)

**Comment by jorgegonzalez** [comment]
https://github.com/raft-tech/TANF-app/pull/1575

**Comment by jorgegonzalez** [comment]
`file-type` should also be upgraded when this is implemented as `react-scripts#5` will support ESM

ref: 
https://github.com/sindresorhus/file-type/issues/505 
https://github.com/sindresorhus/file-type/issues/502 
https://github.com/sindresorhus/file-type/issues/515
https://github.com/sindresorhus/file-type/issues/521
https://github.com/sindresorhus/file-type/issues/528

**Comment by valcollignon** [comment]
@ADPennington to sync with @jorgegonzalez on the priority of this ticket. per backlog refinement 2.8.22

**Comment by ADPennington** [comment]
per @jorgegonzalez, this is not a high priority and can be revisited in a later sprint. okay for the backlog @valcollignon cc: @abottoms-coder @lfrohlich

**Comment by ADPennington** [comment]
3/16/22: 

- decided during dev sync to revisit this ticket after nextgen xms epic (#1153) completed. 
- dependabot security alerts (highs and criticals) will be discussed weekly at dev syncs.

**Comment by riatzukiza** [comment]
In #1813 dependabot notified us that redux 4.2.0 is depreciating the `createStore` interface we use, in favor of a new library react-toolkit
https://redux.js.org/introduction/why-rtk-is-redux-today

This change requires a full refactor of our redux code, it would be more readable and easier to maintain, and the changes aren't complicated, there would just be a lot of it. This is largely a quality of life update, and can probably be done around the same time as our update to react-scripts

**Comment by lhuxraft** [comment]
Update to a tech memo ticket (spike) for next sprint

**Comment by lhuxraft** [comment]
11/20: Working on upgrading dependencies

**Comment by lhuxraft** [comment]
11/22: Making progress - updated most packages. Updated USWDS breaking changes. Working on getting tests to pass, more complex than expected. Will be doing a tech memo to recap work

**Comment by lhuxraft** [comment]
12/2: Having issue with file type library, experimenting with other libraries. Existing issues with tests

**Comment by lhuxraft** [comment]
Follow-on tickets may want to be taken in during following sprint (after Dec 17)

**Comment by lhuxraft** [comment]
12/4: Tests fixed and requested reviews

**Comment by lhuxraft** [comment]
12/9: Reviewing comments from Miles
