### ISSUE TITLE
Replace deprecated node-sass dependency with sass

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1579]
**Description:**
_Provide a brief background and justification for this issue_

[This dependabot PR](https://github.com/raft-tech/TANF-app/pull/1578) was originally made to upgrade `node-sass` from `6.0` to `7.0`. Therein we learned that `node-sass` [is deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and should be replaced with `sass`. This issue tracks that work.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `node-sass` is no longer a dependency in `package.json`
- [ ] `sass` is listed in `pacakge.json`
- [ ] SCSS files are compiled as normal
- [ ] All existing functionality is the same
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] `npm uninstall node-sass`
- [x] `npm install sass`
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- https://sass-lang.com/blog/libsass-is-deprecated
- https://stackoverflow.com/questions/70281346/node-js-sass-version-7-0-0-is-incompatible-with-4-0-0-5-0-0-6-0-0
