### ISSUE TITLE
Migrate to new stable faker repo

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1585]
**Description:**
The version of faker that we use was intentionally broken by its creator, to receive further updates we need to use:
https://github.com/faker-js/faker
This ticket is in response to [this dependabot pr](https://github.com/raft-tech/TANF-app/pull/1580)
which if merged would have broken everything. The [original faker](https://github.com/Marak/Faker.js) repo has been co-opted as a activist statement. While we can remain on our current version, ultimately, the community is moving on to the repo linked above. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_
- [ ] The repo uses the new community fork of faker but remains on the same 5.5.3 version
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [ ] Inspect to see if there are any significant changes between our prior 5.5.3 version and the new community 5.5.3 version.
- [ ] Update current faker devDependency to the same version (5.5.3) we are currently using but from the community repo
- [ ] Update all references in the code to refer to new faker dependency
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- It is imperative we do not update our version using the original faker repo.
- The only place we should have to update the code is in `tdrs-frontend/src/mirage.data.js`.
- While this is important to get right, it is not hugely urgent nor time-sensitive.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- The community version does have our same [5.5.3 version](https://www.npmjs.com/package/@faker-js/faker/v/5.5.3) available, so we can make a lateral move before jumping to their 6.0 main version.
- [Current maintainers for fakerjs](https://fakerjs.dev/update.html#who-are-the-current-maintainers)
- [Original Faker repo](https://github.com/Marak/Faker.js)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- [What really happened to Aaron Schwarts?](https://www.rollingstone.com/culture/culture-news/the-brilliant-life-and-tragic-death-of-aaron-swartz-177191/)

**Comment by stevenino** [comment]
Closed as not required per backlog refinement on 9/27/22
