### ISSUE TITLE
Sitemap Testing for Grantees

### ISSUE THREAD

**Issue by sreedevip** [raft-tech/TANF-app#1591]
**AC**
- [ ] Information Architecture (IA) of the TDP website is captured in a tree-test on Google Forms and includes current and future pages of TDP
- [ ] 5-15 grantee participants have taken the test
- [ ] Results have been analyzed and will be documented in a research synthesis document
- [ ] Changes have been reflected in the Sitemap [536](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/536)

**Tasks**

- [ ] Create a tree-test using Google Forms to test the Information Architecture (IA) of TDP that includes both existing and future pages from the [Sitemap 536](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/536)
- [ ] Administer an unmoderated test among 5-15 grantees, 
- [ ] Analyze the results of the test to determine the usability of TDP website IA and document the efficacy of Google Forms as an alternative to Optimal Workshop
- [ ] Create follow-on tickets for Research Synthesis, Live Comms update and Project Impact workshop 
- [ ] Refine and Unblock HTML Sitemap (#1385)

DoD
- [ ] Information Architecture has been tested with grantees, potential changes to IA documented and follow-on tickets created
- [ ] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
follow-on tickets have been created already - #1592 synthesis  &# 1593 project impact.

**Comment by reitermb** [comment]
Demoed by @reitermb on 3/15/2022
