### ISSUE TITLE
Tree Test (Sitemap Survey) Research Synthesis

### ISSUE THREAD

**Issue by sreedevip** [raft-tech/TANF-app#1592]
**Description**
This is the synthesis document that captures the results of sitemap testing with OFA and grantees.

**AC**

- [x] PR has been opened to raft-tech
- [x] Synthesis doc reflects team practices documented in the [Design Guide](https://github.com/HHS/TANF-app/blob/main/docs/Design/Design-Guide.md#code-docs)
- [x] Synthesis doc contains sections over viewing who we talked to, what we did, what we tested, what we learned, and what's next.

**Tasks**
- [x] Draft the results and findings of tree-tests (sitemap surveys)in a hackmd
- [x] Document how results impact the project and influence potential changes to the Sitemap
- [x] Open a PR for the reviewed synthesis

**Documentation**
- [Hack-md Draft](https://hackmd.io/@_1LS3pAARp6wGUAvDgp7UA/HyUGcUReq)

**DoD**

 - [x] PR is opened to raft tech
 - [x] Hackmd draft exists and has been shared with reviewers
 - [x] @lfrohlich has reviewed and signed off

**Comment by lfrohlich** [comment]
@reitermb please add the hack.md link to the description when you get a chance. thanks

**Comment by lfrohlich** [comment]
I added comments to the hack.md @reitermb @sreedevip. it does seem like the project impact abruptly ends-- is there any more to say there?
