### ISSUE TITLE
Change domain/name

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1596]
**Description:**
Dev side of #1595 work to shift terminology away from "live comms" term. We are wanting to shift from "live-comms.app.cloud.gov" to "tdp-project-updates.app.cloud.gov".

**Acceptance Criteria:** 
- [ ] Domain/route is changed to reflect #1595 recommendation (e.g. `tdp-project.-updates.app.cloud.gov`)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Delete current route
- [ ] Take down current app
- [ ] Make change to circle CI config
- [ ] Redeploy
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
A change to CI might require follow-on hotfixes due to differences in the normal dev review flow.

**Supporting Documentation:**

**Comment by reitermb** [comment]
Demoed by @reitermb on 3/1/2022
