### ISSUE TITLE
As a TDP team member, I want a refined Release 3

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#1602]
**Description**
As we are nearing completion of release 1 it is a good time to better refine release 3 in the [product roadmap](https://app.mural.co/t/raft2792/m/raft2792/1629476801275/0f2773589c30764b9f53740adbc5706074ac52a6?sender=laurenfrohlich3146). 

**Acceptance Criteria**

- [ ] Roadmap is refined and presented to team for feedback
- [ ] Risks are documented in the risk register
- [ ] Minor releases have tentative timelines

**Tasks**
- [x] Map epics to product roadmap
- [ ] Order epics and group them into minor releases
- [ ] Identify dependencies and potential blockers
- [ ] Identify potential risks 
- [ ] Identify outstanding research questions and incorporate into [research roadmap](https://app.mural.co/invitation/mural/raft2792/1627058877512?sender=laurenfrohlich3146&key=f1a9b8ba-5529-414b-8206-3395c809cda0)
- [ ] Update roadmap doc if necessary 
- [x] Discuss in cross-functional sync 
- [ ] Identify outstanding tickets to complete each epic and document status

**Definition of Done**
All team members have a clear understanding of the work that is expected to be done during Release 3. Roadmap is refined and has clear epics/issues defined under Release 3.

**Comment by ADPennington** [comment]
Let's start task 2 brainstorming at cross-functional sync tmor 2/25 @valcollignon @abottoms-coder @reitermb

**Comment by stevenino** [comment]
No longer required per product sync on 5/6
