### ISSUE TITLE
As a TDP user I want a list of prior submissions for the selected quarter/STT

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1609]
**Description:**
_Provide a brief background and justification for this issue_
This is for release 2 (pre parsing submission history), would be used by both Grantee Data Analysts and OFA users (anyone who can see the data files tab).
As a TDP user I want to see a list of prior submissions for the selected quarter/STT.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Submission history tab displays a table of files for all sections matching Figma specs
- [ ] [USWDS Segmented button group](https://designsystem.digital.gov/components/button-group/#segmented-button-group) is utilized.
- [ ] Section title ("Section [x] - [Section name]" should be implemented with a custom styled table caption as mentioned in Figma implementation notes
- [ ] Filename, timestamp, author are visible as columns.
- [ ] Columns have alternating background colors to break these rows up visually
- [ ] Tables are paginated for submissions lists over 5 records
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement button group
- [ ] Create new submission history tables
- [ ] Add pagination to tables
- [ ] Implement alternating background colors for rows
- [ ] Populate tables with relevant file metadata
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
![image](https://user-images.githubusercontent.com/28515874/153052114-5a403f25-a7e9-4ff3-acfb-87dc496561d0.png)
- [Figma link](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?t=a4NHkaguYUIPL7UB-1) - 
- [Segmented button group](https://designsystem.digital.gov/components/button-group/#segmented-button-group)
- [Pagination component](https://designsystem.digital.gov/components/pagination/)
- [HTML prototype for v3.x (parsing dependent)](https://reitermb.github.io/HTML-Table-example/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Do we want to display an "author" or "submitted by" field?
   - Yes
- As we move forward what will regional staff users have access to (if anything) under "Data Files". Part of the ongoing discussion of research insight around the usefulness of Grantees/Federal staff having the same view of the same data.
- Might there be a need in submission volume for API/backend work to support pagination?

**Comment by lilybl1** [comment]
@reitermb @ttran-hub My initial a11y review for this ticket included the following findings when using both Chrome and Safari with VoiceOver for MacOS turned on:
1. Submission History (no data available)The up/down arrows are now working and reading the text only sections
2. Submission History (with data) It does read the word "Previous" because I have to tab over it
3. Submission History (with data) When tabbing to the word "Next" it actually reads aloud the word "Previous" instead of "Next" - looks like when you inspect the aria-label is set to "Previous page= disabled" might be the reason it is causing this issue

Here's what I tested:
- Role: As a Data Analyst... 
- Be able to view the Submission History tab when there were previously submitted data files
- Clicking the File Name resulted in a download of the data file
- Resubmitting data files are captured in the table as well
- When there is no data submitted in the section, the label “No data available” is listed
- Pagination
- Tab from top to bottom
- Full screen vs resized screen resolution

I was not able to test the role of OFA Admin as I don't have that setting.

**Comment by reitermb** [comment]
@jtimpe 

Final raft a11y review after raft:qasp sync-up: 
- As @lilybl1 identified, the Next button in the paginator has the aria-label from the Previous button resulting in an incorrect screenreader readout, sounds like that's already on your hitlist @jtimpe 
- A similar paginator issue is that all page buttons have the ```aria-current="page"``` attribute. Only the one currently being viewed should have that as it's what identifies to the screenreader which one is currently selected. 
- We should also add aria-current properties to the appropriate states of the button group control that lets the user switch between current submission and submission history as that's currently missing context
- The section labels (e.g. "Section 1 Active Case Data") should be marked up as ```<caption>``` elements _within_ their associated tables rather than existing outside the table as ```<label>``` elements. Might need a style override to maintain current styling.

cc: @ttran-hub @ADPennington
