### ISSUE TITLE
As a user, I want information about the acceptance of my data and a link to the error report for each version

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1610]
**Description:**
_Provide a brief background and justification for this issue_
This is for Release 3 (post parsing submission history)
For the next iteration of these tables, we need to provide the users new columns: acceptance status and error report links.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Users can see a graphic acceptance status per Figma spec
- [ ] Table retains USWDS compliance and form
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Creation of new columns: "Acceptance Status"
- [x] Creation of icons for acceptance status
- [x] Populate acceptance status column from metadata of the respective filename
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

![image](https://user-images.githubusercontent.com/28515874/154102704-21cf2dfc-3c72-4e9b-8936-70b2d6c6c405.png)

- [Figma mockup](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=6576%3A49872)
- [User story from research](https://hackmd.io/xaYQjwFmRpOIonSM1cMRNA#Validated-amp-Dev-Ready-Stories)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by stevenino** [comment]
Blocked by backend story.

**Comment by jtimpe** [comment]
@Smithh-Co 

Update as of 7/17

I'm still reviewing #2485  and #2612 - this story is still blocked by the #2612 but i will begin a draft implementation pulling from that branch.

**Comment by jtimpe** [comment]
7/18 update @Smithh-Co 

I'm reviewing #2612 still - i had to incorporate eric's fix from #2607 to be able to run locally. As part of my review I will look at changes required for 1610.2 and make a draft pr.

**Comment by jtimpe** [comment]
7/19 update @Smithh-Co 

Post-kickoff review of #2612 looks good so far, still doing some testing but I have a draft of the changes needed to finish 1610 locally. I will finish my review then get a PR published.

**Comment by jtimpe** [comment]
7/20 update @Smithh-Co 

Created a PR for part 2, based on 1613. i think I need to go add some frontend tests so i will move it into raft-review once I've done so. #2612 will have my approval once a couple comments are resolved.

**Comment by jtimpe** [comment]
7/24 update @Smithh-Co 

Got the tests updated and PR moved into raft-review - it's still dependent on 1613 which will have my approval pending a few discussion items.
