### ISSUE TITLE
As a user, I want to see detailed metadata for each file version.

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1612]
**Description:**
_Provide a brief background and justification for this issue_
This is for Release 3 (post parsing submission history)

Taking case information

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Case data populates table per Figma spec
- [ ] For files with "rejected" or equivalent status, cells show "N/A" and have custom styling
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement "Cases" column with sub-tables within a given cell
- [ ] Implement sub-tables to follow spec with four columns: "Month", "Accepted", "Rejected, Total" columns
- [ ] Populate cells with data from parsing output
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

![image](https://github.com/raft-tech/TANF-app/assets/28515874/6832d023-bd22-4e55-bf6d-b2fedfbabffc)

- [HTML mockup](https://reitermb.github.io/HTML-Table-example/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Do we want subtables to also have alternating background rows?
   - Yes, default uswds striping class behavior
- Do we want to simplify the table header structure? e.g "Cases accepted" "Cases rejected" "total cases"

**Comment by reitermb** [comment]
Adding some a11y notes: 

These two resources should help us implement the complex elements of the table (the months broken down as child-rows of each top-level row):
[Column groups](https://www.w3.org/WAI/tutorials/tables/irregular/)
[Aria-Rowspan](https://sumandamera.com/aria-rowspanproperty/)

**Comment by jtimpe** [comment]
7/24 update @Smithh-Co 

Got a PR pushed up with the changes - it uses #2622 as a base branch, which itself is dependent on #2612, so i will get it moved into raft-review as we get closer to approval on the prereqs.

**Comment by jtimpe** [comment]
7/26 update @Smithh-Co 

Just waiting on the final word to come out of the case-aggregates/columns discussions. Otherwise have put a little more work into styling the `N/A` columns and have added a few unit tests which I will push along with the column changes when that is ready.

**Comment by ADPennington** [comment]
@jtimpe @reitermb minor change to the statuses for this ticket:

in scenarios where the records unable to process > 0, the status should be "partially accepted with errors" since there are records in the file that couldnt be parsed. Does this sound okay? 

also can we get the mockup picture updated in this ticket?

**Comment by reitermb** [comment]
> @jtimpe @reitermb minor change to the statuses for this ticket:
> 
> in scenarios where the records unable to process > 0, the status should be "partially accepted with errors" since there are records in the file that couldnt be parsed. Does this sound okay?
> 
> also can we get the mockup picture updated in this ticket?

Updated!

**Comment by ADPennington** [comment]
> > @jtimpe @reitermb minor change to the statuses for this ticket:
> > in scenarios where the records unable to process > 0, the status should be "partially accepted with errors" since there are records in the file that couldnt be parsed. Does this sound okay?
> > also can we get the mockup picture updated in this ticket?
> 
> Updated!

@reitermb i think partially accepted with errors only applies the following scenario: 
![1612p1](https://github.com/raft-tech/TANF-app/assets/63075587/901ad6c5-bb61-40f6-838c-219594ae4198)

**Comment by reitermb** [comment]
> > > @jtimpe @reitermb minor change to the statuses for this ticket:
> > > in scenarios where the records unable to process > 0, the status should be "partially accepted with errors" since there are records in the file that couldnt be parsed. Does this sound okay?
> > > also can we get the mockup picture updated in this ticket?
> > 
> > 
> > Updated!
> 
> @reitermb i think partially accepted with errors only applies the following scenario: ![1612p1](https://user-images.githubusercontent.com/63075587/257353097-901ad6c5-bb61-40f6-838c-219594ae4198.PNG)

Ahh I see—I've updated the mockup accordingly but this might be something we should test/play with a bit more to see whether the delta between "Accepted..." and "Partially Accepted" is as noticeable as we'd like it to be for users.
