### ISSUE TITLE
As a developer, I need parsed file metadata (TANF Section 1)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1613]
**Description:**
_Provide a brief background and justification for this issue_
As required by tickets #1612 and #1610, we need the frontend to display specific datum for the file in question in the submission history.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Backend has API endpoint for parsed file metadata and aggregate data
- [x] Frontend has access to "month, accepted, rejected, total"
- [x] Frontend has access to file submission status
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Implement model(s) about parsed file object with fields from spec and acceptance criteria
- [x] Implement API endpoint which can provide data about parsed file given a file identifier
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 
- Presumably, this will invoke a model query where this data is saved so that it is not calculated at runtime every reload?

**Comment by andrew-jameson** [comment]
Got branch passing on unit tests and linters and cleaned up .2 PR with testing steps and did a brief internal demo during office hours of functionality. Also addressed 1613.1 PR comments. 

Kudos to @jtimpe for the assist on rebuilding frontend to get nginx cfgs copied over to resolve local login 404.

**Comment by andrew-jameson** [comment]
Resolved merge conflicts on .2 PR and presented it during office hours and have a number of todo's now to investigate.

**Comment by andrew-jameson** [comment]
Fixing up the various todos from PR feedback. Can't consolidate migrations unfortunately, also, looks like these branches also suffer from the migration timeout in #2598 so will dive deeper and hopefully resolve given the dependencies here of other tickets like #1610
