### ISSUE TITLE
SPIKE: As tech lead, I want automated entity relationship diagrams

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1614]
**Description:**
_Provide a brief background and justification for this issue_
The current [ERD](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/Database/tdp-erd.png) is wildly out of date and will continue to be so. To ensure accuracy and prevent manual rework, we should automate this documentation task. This is a follow on from #1526 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] We have a human-readable Entity Relationship Diagram generated automatically.
- [ ] ERD leverages CircleCI pipeline run on a periodic basis (on merge to `raft-tdp-main` or quarterly).
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] #1733
- [ ] Implement POC with ERD tool(s) to ascertain their feasibility
- [ ] Architect CircleCI Pipeline to run this ERD tool
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- We do not want these stored on every run of every branch of our repo -- it would be unnecessary duplication. Running on merges to main or simply monthly/quarter for the `raft-tdp-main` branch is sufficient.
- This diagram is required by OCIO for continued ATO issuance.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Django tool graphviz](https://django-extensions.readthedocs.io/en/latest/graph_models.html)
- [More graphviz](https://wadewilliams.com/software/generating-erd-for-django-applications/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- What other tools exist for this functionality?
- How do we best reference/commit/store these diagrams?
   - It should be stored in Django admin console like the OWASP scans
- On what interval do we want these generated?

**Comment by valcollignon** [comment]
Next steps are to figure out which tools to use for the automation and what the lift will be.
Per backlog refinement 2.8.22
CC: @abottoms-coder @ADPennington
