### ISSUE TITLE
[SPIKE] As tech lead, I need to know the real-time branches deployed in Cloud.gov spaces

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1620]
**Description:**
_Provide a brief background and justification for this issue_
During some troubleshooting, we were uncertain what the current code deployed was in a Cloud.gov space. To resolve this in the future, I'd like to have a live representation of what branches are present in each space in Cloud.gov. I am open to solutions or where this would be present.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] We have a live representation or table showing the branch/commit and the Cloud.gov space.
- [x] This table is accessible via a well-known link that is documented.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [x] Automate deployment pipeline(s) to update a widget similar to Codecov
- [x] Ensure widget reflects a human-readable branch display
- [x] Evaluate solutions
- [ ] TBD
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Are badges possible like Codecov?
- Can we store these as like an environment variable in Cloud.gov and then query it via CF CLI?
- How do we get this updated when applying github labels?

**Comment by stevenino** [comment]
@andrew-jameson bring this up at bluesky

**Comment by robgendron** [comment]
Update: Still needed.

**Comment by robgendron** [comment]
Aiming to have PR by EOW (Jul 12)

**Comment by robgendron** [comment]
Update: Testing deployments
Next: PR next day or two

**Comment by robgendron** [comment]
Update: Discussed at office hours
Next: Proceeded with shell, PR coming soon

**Comment by robgendron** [comment]
Update: Drafting PR

**Comment by andrew-jameson** [comment]
Documentation sources:
[Verbose Shields.io documentation](https://shields.io/badges/endpoint-badge)
[Their github](https://github.com/badges/shields)
[Dynamic github info](https://github.com/marketplace/actions/dynamic-badges)
