### ISSUE TITLE
As tech lead, I want CircleCI pipelines to catch migration and/or deployment failures

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1623]
**Description:**
_Provide a brief background and justification for this issue_
While reviewing #1387 , we ran into a deployment which failed silently. Please investigate branch `feat/1387-deployment-error-handling`.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] A deployment with a failed migration fails the CircleCI pipeline
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Investigate low hanging fruit error handling for migration issues within the CircleCI pipeline
- [ ] Investigate low hanging fruit error handling for deployment issues within the CircleCI pipeline
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

Cloud.gov log of sandbox deployment proving migration did not run correctly (failed silently):
```
[2022-02-10 17:25:07 +0000] [560] [DEBUG] GET /v1/auth_check
12:25:07.271: [APP/PROC/WEB.0] ERROR Internal Server Error: /v1/auth_check
12:25:07.271: [APP/PROC/WEB.0] Traceback (most recent call last):
12:25:07.271: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
12:25:07.271: [APP/PROC/WEB.0]     return self.cursor.execute(sql, params)
12:25:07.271: [APP/PROC/WEB.0] psycopg2.errors.UndefinedColumn: column users_user.location_id does not exist
12:25:07.271: [APP/PROC/WEB.0] LINE 1: ...", "users_user"."date_joined", "users_user"."id", "users_use...
12:25:07.271: [APP/PROC/WEB.0]                                                              ^
12:25:07.271: [APP/PROC/WEB.0] The above exception was the direct cause of the following exception:
12:25:07.271: [APP/PROC/WEB.0] Traceback (most recent call last):
```

Some discussion from @riatzukiza : 
```
It did it last time because an assumption I made that held true locally did not hold true in staging, there were users currently in existance which did not follow the rules we are trying to enforce here.

[12:33 PM](https://mattermost.goraft.tech/goraft/pl/8mjm5iq6ibb6fftfktkk6a8aqa)

Maybe there is some way we can make the deployment fail if the migrations fail to apply?

would not want this sort of thing to happen in a production situation.

[...omitted...]

Could modify the deploy script for that. 

	
adpennington
GUEST
[1:08 PM]
to report out whats in here, for example? cf logs tdp-backend-sandbox --recent

	
Aaron Beavers
[1:08 PM]
yea, to run that command in the deployscript if theres a non 0 exit code.

	
adpennington
GUEST
[1:11 PM]
id be curious if there's ever a scenario where it could return something that we wouldnt want to show in ci. 

	
Aaron Beavers
[1:12 PM]
CI censors a lot of stuff that looks like it is sensitive, but would want to keep an eye on it to see if there are edge cases.
```

- And the deployment in question is [here](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/6931/workflows/831f3cf8-3ffa-4639-a42e-f576a8733223/jobs/16343).
**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by abottoms-coder** [comment]
Relates to #831 -- we should have team distro notifications upon errors in cloud.gov logs.

**Comment by riatzukiza** [comment]
This line from 1387 is part of this: https://github.com/raft-tech/TANF-app/pull/1572/files#diff-bb5e02a4c17948be30f0aff52e12ef2aebf527ca2e1d11760781b6c718e80021R3

**Comment by andrew-jameson** [comment]
Working with @raftmsohani, we might be able to rollback using this combo:

```cf revisions {app-name}```

Then use the last successful guid, we can populate this reversion command:
```
cf curl v3/deployments \        

-X POST \

-d '{

  "revision": {

    "guid": "{last stable guid from list above}"

  },

  "relationships": {

    "app": {

      "data": {

        "guid": "{current app guid}"

      }

    }

  }

}'```

**Comment by andrew-jameson** [comment]
#2729 covers migration failure but I see no checks for the status after the deployment itself. The `cf push` might execute but the app can fail or we might run into RAM limit or a "App staging" message so we've got some meat here to investigate.

**Comment by reitermb** [comment]
1-2 pts remaining

**Comment by andrew-jameson** [comment]
Existing pipeline covers the failure use cases I had thought to catch. I was previously mistaken and this is no longer needed.
