### ISSUE TITLE
Configure ACF AMS service in ACF and TDP prod environments

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1627]
### Description

As noted [here](https://github.com/raft-tech/TANF-app/issues/1552#issuecomment-1021518560), a process is required when we are ready for ACF AMS authentication service to work in the ACF and TDP prod environments. The change request template is saved [here](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/Authentication%20%26%20Authorization/ACF%20AMS%20docs/OCIO%20OPERATIONS%20REQUEST%20TEMPLATES.docx?d=w5332585c1ecf49a4aeda17674f687154&csf=1&web=1&e=uiUsHo) and is estimated to take 1-2 weeks to obtain approval. It will involve a presentation to ACF OCIO team. 

### ACs 
- [x] Environment variable key value pairs are updated for prod backend (`AMS_CLIENT_ID`,`AMS_CLIENT_SECRET`,`AMS_CONFIGURATION_ENDPOINT`)
- [x]  `ACF user` authenticates  in TDP prod successfully via ACF AMS
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary
 
### Tasks
 - [x] _submit change request form_
 - [x] _receive required documentation (e.g. client id, key, and endpoint) from ACF AMS Ops team_
 - [x] _update EVs in cloud.gov prod space_
 - [x] _re-stage prod backend app_

### Supporting documentation

- [steps followed to configure ACF AMS to work in TDP staging](https://github.com/raft-tech/TANF-app/issues/1552#issuecomment-1023609591)
 
 ---
_Blockers_:
- we need a TDP domain (#726)
- we need a prod environment (#914)
- we need to deploy to prod (#895)

**Comment by ADPennington** [comment]
refined in 2/16 dev sync cc: @valcollignon @abottoms-coder

**Comment by ADPennington** [comment]
change request form submitted to ACF OCIO on 5/5.

**Comment by lfrohlich** [comment]
From Selam Teferi (OCIO) 5/5/22:   I am the new change manager letting you know CR#  CHG0031574 for ACF AMS Integration in TDP Production has been created. Is there an exact date and time I can schedule the deployment? 
Alex asked: Will we need to be available on standby when you deploy? And should we schedule a time to exchange information like the TDP production URLs and client ID and keys?

**Comment by stevenino** [comment]
Expected to be completed by 5/18/22

**Comment by ADPennington** [comment]
@andrew-jameson and I will meet with ACF AMS Ops on 5/16 at 10:30a EST to exchange configuration information and test authentication in `tanf-prod`. Confirmed with Ops team that successful testing during this pairing session is sufficient to close this issue. cc: @lfrohlich @stevenino

**Comment by andrew-jameson** [comment]
Just wanted to add this before it was lost. During integration with the AMS team, our lower environments work correctly while prod seems to have the below session issue:
![image](https://user-images.githubusercontent.com/84722778/168662608-9147256f-1f6d-4f66-8b1d-4a82345e5114.png)

**Comment by lfrohlich** [comment]
Ticket update: ACF OCIO Service Desk Change request # CHG0031574 entered the Scheduled state.  
 
System Name: Red Hat SSO 
Planned start date: 2022-05-16 10:30:00 EDT
Planned end date: 2022-05-16 11:30:00 EDT

**Comment by lfrohlich** [comment]
ACF OCIO Service Desk Change request # CHG0031574 entered the Execution state.  
System Name: Red Hat SSO 
Planned start date: 2022-05-16 10:30:00 EDT
Planned end date: 2022-05-16 11:30:00 EDT

**Comment by ADPennington** [comment]
Actual start date: 2022-05-16 10:30:00 EDT
Actual end date: 2022-05-16 11:30:00 EDT
Complete Code: Unsuccessful
Complete Notes: SSO Client configured, however the TANF application is not in a state to conduct a successful validation. Client configuration in RH-SSO will remain and TANF will reach out once they are able to successfully validate

**Comment by ADPennington** [comment]
https://github.com/raft-tech/TANF-app/issues/1778#issuecomment-1151121222

**Comment by ADPennington** [comment]
Closing this ticket since authentication via ACF AMS in TDP prod environment is functional as of 7/11/22 with a **non-acf domain for backend route**. authentication steps below. cc: @lfrohlich @ttran-hub @stevenino 

1. navigate to frontend landing page and click `Sign in with ACF AMS for ACF staff` button
![1627p1](https://user-images.githubusercontent.com/63075587/178513674-2c17caae-d03f-4429-8d4c-84ab6ad93619.PNG)

2. Review and agree to privacy policy
![1627p2](https://user-images.githubusercontent.com/63075587/178513713-87b274fb-bbf5-4f22-ab51-69c8e789889b.PNG)

3. Enter PIN
![1627p3](https://user-images.githubusercontent.com/63075587/178513789-cca54187-1a56-418c-9d60-6a35dd67526d.PNG)

4. If PIN is correct, the ACF user is redirected to tanfdata.acf.hhs.gov/home where they will either see a request form (if theyve not yet requested access) or a list of permissions associated with their account (if access has been approved). 
_request form view_
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/63075587/178517876-d0a09fdd-f1ee-4835-9613-296d6fe31123.png)

_list of permissions view_
![1627p4](https://user-images.githubusercontent.com/63075587/178517939-a2e2968e-20d5-4b40-b9eb-5364157630aa.PNG)

**Comment by ADPennington** [comment]
8/1/2022 -- submitted request to OCIO to change redirect URLs to URLs that include the ACF backend routes, per #1945. re-opening to track completion of this change request.

**Comment by ADPennington** [comment]
8/2/2022. Successfully updated and tested the prod URLs for ACF AMS. Closing as completed.
