### ISSUE TITLE
Fix Pa11y artifact capture for /profile route

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#1629]
**Description:**

[As of 1495](https://github.com/raft-tech/TANF-app/pull/1571) some pa11y artifacts that are being uploaded do not correctly represent the state of the app, namely the `/profile` route, and we need to figure out a way to configure pa11y such that these new frontend states can be scanned.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] pa11y artifacts for `/profile` shows the actual profile page
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate why screenshot is capturing home page vs profile page (e.g. replicate current issue via  `REACT_APP_PA11Y_TEST` locally)
- [ ] meet with `dev` team to discuss issue
- [ ] _refine ticket or open new with implementation strategy agreed upon among dev team_
- [ ] Run Testing Checklist and confirm all tests pass

## Supporting documentation

Current artifact
![1629p2](https://user-images.githubusercontent.com/63075587/154308048-d51b4494-b041-407c-8822-64c5f7451530.PNG)

Correct artifact 
![1629p1](https://user-images.githubusercontent.com/63075587/154307997-c4cd53e1-5b8d-4da5-8664-aa4687099948.PNG)

**Comment by riatzukiza** [comment]
Its likely this has to do with mirage mocks.

**Comment by ADPennington** [comment]
per dev sync 2/16: this ticket was revised to be a spike to investigate the root cause of this issue and discuss implementation strategy. cc: @valcollignon @abottoms-coder

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

@robgendron @andrew-jameson im not sure because currently no pa11y artifacts are being stored as artifacts in circleci to confirm what is being tested. see the latest build and test for frontend [here](https://app.circleci.com/pipelines/github/HHS/TANF-app/1144/workflows/4467f688-a6e0-4a83-b560-fa4125f81cc4/jobs/2587/artifacts)

![pa11y](https://github.com/raft-tech/TANF-app/assets/63075587/dadd583b-63bd-4420-9526-f11a8874dae3)

**Comment by lhuxraft** [comment]
Need to investigate if this is still a problem
