### ISSUE TITLE
Database needs full backups done periodicly

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1631]
**Description:**

Its good practice for many reasons to keep some kind of back up. The servers could catch on fire, we could have some development issue that breaks the system, what ever it is. Having periodic backups of known good database states would make certain development errors easier to recover from, and prevent data loss in a production environment.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] At some agreed upon interval, a snapshot of the rds state is taken
- [ ] The rds state is stored in a file in s3 as an sql dump file
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by abottoms-coder** [comment]
> Received reply from [support@cloud.gov](mailto:support@cloud.gov). They do not currently have a secure way for us to self-service this option. The only option would be a script to raw-dump the database contents and then use postgre's restore function.
> 
> However, he did mention he is working on a solution for us to do just this and it might be ready in as little as a week. I have inquired about more details on this.
> 
> @raftmsohani Please do try to begin scripting for the pgdump steps and storing those in one of our s3 locations per the below section. https://cloud.gov/docs/services/relational-database/#access-the-data-in-the-database

Another update on support's solution: they are working on an open-source repo to solve this problem. He will provide me a link to the repo once it is available but this would be alpha/beta software where we would be guinea pigs. The best option, despite the rework, is to pursue both solutions. Have our in-house pgdump to s3/pgrestore from s3 scripting and then to work with cloud.gov support on maturing/using this new repo. The reason being is we don't know what the true timeline would be on getting that solution prod-ready so once I have this repo link I will have a follow-on ticket to try to collaborate and improve cloud.gov in this area.
