### ISSUE TITLE
[Design] fTANF Partial to Complete resubmission guide

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1637]
**Description:**
This is an Onboarding related follow-on from resubmission epic (#1269) research findings. This will likely be most effectively tested as part of the pilot program; with a grantee using fTANF/submitting partial data currently. The final format of this guide will be determined by #1693 (e.g. PDF vs knowledge base page).

**Related User Stories:**
- As a grantee user I want a guide to assist me in changing my workflow in fTANF so as to export complete data revisions rather than partial ones.
- As a grantee user I want to understand why this change is happening
- As a grantee user I want to know how to get help if I use a system other than fTANF

**AC:**
- [ ] Guide conveys all steps needed to change fTANF exports from partial to full
- [ ] Relevant user stories are documented.
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines] and accessibility implementation notes are documented(https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

**Tasks:**
- [x] Draft guide content in hack.md 
- [x] Review guide accuracy with DIGIT
   - [ ] Add/revise content as needed

**Supporting Documentation:**
- Hack.md with drafted guide: https://hackmd.io/@mreiter/ryyoEcyE5

**Comment by reitermb** [comment]
Estimate ~a 3 point carryover for this as of 3/29/2022

**Comment by lfrohlich** [comment]
@ADPennington see the hack.md for review

**Comment by stevenino** [comment]
@reitermb Look at comments in the HackMD

**Comment by lfrohlich** [comment]
@reitermb I added a few comments as well. I think these should be addressed before we show to DIGIT. Moving back to in progress

**Comment by lfrohlich** [comment]
per @reitermb 4/22/22: All of it should be ready for further review here: https://hackmd.io/@mreiter/ryyoEcyE5 Images and language tweaks

**Comment by lfrohlich** [comment]
DIGIT has reviewed. @reitermb please see additional comments in the hack.md

**Comment by lfrohlich** [comment]
Updates: removed 3rd goal; added "what is ftANF.exe"; simplified ask for update indicator and including header example; revised final section. @reitermb does that cover it?

**Comment by lfrohlich** [comment]
@stevenino  re: scope, we are focused on  AC#1 Guide conveys all steps needed to change fTANF exports from partial to full. Based on our discussion, initial steps that Alex walked through with UX are missing from the guide. This is not about training people who haven't used FTANF before; it is about documenting the steps that are needed to make the change.

**Comment by ADPennington** [comment]
@reitermb @lfrohlich @stevenino I made some updates throughout the [hackmd](https://hackmd.io/v5UKdNBEQuu1oEV2nnu74A?both) and left a few comments:

- added some more description and placeholders for screenshots 
- suggest defining what "complete data" is
- also think we need to mention somewhere what the process is for resubmitting sections 3 and 4 if the stt is using executables.  i left a comment about the process. in brief, step 2 is irrelevant. this seems worth mentioning because the screenshots show the sections.

**Comment by lfrohlich** [comment]
@ADPennington this is back in QASP

**Comment by ADPennington** [comment]
@reitermb this looks good! I made minor edits for clarity. Some final notes and suggestions:

- The title of the guide seems a bit unclear. 
- I also think the purpose of the guide is presented in a weird spot...maybe consider moving it toward the beginning of the document or at least try leading with this statement in the FTANF section.

**Comment by ADPennington** [comment]
> cc @lfrohlich @ADPennington Updates made!

LGTM 👍🏾
