### ISSUE TITLE
As an ACF user, I should not be required to select an STT on the request form

### ISSUE THREAD

**Issue by valcollignon** [raft-tech/TANF-app#1640]
**Description:**
During testing for #1387, it was discovered that the request form forces the requestor to select an STT. This is only relevant for users in the states, territories, and tribes. This implicates that a system administrator will have to de-select location type when assigning permissions to non-STT users (e.g. OFA regional staff).

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] ACF users should **not** see STT option on request form
- [ ] Non-ACF users' form should remain unchanged
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] For the request form, optionally display the STT field based on user email address
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- Request form could vary based on the authentication method or email address. For example, if an ACF user, the field is region; else, STT.

**Comment by reitermb** [comment]
👍 to "Request form could vary based on the authentication method. For example, if an ACF user, the field is region; else, STT." or some similar variation. We should make sure that the STT field _is_ required for grantees. 

Just to throw another idea out there in case it's easier, maybe this could be keyed off of email address instead of or in addition to auth method since ACF emails should be consistently recognizable.

**Comment by ADPennington** [comment]
noting for future reference--,once this ticket is addressed:

-  `sys admins` will need to confirm asynchronously  which region needs to be designated for someone that is assigned to the `OFA Regional Staff` permissions group
- `sys admins` will not be able to assign a meaningful region to an ACF user that is in any other federal permissions group (i.e. `OFA Admin`, `OFA Data Analyst`) because these users should have access to data for all regions. We need a "central office" region to capture this intention.
