### ISSUE TITLE
[Incident Response Drill] As a sys admin, I need to know how to regain control of my compromised account

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1642]
### Description:

As noted [here](https://github.com/raft-tech/TANF-app/issues/885#issuecomment-1042364716), we will practice how to regain control of a TDP privileged user account that has been compromised and save our incident response plan for this drill in the repo.  This ticket is to track this work. 

### ACs:
- [x] mitigation steps in [hackmd](https://hackmd.io/Yyo_NiIzRp6tqIS-6gLC6w) complete and accurate
- [x] drill conducted
- [x] README is updated, if necessary
- [x] incident response plan (ato version) updated, if necessary

### Tasks:
- [x] finalize drill plan
- [x] conduct drill
- [x] open PR to add drill docs to repo

**Comment by valcollignon** [comment]
@abottoms-coder @ttran-hub @ADPennington and @lfrohlich to review next week per backlog refinement 2.22.22

**Comment by ADPennington** [comment]
@ttran-hub and I met on 3/1 to review the hackmd and go through the list of software installations needed on GFE to carry out the drill. We also discussed our cloud.gov org roles and possible risks associated with that. Hackmd includes these notes/questions for discussion with @lfrohlich. Next steps:

- @ttran-hub will inform once installations on his GFE are completed and cloud.gov credentials have been restored. 
- @ADPennington will schedule drill with @ttran-hub and @lfrohlich.

**Comment by ADPennington** [comment]
3.21.2022:

@ttran-hub and I met today to install CF CLI and go through step 1 of the drill. Standing by for feedback on whether Step 2 of drill can be done successfully from GFE (i.e. hhs windows machine).

**Comment by ttran-hub** [comment]
> 3.21.2022:
> 
> @ttran-hub and I met today to install CF CLI and go through step 1 of the drill. Standing by for feedback on whether Step 2 of drill can be done successfully from GFE (i.e. hhs windows machine).

Thanks @ADPennington!   
Step 2. FAILED with "Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain"

**Comment by ADPennington** [comment]
> > 3.21.2022:
> > @ttran-hub and I met today to install CF CLI and go through step 1 of the drill. Standing by for feedback on whether Step 2 of drill can be done successfully from GFE (i.e. hhs windows machine).
> 
> Thanks @ADPennington! Step 2. FAILED with "Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [password none], no supported methods remain"

thanks for the update @ttran-hub! I have updated drill Step 2 after some additional testing. We now have Step 2a (for ssh'ing on non-GFE) and Step 2b (for ssh'ing on GFE). Please note:

- We will need to use Step 2b when using GFE. 
- You will need to download `jq` and `cURL` to proceed with Step 2b. Please refer to the links in the hackmd for download. You may need ITIO's help for install. 
- Once installed, please test Step 2b and so on and let us know if you run into any issues.

**Comment by ADPennington** [comment]
@ttran-hub and I met today 3/28 to walk through the abovementioned steps. Notes:

- we confirmed that JQ and CURL are installed
- we had to change his space roles in cloud.gov so that he has proper permissions to access. after doing this, we were able to get through all steps. 
- He will now proceed with trying to assign his own permissions and let us know the results (we ran into some unknown issues with using the passcode generated from `cf ssh-code`).

**Comment by ttran-hub** [comment]
> @ttran-hub and I met today 3/28 to walk through the abovementioned steps. Notes:
> 
> * we confirmed that JQ and CURL are installed
> * we had to change his space roles in cloud.gov so that he has proper permissions to access. after doing this, we were able to get through all steps.
> * He will now proceed with trying to assign his own permissions and let us know the results (we ran into some unknown issues with using the passcode generated from `cf ssh-code`).

Thanks Alex!  restart terminal and successfully assigned OFA Sys. Admin role!

**Comment by ADPennington** [comment]
drill scheduled for 4/4.

**Comment by ADPennington** [comment]
drill completed on 4/4. Notes:

- we added syntax for reactivating a deactivated account
- we will add step in communication protocol to include reaching out to cloud.gov in the scenario where account restoration steps fail (e.g. because evil user also compromised sys admin's cloud.gov account). 
- i will update IRP to reference drill documentation. 

cc: @lfrohlich @ttran-hub
