### ISSUE TITLE
[Design] TDP Homepage UX (V2) 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1643]
**Description:**

**Related User Stories:**

**AC:**
- [ ] Relevant user stories are documented.
- [ ] Dev/Design sync has occurred; resulting tickets documented.
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines] and accessibility implementation notes are documented(https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

**Tasks:**
- [ ]

**Supporting Documentation:**

- Figma

**Comment by reitermb** [comment]
Close in favor of #1653
