### ISSUE TITLE
[SPIKE] Investigate the effort involved in upgrading to django 4

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1647]
**Description:**
When we initially tried updating to Django 4, we had a few things break and we want to find out how deep it might go before committing to any specific effort on it.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] We have a report detailing what is preventing tdrs from working with django 4
- [ ] If more work is required, create an issue for actually upgrading, otherwise just do the upgrade

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] investigate the errors in notes
- [ ] find relavent documentation
- [ ] compile findings into report (probably ADR?)

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- `tdrs-backend-web-1 | django.core.exceptions.ImproperlyConfigured: 'colorfield' not needed since django 4.0, remove it from settings.INSTALLED_APPS.`
- ` tdrs-backend-web-1 | ModuleNotFoundError: No module named 'pytz'`

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

How to point a walk in the shadows of a rabbit hole?

**Comment by valcollignon** [comment]
@abottoms-coder to refine further.

**Comment by riatzukiza** [comment]
`tdrs-backend-web-1          | django.core.exceptions.ImproperlyConfigured: 'colorfield' not needed since django 4.0, remove it from settings.INSTALLED_APPS.`
`tdrs-backend-web-1          | ModuleNotFoundError: No module named 'pytz'`

**Comment by ADPennington** [comment]
discussed on 2/23 dev sync. this is an enhancement to upgrade to django v4. for tdp, this is low priority. still in unrefined state. cc: @abottoms-coder

**Comment by robgendron** [comment]
DUPE - PR #2977 does this.
