### ISSUE TITLE
[Design] V2 Onboarding content

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1653]
**Description:**
Delivers dev-ready designs/content for TDP V2 Onboarding. Companion ticket to #1637

**Recommended Pa11y Actions**
- .

**Related User Stories:**
- .

**AC:**
- [ ] Relevant user stories are documented.
- [ ] Dev/Design sync has occurred; resulting tickets documented.
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines] and accessibility implementation notes are documented(https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

**Tasks:**
- [ ] Draft Figma designs for in-app onboarding
- [ ] Draft hack.md content for extra-app onboarding materials
   - [ ] Refine into final deliverable format (e.g PDF)
- [ ] Add relevant implementation notes
- [ ] Add relevant pa11y actions
- [ ] Review with @lfrohlich @ADPennington 
- [ ] Dev/Design sync

**Supporting Documentation:**

- Figma
- Hack.md

**Comment by reitermb** [comment]
Further refined 3/22/2022

**Comment by reitermb** [comment]
Draft of Data Files onboarding materials here: https://hackmd.io/@mreiter/ByN4skDFq

cc @lfrohlich @ADPennington

**Comment by lfrohlich** [comment]
@reitermb i reviewed and made some comments in the hack.md. Note, I also made some edits within the text (mostly commas and minor word changes)-- i think you're able to see what changes i made but if not let me know and i can comment each one.

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich Ready for QASP review
@reitermb : 
- i resolved comments that I made where it appears that these were addressed. 
- i made minor language edits in-line under steps 1, 3
- i added "transmitted" to "how to retrieve your data" header. also reorganized and simplified the instructions herein. 


let me know if you have any questions about these edits. else, looks good to me.

**Comment by lfrohlich** [comment]
LGTM

**Comment by reitermb** [comment]
All final changes look good to me! I think we're good to close this. (#1693 will update knowledge center pages to reflect these content changes!)

cc @lfrohlich @ADPennington @stevenino

**Comment by stevenino** [comment]
Closed per sprint review on 7/6/22
