### ISSUE TITLE
As a developer, I want to audit and update relevant fields available in DAC to be read-only

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1658]
**Description:**
_Provide a brief background and justification for this issue_
We continue to stumble into fields we want to be read-only in DAC so I am proposing a holistic audit of all fields in DAC.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] The relevant objects are read-only for all user types through Django Admin
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Check every DAC page and determine if field should be read-only.
- [ ] Update permissions on relevant page::field combinations to be read-only in nature.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by abottoms-coder** [comment]
Per backlog refinement and @jorgegonzalez , the implementation follow-on to this ticket should be a light lift and could be implemented in this sprint (42).

**Comment by jorgegonzalez** [comment]
I've updated the AC of this ticket to align with the intent of the linked PR; as a side-note, the task listed " Update permissions on relevant page::field combinations to be read-only in nature." would not have been the correct approach; the PR does not modify user permissions in any way, as that would have implications for the API, but just locks down a set of models such that they cannot be changed through Django Admin.

**Comment by jorgegonzalez** [comment]
A separate but related problem to consider in maybe a follow-on ticket–auditing object *permission* in the app. After the PR for this ticket is merged, the problem of read-only objects in DAC goes away where relevant. But certain users will still be able to modify those objects by forming requests to the API directly. We've done a good job restricting the DataFiles object permissions, but there are other models worth locking down. This isn't a big deal currently, but could pose security issues in production.

Exploring how I can extend the current PR for this ticket to address that

**Comment by abottoms-coder** [comment]
> A separate but related problem to consider in maybe a follow-on ticket–auditing object _permissions_ in the app. After the PR for this ticket is merged, the problem of read-only objects in DAC goes away where relevant. But certain users will still be able to modify some of those objects by forming requests to the API directly. We've done a good job restricting the DataFiles object permissions, but there are other models worth auditing and locking down. This isn't a big deal currently, but could pose security issues in production.
> 
> Exploring how I can extend the current PR for this ticket to address that

Excellent, thank you for taking a look, Jorge! I'll try to get to your PR soon. Good insight on the production op-sec potential.
