### ISSUE TITLE
As a Sys admin, I need to be able to deny requests for access to TDP

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#1679]
**Description:**
System admin needs to be able to deny requests for access to TDP if a requestor is not verified to represent an STT.  

TDP does not yet have functionality to facilitate denying a request for access to the system. Once the user submits the request access form, all they can do is authenticate into the system and access the `Home` and `Profile` tabs on the frontend. This will not change unless at least one of the following fields are changed in their user profile on the backend: `Superuser status`, `Groups`, or `Staff status`. Changing one of these fields will trigger access to the front- or backend. 

This is a prerequisite to #1334 and #1336 notifications. Secondarily related to #1352 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Collapse 'deactivated' and 'access_request' fields into one enum field of various statuses "approved, pending, denied, initial, deactivated"
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Map out state diagram and user flows both for requesting users and acting sysadmin
- [ ] Prepare migrations of user models for creation of new field
- [ ] Have a plan for sunsetting of redundant fields `deactivated` and `access_request`
- [ ] Write and refactor relevant unit tests for new flow(s)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by ADPennington** [comment]
3/16/2022 dev sync:
- what result does user want to see when status is changed? we want to send an email 
- this needs R&D work before dev can refine cc: @reitermb

**Comment by ADPennington** [comment]
marked V3 for now, but let's revisit if we start getting a lot of requests for access from unvetted users.

**Comment by stevenino** [comment]
@ADPennington and @andrew-jameson to discuss path forward at dev sync on 6/1. This and #1334 have to be refined and re-aligned.

**Comment by andrew-jameson** [comment]
> @ADPennington and @andrew-jameson to discuss path forward at dev sync on 6/1. This and #1334 have to be refined and re-aligned.

Updated scope and description on 6/1.

**Comment by lilybl1** [comment]
@reitermb @jtimpe Please review together
