### ISSUE TITLE
As an unapproved grantee user, I want my requested STT in my profile

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1680]
**Description:**
Since #1387 was addressed, when an unapproved grantee  user (i.e. new non-ACF user) submits a new request to TDP by submitting a request form with  their first name, last name, and STT, their profile will have a default STT value of "federal government" until their permissions group is assigned. Instead, we want the requested STT in the profile.  The current behavior for an unapproved _ACF_ user should not change. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Unapproved grantee user has requested STT in profile upon submitting request form
- [ ] Unapproved ACF user has "Federal Government" in profile upon submitting request form
- [ ] Unapproved grantee user profile also displays inferred region upon submitting request form
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Improve Profile page logic to display requested STT for grantee user
- [ ] Create backend endpoint to provide human-readable STT name to frontend if not created
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
- #1387 
- _current profile for an unapproved grantee_
![image](https://user-images.githubusercontent.com/10676925/157481815-f21eb717-4bdb-4c6c-835f-920008f852e1.png)

**Comment by riatzukiza** [comment]
![image](https://user-images.githubusercontent.com/10676925/157481815-f21eb717-4bdb-4c6c-835f-920008f852e1.png)
