### ISSUE TITLE
As tech lead, I need updated version of Django and ipython to resolve known vulnerabilities

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1686]
**Description:**
_Provide a brief background and justification for this issue_
Previously, we merged an updated Pipfile in [this PR](https://github.com/raft-tech/TANF-app/pull/1635) then then had to [revert these](https://github.com/raft-tech/TANF-app/pull/1656) changes as the deployment failed going to staging so I believe there is a buildchain difference between Docker and Buildpacks. Our old branch is still active: `deps/security-vulnerabilities-django-ipython`.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Django and ipython are updated to non-vulnerable versions
- [ ] Code changes must be deployed successfully before this is merge-eligible
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Root cause analysis of failure in Buildpacks
- [ ] Resolution of buildpack errors
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Addresses these security vulnerabilities:
[Infinite Loop in Django (High) ](https://github.com/raft-tech/TANF-app/security/dependabot/36)
[Execution with Unnecessary Privilieges (High)](https://github.com/raft-tech/TANF-app/security/dependabot/15)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by ADPennington** [comment]
3/16/22: 

- decided during dev sync to revisit this ticket after nextgen xms epic (#1153) completed. 
- dependabot security alerts (highs and criticals) will be discussed weekly at dev syncs.

**Comment by abottoms-coder** [comment]
If we can resolve this, I believe this will also address a vulnerability with `Pillow` as we need to bump from 9.0.0 to 9.0.1

**Comment by stevenino** [comment]
Closed as OBE since Django was updated per backlog refinement on 9/14/22
