### ISSUE TITLE
As a system admin, I need a way to be redirected to frontend from DAC

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1690]
**Description:**
When #1668 is merged, we will have an `acf ocio` permissions group that will allow members to:
- have read-only access to owasp and clamav scans in DAC
- have access to the home page (that includes a list permissions the user has in TDP) on the frontend
- have access to their profile page on the frontend

We noticed during tabletop that there isn't an easy way (e.g. a link) for this user to get back to the frontend from DAC. They would have to know the URL and navigate to it. **This is actually true for any user with access to DAC.**

Ideally, a link to the frontend would be accessible from DAC. 

_Priority: low (this is a nice-to-have enhancement for backend UX)_

**Acceptance Criteria:** 
- [ ] Any permissions group with access to backend (e.g. `OFA System Admin` , `ACF OCIO`, etc.) has a redirect link to the frontend from DAC
- [ ] OCIO users must have access to this frontend link
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Testing should be done with regard to the locked-down OCIO group to ensure they can view this link
- [ ] Addition of relative link to frontend application within DAC
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
 - Should there be (option 2) a link available for each app (e.g. user, security, groups, etc.) or (option 1 below) is it possible to add a link next to Django administration? 
![redirect](https://user-images.githubusercontent.com/63075587/158201433-4477720b-f947-4ec6-b01d-a782e30e18e0.PNG)

**Comment by andrew-jameson** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85edcabe9a44751ffac3b4838c21c5a962aeba9f/Screenshot%202024-06-11%20at%2011.43.45%E2%80%AFAM.png" alt="Screenshot 2024-06-11 at 11.43.45 AM.png" />


Clicking the "View site" on the far right will redirect to the frontend. Thanks for the call out @jtimpe 
cc @ADPennington @ttran-hub
