### ISSUE TITLE
As a grantee Pilot user I want to know how to get started in TDP

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1691]
**Description**
Delivers a welcome email for the TDP pilot program. This serves as the first formal step of onboarding–a jumping off point that will prompt the user about what to expect in TDP, how to create an account, and other first steps. 

Complements #1653 by delivering getting-started specific content. This content should get a user up and running in TDP, the rest of the onboarding content should take it from there.

**AC:** 
- [x] Email has a clear sequence of next steps for the user to follow
- [x] Each step is complete with a link to the place that step will be carried out  
- [x] User flow is included/updated.
- [x] Images should have alt text notated for #1693 Knowledge Center implementation (alt text will be associated to image in HackMD. 

**Notes**

- [x] How to create a login.gov account
- [x] login.gov has an article that probably covers most of the content here but we can draft some copy re: how we’ll get people in front of it (i.e. email and/or start of the Logging into the TANF Data Portal resource)
- [x] Logging into the TANF Data Portal
- [x] Your login.gov account will be linked to TDP automatically the first time you sign in using login.gov from the TDP homepage (link to TDP homepage)
- [x] Request Access process (why it exists, timeline to expect)
- [x] Welcome Email to include pilot expectations 

**Things to Consider**
- [x] Identify for pilot testing who is sending out these emails. Regional officers, Raft or OFA? Proposing that this comes from Raft. 

**Tasks**
- [x] Draft email copy in a [hack.md](url)
- [x] Review / critique opportunity w/ DIGIT team (Alex/Thomas)
- [x] Revision as needed

**DD**
- [ ] @lfrohlich has reviewed and signed off

**Comment by stevenino** [comment]
Will drive additional dev tix

**Comment by lilybl1** [comment]
@reitermb @stevenino @lfrohlich @ADPennington Please find the mural link and the hackMD pages for review. 

- [Mural](https://app.mural.co/t/raft2792/m/raft2792/1652817527671/4a39866b6f8c5169963e4051a99456f7d27fed78?sender=u3ca60168b5ac4eb17bf92804)
- [Sign-In with Existing LOGIN.GOV account](https://hackmd.io/t1lPMv2vQkCxcDhtPxrbCg)
- [Create New LOGIN.GOV account](https://hackmd.io/I5zu3_jNSZem9Y2cQpb2TA?both)

**Comment by stevenino** [comment]
@lilybl1 Just a few comments.
- Have we decided that the introductory email is coming from a @goraft.tech account? What are the long term implications?  What happens if they reach out with questions not specific to TDP but data specific?
- Is the plan to actually send "manual" emails once TDP access is granted? Who will be sending them? From what email address? Will it be confusing if it is different from the introductory email?
- Why does the "Create New LOGIN.GOV account" ask the question of "do you have a LOGIN.GOV account?" since this document is meant to be for people without an account?
- Are there any legal issues with saying "Read and accept the Rules of Use" in step 3 of "Create New LOGIN.GOV account"?
- Is all of the text in step 5 of "Create New LOGIN.GOV account" actually required?

**Comment by ADPennington** [comment]
left my feedback in hackmds.

**Comment by lfrohlich** [comment]
My comments are in hack.md and Mural. Looking really good @lilybl1 !

**Comment by lilybl1** [comment]
@reitermb @lfrohlich @stevenino Please see below for the comments back and what has been done/completed. @ADPennington I'm working the HackMD feedback next. 
[Steve] Have we decided that the introductory email is coming from a @goraft.tech account? Yes. 

What are the long term implications? This story is focusing just on the pilot program that is happening in August which is short term. Long term when this scales or after hand-off with OFA, definitely need to setup a OFA affiliated email distribution. The reason we didn't want to send to OFA right now is that according to Alex, that inbox is already pretty full and if grantees reply, that may get lost in the shuffle. Creating a new inbox on the OFA side for long term seems like a launch task item that OFA would coordinate internally. Let's discuss if you had other thoughts here.  

What happens if they reach out with questions not specific to TDP but data specific? 

My initial thought is for the short term pilot testing, Miles and I will be manning this inbox and will coordinate with Alex/Lauren if they are questions that we cannot answer.  

I'm hesitant to add everyone to the distribution because it would be preferred that there's a POC that will be responding each time vs. 5 different people chiming in on an email stream.  

Thoughts?  

[Steve] Is the plan to actually send "manual" emails once TDP access is granted? Who will be sending them? From what email address? Will it be confusing if it is different from the introductory email? 

As we discussed in Backlog, due to the small volume of grantees in pilot testing (~roughly 15ish) we would be starting with manual emails. If we wanted to automate this flow then we would need to prioritize and pick-up story 1336. 

When we spoke about this during UX Sync it was discussed that Alex or Thomas would then send the email from their own email address. However, if might be cleaner for the short term in pilot to create a spreadsheet of grantees, track who has requested access, granted access and the UX team will manage coordinating with Alex. Then the UX team can send out the email from [tdppilot@goraft.tech](mailto:tdppilot@goraft.tech). This would keep all the email communication cleaner.  

[Steve] Why does the "Create New LOGIN.GOV account" ask the question of "do you have a LOGIN.GOV account?" since this document is meant to be for people without an account? 

This was an internal thought bubble – looking to include that in the Knowledge Center potentially 

This has been removed from the document itself. 

[Steve] Are there any legal issues with saying "Read and accept the Rules of Use" in step 3 of "Create New LOGIN.GOV account"? 

It is a required step, but agree we may not need to be so explicit in the statement.  

Is all of the text in step 5 of "Create New LOGIN.GOV account" actually required? 

[Miles] Alt text added to HackMD for reference and will need to transfer over to the Knowledge Center page - done 

[Miles] Welcome Email – add a view lines of content on the pilot program feature set – Done 

[Lauren] Mural comments – responded and done

**Comment by lilybl1** [comment]
@ADPennington @lfrohlich HackMD comments have been resolved except for 2 items:
1. [Step 11](https://hackmd.io/I5zu3_jNSZem9Y2cQpb2TA?both) -- there was a request to add a screenshot of the actual email template once the system admin grants access. At this time, we don't have the html email template yet as this is in our future story #1708 -- Also, one thing to note is maybe we don't want to get so specific here and assume everyone will be granted access - isn't it possible that system admin could DENY access as well? My proposal is to keep it generic. Let me know what you think. 
2. Step 12 - will grab screenshot as soon as it is available

**Comment by lilybl1** [comment]
@ADPennington RE: Existing Login.gov comment -- im pretty sure that someone with an existing account in logingov prod env can use it to log into tdp but we've only been using logingov sandbox env so far which does not recognize existing accounts, so we're asking login.gov support to confirm. -- Did someone get back to you on this?

**Comment by ADPennington** [comment]
login.gov support ticket 442 was created to track our UX-related questions. 

1) re: existing accounts --they confirmed that when we shift to logingov production environment, users who have an existing logingov account can use that. this is not currently possible in sandbox, which we've been using. 

2) re: latency issue with 2fa in sandbox--they are still looking into this. this isn't expected behavior. 


cc: @lilybl1

**Comment by ADPennington** [comment]
> 2. re: latency issue with 2fa in sandbox--they are still looking into this. this isn't expected behavior.

from login.gov support :

> In Sandbox we don't use an assigned shortcode. This means that our messaging tool is pulling a number from a shared pool and if those numbers aren't available delivery could be slower. This is not the case on production. On production we have a dedicated shortcode and that ensures prompt delivery.

To be sure, we should test the experience again when we're setup in prod. @lilybl1

**Comment by lilybl1** [comment]
@ADPennington @lfrohlich Reviewed and updated per discussions. This is moving back into QASP for final review.

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich Reviewed and updated per discussions. This is moving back into QASP for final review.


@lilybl1:
- re: Await for Access Next Steps -- can this be dropped? i think the step after this (i.e. Approved for TANF Data Portal)  could acknowledge that the person will have received an email from X on their access request status and if the request has been approved you'll be able to login and see etc. etc.  etc.. Would this work? 
- re: Approved for TANF Data Portal--is there a need for this placeholder? let me know if you need access to something to see the home page

**Comment by lilybl1** [comment]
@ADPennington 

1. Re: Who will email the Welcome AND the Access Approved email - for the pilot this communication will come from the email address tdppilot@goraft.tech - since there will only be roughly 15 people in this v2.0 pilot we will just coordinate via spreadsheet on who has requested and been approved. This will allow us to keep the communication centralized. 

3. re: Await for Access Next Steps
[Alex] can this be dropped? i think the step after this (i.e. Approved for TANF Data Portal) could acknowledge that the person will have received an email from X on their access request status and if the request has been approved you'll be able to login and see etc. etc. etc.. Would this work?
[Diana] I'd recommend to keep this step without the email template and just leave it with the text so that we are setting the right expectation. 

4. re: Approved for TANF Data Portal
[Alex] is there a need for this placeholder? let me know if you need access to something to see the home page
[Diana] Miles is currently working on this screen in feature story #1653 so I'd like to include that once it's ready.

**Comment by lilybl1** [comment]
@ADPennington Updated per our post scrum. Please note that we will update the placeholder screenshot with the final version once #1653 is complete. We discussed this would be appropriate for this ticket.

**Comment by ADPennington** [comment]
> @ADPennington Updated per our post scrum. Please note that we will update the placeholder screenshot with the final version once #1653 is complete. We discussed this would be appropriate for this ticket.

thanks @lilybl1 👍🏾 this is approved. let's be sure to revisit the placeholder photo before this document is added to the knowledge center. cc: @reitermb @lfrohlich
