### ISSUE TITLE
Deploying a different branch to any named instance overwrites django admin static files.

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1694]
**Description:**

In testing a recent update to django admin 508 we encountered differences between local testing environments and the deployed environment that likely arose from css files from another deployment.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Deployments to a different domain don't affect other django admin static files
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Spawn new s3 services for each instance
- [ ] Update each set of environment variables.

- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by abottoms-coder** [comment]
Please reference the s3 prefixes in #1347 when refining this ticket. I think this will solve this issue.

**Comment by robgendron** [comment]
Update: Still needed.

**Comment by robgendron** [comment]
@andrew-jameson please have Dev team pair with Alex on this.
