### ISSUE TITLE
Draft interview protocol for Round 3 of research with STTs

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#170]
**Description:**
Based on the research plan #63, create an interview protocol to use for conducting Round 3 of research. 

**AC:** 

- [x] Interview protocol for Round 3 is drafted based on the tasks

**Tasks:** 

- [x] Draft conversation guide
- [x] Update #115 mockup based on questions created
- [x] Update #275 mockup based on questions created
- [x] Refine goals #226 if needed 
- [x] Create email language template 
- [x] Create template for recording interview notes
- [x] Create PDF versions of mockups
- [x] Update Privacy Agreement

**Reference Documentation:**

03/27/2020 Interview Protocol for XLS: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B95b3ce6f-21d9-4cdc-9276-4f1eea122f81%7D&action=view)) 
04/27/2020 Interview Protocol for Executable Users: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B9907643d-655f-483f-944e-938b5c80c04d%7D&action=view))

**DoD:**
 
 - [ ] Documentation: Interview protocol has been shared with the PO and team for feedback
 - [ ] @cmajel has reviewed and signed off
 - [ ] @lfrohlich has reviewed and signed off

**Deliverables:**

Conversation Guide: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B0333313b-0f88-406b-b894-07687d32921b%7D&action=view))

#115 & #275 Figma Conceptual Mockup 2 Update: ([Link](https://www.figma.com/file/y15co5xc7MIZXBnWBOF6hJ/Conceptual-Mockups-for-STT-Feedback?node-id=0%3A1))
#115 & #275 Figma Conceptual Mockup 1 Update: ([Link](https://www.figma.com/file/y15co5xc7MIZXBnWBOF6hJ/Conceptual-Mockups-for-STT-Feedback?node-id=1%3A2))

TANF Uploading Tool - Mockup 1 PDF: ([Link](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA-UserResearch/Shared%20Documents/User%20Research/STT%20Research%20September%202020/TANF%20Uploading%20Tool_Mockup%20%231.pdf?CT=1601989467103&OR=ItemsView))
TANF Uploading Tool - Mockup 2 PDF: ([Link](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA-UserResearch/Shared%20Documents/User%20Research/STT%20Research%20September%202020/TANF%20Uploading%20Tool_Mockup%20%232.pdf?CT=1601989592610&OR=ItemsView))

#226 Goals Update: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7BA7504334-576D-4ADC-B3AF-45A432492E2F%7D&file=%23226%20-%20September%20User%20Research%20Goals%20-%20STTs.docx&action=default&mobileredirect=true))

Email Language Template: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B645fcfdc-c65d-474a-9c57-d51f3c68ac96%7D&action=view))
STT Privacy Agreement: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B3638AACC-C55D-4B0A-B948-488010F3215B%7D&file=STT%20Participant%20Agreement.docx&action=default&mobileredirect=true))

STT Interview Notes Raw Notes (Template): ([Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B5b822004-b831-4630-88f9-649357b98d3f%7D&action=view))
STT Interview Notes Raw Notes Consolidated (Template): ([Link](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B79a561e4-fca9-4c1e-8069-304e8e794e4f%7D&action=view))

**Comment by dk-ui** [comment]
Hey @lfrohlich , this should be good to go for some async squishy feedback. My goal is to have it all good to go by early next week so i can start sending it out to RO's.

https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B645fcfdc-c65d-474a-9c57-d51f3c68ac96%7D&action=view&cid=ec7ee4dc-52ed-45da-9b43-6545852cfcca

**Comment by lfrohlich** [comment]
This was completed in Sprint 5
