### ISSUE TITLE
As a tech lead, I want frontend linter `prettier` issues to fail the CI pipeline

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1705]
**Description:**
_Provide a brief background and justification for this issue_
While working on a frontend ticket, @riatzukiza was running into a `prettier` linter issue for local development but which does not fail the CircleCI build (although it is present there too!). We also have the `eslint` linter which will fail the CI pipeline. The use of two disparate linters for the frontend is redundant and a bit inconsistent.

```
Failed to compile.
tdrs-frontend-tdp-frontend-1  | 
tdrs-frontend-tdp-frontend-1  | src/components/Header/Header.jsx
tdrs-frontend-tdp-frontend-1  |   Line 31:5:  Replace `····userAccessRequestApproved·&&·isMemberOfOne('Developer',` with `userAccessRequestApproved·&&⏎····isMemberOfOne('Developer',·`  prettier/prettier
tdrs-frontend-tdp-frontend-1  | 
tdrs-frontend-tdp-frontend-1  | Search for the keywords to learn more about each error.
```

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Any frontend linter issue will still fail the CI pipeline
- [ ] Ensure all frontend tests run whether or not the linter fails
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Unify the `.prettierrc` and `.eslintrc` configurations
- [ ] Unify `eslint` execution configurations such that it aligns with `prettier`
- [ ] Update CI pipeline captures/respects linter errors
- [ ] Update pipeline to run tests either before linter steps and/or try to run all pipeline steps and roll up errors at the end
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by robgendron** [comment]
@ADPennington @lfrohlich @andrew-jameson, is this still needed or can it be closed?
