### ISSUE TITLE
As a developer, I want to improve our backend logging formatter

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1707]
**Description:**
_Provide a brief background and justification for this issue_
To improve our debugging and troubleshooting, we could get change the formatters utilized in `common.py`.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Logs have code-location information.
- [x] Logs are visible in cloud.gov's Logstream or accessible in another way.
- [ ] Log files are generated in addition to standard output/error.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update formatters in use to include class name, function name, and line number preferably.
- [ ] Update logging console such that logs are duplicated in logfile(s) and also visible in stdout/stderr
- [ ] Ensure logging best practices are followed (not everything is debug/error, etc.)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Python logging formatStack](https://docs.python.org/3/library/logging.html#logging.Formatter.formatStack)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by stevenino** [comment]
This should be done in the v2 timeframe. It will facilitate debugging in the future.

**Comment by andrew-jameson** [comment]
After resolution of the Cloud.gov LogStream, I no longer feel we need to also log to a file so I no longer think we need to evaluate that acceptance criteria. Additionally, I don't feel like this is the ticket for scouring all of our logging statements and making them pretty -- that will and should be an iterative process.
