### ISSUE TITLE
[Research] V2 Notifications Evaluation Session

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1709]
**Description:**
Facilitates session with regional staff to test/critique/discuss V2 notifications content

**AC:**
- [ ] Session with OFA Regional Staff has occurred
- [ ] Session notes or other top-line synthesis is documented.

**Tasks:**
- [ ] Pair with Lauren to schedule session 
- [ ] Facilitate session
- [ ] Capture notes from session
- [ ] Create follow-on ticket—if needed (for design changes suggested by session)

**Supporting Documentation:**
- Link to [tested content]()

**Comment by robgendron** [comment]
@reitermb Can you give an update on this? #2509 may be the DEV version of this.

**Comment by robgendron** [comment]
Deemed a DUPE by Miles and the Dev Team.
