### ISSUE TITLE
Project Impact workshop for Sitemap Surveys

### ISSUE THREAD

**Issue by sreedevip** [raft-tech/TANF-app#1717]
**AC**
- [ ] Results of the tree test (Sitemap Survey) have been analyzed and findings shared with the team to discuss potential changes to the Information Architecture
- [ ] Changes have been reflected in the Sitemap if applicable [536](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/536)

**Tasks for Project Impacts for the team** 

- [ ] Determine the best way to share results from tree tests (sitemap surveys) to the team
- [ ] Present the findings to the team to discuss changes, if any, to TDP's Information Architecture (IA) and subsequent lift for the dev. team
- [ ] Makes changes, if any, to the Sitemap on Figma
- [ ] Use the findings of sitemap surveys with OFA and STT to inform the [HTML Sitemap](https://github.com/raft-tech/TANF-app/issues/1385)

**Comment by sreedevip** [comment]
This ticket is a result of splitting #1593 into Project Updates and Project Impact workshop for Sitemap Surveys, as agreed upon during a Mattermost discussion on 3.28.2022. 
@lfrohlich @stevenino @reitermb @ADPennington
