### ISSUE TITLE
As tech lead, I need our release strategy documented

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1726]
**Description:**
_Provide a brief background and justification for this issue_
As we approach release 1, we do not appear to have documented how to handle versions/releases either for labelling, merging, nor deployments.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Our release and branching strategy is updated/documented
- [x] Deployment process to production is documented
- [x] Hotfix processes are accommodated
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update [deployment doc](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/Architecture-Decision-Record/008-deployment-flow.md) to accommodate "master" branch in HHS
- [x] Outline version changelog format/process
- [x] Outline what version artifacts are needed and where to store/document them
- [x] Document the release-version nomenclature (e.g., `release/major-minor-patch(-description)`)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Basic gitflow docs](https://datasift.github.io/gitflow/IntroducingGitFlow.html)
- [Atlassian gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
