### ISSUE TITLE
As a developer, I need to know the file naming convention for ACF Titan

### ISSUE THREAD

**Issue by abottoms-coder** [raft-tech/TANF-app#1736]
**Description:**
_Provide a brief background and justification for this issue_
In preparation for transferring files to ACF Titan, we need to strictly follow their filename nomenclature and have our application rename files.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Function returns a completed filename for use by the sftp transfer in #1133
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Using the data from [stt models](https://github.com/raft-tech/TANF-app/tree/raft-tdp-main/tdrs-backend/tdpservice/stts/management/commands/data), grab the relevant FIPS code.
- [ ] Using the notation in the documentation section below, form the relevant string
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

Please see #1011 for further details.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
STT Naming Conventions:
![STT_naming](https://user-images.githubusercontent.com/84722778/121413214-7813a300-c933-11eb-8e29-08a0f85422d9.png)

Tribal Naming Conventions:
![tribal_codes](https://user-images.githubusercontent.com/84722778/121413232-7cd85700-c933-11eb-81e8-6ea48d070b31.png)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by andrew-jameson** [comment]
Investigating `tdrs-backend/stts/management/populate_stts.py` so that @raftmsohani 's function can be tested and iterated with data from the filenames column from the csvs in `stts/management/data`.
