### ISSUE TITLE
As tech lead, I want only approved TDP users with data submission permissions to have the ability to view/submit data files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1744]
**Description:**

[Data-files page](https://tdp-frontend-develop.app.cloud.gov/data-files) is currently visible for any authenticated user, even those who have not been assigned to a permissions group. This is not necessary and could introduce security issues if we add sensitive content to this page.

Additionally, authenticated users who are not in an `approved` state (e.g. pending with a data analyst role) have the ability to submit files. roles and account status should be in alignment. 

**Acceptance Criteria:** 

- [ ] Only approved users with permissions to submit data (i.e. `OFA Admin`, `Data Analyst` , and `Developer` (in non-prod envs only)) can see the data-files page
- [ ] Only approved users with permissions to submit data, can click `search` and `submit data files`  buttons
- [ ] Only approved users with permissions to submit data, can access previously submitted data files for their STT
- [ ] Permissions are up to date for each user group. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Update settings around data-files page views
- [ ] ensure account status and group permissions are aligned 
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] Redirect user to Homepage 

**Notes:**
- (for future reference)  users with `OFA Regional Staff` role do need the ability to view submitted data files for their region only, but this can be addressed after #1605 is implemented. 
-  [permissions by group](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2F[Permissions](onenote:https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/SiteAssets/TANF%20Data%20Portal%20(OFA)%20Notebook/Compliance.one#Permissions&section-id=d9b65ab8-bf29-476a-a652-d003714e50a4&page-id=67b61c8f-b200-46e8-8e73-b5aa6382a19c&end)%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29&wdorigin=703)

**Supporting Documentation:**
- #1387 
- #1679

**Comment by stevenino** [comment]
This is beyond the scope of parity. It will be moved to V4.

**Comment by jtimpe** [comment]
same rules should hide the "Data Files" navigation item in the `Header` component for these roles.

take `account_approval_status` into consideration (must be `Approved`)

**Comment by jtimpe** [comment]
acct approval status emails - approved requires role access

**Comment by stevenino** [comment]
@ADPennington cleanup prior to being assigned.

**Comment by ADPennington** [comment]
@stevenino ticket revised.
