### ISSUE TITLE
Configure nightly owasp scans to run on additional branches

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1754]
**Description:**
Currently, nightly scan jobs run on the `raft-tech/tanf-app:develop` [branch](https://github.com/raft-tech/TANF-app/blob/8d90f867fa8cf8be641eed4f9e8472e475f80a65/.circleci/config.yml#L604), and these reports are stored in [TDP staging backend](https://github.com/raft-tech/TANF-app/blob/8d90f867fa8cf8be641eed4f9e8472e475f80a65/.circleci/config.yml#L452-L478). 

We need these scans to also run on `hhs/tanf-app:main` and `hhs/tanf-app:master` branches, and the reports should be stored in their respective backends. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _owasp scan runs on `hhs/tanf-app:main`  and reports accessible in DAC_
- [ ] _owasp scan runs on `hhs/tanf-app:master` and reports accessible in DAC_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _update circleci/config.yml_
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _What are the benefits of continuing to run nightly scans on `develop` branch?_

**Comment by abottoms-coder** [comment]
> What are the benefits of continuing to run nightly scans on develop branch?

Short: We might catch an issue prior to a subsequent release/version bump.

Long: `hhs:main` will be a series of release-only merges and therefore our present staging environment will majorly only contain release-oriented code. `raft-tech:develop` might have devops/DX or other minor feature inclusions not destined for our current release cycle; put another way, staging may lag behind develop. While we can run the owasp zap scan within the circleci docker image, we could also have a `tdp-frontend-develop.app.cloud.gov` instance to just have a real-time reference of that branch instead of it being a nebulous "latest". Obviously this is open for discussion and I would like to discuss at dev sync with the team and @ADPennington specifically as this alters our cloud.gov architecture. For the scope of this ticket, I think we should continue to let it run on develop and in a subsequent discussion of our cloud architecture we can determine the future of scanning develop.

**Comment by n0remac** [comment]
@andrew-jameson @ADPennington In our configurations I don't see any references to Forks(which I believe is intentional)

It looks like OWASP will run on hhs/tanf-app:develop but it will probably not work because it has the wrong login credentials.

Similarly, if I configure it to run on main and master, it will do so on both the HHS and raft-tech fork. Is this behavior acceptable or do you want it only to run on those specific branches?

**Comment by n0remac** [comment]
> * If yes to the above, we could maybe adapt this job for the production context (e.g. `nightly-owasp-scan-prod`) which would run only on master (which also should only exist in hhs/tanf-app). note that this would make the config file longer so im sure there are more efficient ways to do this. there may be other things steps/jobs to account for in this super long file too

I think I can make the current `nightly-owasp-scan` abstract enough to work for any environment. I'll have to work on it a bit to find out.



> * hhs/tanf-app doesnt have a develop branch

Will it be ok if runs on both hhs/tanf-app:main and raft-tech/tanf-app:main?

**Comment by ADPennington** [comment]
> > * If yes to the above, we could maybe adapt this job for the production context (e.g. `nightly-owasp-scan-prod`) which would run only on master (which also should only exist in hhs/tanf-app). note that this would make the config file longer so im sure there are more efficient ways to do this. there may be other things steps/jobs to account for in this super long file too
> 
> I think I can make the current `nightly-owasp-scan` abstract enough to work for any environment. I'll have to work on it a bit to find out.

sounds great! 

> > * hhs/tanf-app doesnt have a develop branch
> 
> Will it be ok if runs on both hhs/tanf-app:main and raft-tech/tanf-app:main?

if you mean hhs/tanf-app:main and raft-tech/tanf-app:develop, then yep, i think this is what we'd like per [Andrew's justification here](https://github.com/raft-tech/TANF-app/issues/1754#issuecomment-1110143384). to my knowledge, raft-tech doesnt have a main branch.
