### ISSUE TITLE
As an STT data analyst, I need to tell TDP which data report I am uploading

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1755]
**Description:**
As of April 2022, 16 STTs submit -- in addition to the TANF Data Report -- the SSP-MOE Data Report (see list [here](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/states.csv)) through TDRS. These reports are very similar (e.g. submitted quarterly, up to 4 sections are submitted, up to 7 types of records that need to be parsed, content of the data files is very similar, etc.). 

Currently, TDP only distinguishes data files by fiscal year/quarter and section type, so it is not possible for an STT to submit data files for a given data report, quarter and section.  We need this distinction so that TDP knows how to parse, validate, and store the data files correctly. 

Duplicate of #1112

**Acceptance Criteria:** 
- [ ] STT Data Analyst can select the type of data report being uploaded
- [ ] Radio button section not visible to users of STTs without SSP indicator
- [ ] Radio select defaults to TANF
- [ ] Heading 1 is modified to read "Data Files" instead of "TANF Data Files"
- [ ] Heading 2 prints radio selection between [STT Name] and [Fiscal Year]
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Update [`populate_stts.py`](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/populate_stts.py) to append SSP as boolean to STT model
- [ ] Ensure new SSP field for a user is accessible on the frontend
- [ ] Create radio button section on `/data-files/` frontend to comply with ACs
- [ ] Ensure section utilizes USWDS components

**Supporting Documentation:**
- _Current dropdown selections for STT data analysts (with no data report option)_
![1755p1](https://user-images.githubusercontent.com/63075587/163877937-efeda5cd-c60b-499a-b9e5-7206607eddee.PNG)
- _Example mock-up that includes an data report type option (disregard "reporting month")_
![image](https://user-images.githubusercontent.com/63075587/163877969-132c4b06-db6d-4d28-ae70-9a2c59bec894.png)

UX refined 7/18/22
https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=7059%3A49955 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
@reitermb feel free to add any add'l context on figma mockup

**Comment by stevenino** [comment]
@reitermb to create a R&D ticket to refine this ticket. New ticket will block this ticket

**Comment by stevenino** [comment]
Not required for initial pilot release but a nice to have at a later pilot release if SSP data users enter the pilot program (~Nov 2022)
