### ISSUE TITLE
[Dev-ready Design] TANF / SSP-MOE Search Control

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1757]
**Description:**

Delivers an updated spec for being able to search for SSP-MOE as well as just TANF data files. Our original design for this was an extremely informal one generated as part of an early-project ideation session and needs to be updated for consistency with current-state TDP design. Noting that we've been referring to this in discussions as a "dropdown", but the preferred form control here will be a radio select given that there are only two possible values (TANF vs SSP-MOE).

Data Files / Error Reports research that happens prior to this ticket may impact this plan if we find that users want to be able to view error guidance for SSP data more closely alongside error guidance for TANF data (as opposed to having to adjust their 
search to hop between the two).

**Related User Stories:**

- As a grantee user I want to search for files for a given quarter for SSP-MOE reporting (not just TANF).
- As an OFA user I want to search for a particular grantee's SSP-MOE files for a given quarter.

**AC:**

- [x] Documentation work for the following has occurred:
   - [x] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [x] Dev/Design sync has occurred; resulting tickets created (#1755)
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Create a new Figma page for #1757 
- [x] Update design for SSP/TANF radio control (currently found on the [Ideas](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/?node-id=647%3A9595) Figma page.
- [ ] Export PDF/Open PR to dev-ready PDFs repo folder (including an update to the readme)

**Supporting Documentation:**

[Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=7059%3A49954)

**Comment by lfrohlich** [comment]
Hi @reitermb I added a comment about TANF changing to SSP-MOE if selected above--this should also probably be an annotated sticky for dev awareness. Per the ACs, has the Dev-Design sync happened and have follow up tickets been created?

**Comment by stevenino** [comment]
@lfrohlich The dev tix is referenced above #1755. It was reviewed/refined and prioritized at backlog refinement yesterday.

**Comment by lfrohlich** [comment]
Thanks @stevenino. I made the reference explicit in the ACs.
