### ISSUE TITLE
Cloud.gov apps needs restaging (5/11/2022)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1779]
**Description:**
Received the following e-mail from cloud.gov:

```
Hi cloud.gov user,

cloud.gov frequently updates the programming language buildpacks available to
our customers. Buildpack updates include programming language updates and
often include security fixes.

We recently updated buildpacks in use by your applications. You should
restage or redeploy your applications to take advantage of the update.

Keep in mind that restaging is the quickest way to
upgrade, but causes downtime so you may want to leverage your deployment infastructure
if you have set up zero-downtime deploys.

You can restage your applications by opening the command line and entering
the following commands:

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-frontend-sandbox

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-frontend-qasp

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-frontend-raft

  cf target -o hhs-acf-ofa -s tanf-staging ; cf restage tdp-backend-staging

  cf target -o hhs-acf-ofa -s tanf-staging ; cf restage tdp-frontend-staging

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-frontend-a11y

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage elastic-demo-kibana

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-backend-qasp

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-backend-raft

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-backend-a11y

  cf target -o hhs-acf-ofa -s tanf-prod ; cf restage tdp-frontend-prod

  cf target -o hhs-acf-ofa -s tanf-prod ; cf restage tdp-backend-prod

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage tdp-backend-sandbox


For more information about the buildpack update(s), please see the following release notes:

  go_buildpack v1.9.42: https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.9.42

  nodejs_buildpack v1.7.69: https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.69

  python_buildpack v1.7.53: https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.53

  java_buildpack v4.48.3: https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.48.3

  ruby_buildpack v1.8.53: https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.8.53

  php_buildpack v4.4.59: https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.4.59

  dotnet_core_buildpack v2.3.41: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.3.41

  nginx_buildpack v1.1.37: https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.1.37

  r_buildpack v1.1.28: https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.1.28

  binary_buildpack v1.0.43: https://github.com/cloudfoundry/binary-buildpack/releases/tag/v1.0.43


For more information on keeping your application updated and secure, see:
https://cloud.gov/docs/getting-started/app-maintenance/

If you have questions, you can email us at cloud-gov-support@gsa.gov.

Thank you,
The cloud.gov team
```

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] [Outlined process](https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/Architecture-Decision-Record/011-buildpacks.md#notes) is followed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Restage apps
- [ ] Update changelog
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by andrew-jameson** [comment]
We will still need to update nginx for all frontend applications and once develop has been merged into all branch, restage/redeploy to all environments.
