### ISSUE TITLE
[SPIKE] Backend e-mail relay

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1784]
**Description:**
_Provide a brief background and justification for this issue_
Investigate usage of `smtp.ees.hhs.gov` as relay from our Cloud.gov spaces.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Produce script(s) or series of commands for sending an e-mail (and email actually gets sent)
- [x] Pro/con list of SMTP tools (python library vs. linux CLI tool vs...)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Investigate python libraries for working with smtp
- [x] Investigate smtp cli tools 
- [x] Investigate cloud/webapp smtp tools
- [x] Stretch: proof of concept integration with our Django app
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
- [DKIM hack.md](https://hackmd.io/@dBEtH2T9SRqyVnE3ZKtYSA/rkXq8XPdn)
 - https://github.com/cloud-gov/pages-mailer
 - https://aws.amazon.com/ses/
 - https://docs.python.org/3/library/smtplib.html
 - https://realpython.com/python-send-email/

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- How do we ensure this is secure and couldn't be potentially exploited as an open-source project?

**Comment by riatzukiza** [comment]
```python
import smtplib

smtp_server = "smtp.ees.hhs.gov"
sender_email = "test_user@hhs.gov"  # Enter your address
receiver_email = "abeavers@goraft.tech"  # Enter receiver address

message = """\
Subject: Test email from TANF

This message is sent from Python."""

server = smtplib.SMTP(smtp_server)
server.sendmail(sender_email, receiver_email, message)

server.quit()
print ("Email Sent")
```

**Comment by n0remac** [comment]
Django has a stmplib wrapper 
https://docs.djangoproject.com/en/4.0/topics/email/

What are we doing about TLS/SSL? It looks like we can use cloud.gov as a Certificate Authority.

**Comment by stevenino** [comment]
Closed as done per DSU on 7/13/22

**Comment by ADPennington** [comment]
re-opening re: Ironport cc: @andrew-jameson @Smithh-Co @lfrohlich

**Comment by ADPennington** [comment]
we are going to use this ticket to track the creation of an ADR re: email implementation @Smithh-Co

**Comment by ADPennington** [comment]
### June 2023 update on backend email relay requirements 

From HHS ITIO E-mail team on 6/28/2023: 

> In quick summary we will need you to:

>>1.	Establish a relationship with a third-party email service provider
>>2.	Generate a DKIM + SPF record from the email service provider for you verified domain identity: @acf.hhs.gov 
>>3.	Submit DKIM + SPF record to DNS team
>>4.	Point your application to the email service provider’s SMTP server(s)
>>5.	Test sending email from your @acf.hhs.gov mail from address(es) 


>>> Something to think about…

>>>[https://sendgrid.com/solutions/email-api/smtp-service/](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsendgrid.com%2Fsolutions%2Femail-api%2Fsmtp-service%2F&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7Cf522638029b440edd36e08db781c41a9%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638235834990464937%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hnhAMwOZQ5r6HDYZtngiLAUY5bJc71LoV2DbKjH6y2U%3D&reserved=0)

>>>I know some of our applications use this. So it’s something to check out.

---
@lfrohlich @Smithh-Co @andrew-jameson @jtimpe @George-Hudson @raftmsohani @elipe17 

For immediate next steps, we've agreed to explore the pros/cons of <ins>SendGrid</ins> and <ins>Amazon SES </ins> along the following dimensions (feel free to suggest others):

- technical complexity (aiming for feasible, lowest lift, sustainable solution)
- meets FISMA Moderate compliance standards 
- is compatible with cloud.gov ([reference](https://cloud.gov/knowledge-base/2021-09-21-sending-emails-from-clouddotgov/#connecting-to-a-cloud-service-provider-offering))
- costs

Our goal is to follow-up with the HHS E-mail team with our implementation plans/timeline by **7/14/2023**. 

[Hackmd here](https://hackmd.io/25liUecySPSXOtyiF6YugA)

**Comment by jtimpe** [comment]
@Smithh-Co 

Update as of 7/17

The draft pull request #2613 demonstrates connecting to the Sendgrid email api to relay emails, rather than relaying via the HHS smtp server. Aside from the package addition and config changes, the pr also includes some debugging lines and a potential optimization to avoid kicking off a new celery process for every email (the call can be treated synchronously and may give us more information on request failures). 

I still need to test out the optimization, but Alex and I were able to verify that account status change messages are being sent successfully via Sendgrid

**Comment by jtimpe** [comment]
7/18 update @Smithh-Co 

Did some more testing locally and pushed a couple more changes to the draft pr, updating the implementation of `automated_email` throughout the codebase to be synchronous calls to sendgrid, instead of creating a new celery task for each call. Most times we use the email function, it's wrapped in a celery task anyway; for the times it's not, it was hiding some exceptions being thrown.

~~Tests are still failing due to the `pipenv` issue we were having, but eric has a fix in #2607 that will resolve it - once it's merged I will update the branch and put the pr in raft review.~~

Update - i tried to merge the pipfile changes into the sendgrid branch and turns out there's an incompatibility. In researching that, I noticed this issue in the library we use, discussing deprecating it https://github.com/sklarsa/django-sendgrid-v5/issues/117

I'd like to spend some time tomorrow to incorporate the new official sendgrid python library, which unfortunately doesn't work with our django code out of the box. My idea is to create a custom email backend (similar to the dkim strategy) but use the official sendgrid library as the handler.

**Comment by jtimpe** [comment]
7/19 update @Smithh-Co 

Pushed a round of updates to the PR that utilize the official `sendgrid-python` library. I've put the PR in raft review and will get the details added to the description shortly.

**Comment by jtimpe** [comment]
7/20 update @Smithh-Co 

Filled in the PR description and opened it up for raft review.

**Comment by jtimpe** [comment]
7/24 update @Smithh-Co 

No real update - still in raft-review, just needing one more approval. I know we still need approval on using Sendgrid in our stack so no rush.
