### ISSUE TITLE
As a developer, I want linters to run automatically before git push

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1786]
**Description:**
_Provide a brief background and justification for this issue_
Using git's pre-commit checks, ensure linters are auto-run before commit/push cycle.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Allow linting errors in commits for but not pushes.
- [x] Configuration document for developers is produced
- [x] Secrets checks run before commits are allowed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Investigate git commit/push file actions
- [ ] Investigate git secrets catches sendgrid api per recent events
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by robgendron** [comment]
Prioritize for after Parity.

**Comment by lhuxraft** [comment]
11/13/2024: Resolved git secrets, may show during office hours. Digging into truffle hog

**Comment by lhuxraft** [comment]
11/15: Continuing to look into truffle hog

**Comment by lhuxraft** [comment]
11/18: PR is up, needs two reviews

**Comment by lhuxraft** [comment]
11/19: Needs one more review, Jan left comments

**Comment by lhuxraft** [comment]
11/20: Incorporating existing feedback. Removing trufflehog

**Comment by lhuxraft** [comment]
11/25: Jan provided feedback, Eric running into issues with testing

**Comment by lhuxraft** [comment]
12/4: Working through issues w/ Jan's environment, need approvals from Eric/Mo
