### ISSUE TITLE
[Dev-ready Design] 

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#1787]
**Description:**
Provide grantees an alternative route to access TDP links in the form of a site map. 

**Related User Stories:**

—As a [Grantee] I want a site map page so that I can easily access TDP links to help me get to where I need to go next. 

**Recommended pa11y actions:**

—‘click element #error-report’,—

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] —Draft design in Figma—

**Supporting Documentation:**

—Link to Figma and Dev-Ready Design folder PDF—

**Comment by riatzukiza** [comment]
Make a follow on ticket for research task

**Comment by riatzukiza** [comment]
Preliminary screen shot for style of the site map (still have to adjust the button on the bottom):
![image](https://user-images.githubusercontent.com/10676925/178342373-7db62273-030e-4b24-8298-f30a3894f5e4.png)
