### ISSUE TITLE
Updating TANF resource cards on splash page

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1788]
**Description:**
_Provide a brief background and justification for this issue_
As a follow on from #276, we will populate the resource cards on the unauthenticated ticket. We believe this might be a duplicate ticket but could not find the other ticket.

**Acceptance Criteria:** 

- [ ] Unauthenticated landing page no longer has empty "resources"
- [ ] Page matches Figma wireframes
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Using the USWDS Card Component, create the dynamic cards for these resource links.
- [ ] Ensure links within Figma are attached to the corresponding cards and functional
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- As a user I want to access the knowledge center
http://tdp-project-updates.app.cloud.gov/knowledge-center/

- As a user I want to access transmission file layouts and edits for TANF & SSP
https://www.acf.hhs.gov/ofa/policy-guidance/final-tanf-ssp-moe-data-reporting-system-transmission-files-layouts-and-edits

- As a user I want to access Tribal TANF Data Coding instructions https://www.acf.hhs.gov/ofa/policy-guidance/tribal-tanf-data-coding-instructions
- As a user I want to access ACF-199/ACF-209 instructionshttps://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_reports_tan_ssp_instructions_definitions.pdf

**Supporting Documentation:**
- [Figma spec](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=7001%3A49624
)

**Comment by reitermb** [comment]
Updated the notes with the knowledge center URL (it won't work until we—UX—complete #1693, but we have reviewed the URL w/ Lauren & Alex and gotten the green light on it) cc: @andrew-jameson
