### ISSUE TITLE
As tech lead, I need the govbanner changed for production environment

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1789]
**Description:**
_Currently, TDP's prod frontend says the following:

https://github.com/HHS/TANF-app/blob/a913fb896e2558fa2625ce655f2696f8e5f1b973/tdrs-frontend/src/components/GovBanner/GovBanner.jsx#L24

![govbanner](https://user-images.githubusercontent.com/63075587/168685437-6a92246b-01eb-4067-bf46-6acef9762c5d.PNG)

For routes in lower environments, this is fine, but for production, it should look like this [ref](https://designsystem.digital.gov/components/banner/): 

```
An official website of the United States government
```

**Acceptance Criteria:** 
- [ ] govbanner should say "An official website of the United States government" in prod
- [ ] govbanner should stay unchanged in lower environments 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] update [`GovBanner.jsx`](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-frontend/src/components/GovBanner/GovBanner.jsx)
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- https://designsystem.digital.gov/components/banner/
