### ISSUE TITLE
As a developer, the frontend needs access to parser output content

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1807]
**Description:**
_Provide a brief background and justification for this issue_
This issue creates a bridge between #1121 and  #1122 allowing the frontend to query the backend and retrieve the relevant file contents.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Frontend can have access to the contents of the output files from #1121 
- [ ] Backend is queryable for data file id and output s3 link
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create a secure backend API that the frontend can query for output file given a data file identifier
- [ ] Add any relevant object handling/formatting transitioning from frontend to backend (JSON vs textblob, etc)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by andrew-jameson** [comment]
Scope added to #1121 upon request, this ticket is now OBE
