### ISSUE TITLE
As a TDP user, I want to be notified when my request for access to TDP has been submitted

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1814]
**Description:**

After a first-time user authenticates into TDP, they are redirected to the Request Access page of TDP. Completing and submitting the form via clicking the "Request Access" button on this page:
- triggers the `access_request` flag for the user to change from ❌ to ✔️ on the backend **(deprecated)**. 
- will trigger the `account_approval_status` field for the user to change from `Initial` to `Access request` 

When the `account_approval_status` field changes to `Access request`, this should trigger an email to the user that confirms that their request for access has been submitted. 

**Acceptance Criteria:** 
- [ ] When  `account_approval_status` field changes to `pending`, this should trigger a `Access request` email to the user that confirms that their request for access has been submitted.
- [ ] No other changes applied to `account_approval_status`  field should trigger a `Access request` email to the user. 
- [ ] Testing Checklist and confirm all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [Submit email content](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg#As-a-TDP-user-I-want-to-be-notified-when-my-request-for-access-to-TDP-has-been-submitted)
- [background on `access_request` flag](https://github.com/raft-tech/TANF-app/pull/1571)  
- _request access button_
![email](https://user-images.githubusercontent.com/63075587/171469831-343ab82f-8da2-4037-95d6-4a4e56986f61.PNG)

**Notes:**
- this email will trigger off a field that still be delivered when #1679 is addressed. 

**Release**
- V2.1

**Comment by stevenino** [comment]
@lilybl1 Update the email content to include STT name.

**Comment by lilybl1** [comment]
@stevenino Updated this email html to include STT name.

**Comment by stevenino** [comment]
Please use the content in this link https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/
