### ISSUE TITLE
[SPIKE] Explore automated devops tools for Cloud deployments including environment variables

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1826]
**Description:**
As a follow-on to #1489 / #1774 , our suite of bash scripts is incomplete in their adherence to principles:

1. Don't Repeat Yourself: our previous scripts had many repeated commands/segments
2. Idempotent: repeated operations on the same target produce the same result. In other words, the desired state is always attained and the state-machine of such operations is well-handled.
3. Infrastructure as code: Rather than storing state/configuration implicitly in the product, it is an improvement to have it explicit stored as code/config and be human-readable at a glance in a handful of files.
4. Automated/Low maintenance: While the maintained wasn't too high, we repeatedly have been updating these scripts with new hard-coded variable names but also updates to logic.
5. Robust: our existing scripts did not have great error-handling and needed manual intervention frequently
6. BONUS: I'd love if our tool could perform roll-backs to increase stability

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Environment variables should persist across application rebuilds/restages.
- [ ] Special environment variable values should remain across rebuilds (e.g., don't overwrite AMS_CLIENT_ID)
- [ ] Automation tool is maintainable and integrates well with our ecosystem
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Various tool options are explored for adherence to principles outlined in description
- [ ] Existing env vars are "saved" before an environment is deleted/recreated and ensure they are re-applied on start
- [ ] Remove extraneous environment variables from application spaces
- [ ] Make follow-on ticket to address Login.gov key instability and updates
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
- What about reimplementation with [Python](https://github.com/cloudfoundry-community/cf-python-client)?

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Can either of our current two tools (CloudFoundry or Terraform) accomplish these goals?
- Do we need a state-maintenance tool like Ansible/Vagrant/Puppeter above/beyond our current toolbox? 
- What other tools are best-suited to accomplish this infra-as-code task?+
-

**Comment by andrew-jameson** [comment]
As an aside, I would love to finish this devsecops improvement prior to releasing v3 to our wider customer base.

**Comment by lilybl1** [comment]
@andrew-jameson Please review with Tim when you get back

**Comment by andrew-jameson** [comment]
Closing out as the child tickets *are* the deliverables.
