### ISSUE TITLE
As a TDP user, I want to be notified when my request for access to TDP has been approved

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1839]
**Description:**
Currently, users do not have access to TDP until an admin changes their group assignment in their user profile. An assignment means that their request has been approved. Still, the user does not receive a notification of this approval. 

#1679 will deliver functionality for admins to manage requests for access to TDP. When this  field (`account_approval_status`) is changed to `Approved` in a user's profile, this should trigger an email notifying the user that their request has been approved. 

**Acceptance Criteria:** 

- [x] When an `OFA System Admin` changes a user's `account_approval_status` status to `Approved` in the user's profile, this will trigger an `approved` email to the user. 
- [x] No other status changes to `account_approval_status`  will trigger a `approved` email to the user. 
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- #1679 
- [Approved Email Content](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg#Email-Notification-Trigger--An-admin-approves-an-access-request)

**Notes:**
- Release 2.1

**Comment by stevenino** [comment]
Please use the content in this link https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/
