### ISSUE TITLE
As a TDP user, I want to receive an email notifying me that my TDP account has been deactivated.

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1840]
**Description:**
Currently, admins can deactivate a user's TDP account by navigating to their profile and checking the `deactivated` status.

#1679 will deliver newer functionality for admins to manage TDP user accounts. When this  field (`account_approval_status`) is changed to `Deactivated`  in a user's profile, this should trigger an email notifying the user that their account has been deactivated. 

**Acceptance Criteria:** 

- [x] When an `OFA System Admin` changes a user's `account_approval_status` status to `Deactivated` in the user's profile, this will trigger a `deactivated` email to the user. 
- [x] No other status changes to `account_approval_status`  will trigger a `deactivated` email to the user. 
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**

- [implementation of `deactivated` status field](https://github.com/raft-tech/TANF-app/pull/930)
- #1679 
- [Deactivated Email Content](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg#As-a-TDP-user-I-want-to-be-notified-when-my-account-is-deactivated)

**Notes:**
- Release 2.1
