### ISSUE TITLE
As a STT Data Analyst, I want to be notified when data for my program has been submitted.

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1845]
**Need to provide a [html email template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-has-been-submitted.html)** 

**Description:**
 
STT data analysts use the "submit data files" button on the [data-files](https://tdp-frontend-staging.app.cloud.gov/data-files) page for data transmission. A `submit` email should be triggered to all active users associated with STT **if and only if** this submission is successful. 

Active user := a user with the relevant STT in their profile and:
-  `is_active` = True
- `deactivated` = False
- `Group` = (STT) Data Analyst

**Acceptance Criteria:** 

- [ ] A `data submitted` email is sent to all relevant users associated with the STT when data successfully submitted
- [ ] `data submitted` email is _not_ sent out for unsuccessful data submissions or for any other activities on data-files page
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [data submission email content](https://hackmd.io/L0uwkVgxSPqfLBwOcuozPg#As-an-STT-analyst-I-want-to-be-notified-when-data-for-my-program-has-been-submitted)
-  _submit button and successful submission notification_
![submitdata1](https://user-images.githubusercontent.com/63075587/171671409-b39f88d2-2e33-4283-ac57-19d2e760dae2.PNG)

**Notes:**
- Release 2.1
