### ISSUE TITLE
Spike: Secure OFA staff access to Kibana

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1858]
**Description:**
As a front-runner to #1350, I wanted to explore the authentication and permission systems for ES/Kibana, TDP authorization of roles for those services, Cloud networking configurations, system hardening guidelines, etc.

I **cannot** understress the importance of security around the data within Elasticsearch that this ticket stalwarts against. This might be the right time to undertake #753.

**Acceptance Criteria:** 
- [ ] Dev-ready requirements for #1350 and potential follow-on tickets
- [ ] Recommended cloudfoundry security guidelines and configurations
- [ ] TDP user logic and flows for authorization
- [ ] Kibana/ES permissions and configurations guidelines/recommendations
- [ ] Application security hardening both for Kibana/ES and TDP
- [ ] Investigate/automate security scans around our data pool
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Research according to ACs
- [ ] Have write-ups and recommendations for those areas of concern

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by ADPennington** [comment]
@ttran-hub @ysong001 we'll use this ticket to lay out what we want to be able to pull out of the TDP db
