### ISSUE TITLE
As a UX researcher, I want a TDP demo environment

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1881]
**Description:**

**Acceptance Criteria:** 

- [ ] New pair of cloud.gov applications (tdp-frontend-research, tdp-backend-research)
- [ ] Users can use Login.gov in new environment 
- [ ] Environment has unique database
- [ ] Environment can upload data files
- [ ] Any feature branch can be deployed using "deploy-research" label
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Add new URIs to Login.gov prototype app
- [ ] Update documentation for environments
- [ ] Update Terraform configuration
- [ ] If applicable, update CircleCI configuration
- [ ] If applicable, update Github Actions
- [ ] Create new deploy-"research" label
- [ ] Add "research" to `scripts/update-ssh-configs.sh`
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by robgendron** [comment]
@andrew-jameson  is this still needed?

**Comment by lhuxraft** [comment]
Discuss on product sync - testing environment for STTs. Opportunity for beta paradigm from a research standpoint

**Comment by lhuxraft** [comment]
There's a workaround for this right now - TDP environment for STT testing is blocked by technical constraints, closing for now
