### ISSUE TITLE
As a developer, I would like a better deployment experience

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1891]
**Description:**
_Provide a brief background and justification for this issue_

The labels are inconsistent, and difficult to use. Github is not really a great interface for this.
If we deploy to our 4 dev environments the same way we deploy to our staging environments, with a filter to a branch with the same name as the environment we get a few things:

+ Better visibility into what code is deployed on what instance 
+ Easier (for a developer) deployments

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] When we merge into the branches `raft`, `qasp`, `sandbox`, or `a11y`, it deploys to the respective cloud.gov environment.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update circleCI workflow filters
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by stevenino** [comment]
Close as not a viable solution per backlog refinement on 8/16/22
