### ISSUE TITLE
[SPIKE] As a developer working on the frontend, I would like to be able to do my work with out starting the backend.

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1904]
**Description:**

We use Mirage to bypass our requirement for login.gov in our integration testing environments. Currently the way that it is set up is not very flexible and only allows us to test a subset of our apps features meaningfully. We discussed two options:

# Option 1: expand our use of mirage.js

As a tool Mirage can serve as a complete replacement for the backend (for the purpose of testing), with a simulated data base and sessions. 

With mirages data base and models, you can fully test every feature including file uploads and downloads correctly with out the backend.

Right now, the values are all randomly generated from faker.js So we can test that there are values there, but not reliable test if they are correct, or if any state changes are working correctly.

This would lead into proper integration testing of the frontend, since the desired result of this work is a 100% correctly functional mirage of the backend, with out cloud.gov, or django.

# Option 2: Remove backends local depdendence on login.gov with a flag

We could also run the fully deployed app, and add an option in the backend to use a username and password combination, or possibly by pass auth entirely. The objective I think is just a way to run the app and test it end to end without involving login.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_
- [ ] There is a way to run the app without login.gov
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create mock models that map to the models in django
- [ ] OR add flag to django
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- We mentioned backend has similar sort of issue, need to login with login.gov to do any development at all.
- The main issue is dependency on login.gov. This slows down dev and complicates future plans for integration testing.
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [_Mirage Models_](https://miragejs.com/docs/main-concepts/models/)
- [_Mirage Database_](https://miragejs.com/docs/main-concepts/database/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Maybe it is possible to solve this problem through django instead?
- _Open Question 2_

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

I'm not sure. Defer to dev team.

**Comment by robgendron** [comment]
Deemed no longer needed by Dev team.
