### ISSUE TITLE
Change required form field convention to use asterisks on Request Access form

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1906]
**Description:**
We're currently not providing any visual indication of "Associated STT" being required on the Request Access form. Since the form submits user data / can't easily be resubmitted we need a visual cue that it's required (as well as existing HTML attribute based identifiers that it's required). We've decided to use asterisks rather than "(required)" to make form field labels lest text heavy.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Paragraph text exists above form to note "Fields marked with an asterisk (*) are required.''
- [x] Asterisks are present on all three fields making up Request Access 
- [x] Asterisks are within the label attribute
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Deque guide to accessible identification of required fields https://dequeuniversity.com/tips/identify-required-elements
