### ISSUE TITLE
As a user who submits data files, I want to know if my file upload is empty. 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1916]
**Description:**
If a user uploads a file that is blank (no content), a 400 bad request error is returned upon clicking submit, but that is not a meaningful error message for the user. Additionally, the sys admin will not be able to see evidence of the bad request from TDP. cloud.gov logs is the only place where the 400 error is visible to the sys admin and even then admins will not know the root cause of the error. 

This ticket should deliver a more actionable error message to the user indicating that the file upload is empty. 

**Acceptance Criteria:** 
- [ ] when a user uploads an empty file, an error message indicating such is displayed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] update logic to conditionally display empty file error message to user if empty file submitted
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] inline message should read "The file uploaded does not contain any data. Please review this section and re-submit the data file."

**Notes:**
- Release 3.1

**Design**
- See attachment
- ![1916 - Data Analyst uploads an empty file - error message](https://user-images.githubusercontent.com/104451160/197866825-5f184760-54bd-4002-9221-893ac0f45bf9.png)

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

this can be closed. it has already been addressed (though im not sure which PR addressed it). screenshot below from test in staging today (4/30/24)
![blankfile_staging](https://github.com/raft-tech/TANF-app/assets/63075587/96081fd3-2561-47c0-b7e4-d8d7699d9b01)
