### ISSUE TITLE
As a sys admin, I want to be notified when a user submits an infected file 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1917]
**Description:**
#1215 will deliver an "infected" error message to user when a file with a virus is submitted. The sys admin can also see the infected status of every file submitted from the clamav file scans model in DAC, but admins should also be notified immediately when this occurs. 

![virusscan](https://user-images.githubusercontent.com/63075587/176192031-b646721d-94b4-4ea0-a8c3-83b5fdda27b2.PNG)

**Acceptance Criteria:** 
- [ ] When scan `result` = "infected", this triggers an "infected" email to anyone with sys admin role
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Release 4

**Open Questions:**
- What should the email content say? (`ux team`)

**Comment by lhuxraft** [comment]
Issue has not occurred since, closing
