### ISSUE TITLE
[SPIKE] As a team, we would like the site map to be dynamic.

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1943]
**Description:**

Follow on to #1787 

## Context 

In order to keep the site map accurate, it would be ideal if it updated in response to the structure of the website changing, otherwise it could very easily drift out of alignment with the website as it is built up over time. It didn't seem immediately obvious when implementing 1787 the best way to do this.

## Mission

 Research and maybe implement an automated way to generate the site map dynamically based on the routes available,
 considering not all routes are defined with in the react app that we want as a part of our site map.
 
  ## Technical considerations
  
 - not all elements in the site maps are react routes
 - not all users have permission to every element we expect in the site map
 - The location of the links is not the same
 - Multiple different components are used

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] A solution to creating the sitemap that will work for all possible route types, role, or component used to link to that page
- [ ] A list of edge cases and possible solutions to dynamically handling them
- [ ] Stretch: Working implementation depending on difficulty
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [ ] Working with the design team, look at the future of the sitemap to identify any other quarks in future paths.
- [ ] Experiment/investigate a solution that will consistently work for all future planned routes.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Should we be including links to pages that go outside of our app in the sitemap if so, how to represent them for dynamic inclusion in the site map?
- Maybe instead of dynamic site map, a good enough test that will fail if the site is not compliant.

**Comment by n0remac** [comment]
This could be a useful option 
https://docs.djangoproject.com/en/4.0/ref/contrib/sitemaps/

**Comment by riatzukiza** [comment]
Does the admin panel need any work to be compliant related to this?

**Comment by stevenino** [comment]
Closed as not required per backlog refinement on 7/12/22
