### ISSUE TITLE
As tech lead, I need all frontend app buttons in prod env to point to correct endpoints

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1945]
**Description:**
As of July 2022, the frontend and backend in the TDP prod environment are located in different domains. the frontend is in an acf domain, while the backend is in a cloudgov domain. The dev and staging env have not been configured to use multiple domains, so we need to ensure that all frontend buttons in prod hit the correct endpoints. 

currently when : 
```
BASE_URL: https://tdp-backend-prod.app.cloud.gov/v1
FRONTEND_BASE_URL: https://tanfdata.acf.hhs.gov
```
- the `request access` button at [tanfdata.acf.hhs.gov/home](tanfdata.acf.hhs.gov/home) does not work. 
- the `submit data files` button at [tanfdata.acf.hhs.gov/data-files](tanfdata.acf.hhs.gov/data-files) does not work. and returns a `403 error`
- the `sign out` button for users with an acf email address redirects to and acf-ams page that returns a  `Invalid redirect uri` and does not successfully logout on first attempt. (_this button functions properly for non-acf email addresses._)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] request access button at tanfdata.acf.hhs.gov/home functions properly. 
- [ ] users with appropriate permissions can submit data files via submit data file button
- [ ] all acf and non-acf users can sign out properly from frontend
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] reproduce issues in description
- [ ] fix buttons
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- [swagger](https://tdp-backend-prod.app.cloud.gov/swagger/) was used to submit data files to ensure that download button on frontend was functioning properly. [common.py](https://github.com/ADPennington/TANF-app/commits/master) needed changes to facilitate this. 
- frontend sign out button
![1945](https://user-images.githubusercontent.com/63075587/178595009-8c20bc9f-fbb2-45bb-8eb7-ca7184bef120.PNG)

**Comment by ADPennington** [comment]
@riatzukiza the [master branch on my fork](https://github.com/ADPennington/TANF-app/tree/master) is now ready for testing.

- I updated it by first renaming `main` and `master` to `main_archive_20220719` and `master_archive_20220719` (in case you need it for reference)  and created new versions based on most recent merges to hhs repo. 
- Note [this comment](https://github.com/raft-tech/TANF-app/issues/897#issuecomment-1190213094) re: `ALLOWED_HOSTS`.

**Comment by andrew-jameson** [comment]
We have split off related documentation and clean up work into #2031, #2032, and #2038. These changes have been merged into HHS:master and is now live in production.
