### ISSUE TITLE
As tech lead, I need production Login.gov variables scripted in deployments

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1951]
**Description:**
Per dev sync 7/13, we need to adapt certain Login.gov values from their sandbox environment to their production sites.

**Acceptance Criteria:** 
- [ ] Deployments for production environments are able to use new Login.gov site values
- [ ] Ensure dev/staging deployment behavior are unchanged
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Append Login.gov variables from [here](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/settings/common.py#L342) to our deployment [here](https://github.com/raft-tech/TANF-app/blob/develop/scripts/deploy-backend.sh#L35)
- [ ] Test production deployments are successful using @ADPennington 's fork [here](https://app.circleci.com/pipelines/github/ADPennington/TANF-app)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Will need Alex to give assignee permissions in her fork
