### ISSUE TITLE
As a developer, I'd like to use a task queue to handle sending notification emails

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#1952]
**Description:**

Follow on to #1784
After validating the network settings allowing us to send emails from cloud.gov, we decided not to implement it as a django view, but in a celery task. 

Will require functioning celery service to implement this ticket correctly

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Emails are sent from a task queue asynchronously and do not block our django process
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create a class/set of functions for sending emails through the task queue
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**

https://docs.djangoproject.com/en/4.0/topics/email/
https://docs.djangoproject.com/en/4.0/ref/settings/#std-setting-EMAIL_USE_SSL
https://docs.djangoproject.com/en/dev/ref/templates/api/#loading-a-template
```python
from django.core.mail import send_mail

send_mail(
    'Subject here',
    'Here is the message.',
    'from@example.com',
    ['to@example.com'],
    fail_silently=False,
)

```

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
