### ISSUE TITLE
As tech lead, I want us to implement storage solution for non-code files

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#1956]
**Description:**
As an industry best practice, we need to shift off using our github repo for binary files (aka, non-code, non-documentation files). It should be a simple integration to utilize [Git LFS](https://git-lfs.github.com/) as opposed to an artifact file server like [Nexus](https://www.sonatype.com/products/nexus-repository) or [Artifactory](https://jfrog.com/artifactory/) although both of those options are viable for other uses like self-hosting images, packages, or docker hub but there's a maintenance trade-off.

**Acceptance Criteria:** 
- [ ] Binary files are able to be transitioned out of the github repo explicitly
- [ ] Any static/flat files used by the application can be easily/automatically pulled during build-and-test CircleCI workflow
- [ ] New solution (LFS or other) is done in a secure manner but also accessible to the team
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Standup a storage solution (LFS, Nexus, Artifactory)
- [ ] Migrate binary files to this storage solution
- [ ] Ensure all links/references allow `build-and-test` operations
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- Background images on splash page
- `tdrs-frontend/src/assets/`
- logos/icons

**Supporting Documentation:**

- [Self-hosted LFS](https://blog.dermah.com/2020/05/26/how-to-be-stingy-git-lfs-on-your-own-s3-bucket/)
- 

**Open Questions:**
NA

**Comment by lhuxraft** [comment]
Nexus is already set up, will revisit improvements at a later time

**Comment by andrew-jameson** [comment]
Per an internal conversation within raft w/ @vlasse86 and others, Nexus will not be tenable moving forward and we will have to downgrade our pipelines suffering reliability costs or look to free alternatives. A new solution for some files can be found within [Github's Packages feature](https://docs.github.com/en/packages/quickstart) but it appears we will be moving to LFS.

cc @elipe17 @lhuxraft

**Comment by lhuxraft** [comment]
Replaced by #3498
