### ISSUE TITLE
As a Pilot STT, I need to be able to submit data for FY2022

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1957]
**Description:**
Currently STTs can only submit data files FY2020 and FY2021. Because pilot users for v2.0 will be submitting data for FY2022 (i.e. Q3 of FY2022, we need to add an additional year to the fiscal year dropdown menu. 

**Acceptance Criteria:** 
- [x] Users can submit data files for FY2022
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] update source of data_file `year` metadata for dropdown menu to include 2022
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- current dropdown view
 ![1957](https://user-images.githubusercontent.com/63075587/179070320-f7493a3c-e21e-4eac-9bd5-eaee7c84b4ef.PNG)

**Comment by n0remac** [comment]
I can statically add a new year, or make a function that always gives the current year.

**Comment by n0remac** [comment]
note for me. In Dec 2022 the year 2023 should show
