### ISSUE TITLE
[Dev-ready Design] Data Submitted email template to incorporate data into a table format

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#1960]
Related to story #1845 

—As a [active Data Analyst] I want the email to be structured in a scannable format so that I can get the information I need quickly.—

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories - dev ticket #1845
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Build into the html email template directory
- [x] Tag for A11y review (Thomas) 

**Supporting Documentation:**

- [Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-has-been-submitted.html)

**Comment by reitermb** [comment]
@ttran-hub Hi Thomas, we have a mini a11y review ready for this work (adding some data that was in a list to table form instead. Should be a straightforward one! Test environment link here: https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-has-been-submitted.html

cc: @ADPennington

**Comment by ttran-hub** [comment]
> @ttran-hub Hi Thomas, we have a mini a11y review ready for this work (adding some data that was in a list to table form instead. Should be a straightforward one! Test environment link here: https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-has-been-submitted.html
> 
> cc: @ADPennington

@reitermb a11y looks good. 🚀 Not a11y related, please update Section 2 text to Section 2 (Closed Case Data). Thanks.   cc @ADPennington 
![image](https://user-images.githubusercontent.com/61292479/194091471-8f11e23a-6839-4c76-a4df-a0bb95711528.png)

**Comment by stevenino** [comment]
@reitermb please make the section 2 description as called out. Thank you!

**Comment by reitermb** [comment]
> @reitermb please make the section 2 description as called out. Thank you!

Fixed!

**Comment by reitermb** [comment]
> > @reitermb please make the section 2 description as called out. Thank you!
> 
> Fixed!

cc @ADPennington @ttran-hub

**Comment by ADPennington** [comment]
> > > @reitermb please make the section 2 description as called out. Thank you!
> > 
> > 
> > Fixed!
> 
> cc @ADPennington @ttran-hub

thanks @reitermb closing as completed. 👍🏾
