### ISSUE TITLE
Approved-user TDP homepage

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1965]
**Description:**
Replaces the current placeholder content (readout of user permissions) with a new copy, a reminder highlighting the reporting deadlines for the year, and featured resources from the unauthenticated TDP homepage.

**Acceptance Criteria:** 
- [x] Update "Next Reporting Deadline" to "Data Reporting Deadlines"
- [x] Reporting deadline table presented, see reference table in supporting documentation
- [x] Resource cards are present on "Home"
- [x] User permissions are no longer visible
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
- [x] Hardcode the new deadline content, display the entire reporting deadline table
- [x] If possible, reference the resource cards content with an abstraction instead of duplication
- [x] Remove the permissions listing
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
**Supporting Documentation:**
https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=7059%3A49955

<img width="824" alt="image" src="https://user-images.githubusercontent.com/28515874/179604166-112712b3-42fb-46c7-9e07-1b1e94253956.png">

Next Reporting Deadline formatting:
![image.png](https://images.zenhubusercontent.com/63b84eea1f4c6195ccac7523/02443834-a9e2-4949-8b14-9e93e057a703)
Note: Table should be built in app using USWDS/HTML styles/markup. See Submission History for example. 
This includes making sure the "Reporting Deadlines" heading for the table is marked up as the table caption rather than as a separate <p> or <heading> element 

**Open Questions:**

**Comment by reitermb** [comment]
Notes from cross-sync 1/6/20223

Revisit/clarify whether to include featured resources section on interim states (pending access request) of the TDP homepage as well as the "final" approved user welcome state when we bring this onboard

**Comment by n0remac** [comment]
@reitermb the note in the Figma seems to indicate that the date should be updated based on the current date and quarter, similar to what I did with the drop down on the file submission page. But the note at the end of the ticket says to implement the table.  I assume you want the date to update dymanically?

**Comment by ADPennington** [comment]
per tabletop today, it sounds like this ticket was written for our STT end users (Data Analysts), and not for our other users: OFA Admin, OFA Sys Admin, ACF OCIO, etc. So any approved user that isnt a data analyst will see this home page and the message may not be quite right  (e.g. OFA sys admins cannot submit data). 

Noting this for awareness. we need to clean this up eventually.  @Smithh-Co @reitermb @lfrohlich @ttran-hub

**Comment by lfrohlich** [comment]
@lilybl1

**Comment by lilybl1** [comment]
@n0remac One minor edit, in the table there is a misspelled word please change from "calandar" to "calendar". I also checked voiceover and tabbing - all looks good. Thank you!
