### ISSUE TITLE
As an authenticated user that has been inactive for 30 minutes, I want to be notified to extend or end my session

### ISSUE THREAD

**Issue by lauraGgit** [raft-tech/TANF-app#197]
Description:
After 20 mins of inactivity, an authenticated user is served a notification that their session is about to end and provided options to extend or end their session. This issue will ensure the notification is served. 

**Acceptance Criteria:** 
- [ ] After 20 mins of inactivity, user gets notified that their sessions is about to expire. 
- [ ] Notification contains options to extend or end the session
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

Frontend
- [x] Create activity timer
- [x] Create alert box
- [x] Create buttons for alert box
- [x] Display alert box after 20 minutes of inactivity
- [x] Write necessary tests
- [ ] Review alert box with UX to ensure it matches TDP.
- [ ] Create a new issue to tweak the mockup, if necessary

Backend
- [x] Set timeout in authorization cookie
- [x] Reset the cookie on authorized API requests
- [ ] Add necessary tests

**Notes:**
- Session end or extension will be managed by #278
- 15 mins is driven by NIST 800-63 AAL2/3 guidelines on session timeouts. However, based on the discussion with OCIO and FISMA moderate system ACF guidelines, the timeout will be for 30 mins. 
   -- Penyin will share (see also Appendix X, list of controls). (15 minutes for high risk, 30 minutes for moderate)
- We will have a 30 minute session timeout on the backend, so the user will be logged out of the back end and the session destroyed if there is no activity. The front end will monitor activity as described in the link above. At some point before 30 minutes (TBD) the front end will prompt the user to either extend or end the session. If no selection is made the front end will automatically end the session at 30 minutes.

- Session max age (re-authentication) is being managed by #333

**Supporting Documentation:**

- The feature should the follow [WCAG guidelines](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable)
- usajobs inactivity notification
![inactivity notification.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/2e36303e-4ca8-40dc-8948-b239d3a1c5a0)

**Open Questions:**

- Design for the user notification has not been finalized yet. Confirm whether notification can be designed similar to usajobs screenshot. 
- Notification details have not been finalized (e.g., length of time before session expires, setting expectation on unsaved data) 
- Is there a session max age (reauthentication)?

**Comment by iamjolly** [comment]
Related note: Per WCAG/508 ([SC 2.2.1 Timing Adjustable - Level A](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable)), we need to ensure folks have a way to extend their session and not just log out after 15 mins without warning.

**Comment by shubhi-raft** [comment]
need to break these down into two issues - user is served warning and used is logged out.

**Comment by shubhi-raft** [comment]
For sprint 6, this issue will only be tasked out.

**Comment by lfrohlich** [comment]
Reframe as Epic for Sprint 7?

**Comment by lfrohlich** [comment]
This was merged 11/25/20
