### ISSUE TITLE
[Research Facilitation] Workshop policy/decisions on the number of fiscal years to surface in TDP

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1972]
**Description:**
Decide the number of fiscal years needed to be available/made resubmittable within TDP. See also #120 — consolidate w/ this ticket?

**AC:**

- [ ] Research sessions have occurred.
- [ ] Anonymized session notes or other top-line synthesis have been documented.
- [ ] Changes to recruitment criteria have been documented if recruitment/target participant pool has been expanded.

**Notes:**
Do grantees need some in-between state of submitted late / outside of acceptance/rejection/feedback process

		○ There are standard cases for how long we should retain data and then exceptional cases like "We discovered a massive problem with data from 2015 that needs to be fixed" 
			▪ Flip-ability of a switch to allow submission for edge cases like this?
			▪ Currently somebody could submit something to the wrong quarter and even if it errors we would have the file.
			▪ Also possible we could invest in some generic edge case file upload bucket (enabled for specific STTs on demand?) "Open a late data submission ticket" kind of flow?
			▪ Does this relate to the ask from some folks we've heard of "can we test our files without actually submitting?" -- We have a few folks doing this via staging
		○ Beyond 4.0 priority
		○ Look into whether we have additional related tickets already for some of this -- Data retention policy
			▪ #1288 Updated SORN with backup retention policy
#2267 As a grantee, I want to see 5 years of data submission history

#1288 
#2267 

**Tasks:**

- [ ] Meeting with DIGIT & Andrew
- [ ] Determine # of years to show/migrate in TDP
- [ ] Determine how many years to allow resubmission 

**Supporting Documentation:**

- *---Link to hack.md, Mural, or other relevant top-line documentation materials---*

**Comment by stevenino** [comment]
This is a policy decision that will be driven by the outcome of a conversation with DIGIT. Extensive research is not required

**Comment by reitermb** [comment]
Good ground for UX Sync w/ Lauren. Discuss 3-5 years (forward) for data surfacing.

**Comment by reitermb** [comment]
Likely closable, also added to future UX sync discussion to confirm

**Comment by reitermb** [comment]
Discussed in prod sync on May 3, revisiting, refining. 
Target ~ Beyond 4.0

**Comment by reitermb** [comment]
Closing after consolidating with #120
