### ISSUE TITLE
As system owner, I want to add a vulnerability disclosure policy link to TDP frontend

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#1979]
**Description:**
Per #753, the prod TDP system will be covered by the [HHS Vulnerability Disclosure Policy](https://www.hhs.gov/vulnerability-disclosure-policy/index.html) after HHS' Synack assessment team and  ACF OCIO verifies the security state of the system. 

This vulnerability scan is expected to be completed by August 2022, and if any issues are identified, we must remediate them prior to being added to this policy scope. 

After TDP has been added to scope, we will add a link to the HHS VDP to the footer of the TDP frontend pages. 

**Acceptance Criteria:** 
- [x] A link is present on "All known major entry points (regardless of whether PII is collected)" of the website
- [x] The link directs the user to https://www.hhs.gov/vulnerability-disclosure-policy/index.html in a new tab
- [x] Link is named "Vulnerability Disclosure Policy"
- [x] include link in site map
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Add VDP link to footer
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [related footer work](https://github.com/raft-tech/TANF-app/pull/812)
- _TDP footer_
![vpd](https://user-images.githubusercontent.com/63075587/180075104-657173b6-25a0-4124-ba6a-5da19cc24b59.PNG)

**Comment by ADPennington** [comment]
### 8/8/2022 update from OCIO's Synack team: 

 - No vulnerabilities were found on TDP prod. 🚀 
 - They've requested that we add the VPD link, so we need to discuss prioritizing this ticket at backlog refinement mtg @stevenino 

cc: @tdrammeh1 @AiseosaO

**Comment by raftmsohani** [comment]
![Screen Shot 2022-09-02 at 9.25.57 AM.png](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/02b353d1-d65c-4d0e-83c6-29885c766a1e)

**Comment by lilybl1** [comment]
@raftmsohani Let us know how the capitalization of the Policy goes. Thanks!

**Comment by stevenino** [comment]
@ttran-hub have you had a chance to look at this yet?
