### ISSUE TITLE
Define User Research Process

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#20]
Description:
Define what an iterative process for conducting user research will look like.  

AC: 
- [x] Identify who provides approval for iterative rounds of user research 
- [x] Identify what is needs to submitted to seek approval for user research
- [x] Any concerns for structured vs unstructured research
- [x] Identify who creates and provides privacy statement
- [x] Identify PRA concerns (max participants not to exceed)
- [x] Identify user recruitment lead time
- [x] Get access to research debriefs of preciously conducted session(s) 
- [x] Confirm using lookback.io for usability testing sessions or identify an alternative
- [x] Identify how feedback is documented and shared with the team
- [x] Determine whether audio and/or video recording can be made of the sessions

Tasks: 

- [x] Get access to Spring 2020 research feedback
- [x] Get access to research debrief

Open Questions:
1. Is the process for iterative user research been defined? 
2. Is the timeline different for structured vs unstructured research?

**Comment by lfrohlich** [comment]
This looks good to have these conversations soon.

**Comment by shubhi-raft** [comment]
based on the discussion w/ @cmajel the estimate and labeling has been updated.

Here is what we discussed/found:
- no 'formal' approval is needed from any other office/division; @lfrohlich needs to be in the loop and will provide the approval and help recruit participants for user research cycles
-  no particular concerns around structured vs unstructured research. Method will depend on the research goal(s).  
- @lfrohlich will help with updating/modified the privacy statement as needed. Raft will build off of the privacy statement used in the previous (fall and spring) research sessions.
- No more than 9 participants to be recruited per research cycle to address PRA concerns. If additional participants sign up or are made available, then they can be possibly recruited for a future session
- Recruitment lead time is usually a week for States but may be longer for tribes; 
- Raft has access to research synthesis. Verbatim notes have not been shared. 
- Participants do not use Chrome so lookback.io or any tool that requires chrome extension may not be feasible to use. Alternatives are WebEx, Hangout, or Zoom. Have to figure out and dry run how screen sharing and feedback on prototype will work? 
- Research synthesis feedback is document as stated in [wiki]( ) and will be anonymized due to privacy concerns
 
Q: @cmajel - In addition to the note taking, is it ok to record the testing session?

@lfrohlich could review the notes and see if this issue can be closed? 
@reitermb - FYI

**Comment by lfrohlich** [comment]
All of these answers look right to me. I don't think there is any issue with recording sessions as long as we ask for permission. Some participants may use Chrome but we cannot count on it. 
Fine with me to close.

**Comment by cmajel** [comment]
Adding some closing thoughts here:

* Re recording
  * it's something we can do if we get permission, offer an opt out, have a secure place to store that is only accessible by the research team, and a plan for deletion. I've done recordings depending on the context; they can be helpful for doing note clean up, but they have a short half life and can make some participants uncomfortable. 
  * @lfrohlich you able to control access to files within Teams? I tried creating a [test folder / doc](https://teams.microsoft.com/_#/files/Design?threadId=19%3Ae92913e3e7d443adb823e6497dff1fb3%40thread.skype&ctx=channel&context=Access%2520test%2520folder) and it's not clear to me if people outside the #design channel or our team can view it. 

* As context, my colleague working with OHS had very similar experiences about approvals and panel sizes.

**Comment by lfrohlich** [comment]
Tasks complete. Closed
