### ISSUE TITLE
[Research Facilitation] Pilot Program (Moderated and Unmoderated Session Support)

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2015]
**Description:**
The pilot program will begin on 8/8-8/15 with 15 participants (5 moderated and 10 unmoderated). 

**AC:**
- [ ] 8/1 - Conduct Information Session 
- [ ] Research sessions have occurred between 8/8 - 8/15 - see [sign-up](https://teams.microsoft.com/_#/xlsx/viewer/teamsSdk/https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA-UserResearch~2FShared%20Documents~2FUser%20Research~2FPilot%20V2.0~2FTDP%20Pilots%20Participants%20Tracker.xlsx?threadId=19:3bb622256c0b4792976dc5f1f4654fca@thread.skype&subEntityId=%257B%2522web%2522%253A%2522https%253A%252F%252Fhhsgov.sharepoint.com%252Fsites%252FTANFDataPortalOFA-UserResearch%2522%252C%2522list%2522%253A%2522https%253A%252F%252Fhhsgov.sharepoint.com%252Fsites%252FTANFDataPortalOFA-UserResearch%252FShared%2520Documents%2522%252C%2522folder%2522%253A%2522%252Fsites%252FTANFDataPortalOFA-UserResearch%252FShared%2520Documents%252FUser%2520Research%252FPilot%2520V2.0%2522%257D&baseUrl=https:~2F~2Fhhsgov.sharepoint.com~2Fsites~2FTANFDataPortalOFA-UserResearch&fileId=22213866-1b2f-44ee-9af9-1609a41bc631&ctx=openFilePreview&viewerAction=edit) section
- [ ] Anonymized session notes or other top-line synthesis have been documented

**Tasks:**
- [ ] *---Aggregate notes from research sessions---*

**Supporting Documentation:**
- *---Link to hack.md, Mural, or other relevant top-line documentation materials---*
