### ISSUE TITLE
[Dev-ready Design] Update TDP admin spec

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#203]
**Description**
Delivers updated TDP admin mockups in Figma to improve a11y and update design elements that need to be changed due to decisions made since the original mockups were reviewed. 

**Related User Stories:**
- As an OFA regional staff member I want admin controls in TDP to manage user access in my region

**Recommended pa11y actions:**
- *---'click element #error-report',---*

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Notes**
Role dropdowns in existing spec may go away in favor of a more binary approve/don’t approve given that we now think there are fewer user roles needed for grantee users than we did earlier on in the project—could be dependent upon whether a given request is from a grantee user or somebody else at OFA.

**Tasks**
- [ ] Update UI elements in Figma to align to more recent product decisions & ensure better accessibility (e.g. left aligned buttons to better adhere to proximity best practices) 
- [ ] Design:Dev handoff sync

**DD**
- [ ] Documentation: [Figma ](url)page has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Comment by reitermb** [comment]
As per the last dev discussion we had it's also worth noting that it would take some degree of extra effort to allow Admins to edit user properties (like STT). We can definitely do that (we had an earlier stage mockup that did so prior to that discussion), but it sounded like it won't be free dev wise. 

To float another option (and not necessarily suggest it) if we're looking to ruthlessly prioritize we could simply not allow STT to be modified on the front-end. That would mean that if a user mistakenly picks the wrong one and needs to correct it, or somebody moves and still happens to be doing TANF work in a different STT (Are we aware of any time when this has happened?), it would be a dev ticket rather than an admin task.

**Comment by abottoms-coder** [comment]
Repurposing this to update figma mock ups for Profile and AdminUI pages as per #239

**Comment by valcollignon** [comment]
Updated title during backlog refinement 11.30.21. Will refine AC further during upcoming UX refinement session.
CC: @reitermb @sreedevip

**Comment by reitermb** [comment]
#1679 — Backlog 3/8/2022, UX method needed to deny access request in admin UI. Either as part of this ticket or a parallel one.

**Comment by reitermb** [comment]
I believe this is V4 given more recent conversations around release slicing? To follow up on in backlog

**Comment by lhuxraft** [comment]
Close and spin up a new ticket if needed once we finalize regional staff UI big picture. Ticket record is documented in Figma
