### ISSUE TITLE
As a developer, I'd like good documentation for our cross origin code

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#2031]
**Description:**

With how far apart all of the changes for #1945 were in the code base, there should be a thread connecting them all together. The Nginx is very poorly documented, and we interact with it very rarely, so we never thought to check there.

We want to make a readme for the nginx configs, and some comments in the related django and react code that will link developers from the distant parts of the code to a single document explaining how they are connected.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] There is a readme that explains our nginx config and what it does for cross origin headers
- [ ] The django common settings we set for django admin panel have comments directing you to the nginx readme
- [ ] The frontend cookie code gets comments pointing to the nginx readme for details.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Write the readme using the provided notes as a guide
- [ ] Add comments in code where ever network strangeness occurs pointing to document
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- https://hackmd.io/@Erronous/Sk83XFO2q

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://content-security-policy.com/connect-src/
- https://content-security-policy.com/examples/blocked-csp/
- https://docs.djangoproject.com/en/3.0/ref/csrf/

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
