### ISSUE TITLE
As tech lead, I want local configurations to use nginx

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2032]
**Description:**
As we uncovered in #1945, our development docker images do not use nginx for the frontend. We should use nginx so that we can more closely mimic production in our development processes.

**Acceptance Criteria:** 
- [ ] Using our dev aliases, `tdrs-start` will spin up the frontend with nginx
- [ ] The nginx configurations for local and prod are functionally equivalent
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Investigate use of nginx docker base
- [ ] Set docker-compose configurations to ensure reactjs and nginx are spun up seamlessly
- [ ] Match local nginx cfg to production nginx cfg
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/Architecture-Decision-Record/011-buildpacks.md

**Open Questions:**
- Should we just reactjs run inside an nginx docker image similar to our buildpack architecture? While we would have to run through some setup steps, this feels like the 'best' solution but I'm unsure of the lift to get that work done and how that might impact scope.

**Comment by andrew-jameson** [comment]
This will be just for local dev nginx configs and use of hosts files and/or domains will be split off into another ticket.

**Comment by andrew-jameson** [comment]
Per dev meeting 10/27, this is now obsolete. Finished in #1544
