### ISSUE TITLE
[DRAFT] CSRF/CORS issues w/ staging

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2038]
**Description:**
As scope has grown for #1945, this will be a follow-on ticket to fully diagnose and resolve the cross-domain issues within staging.

**Acceptance Criteria:** 
- [ ] Production environments utilizing `*.acf.hhs.gov` domains retain frontend button functionality (login, request access, admin panel)
- [ ] Non-production environments utilizing `*.app.cloud.gov` domains retain their previous functionality (login, request access, admin panel)
- [ ] CORS best practices are implemented
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Diagnose root cause of issues w/ staging and why the production changes introduced broke cloud.gov comms
- [ ] Implement CORS best practices, refactor relevant Django code
- [ ] Refactor relevant ReactJS code for setting cross-domain cookies
- [ ] Write holistic documentation on why certain values are set/not set (understand and justify each line added via 1945)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Django CORS](https://github.com/adamchainz/django-cors-headers)

**Open Questions:**

- Why did 1945 changes resolve original issue? Are all needed?
- What defaults exist for both frontend and backend? 
- Why did our custom backend middleware seem to break cloud.gov comms?
