### ISSUE TITLE
As TDP Sys Admin, I need nightly owasp scan artifacts copied to production backend

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2054]
**Description:**
Since #1754 was merged into `HHS/TANF-app:master` successful nightly scan reports do not appear in DAC. There are currently no reports in prod. See evidence [here](https://github.com/raft-tech/TANF-app/issues/2054#issuecomment-1213474067). 

These reports are not being copied to production backend in DAC because the repository that these artifacts are saved in is hard-coded in [`process_owasp_scan.py`](https://github.com/raft-tech/TANF-app/blob/4852f108f79e5cbb0b954cc8abbeaa5483bc5170/tdrs-backend/tdpservice/security/management/commands/process_owasp_scan.py#L55). `project-slug` should = `HHS/TANF-app` for production (and staging). 

**Acceptance Criteria:**
- [ ] Successful production owasp nightly scan reports are saved in production backend (i.e. `https://api-tanfdata.acf.hhs.gov/admin/security/owaspzapscan/`) 
- [ ] Successful dev and staging nightly scan reports are saved in respective non-prod backends
- [ ] Errors are raised when artifacts cannot be copied to backend environment. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] update `process_owasp_scan.py` (re: project slug , error-handling)
- [ ]  Run Testing Checklist and confirm all tests pass

**Notes:**
- [original implementation of nightly owasp scan storage](https://github.com/raft-tech/TANF-app/pull/1340)
- see investigation notes [here](https://github.com/raft-tech/TANF-app/issues/2054#issuecomment-1216985625)
- this problem also applies to staging deployments from `HHS:main`

**Comment by ADPennington** [comment]
**Evidence collected on 8/12/2022 4p EST**

_nightly scan metrics_
<img width="1352" alt="Screen Shot 2022-08-12 at 3 47 34 PM" src="https://user-images.githubusercontent.com/63075587/184433027-8090907c-5850-410a-ab70-cb31dd4c2c44.png">

_traceback for failed scan_
```
================== OWASP ZAP tests ==================
Config file found
Creating tdrs-backend_zaproxy_run ... 
ERROR [Errno 5] Failed to connect to ZAP after 600 seconds
2022-08-11 00:23:31,942 I/O error: [Errno 5] Failed to connect to ZAP after 600 seconds
Traceback (most recent call last):
  File "/zap/zap-api-scan.py", line 386, in main
    wait_for_zap_start(zap, timeout * 60)
  File "/zap/zap_common.py", line 317, in wait_for_zap_start
    raise IOError(
OSError: [Errno 5] Failed to connect to ZAP after 600 seconds
Found Java version 11.0.15
Available memory: 7820 MB
Using JVM args: -Xmx1955m
```

_successful scan reports saved in HHS CircleCI_
<img width="928" alt="Screen Shot 2022-08-12 at 4 03 04 PM" src="https://user-images.githubusercontent.com/63075587/184434476-2d3f1136-92b2-4248-96b7-e434029f3dae.png">

<img width="1074" alt="Screen Shot 2022-08-12 at 4 04 00 PM" src="https://user-images.githubusercontent.com/63075587/184434499-45a5805e-7d2c-4b7c-a4f0-ae13e75b02b9.png">

<img width="1238" alt="Screen Shot 2022-08-12 at 4 03 30 PM" src="https://user-images.githubusercontent.com/63075587/184434510-df8d70c6-cd28-4646-afa0-a9ca0d809f50.png">

_DAC owasp app as of 8/12/2022 with no reports for successful scans_
<img width="1350" alt="Screen Shot 2022-08-12 at 3 46 14 PM" src="https://user-images.githubusercontent.com/63075587/184434586-4cefeb6e-174b-4b5d-ac6d-01cdcd8dcbb8.png">
