### ISSUE TITLE
[Research Synthesis] Pilot Research Synthesis

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2058]
**Description:**

Delivers a written synthesis of 2.0 Pilot Research

**AC:**

- [ ] A hack.md with the drafted synthesis has been reviewed.
- [ ] PR has been opened containing the final draft of the synthesis.

**Tasks:**

- [x] Aggregate notes from research sessions
- [x] Draft hack.md (Document synthesis)
    - [x] Scope (research goal(s)
    - [x] High-level findings
    - [x] Actionable learnings
    - [x] Takeaways for future research
- [ ] Delete raw video recording(s) once notes are compiled
- [x] Write up Project Updates (audience Regional staff) high level
- [ ] Open PR for synthesis writeup

**Supporting Documentation:**

- [Draft](https://hackmd.io/@Sola0TsrTQ-Bk5-4MR5wOA/ryrx9EpA5/edit)

**Comment by lilybl1** [comment]
@ADPennington This is ready for a first review -  take a look at the Draft link to the Research Synthesis and Project Update. The Project Update is added at the end of the synthesis to keep things in one place to review. We will separate these out for production. Thank you!

**Comment by ADPennington** [comment]
this is back in qasp.

**Comment by ADPennington** [comment]
@reitermb @lilybl1 left a few final comments that need to be addressed before this is merged. i made inline minor edits for clarity and to save time. this looks good. im not able to comment on the project updates but it looks good too.

**Comment by reitermb** [comment]
> @reitermb @lilybl1 left a few final comments that need to be addressed before this is merged. i made inline minor edits for clarity and to save time. this looks good. im not able to comment on the project updates but it looks good too.

Thanks @ADPennington! I'll take a look and work those into the PR

**Comment by stevenino** [comment]
@ADPennington ready to go back to QASP

**Comment by stevenino** [comment]
Related PRs are closed
