### ISSUE TITLE
As gov tech lead, I need prod jwt keys rotated for login.gov

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2073]
**Description:**

Login.gov jwt keys in prod env are due to expire on 9/1/2022. These need to be rotated at least every 90 days. New public and private keys need to be generated and tested prior to submitting a change request to login.gov support. 

![jwtprod](https://user-images.githubusercontent.com/63075587/185628877-fb7301bc-e4ad-42e0-9e97-e8669113d1ad.PNG)

This ticket will track this work. 

**Acceptance Criteria:** 
- [x] _non-ACF users can login via grantee button after 9/1/2022_
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] rotate keys
- [x] add new cert to login dashboard for prod 
- [x] update env variables for login in cloud.gov and use sandbox endpoint to verify keys work properly in prod. 
- [x] revert changes to jwt key and cert
- [x] Run Testing Checklist and confirm all tests pass
- [x] submit change request to login.gov support
- [x] verify change request completed. 

**Notes:**
- prod may experience downtime

**Supporting Documentation:**
-  [rotation steps](https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/secret-key-rotation-steps.md)

**Comment by ADPennington** [comment]
### 8/23/2022 Update

successfully tested new keys in production. steps followed for future reference:
- ran `production-deployment` workflow from HHS circleci to ensure apps are in qasp-approved state
- updated the following env vars via `cf tdp-backend-prod set-env...` and restaged:
```
JWT_CERT # new cert
JWT_KEY # new key
OIDC_OP_ISSUER # using login.gov sandbox domain
OIDC_OP_AUTHORIZATION_ENDPOINT # using login.gov sandbox domain
OIDC_OP_JWKS_ENDPOINT # using login.gov sandbox domain
OIDC_OP_TOKEN_ENDPOINT # using login.gov sandbox domain
OIDC_OP_LOGOUT_ENDPOINT # using login.gov sandbox domain
```
- used grantee button to test login.gov sign-in with 2 different non-acf email addresses. successfully redirected to to request form and was able to submit a request. 
  - **Noticed a bug with the frontend logout for non-ACF users (this was observed with existing and new keys). it is pointing to `https://api-tanfdata.acf.hhs.gov/v1/logout/oidc` which is not included in our list of redirect URIs in login.gov dashboard. I added and tested it but it is still not working. trying it again is needed for a successful logout. will spin up a bug ticket for this**
```
    # first try:
09:56:41.066: [APP/PROC/WEB.0] [2022-08-23 13:56:41 +0000] [561] [DEBUG] GET /v1/logout/oidc
09:56:41.067: [APP/PROC/WEB.0] ERROR Unsafe redirect to URL with protocol 'ttps'
09:56:41.067: [APP/PROC/WEB.0] Unsafe redirect to URL with protocol 'ttps'
09:56:41.083: [APP/PROC/WEB.0] WARNING Bad Request: /v1/logout/oidc

   # second try:
09:58:49.208: [APP/PROC/WEB.0] [2022-08-23 13:58:49 +0000] [563] [DEBUG] GET /v1/logout/oidc
09:58:49.222: [APP/PROC/WEB.0] 10.255.41.16 - - [23/Aug/2022:13:58:49 +0000] "GET /v1/logout/oidc HTTP/1.1" 302 0 "https://tanfdata.acf.hhs.gov/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
09:58:49.221: [RTR.2] api-tanfdata.acf.hhs.gov - [2022-08-23T13:58:49.199171912Z] "GET /v1/logout/oidc HTTP/1.1" 302 0 0 "https://tanfdata.acf.hhs.gov/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" ... ... ...
09:58:49.344: [APP/PROC/WEB.0] 10.255.41.16 - - [23/Aug/2022:13:58:49 +0000] "GET /v1/logout HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
09:58:49.328: [APP/PROC/WEB.0] [2022-08-23 13:58:49 +0000] [561] [DEBUG] GET /v1/logout

```
- re-ran `production-deployment` workflow from HHS circleci (thinking this would overwrite the abovementioned env var changes. it didnt 😞 )
- reset env variables and restaged
- signed in to TDP prod to ensure apps were reverted back to qasp-approved state
- submitted change request to login.gov  (ticket # 1131)

**Comment by ADPennington** [comment]
login.gov pushed the new cert to production. will verify the new key works tomorrow 9/2 morning.

**Comment by ADPennington** [comment]
#### 9/2 Update

verified that new keys are working in prod. Notes for steps followed below. 

1. sign into prod via login.gov on 9/2, since pre-existing cert expired on 9/1. checking if pre-existing jwt keys work.  

   > sign-in successful. 

2. restage `tdp-backend-prod` and try step 1 again. 

   > sign-in successful. 

   > per login.gov support ticket # 1131, any certs (including those that have expired) in the dashboard are not removed until requested. this explains why its still working. 


3. update  `JWT_CERT` and `JWT_KEY` in `tdp-backend-prod` with unexpired versions and restage. 

   > sign-in successful. 

3. re-deploy  latest qasp-approved code (v2.0.1) from HHS CircleCI with _expired_ versions to verify these keys still work. 

   > sign-in successful. 

4. HHS CircleCI has, to-date, not stored `PROD_` prefixed login.gov env variables (e.g. it has `JWT_KEY` and not `PROD_JWT_KEY`), so the non-prefixed versions have not been utilized for deployments. Our prod apps rely on the logingov env variables that pre-exist in cloudgov. For now, during this pilot phase, `PROD_JWT_KEY` and `PROD_JWT_CERT` have been added. The values for these reflect the newest keys. `JWT_CERT` and `JWT_KEY` with the expired versions have been removed from HHS CircleCI, but I am retaining these as backups until the next key rotation in ~90 days. Re-deployed with new keys. 

   > sign-in successful.

5. this change is tracked in [OneNote](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Dev%20Notes.one%7C3dbb7d3a-694d-4f1c-a656-f907991c1f7d%2FProd%20keys%202022-09-02%7C7cfa8451-fd46-4722-ab5e-4fe6e6287ffe%2F%29&wdorigin=703) :lock:
