### ISSUE TITLE
As django admin, I need to manually set pilot users to approved

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2083]
**Description:**
As a follow-on to #1679, we felt it would be simpler to manually set the pilot users to `Account Approval Status` to 'approved' and then run another migration to fully delete the deprecated fields.

**Acceptance Criteria:** 
- [x] User flow is consistent with 1679
- [x] Existing users (especially prod users) retain their existing access/behavior with no intervention
- [ ] Deprecated fields are truly deleted from the user models
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
- [x] Manually set all users
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by ADPennington** [comment]
When the  acct status changes to `approved`, it will trigger an email to existing users. if this is a concern, @reitermb @lilybl1 @ttran-hub we may need to plan to send out a "heads up" about this.

**Comment by lilybl1** [comment]
@ADPennington Okay. Should be manageable for November 2022. Q: will this be the behavior every time the acct status changes to "approved", it will send an email to all existing users? So, if we were to have another expansion in February 2022, our v2.0 would have received an "approved" email for a 3rd time?

**Comment by ADPennington** [comment]
> @ADPennington Okay. Should be manageable for November 2022. Q: will this be the behavior every time the acct status changes to "approved", it will send an email to all existing users? So, if we were to have another expansion in February 2022, our v2.0 would have received an "approved" email for a 3rd time?

@lilybl1 this is a one-time change since the account approval field is new. Should only affect the pre-existing users whose accounts we will manually change ahead of 2.2.

**Comment by ADPennington** [comment]
@andrew-jameson @ttran-hub @lilybl1 @stevenino  2.0 pilot users manually approved. Commands below, and names have been redacted and replaced by the row number in the tracker sheet. Closing this ticket as completed:

```
# ssh into prod backend
cf ssh tdp-backend-prod

# get into django shell
/tmp/lifecycle/shell
python manage.py shell_plus

# filter user model objects by location id of pilot 2.0 users. 
locationid_lst = [87,7,32,25,119,41,88,128,24,49,123] 
users_2pt0 = User.objects.filter(location_id__in=locationid_lst)

# verify these are all the prod users for pilot 2.0
for u in users_2pt0:
     print(f"name: {u.username}, loctype: {u.location_type}, locid: {u.location_id}, group: {u.groups.all()}, acctstat: {u.account_approval_status}")

>>> output below:
name: <row 2 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 7, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 3 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 7, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 18 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 87, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 16 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 119, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 13 of 2.2 tracker worksheet> loctype: stts | stt, locid: 123, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 6 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 25, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 5 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 49, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 8 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 41, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 10 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 32, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 11 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 128, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 14 of 2.2 tracker worksheet> loctype: stts | stt, locid: 123, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 12 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 88, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 9 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 24, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial
name: <row 15 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 123, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Initial

# change their account status and reset to Data analyst role to ensure no pilot user is missing permission

for u in users_2pt0:
    u.groups.set(Group.objects.filter(name='Data Analyst'))
    u.account_approval_status = 'Approved'
    u.save()


# verify change
for u in users_2pt0:
     print(f"name: {u.username}, loctype: {u.location_type}, locid: {u.location_id}, group: {u.groups.all()}, acctstat: {u.account_approval_status}")

>>> output below:

name: <row 2 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 7, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 3 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 7, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 18 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 87, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 16 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 119, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 13 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 123, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 6 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 25, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 5 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 49, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 8 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 41, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 10 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 32, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 11 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 128, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 14 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 123, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 12 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 88, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 9 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 24, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved
name: <row 15 of 2.2 tracker worksheet>, loctype: stts | stt, locid: 123, group: <QuerySet [<Group: Data Analyst>]>, acctstat: Approved

# verify that approval emails were sent via DAC logs
logs = LogEntry.objects.filter(change_message__icontains="Access Request Approved")

for cm in logs:
     print(cm.change_message)

>>> output below:

Email sent to [row 15 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 9 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 12 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 14 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 11 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 10 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 8 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 5 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 6 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 13 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 16 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 18 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 3 of 2.2 tracker worksheet] with subject "Access Request Approved".
Email sent to [row 2 of 2.2 tracker worksheet] with subject "Access Request Approved".

```
