### ISSUE TITLE
Transferred files must be renamed on ACF Titan

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2090]
**Description**

All files transferred to ACFTitan have a fixed name: `ADS.E2J.FTP8.TSNone` which was introduced in #1736. Evidence is captured [here](https://github.com/raft-tech/TANF-app/pull/1918#pullrequestreview-1087368110). The file-renaming logic [starting here](https://github.com/raft-tech/TANF-app/blob/271dc53f81d614b0ac6790275c88d6bd6c73d327/tdrs-backend/tdpservice/data_files/models.py#L154) needs refinement to match the standard file naming conventions expected by the legacy system. 

**Acceptance Criteria**
- [ ] all files submitted through TDP are renamed to match standard TDRS file naming conventions included in STT model `filenames` field. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks**
- [x] Update [`stt models.py`](https://github.com/raft-tech/TANF-app/blob/271dc53f81d614b0ac6790275c88d6bd6c73d327/tdrs-backend/tdpservice/stts/models.py#L37)
- [ ] Update [`create_filename`](https://github.com/raft-tech/TANF-app/blob/271dc53f81d614b0ac6790275c88d6bd6c73d327/tdrs-backend/tdpservice/data_files/models.py#L154) function 
- [x] Run Testing Checklist and confirm all tests pass

**Notes**:

- SECTION value in renamed file should be `1, 2, 3, or 4` only (not `8`) and can be mapped from the section name associated with the original file as follows:
  -  1: =Active Case Data
  -  2:=Closed Case Data
  - 3:= Aggregate Data
  - 4:= Stratum Data
  
  _Note_: TDP is currently only using [these section names](https://github.com/raft-tech/TANF-app/blob/271dc53f81d614b0ac6790275c88d6bd6c73d327/tdrs-backend/tdpservice/data_files/models.py#L97L100), since we are not yet distinguishing between SSP and TANF and Tribal TANF data reports. 
 
- `FTP` and `TS`  are not standard parts of the renamed file convention. All of the exact file names, by section name,  can be pulled from the STT model's `filenames` field, but will need some conditional logic since the section names in this field do not exist yet in TDP. For example:
  - if Indiana, submits a section 1 file of SSP data using TDP today, this file will have a section name == `Active Case Data` but should be `SSP Active Case Data`. 
![2090p3](https://user-images.githubusercontent.com/63075587/186991358-6364217e-ecb7-4ce2-8ce0-14ab01f4d023.JPG)

  - Similarly, if Tulalip Tribes submits a section 1 of Tribal TANF data using TDP today, this file a section name == `Active Case Data` but should be `Tribal Active Case Data`. 
![2090p1](https://user-images.githubusercontent.com/63075587/186991181-4546b286-c116-4425-8d27-65f8e8055093.JPG)

- STT_CODE must be 2 digits for states and territories, and 3 digits for tribes in the renamed file (leading zeros included). this is currently not the way this code is saved in the STT Model. see below. 
![2090p4](https://user-images.githubusercontent.com/63075587/187290942-7c9d68ca-c509-46cd-a294-b953ff0ae249.JPG)

**Comment by ADPennington** [comment]
@stevenino please add this ticket as a dependency to closing out the sftp epic.

**Comment by raftmsohani** [comment]
As per our conversation, the decision is to use the first 4 values in stt.filenames field using section value for the time being.
