### ISSUE TITLE
Create Utility Image(s) for CircleCI pipeline

### ISSUE THREAD

**Issue by raft-twhitlock** [raft-tech/TANF-app#2115]
**Description:**
One of the outcomes from [1826](https://github.com/raft-tech/TANF-app/issues/1826) is to create a Utility Image that has some of the tools that we are installing at the beginning of our pipeline config file. This utility image primary objective is to speed up our pipeline times. Reduction on our scripts to install certain tools will reside within this utility image. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Rely on pre-built Executor image that replaces convenience image
- [ ] Host pre-built Executor on Raft's dockerhub until implementation of container registry exists
- [ ] Dockerfiles contains versions of installed tools

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] 

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Pre-built Executor (primary container) should contains the [base tools here](https://circleci.com/docs/custom-images#required-tools-for-primary-containers) along with our own tools to run in our pipeline

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- Primary documentation for Custom Executor can be found [here](https://circleci.com/docs/custom-images)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_

**Comment by andrew-jameson** [comment]
Closing as won't do/not relevant per DevSecOps sync 8.31.
