### ISSUE TITLE
Container Registry creation

### ISSUE THREAD

**Issue by raft-twhitlock** [raft-tech/TANF-app#2116]
**Description:**
Follow on ticket created from [1826](https://github.com/raft-tech/TANF-app/issues/1826)Create self hosted container registry, using some of the common OSS options available (nexus, harbor, ECR,etc...) paired with Raft's AWS account. Instead of relying on built images every time our pipeline is ran, best practices encourage to have separate jobs/tasks that build images that are unique to a development team. In turn, these images are usually hosted on private container registries where the pipeline's service account can pull from. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ]  Select OSS container registry that can be self-hosted on a EC2 instance or through managed K8s environment
- [ ] Prefer to go with a container registry that has different options for backups (postgres to be used with AWS RDS)
- [ ] Self hosted images can be accessed from pipeline through container registry
- [ ] DNS subdomain configured for container registry, if going with server install on EC2 (Talk to Bhaarat)

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] There might be some cost analysis that we should do for this ticket. To manage a self hosted container registry, the easiest solutions are either hosting the server on EC2 instances or deploying through helm charts on AWS EKS.
- [ ] Cost analysis should include any RDS instances, in case if EC2 instances are taken down by mistake
- [ ] Using selected container registry of choice, there should be recommended resources pointing us to use the right EC2 instance type or options for a AWS EKS cluster

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Nexus Repository Pro vs Nexus Repository OSS](https://www.sonatype.com/products/repository-oss-vs-pro-features?hsLang=en-us)
- [Harbor Registry](https://goharbor.io/)
- [AWS Elastic Container Registry](https://aws.amazon.com/ecr/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- In the case of using Nexus over the others, see if a subscription for Nexus Pro would be more cost effective than using AWS resources. Harbor is 100% open source.

- If we use non-cloud.gov resources (ie. Raft's AWS), what do we need to do for ATO's and if we have to document the system’s non-inherited security controls in an [OpenControl](https://github.com/18F/tdrs-app-rfq/blob/main/Final-RFQ/FINAL-TDRS-software-development-RFQ.md#21-scope) format?

**Comment by George-Hudson** [comment]
EOD: 7/17/2023 

Proof of concept complete at nexus.tdpraft.com can upload and download docker containers. Currently deployed in my personal AWS account.

100% of infrastructure added to terraform. https://github.com/raft-tech/TDP-Infrastructure/pull/1/files

still need to update documentation and show to team. 

Working with Barak Stout to get Raft AWS access to host. Contacted on Mattermost. Discussing having separate account for Raft TANF team

**Comment by George-Hudson** [comment]
EOD: 7/18/2023

Barak Stout reports AWS conversation can happen tomorrow. 

Still need to update documentation.

**Comment by George-Hudson** [comment]
EOD Jul 19th
AWS discussion moved to Steve Nino. Connor will fill me with details from the 1:1 convo
