### ISSUE TITLE
Persist environment variables across application rebuilds/restages.

### ISSUE THREAD

**Issue by raft-twhitlock** [raft-tech/TANF-app#2118]
**Description:**
Ticket created from spike [1826](https://github.com/raft-tech/TANF-app/issues/1826).

1. Don't Repeat Yourself: our previous scripts had many repeated commands/segments
2. Idempotent: repeated operations on the same target produce the same result. In other words, the desired state is always attained and the state-machine of such operations is well-handled.
3. Infrastructure as code: Rather than storing state/configuration implicitly in the product, it is an improvement to have it explicit stored as code/config and be human-readable at a glance in a handful of files.
4. Automated/Low maintenance: While the maintained wasn't too high, we repeatedly have been updating these scripts with new hard-coded variable names but also updates to logic.
5. Robust: our existing scripts did not have great error-handling and needed manual intervention frequently
6. BONUS: I'd love if our tool could perform roll-backs to increase stability

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Environment variables should persist across application rebuilds/restages.
- [ ] Special environment variable values should remain across rebuilds (e.g., don't overwrite AMS_CLIENT_ID)
- [ ] Automation tool is maintainable and integrates well with our ecosystem
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary
- [ ] From [ticket 2160](https://github.com/raft-tech/TANF-app/pull/2160/files), take care of var in files `tdrs-backend/tdpservice/settings/cloudgov.py`

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Various tool options are explored for adherence to principles outlined in description
- [ ] Existing env vars are "saved" before an environment is deleted/recreated and ensure they are re-applied on start
- [ ] Remove extraneous environment variables from application spaces
- [ ] Make follow-on ticket to address Login.gov key instability and updates
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- These environment variables can be done with terraform (IaC) tool that can handle variables. If the variable is secret, we can leverage on how we implement spike [1977](https://github.com/raft-tech/TANF-app/issues/1977)
- The documentation to handle variables in Terraform can be found [here](https://www.terraform.io/language/values/variables#environment-variables)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by robgendron** [comment]
@andrew-jameson @ADPennington Is this still needed? I'm cleaning up the labeling. If not, I can close on my end.

**Comment by ADPennington** [comment]
> @andrew-jameson @ADPennington Is this still needed? I'm cleaning up the labeling. If not, I can close on my end.

im fine with closing it. i dont have this problem in the lower environments.
