### ISSUE TITLE
[Dev-ready Design] Explainer for "Closed Cases" for grantees familiar with "Negative Cases"

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2131]
**Description:**

Pilot research revisited the fact that many grantees use different/older terms for various elements of TANF data, in this case using "Negative" rather than "Closed" to refer to Section 2 data. This ticket delivers in-app and knowledge center enhancements to de-mystify the terminology difference for grantees. In-app changes should be achievable with minimal scope (i.e. around the level of adding text / knowledge center links to the data files page).

**Related User Stories:**

- As a grantee user I want to understand what Closed Case data refers to

**AC:**

- [ ] App explains terminology difference / directs users to the knowledge center
- [ ] Knowledge center explains the terminology difference
- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] Draft design in Figma
- [ ] Draft hack.md with knowledge center changes

**Supporting Documentation:**

- [Figma]()
- [Hack.md]()

**Comment by stevenino** [comment]
@reitermb to add additional details that were discussed as part of the ticket sync with Alex.

**Comment by lilybl1** [comment]
Note: Based on discussions with Alex's meeting with the Tribal team members, it was identified that due to the long tail of fTANF replacement may be 1 year or more, there needs to be some content about Closed = Negative. TBD on the design, but needs to be considered.

**Comment by ADPennington** [comment]
did we also discuss implementing for other terms like "stratum"? @reitermb @lilybl1

**Comment by ADPennington** [comment]
> Collaborator

please disregard. i see this is captured in #2217

**Comment by robgendron** [comment]
@reitermb Is this related to Parity?

**Comment by reitermb** [comment]
This may have been duped by knowledge center work that delivered these FAQ additions
Walking onto UX sync agenda to confirm 
![image](https://github.com/raft-tech/TANF-app/assets/28515874/7804d886-b3ca-45e4-8325-4392ea70abaf)
