### ISSUE TITLE
Knowledge center documentation for common onboarding problems

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2132]
**Description:**

Pilot research revisited a number of friction points that can come into play during onboarding. These include login.gov emails being directed to spam folders and 2FA codes not being delivered on the first attempt. This ticket adds documentation to direct grantees toward to help them quickly resolve these issues. Scope should be limited to a short easily scannable article within the knowledge center (and possibly some added snippets/links to existing Getting Started pages).

**Related User Stories:**

- As a grantee user I want to know what to do if I experience a common issue with the onboarding process

**AC:**

- [x] Knowledge center has added content re: 
   - [x] How to troubleshoot common onboarding issues (STT selection and junk email) - Diana
   - [x] What email notifications to expect (request access, approved and file type data submitted - Diana
   - [x] What's changed since previous releases (changelog) - Miles
   - [x] Google Analytics tag implemented - Miles
   - [x] Footer with privacy policy implemented - Miles
   - [x] Give Feedback form updated w/ more integrated look & feel and adaptivity.
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft hack.md with knowledge center changes
   - [x] Troubleshooting common onboarding issues
   - [x] What email notifications to expect   
   - [x] Changelog
- [ ] Open PR to update knowledge center

**Supporting Documentation:**

- [Test Environment Deployment](https://reitermb.github.io/Test/knowledge-center/)

**Comment by reitermb** [comment]
Updated scope a little based on 10/14 cross product sync to encompass what to expect re: email notifications

cc: @ADPennington

**Comment by reitermb** [comment]
Not ready for QASP yet but I wanted to note that an initial version of work for the changelog (located on the homepage) and implementation of analytics are live in the test environment. 
https://reitermb.github.io/Test/knowledge-center/

![chrome_m6VbAloa2Z](https://user-images.githubusercontent.com/28515874/197894986-f8a73019-5058-448e-b85b-b00fad213891.png)
Re: the changelog if anyone's interested in demoing what the "Removed:" styling looks like there's a placeholder for one commented out in the code that can be edited back in via Inspect.

**Comment by reitermb** [comment]
> Re: the changelog if anyone's interested in demoing what the "Removed:" styling looks like there's a placeholder for one commented out in the code that can be edited back in via Inspect.

![image](https://user-images.githubusercontent.com/28515874/197895259-d66166d3-a42d-404c-add1-a267e442e338.png)
Screenshot for easier reference. 

Also cc: @ADPennington for visibility

**Comment by stevenino** [comment]
@reitermb Can we push the changes Alex requested on Wednesday 11/2?

**Comment by stevenino** [comment]
@ADPennington this is ready for QASP again.
