### ISSUE TITLE
[Dev] Enhancement for Request Access form (Tribe discoverability) 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2133]
**Description:**

Pilot research indicated that the presence of Tribal program names is not discoverable for Tribal grantee users requesting access. This ticket delivers design changes to the Request Access page that minimize or eliminate the potential for user or technological error when entering STT info. 

**Related User Stories:**

- As a grantee user I want to correctly enter which STT I'm affiliated with
- As a grantee user I don't want to see STTs I cannot be affiliated with (e.g. a user from a Tribe seeing states)

**AC:**

- [x] Autocomplete is NOT be enabled on the STT combobox field
- [x] STT combobox appears after jurisdiction type radio button selection
- [x] STT combobox is dynamically labeled based on radio selection 
- [x] Combobox options are limited to the scope of the radio selection
- [x] Form errors reflect the number of visible errors (e.g. error count should not read 3 and not 4 if a user attempts to submit the form without choosing a jurisdiction type
- [x] Keyboard navigable. Test via [activating a screenreader](https://hackmd.io/Z5t247a7St2tZzLS35JBkw) and navigating the form with keyboard only. The below should be default behavior but it's worth explicitly testing on a dynamic form.
   - [x] The STT combobox shouldn't be tabbable before it's visible
   - [x] Once a radio selection is made and the combobox appears it should be the next tab stop after the radio select. 

**Tasks:**
- [x] Add jurisdiction type radio select
- [x] Add dynamic labeling to STT combobox
- [x] Add dynamic visibility to STT combobox
- [x] Add autocomplete="off" to the STT combobox input (NOT the whole form)

**Supporting Documentation:**

![image](https://github.com/raft-tech/TANF-app/assets/28515874/155fc18b-2eed-4a12-87a6-41d1c284ae7b)

**Notes**
- DC combobox option should be included within State category
- We're eliminating "Associated" from all versions of the combobox label, possible labels will be "State*", "Territory*", and "Tribal TANF Program*"

**Comment by stevenino** [comment]
Revisit the need after the November pilot submission.

**Comment by ADPennington** [comment]
@reitermb @lilybl1 is this the ticket that is based on tribal division feedback on the plan forward, which is to change the request form to ask for grantee type then dynamically change the combo-box?

**Comment by reitermb** [comment]
> @reitermb @lilybl1 is this the ticket that is based on tribal division feedback on the plan forward, which is to change the request form to ask for grantee type then dynamically change the combo-box?

As currently written it's agnostic about the exact method for changing the form, but yes—this is the ticket to solve for that issue.

**Comment by reitermb** [comment]
Super lo-fi mockup:

**First Name** 
[                 ]

**Last Name**
[                 ]

**Jurisdiction Type(Radio buttons)**
[  ] State
[  ] Tribe
[  ] Territory

**Associated [State/Tribe/Territory]**
[ Combobox ] 


Noting we'll need to figure out a11y form behavior for radio button driven combobox (does it appear once the radio option is chosen? There all along? Label/content update? error states? as part of the final spec work

cc @lilybl1

**Comment by robgendron** [comment]
Aim to complete after Parity @reitermb

**Comment by reitermb** [comment]
> Aim to complete after Parity @reitermb 

Can we put this onto the back burner for backlog refinement to walk on post parity? This is a dev ticket that just needs a hand-off and any resulting final refinement with the dev team. 

Or a nearer term backlog. @andrew-jameson do you have any preferences when it comes to timing that? Discuss now vs closer to when we'll pull it into a sprint.

**Comment by robgendron** [comment]
3 points remaining.

**Comment by robgendron** [comment]
2 points research, 1 point PR. Upgrade may be needed.

**Comment by robgendron** [comment]
1 point remaining, testing with the screen reader.
