### ISSUE TITLE
Disable browser autofill for STT field on Request Access page

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2134]
**Description:**
Pilot testing revealed that browser autofill can lead to the wrong STT being entered on TDP's Request Access page. This enhancement is related to #2133, but not blocked by it.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Associated STT field gets an ```autocomplete="off"``` attribute
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add ```autocomplete="off"``` to the STT combobox input (NOT the whole form) 
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by reitermb** [comment]
Likely closeable after #2133

**Comment by lhuxraft** [comment]
Should no longer be an issue
