### ISSUE TITLE
As a user, I need ACF Titan filename from STT filename table only

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2136]
**Description:**
_Provide a brief background and justification for this issue_
The DataFile model has a logic to get the filename from STT filename table using section and if the filename does not exist, tried to create one. However, we should always have the filename based on section and do not need to create new filename.

the following logic should not be needed:
```
    def create_filename(self, prefix='ADS.E2J'):
        """Return a valid file name for sftp transfer."""
        """TODO: This method has to be changed when the """
        # STT_TYPES = ["state", "territory", "tribe"]
        SECTION = [i.value for i in list(self.Section)]

        # str(STT_TYPES.index(self.stt.type)+1)
        return ''.join(prefix+'.FTP'+str(SECTION.index(self.section))+'.TS' + str(self.stt.stt_code))
```

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Remove quoted code block above
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by andrew-jameson** [comment]
For future releases, we can remove this logic and should instead utilize only filenames from the database table for SSP users and/or Tribal users. This is an improvement of SFTP generally which will be sunsetted when full parity of parsing is reached. @raftmsohani will remove this dead code.
