### ISSUE TITLE
[a11y] Update footer designs to address additions like vulnerability disclosure

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2137]
**Description:**

Follow-on from #1979 — delivers modification to the footer so that all links are housed in a single list element as opposed to multiple (per column). 

**AC:**
- [x] Footer appears the same visually
- [x] All links in footer are housed in one list element
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Consolidate links into one list element
- [x] Adjust style attributes to adjust any visual changes

**Comment by lhuxraft** [comment]
@reitermb To be further refined into a low priority dev ticket (HTML implementation)

**Comment by lhuxraft** [comment]
12/2: Moved to Raft review, Miles to review today/tomorrow

**Comment by lhuxraft** [comment]
12/9: Tagged Thomas to review
