### ISSUE TITLE
[Design] As regional staff, I can validate a new user is a representative of an STT.

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#214]
**Description:**
A new user has requested access but not yet been approved. This issue documents how a a Regional OFA user would see "handshake" information associated to a request for access and better evaluate whether the user in question should be approved and granted access.

**AC:** 
- [ ] Information submitted by approved grantee users (#1201) is available in the access request approval interface 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

**Tasks:** 
- [ ] Update access request flow as needed to document any changes
- [ ] Update current figma designs for OFA Admin to add grantee sourced team info to approval screens

**DoD:**
- Figma page
- @lfrohlich has reviewed and signed off

**Comment by amilash** [comment]
We need to figure out what the login flow is and how approvals work for OFA admins.

**Comment by valcollignon** [comment]
@reitermb @sreedevip If this issue is for Version 3, can we move it out of "Unrefined and On Deck" to Product Backlog until the work on this is a priority?
CC: @lfrohlich @ADPennington

**Comment by lfrohlich** [comment]
I moved it to Product Backlog :)

**Comment by reitermb** [comment]
Relates to [regional staff vetting flow](https://app.mural.co/t/raft2792/m/raft2792/1627058877512/7514d3617f4bc241d3f70ff6e61253e1ce09f880?wid=0-1700158791456) design roadmap item.

**Comment by lhuxraft** [comment]
Gone in a different direction with user management (takes place external to the system). May create a future ticket that would take place in-app (and would need future research)
