### ISSUE TITLE
As a grantee user submitting data I always want to see the confirmation/error message

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2140]
**Description:**

Pilot research showed us that most of our participants were using TDP at resolutions that cut off the success/error banner on the Data Files submission page. This ticket should deliver an enhancement that sets focus to said banner when Submit is clicked. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Focus shifts to banner when Submit is clicked
- [ ] Banner is not in the normal tab order (i.e. you'll only be able to focus it in screenreader mode or by clicking submit)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add function to set focus to error / success banner
- [ ] Check to make sure the banner is not tabbable normally (without using a screen-reader) 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Page headings are a good example of focused but not in normal tab order behavior. When you land on a page in TDP focus is set to the main heading, but if you start tabbing around you can't land back on the heading. 
Testing multi-file including one fail, test at a high browser zoom to simulate low resolution.

**Comment by jtimpe** [comment]
Given
* i'm logged in as a user with "x" group, "x" location, "x permissions"
* small screen size/low resolution monitor (a user has to scroll to access "Sections" on the Data Files page)

When
* I submit a data file for upload

Then
* a "success" or "error" alert banner scrolls into view
