### ISSUE TITLE
As technical lead, I want an authenticated-user integration test

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2141]
As a developer, I'd like smoke or integration tests to run on deployments to all environments so that changes are tested automatically upon code merge, giving me the highest confidence that my changes will work when deployed to production.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Define smoke testing and integration testing and determine which practices to adopt for these tests, choose an appropriate test runner
- [x] Define a set of scenarios applicable to the selected approach
- [x] In an ADR, document the testing approach and tools, as well as the reasoning for selecting the given test scenarios chosen in the steps above. Include information on how to determine when a new smoke test should be added, as well as a process for responding to failures.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Determine if we're interested in smoke testing or more robust integration testing
- [x] Define some criteria for what makes a "good" test given the end goal
- [x] Research available test runners and/or open source or SaaS tools for each type, select a tool to use
- [x] Start an automated suite by setting up the test runner(s)
- [x] Set up a test suite using the selected runner. Create automated test(s) for an authenticated "hello world"
- [x] Document the research criteria and decision in an ADR
- [x] Update documentation with instructions for running tests locally and in each environment
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Additional scenarios can be split into other work items and separately prioritized.
- Tentatively, will select Cypress as our test runner given @jtimpe 's prior experience.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by stevenino** [comment]
This is an action item that came out of the pilot release post mortem.

**Comment by andrew-jameson** [comment]
Might be worth investigating how "pa11y" bypasses auth in the CI pipeline.
https://github.com/raft-tech/TANF-app/pull/1454
