### ISSUE TITLE
As system owner, I want to TDP backend to have ACF domain for release 2.0

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2145]
For release 1, we used a cloud.gov domain for the backend as shown here: https://github.com/raft-tech/TANF-app/issues/1627#issuecomment-1181853861

This was a workaround to an issue with cross-site domains that is documented in #726. This issue effectively made it impossible to successfully authenticate into TDP.  The workaround resolved this but introduced new issues with the TDP functionality (i.e. requesting access, submitting data files...[see here](#1945)) that make it necessary to resolve the root cause of the cross-domain problem. 

tdp prod backend should be: https://api-tanfdata.acf.hhs.gov/admin/

**ACs**:
- [x] `production-deployment` workflow from HHS CI is successful. 
- [x] ACF user can login at https://tanfdata.acf.hhs.gov/
- [x] non-ACF user can login at https://tanfdata.acf.hhs.gov/ 
- [x] ACF user can request access 
- [x] non-ACF user can request access
- [x] `OFA Sys Admin` can access all parts of DAC to manage users and data via https://api-tanfdata.acf.hhs.gov/admin/

**Tasks**:
- [x] merge #2070 

**Supporting documentation**:
-  #1945 
- #2031 
-  #2038

**Comment by stevenino** [comment]
@andrew to add proposed solution.

**Comment by stevenino** [comment]
Resolved under #2038
