### ISSUE TITLE
As a developer, I want know which version of the app is currently deployed

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#215]
**Description:**
Adding a tag to the bottom of all viewable pages to note which version of the frontend is currently deployed. This is in support of allowing users to know what changes they can currently can expect to see when referencing future change logs and during development. 

**Acceptance Criteria: **

- [ ] Anonymous users can clearly see on the frontend what version/hash is currently deployed

**Tasks: **
- [ ] Create a record of which version the code is on, make updating this easy when going from v2.1 to v2.2 (flat file in repo is how I've seen this done in the past)
- [ ] Make git commit hash available within the CircleCI environment
- [ ] "Stamp" version and hash into frontend footer for display to even anonymous/unauthenticated users

**Open Questions:**

- What is the best way to record code version? Version number and a hash

**Comment by shubhi-raft** [comment]
@carltonsmith @hilvitzs is this still relevant?

**Comment by hilvitzs** [comment]
I haven't seen this or heard anything about it.

**Comment by robgendron** [comment]
Labelling as a DUPE, #1620 covers the work indicated in this ticket. @andrew-jameson and I deemed closed.
