### ISSUE TITLE
As a STT data analyst, I should not be able to upload SSP data if my STT does not upload it

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2166]
**Description:**
A follow on to #217. Related to #1755 

**Acceptance Criteria:** 
- [ ] Reject data file uploads of type `SSP` if STT does not have SSP indicator
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Upon rejection, provide error code to frontend/user data file upload
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by stevenino** [comment]
Closed as not required per sprint planning on 10/25
