### ISSUE TITLE
As tech lead, I do not want our raft-tech circleci to be able to deploy to prod

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2169]
**Description:**
Currently, the `deploy-backend.sh` references a bunch of `PROD_*` envrionment variables. With a more stable prod, we should only be deploying here from `HHS:TANF-app` so we should remove these lines.

**Acceptance Criteria:** 

- [ ] Can no longer deploy to production from raft-tech:TANF-app
- [ ] Deploying to dev and develop applications is still functional
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Extraneous variables are removed, their non-prod counterparts are put in place
- [ ] Clear process documentation on deploying to prod, if updates are needed
- [ ] Deploy to various environments/spaces to ensure we retain our capabilities
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by andrew-jameson** [comment]
@ADPennington Please let me know if this is a duplicate ticket.

cc @stevenino

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

yes. confirmed that there are no env var pairs in raft's circleci that are relevant/up-to-date for prod.
