### ISSUE TITLE
Fix download button disappearance after click

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2175]
### Background ###
Download button on previously submitted data files disappears when clicked. It should remain present whenever a download is available for a given section rather than disappearing after one use.

### Acceptance Criteria ###
- [x] Download buttons do not disappear when clicked
- [x] Download buttons do not appear when no file is present for that section
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

### Tasks ###
- [x] Create unit test(s) to ensure download button persists beyond a click 
- [x] Refactor action/component to grant desired behavior
- [x] Ensure behavior is a11y compliant
- [x] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
_Please include any relevant log snippets/files/screen shots_
![download-0](https://user-images.githubusercontent.com/84722778/198707506-0d2ed6d6-4cea-4b98-9743-a4ae30f396cc.JPG)

![download-1](https://user-images.githubusercontent.com/84722778/198707528-a1714e52-bf56-4c4a-a1f9-bee39c06eed6.JPG)

**Comment by stevenino** [comment]
This bug has a workaround.

**Comment by robgendron** [comment]
@ADPennington @lfrohlich @reitermb , is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich @reitermb , is this still needed or can it be closed?

Recommend having someone from dev or UX test this in develop environment to check if this is still an issue. @robgendron

**Comment by robgendron** [comment]
> > @ADPennington @lfrohlich @reitermb , is this still needed or can it be closed?
> 
> Recommend having someone from dev or UX test this in develop environment to check if this is still an issue. @robgendron

Will do, thank you @ADPennington.

**Comment by victoriaatraft** [comment]
> > > @ADPennington @lfrohlich @reitermb , is this still needed or can it be closed?
> > 
> > 
> > Recommend having someone from dev or UX test this in develop environment to check if this is still an issue. @robgendron
> 
> Will do, thank you @ADPennington.

This is still an issue for me when i test https://tdp-frontend-qasp.app.cloud.gov/home @robgendron @ADPennington

**Comment by robgendron** [comment]
> > > > @ADPennington @lfrohlich @reitermb , is this still needed or can it be closed?
> > > 
> > > 
> > > Recommend having someone from dev or UX test this in develop environment to check if this is still an issue. @robgendron
> > 
> > 
> > Will do, thank you @ADPennington.
> 
> This is still an issue for me when i test https://tdp-frontend-qasp.app.cloud.gov/home @robgendron @ADPennington

Thank you for the update @victoriaatraft.
