### ISSUE TITLE
Restage apps for buildpack update (10/02/2022)

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2183]
**Description:**

Hi cloud.gov user,

cloud.gov frequently updates the programming language buildpacks available to
our customers. Buildpack updates include programming language updates and 
often include security fixes.

We recently updated the buildpack in use by your application. You should 
restage or redeploy your application to take advantage of the update.

A rolling restage operation is the quickest way to upgrade without incurring
downtime. You may still want to leverage your deployment infrastructure to
perform the upgrade if you have compliance requirements for redeployment operations.

You can restage your application by opening the command line and entering 
the following commands:

  cf target -o hhs-acf-ofa -s tanf-dev ; cf restage --strategy rolling elastic-demo-kibana

For more information about the buildpack update(s), please see the following release notes:

  go_buildpack v1.9.50: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fgo-buildpack%2Freleases%2Ftag%2Fv1.9.50&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=2JU9wmN1SAU%2FhiRd1KfjBH2HsE8j72BSUIo4c1HaUWc%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fgo-buildpack%2Freleases%2Ftag%2Fv1.9.50&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dvbtXeSl06dxlqoiSqRPjSk%2Fyu35cepVu3eRnw7JMJM%3D&reserved=0)

  staticfile_buildpack v1.5.33: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fstaticfile-buildpack%2Freleases%2Ftag%2Fv1.5.33&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=ZJuKGjXLiTb88u9QxVUbXNEQcteMvI%2Bh1ba1q6iv4%2FE%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fstaticfile-buildpack%2Freleases%2Ftag%2Fv1.5.33&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FAo5poUdPehQsJK8z9jUZVlrKfnZQaTOc7L4%2F%2F1CJ%2Bc%3D&reserved=0)

  nodejs_buildpack v1.8.0: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnodejs-buildpack%2Freleases%2Ftag%2Fv1.8.0&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=Uki2g1iIh0dtk0M63lx5HRwhy1uVr4TuIX7GiXP36X4%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnodejs-buildpack%2Freleases%2Ftag%2Fv1.8.0&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MJlI7blN9WLjdUnVK5fuHzDp3CtQr8GGTyWBS9rfldY%3D&reserved=0)

  java_buildpack v4.52: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fjava-buildpack%2Freleases%2Ftag%2Fv4.52&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=7P0uGg8mIp35O06TppTliFdsruD67eH9MFViUPNsiSA%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fjava-buildpack%2Freleases%2Ftag%2Fv4.52&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VpeIbHmvJXBxh3ZvutH1jBmjRcwJpF8llUilgF%2FBzvk%3D&reserved=0)

  python_buildpack v1.7.59: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fpython-buildpack%2Freleases%2Ftag%2Fv1.7.59&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=GNA5EFWZLM%2FObeB9RXvqaxmXIwnMvZKpibPJ38cRjAc%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fpython-buildpack%2Freleases%2Ftag%2Fv1.7.59&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9MRYhNf56XANSAMMGdvg76vD8Ck58%2BAT1ao3ybO2GFo%3D&reserved=0)

  ruby_buildpack v1.8.58: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fruby-buildpack%2Freleases%2Ftag%2Fv1.8.58&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=LjgDhHmS6QFwYQGWOFUPn79vySVxSOmrUvoR7rmDycI%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fruby-buildpack%2Freleases%2Ftag%2Fv1.8.58&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Awgstf5mIInqyQmkK%2BbNiltXe9lkSBEBVQ%2FNyT0IO9M%3D&reserved=0)

  php_buildpack v4.4.66: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fphp-buildpack%2Freleases%2Ftag%2Fv4.4.66&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=uwqwKeKu385%2BOFca6n5wlfmnq4B3TvzsNYGPQWiD%2FrI%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fphp-buildpack%2Freleases%2Ftag%2Fv4.4.66&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=66NVQUQIDUVP02TFGilaxBHBtPGOcO4VZjCQLPMIwd4%3D&reserved=0)

  nginx_buildpack v1.1.43: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnginx-buildpack%2Freleases%2Ftag%2Fv1.1.43&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=GBoois1qrw5OabIG3WvFhMoUBS0m80PaQNevvUHmSGI%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fnginx-buildpack%2Freleases%2Ftag%2Fv1.1.43&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002853933546%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vyd7YbGKMNYPHQ21XjLa2JoveD3Nw9VU5sDcFb7nEtg%3D&reserved=0)

  r_buildpack v1.1.33: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fr-buildpack%2Freleases%2Ftag%2Fv1.1.33&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=7yqEw1Vv8kmR9y8k9yhB8Kq0JtbFvyIvBSYOMR53PPQ%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fr-buildpack%2Freleases%2Ftag%2Fv1.1.33&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002854089766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XLj%2FtRBKTggU%2F5HDXN6T2XUfTusxVsfNFkbWu405nIM%3D&reserved=0)

  binary_buildpack v1.0.46: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fbinary-buildpack%2Freleases%2Ftag%2Fv1.0.46&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=qxWrCNS5yxyKhD4AOEXfjXQ25KAy57uMcZPvKkk9j8g%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fbinary-buildpack%2Freleases%2Ftag%2Fv1.0.46&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002854089766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JZByM2t7Sy%2BySxJ%2F9Io58nfKFQWFEkokiHcp7OgWeiY%3D&reserved=0)

  dotnet_core_buildpack v2.4.1: [https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fdotnet-core-buildpack%2Freleases%2Ftag%2Fv2.4.1&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=Jg%2FyHDGPTe64Q02yXelsZ8geFIjfr1AlOw25gIqEKm4%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcloudfoundry%2Fdotnet-core-buildpack%2Freleases%2Ftag%2Fv2.4.1&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002854089766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DO6sG6bMRJyL4XsOkqRQDOv2hNkwzKKgvtVshDMYqgU%3D&reserved=0)

For more information on keeping your application updated and secure, see: 
[https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.gov%2Fdocs%2Fgetting-started%2Fapp-maintenance%2F&amp;data=05%7C01%7Cajameson%40goraft.tech%7C536699b9682e4dcbab4c08daa7140750%7Cecf3b703303747149fb7e24c98f49931%7C0%7C0%7C638006001715512486%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=sigeW57xmelo3rnpCNhNhmJx6AiyoRP2Tj6PEQ8FkcU%3D&amp;reserved=0](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcloud.gov%2Fdocs%2Fgetting-started%2Fapp-maintenance%2F&data=05%7C01%7CAlexandra.Pennington%40acf.hhs.gov%7C013c2a540044471d62dd08daa7144ba1%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638006002854089766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t0%2Fj82AJyhhFUIwZ3WCwIYtTeDtPuk1dE0o1c7LdgSA%3D&reserved=0)

If you have questions, you can email us at [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov).

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] apps restaged with no breaking changes. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] follow steps [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/Architecture-Decision-Record/011-buildpacks.md#notes) for restage steps. 
- [ ] Run Testing Checklist and confirm all tests pass
