### ISSUE TITLE
[Research Planning] Recruitment for November Pilot Expansion

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2184]
**Description:**
Delivers continued recruitment work for the November TDP expansion and additional research prep related either to 3.0 errors research or 2.2 pilot specific research.

**AC:**
- [x] Grantees from the shortlist have been reached out to about participation in November expansion
- [x] Additional tickets needed to support 2.2 / 3.0 research tracks have been created

**Tasks:**
- [x] Send out first wave of recruitment emails (in progress) 
- [x] Use October research sessions as recruitment opportunities (in progress) 
- [x] Miles & Diana sync to refine additional needed tickets / align around schedule for November expansion and errors research

**Comment by lilybl1** [comment]
closing ticket after sync discussion.

**Comment by reitermb** [comment]
Noting that the tickets created as part of the scope of this ticket were discussed in last backlog (#2193 , #2192 , #2191) cc @stevenino @ADPennington

**Comment by ADPennington** [comment]
Closing as completed. per 10/24 UX Sync
