### ISSUE TITLE
[Research Synthesis] 2022, Fall Research Error Messages

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2186]
**Description:**

--Link to research planning, facilitation tickets, other relevant supporting information. Typically pointed at 13 points.--

**AC:**

- [ ] A hack.md with the drafted synthesis has been reviewed.
- [ ] PR has been opened containing the final draft of the synthesis.

**Tasks:**

- [ ] --Aggregate notes from research sessions--
- [ ] Delete video recording(s) once notes are compiled
- [ ] Document synthesis - Scope (research goal(s)), High-level findings, Actionable learnings, Issues that have to be added to Zenhub, Takeways for future research

**Supporting Documentation:**

- --Link to hack.md--
