### ISSUE TITLE
[Research Synthesis] Notifications and SSP Submission Pilot Release v2.2

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2191]
**Description:**

This synthesis delivers findings specific to 2.0 - 2.2 functionality studied during the November Pilot expansion. This includes revisiting elements flagged in the August pilot (e.g. Tribe discoverability in the associated stt combobox), and grantee impressions of new functionality (e.g. Notifications, SSP support) 

**AC:**

- [x] A hack.md with the drafted synthesis has been reviewed.
- [ ] PR has been opened containing the final draft of the synthesis.

**Tasks:**

- [x] Aggregate notes from research sessions into Mural board (#2192)
   - [x] Feedback Form
   - [x] Video Recordings (2)
   - [x] Written Notes from Various Locations
- [x] Document synthesis 
   - [x] Who we talked to
   - [x] What we did
   - [x] What we tested
   - [x] What we learned
   - [x] What's next
   - [x] Issues that have to be added to Zenhub, Takeaways for future research
- [x] Delete video recording(s) once notes are compiled

**Supporting Documentation:**
- [v2.2 Pilot Workshop - Mural](https://app.mural.co/t/raft2792/m/raft2792/1664205610518/2b3edb3a6f413ac420cffdc2461c9d5ecd1433e9?sender=u3ca60168b5ac4eb17bf92804)
- [Hack.md draft](https://hackmd.io/@mreiter/S1Dq0ew7i/edit)

**Comment by reitermb** [comment]
Miles to split into two tickets: 
To be drafted: 2022 Error Guidance (maybe to be published alongside other 3.0 research in early 2023)
To be published: 2.2 Pilot (Notifications & SSP Submission)

**Comment by lilybl1** [comment]
@reitermb It looks like you are the owner on this one... Could you lock the Mural board for v2.2? https://app.mural.co/t/raft2792/m/raft2792/1664205610518/2b3edb3a6f413ac420cffdc2461c9d5ecd1433e9?sender=u3ca60168b5ac4eb17bf92804

**Comment by lilybl1** [comment]
@stevenino @reitermb @ADPennington The hackmd is ready for review. https://hackmd.io/KmAhOw5-Sm2Syu9k3sEEAg?view

**Comment by ADPennington** [comment]
i left questions and comments in the hackmd. some high level notes below: 

- i think there are 21 STTs in the v2.2 tracker, and 15 referenced. Is this limited to those who actually submitted?
- related to the above,  it might be helpful to have a couple of sentences on challenges with recruitment. i think this will help inform scale-up strategy. can also link to #2300. 
- im wondering if an issue is missing about fixing the request access form. if its been created can we reference it here and explain the justification?

@reitermb @lilybl1 back to `raft review`

**Comment by lilybl1** [comment]
@ADPennington Ready for another QASP review.

**Comment by ADPennington** [comment]
> @ADPennington Ready for another QASP review.

@lilybl1 i made some minor in-line changes. this is `qasp` approved. thank you! Can you confirm what the next step here is? Create a PR to add this synthesis to the repo?

**Comment by lilybl1** [comment]
The videos are scheduled to expire on 12/14
