### ISSUE TITLE
[Research Facilitation] Open ended v2.2 feedback sessions

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2192]
**Description:**
Sessions booked based on log events showing grantee submission of data for Nov 15. Runs in parallel with pilot timeline, e.g. Week of the 7th into the week of the 14th.

**AC:**

- [ ] Research sessions have occurred.
   - [ ] SSP states
   - [ ] with 3+ Tribes
- [ ] Anonymized session notes or other top-line synthesis have been documented.
- [ ] Changes to recruitment criteria have been documented if recruitment/target participant pool has been expanded.

**Tasks:**

- [ ] SSP Feedback Session 1
- [ ] SSP Feedback Session 2
- [ ] Tribe Facilitation Session 3
- [ ] Tribe Facilitation Session 4
- [ ] Territory Facilitation Session 5
- [ ] Aggregate notes from research sessions
