### ISSUE TITLE
[Unit Tests] Standardize usage of `react-testing-library` or `enzyme` in frontend unit tests

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2196]
**Description:**
As mentioned by Tim in the discussion of PR #2189, we should standardize our usage of _either_ `react-testing-library` or `enzyme` for our frontend unit tests.
(Link: https://github.com/raft-tech/TANF-app/pull/2189#discussion_r996067861)

Both libraries provide similar functionality (`render` and `mount`, respectively) to render components for tests, but there's probably no reason to use both. We should take a look at our usage and see if we can refactor some tests to use the other library.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Consolidated usage of only one frontend library
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate cause/usage of `enzyme`
- [ ] Coordinate decision of which library to use, pro/con lists if necessary
- [ ] Refactor frontend testing code to gain parity with existing tests
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

@jtimpe ?

**Comment by jtimpe** [comment]
@robgendron @ADPennington we still use both libraries in our codebase and could choose a single one, but this is a minor, nice-to-have test optimization. it's very low priority and i'd be fine with closing it.

**Comment by robgendron** [comment]
Deemed closed by Jan, Andrew, Alex, and Rob.
