### ISSUE TITLE
As tech lead, I need critical finding from WebInspect Oct 2022 scan addressed

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2216]
**Description:**

ACF OCIO performs monthly security scans on prod using [WebInspect](https://www.microfocus.com/media/data-sheet/webinspect_automated_dynamic_application_security_testing_ds.pdf), and has one critical finding for Oct 2022:

"WebInspect has detected support for weak TLS/SSL ciphers on the server `https://tanfdata.acf.hhs.gov:443/runtime-main.[hash].js`". More information is on [p. 23 here](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FTDP%20Security%20Scans%2FWebInspect%2FOct2022%2FACF%2DExternal%20Prod%20%2D%20tanfdata%2Eacf%2Ehhs%2Egov%202022%2D10%2D01T14%2E20%2E10%2Epdf&viewid=6ecbc5f1%2Dfa9c%2D4b0a%2Da454%2D35e222e8044e&parent=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FTDP%20Security%20Scans%2FWebInspect%2FOct2022) :lock: 

Per OCIO, we have 2 weeks to address critical findings. When we need more time to resolve, we should inform them. 

**Acceptance Criteria:** 
- [ ] source of issue identified
- [ ] source of issue resolved or documented
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] investigate root cause
- [ ] look into why this isnt showing up in owasp scans
- [ ] resolve/document
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
- about [`runtime-main.[hash].js`](https://create-react-app.dev/docs/production-build/)

**Comment by ADPennington** [comment]
@jtimpe the critical finding description is on page 8 of the above attachment. and the dependency appears as a `low` finding from zap [here](https://output.circle-artifacts.com/output/job/165ac834-f51a-4d03-8981-fc05c155f334/artifacts/0/tdrs-backend/reports/owasp_report.html)

**Comment by jtimpe** [comment]
@ADPennington @stevenino @andrew-jameson bit of an update here based on some research

* [(Draft PR) attempt to resolve](https://github.com/raft-tech/TANF-app/pull/2227)

I attempted to update our `ssl_protocol` for nginx to TLS 1.3, but it didn't work. I think that's because Cloud.gov sits between the client and the nginx instance we have set up to serve the frontend. Since Cloud.gov is the first party to handle the request, whatever SSL/TLS protocols they support are what the browser will negotiate with. Our nginx configuration only applies to the connection between the Cloud.gov load balancer that initially serves the request and our frontend application.

In Firefox (and I assume Chrome), you can see the protocol settings in DevTools by going to the Network tab, selecting the request to `/`, and selecting the Security tab
<img width="579" alt="image" src="https://user-images.githubusercontent.com/111305129/199331457-73124e86-9a04-41c1-bfe5-3a671625742c.png">

From the [Cloud.gov SSL/TLS docs](https://cloud.gov/docs/compliance/domain-standards/#ssltls-implementation)
> Our TLS implementation and cipher suites are consistent with [White House Office of Management and Budget’s M-15-13](https://https.cio.gov/), the Department of Homeland Security’s [Binding Operational Directive 18-01](https://cyber.dhs.gov/bod/18-01/), and the [NIST Guidelines for TLS Implementations](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-52r2.pdf). Some SSL/TLS scanners will nonetheless return results flagging the following ciphers as “weak”:
> ```
> TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003C)
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xC027)
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xC028)
> ```

I'm afraid this looks like another platform limitation. Unfortunately, we can't update the TLS protocol version for the browser-to-load-balancer part of the request, Cloud.gov handles that. According to their documentation, though, the implementation is secure and we should be able to ignore the finding.

**Comment by ADPennington** [comment]
Thanks @jtimpe this is helpful. I think we can document this on our false positive form and submit to TDP ISSOs. Once the security team approves we can close this ticket. cc: @stevenino @andrew-jameson @AiseosaO @tdrammeh1 

I'm wondering if we need to keep track of findings that show up in the security scans that will not get remediated. we have one for zap [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/Architecture-Decision-Record/016-zap-waiver.md) and maybe we should have a similar one for webinspect. 🤔

**Comment by stevenino** [comment]
False positives will be documented in ATO documents.
