### ISSUE TITLE
ZAP 2.12.0 has new backend alerts

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2222]
**Description:**
_Provide a brief background and justification for this issue_
After merging #2221 and #2218 we're seeing anew false positive. Need to investigate and resolve by either noting as false positive or fixing the backend issue but at a minimum we've prevented pipeline failures.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Either waive or resolve the backend alert.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate if there are new ZAP:2.12.0 issues with backend 
- [ ] If no real issues, create a waiver
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

https://output.circle-artifacts.com/output/job/57b543f2-2182-4c1d-99ba-b2e2e8c03095/artifacts/0/tdrs-backend/reports/owasp_report.html

**Open Questions:**

**Comment by ADPennington** [comment]
2.12.0 version of zap findings:

- frontend nightly on staging [here](https://output.circle-artifacts.com/output/job/96ebb11b-9b77-4a8b-b47c-810998f9d95e/artifacts/0/tdrs-frontend/reports/owasp_report.html)
- backend nightly on staging [here](https://output.circle-artifacts.com/output/job/165ac834-f51a-4d03-8981-fc05c155f334/artifacts/0/tdrs-backend/reports/owasp_report.html)

**Comment by lhuxraft** [comment]
@lhuxraft Incorporate into #2785, add information about evaluating other tools into #2785, then this ticket can be closed

**Comment by lhuxraft** [comment]
Closed, incorporated into 2785
