### ISSUE TITLE
Hashicorp Vault account set up with HA vault cluster plan

### ISSUE THREAD

**Issue by raft-twhitlock** [raft-tech/TANF-app#2225]
**Description:**
**Given** that I can log into a managed high available vault cluster in Hashicorp Cloud Platform, **then** I can see available key/value secrets **when** I have the correct policy and authenticated user logged in.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Hashicorp Cloud Platform account is created which can access a paid managed HA vault cluster
- [ ] Basic Policy is set up to log in user with correct roles to view key/value secrets
- [ ] Test key/value is able to be generated and viewed within a path/namespace
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Create account on trial version of Vault on the Hashicorp Cloud Platform
- [ ] Create admin role so when logged in through the vault cli I don't have to use the default root token
- [ ] Using key/value secret generator, create test secret within a path/namespace
- [ ] Create Policy that authenticates a test user and scopes the logged in user to path/namespace where test key/value is stored 
- [ ] After following items can be done in the trial account, switch to a paid managed HA vault account to repeat tasks in paid account

**Notes:**

- Docs for setting up and working with a managed vault instance is [here](https://developer.hashicorp.com/vault/docs)

**Supporting Documentation:**

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
