### ISSUE TITLE
As tech lead, I want stt_code field to retain leading zeroes

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2241]
**Description:**
_Provide a brief background and justification for this issue_
Per [this comment](https://github.com/raft-tech/TANF-app/pull/2236#discussion_r1015504289) we need to rework this field.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Model field `stt_code` is updated to retain leading zeroes
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Adjust model/create migration
- [ ] Rewrite code sections which deal with this field, if necessary
- [ ] Write additional unit test for "leading zero" case(s)
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by andrew-jameson** [comment]
@jtimpe Did the addtl work from 1641 make this obsolete?

**Comment by jtimpe** [comment]
@andrew-jameson yes, you're correct. this has already been implemented https://github.com/raft-tech/TANF-app/pull/2426

**Comment by andrew-jameson** [comment]
> @andrew-jameson yes, you're correct. this has already been implemented #2426

Thanks, @jtimpe !

Closing this out cc @ADPennington @Smithh-Co
