### ISSUE TITLE
As tech lead, I want trufflehog to catch fake key files

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2242]
**Description:**
_Provide a brief background and justification for this issue_
Per [this comment](https://github.com/raft-tech/TANF-app/pull/2236#discussion_r1014376554) we'll need to investigate this issue.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Trufflehog catches fake RSA files from testing
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Investigate root cause and resolve
- [ ] Test trufflehog pipeline job with fake RSA files
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_
