### ISSUE TITLE
As a data submitter, I want to receive 1 email notification per submission 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2248]
**Description:**

Currently, one email per submission _and_ file type  ([see here](https://github.com/raft-tech/TANF-app/blob/c42845e64154e18316d4b7cc7d729b4ae09fc662/tdrs-backend/tdpservice/data_files/views.py#L75)) is sent to all users associated with STT. This does not match the [mockup](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-has-been-submitted.html), which shows a table of all files submitted for a given fiscal period and program type (SSP or TANF). We should send 1 email per submission to all relevant users. 

Follow-on to #2291

**Acceptance Criteria:** 
- [ ] 1 `submit` email per submission is sent to any approved user associated with STT that also has data submission permissions 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Update [`.../data_files/views.py`](https://github.com/raft-tech/TANF-app/blob/c42845e64154e18316d4b7cc7d729b4ae09fc662/tdrs-backend/tdpservice/data_files/views.py#L75) and any other related code files (ref: #1845)
- [ ] Update tests 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- when an OFA Admin submits data, that user + any approved users associated with the STT should also get the email. 
- when a developer submits data, that user + any approved users associated with the STT should get the email. 
- ditto the above re:  users with `Data Analyst` role. 
- potentially lowest lift - `DataFileViewSet.create` needs to be modified to accept multiple file submissions, send email after each file has been placed on queue. may need to move clamav validation to queue. potential issue with file size and max upload size if multiple files included in single request. refactor frontend implementation to make a single http request

**Comment by stevenino** [comment]
@Alex to split this into 2 tix. This will be prioritized as low v3.1

**Comment by lhuxraft** [comment]
Closing, may reopen as it may inform future work on data submission processing
