### ISSUE TITLE
[Design Deliverable] Update Knowledge Center v3.0 updates (email notifications, submission history)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2250]
**Description:**

Adds screenshots and more detailed description of denial, inactivity, and deactivation emails to the knowledge center. Follow on from discussion in [#2220](https://github.com/raft-tech/TANF-app/pull/2220#discussion_r1015625649)
 
**Tasks:**

- [x] [Diana] Select a page / determine whether we should create a standalone "TDP Notifications" page for the added/updated content
- Need to discuss the Access Request Denied copy - is it reach out to TANF Data Portal help or TANF Program Manager during this expansion phase? 
- [x] [Diana] Create New Login page - add approved/denied screenshot
- [x] [Diana] Update screenshot for data submitted email to be aligned to more recent version of that template
- [x] Add content to submitting data page for Submission History
- [x] Edit the complete submission page for clarity about how it's not just about fTANF

**Notes:**

This might be a good opportunity to go ahead and create a standalone page to cover notifications info. Both in prep for having additional notification events with the addition of parsing and adding some user-control over non-account management notifications. 

**Supporting Documentation:**

- [Test Environment](https://reitermb.github.io/Test/knowledge-center/)

**Comment by lilybl1** [comment]
while we are waiting for final review of the v3.0 grantees shortlist, I can pick up the task for adding in the notifications

**Comment by reitermb** [comment]
As per standup, moved changelog task to #2371 to better slice knowledge center PRs
(one changelog item will be noting the addition of the FAQ page/linking to it)

**Comment by lilybl1** [comment]
@ADPennington @lfrohlich The first three tasks on this story are ready for review in the Test environment. https://reitermb.github.io/Test/knowledge-center/about-email-notifications.html -- I did have a question regarding the Access Request Denied email - Long term we discussed any questions would go to the TANF Program Manager which is how it is coded right now, but during the pilot period - does that still make sense or should it go to TDP Support?

**Comment by ADPennington** [comment]
thanks @lilybl1! some notes below:


> You will receive a notification email from no-reply@tanfdata.acf.hhs.gov when your access request has been submitted. Please allow up to 1 business day for OFA admins to review your request.

can we bold/italicize `no-reply@tanfdata.acf.hhs.gov`? is there an a11y concern with this? please also double-check that the formatting decision is consistent throughout the knowledge center. 

> Data Submitted by Section

We now distinguish data submitted by  program/file type (i.e. TANF, Tribal TANF, and SSP) _and_ section. See example below:
![2250p1](https://user-images.githubusercontent.com/63075587/215500710-082ba357-53a8-4d17-a254-22b3da30b202.PNG)

> We expect TANF Data Portal users to be active grantees. If an account has not been logged into the TANF Data Portal for 180 days, the process to deactivate the account will be set in motion.

for discussion at UX sync: do we want to keep the `grantee` language for now, or do a full audit later? Still, i think we can drop this first sentence. 

also: are we adding the `deactivated` email?

**Comment by lilybl1** [comment]
Tasks 1-4 have been updated in the Test environment including the comments from Alex (above).

**Comment by Smithh-Co** [comment]
-- Migrated commentary outside of ticket -- CS

**Comment by lilybl1** [comment]
Moving over for QASP Review

**Comment by lilybl1** [comment]
I've removed the bullet in the Tasks about adding the info memo until #2300 is complete.

**Comment by lilybl1** [comment]
@ADPennington Moving over to QASP Review after reviewing with @Smithh-Co and @reitermb

**Comment by lfrohlich** [comment]
Great new content @lilybl1 ! One thing -- In the future, it is much easier to review and comment in hack.md, so I would prefer to review new or revised content in a hack.md before its moved to the test environment. Thanks!

**Create a new login.gov Account**
In answer to your question, I think denied requests should be directed to tanfdata@acf.hhs.gov at this point. @ADPennington do you agree? Can we update the email text and screenshot as well? 

**About Email Notifications**
There is some inconsistency with use of TANF Data Portal vs. TDP and whether there is a "the" before it. I think it should be TDP after the first TANF Data Portal, so both instances in #4 would be TDP

**Submitting Data to TDP**
Under "How to retrieve your submitted data", please update text to link to submission history page. 

**Viewing Submission History**
> On the Data Files page you’ll be able to fill out the search fields for ‘File Type’ (if your program submits both TANF & SSP data), ‘Fiscal Year’, and ‘Quarter’ to identify which data you’ll be uploading.

what if you just want to view the submission history and not upload? 

- instead of "time frame" should it be "which data you would like to view" or something else that includes "type"?

- under #2 should there be an instruction to click "submission history"?

**Resubmitting Complete Data Files** 
- Under example, replace "STT" with "a state"

**Comment by ADPennington** [comment]
thanks @lilybl1!  notes below:

- re: Viewing Submission History
> The Submission History tab within the TANF Data Portal (TDP) will allow you to be able to access all of your past submitted data files.

edit suggestion:
_The Submission History tab will allow access to all data files previously submitted via the TANF Data Portal (TDP) ._

> Choose the time frame you would like to view

edit suggestion: 
_Choose the timeframe you would like to view_

> On the Data Files page you’ll be able to fill out the search fields for ‘File Type’ (if your program submits both TANF & SSP data), ‘Fiscal Year’, and ‘Quarter’ to identify which data you’ll be uploading. After searching for the appropriate reporting period, a new area of the page will appear below the search button.

edit suggestions:
_On the Data Files page, you can complete the search fields for ‘File Type’ (if your program submits both TANF & SSP data), ‘Fiscal Year’, and ‘Quarter’ to identify which data will be uploaded. After searching for the appropriate reporting period, a new area of the page will appear below the search button._

> The button group 'Current Submission' and 'Submission History' will only appear if there were previously submitted data files for the 'Fiscal Year' and 'Quarter' through TANF Data Portal.

i dont think this is true. i think both buttons appear after search regardless of previous submission status. 
![2250p1](https://user-images.githubusercontent.com/63075587/216686385-0f49ff24-8a35-42e9-9d4b-fa8659b49608.PNG)

> Submitted On: The date and time the data file were submitted
> Submitted By: The user who submitted the data file
> File Name: The name of the data file is clickable and downloads the file

edit suggestion:
_Submitted On: The date and time the data file(s) were submitted_
_Submitted By: The user who submitted the data file(s)_
_File Name: The name of the data file(s) are clickable and downloads the file_

- re: Resubmitting Complete Data Files

> After the data submission deadline, the Administration for Children & Families (ACF) performs quality assurance and checks across records, ensuring the information is accurate. If any errors are found in the data files submitted, ACF will notify you via email, with an error report containing a summary view of the issues. The following provides guidance on how to resubmit data files after the errors have been corrected.

edit:
After data files are submitted, ACF checks the data for accuracy and completeness. If any errors are found in the data files submitted, ACF will notify you via email, with an error report containing a summary view of the issues. The following provides guidance on how to resubmit data files after the errors have been corrected.

i would also bold the following:

> Transmitting complete data for Sections 1 and 2 (Active and Closed Cases, respectively) is as simple as making sure that each file submitted (or resubmitted at a later date) contains all of the cases you intend to submit for the quarter. Sections 3 and 4 (Aggregate and Stratum Data, respectively) contain population counts, so transmitting complete data for those sections means ensuring that all the counts are present for each month in the quarter.

The placement of the link to ftanf guidance seems a little unexpected. i wouldnt expect it in this section (about the header). it seems like it could be its own section. 

- re: Exporting Complete Data using fTANF

maybe consider dropping the section on "Whats changing in TDP" and "Why we're making this change" since its on the other page. or link to the other page. i don't feel strongly about it, especially if its a lot of extra work.

**Comment by lilybl1** [comment]
@lfrohlich @ADPennington 
The above have been revised in the Test Environment with the exception of two items:
- [ ] Create a new login.gov Account - In answer to your question, I think denied requests should be directed to [tanfdata@acf.hhs.gov](mailto:tanfdata@acf.hhs.gov) at this point. [@ADPennington](https://github.com/ADPennington) do you agree? Can we update the email text and screenshot as well? **Follow-up** This will require a dev ticket to change it in the email as well. Do we want to wait until this is consistent? 
- [x] Resubmitting Complete Data Files - Under example, replace "STT" with "a state". **Follow-up** is this accurate - are only states submitting partial data sets? What about territories?

**Comment by lfrohlich** [comment]
> * [x]  Resubmitting Complete Data Files - Under example, replace "STT" with "a state". **Follow-up** is this accurate - are only states submitting partial data sets? What about territories?

The suggested edit is because STTs aren't necessarily familiar with the acronym "STT". I just said "state" because this is an example, we could say " a state, tribe, or territory" instead

**Comment by lfrohlich** [comment]
@lilybl1 one other thing I noticed -- there is an extra line break in the middle of no-reply@tanfdata.acf.hhs.gov under "Not seeing email notifications?"

![image.png](https://images.zenhubusercontent.com/5f19ca7a632be8361aab1300/38069787-5c85-4cd5-814a-9da297d1d62a)

**Comment by lilybl1** [comment]
This is ready for a11y review. 
@ADPennington We can review the open item related to the "Access Request Denied" email - Create a new login.gov Account - In answer to your question, I think denied requests should be directed to [tanfdata@acf.hhs.gov](mailto:tanfdata@acf.hhs.gov) at this point. [@ADPennington](https://github.com/ADPennington) do you agree? Can we update the email text and screenshot as well? Follow-up This will require a dev ticket to change it in the email as well. Do we want to wait until this is consistent?

**Comment by ttran-hub** [comment]
Thanks @reitermb @lilybl1, Updates to the knowledge center are A11y ready.  cc @lfrohlich @ADPennington
