### ISSUE TITLE
As a developer, I want a more organized CircleCI pipeline parameters

### ISSUE THREAD

**Issue by n0remac** [raft-tech/TANF-app#2260]
**Description:**

As a developer I would like the deployment pipeline to be as easy to understand as possible. The structure of how parameters are created in workflows and passed to jobs and commands is confusing and creates many extra lines.

I want those parameters to be lifted out of the Circle Ci config and put into an env file. Parameters that are dependent upon where they are deployed from should be added to the env file within the circle ci runner, before the pipeline starts (eg when the generated_config.yml is created).

**Acceptance Criteria:** 

- [ ] CICD pipeline runs the same as before
- [ ] One env file is used to supply variables to wherever they need to be used.
- [ ] When deploying to a cloud instance env variables that are specific to that environment are generated and added to the env file. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Simplify and organize cicd pipeline parameter usage via an env file
- [ ] Avoid declaring parameters in pipeline
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Is the resulting implementation less confusing and more organized?

**Comment by stevenino** [comment]
After some investigation and discussion. No longer required.
