### ISSUE TITLE
[SPIKE] Investigate clamav-related network error

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2268]
**Description:**
During v2.2, we've observed 4 states and 1 territory running into instances of network errors when users submit files. 

Today, I uploaded and submitted 3 files for VI at one time. 2 of the 3 were successfully submitted after clean scan, and the other one didnt submit -- resulting in network error returned on frontend.  I resubmitted that one and it was successful. 

_clamav logs of 3-file submission_
```
11:23:32.495: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Started scanning: ADS.E2J.NDM2.TS78
11:23:32.507: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Started scanning: ADS.E2J.NDM3.TS78
11:23:32.508: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Scan result for: ADS.E2J.NDM2.TS78, &{stream: OK  stream  0 OK}
11:23:32.508: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Finished scanning: ADS.E2J.NDM2.TS78
11:23:32.520: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Scan result for: ADS.E2J.NDM3.TS78, &{stream: OK  stream  0 OK}
11:23:32.520: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Finished scanning: ADS.E2J.NDM3.TS78
11:23:32.676: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Started scanning: ADS.E2J.NDM1.TS78
11:23:32.710: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Scan result for: ADS.E2J.NDM1.TS78, &{stream: OK  stream  0 OK}
11:23:32.710: [APP/PROC/WEB.0] 2022-11-15T17:23:32+01:00 Finished scanning: ADS.E2J.NDM1.TS78
```

_resubmitting 1 file 2 min later_
```
11:25:57.662: [APP/PROC/WEB.0] 2022-11-15T17:25:57+01:00 Started scanning: ADS.E2J.NDM1.TS78
11:25:57.665: [APP/PROC/WEB.0] 2022-11-15T17:25:57+01:00 Scan result for: ADS.E2J.NDM1.TS78, &{stream: OK  stream  0 OK}
11:25:57.665: [APP/PROC/WEB.0] 2022-11-15T17:25:57+01:00 Finished scanning: ADS.E2J.NDM1.TS78
```

_DAC showing only 3 clean scans while clamav logs (above) shows 4__
![VI](https://user-images.githubusercontent.com/63075587/201996579-4b4bac20-d58f-472f-87c0-08791fbab6f9.PNG)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Find root cause and write follow on tix to address issue
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
### 12/6/2022 Update

Another STT experienced this issue today. Notes below:

- when re-submitting 3 TANF files (Sections 1, 2, 3) simultaneously for FY22,Q4, they received a network error notification. 2 of the files were successfully submitted. 
- user resubmitted several times in an attempt to get a "successful submission" notification. Evidence of the resubmissions below. Notice that Section 1 resubmissions only appear toward the end. file size = 20.44MB, whereas the other file sizes were <1MB. 
![2268p1](https://user-images.githubusercontent.com/63075587/206032557-514c35b5-ba7a-4e7b-b7cd-7ec7fe6fd22c.PNG)


**Worth investigating if this is related to clamav needing more time to scan large files. We expect Section 1 files to be the largest files that STTs submit.**

**Comment by jtimpe** [comment]
Test
- large files (T1 is largest file, failures seem consistent)
- multi-file upload (multiple concurrent submissions may overload the clamav instance)
- muti-large-file upload, combination of above
- may not be able to reproduce locally, make sure to test in deployed

potential paths
- adjust number of workers of (?) app? clamav?
- likely want to move clamav check into the celery queue with other file upload logic

**Comment by ADPennington** [comment]
additional test files (including large files) [here](https://hhsgov.sharepoint.com/:f:/r/sites/TANFDataPortalOFA/Shared%20Documents/General/Legacy%20System/Dummy%20data?csf=1&web=1&e=Jq8SRo)

**Comment by ADPennington** [comment]
### 12/7/2022 Update

We observed this again today during a moderated session with an STT. 
- all files submitted at same time
- Section 1 file did not successfully submit and network error returned to user. 
- user clicked submit button a few times because of the latency (note: ive seen this network error even when the submit button clicked once)
- resolved via resubmission. 
 
Screenshot shows logs. scan start and completion varies by size. 
| File | Scan Start | Scan Complete     | File Size |Notes|
| -------- | -------- | --- | -------- |-------- |
| Aggregate     | `Dec 7, 2022 @ 16:16:59.799`    |  `Dec 7, 2022 @ 16:16:59.861`   | `429.00B`    |Start and completion of scan happened normally. ![](https://i.imgur.com/JUd6PUX.png)|
| Closed     | `Dec 7, 2022 @ 16:17:00.731`    | `Dec 7, 2022 @ 16:17:00.770`  | `132.22KB`   |Start and completion of scan happened normally. ![](https://i.imgur.com/oQN6Twx.png)|
 | Active     | `Dec 7, 2022 @ 16:17:24.543`    |  `Dec 7, 2022 @ 16:17:24.844`   | `1.97MB`    |Logs suggest several scan starts happening for this file before the first completed results. Pattern: `Start scan,Start scan,Start scan,Clean scan,Clean scan,Post 201,Post 500,error (DETAIL: Key (section, version, quarter, year, stt_id)=(Active Case Data, 1, Q4, 2022, 2) already exists.),Post 200,Transfer to titan` ![](https://i.imgur.com/gLyGTL1.png)|

cc: @ttran-hub

**Comment by lilybl1** [comment]
@ADPennington Updated description above to include number of occurrences for severity.

**Comment by ADPennington** [comment]
i was able to reproduce the error in staging this morning:

- first attempt
   - used files [here](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Jq8SRo&cid=b9e57600%2D9712%2D4a65%2Dafe2%2D72f72f3ef4c4&RootFolder=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FLegacy%20System%2FDummy%20data&FolderCTID=0x01200039BDB10EB450C04FB647A089E033E116)
   - clicked submit once
   - took ~30 seconds to see the successful submission notification
   - backend shows all files transferred
   
- second attempt
  - same files used for a different STT
  - clicked submit once then after 6 seconds clicked it 2 more times
  - about 30 second later got successful submission then a couple seconds later, banner changed to 500 error. 
  - backend shows that section 1 file scanned clean but not transferred, all others transferred

- 3rd attempt
  - same files used for a different STT
  - clicked submit 3 times (once per second)
  - network error returned after about 1 second after the last click
  - no scan result for section 1
  - backend shows the *non-Section 1* files were transferred to Titan
  - i never got a data submission email. 
  

cc: @reitermb @lilybl1 @ttran-hub

**Comment by raftmsohani** [comment]
When clicking submit more than once, if clamav is successful then celery worker will have memory leak. Since the memory is set to limit (at the time it is set to 5M) and the file has t be loaded to memory then worker receives SIGKILL 

![image](https://user-images.githubusercontent.com/97037188/211038020-9a1d2505-9e9d-4d74-9cbc-0b704fc11669.png)

**Comment by raftmsohani** [comment]
Looks like for large files, the memory leak happens from time to time depending on the worker status and file size. Solution can be to increase the memory limit here: 
```
celery -A tdpservice.settings worker -c 1 --max-memory-per-child 5000 &
```

**Comment by raftmsohani** [comment]
Two issues to be resolved:
- The user should not have possibility to click upload/submit_file more than once. We can reenable the submit button after upload task result (either file uploaded or failed)
-  The per child memory cap for celery worker is due to memory limitations and there is trade of between celery task memory and the server memory. It is a known issue and is strongly suggested to have higher memory

**Comment by raftmsohani** [comment]
Another suggestion is to move clamav task scheduler and have the scans be performed as celery task async. Celery tasks then can be linked (see [celery task linking](https://docs.celeryq.dev/en/stable/userguide/calling.html#linking-callbacks-errbacks)) and upload can be done after receiving success signal from clamav

**Comment by raftmsohani** [comment]
Another suggestion is to limit paramiko (SFTP upload package) file chunks (see [this](https://stackoverflow.com/questions/12486623/paramiko-fails-to-download-large-files-1gb)). This solution limits memory usage for large files. If we take this approach, we should be careful to increase wait time for celery, since the upload task will take longer and celery task might assume the task has failed.

**Comment by raftmsohani** [comment]
Follow up tickets created: ( I am updating this as I create tickets)

- #2350 
- #2351
- #2353
