### ISSUE TITLE
Draft expected outcomes for STT research 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#227]
Description:
Based on the approved research goals #226 , draft what we are hoping to learn as outcomes and outputs and how we plan to use outcomes to inform the next round of research or as actionable learnings. The finalized outcomes will be part of the STT research plan (Round 3 of research). 

**AC:** 

- [x] Expected outcomes are actionable and are ready to be included in the research plan #63 

**Notes:**
- These expected outcomes may be updated after #170 (conversation guide) is complete.
- This will not be included in gov review for Sprint 3. 

** Tasks:**
 
   - [x] Draft expected outcome with actionable learnings including outputs (diagrams, documents, etc.)
   - [x] Schedule pairing session w/ 18F and OFA to work through the outcomes
  - [x] Document feedback and update goals #226, if necessary
 
Deliverable(s):
- Expected outcomes document can be found [here](https://teams.microsoft.com/l/file/D5515940-BC9F-444C-A280-BF829605A0AC?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2FSTT%20Research%20September%202020%2F%23227%20-%20September%20User%20Research%20Expected%20Outcomes%20-%20STTs.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):

**Comment by matthewjdoty** [comment]
The working file can be found [here](https://teams.microsoft.com/l/file/D5515940-BC9F-444C-A280-BF829605A0AC?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FDesign%2FSTT%20Research%20September%202020%2F%23227%20-%20September%20User%20Research%20Expected%20Outcomes%20-%20STTs%20DRAFT2.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:e92913e3e7d443adb823e6497dff1fb3@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Comment by cmajel** [comment]
@matthewjdoty this looks good to me and ready to demo 👍 If we do demo this, it might be helpful to show them alongside the research goals.

**Comment by lfrohlich** [comment]
Looks good to me as well!

**Comment by lfrohlich** [comment]
This was completed in Sprint 4
