### ISSUE TITLE
As technical lead, I want our user approval flow tested

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2274]
**Description:**
Spin-off of #2141, we want to build an end-to-end test flow. This ticket will focus on an authenticated user test-flow.

**Acceptance Criteria:** 

- [ ] Integration tests cover critical path of automated user being approved
- [ ] Test flow can be run both in CircleCI and deployed environments
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Implement test(s) for normal-case user access request
- [x] Implement test/trigger for transition of user status from initial/pending to approved/denied
- [x] Implement user being assigned Data Analyst role and their STT
- [x] Ensure failed test notifies runner (human or CircleCI)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
- Should we reuse an existing STT or create a fake/test STT?
- Should test be from the perspective of a data analyst or system administrator?
- Should we implement a test-flow for system administrator in addition? (why not both? we need to perform the action anyway)
