### ISSUE TITLE
[Design Deliverable] A11y Testing 101 Doc 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2275]
**Description:**

Delivers "How to a11y" content aimed at enabling the dev team to shift more a11y testing left. The big goal being to overview what to look for and how to look for it when it comes to common 80% a11y issues that have come up in past raft/gov a11y reviews. This ties into ongoing non-ticketed work to build a "State of a11y in TDP doc", but specifically delivers on the dev-enablement aspects of that. 

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Dev/Design sync has occurred
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Write up high level a11y testing framework 
- [x] Update & pull in existing documentation regarding a11y testing tools & how to use them
- [x] Get some light review from anyone willing from the dev team

**Supporting Documentation:**

[Hack.md](https://hackmd.io/@mreiter/ByVulbdQd)

**Comment by reitermb** [comment]
Drafted! cc @stevenino

**Comment by stevenino** [comment]
@ADPennington ready for QASP

**Comment by stevenino** [comment]
@andrew-jameson Also looking for dev review on this content

**Comment by stevenino** [comment]
Merged
