### ISSUE TITLE
[spike] Why is nightly scan not running on prod?

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2279]
**Description:**

Since merging v2.2.2, nightly scan workflow is running on hhs:main but not initiating on hhs:master. cannot investigate by re-running failed nightly scans that are running on v2.2.1 commit because we need it to run on latest commit. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] nightly owasp scan triggers as scheduled on v2.2.2 commit
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] test more frequent trigger on fork to prod
- [x] try manually triggering on new commit ([reference](https://circleci.com/docs/triggers-overview/#run-a-pipeline-from-the-circleci-web-app))
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [_Doc 1_](https://circleci.com/docs/triggers-overview/#run-a-pipeline-from-the-circleci-web-app)

**Comment by ADPennington** [comment]
### 11/21/2022 Update

[triggering the pipeline from CircleCI web app](https://circleci.com/docs/triggers-overview/#run-a-pipeline-from-the-circleci-web-app) worked.  This triggered all the _unscheduled_ workflows (ie. `build-and-test` and `production deployment` ) on the master branch on the latest commit. Then later, the scheduled nightly scanned triggered and has been running successfully since Friday. See below:

![2279](https://user-images.githubusercontent.com/63075587/203082010-48b2ef37-6b30-4102-926e-e25b3d3abe3c.PNG)

Closing as completed.
