### ISSUE TITLE
As technical lead, I want a file upload integration test 

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2282]
**Description:**
_Provide a brief background and justification for this issue_
#2141 spin-off, we want a full end-to-end test flow for the critical data analyst user path.

**Acceptance Criteria:** 

- [ ] An authenticated, approved test user can successfully upload a file.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ]  Implement mechanism for searching year/quarter prep for file-upload
- [ ]  Implement test(s) for normal-case file upload with standard test file
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by raftmsohani** [comment]
No update on this one, started looking at it again
