### ISSUE TITLE
As a developer, I want to run codecov during local development

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2283]
**Description:**
_Provide a brief background and justification for this issue_
To improve the developer experience, we'd like to be able to run codecov either automatically through an IDE or some set of commands/alias/pre-commit hook to prevent extraneous CircleCI runs.

**Acceptance Criteria:** 

- [ ] A developer can run codecov on their local machine with minimal configuration/steps (ideally an alias in `commands.sh`)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Investigate parameters from the job [`upload-codecov`](https://github.com/raft-tech/TANF-app/blob/c6a301c51caa8f6a30c818a8a9b759b56826992e/.circleci/config.yml#L107) for local usage
- [ ] Write any relevant setup documentation
- [ ] Either write a utility alias or the relevant VSCode configuration
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

Not sure. Defer to dev team.

**Comment by robgendron** [comment]
Deemed no longer needed by Dev.
