### ISSUE TITLE
As a new user, I can select an applicable STT or OFA category from the combo box 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#229]
**Description:**

After the user creates a login.gov user account (#191), they must also select an STT or OFA category. This issue will deliver a searchable combo box and enable the user to choose an applicable category. 

**Acceptance Criteria:** 

- [x] After a user signs in via the [TDP frontend](http://tdp-frontend.app.cloud.gov/), the page displays a combo box to search for and select an STT/OFA
- [x] The STT list matches the list provided by OFA and is displayed alphabetically 
- [x] User can search for and select an STT from the combo box, matching specified search behavior, and experience outlined in [USWDS combo box 2.0](https://designsystem.digital.gov/components/form-controls/#combo-box) guidelines
- [x] Placeholder text for search field is displayed as "Select or Search"
- [x] Color may not match ACF color
- [x]  Testing Checklist has been run and all tests pass

**Tasks:**

- [x] Finalize contents of combo box

Frontend
- [x] Fetch the STT data from backend API
- [x] Add search and filter combo box for STTs 
- [x] Write front end unit tests
- [x] Run Front End Testing Checklist and confirm all tests pass

Backend
- [x] Create STT model/app using [STT region list](https://teams.microsoft.com/l/file/d3ce1f7f-8455-473d-bed3-4c963209e127?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=xlsx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FTribes%20State%20Region.xlsx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&messageId=1598971985825&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) :lock: to provide contents for a combo box dropdown list of selectable STTs
- [x] Create/run STT migrations
- [x] Create endpoint to serve STTs
- [x] Create/run Region migrations
- [x] Build in relationships between Users, STTs, and Regions
- [x] Write unit tests for STT model
- [x] Write unit tests for Regions model
- [x] Write unit tests for STT API endpoint

**Notes:**

- Form validation will be addressed by #230
- New user profile creation will be addressed by #231
- STT list management will be addressed by #23
- Based on the projection that regional users will need to be defined as such, and their view permissions will be defined by the region we are going to create regions as a separate entity from STTS. This will impact estimates on this ticket as creating the separate entity and testing that entity creates more work than originally estimated. For MVP, users will still only be able to sign in as an OFA Admin or an STT, so the only change at this time will be in the back end. The estimated change will most likely cause the backend work to spill over into Sprint 5.

**Supporting Documentation:**

- Approved [UI design](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=628%3A468) 
- [USWDS 2.0 guidelines](https://designsystem.digital.gov/components/form-controls/#combo-box) for search and combo box functionality 
- Accessibility guidelines for [form controls](https://designsystem.digital.gov/form-controls/) and [form templates](https://designsystem.digital.gov/form-templates/)   

**Open Questions:**
- Contents of the combo box have not been finalized - resolved. notes in comments
- Search behavior has not been defined - resolved. notes in comments

**Comment by shubhi-raft** [comment]
The backend tasks of this issue will be worked on Sprint 4 and will be available for spot check. However, the frontend tasks will most likely start on Sprint 5.

**Comment by shubhi-raft** [comment]
Search behavior has not been defined:
- For MVP, we will use combo box USWDS native functionality.

**Comment by shubhi-raft** [comment]
In response to the search behavior functionality - 

> Open question: `Search behavior has not been defined` . For MVP, we will use combo box USWDS native functionality.

@hilvitzs Thanks for updating the GitHub with your note. Pasting it below:

**FOUND ISSUES WITH COMBO BOX**
- USWDS - The Combo Box from USWDS does not properly render as a combo box every time the page is rendered. This is a known issue that has received no USWDS attention here: https://github.com/uswds/uswds/issues/3599. This also causes the page to throw an error when the normal Select is rendered instead of the Combo Box because it is not getting the information it expects.
![Screen Shot 2020-10-05 at 7.48.19 AM.png](https://images.zenhubusercontent.com/5f4faeb5563b71775a41722c/ae75389e-04ed-4538-a1c1-aa1ab8a9f140)

- The `react-select` combo box has some accessibility issues. On mobile, when using VoiceOver, a user cannot select an STT from the dropdown and there were some visually confusing elements when using a Screen Reader that makes it less than ideal for users with visual impairments.

- The Ant design system combo box does not allow for styling and requires the use of `!important` or doubling up of classes to style elements. This does not have the same accessibility issues that `react-select` had but only a cursory accessibility test happened before finding out the styles are not customizable so there could be other accessibility concerns that come up during a more in-depth review even if there was a way to style components.

cc @alexsoble @lfrohlich @reitermb

**Comment by lfrohlich** [comment]
Thanks @hilvitzs @shubhi-raft for the update! What alternatives/next steps would you recommend?

**Comment by shubhi-raft** [comment]
@lfrohlich - @hilvitzs added options to the Teams [doc](https://teams.microsoft.com/l/file/4fe8ee7a-f6e3-42e2-8ac8-7efd0698a401?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fdev%2FCombo%20Box%20Issues.docx&serviceName=teams&threadId=19:96fae73b37194050a5fb671ddf2380e3@thread.skype&messageId=1601923220567&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) :lock: that we could explore

**Comment by RafterGit** [comment]
@hilvitzs found a solution to the USWDS combo-box issue and is currently testing with @reitermb today(10/7/2020)

**Comment by alexsoble** [comment]
@shubhi-raft @hilvitzs  I shared out initial info on Teams today documenting a v1 of how 18F will approach a11y testing, so hopefully this is unblocked on that front!

**Comment by lfrohlich** [comment]
The combo box works great! The only thing I noticed is that the placeholder text is missing (Select or Search) -- please add this for this sprint.

Follow up issue, not a blocker to this PR: consider whether we want Federal Government at the top of the list and if we should change the label (since Fed Govt isn't an STT). Also, I think we'll want to change the language "We need to collect some information" because it raises PRA flags (event though it doesn't actually hit PRA).

**Comment by lfrohlich** [comment]
This was merged October 23
