### ISSUE TITLE
As a data submitter, I want to receive email notifications when data is submitted

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2291]
**Description:**

Only users with `Data Analyst` role receive email notifications ([see here](https://github.com/raft-tech/TANF-app/blob/c42845e64154e18316d4b7cc7d729b4ae09fc662/tdrs-backend/tdpservice/data_files/views.py#L88)). All users with data submission permissions should receive email notifications. 

Related to #2248 

**Acceptance Criteria:** 
- [ ]  All approved users with data submission permissions  (`Developer`, `OFA Admin`, `Data Analyst`) receive email notifications for data submitted.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Update any other related code files (ref: #1845) 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- OFA Admins are intended to be ACF users, who cannot fill in an STT on request form ([ref](https://github.com/raft-tech/TANF-app/issues/1640)). This is because their role permits them to submit data on behalf of any STT. 
- If an OFA Admin submits data, anyone associated with the STT will get the data submission email except the users with the `OFA Admin` role. this ticket should ensure OFA Admins get the email too. 
   - Do we want OFA admins to only receive notification emails for submissions they personally uploaded or do we want them to receive all data submission notifications (including those initiated by STTs)?
   - Do we expect this scenario (OFA admins uploading on behalf of STTs) to ever happen? 
   - Should this scenario (OFA admins uploading on behalf of STTs) be allowed?
- Users with `Developer` role can only submit data for the STT in their profile. they currently do not get an email, but they should, for testing purposes. As a reminder: this role only exists in non-prod environments. 
   - Non-prod, but should Developers have the same notification behavior as Data Analyst users? e.g. start receiving notifications for submissions they make *and* also receive notifications for submissions others make to their assigned STT?

**Comment by ADPennington** [comment]
this is an enhancement. not needed for parity cc: @lfrohlich
