### ISSUE TITLE
As a user, I cannot submit my profile information unless my inputs are valid.

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#230]
**Description:**
This issue will only deliver validation of user profile data that can be saved, and guides a user to task success through visual cues. This issues will not deliver form time outs (#331).

All work for this is done and ready for internal review except for the following issue:

We are still having an issue with USWDS Combo Box where it looks like it can't be cleared when you blur out of the Combo Box after the clear button is pressed. There is more information in this PR: https://github.com/raft-tech/TANF-app/pull/348

**Acceptance Criteria:** 

- [x] [Error message is displayed in a way consistent with USWDS](https://designsystem.digital.gov/components/form-controls/#validation) when fields are not valid
- [x] Testing Checklist has been run and all tests pass
- [x] New issues for form timeouts is created #331

**Tasks:**
- [x] Discuss what is the appropriate validation (check against phone numbers, email addresses, phrases are not in first and last name field)
- [x] Pair with raft UX to display [error message](https://designsystem.digital.gov/components/form-controls/#text-input)
- [x] Create validation functions to ensure first and last name fields contain valid data and checking for a minimum length of 1 character
- [x] No validation is performed until the submit button is pressed and then removed as each error is resolved
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
- This issues will not deliver form time outs - 18F's Accessibility Guide for [Timeouts](https://accessibility.18f.gov/timeouts/)
- Valid data for the first name and last name fields is defined as "not empty"
- Valid data for the STT combo box is "not empty"
- Verification of valid profile submission functionality is from #231

**Supporting Documentation:**

- 18F's Accessibility Guide for [Timeouts](https://accessibility.18f.gov/timeouts/)

**Open Questions:**

- What is the actual acceptable character set for the first and last name fields?
   - We are only checking for a minimum length of 1 character - we are not validating the characters themselves
- What should be displayed to users when invalid characters are entered in the first and last name fields to help them understand why the Submit button has not been enabled after they enter invalid data?
   - Following [USDWS guidelines](https://designsystem.digital.gov/components/form-controls/#text-input) for validation display

**Comment by lfrohlich** [comment]
This was merged
