### ISSUE TITLE
[Research Recruitment] Reach out to additional grantees to enable 3.0 errors research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2302]
**Description:**

Owing to fewer errors (in November data) than anticipated our pool of grantees to recruit for 3.0 research (#626) is smaller than we'd like. This ticket delivers a refinements to our grantee shortlist & initial communication steps to reach out and get them into our research pipeline. 

**AC:**

- [x] Grantees added to shortlist have been contacted.
- [x] Tracker is updated to reflect/track communications

**Tasks:**

- [x] Coordinate with Alex to refine shortlist
- [x] Coordinate with regional staff to contact new grantees
- [x] Update tracker

**Supporting Documentation:**

- [Mural - Recruitment Tracking](https://app.mural.co/t/raft2792/m/raft2792/1670863789542/91ef3f15f55f09eb842ce3419f38e6c601074949?sender=u3ca60168b5ac4eb17bf92804)

**Comment by stevenino** [comment]
Waiting on @ADPennington for the updated spreadsheet.
