### ISSUE TITLE
[Design Deliverable] Design loading state spinner for TANF and SSP

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2306]
### Background ###
(FRA spinner will be implemented separately, this should be focused on unifying submission history across the frames)

This ticket was created in response to feedback received during the v2.2 pilot. Users, particularly Data Analysts, have been submitting data files rapidly due to the absence of a clear loading state, leading to unintended duplicate submissions. To address this, we aim to implement a loading state for the data files submission button and page. This will help prevent users from submitting the same data multiple times, especially before the file has completed the submission process.

Currently, when files are submitted, they are processed quickly (within 10 seconds), but there is no indication of progress, which results in duplicate submissions. As a Sys Admin, the goal is to reduce or eliminate these duplicate submissions to streamline operations and improve the user experience.

### Tasks ###
- [x] Design loading state for submit button
- [x] Create Figma design
- [ ] Sync with dev/design teams
- [ ] Develop follow-on ticket(s) for implementing design and loading state

### Acceptance Criteria ###
- [ ] Complete dev/design sync
- [ ] Design meets markup and accessibility considerations
- [ ] Follow-on tickets developed and reviewed

### Supporting Documentation ###
[Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8006-50591)

### Prioritization ###
- Reach: 127 (number of STT submitters)
- Impact: 1 (medium impact)
- Confidence: 95%
- Effort: 2 person weeks

**Comment by lilybl1** [comment]
Splitting this ticket into two parts: handling the current state with the spinner/loading and a future state when parsing is ready to go.

**Comment by reitermb** [comment]
![loader-svg](https://user-images.githubusercontent.com/28515874/227022288-538b3f5d-47d9-42c9-8bd3-2a8249d05cc0.svg)

Spinner asset

**Comment by lhuxraft** [comment]
Shifting to unified submission history via FRA data (may be handled that way in the future) - worth keeping open until that effort is over

**Comment by lhuxraft** [comment]
The spinner has already been designed - closing this and will create follow up dev implementation tickets for backlog
