### ISSUE TITLE
As a user, I can fill out and submit a form to create my profile.

### ISSUE THREAD

**Issue by adamcaron** [raft-tech/TANF-app#231]
**Description:**
When a user signs in for the first time, they are prompted to create a profile. This issue covers enabling submittal of the form containing first and last name (from #191) and an STT/OFA combo box (from #229) via an API and saving the user's profile to a database. 

**Acceptance Criteria:** 

- [x]  User can enter first and last name into form, and select STT/OFA from combo box (from #191 and #229)
- [x]  User can submit form, and is taken to new page in accordance with design 
- [x]  [Lauren's comments on 229](https://github.com/raft-tech/TANF-app/issues/229#issuecomment-714569850) have been addressed or new ticket has been created to track them
- [x] Testing Checklist has been run and all tests pass

**Tasks:**
UX (@reitermb):
- [x] Discuss with @mfkathleen and @lfrohlich to update description text "We need to collect some information" to something else that does not trigger PRA 
- [x] Lauren + Raft UX team to discuss with Denise whether it ok to say associate tribe (as opposed to tribal organization).

Frontend
- [x] Evaluate moving 'Federal Government' top of the list. Move it to the top of the list if it is quick fix. If it cannot be moved, create a new issue to implement. 
- [x]  Implement `PATCH` to new `PATCH` endpoint once form controls are validated
- [x]  Implement redirect on successful submission
- [x]  Run Testing Checklist and confirm all tests pass
- [x]  New ticket is created for authentication integration testing with Cypress and Pa11y OTP

Points: 3

Backend

- [x]  Create `PATCH` endpoint for STTs to update the user's profile
- [x]  Create tests to test the new endpoint
- [x]  Create tests to cover lines 22->37, and 37->41 of the authorization check endpoint to complete test coverage
- [x]  Run Testing Checklist and confirm all tests pass
- [ ] Set `/v1/authorization-check` endpoint to return users the same as the `/v1/set_profile` endpoint
- [ ] Add email to the `/v1/set_profile` endpoint
- [ ] update tests accordingly

Points: 3

**Notes:**
- Frontend will not be done in Sprint 5. 
- The first and last name fields, and Submit button will be added by #191
- The STT/OFA combo box will be added by #229
- Form validation will be completed by #230
- Editing a user profile will be completed by #277

**Comment by lauraGgit** [comment]
per discussion in dev pairing we'll be sure to add an integration test that includes authentication and submission in cypress.

**Comment by RafterGit** [comment]
> per discussion in dev pairing we'll be sure to add an integration test that includes authentication and submission in cypress.

This will also need to include OTP support for pa11y as mentioned in  the [SPRINT4 PR Review](https://github.com/HHS/TANF-app/pull/58#pullrequestreview-497754278).

**Comment by shubhi-raft** [comment]
Per discussions in Teams, noting here @hilvitzs 
- Update 'We need to collect some information before an OFA Admin can grant you access' to 'Please enter your information to request access from an OFA administrator'
- No update is needed for tribal organization. Lauren confirmed it is ok to say associate tribe in the combobox.

**Comment by lfrohlich** [comment]
This has been merged

**Comment by lfrohlich** [comment]
This has been merged and accepted

**Comment by lfrohlich** [comment]
This has been merged and accepted
