### ISSUE TITLE
[Research Recruitment] 3.0 Pilot Expansion

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2313]
**Description:**

Delivers raft-side work to recruit additional users for the 3.0 release TDP expansion (targeted for February). This ticket should be brought into a sprint shortly after the 3.0 Hopes & Fears session (targeted for early/mid January). 

**AC:**

- [x] Grantees added to shortlist have been contacted.
- [x] Tracker is updated to reflect/track communications

**Tasks:**

- [x] Update shortlist based on 3.0 Hopes & Fears session
- [x] Coordinate with regional staff to contact new grantees
- [x] Determine path forward for Info Session / Office Hours leading into expansion (Good UX sync topic)
- [x] Book info session / office hours if needed
- [x] Update tracker with key POCs and user scenarios

**Supporting Documentation:**

- [Hopes & Fears board](https://app.mural.co/t/raft2792/m/raft2792/1670821228474/fbc87608838f9ef938bbf44d019d7226aa452d03?sender=mreiter1745) 🔒

**Comment by lilybl1** [comment]
Moving to QASP Review. Posted links for tracking in UX MM channel.

**Comment by lfrohlich** [comment]
This was completed. Thanks for all of your work @lilybl1 @reitermb
