### ISSUE TITLE
[Research Planning] 3.0 Pilot Expansion

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2314]
**Description:**

Delivers research planning & Hopes & Fears session to support release 3.0 (Featuring Submission History & Section 1 Parsing) 

**AC:**
- [ ] A research plan has been created which includes:
    - [ ] Research goals, relevant research questions.
    - [ ] Recruitment criteria & target participants.
    - [ ] Recruitment/participation email templates.
    - [ ] Timeline (for recruitment and for research sessions).
    - [ ] Testable Designs/Content (if applicable).
    - [ ] Ethics, privacy concerns 

**Tasks:**
- [x] Prepare for hopes & fears session (including preliminary grantee shortlist)
- [x] Facilitate hopes & fears session (Targeting week of Jan 9) 
- [x] Update tracker w/ finalized shortlist
- [x] Write any additional UX tickets needed to support 3.0 expansion

**Supporting Documentation:**
- [Hopes & Fears 3.0](https://app.mural.co/t/raft2792/m/raft2792/1670821228474/fbc87608838f9ef938bbf44d019d7226aa452d03?sender=mreiter1745) 🔒
