### ISSUE TITLE
SPIKE: Evaluate parser validation methods

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2335]
**Description:**
This is a precursor to #1354 due to some unpleasant side-effect found during its beginning stages. We want to evaluate a few different methods for validating the content and semantics of incoming raw data before being saved to the model/database. As a team, we decided to evaluate several methods including:

1. Django Built-in Model Validators 
2. Custom/Library Content validation (I chose cerberus but there are others such as Pydantic, JSON_schema, Marshmellow, etc.) -- @andrew-jameson 
3. Functional approach -- @n0remac 
4. Class `__init__` or post-init methods

**Acceptance Criteria:** 
- [x] We have a clear outcome and path forward
- [x] A written recommendation on singular solution for #1354
- [ ] Bonus goal: lessons learned
- [ ] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
- [x] Write proof-of-concept for two related fields for each of the methods listed in the description.
- [x] Evaluate computing efficiency, controlability, maintainability and testability of each method
- [x] Discuss pro/con lists of each method

**Notes:**

- Changes to the search_indexes/models.py will result in new migration files. This introduces some brittleness within the backend ops vs just making this an abstract/custom code solution.

**Supporting Documentation:**
- [6 approaches](https://towardsdatascience.com/6-approaches-to-validate-class-attributes-in-python-b51cffb8c4ea)
- [Django docs on validation](https://docs.djangoproject.com/en/3.2/ref/models/instances/#validating-objects)
- [Django modelform reference](https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/#interaction-with-model-validation)
- [django `is_valid()` doc](https://docs.djangoproject.com/en/3.2/ref/forms/api/#django.forms.Form.is_valid)

**Open Questions:**

**Comment by andrew-jameson** [comment]
Discussed with team Friday 1/20. Solution will be to create per-error functions as described in our provided [documentation](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_warning_edits_section_1.pdf) from OFA. These validation functions will be appended as a list to the rowSchema object under `search_indexes/parsers/scehma_defs/tanf.py`. The functions themselves will be imported from another file as per @n0remac's PR #2355
