### ISSUE TITLE
[DevOps] Deploy `develop` to a cloudgov environment after PR merge

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2337]
**Description:**
After PRs merge we should
* build and deploy the application/services to a development environment (bonus points for storing the build artifacts for later deployment to production)
* run end-to-end tests against the deployed application

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] `develop` deploys to [a cloudgov environment] when PRs merge
- [x] cypress tests run against [the cloudgov environment] once a deployment completes
    - [x] run tests after deployment to any environment? dev, staging, qasp, etc (not prod)
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Modify the Circle CI config to deploy the `develop` branch to [a development environment in cloudgov] after PRs merge
- [x] Add a step post-deployment to run the cypress e2e tests against [the environment]. 
   - This requires overriding some environment variables in the `cypress run` command, as well as adding a `CYPRESS_TOKEN` environment variable to the Circle CI config and CloudGov app variables.
   - example ci job: https://github.com/raft-tech/TANF-app/blob/be8197a46585ae006bd2e79a655326b302933157/.circleci/build-and-test/jobs.yml#L44-L65
   - example of overriding env vars in `cypress run`: https://github.com/raft-tech/TANF-app/blob/be8197a46585ae006bd2e79a655326b302933157/tdrs-frontend/package.json#L41
   - [update with link to example config once cypress PR merges]
- [x] Update devops/application documentation to reflect the change in process
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
