### ISSUE TITLE
As Lauren, I want to see GH issues for creating artifacts for upcoming OCIO deadlines

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#234]
This is a card to remind @lfrohlich to create some issues for staff we need to create for OCIO/CFT/PIR/ABCDEFG etc. 

- [x] Physical data model #253 As a compliance person, I want to see a Physical Data Model/database erd
- [x] System Design Document #254 As a compliance person, I want to see documentation of the system design
- [x] Logical data model #211 As a product team, we need to understand how users navigate TDP flow -- added a comment about using this for the logical data model
- [x] Test Plan report
- [x] Section 508 Accessibility Template (PAT) #303 As a compliance person, I need to know the accessibility plan (Section 508 PAT)
- [x] Update SSP #304 As a compliance person, I need to see a system security plan (SSP)

**Comment by lfrohlich** [comment]
Created the label _compliance_
OCIO artifacts are represented: 

- #253 As a compliance person, I want to see a Physical Data Model/database erd
- #254 As a compliance person, I want to see documentation of the system design
- #211 As a product team, we need to understand how users navigate TDP flow -- added a comment about using this for the logical data model
- Test Plan report
- Section 508 Accessibility Template (PAT)
- Update SSP

**Comment by shubhi-raft** [comment]
This is done.
