### ISSUE TITLE
[Research Synthesis] 3.0 Errors Research | February Pilot Expansion

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2344]
**Description:**

Synthesizes January Errors research (in preparation for 3.0 release. Also includes error findings drafted as part of  #2208 

**AC:**

- [x] A hack.md with the drafted synthesis has been reviewed.
- [x] PR has been opened containing the final draft of the synthesis.

**Tasks:**

- [x] --Aggregate notes from research sessions--
- [x] Delete video recording(s) once notes are compiled
- [x] October 2022 research session learnings [link](https://hackmd.io/Lo7C0JcERiS4B_jh3iLUXg?both)
- [x] January 2023 research session learnings [link](https://hackmd.io/WxtMOPCUQiO-JHjahVMPDQ)
- [x] February Pilot Expansion [link](https://hackmd.io/YGdkeM4_SBSrS2Ljm7b0qA?view)
- [x] Merge with draft synthesis from #2208

Notes from 3/7 UX Sync for consideration in this ticket: 
#2344 can be prioritized this month (extends previous draft PR with additional findings to  recap  errors research conducted in January & Django admin experience improvement opportunities 

Alex/Thomas to provide high level summary of the parsing header issues that were noted in the Notebook to include as part of the v3.0 update  

**Supporting Documentation:**

- [Hack.md](https://hackmd.io/@mreiter/BJO5b3rVi)

**Comment by reitermb** [comment]
cc @stevenino

**Comment by lilybl1** [comment]
@lfrohlich @ADPennington This is ready for your review as it has gone through internal Raft Review. The links are listed in the description. Thanks!

**Comment by lfrohlich** [comment]
Discussed adding key takeaways to the top. I'll wait to review until updated. Thanks!

**Comment by lilybl1** [comment]
@lfrohlich When you get a moment, take a look at the February synthesis for the key takeaways. Let me know how this works.

**Comment by lfrohlich** [comment]
@lilybl1 Thanks! I added some comments. I also made some minor in-line edits.

**Comment by lilybl1** [comment]
@lfrohlich Updated. Thanks!

**Comment by lfrohlich** [comment]
@lilybl1 looks good to me, thanks!

**Comment by lilybl1** [comment]
@reitermb Create the PR for review.
