### ISSUE TITLE
As tech lead, I want to load test our application

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2346]
**Description:**
Currently, the production backend runs in 2GB. There is some uncertainty that this might be insufficient for 100+ concurrent users submitting large files. 

**Acceptance Criteria:** 

- [ ] Evaluate third-party toolset(s) with proof of concept implementations
- [ ] Report Card for future evaluation
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Stress test front/backend applications under concurrent user requests
- [ ] Test should ideally simulate a file upload resulting in parsing
- [ ] Testing toolset should remotely target deployed Staging environment 
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] Evaluate future tasking and create follow-on tickets if needed

**Notes:**
- Do *NOT* use Parasoft
- Definitions for different loads:
- ![image](https://github.com/user-attachments/assets/916fb76e-558c-4a96-b06a-32fcdd7fda3a)

Future tasking:
- [ ] List of recommended "virtual hardware" specifications if limits are hit/exposed
- [ ] #3319
- [ ] Stress test PG/ES for expected maximum load
- [ ] Stress test ancillary services for maximum load (such as ClamAV, S3, etc.)

**Supporting Documentation:**

- [File size ranges](https://github.com/raft-tech/TANF-app/blob/develop/docs/Background/Current-TDRS.md#data-transmission)
- [Django Optimization](https://docs.djangoproject.com/en/4.1/topics/performance/)
- [Celery Optimization](https://docs.celeryq.dev/en/stable/userguide/optimizing.html)
- [Random stackoverflow metrics](https://stackoverflow.com/questions/28205282/typical-memory-usage-for-django-applications)
- [k6 testing tool](https://k6.io/) recommended by @jtimpe 
- [k6 cloud free tier](https://grafana.com/pricing/)
- [SF for tools](https://stackoverflow.com/questions/46893226/performance-load-and-stress-testing-in-django)
- [12 tool recommendations](https://www.techrepublic.com/article/load-testing-tools/)

**Open Questions:**

**Comment by lhuxraft** [comment]
Needs further refinement, should be split among multiple tickets

**Comment by lhuxraft** [comment]
To discuss in backlog refinement 12/3: change priority? Pair with celery tickets

**Comment by lhuxraft** [comment]
12/16: First test written, working on cleaning up tech memo

**Comment by lhuxraft** [comment]
12/18: Receiving feedback on tests, working on infra visibility tasks. Making a README instead of tech memo
