### ISSUE TITLE
As a user, I want to know I am logging into a demo site

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#235]
**Description:**
Following feedback from the 9/1 demo to add a demo banner to the home page to notify a user that the site is a test app. 

**AC:** 
- [ ] [TDP frontend](http://tdp-frontend.app.cloud.gov/ ) banner is a 'demo' banner (similar to 'Expected' resource screenshot below)

**Tasks:**
- [x] If login.gov sandbox banner is to be used, ask 18F for demo banner component.
- [x] Update expected functionality screenshot with what the final demo banner will look like. 
- [x] Replace current banner on the [TDP front end](http://tdp-frontend.app.cloud.gov/) with 'expected' functionality banner 

**Note**
- No other content update except for the updating banner will be made. 

Questions:
- Confirm whether demo banner displayed in login.gov sandbox suffices to meet this user story. If not, discuss alternatives. 
   - Yes, it does.

Resources:

Current:
![Screen Shot 2020-09-03 at 11 44 39 AM](https://user-images.githubusercontent.com/22622384/92137204-e2af1580-edda-11ea-96e3-8f991fe4faea.png)

Expected (to be confirmed):
![Screen Shot 2020-09-03 at 11 34 25 AM](https://user-images.githubusercontent.com/22622384/92137022-b7c4c180-edda-11ea-92a0-f0e7d8a5c9da.png)

**Comment by shubhi-raft** [comment]
this can be moved back into the pipeline.

**Comment by shubhi-raft** [comment]
this was completed when trussworks was removed and login page was redone.

**Comment by lfrohlich** [comment]
This was done in Sprint 4
