### ISSUE TITLE
Increase memory limit for deployed instances and celery workers

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2350]
**Description:**

Following #2268, one reason users get error while uploading files (this happens for files > 300KB) is memory limit set on celery workers per child defined in ``` celery -A tdpservice.settings worker -c 1 --max-memory-per-child 5000 & ```.   The setting causes task to terminate when memory usage is higher than the limit (here 5MB) and consequently the child worker being replaced by another one. This means the upload task will be terminated and messages already consumed will be lost.

According to celery documentation, there are approaches to reduce the chance of such failures by adjusting the number of messages to be consumed before one task is complete, controlling how much memory is available to each child and setting when a task is deemed as complete. Despite all the above settings, upload worker still needs more memory, so all the above mentioned settings only ensures the worker is not immaturely terminated.

**Acceptance Criteria:** 

- [x] Uploaded files are scanned by clamav and only files returned as safe are uploaded to SFTP
- [x] Files are uploaded successfully to SFTP
- [x] Upload tasks are acknowledged only after completion meaning if the worker is restarted, the task will be retried
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Increase cloud.gov instance memory (currently set to 512MB). Suggested value is 2G.
- [x] Increase per child max-memory
- [x] following settings in [here](https://docs.celeryq.dev/en/stable/userguide/optimizing.html#reserve-one-task-at-a-time) to set worker only upload one file per worker
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Docs and Links**
- [Setting worker maxmemory](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-worker_max_memory_per_child)
- [Celery optimization](https://docs.celeryq.dev/en/stable/userguide/optimizing.html)
- [Deployment instance config manifest](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/manifest.yml)
- [Example files](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Jq8SRo&cid=83ce52a9%2D83f5%2D49dd%2Dac12%2Df2f7dac19ed0&RootFolder=%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FLegacy%20System%2FDummy%20data&FolderCTID=0x01200039BDB10EB450C04FB647A089E033E116)

**Comment by stevenino** [comment]
Refer to #2353

**Comment by raftmsohani** [comment]
The following log shows successful file upload:

![Screen Shot 2023-01-20 at 2.54.15 PM.png](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/6435387e-963f-44e7-bdc4-086427557e79)
