### ISSUE TITLE
As a user I want to be notified when the files are being scanned or uploaded when I push upload button

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2351]
**Description:**
Following #2268, when user submits files by pushing upload button, there is no notification to the user whether the files are submitted to the backend server and that there is a process in the background to scan the files for virus, etc. One rule of thumb is to send any request taking more than 500ms to background process and notify the user (see Heroku)[https://devcenter.heroku.com/articles/node-redis-workers]. Since for larger files these scans are taking more time, user might assume that the process is frozen or has not been successful and as such tries to push the button again which will increase the load on backend server.

**Acceptance Criteria:** 

- [ ] User clearly knows about background process happening after file(s) successful submittal
- [ ] User won't be able to push the submit button until there is response from backend for either successful submission or an error
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Add user notification either by adding a text or a loading icon after user pushes upload button
- [ ] Avoid allowing user to submit same files while the files are being processed in the background (either being scanned by clamav or being uploaded to SFTP, etc).
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by stevenino** [comment]
#2306

**Comment by robgendron** [comment]
Deemed no longer needed, #2306 covers this.
