### ISSUE TITLE
[WIP] test staging and production deployment before v3.0 release 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2360]
**Description:**
After rotating secret keys as part of #2336, i added the new keys to circleci and re-ran the deployment workflow to test that the deployment runs from ci without problems. It failed at the deploy backend step. It appears to be related to the buildpack (see below)

This needs to be investigated prior to the next release. For now, in order to get prod back to a functional state, i re-mapped the prod routes and restaged from cloud.gov. confirmed that all new keys currently working in prod. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] production-deployment workflow runs successfully upon next merge to master branch. 
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] alex to investigate via fork to staging branch. 
- [x] alex to re-run prod deploy workflow after business hours
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

![deployprod](https://user-images.githubusercontent.com/63075587/212994101-f3273186-8d71-493a-8bdb-a9e85ccf8028.PNG)

**Comment by ADPennington** [comment]
### update on testing staging deployment workflow

tested on ADPennington/TANF-app/staging-v223 and it was successful 

![depstaging](https://user-images.githubusercontent.com/63075587/213028306-567850f4-4582-4292-9142-f2c46ca8ae33.PNG)

**Comment by ADPennington** [comment]
### update on testing prod deployment workflow 

re-ran from hhs circleci and it was successful.  confirmed all new keys work. 
![deployprod2](https://user-images.githubusercontent.com/63075587/213030662-3cdb60a1-9db9-41d9-81f3-eb80b1e72a5c.PNG)

closing as completed.
