### ISSUE TITLE
[Research Facilitation] Transmission report error prototypes planning and research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2368]
**Description:**
Planning out the research to better understand how grantees (State and Tribal) programs will be able to use the .csv report in correcting their errors to resubmit data files. 

These will be tested with users over the course of May 2023 to ensure that the new format will work for grantees. Additionally UX plans to continue ideation on the error reports to set up research around how we might smoothly link data analysts from an error to the coding instructions, or potentially include coding instructions within the content of the error report itself. 

This ticket delivers prototype templates that we'll use to enable all error research in/from April. 

**AC:**
- [x] Plan and review the goals for the research
- [x] Research sessions conducted with 3-5 (States and Tribes) 
    - [x] Session 1 (Tribe)
    - [x] Session 2 (State)
    - [x] Session 3 (Tribe)
    - [x] Session 4 (Tribe) - 5/2
    - [x] Session 5 (State) - 5/2
    - [x] Session 6 (State) - 5/4
    - [x] Session 7 (State) - 5/8
    - [x] Session 8 (State) - 5/15
    - [x] Session 9 (Tribe) - 5/23
- [x] Affinity Map findings (high level only) 

**Tasks:**
- [x] Identify and reach out to shortlist based on errors generated in last quarter submissions
- [x] Create and generate a testable .csv format error report template

**Supporting Documentation:**
[Ideation/Planning Mural](https://app.mural.co/t/raft2792/m/raft2792/1670442812740/df177d3bb67bd1a9921614d0261a1abb15214bc5?sender=mreiter1745) 🔒 
[April Planning & Affinity Mapping Board](https://app.mural.co/t/raft2792/m/raft2792/1680720936421/9c61886d42c83c485942b3ab245d37921519f0ae?sender=u3ca60168b5ac4eb17bf92804) 🔒

**Comment by lilybl1** [comment]
Per discussion with Andrew, changing format from .csv to .xlsx as that is how the files will be saved and generated. We will change the format type in our next usability session.

**Comment by reitermb** [comment]
With the final session today and with that this should be good to close. Reviewable content to follow in #2516

**Comment by reitermb** [comment]
> With the final session today and with that this should be good to close. Reviewable content to follow in #2516

cc @ADPennington @lfrohlich @Smithh-Co

**Comment by lfrohlich** [comment]
@reitermb does that mean this ticket shouldn't include affinity mapping?

**Comment by reitermb** [comment]
> @reitermb does that mean this ticket shouldn't include affinity mapping?

The affinity mapping is linked in the second supporting documentation link if you'd like to take an early look! We're treating is as more of an internal task to consolidate our notes and set up synthesis work than a reviewable deliverable though.

**Comment by lilybl1** [comment]
This ticket is ready to be closed.
