### ISSUE TITLE
As tech lead, we need the parsing engine to run quality checks across TANF section 1

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2369]
**Description:**
We discovered the scope of this engine in #132 and created spike #2335 to decide on a path forward as the validator abstraction proved a large task than initially expected. This ticket is intended to capture this next phase of parsing.

**Acceptance Criteria:** 

- [ ] Parsing completes regardless of data quality
- [ ] Parsing errors whether fatal or warning generate a ParserError obj
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Implement cat2/3 validator functions for tanf section 1 including relevant unit tests.
- [x] #2536
- [x] Configure schema_defs to co-locate a list of validator functions
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
![image](https://user-images.githubusercontent.com/28515874/215615601-8cd6473e-b4ac-4e1f-a0a7-352464eb838e.png)
https://app.mural.co/t/raft2792/m/raft2792/1675119530632/15dc23ac92cc546ac1212455f4bea1bd6cb368dd?sender=mreiter1745 - Mural Version

**Supporting Documentation:**
- [Spike closing comment](https://github.com/raft-tech/TANF-app/issues/2335#issuecomment-1400460486)
- [97 page doc](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_reports_tan_ssp_instructions_definitions.pdf)
- [T1 excel workbooks - source of truth](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BF99CEA75-18CC-4494-9302-677CC92E3EF4%7D&file=TDP_Validation.xlsx&action=default&mobileredirect=true&cid=7776f046-c9be-4720-9367-46d58b9ac731)
- [T1 Fatal edits](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_fatal_edits_sections_1_and_4.pdf)
- [T1 Warning edits](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_warning_edits_section_1.pdf)
- [Parent OFA page](https://www.acf.hhs.gov/ofa/policy-guidance/final-tanf-ssp-moe-data-reporting-system-transmission-files-layouts-and-edits)
- [Parsing Folder OneNote](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Dev%20Notes.one%7C3dbb7d3a-694d-4f1c-a656-f907991c1f7d%2FParsing%7C0421d80f-82aa-4d35-91f7-682cf344bee4%2F%29&wdorigin=NavigationUrl) 🔒 

**Open Questions:**

**Comment by Smithh-Co** [comment]
@n0remac @andrew-jameson Hey guys, dropping a line post our 2.1 dev sync: Prioritize Cat 2, line items and unit testing logs; minimal refactoring for now but discussed adjusting state FIPS code and header.

**Comment by raftmsohani** [comment]
The section 1 items are explained here in more detail: https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_report_section1_10_2008.pdf

**Comment by raftmsohani** [comment]
Tabletop video: https://gorafttech-my.sharepoint.com/:v:/g/personal/msohani_teamraft_com/EXkRMeK3irpAmtbSvU4p1-4BsgIiRdsZBlFbFGMOmIMAVg?e=pRELtZ
