### ISSUE TITLE
As tech lead, I need STT metadata updated for NC who is transitioning from sample to universe data reporting

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2373]
**Description:**
NC recently informed that they are in the process of transitioning from submitting sample data to universal data on the ACF-199 (TANF Data Report). This state is expected to start universal reporting in Spring 2023 (for FY23+). 

Currently, our system identifies this state as a sample state who submits all 4 sections of TANF data. We need to update the metadata to account for this change. 
![NC_transition](https://user-images.githubusercontent.com/63075587/214645554-5d21f92a-54b6-4ae2-a2a8-af4e8962ab9f.PNG)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] NC's metadata in STT model is correct
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] update [states.csv](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/states.csv)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- The state shouldnt be recruited for TDP use until this change is implemented.
