### ISSUE TITLE
[DRAFT] Normalize tanf-dev services and deployments

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2393]
**Description:**
Per investigation from [here](https://github.com/raft-tech/TANF-app/pull/2392), we have a new ceiling on our cloud.gov services. We can make `tanf-dev` normal and reduce some quirkiness related to environments we introduced to work around the previous ceiling. Please see supporting documentation for links to previous tickets.

To accomplish this, we will use Terraform and CI/CD to auto deploy a unique environment to tanf-dev for each feature or other branch. Terraform will also tear down these environments upon a successful PR to develop, deletion of the branch, or when prompted by a user. This will remove the need for persistent environments in tanf-dev.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] TBD -- spike?
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by robgendron** [comment]
Still being used.
