### ISSUE TITLE
Users can easily upload data 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#24]
Description:
(please define the reason as to why this issue is being created )

AC: 

- [ ] Sample acceptance criteria

Tasks: 

- [ ] Sample tasks

DoD: 
 - [ ] minimum 90% code coverage test
 - [ ] 0 linting errors and warnings
 - [ ] 0 accessibility errors
 - [ ] deployed to a dev environment
 - [ ] all significant changes have been documented
 - [ ] free of high and medium security vulnerabilities
 
 

Supporting Documentation:

(please include any relevant log snippets/ files/ screen shots here.)

Open Questions:

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
duplicate.
