### ISSUE TITLE
[Design Deliverable] Explainer content/tool to help grantees navigate Δ:Fiscal period/Calendar period

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2406]
**Description:**
Context: 
- We know at least two grantees have made submissions for the wrong Fiscal Period so far (for February 2023 deadline)

Assumptions: 
- Calendar/Fiscal quarter mapping can be confusing and difficult (for us and for grantees) 
- We can help address this via knowledge center explainer content 
- We can help address this via in-app help-content that could adjoin the Data Files page

This delivers knowledge-center-content and/or in-app-help-content aimed at mitigating/avoiding the above

**Related User Stories:**

- As a user I want to submit data to the correct fiscal period
- As a user I want hep understanding which fiscal period maps to which calendar period

**AC:**

- [x] Documentation work for the following has occurred:
   - [x] Relevant User stories.
- [ ] Dev/Design sync has occurred (if this ticket generates in-app designs); resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>
- [ ] Work has been reviewed in internal raft-review design tabletop

**Tasks:**

- [ ] Ideation
- [ ] Draft hack.md
- [ ] Draft Figma (if pursuing in-app solution)
- [ ] Schedule design tabletop (for raft review)

**Supporting Documentation:**

—Link to Figma and Dev-Ready Design folder PDF—

**Notes:**
- A pre-parsing check may ultimately solve for this as well. Implementation of this could depend on parser release timing 
- Is there something we could do along the lines of a "You are here" — "data due for [x deadline] is y"
