### ISSUE TITLE
Preparser Refactor

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2408]
**Description:**
As discussed during Friday 2/10 with the dev team, this ticket is scoped for refactoring and abstracting the head of parsing.

**Acceptance Criteria:** 
- [ ] Parsing is a standalone django app
- [ ] Preparsing and overall parsing management are abstracted from each other
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Move parsing to its own app and reorganize folder structure (`tdpservice/search_indexes/parsers` --> `tdpservice/parsers`)
- [x] Move preparsing error checks (cat1) into a separate file/set of functions
- [x] Refactor existing `preparse()` to be an overall parsing manager/main function and subordinate `preparse` function
- [ ] STRETCH: Preparsing record types header/trailer are created as models akin to T1 documents
- [ ] STRETCH: All category 1 errors utilize data struct/model from #1121 
- [x] STRETCH: Adjust parsing unit tests for restructuring in this ticket
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
These notes are meant to be a guideline and to flesh out the ideas above but are not definitive or immovable.
* Create new file `parsers/parser_manager.py` to be invoked by `scheduling.parser_task.py`.
* This new manager will call parsing functions in order based on DataFile object (`data_type`, `section`, etc.)
```python
# tdpservice/parsers/manager.py
def main(datafile, data_type, section):
  # datafile handling
  returns = preparse(kwargs)
  # error-handling of preparsing
  
    if data_type == 'TANF':
        if section == "Active Case Data":
           tanf_parser.active_parse(datafile)
       elif section == "Closed Case Data":
          tanf_parser.closed_parse(datafile)
    #   we don't currently have different sections but we'll stub those out here
    
    # elif data_type == 'SSP':
    #    ssp_parser.parse(datafile)
    # elif data_type == 'Tribal TANF':
    #    tribal_tanf_parser.parse(datafile)
    else:
        raise ValueError('Preparser given invalid data_type parameter.')
```
* Any sort of structure errors or cat-1 validation should be left in `preparser.py`.
* Per supporting documentation, we will treat preparsing like a "section 0" to be done before section 1. This includes refactoring header/trailer validation to match structure of #1121
* Any category 1 checks on data rows (e.g., length checks, bad record type) should be included as part of preparsing.
* Header content must be saved in a new model so it can be referenced in later validation checks.
* This will require significant reworking of unit tests
* Another note, per repeated commentary from @ADPennington, we should treat any trailer mistakes as warnings and just proceed with all relevant parsing.

**Supporting Documentation:**
- [Flow Diagram](https://app.mural.co/t/raft2792/m/raft2792/1675268418098/d56ec0d5415d8cda9c6ae9cae61154bcc4e74bba?sender=ce75cff7-c7f8-41b1-8947-5b7df76ae538)
- [Detailed Architecture Description](https://lucid.app/lucidchart/a86a36e7-dd40-4d10-bff9-d5523212f322/edit?invitationId=inv_d6e2304a-12f8-49fb-adc8-20e2d640adc8&page=0_0#)

**Open Questions:**
