### ISSUE TITLE
As system admin, I want to view metadata on parsed datafiles

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2411]
**Description:**
Per Backlog Refinment 2/14, we want an intuitive sysadmin experience for filtering on submitted datafiles. #1613 is already covering some of this scope but we need to cater the admin panel display to include these data about subsmissions: file status (accepted, rejected), case totals, err report link, header enc flag, year/qtr, progtype 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Parsed datafiles are filterable on: STT, Year, Quarter, Program Type
- [ ] Admin view of parsed datafiles contain: file status, case totals, err report link, header enc flag, link to STT object, link to originating DataFile
- [ ] Clickable obj link is not an incrementing integer
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Enhance model from #1613 to support ACs
- [ ] Add filters for admin view of object
- [ ] Create short human-friendly obj-name
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- @ADPennington write-up [here](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Admin%20Notes.one%7C8e533710-461e-4b99-a33c-94e9b67b197e%2FSystem%20admin%20sync%20log%7C47928620-33e4-4cd0-8a3c-0542b83ef9b0%2F%29&wdorigin=NavigationUrl)

**Open Questions:**
