### ISSUE TITLE
CICD: refactor current pipelines

### ISSUE THREAD

**Issue by George-Hudson** [raft-tech/TANF-app#2419]
Currently our pipelines are working, but could use some quality of life updates for developer readability and workflow triggering logic. There have been times when workflows are being triggered when unnecessary and not desired. Such as with this bug: https://github.com/raft-tech/tanf-app/issues/2403

We need to set up workflows where all the logic  for what is getting run is visible at the start of the workflow, not nested further down in the jobs, etc. 

Workflow logic should happen on a limited when condition as much as possible, and not a growing list of unless logic. 

Currently we are using CI/CD pipelines from GitHub Actions to trigger CircleCI pipelines, which, even though is the accepted flow from CircleCI documentation, is perhaps indication to lift the pipeline fully to another platform (Jenkins, GitLab etc)
Map out the current and proposed workflow maps on our [whiteboard](https://app.mural.co/t/raft2792/m/raft2792/1675268418098/d56ec0d5415d8cda9c6ae9cae61154bcc4e74bba?fromVisitorModal=true&sender=42d6e1c4-9469-4fe1-a23a-87be81fa3dc9) and [steps details](https://docs.google.com/document/d/11lRy78ML0Dwxph9DTCaKSbKswTEPoNDHk0Zwmc3iO6I/edit)

Push pipeline logic down to bash/python scripts. Make it easy to perform pipeline steps manually, if necessary.
Make it easy to port to different pipeline tools.

## 1. Reduce workflows for deploy pipeline
+ [x] #2722
+ [ ] Update deploy-(front/back)end.sh scripts to be called more intuitively from the pipeline
+ [ ] Make the pipeline Deploy Workflows DRY by passing only the needed information to the shell scripts
+ [ ] Create one RDS service per env
+ [ ] put terraform deploy and S3 versioning together
+ [ ] Put code for updates-site and make-erd into deploy script
+ [ ] Push step/workflow logic into deploy shell scripts where appropriate
+ [ ] Add commands that are written into the pipeline yml into the deploy script instead
+ [ ] ensure logic for script works for all permutations of deploy 

## 2. Refine build and test workflows
+ [ ] Put Secrets check into test script
+ [ ] Call on one script, with parameters for testing vs deploy (frontend, backend, e2e)
+ [ ] Push logic to script
+ [ ] Update pipeline yml for one workflow

## 3. Refactor OWASP scans
+ [ ] Make DRY, only need one workflow for this
+ [ ] create script that works for frontend/backend and develop/staging/production/circleci envs

## 4. Reduce multi-folder, multi-file pipeline to one file
+ [ ] reduce remaining repetition of different named steps/commands that do same basic function
+ [ ] make underlying shell scripts adaptable to whatever pipeline parameters are given
+ [ ] push remaining logic from pipeline in to scripts as much as possible while maintaining ability to run workflows in parallel

**Comment by robgendron** [comment]
Work associated with this epic was completed.
