### ISSUE TITLE
Validation Halting Mechanism

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2423]
**Description:**
This could be as simple as some if statements but if it requires a more complicated approach, this ticket is to handle that scope-creep.

**Acceptance Criteria:** 

- [ ] If parsing category N has any validation errors, category N+1 validators are not run
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Implement logic or mechanism to prevent errant N+1 validation
- [ ] Write novel unit tests to assert functionality
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by robgendron** [comment]
Backlog Refinement, team deemed complete.
