### ISSUE TITLE
Singular ClamAV Scanner

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2429]
**Description:**
To reduce consumed RAM, we want to collapse the 3 clamav instances into one. For ATO reasons, the prod backend must use an instance in the prod space. 

**Acceptance Criteria:** 
- [ ] Point all our backend apps instance to a tanf-prod clamav scanner
- [ ] Ensure all pipeline/deployment automation reinforces this new structure
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Update backend code specific to clamav location
- [ ] Update deployment scripts which link/unlink (both deploy-backend and circleci)
- [ ] Ensure space-level networking is opened such that all staging/dev apps can speak with prod scanner
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- This should free up approximately 4GB of RAM usage across the org and might prevent future deployment failures due to memory quota ceiling.

**Supporting Documentation:**

**Open Questions:**

**Comment by George-Hudson** [comment]
EOD: Jul 19th: pulled into current work. Discussed need for reducing space mem usage. Created branch and started looking through code.

**Comment by George-Hudson** [comment]
@raftmsohani has created a new NGINX server in order to handle requests coming from other spaces instead of granting spaces internal access using network-protocols.

I believe this work is ready for review and usage, once @andrew-jameson is back. 

Once that change is merged and the manual steps completed, we can shut down the ClamAV servers in each of the other spaces and free up resources.
