### ISSUE TITLE
[Design Deliverable] Knowledge Center FAQ Additions

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2431]
**Description:**

Delivers enhancements / additions to the FAQ page of the knowledge center. We expect this ticket to receive additional refinement en route to the next major TDP release as we identify additional content to add. 

**AC:**

- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft content in hack.md
   - [x] Add clarification to FAQ about how much data can be submitted at once — "Each data file can only contain one quarter"
   - [x] Add FAQ item regarding how many users can request access to TDP from one STT — include our recommendation of 2-3 and contextualize with our example of two users being useful for sick leave/vacation situations where alternate team members will need to submit data to meet deadlines.
   - [x] Add FAQ item re: multiple vectors of login.gov usefulness (e.g. Those who use login.gov for access to GrantSolutions can use the same account for TDP)
   - [x] Include a link to the dear colleague letter as part of the homepage intro copy 
- [x] Review content 
- [x] Stage changes in Test environment
- [x] Open a PR to raft-tech

**Supporting Documentation:**

- [Hack.md Draft](https://hackmd.io/@mreiter/rJDZW5pJh/edit)

**Comment by lfrohlich** [comment]
I added some comments to the FAQ hack.md. Tagging @ADPennington in case she wants to review

**Comment by reitermb** [comment]
[Test Environment Link
](https://reitermb.github.io/Test/knowledge-center/index.html)
**Changes:** 
- All feedback in hack.md is addressed
- FAQ additions have been added to Test environment
- Reorganized FAQ page around emerging categories of question to make it easier to parse
- Added mention/link to Dear Colleague letter on the homepage (also live in Test environment

cc: @lfrohlich @ADPennington

**Comment by ADPennington** [comment]
@reitermb this looks really good. Lite suggestions below:

- over time as the FAQs get longer, we should include section tags at the top of the page
- for the 2nd question under submitting data, consider adding a link to the submitting data page for visuals on the process.
