### ISSUE TITLE
[Design Deliverable] Pre-Production — Knowledge center videos

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2432]
**Description:**

This ticket delivers pre-production for video content additions to the knowledge center. UX expects the initial scope for this to look something like two to three videos (each ≤ 3 minutes) and likely concerning core functions like the new user request access flow or the data submission flow—potentially with one video dedicated to an overview of TDP as a whole / as a sort of video counterpart to the dear colleague letter. 

**AC:**

- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Notes:**

These videos are opportunities to speak to FAQ type material within the scope of their subject area (e.g. Tribes should select their Tribal Program Name, Nod to which data quarter maps to which fiscal)

**Tasks:**

- [x] Determine the subject of prioritized videos in UX/cross functional sync
   - [x] Requesting Access, Uploading Data — videos are greenlit as per discussion in UX sync
   - [x] Where will we host the videos? e.g. direct hosting vs embedded YouTube or Vimeo — shooting for ACF YouTube channel 
- [x] Write scripts for prioritized videos
   - [x] Include a "shot-list" within the script to describe the screen recordings / other visuals we'll see on-screen alongside any voiceover or on-screen-text

**Supporting Documentation:**
[ACF YouTube Guidance](https://www.acf.hhs.gov/digital-toolbox/multimedia/youtube-guidance)
[ACF YouTube Channel](https://www.youtube.com/@usgovACF/playlists)

- [Hack.md Script]()

**Comment by lfrohlich** [comment]
Added comments/edits to requesting access script and data submission script. Tagging @ADPennington for review. @ttran-hub you may want to look as well

**Comment by lfrohlich** [comment]
Scripts were finalized
