### ISSUE TITLE
As tech lead, I need HHS/TANF-app/CircleCI to supply environment variables for staging and prod environments

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2435]
**Description:**
Currently, every time we merge PRs to `HHS/TANF-app:main` (which triggers the `staging-deployment` workflow), during the `deploy backend application` step, the key-value pairs stored in CircleCI (for prod) are supplied to `tdp-backend-staging` app. We have to immediately and manually update at least some of the following pairs via cloudgov dashboard (with the appropriate key value pairs for staging) after the workflow is completed:

AMS_CLIENT_ID
AMS_CLIENT_SECRET
AMS_CONFIGURATION_ENDPOIN
~AV_SCAN_URL~
BASE_URL
~CLAMAV_NEEDED~
~CLIENT_ASSERTION_TYPE~
~DJANGO_CONFIGURATION~
~DJANGO_SECRET_KEY~
~DJANGO_SETTINGS_MODULE~
~DJANGO_SU_NAME~
~FRONTEND_BASE_URL~
JWT_CERT NEED
JWT_KEY NEED
~LOGGING_LEVEL~
~OIDC_OP_ISSUER~
~REDIS_URI~

SEND_GRID_KEY (MAYBE?)

Instead of this manual step, we need CircleCI to store key value pairs for both environments. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `tdp-backend-staging` app environment variables persist in cloudgov after staging-deployment workflow is complete
- [ ] `tdp-backend-prod` app environment variables persist in cloudgov after production-deployment workflow is complete
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] update code files that supply environment variables to HHS/TANF-app environments
- [ ] Run Testing Checklist and confirm all tests pass
