### ISSUE TITLE
[Chore] Update/restage buildpacks (2023-03-01)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2436]
**Description:**
Standard update on restaging calling out project-updates in particular. However, looks like we might want to update our other buildpack versions after testing that they're not broken.

**Acceptance Criteria:** 

- [ ] Update buildpack versions as possible with minimal/no other code changes
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update and restage  `project-updates`
- [ ] Investigate if newer `nginx` buildpack impacts frontend
- [ ] Investigate if newer `python` buildpack impacts backend
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- I think our backend is on python v.1.7.x, and 1.8.x is available.

**Supporting Documentation:**

> Hi cloud.gov user,
>
> cloud.gov frequently updates the programming language buildpacks available to
> our customers. Buildpack updates include programming language updates and 
> often include security fixes.
> 
> We recently updated the buildpack in use by your application. You should 
> restage or redeploy your application to take advantage of the update.
> 
> A rolling restage operation is the quickest way to upgrade without incurring
> downtime. You may still want to leverage your deployment infrastructure to
> perform the upgrade if you have compliance requirements for redeployment operations.
> 
> You can restage your application by opening the command line and entering 
> the following commands:
> 
>   cf target -o hhs-acf-ofa -s tanf-dev ; cf restage --strategy rolling tdp-project-updates
> 
> 
> For more information about the buildpack update(s), please see the following release notes:
> 
>   go_buildpack v1.10.4: https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.10.4
> 
>   staticfile_buildpack v1.5.38: https://github.com/cloudfoundry/staticfile-buildpack/releases/tag/v1.5.38
> 
>   nodejs_buildpack v1.8.5: https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.8.5
> 
>   python_buildpack v1.8.4: https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.8.4
> 
>   java_buildpack v4.54: https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.54
> 
>   ruby_buildpack v1.9.2: https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.9.2
> 
>   php_buildpack v4.5.2: https://github.com/cloudfoundry/php-buildpack/releases/tag/v4.5.2
> 
>   dotnet_core_buildpack v2.4.7: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/tag/v2.4.7
> 
>   nginx_buildpack v1.2.0: https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.0
> 
>   r_buildpack v1.2.0: https://github.com/cloudfoundry/r-buildpack/releases/tag/v1.2.0
> 
>   binary_buildpack v1.1.2: https://github.com/cloudfoundry/binary-buildpack/releases/tag/v1.1.2
> 
> 
> For more information on keeping your application updated and secure, see: 
> https://cloud.gov/docs/getting-started/app-maintenance/
> 
> If you have questions, you can email us at [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov).
> 
> Thank you,
> The cloud.gov team

**Open Questions:**

**Comment by robgendron** [comment]
@andrew-jameson is this good to be brought into the Improved Dev Tooling epic?
