### ISSUE TITLE
[Design Deliverable] Production & Post-Production — Knowledge Center videos

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2438]
**Description:**

Handles production and post-production processes for 3.1 (read: MVP) Knowledge Center video content. 

**AC:**

- [ ] Videos / metadata deliverables meet ACF YouTube content guidelines and have been submitted [here](https://bixal-servicedesk.atlassian.net/servicedesk/customer/portal/16/group/53/create/169)
   - [ ] Thumbnails
   - [ ] Titles/Descriptions
   - [ ] Tags
   - [ ] Transcript/Captions
   - [ ] Video files
   - [ ] Project scope as detailed [here](https://www.acf.hhs.gov/digital-toolbox/multimedia/youtube-guidance)
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Record content for video (pertinent video, screen recordings, and audio as needed for script) 
- [x] Edit content & render rough-cut versions for review
- [x] Make any revisions
- [x] Add closed captioning
- [x] Create thumbnails
- [x] Render final cut
- [x] Submit to ACF

**Comment by lilybl1** [comment]
Keeping open as we are waiting to hear back from ACF Youtube - should be this week.

**Comment by lfrohlich** [comment]
Complete
