### ISSUE TITLE
[Design Deliverable] Video Release — Embed videos in knowledge center

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2439]
**Description:**

Delivers final embeds of ACF hosted videos to pertinent Knowledge Center pages 

**AC:**

- [x] OFA/Raft a11y review tagup has occurred to evaluate video embeds
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Embed videos
- [x] Stage in test environment
- [x] ~~Open PR to raft-tech~~ This work to be included in the same PR as #2503
