### ISSUE TITLE
Leverage path filtering for CI builds

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2457]
**Description:**
To decouple frontend, backend CI builds, we can utilize path filtering to only build changed directories -- not building everything for a simple document change.

**Acceptance Criteria:** 
- [ ] Must work correct in HHS CircleCI
- [ ] Build trigger is service-specific (frontend, backend)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] For agnostic files (scripts/deploy.sh), ensure CI builds all
- [ ] Implement `path_ignore` for documentation updates
- [ ] Implement `path` filtering for decoupling builds on fronend vs backend
- [ ] Document new flows in README
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
 - We are trying to improve readability and dev experience in regards to these pipelines.

**Supporting Documentation:**

**Open Questions:**
