### ISSUE TITLE
Integrate Nexus into CircleCI

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2458]
**Description:**
As follow-on to #2116, first step into integrating nexus into the pipeline is building base images and uploading those to Nexus.

**Acceptance Criteria:**

- [ ] Nexus is accessible via a service account
- [ ] Nexus is automatically updated with newly built images
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Ensure service account is created and capable for nexus access
- [x] Implement Nexus CRUD workflow (and leverage it for Docker)
- [x] Attempt to utilize base `develop` image(s) for `build-and-test`
- [x] Store any db dump files from #2965 in Nexus, *not* Github repo
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

- [Backend Docker Hub](https://hub.docker.com/repository/docker/rafttech/tdp-backend/builds)
- [Frontend Docker Hub](https://hub.docker.com/repository/docker/rafttech/tdp-frontend/builds)

**Open Questions:**

**Comment by robgendron** [comment]
Prioritize in the near future.

**Comment by reitermb** [comment]
Blocked pending access to raft labs

**Comment by robgendron** [comment]
Still pending access - pushing up Raft-side as an issue.

**Comment by reitermb** [comment]
On deck for tabletop w/ Alex next week (M, W)
