### ISSUE TITLE
As a Sys Admin, I want to filter users with IPv6 based on their Geo locations 

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2461]
**Description:**
The Nginx issue added filtering ipv4 based on users geolocation. This issue is to add ipv6 to whitelist. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Users with ipv6 outside of US are blocked
- [x] Users with ipv6 inside US can login
- [x] All tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Rename the existing whitelist file to whitelist_ipv4
- [x] Create new whitelist file and name it whitelist_ipv6
- [x] Remove the wide range ipv6 from top of whitelist file
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://www.ip2location.com/free/visitor-blocker

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by raftmsohani** [comment]
Ip from Europe is blocked. See screen shots. 
![Screenshot 2023-04-18 at 12.17.06 PM.png](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/f458c4f7-c098-4aab-99fd-53be127d21f8)![Screenshot 2023-04-18 at 12.17.58 PM.png](https://images.zenhubusercontent.com/61d3697f7808855468eeaafa/30595e95-faba-4c33-8e1a-13ab0797b06e)
