### ISSUE TITLE
As sys admin, I need the API viewsets updated for the user, stt, and datafile apps

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2466]
**Description:**
We periodically query the api to track user requests and data submissions. Some of the fields that are available in the model viewsets are either deprecated or missing:

1. User
missing the following needed fields: `groups`, `superuser status`, `staff status`, `STT`, `account approval status`, `login UUID`, `HHS id`, `last login`, `date joined`
![user_viewset](https://user-images.githubusercontent.com/63075587/228555679-b3e3118f-78f2-4cc2-987c-5b337b56340e.PNG)

3. STT
missing: `STT_code`, `filenames`
![stt_viewset](https://user-images.githubusercontent.com/63075587/228555741-d98823c2-9c72-46b4-ac11-d2ca816819c3.PNG)

5. Data_files
missing: `version`, `s3 versioning id` , `file (location in s3)`
![datafile_viewset](https://user-images.githubusercontent.com/63075587/228555761-4f130174-bb70-4d81-a382-01835a73e4b0.PNG)

**Acceptance Criteria:** 
- [ ] response to user model queries include all relevant fields
- [ ]  response to data_files model queries include all relevant fields
- [ ]  response to stt model queries include all relevant fields
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by ADPennington** [comment]
superseded by #2489

**Comment by elipe17** [comment]
After some back and forth, it made the most sense to put the small changes #2489 would have added to this ticket into the #2477 PR to avoid multiple PRs. All work pertaining to #2466 and #2489 now live in the #2477 PR.
