### ISSUE TITLE
As a STT, I want to know what information is needed to create header and trailer for flat files

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#248]
**Description:**

During OFA research, we discovered that submitted flat files have header and trailer errors. Further research is needed to understand how the header and trailer are created for flat files, what is the cause of the errors, and what information can be automatically added (by default), and what information needs to be added by STTs. Having this understanding would allow us to standardize header and trailers and gather the correct information from STTs when creating flat files for submission. 

**What will not be done in this issue **

1. Standardization of header and trailers

**AC:**

- [x] Flat files are analyzed
- [x] Metadata (e.g., header and trailer) that will be validated by the MVP for creating a new report
- [x] New follow on issue(s) are created (e.g. exploring standardization)

**Tasks:** 

- [x] Review what is known about headers and trailers
- [x] Analyze sample text files 
- [x] Document what information is needed for the header
- [x] Document what information is needed for the trailer

**Supporting Documentation:**

(please include any relevant log snippets/ files/ screen shots here.)

**Open Questions:**

(any clarifying questions in support of the issue)

**DoD:**

 - [x] Documentation: Draft of information needed to create header and trailer for flat files has been shared with the PO and team for feedback
 - [x] @cmajel has reviewed and signed off
 - [x] @lfrohlich has reviewed and signed off

Deliverable(s):
- Documented header and trailer details can be found [here](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B1DFCC4C4-9A7C-4F97-8489-713AC8B85C4F%7D&file=%23248%20-%20Document%20Flat%20File%20Metadata.docx&action=default&mobileredirect=true):lock:

**Comment by lfrohlich** [comment]
Re: ACs, it would be good to have that distinction. If it is more of a lift to add that, please create a separate issue. Not sure if the variance is based on errors or why different files have different headers. If the latter I think that is covered. 
The data type fields in the header do depend on the section. 
All four sections contain monthly data, submitted quarterly. 
@reitermb  Could you revise the notes accordingly and clarify the first two ACs and introduce new issues if necessary?
Thanks!

**Comment by lfrohlich** [comment]
This looks great! I really appreciate the table and laying out the difference of automatic vs. guardrailed. i just have two questions in comments about how calendar year and data type could be automatic. Thanks for placeholder #302

**Comment by cmajel** [comment]
Agree this is helpful to see. I added a few notes about
*  The `Guardrailed (Technically Feasible)` column and what that tells us
*  How `data type` aka section can be automatic
*  Where we should capture some of these open research questions

Also ❤️  love the #302 placeholder to sync with dev on this for the next round of research. I'm good moving this forward 👍

**Comment by lfrohlich** [comment]
@reitermb  thanks for the response re: calendar year and data type, makes sense now. Closing this out.
