### ISSUE TITLE
as sys admin, i want the location-related fields in the user model to be sortable

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2482]
**Description:**
The location field is not currently sortable. This is because the location field is a combination of multiple fields in the user model, and not its own field. 
![location-sortable](https://user-images.githubusercontent.com/63075587/231493144-6c5d09d8-b972-4439-86ac-b2afa8d99cc9.PNG)

**Acceptance Criteria:** 

- [ ] Admins can sort the user list by location-related fields
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] update user model codebase
- [ ] Run Testing Checklist and confirm all tests pass
