### ISSUE TITLE
[SPIKE] Research parser performance

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2486]
**Description:**
After #2408 and #1113, we've noticed that the time required to parse large data files sits around 6 minutes (`ssp_section1_datafile.txt`, ~33,000 lines). Research the root cause and ways to make the process faster.

One thought is that repeated, synchronous database calls may be contributing to execution time. Django transactions may alleviate some of the issue
* Django transactions - https://docs.djangoproject.com/en/4.2/topics/db/transactions/

Another thought is that elasticsearch requests to back up postgres models (after django model `save`) may also be synchronous and contributing to long execution time. `django-elasticsearch-dsl` may have settings available to change the behavior.
* https://django-elasticsearch-dsl.readthedocs.io/en/latest/settings.html

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Identify root cause of any performance issues
- [ ] Identify mitigation steps
- [ ] Create a benchmarking test to compare and contrast current performance with any possible improvements
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by elipe17** [comment]
This has been blocked by the python dependency issue that has cropped up. It cant move further into the review process until that issue is resolved.

**Comment by elipe17** [comment]
Back in Raft review after some final code changes. upped environment memory requests by 1GB.
