### ISSUE TITLE
Resolve API Endpoints Security Issues

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2489]
**Description:**
During the implemenation of #2466 it was discovered that a myriad of security issues exist with the backend endpoints. That is, any authenticated user (admin or not) can query the endpoint and list all information about users. This is obviously bad and needs to be remedied. We would like to consider adding custom permissions to these endpoints to ensure appropriate access is managed. We would also like to re-consider whether all the fields that are returned from `v1/users` are appropriate. For this work, you will want to branch off of `2466-admin-viewsets`

**Acceptance Criteria:** 

- [ ] Only admin users can query api endpoints
- [ ] Discussion on `v1/users` resulted in unanimous agreement on returned fields
- [ ] Implementation of custom permissions alleviates the need for `DataFileFilter` in data file views
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create new permissions class that satisfies ACs
- [ ] Update unit tests to invoke API functionally per support docs belowconfirm 
- [ ] Unit tests created for admin users vs non-admin users in regards to API results
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_
- Please see similar unit tests [here](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/data_files/test/test_api.py#L242) name `test_data_analyst_gets_email_when_user_uploads_report_for_their_stt1`

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
## Baseline check of access to TDP API

The API is accessible from `..frontend../v1/` (e.g. https://tdp-frontend-staging.acf.hhs.gov/v1/). All API endpoints that will be checked are available here: `..frontend../swagger/` (e.g. https://tdp-frontend-staging.acf.hhs.gov/swagger/)

This will be the basis for `qasp` review  of PR #2477.  We want to avoid enabling API access beyond what non-admin users already have. We may also need follow-on tickets to address access that non-admins currently have, but shouldn't. 

### 1. What parts of the API can **unauthenticated users** access?

   - as a logged out user, hitting any of the API endpoints returns the following: :ok_hand: 

        ```
        HTTP 403 Forbidden
        Allow: GET, HEAD, OPTIONS
        Content-Type: application/json
        Vary: Accept

        {
            "detail": "Authentication credentials were not provided."
        }
        ```

### 2. What parts can **authenticated users with no role** access?

- as logged in, authenticated user who has not requested access, hitting the `../v1` endpoint returns the following: :ok_hand:

    ```
    HTTP 200 OK
    Allow: GET, HEAD, OPTIONS
    Content-Type: application/json
    Vary: Accept

    {
        "roles": "https://tdp-frontend-staging.acf.hhs.gov/v1/roles/"
    }
    ```
- then, tried hitting the `roles` endpoint referenced above, and the following was returned: :ok_hand:

    ```
    HTTP 403 Forbidden
    Allow: GET, HEAD, OPTIONS
    Content-Type: application/json
    Vary: Accept

    {
        "detail": "You do not have permission to perform this action."
    }
    ```
- tried all other endpoints behind `../v1/..`:
   - `../v1/auth_check` returns all info that would be in the user's profile in DAC + the `csrf token`. :ok_hand:
   - `../v1/data_files` returns `"detail": "You do not have permission to perform this action."` :ok_hand:
   - most endpoints returns the 403 response, except the following:
     - `../v1/stts/` returns STT metadata :ok_hand: 
     - `..v1/users/{id}` returns the user's own profile metadata (same as what is in `..v1/auth_check`) :ok_hand:
     `..v1/users/request_access/` allows me to modify the STT and region in my profile.  (_all **patch** requests to the profile are allowed_) :warning:
     - `..v1/parsing/parsing_errors` returns a really long hash. :question:

- tried all endpoints when account_approval_status = `Initial` and `Access Request`. the results were the same. 


### 3. What parts can an **authenticated user with a `Data Analyst` role** access? (_this is most of our user base_)
- as logged in, authenticated user with a `data analyst` role, hitting the `../v1` endpoint returns the following:
    ```
    HTTP 200 OK
    Allow: GET, HEAD, OPTIONS
    Content-Type: application/json
    Vary: Accept

    {
        "roles": "https://tdp-frontend-staging.acf.hhs.gov/v1/roles/"
    }
    ```
- then, tried hitting the `roles` endpoint referenced above, and the following was returned:

    ```
    HTTP 403 Forbidden
    Allow: GET, HEAD, OPTIONS
    Content-Type: application/json
    Vary: Accept

    {
        "detail": "You do not have permission to perform this action."
    }
    ```

-  tried all other endpoints behind `../v1/..`:
   - `../v1/auth_check` returns all info that would be in the user's profile in DAC + the `csrf token`. :ok_hand:
   - `../v1/data_files` returns a form field which could be used as an alternative method for submitting data files manually or via API post request (only for user's STT) :warning:
   - most endpoints returns the 403 response, except the following:
     - `../v1/stts/` returns STT metadata :ok_hand: 
     - `..v1/users/{id}` returns the user's own profile metadata (same as what is in `..v1/auth_check`) :ok_hand:
     `..v1/users/request_access/` allows me to modify the STT and region in my profile.  (_all **patch** requests to the profile are allowed_) :warning:
     - `..v1/parsing/parsing_errors` returns a really long hash. :question:
 

### 4. What parts can a **`OFA Admin`** access? 

- can access `../v1/auth_check` endpoint.:ok_hand:
- can access `../v1/roles` endpoint.:ok_hand:
- can access `../v1/data_files` endpoint (for any STT).:ok_hand:
- can access `../v1/users/{id}` endpoint (for any user).:ok_hand:

### 5. What parts can a **`OFA System Admin`** access? 
 
 - same access as `OFA Admin`

### What parts can a user with `ACF OCIO` role access?

- `..v1/auth_check` for self :ok_hand:
- `../v1/users/{id}` for self :ok_hand:
