### ISSUE TITLE
Create root-level docker-compose configuration file(s)

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2491]
**Description:**
_Provide a brief background and justification for this issue_
For simplicity, we'd like to collapse our docker configurations into a single docker-compose file at the root.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Docker compose files are not stored within backend/frontend folders but at repo root
- [ ] `commands.sh` commands still work
- [ ] Pipelines continue to function normally
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Combine the current 4 docker-compose files into a parent set for root of the repo
- [ ] Adjust `commands.sh` for new simplified configuration
- [ ] Adjust relevant pipelines for new simplified configuration as necessary
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Will have Dockerfiles at directory below (frontend/backend) cause an issue?

**Comment by raftmsohani** [comment]
With #2960 this issue is a dup and can be closed
