### ISSUE TITLE
as tech lead, i need nightly scan workflow to run successfully with nginx+domain changes

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2494]
**Description:**
since the release v3.0.2, nightly scan is failing. the screenshot below is from `hhs:main`. 

![nightly_nginx_domain](https://user-images.githubusercontent.com/63075587/233155387-9739cd97-fed6-4d2e-81c6-dbffb60e2c7d.PNG)

looks like we may be missing the app_urls for scenario when environment = "nightly" but target_env != 'prod':
https://github.com/raft-tech/TANF-app/blob/cd35c12f46e0808c494a1161bec6b9e5b6600dfd/scripts/zap-scanner.sh#L15L27

**Acceptance Criteria:** 
- [ ] nightly scan workflow should run successfully
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] tbd
- [ ] Run Testing Checklist and confirm all tests pass
