### ISSUE TITLE
[Design Deliverable] May Knowledge Center Enhancements 

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2503]
**Description:**

**AC:**

- [ ] Changed staged in Test environment
- [ ] PR to raft-tech opened
- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Add knowledge center guidance re: grantee employee offboarding. MVP of this is maybe an FAQ? 
   - [x] Tackles the fact that we're reliant on being told when somebody who has access to TDP should be removed prior to their 180 day timeout. Asks that grantee staff notify us when somebody on their team should have their access removed. 
- [x] Update images
   - [x]  on exporting complete data using ftanf guide: can we change the picture [here](https://tdp-project-updates.app.cloud.gov/knowledge-center/exporting-complete-data-using-ftanf.html) under step 2 such that reset transmission flag is step 1?
- [x] If not already implemented, embed videos in Getting Started & Submitting Data pages on Knowledge Center (#2439)
- [x] Release notes for: 1) coming soon error reporting, 2) KC Videos 3) improved FAQs

**Supporting Documentation:**

—Link to Figma and Dev-Ready Design folder PDF—

**Comment by reitermb** [comment]
Finalizing some copy but I think we're ready for a11y review on this @ttran-hub. 

All changes are live in the test environment: https://reitermb.github.io/Test/knowledge-center/index.html

- [ ] YouTube video embeds on New/Existing login.gov pages and submitting data page
- [ ] Updated release notes
- [ ] Updated image on the fTANF guide
- [ ] FAQ (headings based) quick-nav and new FAQ item

Noting that I'm running into an axe error on the YouTube elements but I'm not sure it's a solvable one. It seems to be objecting to something YouTube does with the channel logo where it's a hover-interaction-only link that expands with more channel details and a button when you hover it. Doesn't seem to be keyboard navigable. It's also unfortunately not an element that I have control over as part of the iframe, it's one that the YouTube API pipes in. That said, core video functionality works just fine.

**Comment by reitermb** [comment]
@lfrohlich @ADPennington 

Ready for content review! This update includes:
- New release notes
- Video embeds
- Updated image on the fTANF guide to tweak the order of steps on image 2
- FAQ item for offboarding guidance 
- FAQ quick nav

**Comment by lfrohlich** [comment]
Looks good to me! Thanks @reitermb

**Comment by ttran-hub** [comment]
> Noting that I'm running into an axe error on the YouTube elements but I'm not sure it's a solvable one. It seems to be objecting to something YouTube does with the channel logo where it's a hover-interaction-only link that expands with more channel details and a button when you hover it. Doesn't seem to be keyboard navigable. It's also unfortunately not an element that I have control over as part of the iframe, it's one that the YouTube API pipes in. That said, core video functionality works just fine.

Link to the [HHS axe monitor](https://hhs-axemonitor.dequecloud.com/worldspace/organizationProject/pages/125?SYNCHRONIZER_TOKEN=56d7f010-9990-4c1f-b23c-1b1ee2e73ada&SYNCHRONIZER_URI=%2Fworldspace%2ForganizationProject%2Fpages%2F125&urlContains=&titleContains=&pageStatus=Completed&showNeedsReview=on&cleanOnly=on&go=Search&selectedpageids=&application=delete&pageSize=20&page=1&startNo=0&share=bd7715e2560929a7e13d99d61532254f7fea5951) report for the Test/TDP-Knowledge-Center for reference and manual review.

It does seem like part of a YouTube video embedded in an inline frame. CC is available once the video is played and was accessible with keyboard. It is worth more research with the iframe element, but it should not hold up the PR.

It's really nice to have links to the tutorial videos in the Knowledge Center.  Thanks @reitermb! a11y 🚀
