### ISSUE TITLE
As a data analyst, I need to know when my data has been processed with or w/o errors

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2509]
**Description:**
Generate email to STT data analysts for error reports on submitted datafiles. this email will replace the current data submission email that STT users currently receive. 

**Acceptance Criteria:** 
- [ ] Aligned with design spec ("Near Term Lower-lift" version):
   - [ ] Data analysts receive email notification that their data is processed
   - [ ] Email subject leads with whether or not their data file had errors
   - [ ] Email table contains columns for section, submitted by, and error report (Error Report Available/No Errors being possible values)
   - [ ] Email body contains copy on where to access the error report in TDP and where to go for more information in the knowledge center
- [ ] Replaces existing notifications for data file submission
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Create new email template [here](https://github.com/raft-tech/TANF-app/tree/develop/tdrs-backend/tdpservice/email/templates)
- [x] Find conditional/trigger for when error reports are ready
- [x] Test null values for all variables
- [x] Remove old email template for data submission**
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Pull in after 1) Parsing Enhancements and 2) Error Messaging epics are complete.

**Supporting Documentation:**
- [Design spec (HTML)](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/error-report-available-low-lift.html)

Screenshot w/ replacement tags
![image](https://github.com/raft-tech/TANF-app/assets/28515874/b84c6f6b-65ae-4d35-98be-16b0efdb8b33)

Screenshot w/ example values
![image](https://github.com/raft-tech/TANF-app/assets/28515874/7f49116b-f67b-4f2a-b25e-4b11da09290d)

**Open Questions:**

- How can this be made as a stepping stone to ultimately #2248 ?
- Do we indeed want to replace the old email template for data submission even for minutes delay?

**Comment by Smithh-Co** [comment]
@lilybl1 @reitermb Hi team, post backlog refinement 5.9, we need updated copy for this ticket regarding a figma/html template and alignment on content/CTA wording to current errors research prototypes.

Tagging this as high priority for development ahead of v3.3 as well - TY

**Comment by reitermb** [comment]
2pts left depending on unit tests

**Comment by robgendron** [comment]
2 points remaining.

**Comment by lfrohlich** [comment]
@ttran-hub  could you do an a11y review?

**Comment by reitermb** [comment]
![image](https://github.com/raft-tech/TANF-app/assets/28515874/ef7504eb-43d7-4a08-a585-4f68577f34b1)

Refreshed a11y review from the Raft side. Noting that the 3 errors listed there are regarding the control at the top to toggle between nearer and later term versions of the email template, not the template itself--so this is equivalent to a clean scan for the actual content being evaluated. 

cc @ttran-hub

**Comment by ttran-hub** [comment]
a11y 🚀LGTM.
