### ISSUE TITLE
[Research Synthesis] Spring Research - Exploring Error Reports

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2516]
**Description:**
This is the research and findings that resulted from the Spring 2023 sessions around error reports. 

**Tasks:**
- [x] --Aggregate notes from research sessions--
- [x] Delete video recording(s) once notes are compiled - scheduled to expire in 120 days
- [x] Summary
- [x] Who we talked to 
- [x] What we did
- [x] What we tested
- [x] What we learned
- [x] What's Next
- [x] Issues that have to be added to Zenhub
- [x] Takeaways for future research

**Supporting Documentation:**
[Hack.md Link](https://hackmd.io/@dliang/HkeRnHFr3/edit)

**Comment by lilybl1** [comment]
First draft for internal Raft review.

**Comment by reitermb** [comment]
@ADPennington ready for a final pass!

**Comment by ADPennington** [comment]
added a couple of minor comments. @reitermb can you let me know how/if these were addressed as a comment in this ticket?

**Comment by ADPennington** [comment]
@reitermb can this be closed?

**Comment by reitermb** [comment]
> @reitermb can this be closed?

Yes, good to close!

**Comment by ADPennington** [comment]
closing as completed with #2581
