### ISSUE TITLE
"nightly" owasp scan after qasp deployment

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2526]
**Description:**
We have a persistent pipeline failure for the nightly scan, please see supporting documentation.

**Acceptance Criteria:** 

- [x] Ensure nightly scan is running to completion successfully and pipeline reflects status
- [x] Ensure artifacts are being saved to security tab in staging/prod apps.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Investigate pipeline or ZAP failure for resolution
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

- https://app.circleci.com/insights/github/raft-tech/TANF-app/workflows/nightly/overview

**Open Questions:**

**Comment by robgendron** [comment]
@ADPennington @lfrohlich, is this still needed or can it be closed?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich, is this still needed or can it be closed?

Yes this is still needed.

**Comment by robgendron** [comment]
Needs investigation to ensure artifacts are uploaded but this may no longer be needed given other work on zap in the past unless the uploads are failing.

**Comment by ADPennington** [comment]
> Needs investigation to ensure artifacts are uploaded but this may no longer be needed given other work on zap in the past unless the uploads are failing.

@robgendron worth some discussion before closing. the original goal for this ticket is to have the zap scan run in a deployed apps when the qasp label is added to PRs. it currently does not.

**Comment by andrew-jameson** [comment]
Scan is running and results uploaded successfully. This ticket is no longer needed.

<img width="1088" alt="Screenshot 2024-07-29 at 10 07 57 AM" src="https://github.com/user-attachments/assets/04fb5558-4cd6-4297-896f-61e4a7aca4d0">
