### ISSUE TITLE
[Design Deliverable] Error-research informed Excel Error Report design

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2527]
**Description:**

Delivers final spec for excel-based TDP error reports. 

**AC:**

- [x] Internal Raft Review has occurred to ensure DoD standards and QA
- [x] Dev/Design sync has occurred; resulting tickets created
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft final excel prototype reflecting design choices/research insights
   - [x] Include itemized list of changes relative to current parsing engine output (attached to comment below)
- [x] Annotate implementation notes
- [x] Audit section 1 errors to inventory weird/difficult to templatize or fit into error report edge cases that may be encountered as further parsing is added
- [x] Schedule dev:design sync

**Supporting Documentation:**
- [x] [Excel prototype](url)

**Comment by reitermb** [comment]
[2023-Q1-SSP Active Case Data.xlsx](https://github.com/raft-tech/TANF-app/files/11709429/2023-Q1-SSP.Active.Case.Data.xlsx)

**Comment by reitermb** [comment]
From dev: design sync

- Bolded Headings (If our excel generator has that power)
- Underscores -> spaces
- Plain language conversion for Reporting Month (e.g. 202302 -> February 2023)
- Column order
- Columns shown

Tangentially: 
- Friendly names for attributes (these should be 1:1 for Item names in the coding instructions)

**Comment by lilybl1** [comment]
This ticket is ready to close - I'm creating a dev ticket based on our discussion around the Error Report today.

**Comment by lilybl1** [comment]
Dev ticket created here - https://github.com/raft-tech/TANF-app/issues/2599

cc: @Smithh-Co @ADPennington @lfrohlich
