### ISSUE TITLE
STRETCH: Spike/attempt to implement cat4 validation as well

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2536]
**Description:**
This ticket is to scope out cat4 validation for inter-file consistency validation.

**Acceptance Criteria:** 

- [ ] Template/interface for a reusable methodology for consistency/integrity checks across differently formatted fields of the same sections
- [ ] Template/interface for a reusable methodology for consistency checks of aggregate numbers (stratum vs active #)
- [ ] Mechanism should ideally be program-type agnostic or take it in as a parameter
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Scope/Implement higher-order mechanism(s) for section-wide consistency comparisons
- [ ] Comparing header quarter to multiple sources (frontend submission qtr, RPT-MONTH-YEAR fields, etc.)

**Notes:**
![image](https://user-images.githubusercontent.com/28515874/215615601-8cd6473e-b4ac-4e1f-a0a7-352464eb838e.png)
https://app.mural.co/t/raft2792/m/raft2792/1675119530632/15dc23ac92cc546ac1212455f4bea1bd6cb368dd?sender=mreiter1745 - Mural Version

**Supporting Documentation:**
- [Condensed cat4 notebook](https://gorafttech.sharepoint.com/:x:/s/TDRSResearchDesign/Ebcv7lByTM1Dk3VX4OZaTf0BvBSqAJnv6n9IFvkKVSqd-g?e=3SAnHZ)🔒 
- [Parsing Folder OneNote](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev%2Fdev%2FParsing%2Fdata&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46) 🔒 

**Open Questions:**

**Comment by andrew-jameson** [comment]
- t1 family should have individual records associated and vice versa
- check for disposition=2

**Comment by andrew-jameson** [comment]
Hmm, this is posing some interesting architecture-level problems. Things I've confirmed:

- header/trailer need to be stored as records properly
- we'll want a parent-class to SchemaManager
- I think a TDD approach will work wonders here
- we'll want an abstract structure for holding case-level data for Active/Closed 
- we need a way to store validators at a level above RowSchema
```
QTR - cat5/6 -- post parity
    activeSection  - cat4
        header - cat1,2
        t1 - cat2,3
        t2 
        t3
        trailer
    closedSection
        header
        t4
        t5 
        trailer
    stratum 
        num_applicants == active where joindate => qtr
'''
```


Open questions still:

- My condensed list of cat4 validators seems like it could use embellishment -- will want to review with OFA prior to implementation
- What inheiritance structure for SchemaManagers and cat4 is useful?
- What modularity can we invoke for the abstract structure for both case-level data and the aggregate stratrum data?
- What's the overlap between case_aggregates and the case-level data?
- Are querysets still the proper way forward?
