### ISSUE TITLE
[Design Deliverable] Final mockup for error report available email

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2559]
**Description:**

Delivers final templates for email notifications re: new available error reports in TDP 

**AC:**

- [x] HTML templates match planned changes (documented [here](https://app.mural.co/t/raft2792/m/raft2792/1670442812740/df177d3bb67bd1a9921614d0261a1abb15214bc5?wid=0-1682096681687))
- [x] Internal Raft Review has occurred to ensure DoD standards and QA
- [x] Dev/Design sync has occurred; resulting tickets created
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Update email templates in HTML email demo environment

**Supporting Documentation:**

[HTML Email Templates](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/error-report-available-low-lift.html)

**Comment by reitermb** [comment]
All changes from prod sync have been pushed to the demo environment! Including an example of the near term template with example data in addition to the version with replacement tags as per @andrew-jameson 's request. 

Templates can be demoed here: https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/error-report-available-low-lift.html

cc @Smithh-Co @lfrohlich @ADPennington

**Comment by ADPennington** [comment]
> SSP Data Processed With Errors

@reitermb below is a screenshot of current data submission emails. It looks like `section_name` is also included in the subject line, though i cant quickly find where in the codebase the subject line is generated. So its possible that the proposed template subject could look like the following, maybe? 

> SSP Processed With Errors



![emails_ssp](https://github.com/raft-tech/TANF-app/assets/63075587/21a46609-442d-414b-9d7f-4347da8f6ab0)

**Comment by reitermb** [comment]
> > SSP Data Processed With Errors
> 
> @reitermb below is a screenshot of current data submission emails. It looks like `section_name` is also included in the subject line, though i cant quickly find where in the codebase the subject line is generated. So its possible that the proposed template subject could look like the following, maybe?
> 
> > SSP Processed With Errors


Thanks @ADPennington, corrected and pushed up (also fixed a div tag that may have been preventing the enhancement radio buttons from working earlier today)!

**Comment by reitermb** [comment]
@ADPennington Pushed one more update to correct the tag to: 

{File Type} {Section Name} {Processed With Errors / Processed Without Errors} ==> SSP Data Processed With Errors

**Comment by ADPennington** [comment]
`qasp` approved thanks @reitermb 🚀

**Comment by ADPennington** [comment]
can we close this @reitermb

**Comment by reitermb** [comment]
> can we close this @reitermb

Yes, good to close!
