### ISSUE TITLE
Spike: parsing log per file upload

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2562]
**Description:**
To assist future debugging and better operational capacity, it would be ideal to be able to easily find the relevant logging for a given parsing session for a file upload.

**Acceptance Criteria:** 

- [ ] Proposed and actionable plan for implementation without significant infrastructure lift (ideally, backend-only or with lightweight microservice)
- [ ] System admin should intuitively be able to find the parser output for a given datafile (stt/qtr/section)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Spike
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Utilize duplicate django logging, store file via s3? Alternatively, lightweight microservice like logstash or sentry per comment below in open questions.

**Supporting Documentation:**

**Open Questions:**

- Do we need [831](https://github.com/raft-tech/TANF-app/issues/831#issuecomment-1057110419) or can we MVP this via only backend?

**Comment by andrew-jameson** [comment]
#3122 Review: How do we want a log file to look and be useful both for per-field validation but also at a callstack level showing positively each step taken?

**Comment by lhuxraft** [comment]
11/13/2024: Working through feedback from team, published a draft PR and will discuss during office hours

**Comment by lhuxraft** [comment]
11/15: Received feedback, cleaning up notes and published for Raft review

**Comment by lhuxraft** [comment]
11/18: Finishing up, should be up for review later today

**Comment by lhuxraft** [comment]
11/20: Need to create follow-on tickets, ready to merge. Alex will review during office hours today. Can close after
