### ISSUE TITLE
Adjust TANF and SSP Section 1 item numbers per OFA guidance

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2564]
**Description:**
Alex found via [this comment](https://github.com/raft-tech/TANF-app/pull/2504/files/a31b32f9d2b6b0a582bca87db6487b5adaacbc33#r1218263890) that we are using the wrong item numbers. It appears we did not consult the correct ordering. Please see document section below for updated excel spreadsheets which directly link item number and description and update our RowSchema accordingly.

As a data analyst, I need TANF and SSP Section 1 item numbers to match OFA documentation.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] All displayed error messages should output items numbers that map to the supporting documentation.

- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Will need excel docs for everything not T1 - @ADPennington 
- [ ] Adjust item numbers in RowSchema for all SSP Section 1
- [ ] Adjust item numbers in RowSchema for all TANF Section 1
- [ ] Spike: analyze any locations that these updated item numbers could conflict (like in t1 models in prod)
- [ ] Coordinate with Alex to ensure prod item numbers are overwritten in an automated fashion.
- [ ] Adjust any tests as needed
- [ ] STRETCH: Look for modular way to update these item numbers in the future.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Please avoid migration(s) if possible.

**Supporting Documentation:**

- [T1 sheet](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BF99CEA75-18CC-4494-9302-677CC92E3EF4%7D&file=TDP_Validation.xlsx&action=default&mobileredirect=true)
- [SSP, M1-M3](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BD750ECCD-B320-4E7A-B7F6-C9354B84F61B%7D&file=TDP_Validation_SSP_Section1.xlsx&action=default&mobileredirect=true)
- [99 page doc](https://gorafttech.sharepoint.com/:w:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BFD51E66D-6DDA-47AA-A970-29006EEC07F3%7D&file=TANF-SSP%20data%20instructions_clean.docx&action=default&mobileredirect=true)

**Open Questions:**

- Update these values in stored ParserError objects in prod DB?

**Comment by ADPennington** [comment]
- `T2_Cat2` and `T3_Cat2` sheets added [TDP_Validation_TANF_Section1.xlsx](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/Parsing/data/tanf/Section1/TDP_Validation_TANF_Section1.xlsx?d=wf99cea7518cc44949302677cc92e3ef4&csf=1&web=1&e=WPDFZx) -- includes item numbers

- `M1_Cat2` , `M2_Cat2` and `M3_Cat2` sheets added [TDP_Validation_SSP_Section1.xlsx](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/Parsing/data/ssp/TDP_Validation_SSP_Section1.xlsx?d=wd750eccdb3204e7ab7f6c9354b84f61b&csf=1&web=1&e=ZVbesW) -- includes item numbers 

Minor edit to fix links
