### ISSUE TITLE
[Design Deliverable] Knowledge Center Additions (June+)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2568]
**Description:**

Will be regularly refined/extended until we bring it into a sprint. Aggregates next collection of changes we want to bring to the Knowledge Center.

**AC:**

- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] Guidance on high volume of errors—next steps for folks experiencing a turbulent systems transmission 
- [ ] Guidance on SSN errors? Re: potential that they might turn up but be unresolvable (if SSN doesn't exist yet) or in some weird edge case of non-standard encryption? 

**Notes:**
- Revisit SSN errors once we have Cat 3 error usage to evaluate from userbase

**Comment by robgendron** [comment]
@reitermb is this still needed?

**Comment by lhuxraft** [comment]
No longer needed
