### ISSUE TITLE
[Research Facilitation] Follow-on error research with 2 STTs

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2569]
**Description:**
Facilitates follow-up research sessions with two STTs from errors round research.

**AC:**

- [ ] Research sessions have occurred.
- [ ] Anonymized session notes or other top-line synthesis have been documented.
- [ ] Changes to recruitment criteria have been documented if recruitment/target participant pool has been expanded.

**Tasks:**

- [x] Produce excel-based error reports based on actual May data submissions
- [x] Send error report for corrections
- [ ] Update synthesis document to capture new findings (if relevant/project impact-y)
- [ ] Follow up at 30 day 

**Supporting Documentation:**

- [Example of prototype used for May/this errors research](https://reitermb.github.io/HTML-Table-example/xlsx-login)
- [Synthesis](https://hackmd.io/@dliang/HkeRnHFr3/edit)

**Comment by lilybl1** [comment]
Updated error report has been sent to 2 states as follow-up.

**Comment by reitermb** [comment]
Closing — Outdated ticket. Follow-on research occurred and will be covered in next revision of research synthesis folder
