### ISSUE TITLE
As an OFA Analyst, I need only the most recent version of STTs' parsed data

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2579]
**Description:**

In TDRS, OFA data staff have access to ~~only~~ the most recent version of parsed data submitted for each STT, section, and fiscal period. This should also be the case in TDP.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] The default view of parsed data by OFA staff should be only most recent upload
- [ ] OFA system administrators should be able to see non-recent parsed data if desired
- [ ] TBD
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] #2583
- [ ] Implement Elasticsearch/Kibana filtering queries based upon originating datafile reference
- [ ] TBD
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- STTs routinely re-submit sections of data. TDRS relies on the [update indicator](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_system_edits_fatal_and_warning.pdf) to manage revisions in the db. When indicator is "D", any previously submitted data from the STT for the given section and fiscal period is deleted and overwritten by the contents in the resubmitted file. Otherwise, data is either added ("N") or updated "U") in the db. 
- OFA expects complete and accurate data in every submission, so only the most recent version of data submitted is needed. 
- all other versions of the parsed data should be available to query periodically (eg quarterly) by sys admins. 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**

- should TDP check the update indicator in the Header? it should be "D". If the update indicator is not "D", should TDP still parse or raise a cat 1 error (pre-parsing error)?
- is it feasible to retain all versions of parsed data for sys admins (eg, for trend-tracking purposes)?
- Will we hit storage limits within our data retention lifecycle? [docs](https://cloud.gov/docs/services/relational-database/)

**Comment by elipe17** [comment]
This has been blocked by the python dependency issue that has cropped up. It cant move further into the review process until that issue is resolved.
