### ISSUE TITLE
Deploy celery as a separate cloud.gov application

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2592]
Per https://github.com/raft-tech/TANF-app/issues/2347#issuecomment-1590012582 

> * Deploy celery as a separate cloud.gov application (separate manifest)
>    * independently scalable
>    * requires separate redis service - draft pr https://github.com/raft-tech/TANF-app/pull/2590

**Description:**

Deploying celery as a separate application alleviates the application server and allows each to be independently scalable. This (roughly) requires:

1. Deploy redis as a separate service
   1. See [draft pr](https://github.com/raft-tech/TANF-app/pull/2590) allowing django/celery to communicate with an external redis service as a broker.
   2. Remove redis-related lines from `gunicorn_start.sh`
      ```bash
      set -e

      echo "REDIS_SERVER"
      echo "redis local: $REDIS_SERVER_LOCAL"
      if [[ "$REDIS_SERVER_LOCAL" = "TRUE" || "$CIRCLE_JOB" = "backend-owasp-scan" ]]; then
          echo "Run redis server on docker"
      else
          echo "Run redis server locally"
          export LD_LIBRARY_PATH=/home/vcap/deps/0/lib/:/home/vcap/deps/1/lib:$LD_LIBRARY_PATH
          ( cd  /home/vcap/deps/0/bin/; ./redis-server /home/vcap/app/redis.conf &)
      fi
      ```
   3. Remove redis from deployed application dependencies [`apt.yml`](https://github.com/raft-tech/TANF-app/blob/f7dcaf659ef58a99b51e8364bb67112d697a4709/tdrs-backend/apt.yml#L9)
   4. Remove `REDIS_URI` env [`manifest.buildpack.yml`](https://github.com/raft-tech/TANF-app/blob/f7dcaf659ef58a99b51e8364bb67112d697a4709/tdrs-backend/manifest.buildpack.yml#L8)
   5. Deploy redis in cloud.gov and bind to application deployment using circleci
      * Add redis service binding in [deploy-backend.sh]()

2. Deploy celery as separate cloud.gov application, with its own manifest
   1. Make a copy [`manifest.buildpack.yml`](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/manifest.buildpack.yml) (named `manifest.celery.yml` or similar)
   2. Update the `command` in the new manifest to run a script starting celery, removing [these lines from `gunicorn_start.sh`](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/gunicorn_start.sh#L21C1-L27C0)
      ```bash
      celery -A tdpservice.settings worker -c 1 &
      sleep 5
      # TODO: Uncomment the following line to add flower service when memory limitation is resolved
      celery -A tdpservice.settings --broker=$REDIS_URI flower &
      celery -A tdpservice.settings beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler &
      ```
   3. Deploy the new celery application in cloud.gov using circleci
      * must be bound to all same services as main application
      * copy/abstract logic in `deploy-backend.sh` - env var logic needs to exist for both celery/app, `cf push` new manifest

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Celery is deployed as its own cloud.gov application, changes are deployed via circle ci
- [ ] Redis is deployed as a standalone cloud.gov service, bound to both celery and the main application
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by George-Hudson** [comment]
PR here: https://github.com/raft-tech/TANF-app/pull/2773

**Comment by lhuxraft** [comment]
Jan to create a follow-on ticket to capture work that is left to do
