### ISSUE TITLE
[SPIKE] Investigate the failed `staging-deployment` workflow in HHS/TANF-app:main for sprint 75 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2598]
**Description:**
when attempting to push release `v3.1.2 (sprint 75)` to the staging env, the `staging-deployment` workflow is failing in the HHS repo at the deploy backend step

![sprint75_fail](https://github.com/raft-tech/TANF-app/assets/63075587/f030d637-a736-4565-b7e4-cbd6387a7367)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] STRETCH: #2435 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
### Notes from sys admin sync on 6/27 troubleshooting 

After the initial failure in CircleCI, we tried the following:
- from CLI, `cf restage tdp-backend-staging`. the result was as follows:
```
16:46:33.109: [APP/PROC/WEB.0] 93:M 27 Jun 20:46:33.108 * Ready to accept connections
16:46:34.924: [APP/PROC/WEB.0] Migrations for 'users':
16:46:34.925: [APP/PROC/WEB.0]   tdpservice/users/migrations/0039_alter_user_options.py
16:46:34.925: [APP/PROC/WEB.0]     - Change Meta options on user
16:46:36.573: [APP/PROC/WEB.0] Operations to perform:
16:46:36.573: [APP/PROC/WEB.0]   Apply all migrations: admin, admin_interface, auth, authtoken, contenttypes, core, data_files, django_celery_beat, parsers, search_indexes, security, sessions, stts, users
16:46:36.687: [APP/PROC/WEB.0] Running migrations:
16:47:32.956: [HEALTH.0] Timed out after 1m0s (30 attempts) waiting for readiness check to succeed: failed to make TCP connection to 10.255.47.24:8080: dial tcp 10.255.47.24:8080: connect: connection refused
16:47:32.956: [CELL.0] Failed after 1m0.23s: readiness health check never passed.
16:47:32.959: [CELL/SSHD.0] Exit status 0
16:47:49.298: [CELL.0] Cell dd6f432d-8d2d-456e-b9fb-38da759216ce stopping instance b971e764-bb20-4cd2-6b67-7657
16:47:49.298: [CELL.0] Cell dd6f432d-8d2d-456e-b9fb-38da759216ce destroying container for instance b971e764-bb20-4cd2-6b67-7657
16:47:49.401: [PROXY.0] Exit status 137
16:47:49.305: [API.1] Process has crashed with type: "web"
```

- re-run the workflow from CircleCI also did not work
- we rolled back to sprint 74 commit in CircleCI and  this deployment was successful.

**Comment by andrew-jameson** [comment]
Stretch goal would be to address #2435 during diagnosis and resolution here to prevent manual rework of setting staging env vars after every deploy. HHS circleci does not have staging-specific env vars nor does raft-tech.

**Comment by raftmsohani** [comment]
Ideas: 
1) Create a branch without the User model changes (the aim is not to have the migration) and validate whether the deployment is successful without migration
2) If step 1 is successful, then should be able to ssh into the instance, re-add the changes to the deployed version and create migrations and run them -> this makes sure the migrations are being deployed manually into the database
3) add print/log statements to check the followings:
    - database connection
    - User model: should be able to get the User model definition
    - Print statement for each step in gunicorn_start.sh: we suspect the failure is in ```python manage.py migrate``` step, but need to have print statements before/after to verify
