### ISSUE TITLE
As a grantee, I would like to be able to view the Error Report so that I can make corrections that impact my WPR metrics in a timely fashion. 

### ISSUE THREAD

**Issue by lilybl1** [raft-tech/TANF-app#2599]
**Description:**
As a grantee, I would like to be able to view the Error Report so that I can make corrections that impact my WPR metrics in a timely fashion. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

Scenario: Be able to download the Excel
Given the grantee has logged into TANF Data Portal
And is viewing the Submission History with Error Report Status
When the grantee clicks the Error Report link an Excel spreadsheet is downloaded

Scenario: Be able to download the open and view the Excel spreadsheet
Given the grantee has clicked to open
And view the Excel spreadsheet
When the Excel spreadsheet is open - please see the Excel example (attached)

[Error Report](https://gorafttech.sharepoint.com/:x:/s/TDRSResearchDesign/ETlTA9K7mG1Pp023CgApZcYBBA0bPMNGuScsA7Z5AcAOtw?e=j8tf8V)

- Upon opening the width of the columns are pre-adjusted to fit the content except for Line 1 which should display across the top
- Line 1: existing - Error reporting in TDP is still in development. We'll be in touch when it's ready to use! For now please refer to the reports you receive via email.
- Empty Line Item to create break between heading and errors
- Column Headers are bolded
- Case Number - 	
- Reporting Month - convert to display Month (January - December) 
- Reporting Year - YYYY	
- Error Message - displays the error message with item numbers defined based off of the coding instructions and style guide

Item Number 
 - Single item number - display as is (21A)
 - Multiple item numbers - display each item number value and insert a comma in between each item number (ex. 21A, 21B)
 
Item Name 
 - Primary Only - display as is based off of the coding instructions
 - Primary Name and Sub Name - display the sub name based off of the coding instructions	
 
Internal Variable Name - the internal coding names that Alex provided 
 - Single variable name - display as is (ex. CASH_AMOUNT)
 - Multiple variable names (CASH_AMOUNT, NBR_MONTHS) - separate each variable name with a comma

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Ensure task list for required items are implemented (see error report example and bullets listed above)
- [ ] Schedule review with UX and PM
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Style Guide](https://hackmd.io/J9mD0jeUSVm3QgJucSo5_g)
- [Excel Spreadsheet](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BD2035339-98BB-4F6D-A74D-B70A002965C6%7D&file=2023-Q2-Active-Hawaii.xlsx&action=default&mobileredirect=true)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
