### ISSUE TITLE
Down for maintenance page

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2618]
**Description:**
Create a static page and have nginx render this for all routes if a env var is set to True

Old ticket: #2066

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] STRETCH: include same headers/footers as in the 404 error
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement nginx location based on environment variable
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by raftmsohani** [comment]
UPDATE Jul 28th: Nginx has a js module which can be used to implement any logic, however the javascript package is not pre-installed in Nginx buildpack. The package can be used to query, authenticate, etc (to see some examples, look into https://github.com/nginx/njs-examples#reading-subject-alternative-from-client-certificate-http-certs-subject-alternative)

Although we can install the package, there are easier ways to add a Downtime page.
