### ISSUE TITLE
Spike - Improve parsing logging

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2626]
**Description:**
This was an out-of-scope addition to my review on #2548 -- we could improve our debugging/operational logging for significant workloads specifically around the bulk creates and parsing generally. Our current default logging level is DEBUG which maybe shouldn't be true in production but adding some dev-level debugging for future work seems prudent.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Create spec/recommendations for places needing logging improvements/additions
- [x] Increased visibility into system actions for info-level logging for prod
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Assess logging shortcomings for prod info-level
- [x] Assess useful debug-level logging for development and unit tests
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
- How can we better bound/define this requirement? It's super subjective/squishy.

**Comment by andrew-jameson** [comment]
todo: scenarios, user stories, recommended improvements

investigate rowschema.py

also prompt alex on friday morning meaning

**Comment by andrew-jameson** [comment]
Gave Eric a draft version of scenarios/recommendations. Will try to put something more formal in this ticket later today or monday.
