### ISSUE TITLE
Populate `DataFileSummary.case_aggregates` differently for each section

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2646]
**Description:**

According to the [UX HTML file](https://reitermb.github.io/HTML-Table-example/) different datafile submission sections have different aggregate data displayed in the table. 

Sections 01 and 02
![image](https://github.com/raft-tech/TANF-app/assets/28515874/4b202a52-d6bc-4294-b324-f9b801d96d85)

Sections 03 and 04
![image](https://github.com/raft-tech/TANF-app/assets/28515874/0bcce14c-4074-45ae-90d2-3490cdea0008)

To facilitate this, we need the ability to run a different aggregation function for different submission sections. #2612 [introduces `dfs.case_aggregates = case_aggregates_by_month(data_file)`](https://github.com/raft-tech/TANF-app/blob/d3bceb7da6f43c3c8b30e3be13b9c0412399795e/tdrs-backend/tdpservice/scheduling/parser_task.py#L27) which will need to be repurposed and replicated for the different sections.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] A `DataFileSummary` created for a submission has `case_aggregates` populated with the correct data for the section
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Modify `scheduling/parser_task.py` similar to the example implementation below, running a different aggregation function for different sections and populating `dfs.case_aggregates` appropriately
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Example implementation (in `parser_task.py`)

```python
def case_aggregates_by_section(data_file):
    if data_file.section.contains('Active Case Data'):
        return case_aggregates_by_month(data_file)
    elif data_file.section.contains('Closed Case Data'):
        return # some other function call
    # ... repeat for all sections

def parse(data_file_id)
    # ...
    dfs = DataFileSummary.objects.create(datafile=data_file, status=DataFileSummary.Status.PENDING)
    errors = parse_datafile(data_file)
    dfs.status = dfs.get_status(errors=errors)
    dfs.case_aggregates = case_aggregates_by_section(data_file)
    dfs.save()
```

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [_HTML copy_](https://reitermb.github.io/HTML-Table-example/)
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- 1, 2, 3, 4 all different or 1/2 and 3/4?
- Existing tickets for sections 2/3/4?
- Frontend impl?
