### ISSUE TITLE
As a user who submits data files, I want to know if my file upload has the incorrect file extension

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2664]
**Description:**
If a user uploads a file that has the incorrect extension, a 400 bad request error is returned upon clicking submit, but that is not a meaningful error message for the user. Additionally, the sys admin will not be able to see evidence of this in TDP

This ticket should deliver a more actionable error message to the user indicating that the file upload has the wrong extension.

**Acceptance Criteria:** 
- [ ] when a user uploads an a file with incorrect extension , an error message indicating such is displayed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ]TBD
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] inline message should read "The file uploaded does not contain correct extension. Please review this section and re-submit the data file."
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Notes:**

- similar ticket: #1916 
- _Note 2_
- _Note 3_

**Supporting Documentation:**

examples of files submitted that resulted in 400 bad request response and the resolution

_kansas_
![KS_incorrect](https://github.com/raft-tech/TANF-app/assets/63075587/e49e47c0-f244-4999-a233-bdb7491616e9)
![KS_correct](https://github.com/raft-tech/TANF-app/assets/63075587/cfcf2c47-4867-42d6-a4e3-630b88785633)

_west virginia_
![WVp1](https://github.com/raft-tech/TANF-app/assets/63075587/6478b8de-f592-4521-bb33-66587a6cbb08)
![wvp2](https://github.com/raft-tech/TANF-app/assets/63075587/144dd49f-2cb3-4e6c-8980-4ac1be961de9)

**Comment by Smithh-Co** [comment]
Note from backlog 8.22, investigate generating exclusion rules for a small subset of items we want to throw a human readable error for. Currently throwing 400 for anything not .txt and potentially looking for, "TS20" in the file name as well.
