### ISSUE TITLE
Cat 1 Errors Audit Fixes

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2673]
**Description:**

TDP should still parse data files when the header  or trailer records are too long. Its most concerning when the record is too short, since this indicates that there is information missing from the record.

![hetr_length](https://github.com/raft-tech/TANF-app/assets/63075587/6d8ed97c-1782-47fd-b40a-95bb4936c3e3)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] All trailer length issues should be ignored / omitted from error reports and parsing requirements 
- [ ] Cat 1 errors should be consistent with Desired Outputs in the [Cat 1 Validators section](https://hackmd.io/itv2dcDPRVulWm5mcaJtHQ?view#Cat-1-Validators) of the errors audit 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Remove error generation for trailer length errors
- [ ] Adjust error output for header and record length errors (for consistency with error audit)
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Error audit Hack.md ](https://hackmd.io/itv2dcDPRVulWm5mcaJtHQ?)

**Comment by ADPennington** [comment]
Confirmed during testing today that data files are still parsed if trailer issue. Still, the record-length related checks on the trailer record is not relevant.

**Comment by ADPennington** [comment]
for some reason this trailer produces weird results in the feedback report. we should drop trailer checks. 

`TRAILER010989503       `
![trailerissue](https://github.com/raft-tech/TANF-app/assets/63075587/c0e84162-22dc-4d29-803b-b14fe541ccc6)

**Comment by ADPennington** [comment]
@reitermb we need desired output for a new pre-parsing check. It will be addressed in this ticket.  @elipe17 added the check in #2834:

if the case_number is blank, the record will not be parsed:
- validator: `notempty()`
- current language: https://github.com/raft-tech/TANF-app/blob/e06fba6f7d4cc5433b0cb01a5f0a132521694bc2/tdrs-backend/tdpservice/parsers/validators.py#L296

**Comment by reitermb** [comment]
@reitermb

**Comment by ADPennington** [comment]
> @reitermb we need desired output for a new pre-parsing check. It will be addressed in this ticket. @elipe17 added the check in #2834:
> 
> if the case_number is blank, the record will not be parsed:
> 
> * validator: `notempty()`
> * current language: https://github.com/raft-tech/TANF-app/blob/e06fba6f7d4cc5433b0cb01a5f0a132521694bc2/tdrs-backend/tdpservice/parsers/validators.py#L296

@reitermb @elipe17 was this validator and language addressed in #2838? this is currently in QASP review.

**Comment by reitermb** [comment]
> > @reitermb we need desired output for a new pre-parsing check. It will be addressed in this ticket. @elipe17 added the check in #2834:
> > if the case_number is blank, the record will not be parsed:
> > 
> > * validator: `notempty()`
> > * current language: https://github.com/raft-tech/TANF-app/blob/e06fba6f7d4cc5433b0cb01a5f0a132521694bc2/tdrs-backend/tdpservice/parsers/validators.py#L296
> 
> @reitermb @elipe17 was this validator and language addressed in #2838? this is currently in QASP review.

I'm not seeing it as one of the changes currently in #2838. Just to make sure I'm understanding the context of this error, would it be served up in an instance of somebody giving us a case number like `12345  8910`? And read `12345  8910 contains blanks between positions 5 and 8`? 

Language thoughts are that if this is exclusive to case number we should call that out at the beginning `Case number "string" contains blanks...` and swap out `positions` for `characters`.

@ADPennington @elipe17

**Comment by ADPennington** [comment]
> > > @reitermb we need desired output for a new pre-parsing check. It will be addressed in this ticket. @elipe17 added the check in #2834:
> > > if the case_number is blank, the record will not be parsed:
> > > 
> > > * validator: `notempty()`
> > > * current language: https://github.com/raft-tech/TANF-app/blob/e06fba6f7d4cc5433b0cb01a5f0a132521694bc2/tdrs-backend/tdpservice/parsers/validators.py#L296
> > 
> > 
> > @reitermb @elipe17 was this validator and language addressed in #2838? this is currently in QASP review.
> 
> I'm not seeing it as one of the changes currently in #2838. Just to make sure I'm understanding the context of this error, would it be served up in an instance of somebody giving us a case number like `12345 8910`? And read `12345 8910 contains blanks between positions 5 and 8`?
> 
> Language thoughts are that if this is exclusive to case number we should call that out at the beginning `Case number "string" contains blanks...` and swap out `positions` for `characters`.
> 
> @ADPennington @elipe17

i believe #2838 is back in raft review pending an outcome on this. this validator is used in multiple places so not exclusive to CASE_NUMBER. we can discuss among the 3 of us on whether to address in current or later ticket @elipe17 @reitermb.

**Comment by ADPennington** [comment]
> > > > @reitermb we need desired output for a new pre-parsing check. It will be addressed in this ticket. @elipe17 added the check in #2834:
> > > > if the case_number is blank, the record will not be parsed:
> > > > 
> > > > * validator: `notempty()`
> > > > * current language: https://github.com/raft-tech/TANF-app/blob/e06fba6f7d4cc5433b0cb01a5f0a132521694bc2/tdrs-backend/tdpservice/parsers/validators.py#L296
> > > 
> > > 
> > > @reitermb @elipe17 was this validator and language addressed in #2838? this is currently in QASP review.
> > 
> > 
> > I'm not seeing it as one of the changes currently in #2838. Just to make sure I'm understanding the context of this error, would it be served up in an instance of somebody giving us a case number like `12345 8910`? And read `12345 8910 contains blanks between positions 5 and 8`?
> > Language thoughts are that if this is exclusive to case number we should call that out at the beginning `Case number "string" contains blanks...` and swap out `positions` for `characters`.
> > @ADPennington @elipe17
> 
> i believe #2838 is back in raft review pending an outcome on this. this validator is used in multiple places so not exclusive to CASE_NUMBER. we can discuss among the 3 of us on whether to address in current or later ticket @elipe17 @reitermb.

@reitermb @elipe17 what was decided here?

**Comment by elipe17** [comment]
> > > > > @reitermb we need desired output for a new pre-parsing check. It will be addressed in this ticket. @elipe17 added the check in #2834:
> > > > > if the case_number is blank, the record will not be parsed:
> > > > > 
> > > > > * validator: `notempty()`
> > > > > * current language: https://github.com/raft-tech/TANF-app/blob/e06fba6f7d4cc5433b0cb01a5f0a132521694bc2/tdrs-backend/tdpservice/parsers/validators.py#L296
> > > > 
> > > > 
> > > > @reitermb @elipe17 was this validator and language addressed in #2838? this is currently in QASP review.
> > > 
> > > 
> > > I'm not seeing it as one of the changes currently in #2838. Just to make sure I'm understanding the context of this error, would it be served up in an instance of somebody giving us a case number like `12345 8910`? And read `12345 8910 contains blanks between positions 5 and 8`?
> > > Language thoughts are that if this is exclusive to case number we should call that out at the beginning `Case number "string" contains blanks...` and swap out `positions` for `characters`.
> > > @ADPennington @elipe17
> > 
> > 
> > i believe #2838 is back in raft review pending an outcome on this. this validator is used in multiple places so not exclusive to CASE_NUMBER. we can discuss among the 3 of us on whether to address in current or later ticket @elipe17 @reitermb.
> 
> @reitermb @elipe17 what was decided here?

@ADPennington we added a specific validator for preparsing validation wrt case number. `caseNumberNotEmpty`. I need to update the language on the error to be consistent with what Miles suggested. I missed that suggestion.
