### ISSUE TITLE
Create a `search_indexes` base model

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2675]
**Description:**

There are a couple cases where we want to query for all the records created by the parser for a datafile, across all the possible model types. 
* `DataFileSummary`'s `get_status` - introducing a "Partially Accepted"/"Partially Accepted With Errors" status
* `case_aggregates_by_month` - counting cases created across model types
There may be further use-cases in the future (cat 4/5 validation).

To complete this issue:
* Utilize inheritance for `search_indexes` models; shared fields
   * id
   * datafile
   * RecordType
   * RPT_MONTH_YEAR
   * CASE_NUMBER
* Rework `DataFileSummary.get_status`
   * Pending = 0 records created, None errors
   * Rejected = 0 records created, >0 file-precheck errors
   * Partially Accepted = >0 records created, 0 file-precheck errors, >0 row-precheck errors
   * Accepted with Errors = >0 records created, 0 file/row-precheck errors, >0 field validation errors
   * Accepted = >0 records created, 0 file/row-precheck errors
* Rework `case_aggregates_by_month`
   * simplify `curr_case_numbers` query/set creation. shouldn't need the loop anymore

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] All `search_indexes` models inherit from a base model containing the subset of fields shared by all the models.
- [ ] `case_aggregates_by_month` is updated to utilize the `search_indexes` base model in its queries
- [ ] `DataFileSummary.get_status` is updated to utilize the number of rows created to determine the summary status
- [ ] ~~`DataFileSummary.get_status` adds a new "Partially Accepted"/"Partially Accepted with Errors" status~~
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create base model
- [ ] Create migration to preserve record data
- [ ] Refactor aggregations
- [ ] Identify other areas we wish to use the base model
- [ ] Test migration with large data set
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by lhuxraft** [comment]
Should do this ahead of Cat 5 validation? May no longer be useful if we move away from Elasticsearch/Kibana (if we move away, ticket needs a rewrite)

**Comment by lhuxraft** [comment]
Closing this, as we are sunsetting Kibana/ElasticSearch. May resurface with DAC in the future, but closing for now
