### ISSUE TITLE
TANF Section 2 validation clean-up

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2688]
**Description:**
After #2633 merges, some of the validation checks for TANF Section 2 data needs updates. These include space-filling for some non-required data elements

[workbook for TANF section 2](https://gorafttech.sharepoint.com/:f:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/Parsing/data/tanf/Section2?csf=1&web=1&e=dywxgb) updated. See column I in relevant worksheets for data elements that should allow for spaces

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] relevant T4 data elements allow for space-filling
- [ ] relevant T5 data elements allow for space-filling
- [ ] REC_SUB_HOUSING range is 1-2
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] update tanf section 2 (ssp and tribal section 2 have already been completed)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Other cleanups in section 2 that are now captured in other tickets_ 

- ~`DATE_OF_BIRTH` in the T4  record are stored and validated as integers instead of date (YYYYMMDD)~
    - captured by #2746
- ~`if (calculated) AGE >= 19, then item 19A == 1 or 2` not implemented~
    - dob calculation changed by #2746, drop this req
- ~`FIPS_CODE` not stored in the T4 record~
    - captured by #2796

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- do any updates need to be made to pre/post-parsing validators? initial assumption is: no

**Comment by ADPennington** [comment]
add #2712

**Comment by ADPennington** [comment]
@jtimpe this is ready for backlog on 3/5.

**Comment by robgendron** [comment]
1 point remaining.

**Comment by reitermb** [comment]
Walking on a small addition after conversation with @raftmsohani following error audit syncs with @ADPennington. 
Simplifies errors that read like `0 is not larger or equal to 1 and smaller or equal to 3` to make them easier to interpret when the range of allowable values is small. Simplified version to aim for results like `0 is not in range [1-3]` in these cases
