### ISSUE TITLE
[Error Audit] Category 2 error messages clean-up 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2693]
**Description**
Delivers Category 2 error language fixes 

**Acceptance Criteria**:
- [x] All Cat2 errors should include the `[Item #][Friendly Name]` pattern (see `run_field_validators` in row schema)
- [ ] All Cat 2 errors are consistent with desired outputs in the [HackMD table](https://tdp-project.gitbook.io/project-trackers-and-guides#cat-2-validators)
- [ ]  Misc cleanups are fixed:
   - [ ] `validateRace` error message typo fix Desired output: `f"{value} is not greater than or equal to 0 or smaller than or equal to 2.`

**Tasks**:
- [ ] Correct row schema to add Item/Friendly names to Cat2 errors
- [ ] Correct misc cleanup re: `validateRace`
- [ ] Correct other issues noted in Hack.md table which includes validators `oneOf, notOneOf, isInStringRange, isNumber`

**Supporting Documentation**:

- [Error Audit HackMD](https://tdp-project.gitbook.io/project-trackers-and-guides#cat-2-validators)

**Comment by robgendron** [comment]
@reitermb @andrew-jameson need more detail to implement - AC is specific, Hackmd is not. Let's build out more tasks and pull out what is needed to do the work from the hackmd (tables, etc.) and put it in the ticket (not hyperlinked).

**Comment by reitermb** [comment]
Removing the following AC for the moment, I believe they originally referred to errors that will be corrected by other work including #2688. Quoting here in case we need to refine into this/other tickets 

   - [ ] intHasLength
   - [ ] dateYearIsLargerThan
   - [ ] dateMonthIsValid
   - [ ] dateDayIsValid

**Comment by jtimpe** [comment]
> Item 37 (Education level) must be in range of values [01-16] or in set of values [98, 99] | Above issue of missing item number + missing ranges/sets/both of allowable values. We might have a little bit of a broader issue here with fields that are not required serving up errors saying they're required. If it's a space fill issue it should not produce an error indicating that it's a missing value.

education level is already optional so the cat3 validator is what's returning here, #2821 would cover this case
