### ISSUE TITLE
As tech lead, I need some space-filled values to be allowed in TANF Section 1 data files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2695]
### Description

Per the following public guidance, OFA must allow for space-filling for some data elements reported in TANF Section 1 files, where applicable:

> Each item needs to hold a certain number of spaces in the flat file. If your system does not automatically hold the spaces, see the file layout for the number of spaces (length) that need to be held. If an element is not applicable or no longer in use, enter the number of digits (zeros or blanks)

the [tanf section 1 validation workbook](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BF99CEA75-18CC-4494-9302-677CC92E3EF4%7D&file=TDP_Validation.xlsx&action=default&mobileredirect=true&cid=7776f046-c9be-4720-9367-46d58b9ac731)  has been updated with a new column on the Cat 2 worksheets for `T1`, `T2`, and `T3`  for each data element that should include spaces as valid in the possible range of values. example below:

![spacefill](https://github.com/raft-tech/TANF-app/assets/63075587/fda9a73d-a834-4a64-81bc-71a402166fcb)

### Acceptance Criteria

- [ ] relevant `T1` data elements with spaces as values are not flagged as cat 2 (out-of-range) errors
- [ ] relevant `T2` data elements with spaces as values are not flagged as cat 2 (out-of-range) errors
- [ ] relevant `T3` data elements with spaces as values are not flagged as cat 2 (out-of-range) errors
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks
- [ ] Update schema and validators for `T1`, `T2`, `T3` for relevant data elements as needed
- [ ] update other relevant code files
- [ ] Run Testing Checklist and confirm all tests pass

### Supporting documentation 

states that currently space-fill for some TANF Section 1 data elements

#### `T1` records
![county_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/61affd59-9c38-4665-82c3-da7bbc254d94)

#### `T2` records
![race_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/edf84dbb-0395-49b9-ba3c-33963e4503c8)
![mar_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/f38af14f-097c-4060-b6cc-8489b64c596b)
![tl_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/bfd81ba4-1ac3-449f-a521-a45f88d43501)
![unsub_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/c9920670-df2f-4667-9423-180f8f179668)
![ojt_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/6ac5782c-1633-473c-ad55-b27a55be380a)
![com_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/c7c0053b-1321-437f-b102-2a5d52a75f44)
![js_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/3261fd85-075b-427a-86ff-3e83d8d32d4c)
![sa_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/f90fc8d1-d8f1-4a97-a7f8-0b0f0005ff0f)
![deem_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/b37252bf-b7dd-45b7-8b9e-c15e37a70cb3)

#### `T3` records

![t3_spaces_bystate](https://github.com/raft-tech/TANF-app/assets/63075587/65bbcde8-692c-4353-9c08-21fef3a8432f)

_Originally posted by @ADPennington in https://github.com/raft-tech/TANF-app/issues/2681#issuecomment-1702820720_

**Comment by ADPennington** [comment]
@Smithh-Co ticket updated. please feel free to update the link to the workbook in the summary, as needed.
