### ISSUE TITLE
Refine labels and text for Data Files search controls

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2699]
### Background ###
This ticket addresses refinements to the labels and accompanying text for the search controls on the Data Files page. These changes will improve the clarity of required fields and enhance the user experience for the form.

### Acceptance Criteria ###
- [x] Add the following paragraph text under the Data Files heading and before the first form input:
- [x] "Fields marked with an asterisk (*) are required."
- [x] Add required asterisks to all fields, including the STT field for OFA users, which should already have one.
- [x] Change the label for the Quarter dropdown to: "Fiscal Quarter*".
- [x] Ensure that existing form validation rules remain unchanged:
- [x] Only show relevant fields to each user group.
- [x] Only count visible errors in the error summary (fields not visible to the user should not be counted as errors).
- [x] Run the Testing Checklist to confirm all tests pass.
- [x] Update the README if necessary, to reflect changes to the form or labels.

### Tasks ###
- [x] Add paragraph text referencing asterisks == required fields
- [x] Add asterisks to all fields missing them
- [x] Change quarter label
- [x] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
![image](https://github.com/raft-tech/TANF-app/assets/28515874/e4a0943b-b596-454a-a1e6-2d113be73160)
Design spec showing the view an OFA user would have including all available fields

**Comment by robgendron** [comment]
@reitermb is this refined? Please label if so.
