### ISSUE TITLE
(Internal) Determine where to post research artifacts and deliverables

### ISSUE THREAD

**Issue by matthewjdoty** [raft-tech/TANF-app#270]
**Description:**
Per request from @cmajel  in a discussion within issue #113, this issue is being created to "determine where research should live in the future" as well as discuss "Raft wiki access"

**Questions:**
- What privacy considerations need to be made?

**AC:**
- [x] Guidance/Instructions are documented 
- [ ] Research issue template is updated if needed

**Tasks:**
- [x] Conversation with Design/Research team, Christine, and Lauren
- [x] Document Guidance/instructions 
- [x] Update research issue template if needed

**Deliverables:**
Design and Research Single Source of Truth Doc: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc=%7B71F4E5D9-431A-4E47-A054-4B8DAE6CEBC5%7D&file=Single%20Source%20of%20Truth%20(Design%20and%20Research).docx&action=default&mobileredirect=true))

**Comment by matthewjdoty** [comment]
@shubhi-raft I've added comments and made very minor(tracked) changes. please feel free to review

**Comment by shubhi-raft** [comment]
thanks @matthewjdoty. added more notes, moving this back to in progress.

**Comment by shubhi-raft** [comment]
Raft does not have wiki write access and hence will be using PR to submit updates and changes to documentation that will live on Code<> doc.

**Comment by lfrohlich** [comment]
This was completed in Sprint 5 and followed up with #321
