### ISSUE TITLE
FETCH_STTS Infinite Request

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2701]
**Description:**
It was recently discovered that under certain conditions the FETCH_STTS request will happen infinitely many times (or until your browser crashes.). This happens in the instance that the backend has not had `manage.py populate_stts` executed. The frontend will continuously execute the request even though it is not getting anything in the response. This should not be the case, we want the frontend to execute this request a few times and then give up and throw an error indicating it could not fetch the STTs.

![Screenshot 2023-09-07 at 1 38 58 PM](https://github.com/raft-tech/TANF-app/assets/125676261/beff7e19-db70-4890-a7cd-44c762972937)

**Acceptance Criteria:** 

- [ ] FETCH_STTS should be executed a finite amount of times no matter the response.
- [ ] If FETCH_STTS continuously has no response, an error indicating to the user the issue should be thrown.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update request logic to execute FETCH_STTS a finite amount of times
- [ ] Implement an appropriate error in the instance the STTs cannot be fetched
- [ ] Update tests to handle these new branches
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
