### ISSUE TITLE
SSP Active Data (01) - Validation

### ISSUE THREAD

**Issue by Smithh-Co** [raft-tech/TANF-app#2709]
**Description:**
Validation for SSP Active Data (01) - T1 to T3 record types

**Acceptance Criteria:** 
- [ ] Data File parsing logic is in place such that data file submission can be completed by user and parsed by system for full submission once errors are resolved.
- [ ] Data Errors tell user specifically where in the file they occur, and therefore what exactly needs to be fixed in order for the submission to be complete
- [ ] TDP gives the user all data errors for a submission in a way they can easily save or export so they can take the issues back to their case management software and fix the issues then recreate an export for resubmission to TDP.
- [ ] Data Errors must be issued in human readable plain language so that an english speaker can easily understand what is needed. 

**Tasks:**
- [ ] T1 -T3 Validation
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [_SSP_Validation_Workbook_](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BD750ECCD-B320-4E7A-B7F6-C9354B84F61B%7D&file=TDP_Validation_SSP_Section1.xlsx&action=default&mobileredirect=true)
- [_Parsing_Notebook](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev%2Fdev%2FParsing%2Fhtml&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46&noAuthRedirect=1)
- [_SSP_Instructions_Doc_](https://gorafttech.sharepoint.com/:w:/r/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc=%7BFD51E66D-6DDA-47AA-A970-29006EEC07F3%7D&file=TANF-SSP%20data%20instructions_clean.docx&action=default&mobileredirect=true)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Space-fill workflow (2695) implications?_
- _Open Question 2_

**Comment by ADPennington** [comment]
@jtimpe @Smithh-Co cat 3 validators added to workbook
