### ISSUE TITLE
As a developer, I want to move migration commands in the pipeline to circleci

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2729]
**Description:**
Currently the _migrate_ command is applied in _gunicorn_start.sh_ script which is causing larger migrations fail due to disk space limitations in cloud.gov app instances.
This ticket should move the migrate command upstream to circleci. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] New migrations apply ahead of deploying app
- [ ] Confirm the above AC using large dataset in the DB
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Confirm the target app runs and circleci can connect to the app
- [ ] Connect to target DB from circleci
- [ ] Run migrations from circleci before deploying the app
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Research HackMD](https://hackmd.io/xCtZvIUIQK6Tuywl7771qQ?both)
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Circle CI may require a paid account for higher resource requests, currently on free tier
- _Open Question 2_

**Comment by jtimpe** [comment]
related to #2591
