### ISSUE TITLE
As an STT, I need to know if there are issues with the DOBs reported in my data files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2746]
**Description:**
As noted #2681, we are currently storing DOB as numeric in TDP's db and not as a date (i.e. `YYYYMMDD`). dev team noted that resolving this could be expensive (including introducing a pretty large migration). 

As an alternative, the DIGIT team proposes keeping the DOB stored in the numeric format but validate as follows:

- DOB should be exactly 8 digits (e.g. 20231108)
- the values in the YYYY position should be > 1900 
- the values in the MM position should be between 01 and 12
- the values in the DD position should be between 01 and  31  

This would catch most of the issues the data team detects but would miss scenarios where the full date is impossible (e.g. Feb 30th). The data team will handle those issues on a case by case basis. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] DOB should be exactly 8 digits (e.g. 20231108)
- [ ] the values in the YYYY position should be > 1900 
- [ ] the values in the MM position should be between 01 and 12
- [ ] the values in the DD position should be between 01 and  31  
- [ ] implement DOB validator in the schemas listed below
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- This applies to:
  -  T2 and T3 records in TANF and Tribal TANF section 1 files
  -  T5 records in  TANF and Tribal TANF section 2 files
  -  M2 and M3 records records in  SSP section 1 files
  -  M5 records in  SSP section 2 files

**Supporting Documentation:**

- DOBs reported in error for FY23 as of Oct 2023
![DOB_issues2](https://github.com/raft-tech/TANF-app/assets/63075587/f2b2ef2e-aa9c-487e-88a2-95e23eacb0cf)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
@jtimpe @reitermb lets discuss at next backlog.

**Comment by ADPennington** [comment]
BTW @jtimpe @elipe17 was correct: DOB validator is incorrect. 


![DOBerror](https://github.com/raft-tech/TANF-app/assets/63075587/685353ac-ac03-40a8-a2dc-dff8f1ad9a34)
