### ISSUE TITLE
As tech lead, I need validation checks to be consistent with FTANF validation checks. 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2749]
**Description:**
OFA team recently learned that some of our validation checks are not consistent with FTANF executables, which some STTs use to prepare their files. Until we can replace FTANF functionality, we need to ensure that STTs that still use the tool can prepare their files and also follow the updated coding instructions. 

---

**TANF Section 1**

_T1:Cat2_

- FTANF is dropping any leading zeros from item # 2 `COUNTY_FIPS_CODE`, so TDP needs to zero-fill so that the zeros are stored in the db and cat 2 errors arent raised for this. 

_T3:Cat2_
- 0 is out-of-range for item # 76_1 and # 76_2 (CITIZENSHIP_STATUS)

---

**TANF Section 2**

_T4:Cat2_
- FTANF is dropping any leading zeros from item # 2 `COUNTY_FIPS_CODE`, so TDP needs to zero-fill so that the zeros are stored in the db and cat 2 errors arent raised for this. 

---

**SSP Section 1**

_M1:Cat2_
- FTANF is dropping any leading zeros from item # 2 `COUNTY_FIPS_CODE`, so TDP needs to zero-fill so that the zeros are stored in the db and cat 2 errors arent raised for this. 

_M2:Cat2_
- 00 is out-of-range for item # 37 (`EDUCATION_LEVEL`)
- 0 is out-of-range for item # 38 (`CITIZENSHIP_STATUS`)
- 0 is out-of-range for item # 39 (`COOPERATION_CHILD_SUPPORT`)

_M3:Cat2_
- 00 is out-of-range for item # 68_1 and 68_2 (`EDUCATION_LEVEL`)
- 0 is out-of-range for item # 69_1 and 69_2 (`CITIZENSHIP_STATUS`)
---

**SSP Section 2**

_M4:Cat2_
- FTANF is dropping any leading zeros from item # 2 `COUNTY_FIPS_CODE`, so TDP needs to zero-fill so that the zeros are stored in the db and cat 2 errors arent raised for this. 

_M5:Cat2_
- 00 is out-of-range for item # 23 (`EDUCATION_LEVEL`)
- 0 is out-of-range for item # 24 (`CITIZENSHIP_STATUS`)
---

**Tribal TANF Section 1**

_T1:Cat2_
- FTANF is dropping any leading zeros from item # 2 `COUNTY_FIPS_CODE`, so TDP needs to zero-fill so that the zeros are stored in the db and cat 2 errors arent raised for this. Additionally, tribes are populating this field with their `STT_CODE`, which is okay. So we should accept any 3-digit value

_T2:Cat2_
- ADD_WORK_ACTIVITIES (item # 61) should also zero-fill. 
----

**Tribal TANF Section 2**
_T4:Cat2_
- (see note) FTANF is dropping any leading zeros from item # 2 `COUNTY_FIPS_CODE`, so TDP needs to zero-fill so that the zeros are stored in the db and cat 2 errors arent raised for this. Additionally, tribes are populating this field with their `STT_CODE`, which is okay. So we should accept any 3-digit value

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] TDP validation rules are consistent with FTANF, as per abovementioned fixes
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] add tests for values that have partial space fill (e.g., `' 12'` vs `'012'`)
    - [ ] `isNumber`, `isAlphaNumeric`, etc.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- this affects TANF, SSP, and potentially Tribal TANF Sections 1 and 2

- python's `String.isnumeric()` returns `False` for a value of `' 12'` (vs `'012'` returning `True`)
    - https://www.w3schools.com/python/ref_string_isnumeric.asp
    - > "-1" and "1.5" are NOT considered numeric values, because all the characters in the string must be numeric

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [coding instructions, which are consistent with FTANF](https://www.acf.hhs.gov/sites/default/files/documents/ofa/ACF199_209%20TANF_SSP%20data%20report%20instructions%20-%20valid%20thru%202026-10_compliant_FINAL.pdf)
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
I will refine this ticket as soon as I  have a comprehensive list of changes.

**Comment by ADPennington** [comment]
@jtimpe this is ready for refinement on 3/5.

**Comment by robgendron** [comment]
2 points remaining.

**Comment by robgendron** [comment]
1 point remaining.
