### ISSUE TITLE
as an STT user, I need the resource cards updated with the latest coding instructions

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2751]
**Description:**

New coding instructions for TANF and SSP (_not Tribal TANF_) are [here](https://www.acf.hhs.gov/ofa/policy-guidance/tanf-acf-pi-2023-04). we need to update the resource card(s) in TDP that link to the old version. 

![resource_change](https://github.com/raft-tech/TANF-app/assets/63075587/0bf77dc6-637a-46c3-9d56-964386e0f791)

**Priority**: 
Link to PI here: https://www.acf.hhs.gov/ofa/policy-guidance/acf-ofa-pi-23-04 
pdf version  here: https://www.acf.hhs.gov/sites/default/files/documents/ofa/ACF199_209%20TANF_SSP%20data%20report%20instructions%20-%20valid%20thru%202026-10_compliant_FINAL.pdf

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Resource cards reflect the latest coding instructions for TANF and SSP. 
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by jtimpe** [comment]
depends on #2749

**Comment by ADPennington** [comment]
> depends on #2749

im not sure this depends on #2749 anymore? @lfrohlich any reason we shouldnt move forward with this ticket? cc: @jtimpe

**Comment by lfrohlich** [comment]
No reason to wait -- would be good to update this ASAP but I think we should link to PI: https://www.acf.hhs.gov/ofa/policy-guidance/acf-ofa-pi-23-04
