### ISSUE TITLE
As tech lead, i need sections 3 and 4 files rejected if the T6, T7, M6, or M7 records cannot be parsed. 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2754]
**Description:**

In #2731 I noticed that the M7 record that did not have the correct length was not parsed but the status was "partially accepted with errors". see [here](https://github.com/raft-tech/TANF-app/pull/2731/files#r1400678633). 

Eric explained:

> In the event that the file had more than one record, those records could be correct/have no preparse errors and would parse correctly/be added to the DB. That is why the status is partially accepted. 

This makes more sense for the other sections that have multiple record types (excluding header, trailer records), but all of the parse-able data needed for sections 3 and 4 are all in the T6/T7 or M6/M7 record. So if one of these records cant be parsed and added to db, the status should be rejected. 

This should expand to section 1 and 2 files as well - if no records are successfully processed, the summary status should be Rejected.
- look at `DataFileSummary.get_status` to add in a row count check

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] If the T7 record cannot be parsed, the status of the file is rejected. 
- [ ]  If the M7 record cannot be parsed, the status of the file is rejected. 
- [ ] If the M6 record cannot be parsed, the status of the file is rejected. 
- [ ]  If the T6 record cannot be parsed, the status of the file is rejected. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Relevant to Sections 3 and 4 TANF, SSP, Tribal TANF files. 
- may also be relevant to Sections 1 and 4 files that are not "complete" see comment [here](https://github.com/raft-tech/TANF-app/issues/2754#issuecomment-1946376987)
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
note for `dev` team: this issue was also detected in Section 1 and 2 when testing in #2834  with a file that had only 1 non-header/trailer record. OFA does not expect one record in section 1 and 2 files, and we think this would be caught once #2818 is implemented (because it would be evidence that the STT is submitting partial data). cc: @andrew-jameson @elipe17 @jtimpe @raftmsohani
