### ISSUE TITLE
Generate preparser errors when multi-record rows are the wrong length or are missing space-filled second records

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#2757]
**Description:**
#2748 fixes an issue where mis-formatted multi-records would throw an uncaught exception, stopping parsing for a file and throwing out any uncommitted records, when the second (or `n`th) record was non-existent or shorter than the range given to the `notEmpty` preparsing validator. Because this mis-formatting is technically a violation of the coding instructions, we'd like to throw a preparsing error when the record is not properly filled or space-filled.

one or both of these possible solutions
* modification of the `parse_and_validate` method of `SchemaManager` to add some bounds checking (consider making a change to `Field`'s `parse_value` as well)
* change to existing `isEmpty`/`notEmpty` preparsing validator approach to ensure edge cases are reported

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- Mis-formatted `T3`, `M3` and Tribal `T3` records are reported with preparsing validator errors
    * [x] Records where space-fill is not included
    * [x] Records where the second/`n`th record length is less than given range
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
sharing for visibility:

----
----

**TANF Section 1, T3 Record Type**

max Tribal TANF T3 record length == 156

Parse child 1 positions (1-60) if:
* record length >=60 
* positions 1-60 not empty

Parse child 2 positions (61-101) if:
* record length >=101
* positions 61-101 not all space or all zeros 


| Scenario | Scenario Description                           | Parse Child 1? | Parse Child 2? | Error message related to record length? |
| -------- | ---------------------------------------------- | -------------- | -------------- | --------------------------------------- |
| 1        | 1 child, with space-filling from 61 to 156     | Yes            | No             | n/a                                     |
| 2        | 2 children, with space-filling from 101 to 156 | Yes            | Yes            | n/a                                     |
| 3        | 1 child, with zero-filling from 61 to 156      | Yes            | No             | n/a                                     |
| 4        | 2 children, with zero-filling from 101 to 156  | Yes            | Yes            | n/a                                     |
| 5        | 1 child, record length == 65                      | Yes            | No             | 2nd child record truncated              |
| 6        | 2 children, record length== 98                   | Yes            | No             | 2nd child record truncated              |
| 7        | 1 child, record length==55                      | No             | No             | 1st child record truncated              |
| 8         |    1 child, record length== 60             |     Yes           |    No            |                       n/a                  |
| 9         |    2 children, record length== 101             |     Yes           |    Yes            |                       n/a                  |


---

**Tribal TANF Section 1, T3 Record Type**

max Tribal TANF T3 record length == 122

Parse child 1 positions (1-60) if:
* record length >=60 
* positions 1-60 not empty

Parse child 2 positions (61-101) if:
* record length >=101
* positions 61-101 not all space or all zeros 

| Scenario | Scenario Description                           | Parse Child 1? | Parse Child 2? | Error message related to record length? |
| -------- | ---------------------------------------------- | -------------- | -------------- | --------------------------------------- |
| 1        | 1 child, with space-filling from 61 to 122     | Yes            | No             | n/a                                     |
| 2        | 2 children, with space-filling from 101 to 122 | Yes            | Yes            | n/a                                     |
| 3        | 1 child, with zero-filling from 61 to 122      | Yes            | No             | n/a                                     |
| 4        | 2 children, with zero-filling from 101 to 122  | Yes            | Yes            | n/a                                     |
| 5        | 1 child, record length == 65                   | Yes            | No             | 2nd child record truncated              |
| 6        | 2 children, record length== 98                 | Yes            | No             | 2nd child record truncated              |
| 7        | 1 child, record length==55                     | No             | No             | 1st child record truncated              |
| 8        |    1 child, record length== 60                 |     Yes        | No             |      n/a                                |
| 9        |    2 children, record length== 101             |     Yes        | Yes            |                       n/a               |

---

**SSP Section 1, M3 Record Type**

max SSP M3 record length == 150

Parse child 1 positions (1-60) if:
* record length >=60 
* positions 1-60 not empty

Parse child 2 positions (61-101) if:
* record length >=101
* positions 61-101 not all space or all zeros 

| Scenario | Scenario Description                           | Parse Child 1? | Parse Child 2? | Error message related to record length? |
| -------- | ---------------------------------------------- | -------------- | -------------- | --------------------------------------- |
| 1        | 1 child, with space-filling from 61 to 150     | Yes            | No             | n/a                                     |
| 2        | 2 children, with space-filling from 101 to 150 | Yes            | Yes            | n/a                                     |
| 3        | 1 child, with zero-filling from 61 to 150      | Yes            | No             | n/a                                     |
| 4        | 2 children, with zero-filling from 101 to 150  | Yes            | Yes            | n/a                                     |
| 5        | 1 child, record length == 65                   | Yes            | No             | 2nd child record truncated              |
| 6        | 2 children, record length== 98                 | Yes            | No             | 2nd child record truncated              |
| 7        | 1 child, record length==55                     | No             | No             | 1st child record truncated              |
| 8        |    1 child, record length== 60                 |     Yes        | No             |      n/a                                |
| 9        |    2 children, record length== 101             |     Yes        | Yes            |                       n/a               |

**Comment by reitermb** [comment]
Couple of unit tests remaining, spinoff ticket coming up. ~1 pt remaining before raft review

**Comment by ADPennington** [comment]
@raftmsohani I added tribal and ssp tables ⬆️

**Comment by raftmsohani** [comment]
> @raftmsohani I added tribal and ssp tables ⬆️

Thanks Alex!
