### ISSUE TITLE
Update TDP Homepage with Related Resource Content

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#276]
**Description:**

Delivers Figma spec for the resources we'll link to on the (unauthenticated) TDP homepage in V2. 

**Related User Stories:**

- As a user I want to access the [knowledge center](https://tdp-project-updates.app.cloud.gov/knowledge-center/)
- As a user I want to access transmission file[ layouts and edits ](https://www.acf.hhs.gov/ofa/policy-guidance/final-tanf-ssp-moe-data-reporting-system-transmission-files-layouts-and-edits)for TANF & SSP
- As a user I want to access [Tribal TANF Data Coding instructions](https://www.acf.hhs.gov/ofa/policy-guidance/tribal-tanf-data-coding-instructions)
- As a user I want to access [ACF-199/ACF-209 instructions](https://www.acf.hhs.gov/sites/default/files/documents/ofa/tanf_data_reports_tan_ssp_instructions_definitions.pdf)

**AC:**

- [x] Documentation work for the following has occurred:
   - [ ] Relevant User stories
   - [ ] Updating living Figma documents
- [x] Dev/Design adhoc sync has occurred; resulting in dev tickets created - book with Andrew
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Update unauthenticated homepage Figma spec to show actual resources

**Supporting Documentation:**

- [Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=7001%3A49625)

**Comment by amilash** [comment]
@dk-ui @lfrohlich Do we want to do this work? If so when, before we release to the public- or before we release to the early tribal release (v2)?

**Comment by reitermb** [comment]
Noting this is likely high potential for Onboarding research/design focus

**Comment by valcollignon** [comment]
@reitermb @sreedevip to further refine this ticket as part of work on #1653.

**Comment by reitermb** [comment]
> @reitermb is this the right figma link? it takes me to SiteMap

Whoops—sorry! That was the wrong one, it should be fixed now (and points here: https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=7001%3A49625)

**Comment by lfrohlich** [comment]
Made some minor edits to the text. Otherwise, looks good to me! @reitermb will you be adding the knowledge center URL before handing off to dev?

**Comment by lfrohlich** [comment]
@reitermb changes look good!
