### ISSUE TITLE
Update `validateSSN` validator to allow for all  0s,1s,...,9s as valid possible values except in cat3 scenarios. 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2771]
**Description:**

OFA's coding instructions indicate the following for STTs  (this instruction is consistent for TANF, SSP, and Tribal TANF for adult and child records):

> Social Security Number: Enter the nine-digit Social Security Number (SSN) for the adult. If the family affiliation code is 1 or 2, the state must provide the SSN, unless family affiliation is 2 with no SSN due to immigration status. If the family affiliation code is not 1 or 2, enter 999999999. 

This is describing the conditions for a cat 3 error (inconsistency between related data elements in the same record) which has already been implemented, but based on review of error reports for recently submitted data files in prod, TDP is also flagging SSN values like this as cat 2 (out of range) errors. 

all 0s,1s,...,9s are possible values for SSN. TDP should only raise cat 3 errors related to SSN. 

Priority: Parity 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] cat 2 error is not raised when SSN == all 0s, 1s, ..., 9s in TANF Sections 1 and  2
- [ ] cat 2 error is not raised when SSN == all 0s, 1s, ..., 9s in SSP Sections 1 and  2
- [ ] cat 2 error is not raised when SSN == all 0s, 1s, ..., 9s in Tribal TANF Sections 1 and  2
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
