### ISSUE TITLE
As an authenticated user who has been notified of an inactive session, I want to end or extend the session. 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#278]
**Description:**
After an authenticated user is served an inactive notification for ending or extending their session, a user can take an action based on the options. This issue will deliver the session to be extended or ended based on user's selection. The session will automatically timeout (end) after 10 mins after the user is served notification to take an action. 

**Acceptance Criteria:** 

- [x] User will be able to log out using this interaction (end session)
- [x] Direct `Extend` button to `/v1/auth_check` endpoint
   - [x] Close alert box
- [x] Direct `Logout` button to `/v1/logout` endpoint
   - [x] Redirect to splash page with successful logout
- [x] User will be able to extend the session using this interaction
- [x] Session will automatically timeout at a specified length of time after 3 min notification
- [x] Testing Checklist has been run and all tests pass

**Tasks:**

_Frontend_

- [ ] Modal pops up after 20 minutes and logs out after 3 more minutes of inactivity
   - [ ] End session on frontend and logout through backend
- [ ] Run Testing Checklist and confirm all tests pass

Points: Based on spike #282

Points: 5

**Notes:**
- Notification is addressed by #197 
- Note: only to be pulled for backend. 

**Open Questions:**
- Is 10 mins sufficient? 10 mins was used as a baseline based on USAJOB notification. 
- Which page does the user see after being automatically signed out/session has timed out?

**Comment by lfrohlich** [comment]
AC-02(05)	ACCOUNT MANAGEMENT | INACTIVITY LOGOUT	"The organization requires that users log out when [Assignment: organization-defined time-period of expected inactivity or description of when to log out].

AC-2 (5) Additional FedRAMP Requirements and Guidance:
Guidance: Should use a shorter timeframe than AC-12
"

**Comment by lfrohlich** [comment]
This was merged 11/25
