### ISSUE TITLE
As a developer, I want to have documentation on django migration best practices

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2781]
**Description:**
After performing a post-mortem on production database discrepancies that happened during sprint 80, one action item is to develop migration best practices documentation for the project that the team can use during code development and code review.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Develop best practices for naming migrations
- [ ] Develop best practices for defining migrations for new models/fields 
- [ ] Develop best practices for defining migrations for changing/altering existing models/fields
- [ ] Clear understanding of how to test the new migrations in develop/staging before deployment

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Database failure post-mortem](https://hackmd.io/-dG5uQfkSNuRDKp92VBlbg)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
