### ISSUE TITLE
Kibana Deployment

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2790]
**Description:**
- Update manifests to support deploying Kibana via  docker
   - buildpacks do not support cfos4

**Acceptance Criteria:** 

- [ ]   Kibana deploys to dev environment
- [ ]  Routes between Kibana and Elastic are configured
- [ ]  Kibana can connect to Elastic
- [ ]  User can navigate to Kibana from frontend
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update backend app manifest to deploy Kibana as a docker container
  - [ ] Parse hostname, username, and password from VCAP env vars and feed to container
  - [ ] xpack should be disabled
- [ ] Verify Kibana and Elastic are connected and communicating securely 
- [ ] Create necessary routes for the frontend and backend to talk to Kibana and redirect to Kibana
- [ ] Verify only HHS AMS authenticated admin users can access Kibana
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
