### ISSUE TITLE
update `dateYearIsLargerThan()` validator logic for `RPT_MONTH_YEAR` 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2793]
**Description**

We need a different validator for `YYYY` in the `RPT_MONTH_YEAR` field. We currently use this:

https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/parsers/validators.py#L371L376

below is an edge case:

records with `RPT_MONTH_YEAR` == `202 00` raises the following error message: `reporting month year is required but a value was not provided` and it still gets stored in the db. Couple of issues with this: 

- OFA ultimately cant do anything with these records, so these shouldnt be parsed because we cant infer the reporting period.
- the error message is unclear. a value for `RPT_MONTH_YEAR` was provided, but it is invalid (i.e. does not follow the YYYYMM format)

**Acceptance Criteria**
- [ ] records that require a `RPT_MONTH_YEAR` but do not have a valid value are not parsed. 
- [ ] error message associated with this validator is clear/user-friendly. 

**Tasks**
- [ ] Implement `preparsing_validator` with a clear error message
- [ ] Ensure the line is not parsed (no records created) and a cat 1 `ParserError` is created 
- [ ] Ensure the case aggregates counts reflect the new `row_precheck_error`

**Notes**
- relevant to T1, T2, T3, T4, T5,M1,..., M5 for TANF, SSP, and Tribal TANF
- possible approach is to implement a new `preparsing_validator` so the row is not parsed when an invalid `RPT_MONTH_YEAR` is encountered

**Supporting Documentation**

**Comment by elipe17** [comment]
@reitermb could you provide feedback on the cat1 error message I have written to satisfy the above requirements?
`The value: 202 10, does not follow the YYYYMM format for reporting month and year.`

**Comment by reitermb** [comment]
> @reitermb could you provide feedback on the cat1 error message I have written to satisfy the above requirements? `The value: 202 10, does not follow the YYYYMM format for reporting month and year.`

I like this! Only feedback would be switching around the friendly name there at the end to match the [instructions](https://www.acf.hhs.gov/sites/default/files/documents/ofa/ACF199_209%20TANF_SSP%20data%20report%20instructions%20-%20valid%20thru%202026-10_compliant_FINAL.pdf). 

`The value: 202 10, does not follow the YYYYMM format for Reporting Year and Month.`

More for my own awareness rather than a tweak request, do we have an easy way currently to pull in Item Number / Friendly Name stuff into this error? e.g. "Item 4 (Reporting Year and Month)" / Item 3 if SSP

**Comment by elipe17** [comment]
> > @reitermb could you provide feedback on the cat1 error message I have written to satisfy the above requirements? `The value: 202 10, does not follow the YYYYMM format for reporting month and year.`
> 
> I like this! Only feedback would be switching around the friendly name there at the end to match the [instructions](https://www.acf.hhs.gov/sites/default/files/documents/ofa/ACF199_209%20TANF_SSP%20data%20report%20instructions%20-%20valid%20thru%202026-10_compliant_FINAL.pdf).
> 
> `The value: 202 10, does not follow the YYYYMM format for Reporting Year and Month.`
> 
> More for my own awareness rather than a tweak request, do we have an easy way currently to pull in Item Number / Friendly Name stuff into this error? e.g. "Item 4 (Reporting Year and Month)" / Item 3 if SSP

@reitermb thank you for the feedback on the error message! With respect to your other question, there is a way to get that information into the error message. But it is not very easy because it will require some decently large design changes, along with a slew of updates to the tests. That change will definitely need to stay scoped to the tickets that came out of the errors audit HackMD
