### ISSUE TITLE
Make `CASE_NUMBER` field validators accept spaces and special characters

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2794]
**Description**

the T1 record below is an example of a real record from an STT. the `CASE_NUMBER` in this record has trailing spaces, and therefore results in error messages that indicate the following:

```shell
#T1 record
T120240723456623   00133200101110413110989300000000    0638055      000    000000000000000000213122122    00002229012                                       

# error message
23456623    is not alphanumeric.
```

We are using `isalnum()` to validate this field, which doesnt consider spaces or special characters in the case number, both of which are possibilities. `CASE_NUMBER` can be anything except all spaces. Some examples are below:

```
99999999999
999AB 99999
999AB$99999
999ABC99999
999ABC         
        99C
```

_Originally posted by @ADPennington in https://github.com/raft-tech/TANF-app/issues/2681#issuecomment-1852328435_
            
**Acceptance Criteria:**

 - [ ] `CASE_NUMBER` validator is updated to capture all possible variations and error messages aren't raised 
 - [ ] Testing Checklist has been run and all tests pass
 - [ ]  README is updated, if necessary

**Tasks:**
- [ ] update validator for case number 
- [ ] test validation for case number

**Notes:**
- relevant to TANF, Tribal TANF, and SSP 
- possible approach is to utilize the `value_is_empty` helper (in `parsers/validators.py`) - may require writing a new wrapper function as `notEmpty` is set up to take a start/end index
