### ISSUE TITLE
[Knowledge Center a11y] The purpose of a link must be descriptive

### ISSUE THREAD

**Issue by mitika-lj** [raft-tech/TANF-app#2797]
**Description:**
_The purpose of a link must be described by its link text alone, or by the link text together with preceding page context._

**Acceptance Criteria:** 
_Users understand the purpose of each link so they can decide whether they want to follow the link.WCAG 2.4.4 Level A_

- [ ] Accessible name should describe the purpose of the link in more clearer way
- [ ] Rephrasing content - so links are more descriptive
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] <a href="create-new-login.html" class= "usa-button">View Guide</a>  ---> < a href="/" aria-label="Create new login View Guide" > Create new Log in View Guide < /a>
- [ ] <a href="existing-login.html" class=" usa-button">View Guide</a> ---> < a href="/" aria-label="Existing login View Guide" > Existing Log in View Guide < /a>
- [ ] <a href="existing-login.html" >link</a> ---> a href="/" aria-label="Using an existing Log in" > Using an Existing Log in < /a>
- [ ] <a href="create-new-login.html" >create</a> ---> a href="/" aria-label="Create a new Log in" > Create a new Log In < /a>
- [ ] <a href="uploading-data.html" >submitted</a> ---> a href="/" aria-label="Submitting Data to TDP Guide " > Submitting Data to TDP Guide < /a>
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- The unique purpose of each link is made clear by adding the name of the Knowledge Center page to the link text.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- (https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)

**Comment by robgendron** [comment]
Deemed closed by Alex.
