### ISSUE TITLE
As a user, I want TDP site to be customized so I know it is an ACF site [remove trussworks]

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#280]
**Description:**
Per #274 , trussworks will be removed. This issue will deliver removal of trussworks and update any other components as necessary.

**NOTES**
- After meeting with Laura, Christine, and Miles we decided that we need to talk to Lauren about creating an issue for setting up the color palette and pulling it into the next sprint. The amount of work that it will take is more than is feasible for adding to this ticket.
- If Lauren is okay with doing the color palette as another issue then this PR is not blocked. If she wants the color palette to be included in this PR and is not okay with leaving it as is then this will be blocked.
- The disabled `Request Access` button is throwing an accessibility warning. The functionality to re-enable the button will be worked on with form validation.

**Acceptance Criteria:** 
- [ ] trussworks/reactuswds framework is removed
- [x] Color palette is added in code and @reitermb signs off
- [ ] Document what items were impacted by creating new issues, if necessary
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [x] Remove trussworks from tdrs-frontend
- [x] Replace all trussworks components with normal elements and USWDS classes
- [x] Replace unnecessary CSS overrides with normal classes
- [x] Remove !important and doubled up classes from SCSS (hopefully)
- [x] Run Testing Checklist and confirm all tests pass

**Open Questions:**

- Is it possible to override styles by adding personal project classes or is increased specificity still necessary in SCSS selectors?

**Comment by shubhi-raft** [comment]
@hilvitzs could you please task this out.

**Comment by shubhi-raft** [comment]
- Is it possible to override styles by adding personal project classes or is increased specificity still necessary in SCSS selectors? @lauraGgit and @cmajel can help with answering this question.

**Comment by reitermb** [comment]
All good on the palette front now, signing off on my AC
