### ISSUE TITLE
Friendly name cleanup

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2801]
**Description:**

There are inconsistencies in the friendly names for related data elements. Some examples are below for TANF T6 record for the approved number of application data elements:

https://github.com/raft-tech/TANF-app/blob/ca6eecf9dada19b29ba5f35b3f77541856ad2ebb/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py#L300

https://github.com/raft-tech/TANF-app/blob/ca6eecf9dada19b29ba5f35b3f77541856ad2ebb/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py#L89

https://github.com/raft-tech/TANF-app/blob/ca6eecf9dada19b29ba5f35b3f77541856ad2ebb/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py#L511

 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] friendly names for [TANF T6 records](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t6.py) are consistent
- [ ] All friendly names in code base are crross-referenced with associated coding instructions and 1:1 match each item name
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Miles & Victoria pair on Git processes and friendly name subject area
- [x] Replace friendly names in codebase with verbatim versions from coding instructions
- [x] Write truncated friendly names for wordy instruction edge cases
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by victoriaatraft** [comment]
Documenting the initial [local changes to the python files here](https://gorafttech-my.sharepoint.com/:x:/g/personal/vamoroso_teamraft_com/EbOyrZPqlA1Chz8oaVTWDKQBj5CmOYb-N8-U606f1gMvQg?e=fCKoSZ) while highlighting fields that are either very long (highlighted in yellow) or present potential conflict (highlighted in orange). Will be updating any rows that are green based on feedback.

After a conversation with @reitermb, we'll be reassessing the lengthy names that are in the codebook and explore presenting as a discussion topic at the next ux or product sync

**Comment by reitermb** [comment]
Likely remaining 3pts on work + review process

**Comment by victoriaatraft** [comment]
All tribal_tanf files from t1-t7 have been updated with the following:
- record type -> Record Tyle
- reporting month year -> Reporting Year and Month
- All race or ethnicity options start with: Ethnicity/Race: XXX
- Your comments have also be updated on t1
- Added options for rewrite in green under t2
- Updated up the schemas A B and C on t6 to correspond to the months A- First Month B-Second Month and C is - Third Month

**Comment by reitermb** [comment]
~5pts remaining

**Comment by andrew-jameson** [comment]
~3 pts remaining

**Comment by victoriaatraft** [comment]
Fixed [excel workbook ](https://gorafttech-my.sharepoint.com/:x:/g/personal/vamoroso_teamraft_com/EbOyrZPqlA1Chz8oaVTWDKQBj5CmOYb-N8-U606f1gMvQg?e=haH2Bf)columns to better reflect changes made in the codebase for feedback from @lfrohlich in the "Additional Comments" Column Added in additional screenshots for context.

**Comment by robgendron** [comment]
5 points remaining.

**Comment by lfrohlich** [comment]
Final fixes were merged with #2931
