### ISSUE TITLE
As a developer I want to have database analyzer tool to monitor and analyze Postgres

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2808]
**Description:**
As the TANF application is becoming more complex and we are adding more logic with transactions to the backend DB, we will need to monitor the DB logs and analyze it in depth to find ways to improve and resolve issues.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Install [pgbadger](https://github.com/darold/pgbadger) or a similar postgres analyzer
- [ ] The analyzer is available to an admin user
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by jtimpe** [comment]
related #831

**Comment by raftmsohani** [comment]
This is not required anymore after Sentry is installed we will have query analysis tools #DUPE
