### ISSUE TITLE
As a user, I want to know that TDP site is an ACF site [add Gulp to tdrs-frontend in order to utilize USWDS styles and styling is updated with mobile breakpoints]

### ISSUE THREAD

**Issue by hilvitzs** [raft-tech/TANF-app#281]
**Description:**
In the USWDS docs, there are instructions for adding gulp to your project in order to utilize customizations and base styling.

**Acceptance Criteria:** 

- [ ] Gulp is added as an NPM package
- [ ] Extra breakpoints are added to the project and mobile styling is updated to match mocks with new breakpoints
- [ ] Able to add extra customization such as default fonts and added colors
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [ ] Add Gulp to tdrs-frontend
- [ ] Use .gulpfile from USWDS docs
- [ ] Change available breakpoints and update styling to match mocks
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://designsystem.digital.gov/documentation/developers/
- https://github.com/uswds/uswds-gulp

**Open Questions:**

- Can you add custom colors to be used as token once Gulp is added?

**Comment by lauraGgit** [comment]
@hilvitzs just checked with main dev on uswds and they said they are working to update the documenation in the next sprint to go deeper on the customization requirements for USWDS. But the main things that we can use our compiler for 

1. get your project's custom settings
2. get the uswds source from the npm package
3. attach any custom styles at the end

which we can do with the `node-sass` on this.

I'm going to share a doc in teams on it with you and would be happy to pair to show what i have set up on other sites with sass compilers for uswds custimization.

**Comment by lfrohlich** [comment]
@hilvitzs  can you confirm whether this is still needed?

**Comment by hilvitzs** [comment]
@lfrohlich This is not needed anymore so I will close it.
