### ISSUE TITLE
Reduce dev environment count

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2813]
**Description:**
For prudent cost-cutting, we will be reducing number of our idle dev environments.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Reduce dev env apps by 1
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Delete raft or sandbox environment
- [x] Update dev-space documentation
    - [x] update `draw.io` diagram to remove raft or sandbox from the following - https://github.com/raft-tech/TANF-app/blob/develop/docs/Technical-Documentation/diagrams/tdp-environments.png
    - [x] possible markdown docs updates
- [x] Remove said environment from automation/CircleCI
- [x] Run Testing Checklist and confirm all tests pass
- [ ] Stretch: ensure AMS login works on QASP

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by andrew-jameson** [comment]
Manual intervention needed for this service:

```
{
  "error": {
    "statusCode": 502,
    "status": "502 Bad Gateway"
  },
  "errorResponse": {
    "description": "Service instance tdp-storage-sandbox: Service broker error: BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
    "error_code": "CF-ServiceBrokerBadResponse",
    "code": 10001,
    "http": {
      "method": "DELETE",
      "status": 500
    }
  }
}```
