### ISSUE TITLE
Aggregate Cloud.gov ES instances

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2814]
**Description:**
As the development of Kibana has wrapped up it has been discovered that it is prohibitelve expensive to deploy ES, Kibana, and the ES proxy on a per app basis. Thus, we want to aggregate all ES instances into one singular (larger) instance to help mitigate cost and deployment complexity.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ]  Singular Elastic instance
- [ ] Singular Kibana instance
- [ ] Frontend and backend apps for all environments happily talk to the singular instances
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Delete existing Elastic instances
- [ ] Update Terraform to stand up a singular Elastic instance
- [ ] Update deploy scripts to connect frontend/backend apps to the correct Elastic instance
- [ ] Update Kibana and Elastic proxy deployment manifests to not be environment specific 
- [ ] Redeploy/restage frontend/backend apps so that they connect to the new instances

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
