### ISSUE TITLE
Kibana Dashboard Upload

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2815]
**Description:**
With Kibana now deployed and functional, we would like to have some pre-canned dashboards prepared for OFA staff. That way no manual configuration will be required by the customer. Kibana has an import and export API specifically for this. We can leverage the API to import the exported dashboards on app deployment.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] ~~Work with Alex to define dashboards to meet OFA needs~~
- [ ] Dashboard(s) can be imported successfully on app deployment
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] ~~Work with Alex to define dashboards to meet OFA needs~~
   - UX to help scope needs
- [ ] Update local config to import dashboards
- [ ] Add script or update an existing script to connect to the appropriate Kibana instance to upload dashboards
  - [ ] Potentially do this in the deployment manifest
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by robgendron** [comment]
Nearing completion.

**Comment by lhuxraft** [comment]
Closing as Kibana is leaning towards no use, may revisit in the future
