### ISSUE TITLE
Parametrize ES Indices

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2816]
**Description:**
Since we are planning to move to a singular Elastic instance in the dev zone, it would be nice to parametrize our indices in Elastic so that we still have the capability to analyze data uploaded to Elastic on a per app basis.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Each environment has unique indices in Elastic
- [ ] Each index is found and usable by Kibana
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add a new setting to capture the environment the backend app is being deployed in
- [ ] Use the new setting to parametrize the index name for all the ES documents
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by jtimpe** [comment]
dependent on #2814

**Comment by andrew-jameson** [comment]
Done months ago per dev office hours.
