### ISSUE TITLE
As tech lead, I need TDP to reject files that do not have an update indicator == D

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2818]
**Description:**

Currently, the legacy system (TDRS) handles re-submitted records based on the [update indicator](https://www.acf.hhs.gov/sites/default/files/documents/ofa/transmission_file_header_trailer_record.pdf) in the header record. The rules are as follows:

- indicator = N for new records to be added to the db for a given fiscal period, program type, and data type
  - STTs may use this indicator as a mechanism for submit a subset of records
- indicator = U for records  that are being re-submitted to update existing records in the db for a given fiscal period, program type, and data type 
  - STTs often use this indicator as a mechanism for submit a subset of records
- indicator = D for records that are being re-submitted to delete and overwrite any existing records in the db for a given fiscal period, program type, and data type

TDP does not currently consider the update indicator in the pre-parsing logic; additionally we have been advising the STTs in our knowledge center to always use the D indicator for re-submissions to help them start to practice sending all records that they intend to submit for federal reporting. 

We now need a mechanism to ensure TDP is not parsing and storing data from "incomplete" files in the db. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] If the update indicator != D, reject and do not parse the file. 
- [ ] feedback report should indicate this as a cat 1 error. 
- [x] OFA updates the header record documentation to remove the N and U options as valid possible values
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- A lower lift would be to remove the N and U as valid possible options  and keep parsing, so STTS have a chance to correct it? 
- _Open Question 2_

**Comment by ADPennington** [comment]
@reitermb note that this will introduce a new definition for why files can be rejected. this needs to be reflected in the KC.

**Comment by ADPennington** [comment]
for `dev` who picks up this ticket, please see: https://github.com/raft-tech/TANF-app/issues/2754#issuecomment-1946376987

**Comment by atrimpe** [comment]
Per Miles, remove AC about knowledge center as it is being covered in [#2847](https://github.com/raft-tech/TANF-app/issues/2847)

**Comment by ADPennington** [comment]
@ttran-hub this is the ticket that includes an OFA task for updating header documentation.

**Comment by ADPennington** [comment]
> @ttran-hub this is the ticket that includes an OFA task for updating header documentation.

thanks @ttran-hub for updating the header documentation 🚀

**Comment by ADPennington** [comment]
@atrimpe @elipe17 -- do we have a replacement PR for this ticket?

**Comment by ADPennington** [comment]
> @atrimpe @elipe17 -- do we have a replacement PR for this ticket?

adding @robgendron
