### ISSUE TITLE
 Resolve WebInspect scan findings for Jan-Feb 2024

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2822]
**Description:**

As of February 2024, WebInspect is flagging the following medium/low findings. These issues are tracked [here](https://hackmd.io/UJgaqZW9RiCf5MSihhsijA?view).

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] medium finding addressed without impact to sys admin api access (60 day turnaround)
- [ ] 3 low findings addressed (120 day turnaround)
- [ ] repo captures documentation on any findings that will not be addressed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

** Related issues **

- #2901 
- #2902

**Comment by ADPennington** [comment]
@jtimpe this is ready for backlog on 3/5.

**Comment by ADPennington** [comment]
per 3/5/24 backlog:

- medium finding will not be remediated given ISSO-approved session management strategy here: https://github.com/HHS/TANF-app/blob/main/docs/Security-Compliance/Security-Controls/ac-2-5/index.md
- #2843 will address low finding re: unsafe- series of headers. 
- other low findings will be addressed in this ticket 
- priority: 120 day turnaround

**Comment by ADPennington** [comment]
per today's sync with Mo -- we will remediate the medium webinspect finding re: cookie and will create a new ticket to add a token for admin access to api.

**Comment by raftmsohani** [comment]
AC: set SESSION_EXPIRE_AT_BROWSER_CLOSE to True, this will set the session to while browser is open

**Comment by ADPennington** [comment]
@robgendron please add this ticket to the deck to be picked up next sprint.

**Comment by robgendron** [comment]
@ADPennington Will do!

**Comment by robgendron** [comment]
Still developing potential fix.

**Comment by jtimpe** [comment]
@robgendron closing as #2941 has merged, waiving the applicable low priority finding. #2911 had previously merged, resolving the medium finding.
