### ISSUE TITLE
Resolve issues raised in pen testing findings

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2824]
**Description:**

ACF Tech is performing penetration testing in the staging environment ([currently on Sprint 90 release](https://github.com/raft-tech/TANF-app/releases/tag/v3.2.0-Sprint-90)) between 1/22/24 - 2/05/24. Key findings will be captured [here](https://hackmd.io/RF6RT80yQOqMPdwiCrT2VQ?view#)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Finding 1 resolved
- [x] Finding 2 resolved
- [x] Finding 3 resolved
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://github.com/raft-tech/TANF-app/pull/2679#discussion_r1307755734
- most recent qasp- testing of api: https://github.com/raft-tech/TANF-app/pull/2477#pullrequestreview-1429518039

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by raftmsohani** [comment]
I am writing this as a suggestion since there are many way to attack this problem. 

The idea is to add django authentication [decorator](https://docs.djangoproject.com/en/5.0/topics/auth/default/) to verify if the user is authenticated to view the api. There is a authentication test that verifies if the user is authenticated and which group user is assigned to. Then the decorator should be added to api views that need to be locked to specific users.

Another task is to disable changing the superuser for the user. My suggestion is to hide the superuser or make it readonly in the admin page, and additionally disable serializer/view to change the superuser field.

**Comment by ADPennington** [comment]
@andrew-jameson @jtimpe @elipe17 hackmd updated. please share findings with @raftmsohani
