### ISSUE TITLE
As tech lead, I need some record types that currently require trailing spaces to be parsed

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2826]
**Description:**

We currently do not parse records that are too short. See example below:

![record_length_preparsing](https://hackmd.io/_uploads/r1s5OAv56.png)

This is because the record layouts, as published, define the expected lengths. However, several record types are space-filled simply due to the legacy record layout design. For example, in TANF Section 1, `T1`, `T2`, and `T3` record types are all expected to be `156` in length, but `T1` and `T3` expects trailing spaces or zeros. 

While OFA has observed scenarios where records that are too short raise errors in TDRS, we've also seen scenarios where TDRS doesn't raise an error. Many STTs have not space- or zero-filled as required, for this reason. 

To handle this, we would like to parse the records that do not include the trailing spaces or zeros and not raise a cat 1 error. 

Consideration:
- how to know when a record is too short, but still "parse-able"? (e.g. for `T1`, as long as there is a value reported for item # 29, which is the last item in the T1 record, proceed with parsing. )

**Acceptance Criteria:** 

- [ ] TANF `T1` records are parsed if 117<= length <= 156
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~TANF `T3` records with one child are parsed if length >= 60~~
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~TANF `T3` records with two children are parsed if 101 <= length <= 156~~
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~Do not store records from the 2nd child position of  TANF or Tribal TANF `T3` record  if there is only one child in the record (#2757 )~~
- [ ] Tribal TANF `T1`  records are parsed if 117<= length <= 122
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~Tribal TANF `T3`  records with one child are parsed if length >= 60~~
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~Tribal TANF `T3` records with two children are parsed if 101 <= length <= 122~~
- [ ]  Tribal TANF and TANF `T4` records are parsed if 36 <= length <= 71
- [ ] SSP `M1` records are parsed if 113<= length <= 150
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~SSP `M3` records with one child are parsed if length >= 60~~
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~SSP  `M3` records with two children are parsed if 101 <= length <= 150~~
- [ ] Being covered [HERE](https://github.com/raft-tech/TANF-app/issues/2757): ~~Do not store records from the 2nd child position of `M3` record  if there is only one child in the record (#2757 )~~
- [ ]  SSP `M4` records are parsed if 36 <= length <= 66
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- relevant to TANF, SSP, and Tribal TANF schemas
- replace `hasLength` preparser validator with `notEmpty`
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- TANF and SSP record layouts: https://www.acf.hhs.gov/sites/default/files/documents/ofa/Forms_ACF-199_and_ACF-209-Crosswalk_of_Changes.xlsx
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
@raftmsohani and I met about #2757 since some of the requirements here (specifically re: child records for TANF, Tribal TANF, and SSP) are related. We agreed that he would address this ticket's ACs for the child records in #2757.
