### ISSUE TITLE
Spike - Cloud.gov Kibana Reschedule Route Issue

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2839]
**Description:**
Cloud.gov does maintenance from Tuesday to Thursday. In this time they can bring apps down, or reschedule them to perform the maintenance. When the Kibana app is rescheduled/brought down and then up, the internal Nginx route from the frontend to Kibana is no longer valid. Nginx does not receive the updated state from cloud.gov giving the Kibana app a new IP address. The workaround for this is to restage the frontend. Nginx gets the updated info and all is well. However, we would like to avoid having to do this manually and see if we can somehow tie the state of Kibana reschedule to the frontend a little better.

One thing to note is that this issue only happens with docker apps in cloud.gov. When a buildpack app is restaged, the routing is not messed up. Another example of this is the clamav nginx router. Below are logs confirming the issue:

```
# Occurred Thursday 2/8/24

# Kibana Logs
14:47:25.073: [CELL.0] Container became healthy
14:47:25.224: [API.2] Process is being rescheduled
14:47:29.414: [CELL.0] Cell c51e9a40-dff6-400a-b1b0-c88318aae8f2 stopping instance 611cb987-a12b-47c3-768e-4b7f
14:47:34.785: [CELL/SSHD.0] Exit status 0
14:47:45.784: [CELL.0] Cell c51e9a40-dff6-400a-b1b0-c88318aae8f2 destroying container for instance 611cb987-a12b-47c3-768e-4b7f
14:47:45.921: [PROXY.0] Exit status 137
14:47:46.624: [CELL.0] Cell c51e9a40-dff6-400a-b1b0-c88318aae8f2 successfully destroyed container for instance 611cb987-a12b-47c3-768e-4b7f

# Frontend Logs
16:17:52.985: [APP/PROC/WEB.0] 2024/02/08 23:17:52 [error] 116#0: *232 connect() failed (113: No route to host) while connecting to upstream, client: 107.2.184.249, server: , request: "GET /kibana/ HTTP/1.1", upstream: "http://10.255.134.124:5601/", host: "tdp-frontend-qasp.app.cloud.gov", referrer: "https://tdp-frontend-qasp.app.cloud.gov/data-files"
16:17:52.987: [RTR.4] tdp-frontend-qasp.app.cloud.gov - [2024-02-08T23:17:52.290706978Z] "GET /kibana/ HTTP/1.1" 404 0 555 "https://tdp-frontend-qasp.app.cloud.gov/data-files" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "127.0.0.1:5454" "10.10.1.25:61238" x_forwarded_for:"107.2.184.249, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:"182a34b5-e22a-4535-7cc2-e5c9549fce50" response_time:0.696023 gorouter_time:0.000101 app_id:"66b86b25-3c40-48a9-916e-c5319e51f308" app_index:"0" instance_id:"d9430b8e-a38a-43ed-6eb4-b38e" x_cf_routererror:"-" x_b3_traceid:"182a34b5e22a45357cc2e5c9549fce50" x_b3_spanid:"7cc2e5c9549fce50" x_b3_parentspanid:"-" b3:"182a34b5e22a45357cc2e5c9549fce50-7cc2e5c9549fce50"
16:17:52.985: [APP/PROC/WEB.0] 2024/02/08 23:17:52 [error] 116#0: *232 open() "/home/vcap/app/public/50x.html" failed (2: No such file or directory), client: 107.2.184.249, server: , request: "GET /kibana/ HTTP/1.1", upstream: "http://10.255.134.124:5601/", host: "tdp-frontend-qasp.app.cloud.gov", referrer: "https://tdp-frontend-qasp.app.cloud.gov/data-files"
```

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Determine if there is a way to automatically resolve the routing issues
- [ ] Implement solution
- [ ] Reschedule Kibana and verify Frontend can still route to it without restaging it.

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Determine if it is possible to tie app state together a bit better.
- [ ] reach out to cloud.gov support to get more context on the issue
- [ ] Implement solution if it exists

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Potential workaround
    - restage nginx proxy application after elastic restage
- Low-fi solution
   - automatically restage app after elastic restage or periodically
   - uptime monitor to notify when application goes down
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
i sent an email today to cloud.gov support. ticket # 8132

**Comment by ADPennington** [comment]
> i sent an email today to cloud.gov support. ticket # 8132 

Response: 

Thank you for your ticket/question. When we do maintenance and apps redeploy, the IPs change and Nginx may lose its connection to things. After looking into this matter we would suggest you try following the recommendations in this video at this timestamp: [https://youtu.be/2m4FP522DU8?si=VZ02zMXkkqoatYTg&t=749](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2F2m4FP522DU8%3Fsi%3DVZ02zMXkkqoatYTg%26t%3D749&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7Cd281e5eaf31c43fdcf1508dc2ce4e1d6%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638434608748377798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=eoPqobRIYJEYWoXuuXLpv1r2%2BnOfuU9MaPoJnX4qevc%3D&reserved=0) for this matter. Additionally name resolution for internal routes is also discussed here at the link [here](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.cloudfoundry.org%2Fbuildpacks%2Fnginx%2Findex.html%23nameservers&data=05%7C02%7Calexandra.pennington%40acf.hhs.gov%7Cd281e5eaf31c43fdcf1508dc2ce4e1d6%7Cd58addea50534a808499ba4d944910df%7C0%7C0%7C638434608748387795%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OoFKg%2BbYaWjA0qCvaU5iFVZiOUJrxv6X4nQAFy%2FhteQ%3D&reserved=0). Please let us know if you would like any further clarification or have any other questions.

**Comment by elipe17** [comment]
Other helpful documentation can be found [here](https://www.nginx.com/blog/dns-service-discovery-nginx-plus/).
