### ISSUE TITLE
DIGIT Kibana Access

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2840]
**Description:**
Pending the completion of #1441, and Alex giving the OK to allow access, we would like the DIGIT team to be able to access Kibana and have pre-canned queries so they can export and visualize the data they regularly interact with. See #1441 for examples of the types of queries the DIGIT team will need ported over to Kibana.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] DIGIT Team can access Kibana
- [ ] DIGIT Team can run queries and get necessary data via Kibana
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update Kibana auth check view to include DIGIT Team group for access.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by elipe17** [comment]
Note, CSV export of queries is only supported in AWS ES 7.9. However, Cloud.gov only supports AWS ES 7.4. Thus, we can generate equivalent KQL/Elastic queries, but there will not be an easy way to export them until cloud.gov supports a newer version of the AWS ES service, or we are no longer bound to cloud.gov.
