### ISSUE TITLE
[Design Deliverable] GitHub Error Categories Guide

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2845]
**Description:**

Delivers GitHub repo Technical Documentation folder document covering definitions and examples of Cat1-4. Follow-on work will later add examples for Categories 5, 6

**AC:**

- [x] Definitions & Examples for Categories 1-4 are present
- [x] Other categorizations of TANF data are defined including 
   - [x] File types (TANF, SSP-MOE, Tribal TANF)
   - [x] Sections of data (1-4)
   - [x] Record Types (T1-T7)

**Tasks:**

- [x] Draft [content in hack.md](https://hackmd.io/@mreiter/HkoZa3V5T)
- [x] Open PR

**Comment by ADPennington** [comment]
@reitermb I dont think OFA expects cat 5 or cat 6 errors to be implemented anytime soon. we can open a new ticket when those are ready.
