### ISSUE TITLE
[Design Deliverable] Submission History Knowledge Center Explainer

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2846]
**Description:**

Delivers updated knowledge center content defining acceptance statuses / other elements of the submission history page. Some of this content will eventually be surfaced in-app (like the key breaking down acceptance statuses)

**AC:**

- [ ] Definitions & Examples for all acceptance statuses are present
- [ ] Other data centric submission history columns are defined 
   - [ ] Cases with/without errors
   - [ ] Records unable to process
   - [ ] Error report
- [ ] Additions have passed internal and gov-a11y review from @ttran-hub (deployed in Knowledge Center Test Environment)
- [ ] PR is opened

**Tasks:**

- [ ] Draft [content in hack.md]()
- [ ] Deploy to test environment

**Comment by ADPennington** [comment]
this ticket is related to #2509

**Comment by reitermb** [comment]
1 pt remaining

**Comment by lfrohlich** [comment]
@reitermb can you comment on why this was closed? was it subsumed into #2847?

**Comment by reitermb** [comment]
> @reitermb can you comment on why this was closed? was it subsumed into #2847?

This closed out with the #2906 PR that was merged a couple weeks ago. 
#2847 isn't directly related and be merged via a new PR
