### ISSUE TITLE
[Design Deliverable] Error Report Knowledge Center Explainer

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2847]
**Description:**

Delivers knowledge center content defining the error report and how it relates to TANF data files

**AC:**

- [x] Include:
   - [x] Cases, Records, data elements (and their values) 
   - [x] Resources for acting on error reports (instructions, layouts)
- [x] Additions have passed internal and gov-a11y review (deployed in Knowledge Center Test Environment)
- [x] PR is opened

**Tasks:**

- [x] Draft [content in hack.md](https://hackmd.io/@mreiter/B1d_OLceC)
   - [x] File extension guide (was covered in #2846)
   - [x] Error Report explainer
- [x] Stage in Test environment

**Comment by reitermb** [comment]
@ttran-hub @ADPennington Testing resources for confirming these steps are reproduceable: 

The txt file extension guide is staged in the testing environment at:  https://reitermb.github.io/Test/knowledge-center/file-extension-guide

- Follow the steps in both method walkthroughs to produce a flat file with a .txt extension. 
- Attempt to upload the file to TDP to ensure it can upload as expected and does not trigger the file extension error.
- If any of the written guidance is unclear please annotate it in the [hack.md](https://hackmd.io/@mreiter/r1cVEHNTp)

FTANF can be used to produce one but I've also attached an extensionless sample file here in the zip folder if one is helpful to attempt the renaming method on. 

[Extensionless file.zip](https://github.com/raft-tech/TANF-app/files/14516431/Extensionless.file.zip)

**Comment by ADPennington** [comment]
> @ttran-hub @ADPennington Testing resources for confirming these steps are reproduceable:
> 
> The txt file extension guide is staged in the testing environment at: https://reitermb.github.io/Test/knowledge-center/file-extension-guide
> 
> * Follow the steps in both method walkthroughs to produce a flat file with a .txt extension.
> * Attempt to upload the file to TDP to ensure it can upload as expected and does not trigger the file extension error.
> * If any of the written guidance is unclear please annotate it in the [hack.md](https://hackmd.io/@mreiter/r1cVEHNTp)
> 
> FTANF can be used to produce one but I've also attached an extensionless sample file here in the zip folder if one is helpful to attempt the renaming method on.
> 
> [Extensionless file.zip](https://github.com/raft-tech/TANF-app/files/14516431/Extensionless.file.zip)

thanks @reitermb. this is in good shape. please note:

- i made in-line changes using ~~strikethrough~~ in the hackmd and left a comment. 
- I noticed that the language in the test environment doesnt exactly match what is in the hackmd. Because of this, i focused on the hackmd language. Please check that these align. 
- Some of the visuals are not rendering in the test environment. 
- I have successfully tested both approaches and can confirm they work from my Windows 11 machine.

**Comment by reitermb** [comment]
> > @ttran-hub @ADPennington Testing resources for confirming these steps are reproduceable:
> > The txt file extension guide is staged in the testing environment at: https://reitermb.github.io/Test/knowledge-center/file-extension-guide
> > 
> > * Follow the steps in both method walkthroughs to produce a flat file with a .txt extension.
> > * Attempt to upload the file to TDP to ensure it can upload as expected and does not trigger the file extension error.
> > * If any of the written guidance is unclear please annotate it in the [hack.md](https://hackmd.io/@mreiter/r1cVEHNTp)
> > 
> > FTANF can be used to produce one but I've also attached an extensionless sample file here in the zip folder if one is helpful to attempt the renaming method on.
> > [Extensionless file.zip](https://github.com/raft-tech/TANF-app/files/14516431/Extensionless.file.zip)
> 
> thanks @reitermb. this is in good shape. please note:
> 
> * i made in-line changes using ~strikethrough~ in the hackmd and left a comment.
> * I noticed that the language in the test environment doesnt exactly match what is in the hackmd. Because of this, i focused on the hackmd language. Please check that these align.
> * Some of the visuals are not rendering in the test environment.
> * I have successfully tested both approaches and can confirm they work from my Windows 11 machine.

I'm not sure I found the noted differences between what was staged in the test environment and the hack.md but all changes should be addressed now in the Test environment & imagery added! 
https://reitermb.github.io/Test/knowledge-center/file-extension-guide

**Comment by reitermb** [comment]
2pts remaining

**Comment by robgendron** [comment]
Estimates 4 points remaining.

**Comment by reitermb** [comment]
![image](https://github.com/raft-tech/TANF-app/assets/28515874/8cc29ade-f502-481f-b9e7-4b38df9bd85f)

A11y sync w/ @ttran-hub and @victoriaatraft on 4/29/24 — All coming up error-free
Noting that we scanned all knowledge center pages, not just the new error reports page, given that this work adds a new item to the navigation (which requires code changes to the navbar component on all pages)

**Comment by ttran-hub** [comment]
> ![image](https://private-user-images.githubusercontent.com/28515874/326538018-8cc29ade-f502-481f-b9e7-4b38df9bd85f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTQ2ODAsIm5iZiI6MTcxNDQxNDM4MCwicGF0aCI6Ii8yODUxNTg3NC8zMjY1MzgwMTgtOGNjMjlhZGUtZjUwMi00ODFmLWI5ZTctNGIzOGRmOWJkODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE4MTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmEwNjQ2MGZiNTI3YTVjMjBjMTc5OWE2NzAxM2QzNDk1ZjkwNDA1ZjUzZGQwYWU2MDRjZWZlMWVlNTVhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4XbzybGz8D-1hYE2pP3TpnDYSVBJnCa8jSqyvnP1j1g)
> 
> A11y sync w/ @ttran-hub and @victoriaatraft on 4/29/24 — All coming up error-free Noting that we scanned all knowledge center pages, not just the new error reports page, given that this work adds a new item to the navigation (which requires code changes to the navbar component on all pages)

Thanks @reitermb and @victoriaatraft for the sync! a11y looks good. 🚀

**Comment by ADPennington** [comment]
just documenting for team visibility that I reviewed the draft and left comments on 5/1/2024.

**Comment by lfrohlich** [comment]
@reitermb is this back in Raft review to address Alex's comments? https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/knowledge-center-drafts/error-reports-and-file-structure/~/comments/njbl3QnoEWuee5PsA7tB?node=8mjpRv6BxsEe

**Comment by reitermb** [comment]
> @reitermb is this back in Raft review to address Alex's comments? https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/knowledge-center-drafts/error-reports-and-file-structure/~/comments/njbl3QnoEWuee5PsA7tB?node=8mjpRv6BxsEe

Yes! Targeting a fully updated/responded version by end of day today.

**Comment by reitermb** [comment]
Updating with info from standup: 
- Wrapped up changes yesterday with a couple of remaining review follow-up / discussion items in comments. @ADPennington to let me know if there's an opportunity for an earlier sync but if not they'll be a UX sync discussion item come Tuesday

cc @ADPennington @lfrohlich

**Comment by ADPennington** [comment]
> Updating with info from standup:
> 
> * Wrapped up changes yesterday with a couple of remaining review follow-up / discussion items in comments. @ADPennington to let me know if there's an opportunity for an earlier sync but if not they'll be a UX sync discussion item come Tuesday
> 
> cc @ADPennington @lfrohlich

@reitermb i took another pass on review. i left some suggestions on how to help the guide flow better and where more context is needed. we can discuss at next ux sync.

**Comment by ADPennington** [comment]
when its ready, please also include this ticket number in the PR for tracking ticket closure.

**Comment by reitermb** [comment]
@victoriaatraft @robgendron should be ready for any final raft-review readability passes!

**Comment by reitermb** [comment]
Raft-review complete, back over to QASP!

cc @ADPennington @lfrohlich

**Comment by ADPennington** [comment]
@reitermb I've completed review. Once comments are addressed, please push up changes in a PR and include the test environment links. cc: @lfrohlich @ttran-hub
