### ISSUE TITLE
DB Backup Failing

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2852]
**Description:**
It was discovered while collecting evidence for the SCA that the nightly postgres database backups are not happening. Alex verified this by checking the S3 bucket and seeing that the last backup was a manual backup and it occurred ~3 months ago, see below:
```
$ aws s3 ls  s3://cg-<redacted>/backup/tmp/  --profile TDP_prod_datafilesS3_20240201
2023-11-09 09:57:07  221750276 backup-2023-11-09.pg
2023-08-03 17:18:38    8196819 backup-prod-sprint77
2023-08-23 15:25:43   79974970 backup-prod-sprint79-sendgrid
```

This issue also exists in the dev and staging environments. The last backup in the dev environment was well over a year ago.
```
2022-05-06 04:24:58      69016 backup.pg
```

- Database backups should happen nightly.
- Apparent logging of the backup happening, completing, and failing should exist at bare minimum in the system console logs.
- Ideally some logging should be done to the DAC for extra persistence

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Nightly backups occur
- [ ] Better observability into the backup task by system and django based logging
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Identify the failure in the backup task.
- [ ] Resolve the failure.
- [ ] Add system and Django based logging
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by elipe17** [comment]
Update, I reached out to cloud.gov because this seems to be an issue with there VMs and the pg client they install by default. The error message below indicates that the pg client binaries cannot access the correct version of perl.

`Can't locate PgCommon.pm in @INC (you may need to install the PgCommon module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at ./pg_dump line 22.`

**Comment by elipe17** [comment]
Update. There are many postgres client binaries installed on the VM. The only set of binaries that doesn't throw the above error are the ones located here: `/home/vcap/deps/0/apt/usr/lib/postgresql/12/bin/`. However, when we use this set of binaries we get the following error: 

```
pg_dump: error: server version: 15.5; pg_dump version: 12.18 (Debian 12.18-1.pgdg120+2)
pg_dump: error: aborting because of server version mismatch.
```
