### ISSUE TITLE
Upgrade Postgres DB from version 12 to version 15

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2857]
**Description:**
Postgres version 12 is reaching EOL sometime in Oct 2024 (see [this](https://www.postgresql.org/support/versioning/)).
- upgrading to 14 may be a lower lift until some operating system dependencies are ironed out (more info)
- additional considerations - "*Note: For PostgreSQL versions 15+ , using SSL is required when connecting to your database. As such, you will need to configure your client library to use SSL when connecting to your database." - https://cloud.gov/docs/services/relational-database/#create-an-instance

Cloud.gov drops support for DBs that are not supported (see [this](https://cloud.gov/docs/services/relational-database/))

We will need to upgrade from version 12 to version 15.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Postgres is upgraded to version 14/15
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] check out the posgres upgrade binary to automate the following steps:
   - [ ] Specify version 14/15 in terraform
   - [ ] Perform a database backup
   - [ ] delete and recreate the database in the new version
   - [ ] restore db using backup
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by robgendron** [comment]
@raftmsohani is this refined as is? If so, please remove the placeholder tasks, notes, supporting documents, and questions.

**Comment by robgendron** [comment]
Update: Dev environment is at 15.7, deployed Raft application 
Next: Staging and development
