### ISSUE TITLE
Simplify invalid file extension error message and add Knowledge Center link

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2873]
### Background ###
As a data analyst, I need clear guidance on how to comply with file extension validation requirements. This update simplifies the error message shown on the Data Files page when an invalid extension is uploaded and provides a direct link to the Knowledge Center for more detailed instructions. This follows up on the work done in #2690 to address an increased number of user inquiries regarding file extension requirements.

### Acceptance Criteria ###
- [ ] Error language is updated to "Invalid extension, please upload a .txt file. [Need help?](https://tdp-project-updates.app.cloud.gov/knowledge-center/file-extension-guide.html)" (link not env dependent, follow pattern for knowledge center links on homepage/footer)
    - [ ] update `INVALID_EXT_ERROR` in `FileUpload.jsx`
- [ ] Link points toward knowledge center guidance delivered in #2847 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [x] Change error copy
- [x] Add link to error
   - [ ] https://tdp-project-updates.app.cloud.gov/knowledge-center/file-extension-guide.html
- [x] Run Testing Checklist and confirm all tests pass
- [ ] A11y review to confirm that a new tab stop within the file upload component doesn't break anything

**Comment by robgendron** [comment]
What is the priority of this? @reitermb
