### ISSUE TITLE
Move ES AWS routing docker image to RAFT hub

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2877]
## Description

Currently, the Kibana docker image lives in [personal hub](https://github.com/raft-tech/TANF-app/blob/4daa673d3874431209df1ee4c0201e62441822e8/tdrs-backend/manifest.proxy.yml#L10). It has to be moved to non-personal project hub.

**Acceptance Criteria:** 

- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Move Kibana docker to RAFT hub
- [ ] Update .yml file to reflect new docker URL
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
