### ISSUE TITLE
Pre-Made Reporting Dashboards on Kibana

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2883]
**Description:**

Onboarding Kibana dashboards has to be created for OFA users.

Had a discussion with Alex and decided to perform a research on the reports that OFA has to prepare monthly/yearly on TANF caseloads and as a first step create a dashboard for reports in [this doc](https://www.acf.hhs.gov/sites/default/files/documents/ofa/fy2023_tanf_caseload.pdf)

Most reports (specifically WPR, TL, and Characteristics) require data manipulation and clean up, however our target in this ticket is only TANF/SSP/Tribal TANF section 3 reports that do not need such clean up. Additionally, this PR should investigate these reports and create a proposal for next candidates.
 
Related tickets:
- [ ] [issue 1441](https://github.com/raft-tech/TANF-app/issues/1441)

**Related User Stories:**

—As an OFA user I want to have queries and dashboards that help me to create monthly/yearly TANF case loads

**Recommended pa11y actions:**

—‘click element #error-report’,—

**TASKS**

- [x] Create queries for reports in [1]
- [x] Create dashboard graphs that can be used in those reports
- [x] Create KQL/Elastic queries that provide the same output as the DIGIT Team's SQL queries.
- [x] Determine if queries can be preloaded into Kibana easily.

**Notes:**
- 

** References **
[1]  OFA case loads: https://www.acf.hhs.gov/sites/default/files/documents/ofa/fy2023_tanf_caseload.pdf
[2] TANF data reports https://www.acf.hhs.gov/ofa/programs/tanf/data-reports

**Comment by robgendron** [comment]
This would be MVP for Kibana.

**Comment by robgendron** [comment]
2 points remaining.

**Comment by robgendron** [comment]
Half way through Raft review.
