### ISSUE TITLE
as tech lead, I need SSP Section 2 item # 18A (REC_OASDI_INSURANCE) schema def updated as not a required field

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2887]
**Description:**

Per the coding instructions, SSP Section 2 item # 18A (REC_OASDI_INSURANCE) is not a required field. 

![2887p1](https://github.com/raft-tech/TANF-app/assets/63075587/876ed466-c826-4331-830c-d3906f2783a4)

However, we missed setting this to not required, as shown below: 
https://github.com/raft-tech/TANF-app/blob/abd50999a5d9c793dc30b7daec096059fc1a3d56/tdrs-backend/tdpservice/parsers/schema_defs/ssp/m5.py#L251

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] SSP Section 2 item # 18A (REC_OASDI_INSURANCE) is not a required field. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update codebase to account for this item number not being a required field. 
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [workbook](https://gorafttech.sharepoint.com/:x:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/Parsing/data/ssp/TDP_Validation_SSP_Section2.xlsx?d=we5e1fbb5fde343438ae28cb6a3b6363c&csf=1&web=1&e=QgfQbb) updated

- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
