### ISSUE TITLE
As a data analyst I want finalized language and guidance resources in Submission History & Error Reports

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2897]
**Description:**
Delivers final copy and guidance links to Submission History/Error Report experience in TDP

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Submission history page, data columns, and error report copy match requirements
- [ ] All changes in frontend pass a11y review
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Remove "(In Development)" from Error Reports column of submission history table
- [x] Replace text above the error-related columns & sections in Error Reports with content and links from the prototype
- [ ] Add link to submission history knowledge center explainer to top of Submission History page (between the Current Submission/Submission History tab control and the Section 1 Table)
- [x] remove error type from the feedback workbook (example below)
![2818p5](https://github.com/raft-tech/TANF-app/assets/63075587/c8c3a984-133d-4eeb-9daa-6c3d84632fb5)

- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
[Error-Report-Prototype.xlsx](https://github.com/raft-tech/TANF-app/files/14953657/Error-Report-Prototype.xlsx)

**Comment by robgendron** [comment]
@reitermb is this a Dev or UX ticket?

**Comment by ADPennington** [comment]
@reitermb @robgendron i added a task to this ticket re: removing error type from excel workbook. this is in response to research findings that suggested error type wasnt meaningful for end users, and since we arent explaining what the values mean in the workbook, we should remove it.
