### ISSUE TITLE
As a STT, I need to understand what roles are available as a MVP 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#290]
**Description:**
Roles for MVP need to confirmed. Currently, for MVP there is a data prepper, OFA Admin, and STT admin. This issue will discuss if those roles are sufficient and what set of permissions and functionality is associated with those roles. 

Two possible ways:
1. Roles are associated with permissions. 
2. Permission can be selected based on the roles 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Document how the roles and permissions will be function as the system enhances. 
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- What has security imlpications?
- _Open Question 2_

**Comment by shubhi-raft** [comment]
Tail end sprint 5 and Sprint 6.

**Comment by jenewingpierce** [comment]
@shubhi-raft I think our journey map process is covering this---can we close?

**Comment by shubhi-raft** [comment]
Sure, however, we would need to update the journey map to add roles and permissions MVP users will have as an outcome of it.

**Comment by jenewingpierce** [comment]
@dk-ui and @reitermb let's sync on this later today please.

**Comment by dk-ui** [comment]
@jenewingpierce sounds good!

**Comment by amilash** [comment]
@dk-ui Please confirm we have our personas identified and they are not changing. If confirmed please close this ticket.

**Comment by amilash** [comment]
This is now complete as we have a User and permissions matrix defined.
