### ISSUE TITLE
As an admin user, I want to be able to programmatically access to backend API

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2901]
**Description:**
As a follow up discussion in #2822 , looks like we need to set up JWT token based authentication for reporting codes that need to access the backend API.

**Suggested approach**

Unfortunately, login.gov does not support API user authentication and only supports web login via redirects.

1. One way to handle authentication and grab token is to create an API user, then the user can login normally via webpage, but after login user will be redirected to a page that only shows the API token, which then can be pasted into custom application
2. Bypass 2FA and only generate a DRF API token. To ensure higher security, we can define rules in Nginx to limit access only to VPN connections from ACF.

**Acceptance Criteria:** 

- [ ] Crete a two factor authentication for acquiring new token and logging into backend API
- [ ] API user can authenticate from external application with backend api
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] create an api user in Django
- [ ] create an api to authenticate the user with JWT from ACF
- [ ] create code snippet (python script from outside django/backend with no dependency to django app) to authenticate with login.gov and grab jwt
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- 2 factor auth? manually creating a token after a user signs up/logs in via 2-step process should satisfy req.
- need to also authenticate login.gov jwt token on every request, token auth alone is not sufficient
- token timeout? not implemented by drf
- evaluate other libraries or drf extensions? https://www.django-rest-framework.org/api-guide/authentication/#third-party-packages
