### ISSUE TITLE
As a user I want my session to expire at browser close

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2902]
**Description:**
The session persist up to 14 days, however as a follow up to #2822 the session should expire after closing the broser 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Browser session expires after closing
- [ ] Test to grab the cookie and close the browser and try to login to API using that cookie and confirm the connection fails
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add [SESSION_EXPIRE_AT_BROWSER_CLOSE](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-SESSION_EXPIRE_AT_BROWSER_CLOSE)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
