### ISSUE TITLE
As a `DIGIT Team` user, I need the ability to export parsed data from DAC to csv

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2908]
**Description:**

We had hoped to enable OFA's access to the parsed data in Elastic db via Kibana, but for the following reasons, this is not a feasible solution for `parity`:

- any query will only return 1,000-10,000 records at a time (OFA's queries of TANF section 1 data typically return upwards of 600K records for a given record type and fiscal period) 
- query results are returned in JSON format, and to retrieve the data in this format, OFA team members would need browser dev tools enabled, which currently requires higher level security clearances on government-furnished equipment. 
- Kibana's dev tools console is not fully functional 

The alternative is to access the data via postgres (note: the data in elastic is a copy of the data in postgres, which is considered the "source of truth"), and currently the postgres data is not easily accessible via TDP's interfaces. But some proof-of-concept work completed on [this branch](https://github.com/raft-tech/TANF-app/tree/dac-csv-export) demonstrates the potential to export postgres data to CSV.  OFA would like to move forward with this approach with the following specs in mind:

- only the latest/newest parsed records (for any/all STTs) can be included in each export
- export includes all fields and latest records
- The STT code/location is attached to each record (in its own column)
- it is possible to limit which records are exported by record type, STT, and fiscal period. 
- it is not possible to edit or delete any parsed data records via DAC. 
- field_names are included in the export
- multiple selections within each "filterable" field is possible (e.g. all T1 records for FY24Q1 for Alabama and Alaska)
- it is possible to select multiple filters before clicking "apply" 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `DIGIT team/OFA system admin/OFA admin` can export parsed data via DAC to CSV
- [ ] CSV export includes field names and STT code
- [ ] CSV export only includes latest parsed data for any/all STTs 
- [ ] anyone with access to search_indexes cannot edit/delete parsed data via DAC
- [ ] filtering capability built to abovementioned specs
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- reference: #2861
- _Doc 2_

**Open Questions:**

- _Open Question 1_
- _Open Question 2_
