### ISSUE TITLE
[Research Spike] OOtB OFA Kibana Experience & DIGIT Data Access

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2909]
**Description:**
The 3.4 Release Project Roadmap includes work targeted at ensuring TANF data is accessible to the DIGIT team and continued development of Kibana as a reporting platform. UX will investigate this problem space to help support the below dev tickets, identify ticketing gaps, and answer any open questions required for scoping and delivering this work. 

Supports:
- #2908 Export parsed data from DAC to csv
- #2883 Premade dashboards/queries
- #2840 Kibana Access/Queries
- #2815 Kibana dashboard upload
- #1355 Research questions around DIGIT team queries

**AC:**

- [ ] Research sessions have occurred.
- [ ] Top-line synthesis relevant to refinement of above tickets has occurred 
   - [ ] Identifies resources needed for delivery (e.g. examples of existing reports that Kibana needs to be able to produce)
   - [ ] Identifies open questions required for delivery and scoping of this work
   - [ ] Identifies next steps / generates further tickets aligned to those next steps

**Tasks:**

- [x] Refine current Kibana backlog (see above ticket list) 
- [x] Sync with dev team to align on current knowns
- [x] [Top-level synthesis](https://app.mural.co/t/raft2792/m/raft2792/1716915624823/5f6af93954c13468aa2bb6597f01c1609920b431?sender=ufa4902beba666df5bec09412)
- [x] Discuss w/ dev in Office Hours
- [x] Draft tickets for any previously un-scoped areas, refine existing tickets
- [x] Capture any documentation illustrating current DIGIT reporting / querying as an example of what we'd want to reproduce in 

**Supporting Documentation & Artifacts:**
- [Discussion Notes with Mural and Session Recording from 05/28/2024](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/2909-research-session)
- Use these as a comparison point. e.g. Is this 30% of DIGIT needs for what Kibana needs to deliver? 100%?
   - [Example 1](https://www.acf.hhs.gov/sites/default/files/documents/ofa/fy2023_tanf_caseload.pdf) 
   - [Example 2](https://www.acf.hhs.gov/sites/default/files/documents/ofa/fy2023_tanssp_caseload.pdf)
   - [Example 3](https://www.acf.hhs.gov/sites/default/files/documents/ofa/FY2016_Tribal_Characteristics_Reports.pdf)

**Comment by robgendron** [comment]
Anticipated start - 5/14

**Comment by robgendron** [comment]
Targetted start for this week.

**Comment by victoriaatraft** [comment]
[Discussion Notes with Mural and Session Recording from 05/28/2024](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/2909-research-session)

**Comment by robgendron** [comment]
Working on decomposing follow on tickets.

**Comment by reitermb** [comment]
Closed this spike now that #3028, #3029, and #3030 have been written to track remaining open questions and ultimately deliver the prioritized reports

cc @ADPennington
