### ISSUE TITLE
[Research Facilitation] Admin Experience Improvements

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2910]
**Description:**

Delivers a sync w/ Alex & Thomas to identify and prioritize needed django admin improvements. 

**AC:**

- [x] Research sessions have occurred.
- [x] Notes have been documented
- [x] Dev tickets have been written for prioritized improvements

**Tasks:**

- [x] Schedule 1 hr sync
- [x] Walk through & discuss enhancement requests
- [x] Discuss relative priority to issues already in #2930
- [x] Discuss whether there's still a need for change request process as documented by notes in #1662 
- [x] Discuss #960
- [x] Prioritize enhancement requests
- [x] Write dev tickets

**Supporting Documentation:**

- [Mural](https://app.mural.co/t/raft2792/m/raft2792/1720460304271/b1de09b0efbfd35bb9f72063d4162ccd20a17d25?sender=uf443e00cb4626b8bec157528): Categorizing the requests and feedback below for talking points
- [Gitbook Notes](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/2910-admin-experience-improvements)

**Comment by ADPennington** [comment]
@reitermb Is this a good ticket to capture notes on OFA's suggestions for DAC enhancements, including those recommended from DIGIT? or is this focused on admin experience?

**Comment by reitermb** [comment]
> @reitermb Is this a good ticket to capture notes on OFA's suggestions for DAC enhancements, including those recommended from DIGIT? or is this focused on admin experience? 

Definitely! Depending on the specific enhancements we might end up moving certain things into tickets to sort between different use cases but at the moment this ticket is all things sys admin experience / digit users in DAC / other potentially useful app health monitoring workflow opportunities

**Comment by ADPennington** [comment]
jotting down a few pieces of feedback based on digit syncs:

- data submission email may be more useful if it mentions the file processing status
- data submission email "successfully submitted" terminology may be misleading (maybe first bullet could address this)
- data files summary column on data files page in DAC is misleading/potentially inaccurate. for example: could say "rejected' but clicking the link may suggest a different status, like "accepted with errors". also, file status on submission history page (for STT users) may not match the file status in DAC (making it difficult to clarify for STT users who inquire). related: digit users cannot see the submission history page on the frontend
- a lot of latency when clicking the parsing errors column on the data files page 
- being able to filter the data files page by submission date would be useful
- we can filter by file version, but is it also possible to filter by most recent file version, since the version number can vary by stt, fiscal period, and section?

**Comment by ADPennington** [comment]
more feedback from digit as of 6/3/2024:

- the data submitter's email address listed in the data file metadata should open in outlook instead of the user's profile
- TANF section 3 for states and territories only needs to refine validation on total number of families such that the minimum range is >= 1.

**Comment by ADPennington** [comment]
6/6/2024 feedback from digit: 

- make fiscal period dropdown for data export multi-select.

**Comment by robgendron** [comment]
Update: Preparing for research session
Next: Research session tomorrow (DIGIT & Alex)
Points Remaining: 4

**Comment by robgendron** [comment]
Update: Yun is back at work to schedule follow-up

**Comment by victoriaatraft** [comment]
- Follow on meeting to be schedule for Wednesday July 17 at 1PM ET, to add Caroline
- From UX Sync: UX to Create Research Synthesis To Address Personas
- Several spin off tickets that are in WIP:

- #3068 
- #3074 
- #3075 
- #3076 
- #3077 
- #3087 
- #3089 
- #1337 
- #3090 
- #3092
- #1131 
- #3093 
- #3094 
- #3059 
- #3096
- #3102   
- #2561

**Comment by robgendron** [comment]
Writing dev tickets - aiming for EOD.

**Comment by victoriaatraft** [comment]
Tickets have been created above as a framework for notes and moving on to the synthesis #3078 
@robgendron
