### ISSUE TITLE
As a user, I want to know this is an ACF Site by seeing their color palette [override USWDS color palette with ACF color palette]

### ISSUE THREAD

**Issue by hilvitzs** [raft-tech/TANF-app#294]
**Description:**
The color palette from USWDS needs to be overridden by the ACF color palette. After discussions, it was decided that getting the color palette set up will be easier and more beneficial in the long run than overriding the color palette with scss variables. This work will be for both dev and design and will require finding what variables are correlated to what elements as documentation for USWDS color palette work is not great.

**Acceptance Criteria:** 

- [ ] Colors are correct on site using USWDS tokens and not scss variables 
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [ ] Remove scss variables
- [ ] Research what uswds theme variables correlate to which colors
- [ ] Decide what colors are actually necessary from the ACF palette
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- The decision to override the color palette came from a meeting between Laura, Christine, Miles and Spencer about the future of styling work for the ACF project. It was okayed as a separate issue by Lauren on 9/25.

**Supporting Documentation:**
- [USWDS Color Docs](https://designsystem.digital.gov/design-tokens/color/overview/)
- [ACF Color Palette](https://www.acf.hhs.gov/digital-toolbox/visuals/visual-style-guide)

**Comment by reitermb** [comment]
Removing R&D label as this is a purely front-end ticket

**Comment by valcollignon** [comment]
moved to v2 after speaking with @ADPennington

**Comment by valcollignon** [comment]
Not a priority. Added techdebt label and changed to V4 per backlog refinement 1.4.21
CC: @ADPennington @lfrohlich @ttran-hub

**Comment by robgendron** [comment]
@ADPennington @lfrohlich is this still needed?

**Comment by robgendron** [comment]
Deemed closed by team.
