### ISSUE TITLE
Spike - remove sleep from zap scanner

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2946]
**Description:**
Follow on of technical debt introduced in #2768 and #2939. We have added some "magic" sleep of 5 minutes without understanding what background state results in the EOF failure state.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Fully understand origin of EOF
- [ ] Have passing scan pipeline
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Grab result from target to verify upload success
- [ ] TBD
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

We have a working solution and didn't want to scope-creep here. Perhaps try a different executor or moving off the circleci env causing our issue here.

**Supporting Documentation:**

**Open Questions:**
What is origin of EOF?

**Comment by robgendron** [comment]
Finishing time box period this week, then will pair with greater Dev team with mark down reflecting discovery results.

**Comment by elipe17** [comment]
Closing with no resolution. Attached is the MD that lists what was tried and what other options might still exist to remedy the issue.
[zap_trials.md](https://github.com/user-attachments/files/15536337/zap_trials.md)
