### ISSUE TITLE
As tech lead, I need the STT filter for search_indexes to be updated

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2950]
**Description:**

Follow-on to #2908/#2915

Currently, the STT filter for `search_indexes` appears as a long list of 129 STTs (see below). 
![2950](https://github.com/raft-tech/TANF-app/assets/63075587/5a388a6a-e8b1-4341-ad03-a91a83642a74)

- some STTs do not submit certain types of records (e.g. tribal STTs only submit tribal records), so the filter list could be much shorter. 
- the filter would also be more useful as a combobox, where OFA staff can choose multiple STTs for inclusion in CSV exports. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] list of STTs to filter by includes only STTs that submit those record types (e.g. tribal STTs are not needed in the list for TANF and SSP record types)
- [ ] STTFilter is a combobox with multi-select capabilities
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update HTML template to a combination box 
- [ ] Update lookups function in the STTFilter class to address #1 AC 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- Django doesn't have content to support this, Mo has experience with it. 
- Might already have updated template. 

**Supporting Documentation:**

NA 

**Open Questions:**

NA

**Comment by raftmsohani** [comment]
@ADPennington : since the admin page is accessed by admin, and filter is per, not sure how we can limit the filters

**Comment by robgendron** [comment]
4 points remaining.

**Comment by robgendron** [comment]
Further guidance is needed, 3 points remaining.

**Comment by robgendron** [comment]
Possible solution - 2 points remaining to implement.

**Comment by raftmsohani** [comment]
This ticket is blocked.

Have implemented the SST list filter to only include the relevant STTs (so this is done). However, when tried to add muti-selection, realized that with django-508 package changes for admin filters, the scripts are not working properly. (Will create a bug ticket for this) 

There is a work-around to do an inline script that can fix the STT filters, but suggestion is to resolve the issue from the source.
