### ISSUE TITLE
As a user, I want quality issues to be caught prior to the release of a feature (Design QA)

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#296]
**Problem Statement and Justification:** 

Due to the complex nature of developing a newly designed feature, certain specifications such as accessibility, content, and mobile behavior can lead to usability errors that can become painful to users if not caught prior to release. A series of quality checks can help catch some of these unforeseen errors before users find them in production.

**AC:** 
   - [ ] TBD
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

**Tasks**
- [ ] Document procedure to check accessibility
- [ ] Document procedure to check content
- [ ] Document procedure to check screen sizes and browsers behaviors

**Inspiration**
https://saltywebdesign.com/quality-assurance-checklist/

**DoD**
- [ ] Documentation has been shared with the PO and team for feedback
- [ ] @cmajel has reviewed and signed off
- [ ] @lfrohlich has reviewed and signed off

**Deliverables**
Design QA Procedure: (Google Doc Link)
