### ISSUE TITLE
As a engineer I need to replace bash script with task file for local dev

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2960]
**Description:**
Dev is using bash script file ```commands.sh``` to run development commands such as starting backend/frontend app, start bash in docker instance, etc.
Some of the commands in this bash file are throwing error and are not declarative. Taskfile wraps the commands and is more declarative.

**Acceptance Criteria:** 

- [ ] All steps/commands in ```commands.sh``` are available using task file
- [ ] Commands for the followings are available:
      - Start backend app
      - Start frontend app
      - Start backend/frontend together
      - Backend test with command line options
      - Frontend test with command line options
      - Run linting on changed files
      - Run lint check on all files
      - Run pgadmin container with access to database and which can be accessed on browser
      - help command to list all available commands with description
      - Clean up DB and start backend with a fresh database
- [ ] Follow similar approach as Taskfile developed for [django-508 repo](https://github.com/raft-tech/django-admin-508/pull/29)
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Develop a Taskfile with all commands in commands.sh script + listed commands in ACs
- [ ] Tests all developed commands
- [ ] Delete ```commands.sh```
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documents:**

- [Taskfile](https://taskfile.dev)

**Comment by robgendron** [comment]
#2491 is related - look to combine.

**Comment by robgendron** [comment]
@raftmsohani please provide refinement.

**Comment by raftmsohani** [comment]
I have decided not to delete commands.sh for now just in case someone is using it
