### ISSUE TITLE
As tech lead, I want a database seed implemented for testing

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#2965]
**Description:**
Given our occasional setbacks resulting from database inconsistencies that result in deployment failures that back up our release schedules, we should mitigate this with more thorough testing.

**Acceptance Criteria:** 

- [x] We have a maintainable and extensible toolset
- [ ] Seeding a database is performant ( sub hour )
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Create a tool/mechanism for generating "random" and internally consistent data
- [x] #3168
- [x] Tool will "fuzz" or generate out of range values to intentionally create issues [ stretch ]
- [ ] #3175
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

- Can we work with Alex to scrub PII from the prod postgres dataset?
- How can this be integrated into unit/integration tests? Pipelines?
- What drift exists between postgres migrations and ES documents? Is that prone to human error?
- Can we leverage co-pilot or other AI for generation?

**Comment by jtimpe** [comment]
A basic implementation of a random record generator is included here - https://github.com/raft-tech/TANF-app/pull/2881/files#diff-ce520f958d18ac5092cb7ab4baa305d5cf3d72a5ee1e00f93020334fb83fa92b

**Comment by reitermb** [comment]
Pushed back slightly to walk on P5 work
