### ISSUE TITLE
Unify Duplicate Detection Across Program Types

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#2966]
**Description:**
- #2795 introduced updates to the cat4 validation process that allowed for duplicate and partial duplicate record detection for TANF sections 1 - 4. After a brief discussion with Alex, it seems that the logic for exact and partial duplicate record detection will be consistent across all program types. Therefore, we need to introduce a minimal set of changes to `duplicate_manager.py` to accommodate the remaining program types.

- [Duplicate detection criteria](https://hackmd.io/Q4jjJlBNRbuHxEjZbPK37A?view#TANF-Section-3).

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Duplicate detection logic is applied consistently to TANF, SSP, and Tribal TANF files.
- [ ] Test coverage added for all program types
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update `duplicate_manager.py` to be program type agnostic. This should be as easy as updating the functions that rely on `RecordType` to only require the record number from the `RecordType` field. That is, the appropriate functions should only need to consume `1` instead of `T1`/`M1`.
- [ ] Add unit tests to `test_case_consistency.py` for the remaining program types
- [ ] Add integration tests to `test_parse.py` for the remaining program types
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

N/A

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

N/A

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

N/A

**Comment by elipe17** [comment]
This should have closed when the PR merged. Closing manually.
