### ISSUE TITLE
[Research Spike] New Reporting Requirements Kickoff & Ideation

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2971]
**Description:**

Kicks off #2929 scoping and related research/ideation

**AC:**

- [x] Kickoff sync(s) have occurred
- [x] Raft team has documented: 
   - [x] All new data that will be collected to support FRA changes
   - [ ] Which strategy (called out in the dear colleague letter) is favored by OFA
   - [ ] Whether OFA has a data collection solution in mind yet
- [ ] Follow-on research & design tickets for #2929 are refined

**Tasks:**

- [ ] Begin conversations on where FRA planning has gone over the last 6 months
- [ ] Document updates on scope/strategy of FRA changes
- [ ] Capture other notes / related ideation 
- [ ] Update epic work accordingly 

**Supporting Documentation:**

- [Dear Colleague Letter on FRA requirements](https://www.acf.hhs.gov/ofa/policy-guidance/ofa-dear-colleague-letter-fiscal-responsibility-act-fra-2023)

**Comment by lfrohlich** [comment]
@lhuxraft  @reitermb  @victoriaatraft  should this be repurposed or refined?

**Comment by lhuxraft** [comment]
> @lhuxraft @reitermb @victoriaatraft should this be repurposed or refined?

Confirmed with @reitermb and @victoriaatraft that this ticket has been completed and should be closed out. Follow-on work can be tracked in #3267 and #3297
