### ISSUE TITLE
Spike - Investigate/resolve Webinspect medium findings for April 2024

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2975]
**Description:**

There are 3 medium findings in the April 2024 Webinspect scan located [here](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc={c9d41a72-bff8-4eba-b245-bb04ba265e12}&action=edit&wd=target%28Dev%20Notes.one%7C567fc274-f86b-0a48-901d-543bdc5250ac%2FWebsinspect%20April%202024%7Cdd600afd-52c7-4750-a8ea-ab6e4c941e5c%2F%29&wdorigin=703) :lock: one is related to the session cookie and has already been addressed. the other 2 needs review and potential remediation. If false positive, please document in raft's OneNote page linked above. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] 2nd medium finding reviewed and/or resolved
- [ ] 3rd medium finding reviewed and/or resolved
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
### 5/10/2024 update on checking if medium findings are reproducible:

1. Insecure Deployment: OpenSSL
  - webinspect recommendation was to check the openssl version on the server. OpenSSL 0.9.8 SSL/TLS users should upgrade to 0.9.8za or later. OpenSSL 1.0.0 SSL/TLS users should upgrade to 1.0.0m or later. OpenSSL 1.0.1 SSL/TLS users should upgrade to 1.0.1h or later
    -  result after checking version on backend: `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)` The issue appears to be a false positive. 

2. Insecure Transport: SSLv3/TLS Renegotiation Stream Injection
 - webinspect recommendation is to use openssl  to test connection renegotiation. the presumption is that if it fails, the server is vulnerable. 
   - result: The server employs TLS 1.3, which does not support the renegotiation feature available in older TLS versions [reference](https://wiki.openssl.org/index.php/TLS1.3#Renegotiation).  Manual testing with openssl verified that the server correctly rejects renegotiation attempts, consistent with TLS 1.3 standards. The issue appears to be a false positive.

**Comment by robgendron** [comment]
Alex deemed closed.
