### ISSUE TITLE
As a developer I want to test django-508 repo

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#2980]
**Description:**
The [django-508](https://github.com/raft-tech/django-admin-508) package doesn't have any tests. Tests should be written for that repo and they should be independent from the django-backend app.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Docker instance runs a django app and pulls django-508 as dependency
- [ ] Pytest runs on unit tests using docker instance
- [ ] Testing Checklist has ran and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Write at least one unit test for pytest and write a plan for future test development
- [ ] Develop a plan for testing ally requirements on this repo
- [ ] Write documentation on how to run tests
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

NA

**Comment by andrew-jameson** [comment]
Per standup 6/7, clarification is that this ticket will be to capture the system and infrastructure (including docker-compose) surrounding the work done in #3008 which will have the logical tests implemented and iterated.

**Comment by robgendron** [comment]
2 points remaining.

**Comment by andrew-jameson** [comment]
Merged as part of #3008
