### ISSUE TITLE
[Design Deliverable] Email spec for Admin Notification for stuck files

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2985]
**Description:**
Follows on from #831, delivers spec for sys admin notifications of files stuck in pending / other non-processing states

**AC:**

- [x] Internal Raft Review has occurred to ensure DoD standards and QA
- [x] Dev/Design sync has occurred; resulting tickets created
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Determine the right cadence for the system to check for stuck files
- [x] Mockup HTML template with the following data:  STT, Program Type, Fiscal Period, Section, Submission Date/time

**Deliverables:**
[TDP Email Templates](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/):
[#2985: Admin Notifiation for Stuck Data](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/admin-stuck-data-files.html)
[#2985: Admin Notifiation for Stuck Data with CTA](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/admin-stuck-data-files-button.html)

**Notes:**
- 15 minute threshold was a suggestion from Andrew. ~double the time we'd expect would be required to parse the largest data files

**Comment by reitermb** [comment]
Stub ticket, related to #2930

**Comment by reitermb** [comment]
A11y reviewed w/ @ttran-hub and @victoriaatraft on 6/26/2024

![image](https://github.com/raft-tech/TANF-app/assets/28515874/dfb7511a-2d81-4e48-82a6-c574b412df99)

**Comment by ttran-hub** [comment]
Thanks @reitermb @victoriaatraft! As discussed: to help with managing the outstanding pending file, if possible, include the dynamic links to the pending source data files in the Django or STT submission history.
The a11y review for the pending email layout template lgtm 🚀.

**Comment by robgendron** [comment]
Awaiting content feedback and may need some dev input, 1 point remaining.

**Comment by reitermb** [comment]
Capturing notes from UX sync:
- Add **{Section Name}** variable to subject line and body (position in body text is pictured in UX sync notes)
- Create a version with a "View file in Django Admin Console" button below body text 

cc @victoriaatraft

**Comment by victoriaatraft** [comment]
[like]  Victoria Amoroso reacted to your message:
________________________________

**Comment by victoriaatraft** [comment]
@reitermb changes made and ready for your review :)

**Comment by robgendron** [comment]
Finishing review, will be in QASP sooon.

**Comment by victoriaatraft** [comment]
@ADPennington two versions are ready for review, especially content. There was a suggestion to remove STT from the subject line in the template due to cases where the STT names are very long. 
The version with the CTA button may still require you to login instead of viewing the files directly like the button implies. And one last idea, let me know if a bulleted format instead of a paragraph form would be easier to read, happy to adjust.

[TDP Email Templates](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/):

- [#2985: Admin Notifiation for Stuck Data](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/admin-stuck-data-files.html)
- [#2985: Admin Notifiation for Stuck Data with CTA](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/admin-stuck-data-files-button.html)

**Comment by reitermb** [comment]
![image](https://github.com/user-attachments/assets/6bd8b01c-e243-484d-b045-64e0c7106eda)
Notes for re-arrangement of subject line—check what replacement tags are called here & how they'll populate

- UX sync 7/15/2024

**Comment by ADPennington** [comment]
@lfrohlich @ttran-hub @reitermb @victoriaatraft @robgendron is this ticket pending me? Sorry i may have lost track.

**Comment by victoriaatraft** [comment]
@ADPennington I am currently working my way through the email templates and updating the content reflect @reitermb screenshot today :) 
![Screenshot 2024-08-23 at 8 23 15 AM](https://github.com/user-attachments/assets/317f07c8-75eb-4cae-bdcf-31530ce8b4e5)

**Comment by reitermb** [comment]
Thanks for the final pass on this @victoriaatraft 

@ADPennington should be good to go for your pass!

**Comment by ADPennington** [comment]
@victoriaatraft @reitermb just a couple of questions/comments:

- will this email be delivered every time a file gets stuck? just wondering for the next bullet's language (i.e. `file` vs `file(s)`)
- for the subject line can we construct it as follows for dev: `{Section} file for {Fiscal Year, Quarter} stuck in {file status} state`
- will this email include a link to the datafiles page that's already filtered to "pending" files? 
- have the design mockups passed a11y testing?

**Comment by victoriaatraft** [comment]
@ADPennington 

@victoriaatraft @reitermb just a couple of questions/comments:

> * will this email be delivered every time a file gets stuck? just wondering for the next bullet's language (i.e. `file` vs `file(s)`)

@reitermb correct me if i'm wrong (and any on the following below) but I believe it's every time a file gets stuck
> * for the subject line can we construct it as follows for dev: `{Section} file for {Fiscal Year, Quarter} stuck in {file status} state`

Yes

> * will this email include a link to the datafiles page that's already filtered to "pending" files?

I believe there was a caveat to the template with the call to action button: view file in django admin console. in that you have to be already logged in to be taken to the admin console. 

> * have the design mockups passed a11y testing?

Yes

**Comment by reitermb** [comment]
UX to add "file" to subject line as requested by Alex, update the screenshot here

cc @ADPennington

**Comment by victoriaatraft** [comment]
<img width="880" alt="Screenshot 2024-08-26 at 9 21 37 AM" src="https://github.com/user-attachments/assets/fa388a44-2724-4937-aa68-440f87a6e021">
<img width="843" alt="Screenshot 2024-08-26 at 9 22 03 AM" src="https://github.com/user-attachments/assets/afcb7e27-44ca-4f29-90c7-6fbc910957eb">

@ADPennington if the single word of "state" bothers you in the subject line, we can remove. Granted the subject line is responsive given the screen size. In design, we usually call single words on a line an widow or orphan. :)

**Comment by ADPennington** [comment]
> <img alt="Screenshot 2024-08-26 at 9 21 37 AM" width="880" src="https://private-user-images.githubusercontent.com/106103383/361503098-fa388a44-2724-4937-aa68-440f87a6e021.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTk2ODksIm5iZiI6MTcyNDY5OTM4OSwicGF0aCI6Ii8xMDYxMDMzODMvMzYxNTAzMDk4LWZhMzg4YTQ0LTI3MjQtNDkzNy1hYTY4LTQ0MGY4N2E2ZTAyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxOTA5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTRlNjgzNDAxNWQwZjk0OTczMGQ4YmNkZWEwODNhZDAwMDAyODE2MTg5M2NlZGU2MGZkODMwYzFjZTE3OTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ACeqrZljNArgWPCHrTJq-3D5ut2EA227D1Q98WjOitw"> <img alt="Screenshot 2024-08-26 at 9 22 03 AM" width="843" src="https://private-user-images.githubusercontent.com/106103383/361503202-afcb7e27-44ca-4f29-90c7-6fbc910957eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTk2ODksIm5iZiI6MTcyNDY5OTM4OSwicGF0aCI6Ii8xMDYxMDMzODMvMzYxNTAzMjAyLWFmY2I3ZTI3LTQ0Y2EtNGYyOS05MGM3LTZmYmM5MTA5NTdlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxOTA5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGRiMTVjMmQ0YzlmNWY4ZjgwOWJiY2JjMjUwOWM2ZTE2YmRiYTg0MjhkZDE0Njg5YjM1ODIzMWM1NGVlOGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iLxMnSScRktlxIImbiYt0IBJCbc1I2GtNpz3sFhlSEk">
> @ADPennington if the single word of "state" bothers you in the subject line, we can remove. Granted the subject line is responsive given the screen size. In design, we usually call single words on a line an widow or orphan. :)

@victoriaatraft @reitermb we can keep "state" :). One minor suggestion, if it is possible to include the file id number in the body of this e-mail (especially in the event that there is no button), this would be great nice-to-have. This is qasp-approved from my perspective. ✅  cc: @ttran-hub @lfrohlich

**Comment by victoriaatraft** [comment]
@ADPennington thank you! We have an internal sync in a few I can check on if we can include the file ID number. I'll keep you posted and make updates accordingly. Thank you!

Update: We can include the file ID number. Andrew made note to do the lighter lift on the cadences of how often these emails will be sent (one email per file or list of files)

**Comment by victoriaatraft** [comment]
<img width="841" alt="fileid with cta" src="https://github.com/user-attachments/assets/ed47bb2f-c48d-4b7f-a6d5-077bacb2035f">
<img width="814" alt="fileid without cta" src="https://github.com/user-attachments/assets/b04a2ec8-1c6b-422e-b18b-d78a45c4acef">
