### ISSUE TITLE
Sys-admin notifications for files stuck in processing

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#2990]
**Description:**
Follows on from #831 and #2985. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Notification occurs if a newly submitted file has been in pending state for 1+ hours
- [x] All system admin users receive this notification
- [x] Notification content must include:
   - [x] STT, Program Type, Fiscal Period, Section Name, Submission Date/time
   - [x] Dynamic link that passes data file ID to the django URL string
- [x] Confirm these email events should be captured in logs
- [ ] Notification content matches [spec](url)
- [x] All sys-admin users receive the notification
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create notification logic (timing and user group to be notified) (e.g., `datafile_submitted_pending_email_task.delay(minutes=60)`)
- [ ] Implement notification template
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Original comment IDing the need for this notification](https://github.com/raft-tech/TANF-app/pull/2959#pullrequestreview-2038865291)

**Open Questions:**
- Where do we land on priority and preference between sys-admin notifications and user-facing status changes / notifications for this?
- What other work can we prioritize that will reduce or eliminate the need for this notification? 
   - https://github.com/raft-tech/TANF-app/issues/2978 — Reparse files

**Comment by reitermb** [comment]
cc @ADPennington for ticket visibility

**Comment by andrew-jameson** [comment]
Discussed with UX during office hours 7/3, will need a corresponding backend ticket, to be discussed with Alex Friday via #3026

**Comment by robgendron** [comment]
Will be refined once design ticket (#2985) is through QASP.

**Comment by andrew-jameson** [comment]
@ADPennington Has mentioned that whichever implementation is lightest works -- per hour cron w/ list or per file delay. An email per singular file is acceptable -- ideally we wouldn't email 4 times if all files from a submission quarter all end up in pending.

**Comment by jtimpe** [comment]
* pending for 1+ hours doesn't necessarily mean parsing takes 1+ hours - worker could have died (timeouts may not catch all cases)
* why would the worker die but not throw an exception? memory?
* "sweep" approach can group by submission time
* callback on error, callback on success?
* per submission meta model -> how does this interface w/ reparse meta model and datafile summary? overlap?
* cron job to call management command on the backend? or circleci cron?
* alert when celery dies due to oom (not max tasks per child, but if we actually run out of mem and the worker dies)? sentry? prometheus?

**Comment by reitermb** [comment]
Miles & Victoria to review (see Jan's message)
