### ISSUE TITLE
As tech lead, I need the sftp file transfer feature to be deprecated

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2991]
**Description:**
At the end of May 2024, the legacy system (TDRS) will be decommissioned. This means that data files from STTs will no longer be processed in-parallel with processing in TDP, so the file transfer feature can be disabled. 

**Acceptance Criteria:** 

- [x] files submitted through TDP are not transferred to ACFTitan server. 
- [ ] file transfer env vars are no longer present in the codebase, circleci, or backend environments
- [x] backend logs do not show evidence of file transfer attempts. 
- [x] all other existing TDP features are functioning as expected. 
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Disable sftp file upload 
- [x] Delete sftp_task, remove the task and delete all references including _sftp_task.upload_ in data_file.views
- [x] Delete any associated upload task test (test_file_upload)
- [ ] ~~Delete the _LegacyFileTransfer_ model, and create migration to remove the data from app (Question: should we keep this model and all the history?)~~
- [x] Remove associated lines in readme files (File-transfer-TDRS), etc
- [x] delete _ACFTITAN_SFTP_PYTEST_ environment variable
- [x] delete all sftp_config environment variables (ACF_TITAN_XYZ) in settings
- [x] delete python _pytest_sftpserver_ package and  update the pipfile lock
- [ ] Delete ACF Titan keys
- [x] Delete the line in secret_key_rotation_steps.py for _ACF Titan server keys_
- [x] Delete ACFTITAN keys from deploy-backend.sh
- [ ] Delete related env vars from backend and frontend docker-compose files   
- [x] Run Testing Checklist and confirm all tests pass
- [x] Test Case: Upload file and check to see if it fails 

**Notes:**

- Discussion with Alex and the dev team, we have decided to keep the LegacyFileTransfer model/table and create a follow up ticket

**Open Questions:**

- When should we delete the LegacyFileTransfer model?

**Comment by robgendron** [comment]
@mhsraft will provide refinement details

**Comment by robgendron** [comment]
1 point remaining.
