### ISSUE TITLE
[Design Deliverable] TDP Poster for summer 2024 conferences

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#3000]
**Description:**

Lauren and Thomas will have a table at a tribal TANF conference on June 4 and was thinking it would be great to have a poster/visual advertising TDP. We have a few TANF meetings this summer that we could re-use it at. We are looking for a design that we could print. I'm thinking it could have the TDP logo, some screenshots showing key functionality  (that is unlikely to change) and a QR code to sign up. Also open to other ideas! The poster could either be 21” x 21” if we want to get it printed through the conference (if it's not too late) or another size. 

**Related User Stories:**

- As a potential TDP user, I want to learn about TDP and know how to access it. 

**Recommended pa11y actions:**
- [x] Poster should be accessible (e.g. contrasting colors)

**AC:**
- [x] QR code leads to the TDP home page https://tanfdata.acf.hhs.gov/ 
- [x] Poster Contains Content from supporting documentation
- [x] Key functionality: TDP Home Page, Data Files, Submission History
- [x] Reviewed by Lauren
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft design in Figma

**Supporting Documentation & Design Deliverables:**

- [Link to Working Figma File](https://www.figma.com/design/c6lXUgqyIXbCZYzKYEaTD1/TDP-Poster?node-id=0%3A1&t=CQnLDLSelRUrg7Dk-1)
- [TANF Data Portal Poster.pdf](https://github.com/raft-tech/TANF-app/files/15473743/TANF.Data.Portal.Poster.pdf)
- Dev-Ready Design folder PDF

**Content for Poster**

``The vision for TDP is to allow grantees to easily submit accurate data and be confident that they have fulfilled their reporting requirements. This reduces the burden on all users, improves data quality, inform better policy and programs, and ultimately helps low-income families.``

![qrcode_tanfdata acf hhs gov](https://github.com/raft-tech/TANF-app/assets/106103383/eeb202b9-c47f-46ee-8ae7-aa8ae50e08e8)
![TDP_Logo_Text_2 00-01](https://github.com/raft-tech/TANF-app/assets/106103383/2120ac93-51ee-4c31-8abb-e9f9bfbeec8d)

**Comment by victoriaatraft** [comment]
Hi @lfrohlich the poster ready for you review: [Poster Option 1.pdf](https://github.com/raft-tech/TANF-app/files/15439793/Poster.Option.1.pdf). We added in the Knowledge Center screenshot to add balance to the other images on the poster, an additional logo and captions to the images taken from the Knowledge Center and an email as an additional contact source. You may also view it in the [Figma link](https://www.figma.com/design/c6lXUgqyIXbCZYzKYEaTD1/TDP-Poster?node-id=9-10&t=QjjFocsQvXR6lSd4-1). Happy to work out more iterations based on your feedback.

**Comment by lfrohlich** [comment]
Thanks @victoriaatraft ! Looks really good. A few comments: 
1. Could you make the TDP logo bigger and the vision smaller? 
2. I'd like to mention error reports on the submission history page. Something like: 

> Submission History allows you to access all versions of data files previously submitted for a given quarter via TDP, along with reader-friendly error reports. 

4. For the knowledge center, can you revise to something like: 

> The TDP Knowledge Center contains guides and resources to help you use TDP, from account creation to data submission

**Comment by lfrohlich** [comment]
Accepted, accepted with errors, and rejected in screenshot please. Also change North Caroline to "TANF Program"

**Comment by victoriaatraft** [comment]
@lfrohlich final pdf and working file is attached under supporting documentation & design deliverables.

**Comment by lfrohlich** [comment]
This was completed May 29
