### ISSUE TITLE
As a software engineer, I want to be able to test django-admin-508

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#3008]
**Description:**
The [django-admin-508](https://github.com/raft-tech/django-admin-508) is a dependency repo, managed by Raft to conform with the accessibility requirements of TANF project. Currently, to test functionality and changes, we will need to point the backend app to the repo and manually test the changes.

This ticket aim to create the foundation for testing the repo independent from the backend application and write a couple of test suites and examples as a base for further work. Additionally, it should clean up any clear unused logic and code.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Need to be able to test changes independent from the backend 
- [ ] Documentation is created for all the testing and releasing steps 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Need to develop test within Django
- [ ] Create documentation - testing and release steps 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- A11y review post-508 release (potential separate ticket)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://github.com/raft-tech/django-admin-508 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

NA

**Comment by robgendron** [comment]
If unresolved, will block other work within DAC.

**Comment by robgendron** [comment]
5 points remaining.

**Comment by robgendron** [comment]
3 points remaining.

**Comment by robgendron** [comment]
2 points remaining.

**Comment by andrew-jameson** [comment]
[PR](https://github.com/raft-tech/django-admin-508/pull/29) is located in the 508 repo, so it was not linked. Will close once reviewed/merged.
