### ISSUE TITLE
(Internal) As a tadpole, I want to understand how my work supports the roadmap

### ISSUE THREAD

**Issue by matthewjdoty** [raft-tech/TANF-app#301]
Description: 
The product team needs a clear vision of which user stories (existing or creating new ones) need to be completed to deliver on the [OFA MVP](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592336604317/61159efd030645a74c267130ea19b2083f87dd09) ~ Sprint 12 . 

AC: 
- [x] Workshop to create comprehensive list of epics and high-level stories to deliver OFA MVP (note: this will not be an exhaustive list of user stories but rather provide the product team an understanding of how we will deliver on MVP) 
- [x] Create a follow-up issue to migrate user stories from milestone path that is created on roadmap for OFA MVP to ZenHub. #327

Tasks
- [x] Shubhi + Lauren + Alex P session on KPI/milestones (thinking about 3 sprints chunks) and how this achieves the OFA MVP
- [x] Workshop (possibly story writing workshop) with TDP product team to delve deep into the roadmap to review existing one or create new ones/KPIs that need to be delivered for OFA MVP -- what stories are we missing? Mark stories that we think would be ATO/OCIO dependent
- [x] Share what will be delivered in high level user stories with OCIO to ensure we are not missing anything that is necessary for ATO #1 for OFA MVP 
- [x] Evaluate to restructure backlog refinement sessions (@shubhi-raft create a separate issue to track this) 

Deliverable(s):
- [User story workshop](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1603716308179/3fc5724de4b66be950fc453a966754f9b3bd58ea)  
- [Updated roadmap](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592336604317/61159efd030645a74c267130ea19b2083f87dd09)

**Comment by shubhi-raft** [comment]
@lfrohlich Are you planning to share the outcome of story mapping workshop (updated roadmap - #327) at IPT or should we schedule another meeting w/ OCIO to ensure we are not missing any epics to receive ATO #1.

**Comment by shubhi-raft** [comment]
We plan to demo this during backlog refinement meeting on Nov 4, time boxed to 15 mins.

**Comment by lfrohlich** [comment]
This was shared with OCIO. We should make sure this is shared back with the team during Sprint Planning.
