### ISSUE TITLE
Outdated info banner for submission history results with data processed before 5/31/24

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3014]
**Description:**

This ticket delivers an info banner appearing contextually at the top of any submission history page containing error reports generated prior to May 31 2024.

Original description:
```The ATO for the legacy system (TDRS) is set to expire at the end of May 2024. This means that files will no longer be processed thru TDRS and TDRS feedback reports will not be sent (as of 5/31/2024). 

To-date, STTs have not been relying on the TDP-generated feedback reports, primarily because these feedback reports have changed overtime as the parsing and validation engine has been refined. To help mitigate confusion, OFA recommends wiping the feedback-related columns in the submission history for files submitted prior to 5/31/2024.  
```

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Banner appears on submission history if 1 or more files are present for viewed quarter that were submitted prior to May 31, 2024
- [x] Banner does not appear if a given quarter doesn't have data submitted before May 31 2024 
- [x] Language matches spec "```Please note that error reports and submission history content for files submitted prior to
May 31, 2024 may be outdated. Please resubmit to get access to updated information.```"
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create logic to check for submission history entries made before 5/31/24
- [ ] Implement info banner when that logic returns true
- [ ] Tag for a11y review
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- This ticket is particularly aimed at smoothing the transition for Tribes who aren't used to having the level of data feedback submission history provides. Requesting that STTs simply ignore inaccurate older data has not been particularly successful at alleviating concerns.

**Supporting Documentation:**
[Figma](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8993-259&t=OQgW2zgCgvJaKsFL-1)

![image](https://github.com/user-attachments/assets/a1040ef3-f4c7-4285-b72c-1333fd8949d9)

**Comment by ADPennington** [comment]
@reitermb can you add this ticket to the next UX sync agenda? I think we could use suggestions and a design mockup before this can go into refinement.

**Comment by robgendron** [comment]
UX will be providing AC and Screenshots to support.

**Comment by robgendron** [comment]
Scheduling one-off meeting to address this @andrew-jameson

**Comment by victoriaatraft** [comment]
Removed WIP was addressed on May 30 at UX sync AC and screenshots provided in description. @ADPennington @robgendron

**Comment by robgendron** [comment]
Alex - Need to understand or end user uses this. Add to office hours next week (7/22). Parsing may fix this.

**Comment by andrew-jameson** [comment]
Dev notes

- frontend only change? Significantly easier lift
- status set to pending vs n/a -> high lift
- datafile model has "hidden/old" field we can query
- why not let people have old error reports? transparency vs questions on old files

**Comment by robgendron** [comment]
OFA will have an internal conversation on this, will bring findings to the following office hours.

**Comment by robgendron** [comment]
Bring into the next UX Sync @victoriaatraft @reitermb

**Comment by ADPennington** [comment]
@andrew-jameson @robgendron this ticket will be re-scoped by UX team for a banner notification on submission history for files submitted prior to end of May 2024. assigning ux team for scoping.

**Comment by reitermb** [comment]
cc @ADPennington 

Added in final refinements!

**Comment by vlasse86** [comment]
Deployed to Raft 11/8/24

**Comment by lhuxraft** [comment]
11/13/2024: Waiting for UX to review, Victoria taking a look this morning
