### ISSUE TITLE
[Design Deliverable] Updated KC Release Notes & Update Indicator FAQ

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3021]
**Description:**

Delivers updated release notes to the KC homepage & a new FAQ item with guidance on the update indicator 

**AC:**

- [ ] Release notes include:
   - [ ] New Submission History statuses / guidance
   - [ ] Error Reports no longer in beta
   - [ ] New FAQ on update indicator
- [ ] FAQ page include new item on update indicator
- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft release notes content
- [x] Draft FAQ content
- [x] Tag Lauren & Alex in GitBook draft
- [ ] Stage in Test environment
- [ ] a11y review
- [ ] Open/Merge PR

**Supporting Documentation:**

- [Gitbooks Draft]()

**Comment by robgendron** [comment]
2 points remaining.

**Comment by reitermb** [comment]
@robgendron Ready for raft review! 
https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/knowledge-center-drafts/release-notes-and-faq-updates

For context on where the content before / after the horizontal line will go:
TDP Knowledge Center Homepage: https://reitermb.github.io/Test/knowledge-center/index.html
&
FAQ page: https://reitermb.github.io/Test/knowledge-center/faq.html

**Comment by reitermb** [comment]
@lfrohlich @ADPennington 

Should be good to go for QASP content review: https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/knowledge-center-drafts/release-notes-and-faq-updates

One tangential question, has the new dear colleague letter been finalized or is that still pending?

**Comment by lfrohlich** [comment]
Still pending

**Comment by lfrohlich** [comment]
Added some comments to GItBook

**Comment by ADPennington** [comment]
@reitermb i reviewed and made some minor edits and suggestions. back over to UX.

**Comment by reitermb** [comment]
> @reitermb i reviewed and made some minor edits and suggestions. back over to UX.

Thanks Alex—updated accordingly! 

I made one minor tweak from inline numbering to an actual number list for the FAQ release note change. It looks a little funky in GitBook formatting but should look right once adapted to HTML!

Proceeding with the PR/scheduling an a11y review with @ttran-hub
