### ISSUE TITLE
Spike - Continue Zap Sleep Investigation

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3022]
**Description:**
This is a follow on task to finish the investigation from #2946 into why we need to insert a 4 minute sleep to ensure the nightly owasp scan successfully executes and uploads it's results to the DAC.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Ideally the removal of the sleep from the pipeline
- [ ] If the sleep can't be removed, document any further findings as to why the sleep is necessary and what issue/issues it is "fixing".
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Continue investigation based on results and further tests outlined in: 
[zap_trials.md](https://github.com/user-attachments/files/15539031/zap_trials.md)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by robgendron** [comment]
A few more hours needed, aiming for EOW.

**Comment by raftmsohani** [comment]
The "cf" command is responding with 202 instead of 200, which means cloud.gov is receiving the request but not running it:

What I see when running the command in my local env:

<img width="1904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d7ff80d6cdb24058cac867e3425a4965e24c82f/Screenshot%202024-07-02%20at%2011.31.00%E2%80%AFAM.png" alt="Screenshot 2024-07-02 at 11.31.00 AM.png" />

What we see in circleci:

<img width="1904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2FwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9454a6eb2684971dfee396992f55492a4e554ad8/Screenshot%202024-07-02%20at%2011.34.35%E2%80%AFAM.png" alt="Screenshot 2024-07-02 at 11.34.35 AM.png" />

**Comment by robgendron** [comment]
Potential solution ID-ed, spinning up follow-on ticket. Notes & findings will be added to this ticket.

**Comment by raftmsohani** [comment]
The following is conclusion of investigation about EOF.

REASON: 

Hypothesis for the reason why we are receiving EOF:

Since we are performing the scan from circleci, cloud.gov considers it an external attack and rate limits the requests. After the scan is done (or probably in the middle of scan) the IP from circleci is blocked, delaying the action on requests. So when we try to call the ```cf``` commands after the zap scan, we receive 202, only accepting the command with no immediate response. Although we are receiving HTTP 202: ACCEPTED, It turns out the command does not run, causing an EOF and seeing the circleci step to fail. 

ACTIONS TAKEN
1. Tried to add a step with wait command as below:
```
while [[ $(cf curl "/v2/apps" -v | grep -c "HTTP/1.1 200") == 0 ]]; do
       echo "Waiting for the backend scan to complete..."
        sleep 240
done
```

Since the cf curl command runs first, the task will be scheduled and then it doesn't run the new command even after the wait. Tried to raise the wait time, and increased even to 600 seconds (10 minutes) but it still failed to receive 200 response. 

2. Ran the task + SSH

Logged in using SSH into circleci, then tried to run the CF command while scan was running. At first I could schedule the task, but when owasp scan was in middle the cf command stopped to work. However after scan was finished up, after after a couple of failures with cf schedule, the cf was producing _PANIC ERROR_. 

Since I could run the command after cf login, I thought it is because circleci is logged out. So I added another login step to circleci tasks before running cf task, but since cf is not available, it failed.

SOLUTION:

We keep the sleep command before running cf command.

NOTES:

The scan still runs and there is no impact on zap scanner.

**Comment by robgendron** [comment]
Anticipate Raft review EOD (Jul 5)

**Comment by raftmsohani** [comment]
To overcome this issue, we will need to somehow user two different IP addresses among scan job and CF command that should run afterwards. One solution is to add a proxy server for cf command request (cf command accept forward proxy server), however, creating the forward proxyserver is cumbersome.

**Comment by robgendron** [comment]
Update: Work is complete, no solution.
