### ISSUE TITLE
as STT approved user, I need my IP address whitelisted so i can access TDP

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3023]
**Description:**

An approved user for a tribal program in Alaska was blocked from accessing the website. They shared the screenshot below after trying to get to the home page:

<img width="332" alt="CCHITAforbidden" src="https://github.com/raft-tech/TANF-app/assets/63075587/b216cf98-3267-42ab-ad8b-10c1ea1988b5">

After reviewing the logs, it appears that the user was in a different location, and potentially on a mobile network (IPv6 is normally associated with mobile networks). The user did not confirm use of the mobile network but noted that they tried to access the system from a PC (this can be related to using wireless access point which grabs IPv6 instead IPv4 from the ISP). After discussion with dev, it was confirmed that this IP address is blocked, but does appear to be in the US. Therefore this should be whitelisted

![CCHITAforbiddenlogs](https://github.com/raft-tech/TANF-app/assets/63075587/002da2d4-65b0-4728-bbdc-4a05a0cf4d91)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] The IP address referenced above is whitelisted, so user can access TDP. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Revise the whitelisted IP and add the IP range in question
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- One idea is to design dynamic nginx routing using local redis that is in sync with a backend DB for holding IP addresses. This is a bit advanced and might need more work

**Comment by ADPennington** [comment]
@raftmsohani could use your help with refinement.

**Comment by robgendron** [comment]
Will spin up additional work after completion of the ticket.

**Comment by ADPennington** [comment]
@robgendron @raftmsohani -- we have a meeting on 6/19 with the user referenced in this ticket. can you share an update on the LOE getting this addressed in this sprint and which tickets in-progress would get pushed if we re-prioritized? cc: @lfrohlich @ttran-hub

**Comment by robgendron** [comment]
> @robgendron @raftmsohani -- we have a meeting on 6/19 with the user referenced in this ticket. can you share an update on the LOE getting this addressed in this sprint and which tickets in-progress would get pushed if we re-prioritized? cc: @lfrohlich @ttran-hub

@ADPennington bringing this ticket in and plan on completing by the end of the sprint. @raftmsohani and I discussed workload - no need to push/re-prioritize other tickets.
