### ISSUE TITLE
2897 follow-on for a11y-related enhancement 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3024]
**Description:**

#2897 introduces new guidance in the error report which is currently split across 2 cells to accommodate text formatting. @reitermb agrees with @jtimpe's suggestion to implement the following but remove the bolded text. 

![image](https://github.com/raft-tech/TANF-app/assets/63075587/f3f8da8f-e79b-4521-acf2-6657dfeae540)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] error report matches above spec without bold text
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
