### ISSUE TITLE
As an STT user, I need an accurate error report when I space-fill `COUNTY_FIPS_CODE` 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3025]
**Description:**
_Provide a brief background and justification for this issue_

When STTs submit records with space-filled value for `COUNTY_FIPS_CODE`, the following error appears in the logs:
```shell=
   2024-06-05T14:04:48.89-0400 [APP/PROC/WEB/0] ERR 2024-06-05 18:04:48,898 DEBUG fields.py::parse_value:L45 :  Field: 'COUNTY_FIPS_CODE' at position: [19, 22) is empty.
   2024-06-05T14:04:48.89-0400 [APP/PROC/WEB/0] ERR 2024-06-05 18:04:48,898 ERROR parse.py::manager_parse_line:L370 :  'NoneType' object has no attribute 'lstrip'
```

The error report associated with files like this yield incomplete and incorrect error messages (see below). In particular, 

- the report does not raise a cat 2 (out-of-range) error associated the `COUNTY_FIPS_CODE`
- the report raises cat 4 errors that are not correct (perhaps due to the fact that the T1 record with the space-filled county fips code is not parsed?)

![3025p1](https://github.com/raft-tech/TANF-app/assets/63075587/ce0873ee-a54d-4ecd-bec7-b30e84b815cd)

STT users are unable to make corrections based on this feedback. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] space-filled `COUNTY_FIPS_CODE` raises cat 2 error message in error report. 
- [x] T1 record associated with space-filled `COUNTY_FIPS_CODE`  is still parsed
- [x] cat 4 error message are not raised due to the space-filled `COUNTY_FIPS_CODE` 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] review use of lstrip with `COUNTY_FIPS_CODE` 
- [ ] resolve issue described
- [ ] tbd
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- test file: 
[lstrip-related-records_anon.txt](https://github.com/user-attachments/files/15633171/lstrip-related-records_anon.txt)

- error report associated with test file: 
[2024-Q2-Active Case Data_testfile.xlsx](https://github.com/user-attachments/files/15633355/2024-Q2-Active.Case.Data_testfile.xlsx)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by robgendron** [comment]
2 points remaining.

**Comment by robgendron** [comment]
1 point remaining.
