### ISSUE TITLE
Fix error report accessibility and worker termination issues with large STT files

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3026]
**Description:**
_Provide a brief background and justification for this issue_

Some STTs submit files that have 200K+ errors, which take a lot of time to process (and often get stuck in a "pending" state*). In scenarios where the processing is completed, the error report generated is not able to be downloaded. 

![3026p1](https://github.com/raft-tech/TANF-app/assets/63075587/248d2b1e-be4f-4874-98d1-d022f51622fe)

A review of the logs when clicking download shows something like the following:

```shell=
   2024-06-06T15:09:58.84-0400 [APP/PROC/WEB/0] ERR [2024-06-06 19:09:58 +0000] [14] [WARNING] Worker with pid 174 was terminated due to signal 9
   2024-06-06T15:09:58.85-0400 [APP/PROC/WEB/0] ERR [2024-06-06 19:09:58 +0000] [175] [INFO] Booting worker with pid: 175
```

Relatedly, OFA staff cannot feasibly support STTs who inquire about this because:
- in some cases the processing status captured in DAC is inconsistent (supporting documentation bullet # 2)
- accessing file-specific parsing errors from DAC takes a lot of time (when there are a lot of errors) and parsing error table is not filterable or exportable. 
- DIGIT team and sys admin groups do not have access to frontend error reports to attempt to reproduce the problem described. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] error reports can be accessed by STT users regardless of parser error count
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] identify root cause of worker termination
- [ ] resolve issue with access to error reports with lots of errors
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- *in reviewing the logs during processing, I've observed two types of elastic-related errors when the file is stuck: `elasticsearch.exceptions.ConnectionTimeout` and `elasticsearch.exceptions.TransportError: TransportError(429, '429 Too Many Requests /_bulk')` 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- test file: [SSP_active_anon.txt](https://github.com/user-attachments/files/15685928/SSP_active_anon.txt)

- ![3026p2](https://github.com/raft-tech/TANF-app/assets/63075587/8e4458ff-b32b-4e25-aaae-d5c3256933fc)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- is this a memory-related issue? 
- the legacy system (TDRS) logic was setup to stop processing after 500 errors were detected. This wasn't great because STTs wouldn't know what kinds of errors were detected. Should we consider a similar approach, where we stop processing after a certain point, but inform where in the file, processing stopped? 
- should system check for cat 3 errors if cat 2 error detected? 
- separate ticket needed to address easier access to parsing errors for OFA staff users (digit, sys admin, ofa admin)?

**Comment by andrew-jameson** [comment]
@ADPennington can we talk about pending files generally on Friday 7/5? It came up discussing #2985 and I wanted to dive into this related ticket as well. I'll send you a calendar invite but we can move

cc @victoriaatraft

**Comment by ADPennington** [comment]
A couple of concerns just thought about that I want to jot down re: limiting the number of errors before stopping processing: 

- most of the errors are related to new coding instructions. we've told states and territories that they have until FY26 to address them so if the system stops processing these files, the db will be incomplete until the errors are fixed. 

- some errors are more critical than others. cat 1 and cat 4 are the most important. there are also some cat 2s that probably need to be recategorized (header update indicator). should we consider a prioritization strategy by error type if we have to limit what is returned to end users?

**Comment by ADPennington** [comment]
notes from data team sync on 7/30/2024

Possible solutions to reduce the incidence of errors detected per file should consider:

1. Are the most frequent errors associated with updates to the [coding instructions](https://www.acf.hhs.gov/sites/default/files/documents/ofa/Forms_ACF-199_and_ACF-209-Crosswalk_of_Changes.xlsx)  for (a) deprecated items/data elements or (b) deprecated values for items that are still in-use (_note: states/terr only_)?
2. temporarily suppressing or de-prioritizing category 2 (invalid value) and category 3 (inconsistent values within a record) validation

**Comment by lhuxraft** [comment]
Close in connection to other celery issues
