### ISSUE TITLE
Missing Submissions Report

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3028]
**Description:**
DIGIT currently runs missing data reports around quarterly deadlines to determine which STTs have not met their reporting requirements so as to prioritize outreach, support, and reminder efforts. 

**Acceptance Criteria:** 
- [ ] Report lists the following for the current and previous quarter:
   - [ ] Name of STT(s) with missing data grouped/labeled by region
   - [ ] Which sections each STT is missing
- [ ] Missing data logic factors in which files each STT is required to submit (e.g. A universe state should not have Stratum data marked as missing / a Tribe should not have SSP-MOE files marked as missing, etc... ). See requirements for [States](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/states.csv), [Tribes](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/tribes.csv), [Territories](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/stts/management/commands/data/territories.csv)
- [ ] Report is consistent with [UX mockup](url)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Build new report dashboard in Kibana
- [ ] Implement logic to make report reflect each STT's required sections of data
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
- DIGIT approval of UX provided mockup?
- Are the states, tribes, territories csv's fully reflective of current reporting requirements?

**Comment by kennymcnett** [comment]
Closing as part of backlog cleanup. This issue has been in WIP status for 6+ months without activity and appears to have been superseded by more recent work. Please reopen with updated context if still needed.
