### ISSUE TITLE
Build report to compare caseloads across sections 1, 3, and 4

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3029]
### Background ###
DIGIT currently runs three reports that compare case counts between different sections of data. These reports are generated three days after the 45/90 day deadlines, following quarterly data due dates. They help identify inconsistencies in caseload numbers and support outreach to STTs regarding these discrepancies.

### Acceptance Criteria ###
- [ ] Report compares the most recent quarter's monthly Section 1 caseload numbers against monthly aggregate counts from Section 3 and Section 4 (where applicable)
- [ ] Report lists columns for: 
   - [ ] STT Name
   - [ ] Reporting Month & Year 
   - [ ] Caseload for each month as determined by Section 1 Cases
   - [ ] Caseload for each month as determined by Section 3, 4 aggregate active case values
- [ ] Report is consistent with [UX mockup](url)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Build new report dashboard in Kibana
- [ ] Implement logic to populate caseload values for sections 1, 3, 4
- [ ] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
![image](https://github.com/raft-tech/TANF-app/assets/28515874/e44c712a-330b-4482-bb07-df43e9fb6c86)
Example of current reports

### Open Questions ###
- Is this report still relevant if we have Category 5 parsing? 
   - What relationship does this report currently have with whether STTs have gotten their data cleaned up to a no-error Category 5 level 
- Could we potentially replace the need for Sections 3 and 4 by adding up (and presenting) caseload numbers from Sections 1 & 2?
- Should this report's time scope be a FY (as seen in the Mille Lacs example) or a specific quarter (as seen in the Maryland example)?

**Comment by lhuxraft** [comment]
Potentially close after decommissioning Kibana
