### ISSUE TITLE
Build report for transmission history and file submission aggregate

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3030]
### Background ###
DIGIT currently runs reports querying the transmission history when new files are submitted for a given quarter. These reports provide insights into file submissions, versioning, and processing activity.

### Acceptance Criteria ###
- [ ] Report lists versions and aggregate values for a given Quarter's worth of submissions for a given STT
- [ ] Report lists columns for: 
   - [ ] STT Name
   - [ ] Reporting Month & Year 
   - [ ] Program Type (TANF, SSP)
   - [ ] Section
   - [ ] Cases Processed
   - [ ] Records Processed
   - [ ] Submission Date
- [ ] Report is consistent with [UX mockup](url)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Build new report dashboard in Kibana
- [ ] Implement logic to populate data
- [ ] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
![image](https://github.com/raft-tech/TANF-app/assets/28515874/4a8b5275-6cc6-416d-82f6-b39330220669)
Example of current report. Note that Cases Added/Deleted/Changed is relevant to legacy TDRS's update indicator change management system. It is not scoped for this delivery

### Open Questions ###
- Is this report still relevant if we add metadata readouts to data files page in django?
- Is this report preferable to navigating TDP's Submission History (if we were to add record counts) or a new OFA oriented version of Submission History?
