### ISSUE TITLE
Sentry: Local environment for Debugging

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#3043]
**Description:**
Following #831 we want to use Sentry as a debugging tool for backend app in our local environment. 

**Acceptance Criteria:** 

_As an engineer I want to be able to use Sentry in my local environment for debugging_

- [x] Sentry starts with backend app in local environment
- [x] Errors are logged correctly in Sentry
- [x] A default user is created automatically and user can login to Sentry UI
- [x] Disk/Memory usage is minimal
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Use Install self hosted Sentry (link in supporting docs) to install Sentry
- [x] Add a script to create a user for dev to login to Sentry UI
- [x] Add sentry logging settings to local settings
- [x] Follow the suggestions in [here](https://stackoverflow.com/questions/52970153/kafka-how-to-avoid-running-out-of-disk-storage/52970982#52970982) to reduce disk usage by Kafka
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

- Investigate more on how to reduce memory and disk usage as resources are expensive in cloud.gov

**Supporting Documentation:**

- [Install self hosted Sentry](https://develop.sentry.dev/self-hosted/)
- [Self hosted Sentry github](https://github.com/getsentry/self-hosted#self-hosted-monitoring)

**Comment by reitermb** [comment]
Picked up on Friday, 4-5 pt remaining
