### ISSUE TITLE
Prometheus/Grafana - Local Environment

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3044]
**Description:**
As a follow-on to #831, we will be implementing a logging stack with Prometheus/Grafana.

**Acceptance Criteria:** 
_As an engineer I want to have all logs in frontend and backend to be available using Prometheus/Grafana in local environment_

_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Prometheus is running in local dev environment
- [ ] Prometheus UI shows all the apps and services running
- [ ] Grafana dashboard is accessible in local dev environments
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Prometheus/ Grafana configuration infrastructure setup automation
- [x] Connect Prometheus to Grafana
- [x] Connect backend and frontend to Prometheus
- [x] Connect postgres, redis to Prometheus
- [x] Run Testing Checklist and confirm all tests pass
- [x] Add local admin

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by elipe17** [comment]
We can use this if we want export frontend metrics too. https://github.com/cabify/prom-react

**Comment by andrew-jameson** [comment]
> We can use this if we want export frontend metrics too. https://github.com/cabify/prom-react

I'm for it! If it blows scope out, we can make a follow-on ticket. Ideally, I would like prometheus to get logging from all aspects nginx, reactjs, django, clamav, rds/es, etc.

**Comment by elipe17** [comment]
> > We can use this if we want export frontend metrics too. https://github.com/cabify/prom-react
> 
> I'm for it! If it blows scope out, we can make a follow-on ticket. Ideally, I would like prometheus to get logging from all aspects nginx, reactjs, django, clamav, rds/es, etc.

If we want prom-react it will definitely be another ticket. We have to actually integrate it into the frontend.

Also just noting that Prometheus isn't for logging, It is for metric tracking and time series analysis. If we want log aggregation we should consider adding Loki if we want to visualize logs with Grafana, or something else if we want to visualize logs with Kibana. I think Prometheus, Grafana, Loki, and AlertManager would replace Sentry.
