### ISSUE TITLE
PLG deployed in Cloud.gov

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#3046]
**Description:**
Following #831 Prometheus has been selected as one of the logging servers. We need to deploy both Prometheus and Grafana in cloud.gov prod space.

**Acceptance Criteria:** 

_As an engineer I want to have Prometheus/Grafana to be available in Cloud.gov for system logs_

- [ ] Prometheus, Loki, and Grafana are deployed in cloud.gov
- [ ] Grafana is connected to Promethues and Loki and can query the logs from Loki
- [ ] Backend apps can push logs to Loki
- [ ] Prometheus can pull metrics from backend apps and postgres exporters
- [ ] Loki has persistent log storage via S3
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Deploy PLG
- [x] Connect Grafana to Prometheus and Loki
- [x] Update Loki to store logs in S3
- [x] Update backend to deploy promtail as a sidecar
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

- Study security remarks for deploying Prometheus and document your decisions 
- Follow Prometheus best practices

**Supporting Documentation:**

- [Getting started](https://prometheus.io/docs/prometheus/latest/getting_started/)
- [Monitoring linux server](https://prometheus.io/docs/guides/node-exporter/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by andrew-jameson** [comment]
Est 3 pts remaining
