### ISSUE TITLE
Local Grafana - Log Strategy 

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#3047]
**Description:**
We need to specify how we would like to logs backend logs. We also need to add frontend, server level health monitoring, and Postgres logs to Prometheus.

All modifications in this issue are limited solely to the LOCAL ENVIRONMENT but should be environment agnostic, ensuring that we can fulfill all requirements and acceptance criteria in this issue on cloud.gov in next ticket.

**Acceptance Criteria:** 

_As an engineer I want to create and improve log strategy for sending logs to Prometheus_

- [ ] Logs from backend are available in Grafana
- [ ] Logs from frontend (Nginx) are available in Grafana
- [ ] ~~Backend and Frontend servers are monitored by Grafana (availability, cpu usage, HDD usage)~~
- [ ] README is updated, if necessary

**Tasks:**

- [x] Add/configure Promtail to compose and define scrape endpoints (frontend and backend)
- [x] Add/configure Loki 
- [x] Build Grafana dashboard for logs
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [An example for logging Django logs using Prometheus](https://github.com/gonzalo123/django-logs)
- [Monitoring Django app with Prometheus](https://blog.snapdragon.cc/posts/2022-12-monitor-django-with-prometheus/)

**Open Questions:**

- What other metrics do we want to add to Grafana?
