### ISSUE TITLE
as an STT user, I need the error message related to the header update indicator clarified

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3049]
**Description:**

As noted [here](https://github.com/raft-tech/TANF-app/pull/2963#issuecomment-2130178958), when #2963 merges, this will introduce an item number into the error message related to header update indicator, which is currently the most common error message that STTs receive. 

It looks like the following (when the update indicator is N, for example): `HEADER Item 10 (update indicator): N does not match D.`

- Header is not associated with an item number. 
- STTs also seem confused about the current error message in prod (when the update indicator is N, for example): `HEADER update indicator: N does not match D.`

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Error message for header update indicator does not include item number
- [ ] Error message for header update indicator matches language spec from UX team
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] UX team provides language spec for header update indicator error message
- [x] error message updated to include new language and remove item number
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- from @jtimpe: 

> the change is relatively easy:
  ```python=
Field(
    item="10",
    name="update",
    friendly_name="update indicator",
    type="string",
    startIndex=22,
    endIndex=23,
    required=True,
    validators=[validators.matches("D")],
),
```
> for our update indicator field, the `matches` validator can take a second argument `error_func`, similar to how `startsWith` works in the preparsing validators 
```python=
validators.startsWith(
    "HEADER",
    lambda value: f"Your file does not begin with a {value} record."
)
```
> that would let us hard code the message for the one specific case

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- #2818 
- #2963 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- @reitermb @victoriaatraft can you provide guidance on the error message for the error message referenced in this ticket?

**Comment by ADPennington** [comment]
@victoriaatraft @reitermb this ticket needs your input re: open questions. cc: @robgendron

**Comment by reitermb** [comment]
@victoriaatraft and I will connect tomorrow to finalize the language recommendation here. Marking as refined after connecting with dev on approach & pointing.

**Comment by reitermb** [comment]
Updates from UX workshopping of error language:

We're recommending adjusting this error to read: `HEADER Update Indicator must be set to D instead of [file string]. Please review Exporting Complete Data Using FTANF in the Knowledge Center.` to frame it in plainer language and direct non-technical folks to the most relevant article we have on how to correct the issue.

We like the wayfinding help the explicit article name adds but we also have the `HEADER Update Indicator must be set to D instead of [file string]. Please review Knowledge Center guidance on resubmitting complete data` version as a backup.

cc @elipe17 @ADPennington for handoff/language approval

**Comment by reitermb** [comment]
One remaining raft review

**Comment by ADPennington** [comment]
> Updates from UX workshopping of error language:
> 
> We're recommending adjusting this error to read: `HEADER Update Indicator must be set to D instead of [file string]. Please review Exporting Complete Data Using FTANF in the Knowledge Center.` to frame it in plainer language and direct non-technical folks to the most relevant article we have on how to correct the issue.
> 
> We like the wayfinding help the explicit article name adds but we also have the `HEADER Update Indicator must be set to D instead of [file string]. Please review Knowledge Center guidance on resubmitting complete data` version as a backup.
> 
> cc @elipe17 @ADPennington for handoff/language approval

@reitermb i worry a little about pointing STTs to this page of the KC since some dont use FTANF. could we point them to the FAQ page?

**Comment by reitermb** [comment]
> > Updates from UX workshopping of error language:
> > We're recommending adjusting this error to read: `HEADER Update Indicator must be set to D instead of [file string]. Please review Exporting Complete Data Using FTANF in the Knowledge Center.` to frame it in plainer language and direct non-technical folks to the most relevant article we have on how to correct the issue.
> > We like the wayfinding help the explicit article name adds but we also have the `HEADER Update Indicator must be set to D instead of [file string]. Please review Knowledge Center guidance on resubmitting complete data` version as a backup.
> > cc @elipe17 @ADPennington for handoff/language approval
> 
> @reitermb i worry a little about pointing STTs to this page of the KC since some dont use FTANF. could we point them to the FAQ page?

@ADPennington We do have the "How to get support or help exporting complete data from other systems" at the bottom of that guide. My main worry with the FAQ is that it doesn't include enough guidance on how to actually change the update indicator and for further reading links out to the guide for doing it in fTANF anyway. But you can probably speak better than I can to what instruction has worked for folks encountering this error.

**Comment by ADPennington** [comment]
> > > Updates from UX workshopping of error language:
> > > We're recommending adjusting this error to read: `HEADER Update Indicator must be set to D instead of [file string]. Please review Exporting Complete Data Using FTANF in the Knowledge Center.` to frame it in plainer language and direct non-technical folks to the most relevant article we have on how to correct the issue.
> > > We like the wayfinding help the explicit article name adds but we also have the `HEADER Update Indicator must be set to D instead of [file string]. Please review Knowledge Center guidance on resubmitting complete data` version as a backup.
> > > cc @elipe17 @ADPennington for handoff/language approval
> > 
> > 
> > @reitermb i worry a little about pointing STTs to this page of the KC since some dont use FTANF. could we point them to the FAQ page?
> 
> @ADPennington We do have the "How to get support or help exporting complete data from other systems" at the bottom of that guide. My main worry with the FAQ is that it doesn't include enough guidance on how to actually change the update indicator and for further reading links out to the guide for doing it in fTANF anyway. But you can probably speak better than I can to what instruction has worked for folks encountering this error.

good pt @reitermb. let's keep this for now; im honestly not too sure what users find most useful. personally, i'd opt for a [video](https://github.com/raft-tech/TANF-app/issues/3054/) 😄
