### ISSUE TITLE
(Internal) Clear guidance on how we find documents on process, background

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#305]
**Description:**

 Follow up to 9/29 retro, we need a single source of truth for process, background materials. Currently there's MS Teams wiki, one notes, GitHub wiki 
Particularly important for onboarding. 

**Acceptance Criteria:** 
- [ ] We understand what to put in the wiki vs. MS Teams, what can be linked to >> This is documented
- [ ] Understand file structure in teams 

**Tasks:** 

- [x] Have the conversation with relevant parties 
- [x] Understand wiki permissions or alternatives (consult @rahearn )
- [x] Determine wiki plan going forward

**Deliverable(s):**

The notes and decisions from the single source of truth discussions can be found [here](https://teams.microsoft.com/l/file/CB8C6222-7E24-415A-8951-BAAF8A7705C4?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FSingle%20Source%20of%20Truth.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Comment by rahearn** [comment]
GitHub's wiki can either be set to publicly writable (not ideal) or uses the "write" permission for the main repo (also not ideal). A short-term workaround could be to grant Raft write access to the HHS repo until there are production credentials in CircleCI that need to be protected, but then we need to figure out how to handle the wiki at that time.

Another possibility is using the Raft repo wiki, and using git's CLI to sync the content over to the HHS wiki for long-term access. Not ideal, in that people need to remember not to edit things on the HHS side.

What about the wiki built into Teams? Would OCIO stakeholders have read access to that?

**Comment by SelenaJV** [comment]
Hmm. Thanks for laying out those options @rahearn. @lauraGgit scheduled some time for us to chat about this on Tuesday AM.

**Comment by SelenaJV** [comment]
Current plan:

1. Selena creates a PR that migrates over the Team Charter.
2. Lauren, Shubi, Selena, Alex, (+anyone else interested) gather up and look over PR together; we merge in the PR when Lauren gives it a 👍 
3. Alex works on a second PR that migrates over the wiki contents 
4. When ready, Lauren, Shubi, Alex (+anyone else interested) gather up and look over PR together, we merge in the PR when Lauren gives it a 👍 
5. For research items, Miles creates a 3rd PR that migrates any remaining user research items from Teams
6. Lauren, Shubi, Selena, Alex, (+anyone else interested) gather up and look over PR together; we merge in the PR when Lauren gives it a 👍 
7. For design items, Dmitri creates a 4th PR that migrates any remaining design items from Teams
8. Lauren, Shubi, Selena, Alex, (+anyone else interested) gather up and look over PR together; we merge in the PR when Lauren gives it a 👍

**Comment by SelenaJV** [comment]
@alexsoble Heads up: I annotated the wiki sidebar nav with "Move" on items that I think should clearly move to GH docs because they are likely to evolve.

**Comment by shubhi-raft** [comment]
@SelenaJV  thanks! I think this is ready for QASP review. Opening a following ticket to complete the migration #321.

**Comment by lfrohlich** [comment]
Migration will happen in #321
