### ISSUE TITLE
[Design Deliverable] Spec for light-lift fiscal quarter / calendar quarter explainer in TDP

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3057]
**Description:**

Follow-on from #3017. Formalizes prioritized light-lift ideations into handoff-ready spec. 

**AC:**

- [x] Includes formalized ideations for:
   - [x] Add "Fiscal" to label
   - [x] Add lookup table to Data Files page
- [x] Internal Raft Review has occurred to ensure DoD standards and QA
- [x] Dev/Design sync has occurred; resulting tickets created
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft final designs in HTML prototype or Figma
- [ ] Dev:Design sync

**Supporting Documentation:**

- [Figma Mockups](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8902-3268)
- [Ideation Mural](https://app.mural.co/t/raft2792/m/raft2792/1718739423199/ed42a2fa979a5d63876ab96bd9399458f390f725?sender=uf443e00cb4626b8bec157528)
- [UX Roadmap](https://app.mural.co/t/raft2792/m/raft2792/1627058877512/7514d3617f4bc241d3f70ff6e61253e1ce09f880?sender=60a5ac24-4d3c-413c-afb3-dd9a6e536a42) has placeholder card for testing in the future, per comments below
![Table Option 1](https://github.com/user-attachments/assets/ab34fe04-1f95-4648-8e61-70bdd51544a5)

**Comment by victoriaatraft** [comment]
Post dev office hours feedback: UX to experiment with prototyping and laying out the table vs providing a link to a modal on the page for the light lift option. [Similar to this](https://reitermb.github.io/HTML-Table-example/csv-research.html)

**Comment by robgendron** [comment]
Update: Continuing to work on draft 
Next: Internal UX pairing
Points Remaining: 4

**Comment by robgendron** [comment]
Update: Figma version being worked today, HTML later this week

**Comment by victoriaatraft** [comment]
[Figma Mockups](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8902-3268) attached with options in the Supporting Documents of the main ticket description

**Comment by robgendron** [comment]
Final mile - 2 points remaining.

**Comment by victoriaatraft** [comment]
Hi @ADPennington @lfrohlich 
Following up a question before this moves to QASP. Two versions of showing the tables to help users figure out the Fiscal Year and Quarter table. One option shows the Due Date and the other does not. Would it be helpful for users to have a due date column for data files or will that potentially cause confusion? We can definitely test this in the future as well.

<img width="1078" alt="Screenshot 2024-07-15 at 12 01 07 PM" src="https://github.com/user-attachments/assets/32b0bd62-aeaa-435c-b27c-2d809fc9159f">

**Comment by ADPennington** [comment]
> Hi @ADPennington @lfrohlich Following up a question before this moves to QASP. Two versions of showing the tables to help users figure out the Fiscal Year and Quarter table. One option shows the Due Date and the other does not. Would it be helpful for users to have a due date column for data files or will that potentially cause confusion? We can definitely test this in the future as well.
> 
> <img alt="Screenshot 2024-07-15 at 12 01 07 PM" width="1078" src="https://private-user-images.githubusercontent.com/106103383/348824367-32b0bd62-aeaa-435c-b27c-2d809fc9159f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzI4NjcsIm5iZiI6MTcyMTIzMjU2NywicGF0aCI6Ii8xMDYxMDMzODMvMzQ4ODI0MzY3LTMyYjBiZDYyLWFlYWEtNDM1Yy1iMjdjLTJkODA5ZmM5MTU5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxNjA5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzU3ZDg2MTgzNzQyNDRlZTQ5OWQ2YTIzZTMyNjlkZTJjM2JlOTY1ZDBhZmJhY2YwYjhlY2QzYjQ3YTQ5MGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1sDXOW-xx3gktncEiqPk_q3eda479_vdhLh-BvJs_0w">

@victoriaatraft @reitermb @lfrohlich @ttran-hub -- i think both options look great. my personal preference is the option on the left for less scrolling. is there any a11y concerns with either option?

**Comment by victoriaatraft** [comment]
@lfrohlich @ADPennington thank you. Any thoughts on the Due Date column being included or excluded? 
And also following up, both options are accessible, the two column version may just need more pairing with dev.

**Comment by ADPennington** [comment]
> @lfrohlich @ADPennington thank you. Any thoughts on the Due Date column being included or excluded? 
> 
> And also following up, both options are accessible, the two column version may just need more pairing with dev. 

@victoriaatraft I'm okay with the shorter table without due date since 1) due dates are on the home page 2)the specific purpose of this helper is to identify the correct fiscal period and 3) STTs resubmit regularly, regardless of initial due date. Cc: @lfrohlich @ttran-hub

**Comment by lfrohlich** [comment]
I'm ok with leaving off due date, but also like the idea of testing in the future. Can you put a placeholder in the UX roadmap @victoriaatraft ?

**Comment by victoriaatraft** [comment]
Sure thing @lfrohlich thank you!

**Comment by ADPennington** [comment]
can this be closed @victoriaatraft @lfrohlich ?

**Comment by lfrohlich** [comment]
Yes, this can be closed with the follow on #3109
