### ISSUE TITLE
[Design Deliverable] Release notes email template

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3058]
**Description:**
Follows on from July 1 UX sync discussion, delivers email template implementing June 5th release notes into HTML email

**AC:**

- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**
- [x] Investigate whether SendGrid can be utilized to serve this up pending future enhancements to automate
- [x] Plug HTML template into email test service and create a forwardable format
- [x] Send draft to Alex, Thomas, TANFdata

**Comment by robgendron** [comment]
Connecting today and prepping for review.

**Comment by victoriaatraft** [comment]
Questions for Next UX Sync: 
- How often are we potentially having release notes?
- POC for the content?

**Comment by robgendron** [comment]
1 point remaining.

**Comment by ADPennington** [comment]
@reitermb the email template looks good to me. but the last bullet appears to be formatted differently. screenshot below. cc: @ttran-hub @lfrohlich 

![Screenshot 2024-07-19 091434](https://github.com/user-attachments/assets/e90482c6-0a6b-48ff-a11f-840dd8fe052c)

**Comment by ADPennington** [comment]
@reitermb @ttran-hub is this ready to close?

**Comment by reitermb** [comment]
> @reitermb @ttran-hub is this ready to close?

I think so unless @ttran-hub wants to keep it open to track any final mile steps. I'm not sure if Thomas got the distribution list / sent the release notes yet?

**Comment by ADPennington** [comment]
> > @reitermb @ttran-hub is this ready to close?
> 
> I think so unless @ttran-hub wants to keep it open to track any final mile steps. I'm not sure if Thomas got the distribution list / sent the release notes yet?

thanks @reitermb. @ttran-hub I saved the approved user list in the admin sync log in OneNote. under 8/2/2024.

**Comment by ADPennington** [comment]
@reitermb @victoriaatraft we are ready to close this ticket. cc: @lfrohlich @ttran-hub Please note:

- We've decided not to send out the June 5th release notes because the latest features in the upcoming release will address some of the notes identified here. 
- We need a new ticket to track the next TDP KC release note update (if one does not currently exist). It should include the following: 
  - TDP is now sending email reminders to STTs when the quarterly deadline is approaching (5 days out) 
  - we have relaxed the criteria for the header update indicator such that data will still be processed. Worth explaining to STTs that this was previously resulting in their files being rejected. Also: the header update indicator should still be D and if it isn't, the message will still be included in their error report (#3130)
  - bug fix: resolved issue impacting closed file processing (#3129). Please explain that this was resulting in files being rejected because of SSI-related error message (may be worth mentioning the error message)
  - bug fix: aggregate files for FY21Q1 (#3125)
  - continued enhancement to error messages. worth also calling out that we continue to make refinements based on user feedback. for example: we are trying to learn more from STTs about circumstances that yield high frequency of the following error message: "1: The sum of ('amount of food stamp assistance', 'amount of subsidized child care', 'cash amount', 'child care amount', 'transportation amount', 'transition services amount', 'other amount') is not larger than 0."
