### ISSUE TITLE
Retro 9/29 Commitments

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#306]
**Description:**
Document Retro action items from [9/29 Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1601396752496/b5975035fd7766ec40917c72724df6e88631d0aa) and create issues to address feedback.

**AC:**
- [x] retro items action items have been documented 

**Tasks:**
- [x] Create issue to discuss and confirm the single source of truth for procedure, background, research and design artifacts.  
- [x] In sprint planning, align AC with tasks
- [x] Update the charter with AC are achievable outcomes of tasks. Adding a note in GitHub if AC is not being to be met or may need to be pushed
- [x] Extend Retro timing
- [x] Update 'Gov review' to 'QASP review' on ZenHub boards and Team charter
- [x] Revisit whether sprint schedule is serving us in the next retro 
 

**Supporting Documentation:**

(please include any relevant log snippets/ files/ screen shots here.)

**Open Questions:**

(any clarifying questions in support of the issue)

**Deliverables:**
(Internal) Determine where to post research artifacts and deliverables : #270
