### ISSUE TITLE
As a TDP user, I need to stay logged in when I'm actively using the system

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3060]
**Description:**

After signing in via acf ams or login.gov, and actively using the system, I am automatically signed out after 30 minutes. This is disruptive, and I'd like my session to persist unless:

1. I close my browser
2. I am inactive for 15-30 minutes (whichever is consistent with #3020)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] A user session persists while the user is actively using the system
- [ ] the session ends when the browser is closed
- [x] the session ends if the user is inactive for 15-30 minutes (see above)
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] update session management-related code docs and markdowns
- [x] ensure consistency between sessions via login.gov vs acf ams
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- #3020 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by robgendron** [comment]
Adding to the current sprint backlog as a "Next Ticket to Consider" in addition to the sprint plan.

**Comment by andrew-jameson** [comment]
Est 3 pts remaining
