### ISSUE TITLE
Re-parse Meta Model

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3064]
**Description:**
As a follow on to #3004, it would be convenient for developers and system admins to be able to query a model from the DAC that contains metadata about a re-parse event. This model should contain, but is not limited to the following metadata: 
- the number of datafiles re-parsed
- the number of records deleted
- the number of records re-parsed
- total number of records in the DB before re-parse
- total number of records in the DB after re-parse
- start time of re-parsing
- end time of re-parsing (This would ideally be set when all files had finished parsing and not when the command exits).
- re-parse DB backup location
- re-parse new index pattern if applicable
- a version number that is also a PK

Having a version number on this model will allow us to name backups and indices according to re-parser versions as opposed to datetimes. This will make viewing backups, indices, and indices in Kibana significantly easier and more user friendly.

As a stretch, it would be nice to somehow use this model as an added gate to the `clean_and_reparse` command. That is, if this new model's end time is not set we do not want to allow another re-parse to commence. This can be purely investigative, but would help prevent inconsistency errors and resource utilization based errors.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Meta data model is created
- [ ] Meta data model is serialized to the DB per run of the `clean_and_reparse` command
- [ ] Original submission date is retained even when file is reparsed
- [ ] Migration is named appropriately
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Create model and migration
- [x] Create read only admin model and simple filters for DAC
- [x] Initialize/fill model fields in `clean_and_reparse`
- [x] Add unit tests and integration tests
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

NA

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

NA
**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

NA

**Comment by reitermb** [comment]
Running into problems finishing the run in environments, Andrew to take a look while Eric is OOO
