### ISSUE TITLE
TDP Data Files page permissions for DIGIT & Sys Admin user groups

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3074]
**Description:**
Currently users assigned to the DIGIT or System Admin user groups cannot reach and browse TDP's Data Files page. This ticket adds those permissions for both groups. Functionality should mirror how OFA Admin usergroup users can currently pick from STTs on the data files page on the frontend of the app (see screenshot below). 

**Acceptance Criteria:** 
- [x] DIGIT user group has permissions for accessing TDP frontend Data Files pages
- [ ] System Admin user group has permissions for accessing TDP frontend Data Files pages
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Implement permission group changes
- [ ] Confirm that the data files page can be browsed by both groups & submission history access is included
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
[Research Synthesis w/ all DAC issues](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/ofa-admin-experience-synthesis)

![image](https://github.com/user-attachments/assets/e2da3736-3a8b-4ad4-95e8-b60962891c9b)

**Comment by reitermb** [comment]
Add sys admin to this improvement
