### ISSUE TITLE
DB Backup Script Fix

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3079]
**Description:**
It was recently discovered in #3004 that the `db_backup.py` script has a subtle error. The script correctly creates, and stores a backup. However, the script is using `VCAP_SERVICES` to get the DB connection information. In all environments except for `production` there are multiple database names in the RDS instance. The logic that selects the DB connection information in the script is selecting the first DB it comes across which should not be the case. The script should choose the correct DB for all environments every time. As a bandaid solution, #3004 implemented the backup logic using Django settings which is not what we want. The script should not rely on Django.

**Acceptance Criteria:** 

- [ ] Backup script creates backups of the correct DB in the RDS instance across all environments
- [ ] Script does not require Django to work successfully
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Remove Django settings usage throughout backup script
- [x] Update logic to select correct DB information in `get_system_values()`
- [x] Test the backup script in a deployed environment
- [x] Verify in the production environment that we have valid backups despite this error
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

N/A

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

N/A

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

N/A
