### ISSUE TITLE
Cloud.gov Memory Allocation Error 9/30/2020

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#308]
**Description:**
Deploying the latest backend service to the cloud.gov dev environment resulted in the following error being thrown by the cloud foundry cli tool :

```
memory quota_exceeded
FAILED
```

**Acceptance Criteria:** 

- [ ]  the TDRS Backend service can deploy to the cloud.gov dev environment via rolling and non rolling updates. 

**Tasks:**

- [ ] Adjust the memory allocation as defined in the manifest.yml in `tdrs-backend` 
- [ ] Test the new settings against the circleci deployment to ensure correct behavior 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- More research may need to be done in regards to this. As this issue materialized with no alterations to the tdrs-backend service memory usage since its previous deployment. 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Example of failed deployment](https://app.circleci.com/pipelines/github/raft-tech/TANF-app/697/workflows/8b22ae28-ba16-4874-b35a-7f1e5f18a537/jobs/1284/parallel-runs/0/steps/0-110)
