### ISSUE TITLE
Admin By Newest Filter Enhancements for Data Files Page

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3087]
**Description:**
Currently DAC Search Indexes pages default to filtering results to "Newest". This ticket updates the language of that filter to "Most recent version" and adds that behavior to the Data Files page.

**Acceptance Criteria:** 
- [ ] Search Index filters are updated with newer "Most recent version" language
- [ ] Most recent version filter added as a default to Data Files page
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Update language
- [ ] Add filter to the DAC Search Index Page

**Supporting Documentation:**

- [Research Synthesis w/ all DAC issues](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/ofa-admin-experience-synthesis)

**Comment by lfrohlich** [comment]
FYI this is one of Yun's priorities to enhance usability
