### ISSUE TITLE
Update Section 3, 4 validation to screen for ≥ 1 families rather than ≥ 0 

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3088]
**Description:**
Sections 3 and 4 of TANF data concern aggregate values that are highly unlikely to be 0. This ticket delivers a parsing logic fix to reflect that and make the minimum range is >= 1. This will catch instances like Nebraska 0 filling this data for a number of recent months.

**Acceptance Criteria:** 
- [ ] Family totals parsing for >=1 rather than 0
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Implement parsing logic change
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [Research Synthesis w/ all DAC issues](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/ofa-admin-experience-synthesis)
- [Mural Document #2910](https://app.mural.co/t/raft2792/m/raft2792/1720460304271/b1de09b0efbfd35bb9f72063d4162ccd20a17d25?sender=9a9aa337-a5c5-4306-9324-5a39a7b326da)

**Comment by ADPennington** [comment]
@reitermb @victoriaatraft @elipe17 -- context for this ticket for your reference:

	
this applies to the total number of families for states and territories only and for the TANF program only. the rationale is: it is unlikely for the total number of families served by the TANF program in any state or territory to be 0 in any month.
