### ISSUE TITLE
As an OFA Admin, I need a list of MVP roles in the database to assign to new users

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#309]
**Description:**
This issue will deliver adding a list of preliminary (MVP) roles to the database- `OFA Admin`, ~~`OFA Analyst`~~ and `Data Prepper`. This is precursor to implementation of #164. 

**Acceptance Criteria:** 
- [ ] Preliminary (MVP) roles are populated in the database

**Tasks:**

- [x] Populate database with approved list of MVP roles
- [x] Determine initial permissions for each role
- [x] Populate database with permissions for each role

**Notes:**

- We can use general permissions (simple) to start - can always add more later - we should just decide what they are initially

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**

- Should any other roles be added for MVP?
     - Since roles can be created dynamically via API endpoint, this question is no longer applicable.

**Comment by RafterGit** [comment]
Because of how we’re  managing users, we can leverage Djangos built in functionality for groups and permissions for the roles and permission logic we need. Did some work to start implementing this into our code base. 

Will be pairing with @carltonsmith today (10/7/2020) to address any development concerns / constraints

**Comment by shubhi-raft** [comment]
based on discussion in Teams, @lfrohlich I updated the roles.

**Comment by lfrohlich** [comment]
Thanks @shubhi-raft Yes, as we discussed this will just focus on the two roles/

**Comment by lfrohlich** [comment]
Carl demoed this as part of PR #121 on 1/11/21. OFA admin and data prepper are in the database. Great work! Merged 1/12/21
