### ISSUE TITLE
Add filters to Data File Summaries pages

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3093]
**Description:**

Currently Data File Summaries pages lack filtering capability. This ticket delivers filter options matching those on the Data Files page.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Data File Summaries pages have filters
- [ ] Filter parity with Data Files pages
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add filters to Data File Summaries page
- [ ] Confirm all filters work
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [Research Synthesis](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/ofa-admin-experience-synthesis)

**Comment by lhuxraft** [comment]
Features can be implemented in the future with Grafana. There is also a significant workaround already in place, closing this
