### ISSUE TITLE
[In-App Error Reporting] List of CAT1,4 Rejected Case Numbers for DIGIT & Sys Admin user groups

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3096]
**Description:**
List of CAT1,4  rejected case numbers 

**Acceptance Criteria:** 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] README is updated, if necessary

Notes:
May need a follow-on spike to understand associated error messages

**Supporting Documentation:**
[#2910 Mural Admin Exp Improvements](https://app.mural.co/t/raft2792/m/raft2792/1720460304271/b1de09b0efbfd35bb9f72063d4162ccd20a17d25?sender=70699c5a-0269-4ab3-8427-25b50f413642)

**Comment by lhuxraft** [comment]
Closing as this was intended to retrofit in DAC, may want to evaluate this metric in future visualizations via Grafana (Yun should be able to grab this information easily via queries). May want to revisit in future in-app error reporting work
