### ISSUE TITLE
Rearrange Data Files filters and implement multiselect fiscal period filter

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3097]
**Description:**
On the data files page, implement multiselect functionality on STT filter 
Rearrange Filters for the Django Admin Data Files In the Following Order:
- STT
- Fiscal Period
- Year
- Quarter
- Section

**Acceptance Criteria:** 
- ~~[ ] Multiselect filter allows for filtering by fiscal period like on search index pages~~
- [ ] The filters are rearranged in the described order 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ]  Implement multiselect for STT filter on Data Files page
- [ ] Rearrange order of filters
- [ ]  Confirm that the ability to select multiple STT locations passes by both groups
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
[- #2910 Mural Admin Exp Improvements](https://app.mural.co/t/raft2792/m/raft2792/1720460304271/b1de09b0efbfd35bb9f72063d4162ccd20a17d25?sender=70699c5a-0269-4ab3-8427-25b50f413642)

**Comment by ADPennington** [comment]
@victoriaatraft @elipe17 i removed the first AC here and also tagged it to close with #3204 cc: @vlasse86
