### ISSUE TITLE
[Design Deliverable] Update stakeholders & personas document

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3100]
**Description:**

Examine splitting out OFA Data Analyst persona into DIGIT / Sys Admin
Update Stakeholder & Persona Doc

**AC:**

- [x] Documentation work for the following has occurred:
   - [x] Relevant User stories.
   - [x] Recommended pa11y checks.
   - [x] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [x] Internal Raft Review has occurred to ensure DoD standards and QA
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] [Create Updated Persona Draft in Gitbook for review](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/research-spike-plan-yun-and-digits-data-workflow-3142/3100-personas-draft)
- [x] [Update TDP Github Personas Documentation](https://github.com/raft-tech/TANF-app/blob/develop/docs/User-Experience/Research-Syntheses/2020%2C%20Summer%20-%20Understanding%20Stakeholders%20and%20creating%20personas.md)

**Supporting Documentation:**
[GitBook Protocol Notes: Research Spike Plan: Yun & DIGIT's data workflow #3142](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/research-spike-plan-yun-and-digits-data-workflow-3142)

**Comment by reitermb** [comment]
Added one annotation & a few tweaks @victoriaatraft! Once that's responded to I think we're good to kick this over to QASP and to set up some time with Alex & Thomas!

**Comment by victoriaatraft** [comment]
Thank you @reitermb. Time scheduled next 10/01 at 4pm ET with Alex and Thomas

**Comment by lfrohlich** [comment]
UX will discuss in internal sync 10/9. Miles has been reviewing

**Comment by lfrohlich** [comment]
@victoriaatraft  does this include updating the personas in mural or just the gitbook/github docs?

**Comment by victoriaatraft** [comment]
> @victoriaatraft does this include updating the personas in mural or just the gitbook/github docs?

@lfrohlich just the gitbook/github docs.

**Comment by lfrohlich** [comment]
Waiting minor changes

**Comment by vlasse86** [comment]
Demo on 11/6.

**Comment by victoriaatraft** [comment]
password added to the mural for those outside the workspace trying to access

**Comment by lhuxraft** [comment]
Revisit demoing after regional staff UI tickets are picked up. @reitermb to check if PR is merged. @ADPennington to check with Lauren if still needs to be demoed
