### ISSUE TITLE
Admin Exp: Django Implement Multi-Select Fiscal Period Dropdown For Data Export 

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3102]
**Description:**
Currently the filter control on DAC Search Indexes pages is a single option dropdown. This ticket replaces it with the multiselect control that we use when filtering by STT. This replicates the SQL union queries used in the legacy system.
Replicates SQL union for whole fiscal year type of use case

**Acceptance Criteria:** 
- [ ] Search Indexes pages have multiselect fiscal period filter
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Implement filter for all record types on search indexes pages
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
- [Research Synthesis w/ all DAC issues](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/ofa-admin-experience-synthesis)
