### ISSUE TITLE
[Re-parse command] Retain original submission date when command runs

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3107]
**Description:**

During [review](https://github.com/raft-tech/TANF-app/pull/3041#discussion_r1690513482) of #3041, we noticed that most of the original submission history details on the frontend are retained when the reparse command runs, except the original submission date is overwritten. Ideally, the original submission date would be retained, since STT auditors use this information to confirm if data was submitted on-time.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Submission history details about the original submission (i.e. submission date, user, file) are retained when re-parse command runs
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] update codebase and tests to account for retaining original submission history details 
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- #3041 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by raftmsohani** [comment]
#3064 resolves this issue. This ticket can be closed now

**Comment by ADPennington** [comment]
@robgendron @raftmsohani @elipe17 -- is the AC in this ticket captured in #3064? If not, can it be added, please?

**Comment by elipe17** [comment]
> @robgendron @raftmsohani @elipe17 -- is the AC in this ticket captured in #3064? If not, can it be added, please?

Added
