### ISSUE TITLE
Additional datafile filters

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3108]
**Description:**
To further specify which files need to be re-parsed, sys admins need more granular control.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Datafiles DAC page has granular options for narrowing/expanding datafile search per Notes
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] ~~Enable stacking/`OR`-ing of multiple filters of same type (e.g., I want all datafiles from Florida or Georgia in my query)~~ Implemented via multi-select #3183 
- [x] New Datafile filter for type (state, tribe, territory)
- [x] New Datafile filter for region -- likely same cross-link of datafile and STT objects as above
- [x] New Datafile filter for "latest" -- must be combined with other filter(s). We don't want to re-parse v1,v2,...,v35 of a file so the latest filter would be after the other filters return a queryset of datafiles, only cherry-pick the highest version of each.
- [x] New Datafile filter for program type (we currently have section (SSP Active))
- [x] New Datafile filter for section (piggybacks on above task)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
- ~~Current filtering is "AND" logic which will provide a non-intuitive interface. The first task for stacking/`OR`-ing conditions is paramount to success.~~

- _Requested filters:
  - file id (e.g. 2053, lst)
  - STT (e.g. Alabama, lst)
  - STT type (e.g. tribe, lst)
  - region ( i.e. a set of STTs in a particular region)
  - program type (e.g. TANF)
  - most recent file version (e.g. latest)
  - processing status (e.g. pending)
  - section (e.g. Active Case Data)

**Supporting Documentation:**
- Please see MVP impl. via PR #3041 

**Open Questions:**

- how best to handle the scenario where parameters passed are in conflict (e.g. STT type = tribal and region = 1 (has no tribes)? 
  - Utilize confirmation dialog from #3106  
  - Can we safely rely on a downstream system to handle contradictory parameters as suggested? If using DRF filtering, we could just end up with 0 files and say nothing to do. 
  - Should we have an [Ansible-like](https://docs.ansible.com/ansible/2.9/user_guide/playbooks_checkmode.html) "preview" function? 
    - To be encoded as part of #3106

**Comment by andrew-jameson** [comment]
'Latest' being implemented in #3139
