### ISSUE TITLE
Light-Lift Fiscal Quarter and Calendar Quarter Explainer in TDP 

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3109]
**Description:**
Follow on dev ticket to design ticket #3057 and related to #3017

Release Notes:
- Table added to Data Files Page
- Explain difference between fiscal and calendar year in plain language
- Note when the government fiscal year starts

**Acceptance Criteria:** 
- [x]  Data Files page matches mockup found below
- [x]  Internal Raft Review has occurred to ensure DoD standards and QA
- [x]  The design is usable and accessible, meaning it adheres to definition of done standards for design work.
- [x] Table is responsive on narrow/mobile screen devices and a11y accessible

**Tasks:**
- [x] Add "Fiscal" to label in Data Files
- [x] Add table created in mockups to Data Files page within a two column format
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**

- [Figma Mockups](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8902-3268)
- [Ideation Mural](https://app.mural.co/t/raft2792/m/raft2792/1718739423199/ed42a2fa979a5d63876ab96bd9399458f390f725?sender=uf443e00cb4626b8bec157528)

![image](https://github.com/user-attachments/assets/a753c039-bc05-409b-ba2d-680c3cd730c9)

**Comment by victoriaatraft** [comment]
@lfrohlich @klinkoberstar 

A calendar year runs from January 1 to December 31, while the fiscal year for the U.S. government runs from October 1 to September 30.  If you are submitting data that aligns with the calendar period of the year, the new table will help you match those dates with the fiscal year quarters prior to your submissions.

Also added to the [Release Notes Draft for October 10 in Gitbook](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/oct-8th-release-notes)  if that is easier to comment on for feedback
