### ISSUE TITLE
Spike - Investigate Custom Filter Integration

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3110]
**Description:**
In #3083 it was discovered that Filters outside of the per-view of Django 508 cause problems with how 508 generates the query string for it's native filters. If another filter adds parameters to the query string, 508 does not handle that at all and thus begins duplicating that extra query in the the query string. This is technically not breaking anything as the filter still works as expected. However, as TDP introduces more custom filters, the 508 logic is going to become a big problem. Thus, we need to spend some time determining whether we can conform the TDP custom filters to 508's templates/logic, or if we need to update 508 to better handle query string creation and manipulation.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Plan to update the TDP filter templates or 508's templates and JS to better support custom filters
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Explore how 508 manages query strings
- [ ] Explore TDP's custom filters and templates
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- Have to compare the screen reader before & after
- If you would like to see the incorrect behavior, switch to `3061-a11y-multiselect` or `develop` if `3061-a11y-multiselect` has been merged.
  - Submit some data via the frontend
  - Navigate to the DAC and a `search_indexes` admin page that contains data
  - Choose a selection of STT's (4 or 5) that includes the STT you submitted with
  - Verify the data is still displayed
  - Use any other filter on the page and then apply it
  - Note how the url has the query string duplicated
  - Verify the data displayed matches your filtering

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by robgendron** [comment]
#3064 will give final refinement on this.
