### ISSUE TITLE
Implement a ceiling on number of errors a single datafile generates

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3112]
**Description:**
Coming out of a discussion on #3026, we are thinking to limit the reported number of errors.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Output Error Report indicates more errors may exist
- [ ] Output Error Report caps number of errors presented
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Set a ceiling variable
- [ ] Create mechanism to stop parsing when ceiling is hit
- [ ] Ensure Error Report reflects more limited error count
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- My recollection is that we will stop all parsing at this limit.

**Supporting Documentation:**

**Open Questions:**

- Should we limit errors to 50, 200, 500?
- What exact language should we put in the Error Report to indicate more issues may exist? (UX item)
