### ISSUE TITLE
As tech lead, I need the validation on the header update indicator revised to unblock parsing 

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3113]
**Description:**

The validation on the header update indicator was introduced to help enforce OFA's expectation that STTs would submit all records with every submission. Because this validation check was recently implemented, most files submitted via TDP do not have the appropriate update indicator value, and the re-parsing command introduced in #3041 cannot be used to re-process these files unless this value is correct. 

Since manual correction and resubmission of these files is not feasible for OFA or STTs, the validator needs to be relaxed. 

**Acceptance Criteria:** 

- [x] Validator for header update indicator revised such that records can still be processed when the update indicator value is not `D`
- [x] An error message related to header update indicator is still included in the error report when the value is not `D`
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] update header update indicator validator
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Manual resubmission results](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc={c9d41a72-bff8-4eba-b245-bb04ba265e12}&action=edit&wd=target%28Dev%20Notes.one%7C567fc274-f86b-0a48-901d-543bdc5250ac%2FManual%20Resubmission%20Results%7C3ff147be-7c9a-4ef3-90cd-9e37e32407a5%2F%29&wdorigin=NavigationUrl)

**Comment by ADPennington** [comment]
@robgendron please prioritize this for upcoming sprint.
