### ISSUE TITLE
(Internal) Define the scope and timeline for ATO

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#312]
**Description:**
This issue will deliver the scope and timeline for ATO release. 

**Acceptance Criteria:** 
- [x] MVP scope and timeline is documented in a logical place (teams 🔒 )

**Tasks:**

- [x] Review proposed scope and align it with ATO PRR date
- [x] Share the outcome and output with the larger product team

**Notes:**

**Supporting Documentation:**
NA

**Open Questions:**
NA

#### Deliverable(s):
In order to reduce confusion, we are separating ATO from OFA MVP. Our current goal for PRR is May 13th, 2021 (Just after Sprint 20)

**Comment by shubhi-raft** [comment]
Based on the MVP Scope + ATO timeline conversation, the next steps are: 
- @lfrohlich to schedule a discussion to walk through the [roadmap](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592336604317/61159efd030645a74c267130ea19b2083f87dd09) with @alexsoble and @rahearn 
- Shubhi to schedule a discussion to walk through the updated roadmap and #301 with @dk-ui @reitermb @matthewjdoty 
- Shubhi to schedule MVP discussion with OFA data team Oct 9 - Oct 16

**Comment by shubhi-raft** [comment]
@lfrohlich @SelenaJV besides updating the roadmap based on our discussion, do we need to document this anywhere else?

**Comment by SelenaJV** [comment]
@shubhi-raft @lfrohlich This page of the wiki should get updated https://github.com/HHS/TANF-app/wiki/Roadmap-and-backlog

**Comment by shubhi-raft** [comment]
Thanks!  @lfrohlich are you able update the wiki page with:

--XX-- 
## OFA MVP (Phase 1)

For the minimum viable product (MVP) that can receive an Authority To Operate (ATO), our plan is to deliver on the following epics outlined on the roadmap. For this MVP, we will measure against the key performance indicators (KPI) to determine our success. 

### Epics to be delivered:
- Users can login into the new system
- Users can easily upload data 
- Users can view a list of uploads
- OFA staff has access to the data

### KPIs:
- Users with an assigned role can login and view screens based on their role
- OFA analysts can upload data
- OFA analysts can view a list of uploads 
- OFA analysts have access to data that was uploaded by an OFA analyst. 


--XX--
Feel free to update/edit as appropriate.

**Comment by shubhi-raft** [comment]
Updated roadmap and MVP Phase 1 has been shared with 18F, Raft, and IPT members. Discussion with OFA team to be scheduled next week - Oct 13- Oct 16; conversation has been kicked off Teams to schedule the discussion.

**Comment by lfrohlich** [comment]
@shubhi-raft I'll wait to update the wiki/docs until after our workshop on 10/26

**Comment by kniz-raft** [comment]
@shubhi-raft For the Raft Review, is that something I can complete? Or is this a team thing?

**Comment by shubhi-raft** [comment]
@kniz-raft can you review this against the AC and then if that makes sense you can move it to QASP review?

**Comment by shubhi-raft** [comment]
@kniz-raft Pulling this back into progress for our wed discussion and assigning you.

**Comment by kniz-raft** [comment]
I'm repurposing this ticket to cover what we decided for ATO.

**Comment by lfrohlich** [comment]
This is in a good place!
