### ISSUE TITLE
Fix user profile access for non-superusers from datafile object

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3120]
### Background ###
Currently, when clicking a user's email within the datafile object, the system redirects to the user's profile only for users with superuser access. For non-superusers, the click results in a 403 error. This behavior needs to be adjusted to ensure proper access control and more consistent user experience.

### Acceptance Criteria ###
- [ ] Users with superuser access can successfully navigate to a user’s profile by clicking on the email in the datafile object.
- [ ] Non-superusers are properly restricted from accessing the profile page, with a more appropriate message or behavior (e.g., a redirect or informative message instead of a 403 error).
- [ ] Testing Checklist has been run and all tests pass.
- [ ] README is updated, if necessary, to reflect the new access control behavior.

### Tasks ###
- [ ] Update the access control logic to differentiate behavior between superusers and non-superusers when clicking the email.
- [ ] Implement a user-friendly behavior for non-superusers (mailto: functionality)
- [ ] Update any necessary UI elements to reflect the changes in behavior.
- [ ] Run the Testing Checklist and confirm all tests pass.

**Comment by lhuxraft** [comment]
Needs further refinement to define Yun's role / add screenshots. Determine if mailto: functionality is the right solution here. Be careful around too much customization

**Comment by reitermb** [comment]
Further discussion needed--Sounds like there are a couple potential paths forward that have varying complexity to implement and deliver slightly different experiences for Yun. 

1. Make this link a mailto for non-superusers to add email client functionality 
2. Remove link entirely for non-superusers
3. Make a custom template so that non-superusers are linked to a fully read-only version of the users table 

Clarity from dev on relative lift + preferences from Yun & DIGIT should help inform this! 
cc @lhuxraft @ADPennington @raftmsohani @jtimpe
