### ISSUE TITLE
[Design Deliverable] Email template for system owner notification of assigned admin permissions

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3121]
**Description:**

Delivers email template to support 1337

**AC:**

- [ ] Template exists in [HTML email environment](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/)
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] Draft content 
- [ ] Review in a UX sync 
- [ ] Publish email template 

**Supporting Documentation:**

- [Email template link](url)
