### ISSUE TITLE
Descriptive error message in response to login error from login.gov

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#3135]
**Description:**
Follow up on #1621, template error page is shown when AMS login fails with a description of the error. Similar change is needed for when login to login.gov fails. 

**Acceptance Criteria:** 

- [ ] Template error page which includes the HTTP error code and short description of error will be shown to the user when an error happens during login to cloud.gov
- [ ] Error is descriptive enough for troubleshooting
- [ ] HTTP error code is included
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] change api login to return template page in case of error (for reference see #1621)
- [ ] write unit tests as needed
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by andrew-jameson** [comment]
PR merged and closed, ticket never entered sprint, accounting mistake, will close.
cc @vlasse86
