### ISSUE TITLE
[Design] As an OFA Analyst, I want to be notified when an STT submits TANF Data

### ISSUE THREAD

**Issue by matthewjdoty** [raft-tech/TANF-app#314]
**Problem Statement:** 
During the OFA interviews conducted in August 2020 (and as noted in OFA interview synthesis - issue #113), We observed that alerting OFA when STTs submit data may increase OFA efficiency would likely reduce ambiguity & repetitive manual communication." Additionally, all three OFA Analysts, when asked to describe how they know when STT data has been submitted, outlined a proactive process they need to remember to do as deadlines approach.
•	“I just download the data & check”
•	“We query the database, but what you really want to know is if the state tried to transmit”
•	“We've had to start getting proof of initial transmission”
•	“I know when it gets transmitted because it appears in the inbox”

We are creating this issue to design interactions that account for "Notification functionality for OFAs when STTs submit their data" (See next steps in the OFA synthesis document for issue #113).  

According to the latest [roadmap](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592336604317/61159efd030645a74c267130ea19b2083f87dd09), this should be part of MVP 

**Notes:**
- This is the design issue accounting for this feature. The Development issue(s) can be found here - (#???)

**Questions:**
- Is this needed for OFA MVP?

This is a follow-on to #

**AC:** 
- [ ] The problem we are trying to solve is clearly stated, as are questions we still have 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
  - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

**Tasks:**
Represented by Issue (#TBD)
- [ ] Draft low-fidelity conceptual mockup 
- [ ] Gather conceptual feedback from OFA, 18f, and Raft Development teams 
- [ ] Revise low-fidelity conceptual mockup and prep for concept testing

Represented by Issue (#TBD)
- [ ] Conduct concept testing with OFA Analysts

Represented by Issue (#TBD)
- [ ] Create high-fidelity, dev-ready prototype
- [ ] Check for accessibility 
- [ ] Check for AC
- [ ] Gather tactical feedback from OFA, 18f, and Raft Development teams 
- [ ] Revise high-fidelity, dev-ready prototype and prep for usablity testing
- [ ] Check for accessibility 
- [ ] Check for AC
- [ ] Conduct usability testing with OFA Analysts (Issue #TBD)
- [ ] Finalize high-fidelity, dev-ready prototype 
- [ ] Check for accessibility 
- [ ] Check for AC

**DoD:**
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

**Deliverables:**
Figma Designs: (Link)

**Comment by amilash** [comment]
@lfrohlich I've tagged this as a nice to have for the V2 Tribal release. What do you think? It could also go into v3.

**Comment by valcollignon** [comment]
This issue is related to #958 and #1395.
CC: @reitermb @sreedevip

**Comment by valcollignon** [comment]
We would like to build a new ticket, combining this issue with #958 and #1395 due to repetitiveness. We will discuss with @lfrohlich and @ADPennington at the next UX Sync.
CC: @sreedevip @reitermb

**Comment by ADPennington** [comment]
agree with closing this ticket in favor of the new ticket in hackmd which is more fleshed out, but I do think the user story for this ticket needs a little revision re: region @sreedevip @valcollignon @lfrohlich

**Comment by reitermb** [comment]
Now closeable with the addition of #1462 @lfrohlich
