### ISSUE TITLE
[Research Spike] Get more detail about Yun & DIGIT's data workflow and use cases

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3142]
**Description:**

Evaluates this high level flow for accuracy with Yun's processes:
Data access > data cleaning > data-related reports based on cleaner data > published data reports
Identify Frequency / Rationale for each

UX approach:  Map out more detailed plan for facilitating research in this area. Generate research questions in the above categories

Facilitate session w/ Yun poking at this process, diving into as much observation as we can for confirmed steps of the process (Likely requires multiple sessions)

**AC:**

- [x] Research sessions have occurred.
- [x] Anonymized session notes or other top-line synthesis have been documented.

**Tasks:**

- [x] Bring research plan to a UX sync
- [x] Schedule session w/ Yun
- [x] Facilitate session
- [x] Capture topline synthesis, identify next steps

**Supporting Documents**
[Test Plan](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/research-spike-plan-yun-and-digits-data-workflow-3142)

**Comment by victoriaatraft** [comment]
Updated description with [draft of test plan](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/research-drafts/test-plan-with-yun) to discuss in UX sync today. Also plan to share with dev to capture goals from [Data Access, Process and Mapping Discussion](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/)

**Comment by ADPennington** [comment]
@victoriaatraft @reitermb -- @ysong001 is generally available at 3p EST over the next few weeks. I am planning to look at the draft by end of this week.

**Comment by victoriaatraft** [comment]
@ADPennington @ysong001 How does Monday the 26th for 45 or 60 minutes sound? 
Then we can follow up with shorter timeframes after that. Happy to do another day, @reitermb will just be OOO  27th - 30th.

**Comment by ysong001** [comment]
okay for me

**Comment by victoriaatraft** [comment]
Awesome. I saw you accepted, thank you! We'll be sending in an email in just a few moments to give context for Monday :)

**Comment by victoriaatraft** [comment]
This ticket addresses the case plan and execution of the session. Top level analysis with follow up test plan to be captured in #3164. Want to confirm that this is okay to close. @robgendron 
cc @ADPennington @lfrohlich

**Comment by lfrohlich** [comment]
@victoriaatraft I think I was just confused by the use of the term "test plan" and didn't see it in #3164-- could you add detail to #3164 with deliverables (i.e. top level analysis and follow up test plan)? then we'll be good to close cc: @robgendron
