### ISSUE TITLE
Sprint 110 Release Notes/Knowledge Center 

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3149]
**Description:**
We've received feedback about the ftanf page. its outdated and suggests the transition from tdrs to tdp is still in progress. just a heads up that we need a ticket to track an update to this page. 

**AC:**
- [x] Content drafted in Gitbook
- [ ] Changes staged in Knowledge Center Test environment
- [ ] A11y tested

**Tasks:**
- [x] Draft content for: 
   - [x] ftanf page to reflect the legacy system having been decommissioned
   - [x] Fiscal vs Calendar table release notes 

**Notes:**
From August 15 Release Notes:
We have relaxed TDP's data processing requirements to help ensure that the data in your files can still be processed even if these files have an invalid value for the [update indicator](https://www.acf.hhs.gov/sites/default/files/documents/ofa/transmission_file_header_trailer_record.pdf). However, the TDP system expects the header update indicator to be set to "D" and if not, your error report will still include an error asking you to correct it. [Read more about the header record](https://tdp-project-updates.app.cloud.gov/knowledge-center/viewing-error-reports.html) and [how to export complete data using fTANF.](https://reitermb.github.io/Test/knowledge-center/exporting-complete-data-using-ftanf.html)

**Comment by reitermb** [comment]
Miles and Victoria to see whether this is a quick fix in error type PR

**Comment by victoriaatraft** [comment]
Repurposed to encompass sprint 110 release notes/kc updates

**Comment by ADPennington** [comment]
@victoriaatraft -- is this the ticket for this sprint's release notes? cc: @klinkoberstar

**Comment by victoriaatraft** [comment]
@ADPennington @lfrohlich @klinkoberstar To confirm, the[ ftanf page that you're referring too is this one](https://reitermb.github.io/Test/knowledge-center/exporting-complete-data-using-ftanf.html ), correct?

**Comment by victoriaatraft** [comment]
> @victoriaatraft -- is this the ticket for this sprint's release notes? cc: @klinkoberstar

Yes! Looking back we're going to make a release notes ticket for every sprint in the event we need to track a release, but I think we'll need your go ahead if we plan to release something next week. 

Here is the draft for the release notes content: https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/oct-xx-release-notes

I made a sub draft page underneath that gitbook page it for the[ FTANF page updates](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/oct-xx-release-notes/ftanf-updates).

**Comment by klinkoberstar** [comment]
@victoriaatraft Based on my conversation with @ADPennington today we confirmed that the upcoming release notes will only include notes for #3109 (language was already reviewed in the last release notes cycle)

The other tickets that were under consideration will not require release notes:

- #3014 - still requires some testing and will likely not be approved in time
- #3106 - will send System Database Maintenance notification (Alex to send) but no release notes needed

I left one small comment on the fTANF language
