### ISSUE TITLE
Release Notes Knowledge Center and Email Template

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3156]
**Deliver Release Notes For:**
- #3122 Approved
- #3051 In progress

**AC:**
- [x]  Internal Raft Review has occurred to ensure DoD standards and QA
- [x]  The design is usable and accessible, meaning it adheres to definition of done standards for design work.

**Tasks:**

- [x]  Plug HTML template into email test service and create a forwardable format
- [x]  Send draft to Alex, Thomas, TANFdata
- [x] Update [KC page on common errors](https://tdp-project-updates.app.cloud.gov/knowledge-center/viewing-error-reports.html#overview-of-the-error-report:~:text=Examples%20of%20Common%20Errors), as applicable

**Deliverables:**
[Draft Content](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-emails/august-29th-release-notes-email)

**Comment by ADPennington** [comment]
Want to jot this idea here so I don't forget. I wonder if we should host a series of weekly or biweekly office hours to answer questions? to help keep it manageable maybe we let up to 3-5 STTs sign up per session? this may also create an organic opportunity for UX research? thoughts @victoriaatraft @lfrohlich  ?

**Comment by victoriaatraft** [comment]
@ADPennington I would be open to this for sure! I can add this to the UX agenda. Another idea to add/explore to the idea basket --  if we had the capability... a community forum of the sort like, like a reddit. Adobe and figma leverage forums as a method to answer common questions when there's not a large support infrastructure.

**Comment by ADPennington** [comment]
thanks @victoriaatraft -- this is an interesting idea--worth discussing in the next sync. 

I've made some edits to the draft and would like to think more about the last section of the release notes regarding user feedback and terminology:

- we may want to consider leading with that section. 
- this section may also be a place for us to signal that we're thinking through some opportunities to connect with partners to discuss the TDP error report: terminology, what errors mean, etc. 

Discussed next steps with @lfrohlich -- and we think that we can keep working on refining these notes next week. Since a holiday is approaching, the [next release](https://github.com/raft-tech/TANF-app/releases/tag/v3.6.0-Sprint-105) to prod will be scheduled for the second half of next week.

**Comment by victoriaatraft** [comment]
Sounds good. Thank you. @ADPennington document is updated with your said edits, release notes convo added to ux sync agenda and updated the email send to Sept 5

**Comment by victoriaatraft** [comment]
Creating PR for KC Updates. Preview on test: https://reitermb.github.io/Test/knowledge-center/
 @ADPennington @reitermb

**Comment by ADPennington** [comment]
email and KC release notes completed on 9/10.
