### ISSUE TITLE
Reparse Model Field Additions

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3157]
**Description:**
As a follow on to #3064 it would be nice to have a few more fields added to the meta model. Adding a "time_completed" datetime field will be useful to know how long the event took to reparse all files. Also, tracking cat4 errors before and after the reparse will be helpful to help admins justify when the the "num records deleted" and the "num records created" diverge. We might also consider tying individual counts of cat4 errors to each file as opposed an aggregate for all files.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] ReparseMeta model as new "finished_at" datetime field and cat4 tracking field
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Custom migration is written to populate existing ReparseMeta models with valid values. The new "finished_at" field should be populated with the existing `timeout_at` field. The cat4 count field should be added based on what is implemented.
- [x] Add new fields to model
- [x] Add logic to set fields when reparsing
- [x] Write custom migration
- [ ] Test custom migration
- [x] Test fields are updated when reparsing
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
