### ISSUE TITLE
Ensure item number column includes all relevant items associated with cat 3 errors

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3161]
**Description**

For `Category 3: Record Consistency` error messages, the error report's item number column only includes one of the item numbers associated with the error, but should include all relevant item numbers. Some example error reports are included below for reference. In the screenshot below, for example, We should expect Items 14 and 16 in the item number column, but only see item 14. 

![Screenshot 2024-12-20 123538](https://github.com/user-attachments/assets/8466c355-0fba-45ea-a9db-0fc7de77e18e)

**Acceptance Criteria**
- [ ] TANF/SSP/Tribal Active error reports w/ cat 3 errors include all relevant item numbers in column. 
- [ ] TANF/SSP/Tribal Closed error reports w/ cat 3 errors include all relevant  item numbers in column. 
- [ ] TANF/SSP/Tribal Aggregate error reports w/ cat 3 errors include all relevant item numbers in column. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks**
- [ ] Determine if a new field should be created or if the existing field should be updated to support multiple values??
- [ ] Run Testing Checklist and confirm all tests pass

**Notes**
- Applicable to TANF, SSP, and Tribal TANF Active, Closed, and Aggregate files

**Supporting Documentation**
 - PR comment originally posted by @jtimpe in https://github.com/raft-tech/TANF-app/issues/3122#issuecomment-2315755271
 - Closed file error report example: [2024-Q4-Closed Case Data_3161.xlsx](https://github.com/user-attachments/files/18213664/2024-Q4-Closed.Case.Data_3161.xlsx)
 - Active file error report example: [2024-Q1-Active Case Data_3161.xlsx](https://github.com/user-attachments/files/18213672/2024-Q1-Active.Case.Data_3161.xlsx)
 - Aggregate file error report example: [2022-Q1-Aggregate Data_3161.xlsx](https://github.com/user-attachments/files/18213748/2022-Q1-Aggregate.Data_3161.xlsx)

**Comment by lhuxraft** [comment]
Alex to further refine

**Comment by ADPennington** [comment]
> Alex to further refine

updated @lhuxraft

**Comment by lhuxraft** [comment]
Discuss as part of FRA frontend ticket when Jan is back
