### ISSUE TITLE
CircleCI pipeline utilizes internal Nexus infrastructure

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3171]
**Description:**
To fully insulate our pipeline being broken by issues out of our control via upstream issues, we should ensure all steps can be self-sufficient within our infrastructure. For higher environments (HHS repo), we should ensure backwards compatibility with standard internet mirrors

**Acceptance Criteria:** 

- [x] Pipeline builds don't reach out to the internet by default
- [x] Pipeline builds will fail-through to internet repositories if Nexus connection fails
- [x] Pipeline build times are reduced
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Apt repo configured
- [x] NPM repo configured
- [x] PyPI repo configured
- [x] Have CloudFoundry CLI be available in the pipeline through Nexus
- [x] Have alternative sources point to our standard internet repositories
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
Implementation of a base image is out of scope, this is an infrastructure buildout.

**Supporting Documentation:**

**Open Questions:**

- How do we build once and reference the docker image moving forward? Out of scope, will generate another docker-nexus ticket.
- How do we correctly cache dependencies/images? Out of scope, will generate another docker-nexus ticket.
-

**Comment by andrew-jameson** [comment]
Implemented apt and pypi repositories MVP within #3141
