### ISSUE TITLE
Re-add Error Type column to Error Reports

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3180]
**Description:**
We plan to help certain STTs encountering a high volume of errors by leveraging error type as a way to direct their attention toward the highest priority issues first as a more tackle-able subset of error corrections. Not blocked by but relates to #3181 

**Acceptance Criteria:** 
- [ ] (friendly version) Error Type column appears in error reports
- [ ] Error type column appears as the right-most column
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Adjust error report generation to include error type column (friendly name error category version, not a numeric)
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by ADPennington** [comment]
@reitermb @victoriaatraft @klinkoberstar -- im starting review the PR for this ticket today. this will need release notes.

**Comment by ADPennington** [comment]
> @reitermb @victoriaatraft @klinkoberstar -- im starting review the PR for this ticket today. this will need release notes.

@ttran-hub and I paired on review of this ticket, and wanted to share some info to help inform the release notes :)

- test file used: [test_error_messages.txt.txt](https://github.com/user-attachments/files/17196513/test_error_messages.txt.txt)
- TDP error report associated with the test file: [2023-Q1-Active Case Data_feedbackrpt.xlsx](https://github.com/user-attachments/files/17196526/2023-Q1-Active.Case.Data_feedbackrpt.xlsx)
- error type definitions are below. As a reminder, we refer to categories internally, but STTs are not familiar with "category" terminology:
  - File pre-check (AKA category 1)
  - Record value invalid (AKA category 2)
  - Record value consistency (AKA category 3)
  - Case consistency (AKA category 4)


@reitermb @victoriaatraft @klinkoberstar
