### ISSUE TITLE
[Design Deliverable] Update Knowledge Center with Error Type guidance and Release Notes Email

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3181]
**Description:**

Supports #3180

**AC:**

- [x] Error guide page is updated with error type guidance
- [x] Screenshots are updated
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft content addition in gitbook
- [x] Update screenshots
- [x] Draft PR

**Comment by ADPennington** [comment]
for team awareness @victoriaatraft @reitermb @ttran-hub @lfrohlich 

- this ticket will deliver KC guidance related to error type column. @klinkoberstar will support this ticket based on artifacts [here](https://github.com/raft-tech/TANF-app/issues/3180#issuecomment-2384169375)
- we have some concerns about the error type description, so we think it will be important to start to provide critical guidance on these error types in the release notes. @klinkoberstar will share a working draft

**Comment by klinkoberstar** [comment]
@victoriaatraft @reitermb @ttran-hub @lfrohlich

based on discussions with @ADPennington, I've put together a starting draft of release notes.

Goals:
- Notify users that error type column exists
- Briefly introduce concept of error type
- Support users in turning on filter to view high priority errors

_____

<html>
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>

<b style='margin:0in;font-family:Calibri;font-size:14.0pt'>New Error Type Column Added to Error Report</b>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>To improve error
identification and prioritization, a new column called &quot;Error Type&quot;
has been added to error reports. This feature will help users quickly find and
filter high-priority errors affecting file submission.</p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>The new column
categorizes errors by their priority and impact on file status. There are four
types of errors.</p>

<div style='direction:ltr'>

Error Type | Priority | Impact | File Status
-- | -- | -- | --
File Pre-Check | High | Entire file will   be rejected. | Rejected
Case Consistency | High | Record rejected. | Partially Accepted   with errors
Record Value   Invalid | Low | Record accepted. | Accepted with   errors
Record Value   Inconsistency | Low | Record accepted. | Accepted with   errors

</div>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>To filter High
Priority Errors:</p>

<ol type=1 style='direction:ltr;unicode-bidi:embed;margin-top:0in;margin-bottom:
 0in;font-family:Calibri;font-size:11.0pt;font-weight:normal;font-style:normal'>
 <li value=1 style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
     style='font-family:Calibri;font-size:11.0pt;font-weight:normal;font-style:
     normal;font-family:Calibri;font-size:11.0pt'>Download the </span><a
     href="https://tdp-project-updates.app.cloud.gov/knowledge-center/view-submission-history.html#:~:text=Download%20Error%20Reports%20and%20Previously%20Submitted%20Data%20Files"><span
     style='font-family:Calibri;font-size:11.0pt;font-family:Calibri;
     font-size:11.0pt'>Error Report</span></a><span style='font-family:Calibri;
     font-size:11.0pt;font-weight:normal;font-style:normal;font-family:Calibri;
     font-size:11.0pt'>.</span></li>
 <li style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
     style='font-family:Calibri;font-size:11.0pt'>Select </span><span
     style='font-weight:bold;font-family:Calibri;font-size:11.0pt'>Row 6.</span></li>
 <li style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
     style='font-family:Calibri;font-size:11.0pt'>Navigate to </span><span
     style='font-weight:bold;font-family:Calibri;font-size:11.0pt'>Data &gt;
     Format</span><span style='font-family:Calibri;font-size:11.0pt'>, Select </span><span
     style='font-weight:bold;font-family:Calibri;font-size:11.0pt'>Filter.</span></li>
 <li style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
     style='font-family:Calibri;font-size:11.0pt'>Scroll to the right and find
     the</span><span style='font-weight:bold;font-family:Calibri;font-size:
     11.0pt'> Error Type</span><span style='font-family:Calibri;font-size:11.0pt'>
     column.</span></li>
 <li style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
     style='font-family:Calibri;font-size:11.0pt'>Use the filter options to
     prioritize:</span></li>
 <ol type=a style='direction:ltr;unicode-bidi:embed;margin-top:0in;margin-bottom:
  0in;font-family:Calibri;font-size:11.0pt;font-weight:normal;font-style:normal'>
  <li value=1 style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
      style='font-family:Calibri;font-size:11.0pt;font-weight:normal;
      font-style:normal;font-family:Calibri;font-size:11.0pt'>File Pre-Check</span></li>
  <li style='margin-top:0;margin-bottom:0;vertical-align:middle'><span
      style='font-family:Calibri;font-size:11.0pt'>Case Consistency </span></li>
 </ol>
</ol>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>This will highlight
errors that most significantly affect your file submission. </p>

<p style='margin:0in;font-family:Calibri;font-size:11.0pt'>Detailed guidance on
these new error types and their implications for file submissions is available
in the <a
href="https://tdp-project-updates.app.cloud.gov/knowledge-center/viewing-error-reports.html#:~:text=e.g.%20YYYYMMDD).-,Overview%20of%20the%20Error%20Report,-TDP%27s%20error%20reports">Knowledge
Center.</a></p>

</body>

</html>

**Comment by klinkoberstar** [comment]
@victoriaatraft @reitermb @ttran-hub @lfrohlich

based on discussions with @ADPennington, I've put together a starting draft of KC updates.

Goals:
- Provide a detailed explanation of Error Types with examples
- Connect the dots between the error report and submission status by illustrating the series of checks that files and records go through in order to:
        - Demystify the process of error checking and generating submission status
        - Help users prioritize errors to address first by providing information on error severity
        - Provide users familiar with the legacy Fatal/Warning Edit classification with a similar indicator of severity

_Note: Alex and I are working on a flow to visualize validation checks and resulting error types/file submission status which will help with the second goal; KC can be updated iteratively if this isn't ready in time_

___

[KC Draft Proposed Update](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/_layouts/OneNote.aspx?id=%2Fsites%2FTDRSResearchDesign%2FSiteAssets%2FTDRS%20Research%20%26%20Design%20Notebook&wd=target%28Understanding%20Error%20Reports%20and%20File%20Structure.one%7CE9911C37-DB40-4947-A455-EE04ED3ACC41%2FDraft%20Updates%3A%20Understanding%20Error%20Reports%20and%20File%20Structure%7C28E4C80A-D477-46EB-9F6B-F38752415436%2F%29)

**Comment by victoriaatraft** [comment]
@klinkoberstar @lfrohlich [Draft of the release notes/email template here on gitbook](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/oct-8th-release-notes).
