### ISSUE TITLE
Performance Monitoring ADR

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3199]
**Description:**
_Provide a brief background and justification for this issue_
_OFA & UX team: Please include bullets capturing the value to STT end users, related guidance, and/or talking points that should be communicated to STTs in release notes_

**Acceptance Criteria:** 

- [ ] Architecture Decision Record for Application Health Monitoring with expected audience of OCIO
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by lfrohlich** [comment]
Discussed in IPT with ACF Tech on 10/23 -- need to update boundary diagram, SSP
Still need clarity on authentication @ADPennington  @andrew-jameson
