### ISSUE TITLE
Re-parse command refactor

### ISSUE THREAD

**Issue by raftmsohani** [raft-tech/TANF-app#3205]
**Description:**
Follow up on #3106, re-parse command button shares reparse logic with management command. Basically, the command button calls the management command.

We want to create a new utility function to share part of reparsing command logic and create a reparse admin command logic which enables us to customize logic between the two.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Reparse admin command runs from a function and not management command
- [ ] Reparse management command is simplified
- [ ] A utility function is created as a help function for both management and admin command reparse
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Refactor [clean_and_reparse](tdrs-backend/tdpservice/search_indexes/management/commands/clean_and_reparse.py) command and decompose management command from admin action reparse command
- [ ] Create a utility function and move body of reparsing code to utility function
- [ ] Create a separate function for parsing admin command which performs reparsing when called by reaprse command from admin button. This function uses the same utility function created in the step above
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- What error handling updates to we want to add to django admin action?
- Do we want to sunset management command?

**Comment by jtimpe** [comment]
per [comment thread on 3106](https://github.com/raft-tech/TANF-app/pull/3167#discussion_r1804916475), we may also revisit logging when separating the action and management command

**Comment by lhuxraft** [comment]
12/11: 35-40% done with code changes

**Comment by lhuxraft** [comment]
12/16: Tests are passing, need to clean up management command. 50% complete
