### ISSUE TITLE
(Internal) Migrate items from wiki to Code<> doc 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#321]
**Description:**
Follow-on to #305 . This issue will deliver migration of all the items - in HHS TANF wiki -  in the table of contents with a 'Move' label. 

**Acceptance Criteria:** 

- [x] Tasks below have been completed 

**Tasks:**

- [x] ~~Alex~~ Miles works on a second PR that migrates over the wiki contents 
- [x]  ~~When ready, Lauren, Shubi, Alex (+anyone else interested) gather up and look over PR together, we merge in the PR when Lauren gives it a 👍~~ Async communication determined code doc structure / transferring via 1 PR to simplify
- [x]  For research items, Miles creates a 3rd PR that migrates any remaining user research items from Teams
- [x]  ~~Lauren, Shubi, Selena, Alex, (+anyone else interested) gather up and look over PR together; we merge in the PR when Lauren gives it a 👍~~ Async communication determined code doc structure / transferring via 1 PR to simplify
- [x] For design items, Dmitri organizes any remaining design items from Teams for migration
- [ ] ~~Lauren, Shubi, Selena, Alex, (+anyone else interested) gather up and look over PR together; we merge in the PR when Lauren gives it a 👍~~
- [x] Remove the wiki in order to have a single source of truth. 
- [x] Make a note in the docs folder about who helped author these docs for attribution, since removing the wiki would remove the attribution history

**Notes:**
 - This will follow in the tail end of the Sprint 6
 - Communicate loudly - teams/standup
 - This is going to make changes to Gov repo so Raft team may need to aware or may have merge conflicts
-  Create new issues for (demoing process for PR for markdown) + defining IA for docs (follow how wiki lays out table of contents)

**Supporting Documentation:**
NA

**Open Questions:**
NA

**Comment by reitermb** [comment]
[PR is now open in the HHS repo ](https://github.com/HHS/TANF-app/pull/80)

**Comment by alexsoble** [comment]
The last two steps here are finished:

+ Added Contributors section: https://github.com/HHS/TANF-app/pull/103
+ @lfrohlich disabled Wiki section (underlying data still there, but Wiki now hidden)

**Comment by lfrohlich** [comment]
This was closed 12/11
