### ISSUE TITLE
Create system uptime dashboard with metrics

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3217]
### Background ###
Create an uptime dashboard that provides indicators of overall system stability. This dashboard should visually represent system uptime metrics to help monitor performance and reliability. Dependency/blocked on/by #3046.

### Acceptance Criteria ###
- [ ] Dashboard displays cumulative uptime and/or percentage. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [x] Develop visualization(s) and/or summary statistics displaying calculated uptime and/or percentage.
- [x] Ensure data collection is implemented for uptime metrics.
- [x] Ensure the dashboard updates at regular intervals with real-time or near-real-time data.
- [ ] Run Testing Checklist and confirm all tests pass

### Notes ###
- Feel free to be creative with this! If there's additional breakdowns of uptime that you think would be helpful and are minimal effort (e.g., uptime breakdowns by service, alerts/logging in the dashboard itself), that could be a value add as well. This is intended to be relatively open-ended.

**Comment by lhuxraft** [comment]
Note: rewriting ticket to remove email alerts component of this while uncertainty exists around SendGrid - we may still want a follow-on to create email alerts at a later date once SendGrid exception is resolved
