### ISSUE TITLE
[Design Deliverable] Supports 3028

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3218]
**Description:**

—Describe the scope of ticket and problem to be solved. Reference any related tickets that might be helpful to cite for design, discussion, or review. These should typically range between 3 and 13 points.—

**Related User Stories:**

—As a [user type] I want the page to exist so that I can see it.—

**Recommended pa11y actions:**

—‘click element #error-report’,—

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] —Draft design in Figma—

**Supporting Documentation:**

—Link to Figma and Dev-Ready Design folder PDF—

**Comment by lhuxraft** [comment]
Tracking work in 3028, closing
