### ISSUE TITLE
Automate Buildpack states via Terraform

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3223]
**Description:**
Given recent updates coming from #3192 , we are seeing a surge in new manifest files which really highlights our lack of state visibility and control. From a recent call with Cloud.gov, they indicate the CloudFoundry provider for Terraform has been updated and should be usable.

**Acceptance Criteria:** 
- [x] Terraform retains state visibility of all spaces
- [ ] Terraform only redeploys apps/state needing updating
- [x] CircleCI deployment pipelines still used
- [ ] Project Deployment/Cloud documentation is updated
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [x] Spike + technical documentation to write tech memo
- [x] Move manifest command blocks to runnable bash scripts
- [x] Service instances under Terraform control
- [x] CF networking and routing under Terraform control
- [x] Primary apps (nginx, react, django) under Terraform control
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Cloud.gov sample code](https://github.com/cloud-gov/deploy-cf/tree/main/terraform/stacks/cf)
- [CloudFoundry provider doc](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs)

**Open Questions:**
- What shouldn't be under Terraform control in this first pass and/or ever?
- Terraform CircleCI pipelines show granularity of steps?

**Comment by lhuxraft** [comment]
Scope down to only the first task for this sprint

**Comment by lhuxraft** [comment]
11/22: Started on tech memo and documentation. Playing around with the provider

**Comment by lhuxraft** [comment]
12/4: Working on tech memo draft, making progress

**Comment by lhuxraft** [comment]
12/9: Working to incorporate new providers into Terraform setup, tech memo in a good state

**Comment by lhuxraft** [comment]
12/13: Struggling with gap in documentation, to discuss in office hours

**Comment by lhuxraft** [comment]
12/16: Unblocked, recreating manifest to give cloud foundry expected input (unexpected scripting)

**Comment by lhuxraft** [comment]
12/18: Rewriting deployment logic to account for packaging and be more compatible with zipper utility

**Comment by lhuxraft** [comment]
12/30: Successful deployment of frontend, reworking workflow logic

**Comment by andrew-jameson** [comment]
[This Cloud.gov announcement](https://cloud.gov/2025/01/07/v2api-deprecation/) published 3 days ago references a new v3 provider (which we haven't used prior). Switching to this provider will set back our progress using the existing [provider](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry) as there is not overlap. The documentation on the newer provider is just as sparse but there is example code [here](https://github.com/cloudfoundry/terraform-provider-cloudfoundry/tree/main/examples).

**Comment by andrew-jameson** [comment]
After discussion with the wider team, will be discontinuing development of this system as complexity and costs do not outweigh the benefits within our limited cloudfoundry implementation.
