### ISSUE TITLE
Audit Logger

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3224]
**Description:**
We would like to perform an audit of the information that is being logged to the console in the backend. We want to avoid logging any PII or other sensitive information.

**Acceptance Criteria:** 

- [ ] No PII or other sensitive information is logged to the console or file
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Check all logging statements in the backend for sensitive of PII and update appropriately
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- Alex can provide info on what fields in records are considered sensitive or PII.
    - SSN, DoB, case number containing SSN?, email address, user pass (see privacy act statement/doc)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by ADPennington** [comment]
@elipe17 some evidence of sensitive PII fields in the logs below (note: this is not real PII, im testing reparsing in qasp env)

![partial_hash](https://github.com/user-attachments/assets/436250e4-7e68-40b0-9443-96981f15d965)

**Comment by raftmsohani** [comment]
Created this snippet of code to export all error lines into excel and perform investigation:

```
import os

def is_parentheses_balanced(string):
    """
    Checks if parentheses are balanced in a string.
    """

    stack = []
    for char in string:
        if char == '(':
            stack.append(char)
        elif char == ')':
            if not stack:
                return False  # Closing parenthesis with no matching opening
            stack.pop()

    return not stack

def search_subdirectories(root_dir):
    """Searches all subdirectories for a given file."""
    with open("log_messages.txt", "w") as output_file:
        for dirpath, dirnames, filenames in os.walk(root_dir):
            # open each file and search for log messages
            for filename in filenames:
                if filename.endswith(".py"):
                    with open(dirpath + "/" + filename, "r") as file:
                        log_message = ""
                        for line_number, line in enumerate(file):
                            if "log(" in line or "logger." in line:
                                log_message = line.strip()
                                if is_parentheses_balanced(log_message):
                                        output_file.write(filename + "|" + str(line_number) + "|" + log_message + "\n")
                                        log_message = ""
                            elif "log(" in log_message or "logger." in log_message:
                                log_message += line.strip()
                                if is_parentheses_balanced(log_message):
                                    output_file.write(filename + "|" + str(line_number) + "|" + log_message + "\n")
                                    log_message = ""
```

**Comment by raftmsohani** [comment]
[log_messages.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU4vQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb658a68058401e18b71efd4c8be33a0188e3ae7/log_messages.xlsx)

**Comment by lhuxraft** [comment]
11/18: Need more time to review

**Comment by lhuxraft** [comment]
11/20: Still working through review, Alex to sync with Mo over the next couple days

**Comment by lhuxraft** [comment]
11/22: Mo and Alex met this morning, spun up an epic. Ready for Alex to do a final review

**Comment by lhuxraft** [comment]
11/25: Ready to merge, Eric to merge
