### ISSUE TITLE
[Research Planning] FRA Research

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3225]
**Description:**

Delivers research plan for MVP FRA Research

**AC:**
- [x] A research plan has been created which includes:
    - [x] Research goals, relevant research questions.
    - [x] Recruitment criteria & target participants.
    - [x] Recruitment/participation email templates.
    - [x] Timeline (for recruitment and for research sessions).
    - [x] Testable Designs/Content (if applicable)
  - [x] Ethics, privacy concerns 

**Tasks:**
- [x] Channel roadmap scope conversations into a refined UX roadmap item
- [x] Refine research plan document
- [x] Write research recruiting emails
- [x] Generate squishy prototype of FRA MVP experience
- [x] Review in UX Syncs / spin ups
- [x] Ticket next-steps

**Supporting Documentation:**
- [Research plan](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan)
- [Figma ideations](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9284-1183&t=uVBYIX3DmzBG7MKv-1)

**Comment by victoriaatraft** [comment]
Comments received on the [gitbook draft][Gitbook Research Planning and Discovery](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/research-planning-and-discovery-3193)(also in supporting documents above) for feedback by @lfrohlich from UX sync on 10/15 and @andrew-jameson to also review from Internal sync on 10/15 and rough list of items dev can tackle from a light lift perspective to incorporate in the planning chart in tandem research efforts.

@victoriaatraft working through [the Mural ](https://app.mural.co/t/raft2792/m/raft2792/1727290532610/6aa6777c80afd0eb6cd7b17ec569f2afa991e692?sender=uf443e00cb4626b8bec157528)to connect MVP efforts with the gitbook draft, but may need @reitermb input after vacation to fill gaps.

cc: @klinkoberstar @ADPennington, feel free to also review and make comments

**Comment by vlasse86** [comment]
Targeting 10/25 for the prototype delivery.

**Comment by reitermb** [comment]
The planning doc is ready for another pass on for initial Q&A and alignment purposes! cc @lfrohlich @ADPennington @klinkoberstar 

https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan

**Comment by reitermb** [comment]
Initial concept mockups are now also prepared here: https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9284-1183&t=uVBYIX3DmzBG7MKv-1

I still have some integration to do of key open questions emerging from the ideation work into the research plan but concepts should be far enough along to be a useful aid to discussion. We'll be tagging in the dev team for reactions and general cross-functional discussion and any reactions/thoughts/contributions to open questions are welcomed from the OFA side as well! 

Discussion of these ideations and the written research plan is currently on the agenda for UX Sync on the 29th. 

Noting that we don't plan to include research specific to FRA Report 2 and 3 in this research cycle but some early (read: squishier) ideas relevant to those reports is also present in the Figma under the "Future FRA" heading. We'll prioritize discussion relevant to Report 1 above that of future FRA reports, but please feel free to ask questions/make comment there as well. 

cc @lfrohlich @ADPennington @klinkoberstar

**Comment by victoriaatraft** [comment]
Deliverables for this ticket are in the description under supporting documentation. 
[Research plan](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan)
[Figma ideations](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9284-1183&t=uVBYIX3DmzBG7MKv-1)

@reitermb has spun up additional supporting tickets to continue the research: 
#3267 [Research Recruitment] FRA Research 
#3265  [Research Facilitation Prep] Finalize Prototypes for FRA research sessions

This ticket just needs @lfrohlich thumbs up and ready to close
cc: @klinkoberstar @ADPennington

**Comment by lfrohlich** [comment]
Looks good to me, thanks!
