### ISSUE TITLE
[Design Deliverable] Service Blueprint

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3230]
**The Value of a Service Blueprint Artifact**
A service blueprint is a diagram that visualizes the relationships between different service components — people, props (physical or digital evidence), and processes — that are directly tied to touchpoints in a specific customer journey.

For this effort, the blueprint allows us to see how the **current processes workflows** implemented. Additionally, you are able to literally see and identify gaps where research can be conducted to understand how UX can better enhance the experience with TDP and DIGIT's reporting workflows and processes. 

 **Ticket Description:**
Delivers a service map specifically giving an overview of Yun's workflow and processes with data and reporting. Validates our understanding of OFA data workflow, "reporting" related touchpoints along it with STTs, and ideates on report and product requirements

Related to #3193 

**AC:**

- [x] Documentation work for the following has occurred:
   - [x] Relevant User stories.
   - [x] Recommended pa11y checks.
   - [x] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [x] Internal Raft Review has occurred to ensure DoD standards and QA
- [x] Dev/Design sync has occurred; resulting tickets created
- [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [x] Draft designs in Figma
- [x] Work with Alex to refine areas
- [x] Receive feedback from Dev/Digit Team

**Supporting Documentation and Deliverables:**

[Figma Service blueprint](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9080-4762&node-type=canvas)

**Comment by victoriaatraft** [comment]
Meeting on Oct 16th with Alex to go over specific areas of the service map that involves system validation and Yun's interactions with the data stored in the raw database
![image](https://github.com/user-attachments/assets/9b6c95b9-91ec-4fec-bc56-8cf2a58d40b4)

**Comment by victoriaatraft** [comment]
Update: Been tracking progress in the associated ticket: https://github.com/raft-tech/TANF-app/issues/3193
Perhaps to close this ticket, until the blueprint can be further built out in the future, we quickly verify that the submission workflow from the Mural is cohesive with the Service Blue Print is captured accurately.

**Comment by lhuxraft** [comment]
11/13/2024: Updated ticket to show value of service blueprint, added comment above to share progress. Will move to Raft review today

**Comment by victoriaatraft** [comment]
Perhaps to close this ticket, until the blueprint can be further built out in the future, for this ticket/V1, we can verify that the submission workflow from the Mural is cohesive with the Service Blue Print and is captured accurately which is the first part of the blueprint below. And another idea: to update service blueprint as part of ACs for related research efforts in the future.

Open to your thoughts and can also touch on this in the #3249 Design Spec Meeting 
@klinkoberstar @ADPennington @lfrohlich 
cc @reitermb @lhuxraft 

![Service BlueprintV1](https://github.com/user-attachments/assets/b56296e4-5b47-4e8f-ad03-070658dc522a)

**Comment by lhuxraft** [comment]
11/15: Touch base in design specs meeting before closing. Victoria will review with devs in office hours

**Comment by victoriaatraft** [comment]
Final mile notes
@klinkoberstar take initial first pass and when ready and then I'll schedule a 30 minute meeting to triage review to make any live edits to finish cc @ADPennington @lfrohlich  @lhuxraft 
@andrew-jameson will bring this into office hours once the above has been satisfied. 

Here's the [figma](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9080-4762&node-type=canvas) if you need to zoom in more and you can add comments o the page directly

**Comment by klinkoberstar** [comment]
> Final mile notes @klinkoberstar take initial first pass and when ready and then I'll schedule a 30 minute meeting to triage review to make any live edits to finish cc @ADPennington @lfrohlich @lhuxraft @andrew-jameson will bring this into office hours once the above has been satisfied.
> 
> Here's the [figma](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9080-4762&node-type=canvas) if you need to zoom in more and you can add comments o the page directly

One quick add: Victoria has a great idea to make updating the blueprint an Acceptance Criteria for any tickets that impact the service blueprint going forward

**Comment by victoriaatraft** [comment]
> > Final mile notes @klinkoberstar take initial first pass and when ready and then I'll schedule a 30 minute meeting to triage review to make any live edits to finish cc @ADPennington @lfrohlich @lhuxraft @andrew-jameson will bring this into office hours once the above has been satisfied.
> > Here's the [figma](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9080-4762&node-type=canvas) if you need to zoom in more and you can add comments o the page directly
> 
> One quick add: Victoria has a great idea to make updating the blueprint an Acceptance Criteria for any tickets that impact the service blueprint going forward

Just proposed changes/created PRs to making edits to the templates when creating issues for UX design deliverables and UX synthesis to update the service blue prints as applicable with the link so it's always in there 😊

**Comment by lhuxraft** [comment]
11/18: Syncing with Kathryn today

**Comment by lhuxraft** [comment]
11/19: Alex/Kathryn reviewed yesterday, final sync to close out the ticket this afternoon

**Comment by lhuxraft** [comment]
11/20: Final edits being made after final mile

**Comment by lhuxraft** [comment]
11/22: Doing final checks, PM to take a final review

**Comment by lhuxraft** [comment]
11/25: Met with Kathryn on Friday, changes are made. Left some comments open for tracking purposes. Will be presented when folks are back from holiday. Sync on this after UX sync tomorrow

**Comment by ADPennington** [comment]
@victoriaatraft walked me through the service blueprint and its in good shape! TY! this ticket is good to close. cc: @lhuxraft @klinkoberstar @lfrohlich @reitermb

**Comment by victoriaatraft** [comment]
![Service Blueprint Nov 26](https://github.com/user-attachments/assets/a353b05e-b5ae-4252-b1ca-f540f5f890db)
![Error Checks Detailed Flow](https://github.com/user-attachments/assets/1f835c9e-1b9c-482f-a9d2-380f18777627)
