### ISSUE TITLE
Optimize CircleCI pipeline with Docker image tagging and promotion

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3233]
### Background ###
To prevent the duplication of pipeline image builds, we aim to optimize the CircleCI pipeline by building the Docker image once and reusing it in future builds. This will be achieved by implementing a system for tagging and promoting images through different tiers in Nexus, reducing build times and improving pipeline efficiency.

Note: This is out of scope for #3171 but will complement efforts to streamline our CI/CD process.

_OFA & UX Team: Please include bullets for end user benefits, guidance, and any talking points for STTs in the release notes._

### Acceptance Criteria ###
- [ ] CircleCI Pipeline execution time should be notable faster
- [ ] Promotion and tagging system is documented and as intuitive as possible
- [ ] Nexus houses docker images
- [ ] HHS pipelines should not be inhibited
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Spike + technical documentation to write a tech memo for operational approach, tagging paradigm, and scripting scope
- [ ] Configure Nexus tagging and storage
- [ ] Write script(s) to implement promotion and re-use of docker images
- [ ] Test for our use-cases: local, features pipeline, develop pipeline, release paths
- [ ] [STRETCH] Write test script for use within pipelines
- [ ] Run Testing Checklist and confirm all tests pass

### Open Questions ###
- Are there existing systems/libraries we can use for this instead of home-rolling our own which might contain bugs?
- How do we deprecate/delete older images?
- Can we intuitively associate image identifier with branches and/or releases?

**Comment by lhuxraft** [comment]
May be closed after Nexus is decommissioned
