### ISSUE TITLE
Local Alertmanager

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3242]
**Description:**
As our monitoring capabilities enhance, we need a method to alert on logs, or metrics we are tracking. In this ticket we want to integrate [Alertmanager](https://prometheus.io/docs/alerting/latest/overview/) with our PLG stack to enable fine grained alerting capabilities. As an MVP implementation, we would like to integrate SendGrid with Alertmanager to notify the appropriate parties of some issue. The goal is to implement Prometheus [recording rules ](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) and (or) [alerting rules](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) for some metric that we are currently tracking. When the said metrics breaches some threshold or value, Prometheus should fire an alert to Alertmanager who then routes it to the correct receiver. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Prometheus connects to Alertmanager
- [ ] Prometheus sends alerts to Alertmanager
- [ ] Alertmanager integrated with SendGrid
- [ ] Alert emails are received from Alertmanager/SendGrid
- [ ] Documentation updated indicating Alertmanager integration
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add or create Prometheus rules for a chosen metric or metrics alerting
- [x] Add Alertmanager to compose file 
- [x] [Configure](https://prometheus.io/docs/alerting/latest/configuration/#email_config) Alertmanager with Sendgrid
- [x] Generate a test to fire the chosen alert(s)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

N/A

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Alertmanager Docs](https://prometheus.io/docs/alerting/latest/configuration/)
- [Prometheus Docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by lhuxraft** [comment]
11/13/2024: Will start testing locally this afternoon

**Comment by lhuxraft** [comment]
11/15/2024: Next in queue

**Comment by lhuxraft** [comment]
11/18: Approved, left a comment for @elipe17
