### ISSUE TITLE
Promtail Pipelines

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3243]
**Description:**
Now that we have an MVP of Loki and a logging dashboard in Grafana. We need to enhance the logging dashboard to allow querying based on the log message, log level, etc... We can do this by implementing [Promtail pipelines](https://grafana.com/docs/loki/latest/send-data/promtail/pipelines/) which transform outgoing log messages to include metadata labels, i.e. log message, level, app name, etc... 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Promtail pipeline(s) extract at least log level, message, and what app the log came from
- [ ] Grafana logging dashboard updated to query new metadata generated from Promtail pipeline
- [ ] Deployed PLG updated with new config and dashboard
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement Promtail pipeline(s) to extract appropriate metadata
- [ ] Add new query variables to Logging dashboard
- [ ] Ensure new changes (if necessary) are applied to deployed configs/apps as well
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by lhuxraft** [comment]
11/13/2024: Still working, no updates

**Comment by lhuxraft** [comment]
11/15: Issues with Docker yesterday (now fixed), added tags but are not holding (pairing w/ Eric)

**Comment by lhuxraft** [comment]
11/18: Unblocked, need about one more day to work on

**Comment by lhuxraft** [comment]
11/19: Eric and Mo resolved networking issues, @lhuxraft to confirm with Mo progress on the ticket

**Comment by lhuxraft** [comment]
11/20: Almost finished, planning to wrap up today

**Comment by lhuxraft** [comment]
11/25: Raft reviews have been received, changes to be incorporated when Mo is back

**Comment by lhuxraft** [comment]
12/9: Will move to Raft review after doing some additional testing
