### ISSUE TITLE
[DESIGN] As regional staff, I want to be able to see the status of my STTs submissions and view their error reports.

### ISSUE THREAD

**Issue by klinkoberstar** [raft-tech/TANF-app#3249]
**Description:**

Currently, regional staff often contact central office staff with questions regarding STT data, such as:
- Verifying if STT data has been submitted and received by central office.
- Checking if the data submission was accepted.
- Assisting STTs in troubleshooting and resolving errors and/or passing on questions about error reports from STTs.

Currently regional staff do not have access to TDP which limits their ability to view submission statuses directly. This creates a bottleneck, as they must go through the central office to obtain this information, delaying their work and adding to the data team's workload. 

**Acceptance Criteria:** 
- [x] Regional staff can request access to TDP for their region(s)
- [x] Regional staff can log in and see submission history for all STTs within their region 
- [x] Regional Staff cannot download the data file(s) - Question: Grey out or hide completely?
- [x] Regional staff cannot submit data - Question: Grey out or hide completely?
- [x] Provide release notes for both regional staff and STTs, outlining the impacts 
- [x] Email notifications for approved acf users includes correct information 
- [x] Create dev ticket(s) to implement design
- [x] designs pass a11y tests

**Tasks:**
- [x] System admins should be able to assign regional staff to the appropriate region.
- [x] Ensure regional staff can access error reports without restrictions. 
- [x] On data files page, Update the "Associated State, Tribe, or Territory" filter to show only STTs for the respective region.
- [x] Grey out or hide the “Current Submission” tab for regional staff.
- [x] Under “Submission History,” grey out the “File Name” column to prevent file downloads by regional staff.

**UX/Design Tasks:**
- [x] Review/repurpose previous Figma designs 
- [x] Internal UX 
- [x] PM Review edits as needed
- [x] Receive Feedback from OFA for review
- [x] Draft release notes
- [x] Present and receive feedback from dev for review
- [x] Receive approval from OFA/QASP review
- [x] Create Dev tickets
- [ ] Receive approval of release notes

Email specific: 

- [x] Review and repurpose previous email template to address AC
- [x] Content has been written and approved by OFA
- [x] Designs past a11y tests
- [x] Present to Dev for feedback
- [x] Create Dev ticket and have reviews as needed

**Notes**
 The regional staff permissions group exists in TDP but is not configured to accommodate the abovementioned needs:
- Regional staff can request access to TDP but cannot specify the region with which they are associated
- Sys admins have to assign the region in their user profile
- The email notification needs to be reconfigured to notify ACF staff users of their role/assignment in TDP. 
- The regional staff group do not have access to the data files page 

**Supporting Documentation and Deliverables Link(s):**

This feature is a preliminary step toward a comprehensive regional staff interface, as outlined in Epic #1605 . This ticket is intended to be a lighter, more immediate solution that modifies the existing view to improve regional staff’s transparency into TDP and their STTs’ submission status.

- [Figma Designs](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9643-708)
- [Requested Email Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/regional-request-for-access.html)
- [Request Approved Email Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/regional-request-approved.html)
- [Release Notes](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/future-release-notes)

**Open Questions:**
- Can we allow staff to request access for multiple regions? **Yes**
- If we can, can we also add a drop down menu on the data files page for the regional staff user to select the region first, before selecting STTs? (if necessary)
- Are Submission History Reports and Data Submission History Reports two different things? Or are they different lenses for the same data. 
- What are the actions that we'd like Regional Staff to take if any within TDP or should that be bucketed into future work?

**Comment by vlasse86** [comment]
For dev ticket, ensure the following AC is captured: RO OFA staff can see reporting status of grantees in their region (#130)

**Comment by ADPennington** [comment]
@victoriaatraft @reitermb please review and list any outstanding questions before we meet on Friday (11/15). The description here explains why this is a priority. 

Next step: UX to refine and fill-in details to make this an actionable design ticket

cc: @lfrohlich @klinkoberstar @ttran-hub

**Comment by victoriaatraft** [comment]
[Notes to Q&A in Gitbook here](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/data-reporting-research/3249-regional-staff-questions). 

Action items:
- [x] Will add to the next cross prod sync 11/15 to prioritize when this will be worked on.

**Comment by lhuxraft** [comment]
11/25: Internal sync to discuss today, to discuss at UX sync tomorrow

**Comment by victoriaatraft** [comment]
Link to the [working Figma is here](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9643-708)

**Comment by lhuxraft** [comment]
12/2: Miles / Victoria syncing on progress, preparing to review w/ stakeholders during UX sync on Friday. Miles working on email templates

**Comment by lhuxraft** [comment]
12/4: Adjusting, preparing for presenting on Friday

**Comment by victoriaatraft** [comment]
@ADPennington  @klinkoberstar @lfrohlich 

[Figma Designs for #3249](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9643-708)
Moving this to QASP and on the agenda to receive feedback on TDP UX Sync tomorrow. Wanted to get this here in case you needed to time review and process. There are open comments in the Figma as well please feel free to tag us or reply here if/when comments have been made. Thank you :) 

cc @reitermb @lhuxraft

**Comment by ADPennington** [comment]
> @ADPennington @klinkoberstar @lfrohlich
> 
> [Figma Designs for #3249](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=9643-708) Moving this to QASP and on the agenda to receive feedback on TDP UX Sync tomorrow. Wanted to get this here in case you needed to time review and process. There are open comments in the Figma as well please feel free to tag us or reply here if/when comments have been made. Thank you :)
> 
> cc @reitermb @lhuxraft

i've reviewed and will be ready for discussion. thank you!

**Comment by reitermb** [comment]
As mentioned at the tail end of UX sync I've also spun up the email templates associated with this ticket which respectively confirm access requests from Regional Staff and approved requests. These adhere fairly closely to the counterpart notifications for STTs, substituting Regional Staff for Data Analyst and Region #(s) in place of STT. The approved request email also includes direct links to knowledge center pages for accessing submission history and interpreting error reports (I could imagine future revisions linking directly to Regional Staff specific support content further down the road when we have dedicated UI for them). 

[Requested Email Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/regional-request-for-access.html)
[Request Approved Email Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/regional-request-approved.html)

One question I wanted to send into review here is whether the TANF data email is still the correct place to direct them to for support/questions or whether that should be swapped out for Alex/Thomas' emails?

cc @ADPennington @lfrohlich @klinkoberstar

**Comment by ADPennington** [comment]
> One question I wanted to send into review here is whether the TANF data email is still the correct place to direct them to for support/questions or whether that should be swapped out for Alex/Thomas' emails?

tanf data resource mailbox will work just fine. they currently use it to interact with us

**Comment by lhuxraft** [comment]
12/9: Reviewed with QASP on Friday, to discuss on Leads sync. Discuss how to scope Django admin screens

**Comment by lhuxraft** [comment]
12/11: Wrapping up release notes draft

**Comment by victoriaatraft** [comment]
@lhuxraft Release notes draft has been added to the [gitbook](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/future-release-notes) and also linked in supporting documentation and is ready for edits/feedback

cc @ADPennington @lfrohlich @klinkoberstar @reitermb @lhuxraft

**Comment by lhuxraft** [comment]
> @lhuxraft Release notes draft has been added to the [gitbook](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/future-release-notes) and also linked in supporting documentation and is ready for edits/feedback
> 
> cc @ADPennington @lfrohlich @klinkoberstar @reitermb @lhuxraft

LGTM!

**Comment by victoriaatraft** [comment]
Dev tickets
#3384 
#3385

**Comment by victoriaatraft** [comment]
Last quick edit on the 3249 mockups following our convo from dev office hours and quick sync with @andrew-jameson @lhuxraft.
We added in a section for users to identify if they belong to the Regional Staff or Central Office and if they select Regional staff they are shown the drop down list of regions. BUT we did not cover the label of that selection field. I temporarily put it was "Permission Request" but pending a better verbiage suggestion from @ADPennington @klinkoberstar  I'll make the change in Figma and we can close the design ticket out and dev can pickup implementation in the new year.


Update: Sufficient to just ask "Do you work for an OFA Regional Office?" Y/N - then show the regions if they answer yes. Just need to make sure a11y stuff is covered.
