### ISSUE TITLE
Update email templates for STT data submissions re: status and error guidance

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3251]
**Description:**

Yun has observed that STTs are submitting data with errors and failing to correct them. The OFA team believes this issue may stem from the current Submission email, which does not effectively highlight the error report or direct STTs to correct the errors. To address this, we propose updating the Submission email to:

- include file status
- Highlight errors earlier in the email.
- Include a clear call to action in the header and/or first line.
- Introduce a third submission email template specific to STTs whose files were Partially Accepted with Errors or Rejected, which indicates that they _must_ take action and resubmit.
- include reference links to error guidance when errors detected during processing
- consider removing "successful" language in file submission when there are errors

**Acceptance Criteria:** 
- [x] Mock up of 3 Submission Status Email Templates based on file submission status:
  - [x] Accepted with No Errors: No call to action; this email serves as an informational confirmation that the file was submitted.
  - [x] Accepted with Errors: Call to Action: "Warning, your data was accepted, but errors were detected in your file submission."
  - [x] Partially Accepted with Errors/Rejection: Call to Action: "Immediate action required. Some of your data was not accepted by TDP due to errors in the submission. Please review, update your file, and resubmit ASAP."
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Create mockups for the three email templates.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- current [language](https://tdp-project-updates.app.cloud.gov/knowledge-center/uploading-data.html#:~:text=for%20all%20families.-,Submit%20your%20files,-After%20uploading%20the) re: "successful submitted" may be confusing, especially when errors were detected in the file during processing. 
- You may want to explore adding record numbers to email templates per #5143

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by klinkoberstar** [comment]
Based on a conversation @ADPennington and I had on 11/22, we may want to use the "critical error" flag created as part of #3234 to inform the content of these emails. Specifically, we are thinking the content of the email should be determined by both:

1. The file status (was the file accepted by the system, partially accepted or rejected) AND
2. The type of errors (were the errors deemed critical)

This was an informed by a discussion that surfaced a **fundamental challenge with using file status as a proxy for data quality** Partially accepted with errors is used as a proxy to communicate that the file has more severe issues than a file that was accepted with errors. From a data quality perspective this is not necessarily true. Long term, we want to disentangle the file status (Accepted, Partially Accepted, Rejected) from data quality (critical errors). 

Making any changes to the file stats framework will require user research to better understand how users interpret it now, and what would be the best way to convey this information. We don't want to make any major changes to the Submission History page without exploring this further. We do not want to change the file status yet because we want to prevent confusion. We believe that these emails can be a tool to flag critical errors as a lower lift solution.

cc: @victoriaatraft and @reitermb for visibility

**Comment by lhuxraft** [comment]
Revisit after QASP Review on 3155

**Comment by lhuxraft** [comment]
Look at the error report in different scenarios to determine call to action, align more with critical vs. non-critical? Revisit after January webinar

**Comment by lhuxraft** [comment]
Revisit in next sprint

**Comment by ADPennington** [comment]
still reviewing this. will have feedback for 6/24 backlog

**Comment by ADPennington** [comment]
- need an FRA email template
- team is in agreement that for TANF/SSP/tribal, we need an email template that satisfies the following ACs:
  - include file status
  - removing "successful" language in file submission + Highlight the impact of errors in the email. (e.g. what does it mean for a file to be reject, partially accepted, etc)
- Include a clear call to action in the header and/or first line.
- include reference links to error guidance instead of submission history


@lhuxraft

**Comment by lhuxraft** [comment]
@lhuxraft to update to include exploration of record numbers (#5143 reference)

**Comment by ADPennington** [comment]
@lhuxraft is there a document to review here?

**Comment by lhuxraft** [comment]
> [@lhuxraft](https://github.com/lhuxraft) is there a document to review here?

Oops! Here is the link: https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/emails/email-data-submission

**Comment by ADPennington** [comment]
@lhuxraft i left comments in the gitbook. 

for the FRA emails, 

- we need to be sure to point to the fra links in the KC. 
-  "Accepted with errors" isnt a possible status with the tanf exiter reports
- "partially accepted with errors" means that at least some of the records were processed. but the file was not fully processed. 
- "cases" are not applicable for tanf exiters

for TANF/SSP emails, same as above re: "partially accepted" status. also, we will need more clarity around record counts if we are including them in the reports. (will these record counts also be included in the fra reports?)

**Comment by kristen-shaw4** [comment]
I made one of the updates and left a comment in the section about Records Contained

@ADPennington

**Comment by ADPennington** [comment]
> I made one of the updates and left a comment in the section about Records Contained
> 
> [@ADPennington](https://github.com/ADPennington)

thanks @kristen-shaw4. FRA emails look good and left one suggestion for tanf/ssp/tribal re: record counts

**Comment by kristen-shaw4** [comment]
Updated the email templates re: cases & records
1. Accepted: https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-submitted-accepted.html
2. Accepted With Errors: https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-submitted-accepted-with-errors.html
3. Partially Accepted With Errors / Rejected: https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/data-submitted-partially-accepted-rejected.html

**Comment by ADPennington** [comment]
This looks good! hope it's helpful to have the same results in email as in SH! Looking forward to receiving feedback on this from STTs 🚀

**Comment by ADPennington** [comment]
can this be closed? @reitermb @kristen-shaw4

**Comment by victoriaatraft** [comment]
Closing per comment above, dev ticket created for implementation #5478
