### ISSUE TITLE
Alertmanger Cloud.gov

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3254]
**Description:**
As a follow on to #3242, Alertmanager (AM) will need to be deployed to the production environment in cloud.gov with the rest of PLG. Pending the merge status of #3046 the implementer may be inclined to silence certain alerts from AM to avoid false positive alerts while all apps in our environment's begin speaking with PLG. The AM UI should also be accessible via the frontend for administrators and developers to monitor/silence/create alerts.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] AM deployed in the production environment
- [ ] AM UI accessible from any environment (dev, staging, and production)
- [ ] AM alerts fire and route correctly from deployed environment
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update `plg/deploy.sh` to deploy AM and handle any network config
- [x] Update `scripts/deploy-frontend.sh` to add network config to proxy AM in prod from all environments.
- [x] Update nginx conf file to proxy AM in prod
- [x] Add/update a manifest for AM, be sure to use the binary buildpack and deploy AM as a standalone binary for consistency and templating capabilities.
- [x] Upload the newest `Logs` dashboard to Grafana
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by lhuxraft** [comment]
11/15: Ready to test in Cloud.gov, dependent on PLG deployment

**Comment by lhuxraft** [comment]
11/18: Moved to Raft review, working as expected. Needs two reviews

**Comment by lhuxraft** [comment]
11/20: Need one more review
