### ISSUE TITLE
Integrate ElasticSearch exporter for Prometheus monitoring and alerting

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3259]
### Background ###
Once the MVP for monitoring and alerting has been implemented, the next step is to extend our observability to include all services, particularly ElasticSearch. The Prometheus community provides an ElasticSearch exporter that can expose key metrics from ElasticSearch to Prometheus, which is crucial since ElasticSearch is heavily integrated into TDP's parsing engine. By integrating the ElasticSearch exporter with Prometheus, we can monitor the health and performance of ElasticSearch and set up alerts, further enhancing the reliability and observability of the TDP ecosystem.

### Acceptance Criteria ###
- [ ] Elastic Search metrics are exposed to Prometheus
- [ ] Alertmanager has MVP alerts configured for Elastic metrics
- [ ] Elastic exporter is deployed to each environment
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Setup and test the Elastic exporter locally
- [ ] Configure MVP Alertmanager alerts based on exported metrics
- [ ] Add manifest for Elastic exporter
- [ ] Update `plg/deploy.sh` to automate deployment/networking of Elastic exporter
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by lhuxraft** [comment]
Close or rewrite?

**Comment by elipe17** [comment]
> Close or rewrite?

If we have officially decided to deprecate Elastic then we can close this. If we do close it, we should link to the ticket indicating it's deprecation/removal first.

**Comment by lhuxraft** [comment]
Closing due to #3363
