### ISSUE TITLE
[Research Facilitation Prep] Finalize Prototypes for FRA research sessions

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3265]
**Description:**

Delivers prototypes for FRA research sessions (mainly closes the gap between existing mockups and organized clickable versions that better simulate TDP). 

**AC:**

- [x] Prototype includes:
   - [x] Submission workflow 
   - [x] A/B testable error report variants (w/ swappable order) 

**Tasks:**

- [x] Insert designs into clickable prototype
- [x] Insert error report variants into excel files
- [x] Make downloads work
- [x] Sort out logic to be able to alternate A/B B/A order between sessions

**Supporting Documentation:**
Version A Start: https://reitermb.github.io/TDPrototype/knowledge-center/index.html
Version B Start: https://reitermb.github.io/TDPrototype/knowledge-center/index2.html

Version A Errors: https://reitermb.github.io/TDPrototype/knowledge-center/complete.html#complete
Version B Errors: https://reitermb.github.io/TDPrototype/knowledge-center/complete2.html#complete

- [Building off of this past prototype ](https://reitermb.github.io/HTML-Table-example/csv-research.html)
- [TAB B - 1A. Instructions - Work Outcomes of TANF Exiters Report2.docx](https://github.com/user-attachments/files/17720342/TAB.B.-.1A.Instructions.-.Work.Outcomes.of.TANF.Exiters.Report2.docx)

**Comment by victoriaatraft** [comment]
@reitermb Sent via email sent earlier today from @lfrohlich pasting here to track to be updated with prototypes, doc also in the details.
<img width="880" alt="Screenshot 2024-11-12 at 9 10 41 AM" src="https://github.com/user-attachments/assets/055bf249-6c4a-4c4b-b5cb-a5325b00afe2">

**Comment by lhuxraft** [comment]
11/13/2024: Almost wrapped up, putting finishing touches

**Comment by reitermb** [comment]
I'm not sure that this needs extensive QASP attention given that it's just stringing up the concepts we aligned on in research planning but wanted to note that I've updated the description with the A/B version links and both have the requested due date lookup table. 

Ran great in our first session today!

cc @ADPennington @lfrohlich

**Comment by lhuxraft** [comment]
11/18: Pinging Lauren, taking a look. Work continues this week on research, may spin up initial steps towards synthesis.

**Comment by ADPennington** [comment]
@reitermb @victoriaatraft @lhuxraft this can be closed. thank you tracking our feedback on these prototypes in the UX sync notes. Do we have a dedicated place to revisit this feedback? Want be sure we're tracking this as part of the effort to inform final FRA-related designs. cc: @lfrohlich @klinkoberstar
