### ISSUE TITLE
Revise Validation Logic for SSP Active Case Item 32D (Receives Disability Benefit: AABD)

### ISSUE THREAD

**Issue by klinkoberstar** [raft-tech/TANF-app#3266]
**Description:**
Validation on Item 32D (Receives Disability Benefit: AABD) for SSP Active Cases (M2) needs to be updated to accept a value of 0. Current validation requires Item 32D be greater than 0. However, Item 32D is no longer in use and STTs have been instructed to enter a value of 0.  STTs are currently receiving error messages for this question that they should not receive.

**Acceptance Criteria:** 
- [ ] Validator for Item 32D revised to allow 0 as an acceptable value.
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
- [ ] Update validation logic for Item 32D to accept a value of 0.
- [ ] Run Testing Checklist and confirm all tests pass.
- [ ] README is updated, if necessary

**Supporting Documentation:**

- Coding Instructions: [ACF-199 TANF and ACF-209 SSP-MOE Data Reporting Instructions](https://www.acf.hhs.gov/sites/default/files/documents/ofa/ACF199_209%20TANF_SSP%20data%20report%20instructions%20-%20valid%20thru%202026-10_compliant_FINAL.pdf) (Page 59)
![Screenshot 2024-11-05 083725](https://github.com/user-attachments/assets/48e09438-16c7-43ee-b633-4e7f00cb259e)

**Comment by lhuxraft** [comment]
Closing as tickets were consolidated
