### ISSUE TITLE
Reprocessed on enhancement (3014 follow-on)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#3271]
**Description:**
Adds improvement to Submitted On column of submission history replacing current most recent reprocessed date with a clickable trigger that opens a dialog containing a full list of reprocessing event timestamps. 

**Acceptance Criteria:** 

 
- [x] Submitted on/by columns are combined
- [ ] Dialog has a close button
- [ ] Dialog contains paragraph explainer on reprocessing
- [ ] Dialog contains date time stamp for last reprocessing event
- [ ] Dialog opens when trigger in Submitted on column is clicked
- [ ] UX has been pinged to ticket knowledge center revisions to capture these changes
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Add dialog
- [x] Add dialog trigger
- [x] Add explainer text
- [x] Add timestamp
- [x] Combine Submitted On/By columns
- [ ] A11y test in raft review
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Reprocessed on trigger example pending mockups:

[Reprocessed ⓘ]()

Dialog contents:

---
We've reprocessed your files with updated validation criteria, based on system improvements, to improve accuracy of error reports. No changes have been made to your original data submission. 

Data was reprocessed on: [Datetime]

[Close]()

---

**Supporting Documentation:**

<img width="1227" alt="image" src="https://github.com/user-attachments/assets/379c0d59-340a-4db3-b609-980023beb319">

**Comment by ADPennington** [comment]
@reitermb whenever you have time, could you update the description of this ticket to align with Friday's conversation?

**Comment by lhuxraft** [comment]
Miles to further refine, add to the following sprint's backlog

**Comment by lhuxraft** [comment]
Miles to crop out the error report column
