### ISSUE TITLE
Revise Validation Logic for TANF Active Case Item 26AIII (Family Sanction Status)

### ISSUE THREAD

**Issue by klinkoberstar** [raft-tech/TANF-app#3277]
Validation on Item 26AIII (Family Sanction) for TANF Active Cases (T1) needs to be updated to accept a value of 0. Current validation requires Item 26AIII to be one of (1, 2) if Item 26AI (Total Dollar Amount of Reductions Due to Sanctions) is greater than 0. However, Item 26AIII is no longer in use and STTs have been instructed to enter a value of 0.  STTs are currently receiving error messages for this question that they should not receive.

**Acceptance Criteria:**
- [ ] Validator for Item 26AIII should be revised to pass validation when Item 26AI is greater than 0, but Item 26AIII is set to 0.
- [ ] Error message related to Item 26AIII should be updated to reflect correct expected options (0, 1, 2). 

**Tasks:**
- [ ] Update validation logic for Item 26AIII to accept a value of 0.
- [ ] Run Testing Checklist and confirm all tests pass.
 
**Supporting Documentation**
- Conditional Logic to be Updated: https://github.com/raft-tech/TANF-app/blob/cb51a68f5751c259b306feb87a999a9f5423a986/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py#L69
- Coding Instructions: 
![Screenshot 2024-11-13 161444](https://github.com/user-attachments/assets/5f9ae8dc-8a96-4163-ad5a-97fa966becb6)

**Comment by lhuxraft** [comment]
Closing as tickets were consolidated
