### ISSUE TITLE
Revise Validation Logic for TANF Active Case Item 29 (TANF Family a New Child-Only Family)

### ISSUE THREAD

**Issue by klinkoberstar** [raft-tech/TANF-app#3279]
**Description:**
Validation on Item 29 (TANF Family a New Child-Only Family) for TANF Active Cases (T1) needs to be updated to accept a value of 0. Current validation requires Item 29 to be within [1, 2]. However, Item 29 is no longer in use and STTs have been instructed to enter a value of 0.  STTs are currently receiving error messages for this question that they should not receive.

**Acceptance Criteria:**
- [ ] Validator for Item 29 revised to allow 0 as an acceptable value.
- [ ] Error message related to Item 29 should be updated to reflect correct expected options [0, 1, 2] 
	
**Tasks:**
- [ ] Update validation logic for Item 29 to accept a value of 0.
- [ ] Run Testing Checklist and confirm all tests pass.
 
**Supporting Documentation**
- Conditional Logic to be Updated: https://github.com/raft-tech/TANF-app/blob/cb51a68f5751c259b306feb87a999a9f5423a986/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t1.py#L652
- Coding Instructions: 
![Screenshot 2024-11-13 162404](https://github.com/user-attachments/assets/1cab8df4-d25e-439e-9491-946fd145b3b3)

**Comment by lhuxraft** [comment]
Closing as tickets were consolidated
