### ISSUE TITLE
Copy of As tech lead, I want to load test our application

### ISSUE THREAD

**Issue by lhuxraft** [raft-tech/TANF-app#3289]
**Description:**
Currently, the production backend runs in 512MB. There is some uncertainty that this might be insufficient for 100+ concurrent users submitting large files. 

**Acceptance Criteria:** 

- [ ] List of recommended "virtual hardware" specifications
- [ ] Potentially come up with a (third-party) test toolset
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Investigate auto-scaling and [multi-instance apps](https://cloud.gov/docs/management/multiple-instances/)
- [ ] Stress test front/backend applications under 100+ concurrent user requests
- [ ] Stress test PG/ES for expected maximum load
- [ ] Stress test anciliary services for maximum load (such as ClamAV, S3, etc.)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Do *NOT* use Parasoft

**Supporting Documentation:**

- [File size ranges](https://github.com/raft-tech/TANF-app/blob/develop/docs/Background/Current-TDRS.md#data-transmission)
- [Django Optimization](https://docs.djangoproject.com/en/4.1/topics/performance/)
- [Celery Optimization](https://docs.celeryq.dev/en/stable/userguide/optimizing.html)
- [Random stackoverflow metrics](https://stackoverflow.com/questions/28205282/typical-memory-usage-for-django-applications)
- [k6 testing tool](https://k6.io/) recommended by @jtimpe 
- [SF for tools](https://stackoverflow.com/questions/46893226/performance-load-and-stress-testing-in-django)
- [12 tool recommendations](https://www.techrepublic.com/article/load-testing-tools/)

**Open Questions:**
