### ISSUE TITLE
(Internal) Retro 10/15 Commitments

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#329]
**Description:**
Document Retro action items/commitments from [10/13 Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1602610564913/1862c4424ae2114494f2f0eb007108f18e6af7e2) and create issues to address feedback.

**AC:**
- [x] retro items action items have been documented and tasks have been completed

**Tasks for Sprint 6**
- [x] Discussion on frontend and backend issues and whether it makes sense to break them. Backend is ahead of frontend. [In discussion, consider focussing on an epic - upload] (Prioritized and committed) 
   - [x] Discussion on how we manage umbrella issues (for dev and design) (see if this needed after discussion on frontend and backend issues)
- [x] Working session to discuss what we need to deliver for OFA MVP and get on the same page with KPIs (Prioritized and committed) 
- [x] Experiment with 'Shift left' for our dev review. Revisit to see if we need to update this.
- [x] Add sprint summary in the markdown code doc<> on the Day 10. For any additions to the sprint summary or new items 
are submitted on Day 13. Update the sprint summary doc with a PR with comments on the change being made. 
- [x] Revisit next retro whether we have a clear definition on a11y checks to meet QASP 
- [x] Revisit next retro whether frontend architecture uncertainty has been resolved and the path forward is working.

**Supporting Documentation:**

(please include any relevant log snippets/ files/ screen shots here.)

**Open Questions:**

(any clarifying questions in support of the issue)

**Deliverables:**
- (Internal) Determine where to post research artifacts and deliverables : #270
-  Discussion on frontend and backend issues and whether it makes sense to break them: #336
   - Trying to use thin slices of epics that contain backend and frontend issues #9
- Sprint summary is [here](https://github.com/HHS/TANF-app/tree/main/docs/Sprint%20Review)

**Comment by lfrohlich** [comment]
this was completed in Sprint 6
