### ISSUE TITLE
[DRAFT] Update KC re: error report (related to 3155)

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3290]
**Description:**

- [gitbook draft content](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/dec-05-ish)
- release note
  - new error report
  - are only 500 critical errors in report?

- KC guidance
  -  Overview of the Error Report needs to be updated
     - new photo of the error report (Summary and critical tabs)

**Related User Stories:**

—As a [user type] I want the page to exist so that I can see it.—

**Recommended pa11y actions:**

—‘click element #error-report’,—

**AC:**

- [ ] Documentation work for the following has occurred:
   - [ ] Relevant User stories.
   - [ ] Recommended pa11y checks.
   - [ ] Updating living UX documents, e.g. User Flows or Personas(if relevant).
- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] Dev/Design sync has occurred; resulting tickets created
- [ ] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**

- [ ] —Draft design in Figma—

**Supporting Documentation:**

—Link to Figma and Dev-Ready Design folder PDF—

**Comment by ADPennington** [comment]
@klinkoberstar and I to discuss scope for this ticket on 11/22

**Comment by lhuxraft** [comment]
Captured separately in #3316
