### ISSUE TITLE
Implement log file generation and S3 upload for parser runs

### ISSUE THREAD

**Issue by jtimpe** [raft-tech/TANF-app#3294]
### Background ###
Currently, TDP uses Python's logging utility to capture debug messages generated by the application and sent to the terminal. These logs are captured by Cloud.gov, Prometheus, and Sentry. However, there are several key challenges with the existing logging system:

- Sensitive Data Leakage: Logs may potentially expose sensitive information.
- Difficult to Trace Errors: It's challenging to identify errors associated with specific file uploads when reviewing historical logs.
- Lack of Visibility: There is no clear way to compare log differences between parser runs for the same file.

Issue #2562 explored and proposed a solution to save all log output to a file, allowing end-users to access logs for past parser runs tied to a specific datafile submission. Following the design and approach outlined in #2562, this issue focuses on implementing a logging system that includes the creation of a log file for each datafile submission and uploading that log file to S3.

### Acceptance Criteria ###
- [ ] For every datafile submitted, a log file is created and stored in the same s3 directory
- [ ] The log file contains all backend app logs generated from the `parser_task` (and all subroutines)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Create and implement the singleton `ParseLogContextManager` class (Method/Design steps 1-4 from the tech memo)
- [ ] Upload the resulting log file to s3, using the same directory as the uploaded datafile (Method/Design step 5 from the tech memo)
- [ ] Run Testing Checklist and confirm all tests pass

### Prioritization ###
- Reach: 6 (dev team + Alex/Thomas)
- Impact: 0.5
- Confidence: 75%
- Effort: 3 weeks

**Comment by lhuxraft** [comment]
Evaluate in the following sprint's backlog

**Comment by lhuxraft** [comment]
PLG conversation should inform confidence estimate
