### ISSUE TITLE
[Research Synthesis] FRA Research

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3297]
**Description:**
Follow on to #3267 

**AC:**
- [x] Complete user research sessions with STTs 
- [x] Affinity Mapping of research sessions have been completed to guide synthesis findings
- [x] A GitBook with the drafted synthesis has been reviewed by OFA/PM/Dev
- [x] Develop PPT slide for January webinar (to be sent to OFA for review by Dec 31)
- [x] Present preliminary themes to OFA/Dev/PM, evaluating for feedback and discussing impact on outcomes for the FRA MVP. 
- [ ] Opened PR containing the final draft of the synthesis.
- [x] Define follow on development tickets
- [ ] Internal Raft Review has occurred to ensure DoD standards and QA
- [ ] The content is usable and accessible, meaning it adheres to definition of done standards for design work.
> <details>
>      <summary>Expand Definition of Done Standards</summary>
> 
> - It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented
> 
> - Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented
> - It follows [accessibility guidelines](https://accessibility.digital.gov/) and accessibility implementation notes are documented (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.)
> - If feedback identifies bigger questions or unknowns, create additional issues to investigate
> </details>

**Tasks:**
- [x] Aggregate notes from research sessions
- [x] Document synthesis - Scope (research goal(s)), High-level findings, Actionable learnings, Issues that have to be added to Zenhub, Takeways for future research
- [ ] Generate slide for OFA. deck (see dec 6 ux sync notes)
- [ ] Delete video recording(s) once notes are compiled

**Supporting Documentation:**
- [Link to working PPT slides for OFA deck](https://gorafttech-my.sharepoint.com/:p:/g/personal/vamoroso_teamraft_com/EdhirFyOAVJBgR4H4n5n1fgBtkBuIOG6Dr0KSU1ugtXPHQ?e=5kbe4O)
- [Link to synthesis draft on Gitbook ](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/winter-2024-evaluating-fra-submission-and-error-reporting)
- [FRA MVP Research Planning](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/yfhDBBVu7eJEUBHaCqzz/fra-research/fra-mvp-research-plan) which includes planning, protocol and interview transcripts from participants
- [Link to Mural Affinity Mapping](https://app.mural.co/t/raft2792/m/raft2792/1732564281598/dcead26cbc0379f5f51aba1b56ca4656d64b9ef5) which includes a thematic analysis derived from the user research sessions via recordings and transcripts

**Comment by lhuxraft** [comment]
FYI: Added additional AC around creating PPT slide for January webinar. Also updated third AC to capture discussed changes with UX and OFA

**Comment by victoriaatraft** [comment]
Description updated with Draft of synthesis. Will put together rough slides for the webinar next week 😊 cc @lhuxraft @reitermb

**Comment by victoriaatraft** [comment]
@klinkoberstar @ADPennington @lfrohlich 
On the Dec 30 TDP UX agenda to review FRA research synthesis and follow up with Q/A, gitbook comments, etc. as well as the working PPT slides for the webinar deck. The link to the that is above in the supporting documents and will also keep in mind edits pending feedback during our UX sync. 

cc: @reitermb @lhuxraft
