### ISSUE TITLE
As a user, I want to be given at least 20 seconds to easily request more time when completing the new user profile  form

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#331]
**Description:**
Per [18F accessibility timeout guidelines](https://accessibility.18f.gov/timeouts/), once system timeouts is implemented, a user must be given at least 20 seconds to easily request more time when completing a form. This issue will deliver timeouts for first and last name fields when a new user creates a profile.

**Acceptance Criteria:** 
- [ ] Timeout occurs for first and last name fields when a new user creates a profile.
- [ ] User is given at least 20 seconds to request more time.
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
- 18F's Accessibility Guide for [Timeouts](https://accessibility.18f.gov/timeouts/)
- New user profile form:
<img width="708" alt="Screen Shot 2020-10-14 at 2 06 23 PM" src="https://user-images.githubusercontent.com/22622384/96027867-894cf400-0e26-11eb-8e08-9f1465516c82.png">

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by shubhi-raft** [comment]
This is super seeded by session timeout #197. ready to be closed.
