### ISSUE TITLE
Monitor Nexus server and set up alerts for downtime detection

### ISSUE THREAD

**Issue by elipe17** [raft-tech/TANF-app#3313]
### Background ###
Recently, our Nexus server experienced downtime, and we had no way of detecting the issue until pipeline failures occurred. To prevent this from happening again, we want to start monitoring Nexus with PLG and set up Nexus-specific alerts. Nexus exports Prometheus metrics, which makes monitoring straightforward. A Nexus user account for Prometheus already exists, and its credentials can be accessed via a CF service key in the production space under the `tanf-keys` service.

### Acceptance Criteria ###
- [ ] Nexus is monitored by PLG
- [ ] Alert rules created for Nexus
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Update the prometheus.yml and prometheus.local.yml based off of the link above
- [ ] Add new rules to alerts.yml to monitor Nexus based on it's exported metrics
- [ ] Redeploy/re-configure the deployed prometheus and alertmanager to use the configs you updated
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by lhuxraft** [comment]
Closing, Nexus will need to be deprecated
