### ISSUE TITLE
v 3.7.5 Release Notes and Knowledge Center Updates

### ISSUE THREAD

**Issue by victoriaatraft** [raft-tech/TANF-app#3316]
**Description:**
This ticket is to track release notes to STTs on the TDP portal, relative Knowledge Center Updates and the release notes Email sent to STTs.

**AC:**
- [x] Content drafted in Gitbook
- [x] Changes staged in Knowledge Center Test environment
- [x] A11y tested

**Tasks:**
- [x] UX Create a Ticket for Release Notes + Email Template 
- [x] UX/OFA Generate Draft in GitBook 
- [x] Receive Content Feedback from PM/Dev/UX/OFA, schedule sync to finalize 
- [x] UX Update release notes section and/or knowledge center for test environment
- [x] UX Update release number on release note provided by dev
- [x] Attach proof of a11y pass. 
- [x] 12/17: Update for additional section
- [x] UX Create a project repo PR and request final-mile approval from OFA. 
- [x] UX Makes final-mile edits to the PR/Test environment as needed until approved.
- [x] UX Create Email and send draft to Alex/Thomas for approval
- [x] UX makes edits to email as applicable, sends final draft
- [x] Dev cuts release
- [x] OFA approves PR
- [x] UX merges PR to Knowledge Center after release is pushed to production.
- [x] OFA sends email release notes to STTs

**Supporting Documentation and Links:**

- [Link to the Draft Content for Release Notes](https://app.gitbook.com/o/Yd4Wv0Fi89kSKpmakWrn/s/uAlDVLhlFIbJw6huUS2x/release-notes-workflow/dec-4-ish-release-notes)
- [Test Environment with Release Notes](https://reitermb.github.io/Test/knowledge-center/index.html)
- [Test Environment KC: Viewing Error Reports](https://reitermb.github.io/Test/knowledge-center/viewing-error-reports.html)
- [Test Environment KC:Submission History](https://reitermb.github.io/Test/knowledge-center/view-submission-history.html)

**Comment by victoriaatraft** [comment]
@ADPennington Release notes draft has been updated to remove the error limit per the comment in #3234 

cc: @reitermb @lhuxraft

**Comment by ADPennington** [comment]
it would be helpful to add the following content somewhere around or in reference to [this part of the KC](https://tdp-project-updates.app.cloud.gov/knowledge-center/viewing-error-reports.html#:~:text=File%20Pre%2DCheck%3A%20Errors%20related%20to%20record%20length%3A):


| Program | Record Type | Min Length | Max Length | Notes |
|---------|-------------|------------|------------|-------|
| TANF    | T1          | 117        | 156        |       |
|         | T2          | 156        | 156        |       |
|         | T3          | 60         | 156        | T3 records with one child must have a record length >= 60. T3 records with two children are must have  101 <= record length <= 156. If any value is in the 2nd child positions (61 to 101), the 2nd child record will be processed, unless it is completely zero-filled or space-filled. |
|         | T4          | 36         | 71         |       |
|         | T5          | 71         | 71         |       |
|         | T6          | 379        | 379        |       |
|         | T7          | 247        | 247        | Please space-fill to max length after last stratum reported. |
| Tribal  | T1          | 117        | 122        |       |
|         | T2          | 122        | 122        |       |
|         | T3          | 60         | 122        | T3 records with one child must have a record length >= 60. T3 records with two children are must have  101 <= record length <= 122 If any value is in the 2nd child positions (61 to 101), the 2nd child record will be processed, unless it is completely zero-filled or space-filled.|
|         | T4          | 36         | 71         |       |
|         | T5          | 71         | 71         |       |
|         | T6          | 379        | 379        |       |
| SSP     | M1          | 113        | 150        |       |
|         | M2          | 150        | 150        |       |
|         | M3          | 60         | 150        | M3 records with one child must have a record length >= 60. M3 records with two children are must have  101 <= record length <= 150. If any value is in the 2nd child positions (61 to 101), the 2nd child record will be processed, unless it is completely zero-filled or space-filled. |
|         | M4          | 36         | 66         |       |
|         | M5          | 66         | 66         |       |
|         | M6          | 259        | 259        |       |
|         | M7          | 247        | 247        | Please space-fill to max length after last stratum reported. |

**Comment by ADPennington** [comment]
@victoriaatraft  @reitermb @lhuxraft -- i updated the release note related to #3234. please review. i also recommend proceeding with the KC updates on the error report page based on @klinkoberstar's draft and the latest version of the error reports which are available in the qasp environment. also attached one here for reference. 
[2023-Q1-Active Case Data (42).xlsx](https://github.com/user-attachments/files/18029732/2023-Q1-Active.Case.Data.42.xlsx)

**Comment by lhuxraft** [comment]
12/6: Addressing comments from PRs, getting updates in test environment

**Comment by lhuxraft** [comment]
12/9: No longer a priority to send out this week, continuing to work on updates

**Comment by victoriaatraft** [comment]
Current content from Gitbook is now in test for Release Notes specifically, pending version number for next week: https://reitermb.github.io/Test/knowledge-center/index.html

cc @reitermb @ADPennington @klinkoberstar @lhuxraft @andrew-jameson

**Comment by klinkoberstar** [comment]
> Current content from Gitbook is now in test for Release Notes specifically, pending version number for next week: https://reitermb.github.io/Test/knowledge-center/index.html
> 
> cc @reitermb @ADPennington @klinkoberstar @lhuxraft @andrew-jameson

One small comment on wording! Otherwise, looks good to me.

**Comment by victoriaatraft** [comment]
Comment above addressed for the release notes. 
Knowledge Center updates have also been made in test as well

https://reitermb.github.io/Test/knowledge-center/viewing-error-reports.html
https://reitermb.github.io/Test/knowledge-center/view-submission-history.html

cc @reitermb @ADPennington @klinkoberstar @lhuxraft

**Comment by lhuxraft** [comment]
12/11: Lauren/Miles to review, then move over to QASP

**Comment by ADPennington** [comment]
@victoriaatraft @reitermb @klinkoberstar 

- made some changes in gitbook to release notes. see what you think. tried to consolidate validation fixes
- i wasnt sure what changed on the submission history page. anything? 
- error report page LGTM

**Comment by victoriaatraft** [comment]
> * made some changes in gitbook to release notes. see what you think. tried to consolidate validation fixes
> * i wasnt sure what changed on the submission history page. anything?
> * error report page LGTM

@ADPennington @reitermb @klinkoberstar
Suggested changes have been updated to the [release notes test page](https://reitermb.github.io/Test/knowledge-center/index.html). I made minor visual edits (removed period at the end of each bullet and removed the bullets from each error message) and for the [Viewing Submission History Page](https://reitermb.github.io/Test/knowledge-center/view-submission-history.html), an additional paragraph has been added, screenshot below 😊
<img width="766" alt="Screenshot 2024-12-17 at 8 00 17 AM" src="https://github.com/user-attachments/assets/dfca69dc-976d-4ea6-bdb8-7776d530e2b7" />

**Comment by victoriaatraft** [comment]
✅ a11y tests passed
![Screenshot 2024-12-17 at 9 26 14 AM](https://github.com/user-attachments/assets/39611cb0-2635-49a4-88c6-0fd76e5c2025)
![Screenshot 2024-12-17 at 9 25 52 AM](https://github.com/user-attachments/assets/f7d70b0f-c875-4d5b-bdfb-2bb6045b56f8)
![Screenshot 2024-12-17 at 9 32 50 AM](https://github.com/user-attachments/assets/b613b738-03e5-48a6-b034-b476e13ca2f9)

**Comment by ADPennington** [comment]
@victoriaatraft @klinkoberstar --

- i made some language adjustments to the reprocessing related release note. see what you think. 
- is there a reason the validation snippets in the release notes have some words in bold? if not, is it possible to remove the bold?
- for the submission history language, i suggest dropping the language marked below (i couldnt find this easily in gitbook):

> We occasionally update validation rules to improve error report accuracy. When this happens, we may “reprocess” files ~~, meaning they’re re-evaluated using the latest criteria~~ without changing the original data. The Submission History will display the latest reprocessing date if this occurs.

**Comment by victoriaatraft** [comment]
@klinkoberstar  @ADPennington --

> * i made some language adjustments to the reprocessing related release note. see what you think.

Looks good -- [Updated to test](https://reitermb.github.io/Test/knowledge-center/index.html)

> * is there a reason the validation snippets in the release notes have some words in bold? if not, is it possible to remove the bold?

It was just easier to read what's different since the lines were similar. Bold has been removed.

> * for the submission history language, i suggest dropping the language marked below (i couldnt find this easily in gitbook):
> 
> We occasionally update validation rules to improve error report accuracy. When this happens, we may “reprocess” files ~, meaning they’re re-evaluated using the latest criteria~ without changing the original data. The Submission History will display the latest reprocessing date if this occurs.

Content updated to the [history page](https://reitermb.github.io/Test/knowledge-center/view-submission-history.html)

😊

pending new screenshots

**Comment by klinkoberstar** [comment]
> @klinkoberstar @ADPennington --
> 
> > * i made some language adjustments to the reprocessing related release note. see what you think.
> 
> Looks good -- [Updated to test](https://reitermb.github.io/Test/knowledge-center/index.html)
> 
> > * is there a reason the validation snippets in the release notes have some words in bold? if not, is it possible to remove the bold?
> 
> It was just easier to read what's different since the lines were similar. Bold has been removed.
> 
> > * for the submission history language, i suggest dropping the language marked below (i couldnt find this easily in gitbook):
> > 
> > We occasionally update validation rules to improve error report accuracy. When this happens, we may “reprocess” files ~, meaning they’re re-evaluated using the latest criteria~ without changing the original data. The Submission History will display the latest reprocessing date if this occurs.
> 
> Content updated to the [history page](https://reitermb.github.io/Test/knowledge-center/view-submission-history.html)
> 
> 😊
> 
> pending new screenshots

thank you both for making this clearer and more concise :) It's looking good to me!
