### ISSUE TITLE
TDP can process "encrypted" files (TANF Section 1)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#332]
### Description: 

"Encryption" is an artifact of STTs using executables like `FTANF.exe` to prepare their data transmissions files. Encryption in this context means that the values in the SSN position of Section 1 (record types `T2` and `T3`)  data files are replaced with other alphanumeric characters. 
    
TDRS has a decryption script that runs on transmitted files if (and only if) the files have an "E" as the [encryption indicator in the header record](https://github.com/raft-tech/TANF-app/blob/develop/docs/User-Experience/Research-Syntheses/2020,%20Fall%20-%20Flatfile%20Metadata%20Guide.md#header-structure). 
    
This decryption ensures that SSNs stored in the database can be used to match to other administrative data sources (e.g. matching to wage records to track employment outcomes for individuals receiving TANF). 

STTs using these executables are tracked [here](https://github.com/raft-tech/TANF-app/tree/develop/tdrs-backend/tdpservice/stts/management/commands/data). These STTs will have an `SSN_Encrypted` value of 1. This may change over time. 

The decryption code is included the [parsing notebooks](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev%2Fdev&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46) :lock:. This code should be applied if and only if special characters are found in the SSN position of the abovementioned relevant record types. 

### ACs: 

- [ ] Section 1 records with "encrypted" SSNs are decrypted
- [ ] Section 1 records with "unecrypted" SSNs are not subject to the decryption script 
- [ ] Section 1 records that do not have SSNs (e.g. T1) are not subject to decryption. 

### Tasks:

- [ ] Implement test for encrypting and decrypting sample text

### Supporting documentation:
 - [parsing notebooks](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev%2Fdev&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46)
 - example of encrypted file
```
HEADER20204A06   TAN1EN
T12020101111111111223003403361110213120000300000000000008730010000000000000000000000000000000000222222000000002229012                                       
T2202010111111111121219740114WTTTTTY@W2221222222221012212110014722011400000000000000000000000000000000000000000000000000000000000000000000000000000000000291
T320201011111111112120190127WTTTT90W022212222204398100000000                                                                                                
T12020101111111111524503401311110233110374300000000000005450320000000000000000000000000000000000222222000000002229021                                       
T2202010111111111152219730113WTTTT@#Z@2221222122211012210110630023080700000000000000000000000000000000000000000000000000000000000000000000000551019700000000
T320201011111111115120160401WTTTT@BTB22212212204398100000000                                                                                                
TRAILER0000006 
```
 - example of unencrypted file
```
HEADER20204A06   TAN1EN
T12020041111111111110833302561120233 10046300000000    0414026      000    000000000000000000000222222    00002229021000000000000000000000000000000000000000
T2202004111111111112219850422900012360222122222221101229911004   208990000000000000000000000000000000000000000000000000000000000000000000000    0783        
T320200411111111111120060627900001906222122122043081        000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
T12020041111111111212333303011120213 10337300000000    0515026      000    000000000000000000129122222    00002229012000000000000000000000000000000000000000
T2202004111111111121219950705900019126222122222222101211211026   101172000000000000000000000000000000000000000000000000000000000000001650000                
T320200411111111112120170401900028456222122122043981        000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
TRAILER0000006
``` 

### Notes:
- decryption logic is slightly different for SSP data. 
- decryption also needs to be applied to section 2 data (for tanf and ssp data).

**Comment by amilash** [comment]
@dk-ui @lfrohlich This has a tag of 'no longer needed'. Did we already do the research here? Why is this no longer needed, and if not, can we close as 'will not do'? 
thanks!

**Comment by lfrohlich** [comment]
I don't know that we've fully decided how the encryption indicator will be handled in the new system. should discuss cc: @ADPennington

**Comment by dk-ui** [comment]
@amilash Yes i think this is better to be discussed as a group. We havent boiled down to how this will be handled yet.

**Comment by ADPennington** [comment]
> I don't know that we've fully decided how the encryption indicator will be handled in the new system. should discuss cc: @ADPennington 

Some notes:
-  this is an artifact of STTs using FTANF/SSPMOE executables to prepare their transmissions files. 
- "encryption" in the context of these executables means that the values in the SSN position are replaced with other alphanumeric characters. 
- this month, I performed an audit of the SSN "decryption" logic previously provided and have an updated, verified version for TDP. 
- Presuming STTs want to continue using these exe's for now, TDP could automatically "decrypt". One benefit of this approach is that it saves the need to ask and potentially confuse users who may interpret "encryption" differently. 
- One question I have is how to apply this decryption such that it doesn't impact files that arent using the exe's. There is a bit of a risk because the decryption logic  involves replacing numeric values with other numeric values. Currently TDRS relies on the header record to know whether or not to apply the decryption logic. 
- important to get right because we use SSN to link to other data sources. 

cc: @lfrohlich @amilash @dk-ui

**Comment by ADPennington** [comment]
@valcollignon this is release 3. context and brainstorming included in above comment. i dont think we need more user research on this, but this ticket will remain in unrefined state until discussion w/ dev on decryption implementation strategy. cc: @lfrohlich

**Comment by valcollignon** [comment]
Removed R&D label as further research is not needed; however, we will need a cross-functional sync on this issue in the future.
CC: @sreedevip @reitermb

**Comment by ADPennington** [comment]
@Smithh-Co @andrew-jameson can you remind us where this ticket is on the roadmap? cc: @lfrohlich

**Comment by Smithh-Co** [comment]
Adding notes post 5.12 syncs:

- Sitting in v3.2 release and 1101 epic, nested into criteria for completion of TANF Section 1 (slated ~ around spr 74/75)
- Alex to migrate .py files into Raft SharePoint and I'll update the ticket resources post
- Encryption is the same for TANF Section 1 and 2
- Encryption is different for SSP Section 1 and 2, F/U ticket to be generated (placeholder in RM currently)

CC: @ADPennington  @lfrohlich @andrew-jameson

**Comment by ADPennington** [comment]
> Adding notes post 5.12 syncs:
> 
> * Sitting in v3.2 release and 1101 epic, nested into criteria for completion of TANF Section 1 (slated ~ around spr 74/75)
> * Alex to migrate .py files into Raft SharePoint and I'll update the ticket resources post
> * Encryption is the same for TANF Section 1 and 2
> * Encryption is different for SSP Section 1 and 2, F/U ticket to be generated (placeholder in RM currently)
> 
> CC: @ADPennington @lfrohlich @andrew-jameson

dev sharepoint files migrated to raft [site](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTDRSResearchDesign%2FShared%20Documents%2FDev&viewid=981949f0%2D98e1%2D4ace%2D8da8%2D436aca592a46)
