### ISSUE TITLE
Revise Cat 3 Validator Logic for SSP Active Case Data

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3320]
**Description:**

Currently errors like the following are appearing in STT's SSP active error reports:
`Since Item 26 (Family Affiliation) is 1, then Item 38 (Citizenship/Immigration Status) 3 must be one of (1, 2)`
`Since Item 60 (Family Affiliation) is 1, then Item 69 (Citizenship/Immigration Status) 3 must be one of (1, 2)`

 but 3 is a valid possible value for citizenship when family affiliation is 1. 

`Dev team`: The logic [here](https://github.com/raft-tech/TANF-app/blob/97bf95ee249f5920c056709fff991362d475c603/tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py#L93L98) and [here](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py#L91L95) needs to be revised to allow 3 as a valid possible value for the Citizenship field.

`UX Team`: the **release notes** associated with this ticket should communicate the following:

#### Fixed:
**Validation logic related SSP family affiliation and citizenship status have been fixed**
TDP was incorrectly generating the following error messages for some SSP Section 1: Active Case files:

`Since Item 26 (Family Affiliation) is 1, then Item 38 (Citizenship/Immigration Status) 3 must be one of (1, 2)`
`Since Item 60 (Family Affiliation) is 1, then Item 69 (Citizenship/Immigration Status) 3 must be one of (1, 2)`

This has been resolved, and no changes to these files are needed. The TDP team will re-process the files at a later date. You may also resubmit any files impacted by this bug to obtain revised TDP-generated feedback reports, but this is not required.

**Acceptance Criteria:** 

- [x] Cat 3 Validator logic for Items 26 and 38  is revised to allow 3  as an acceptable value for citizenship .
- [x] Error message related to Items 26 and 38 should be updated to reflect correct expected options.
- [ ] Cat 3 Validator logic for Items 60 and 69  is revised to allow 3  as an acceptable value for citizenship .
- [ ] Error message related to Items 60 and 69  should be updated to reflect correct expected options.
~~- [ ] references to "alien" in the codebase is changed to "non-citizen" (`on hold`)~~
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x]  Update cat 3 validation logic for Items 26 and 38 [here](https://github.com/raft-tech/TANF-app/blob/97bf95ee249f5920c056709fff991362d475c603/tdrs-backend/tdpservice/parsers/schema_defs/ssp/m2.py#L93L98)
- [ ] Update cat 3 validation logic for Items 60 and 69 [here](https://github.com/raft-tech/TANF-app/blob/develop/tdrs-backend/tdpservice/parsers/schema_defs/ssp/m3.py#L91L95)
~~- [ ] check complexity of changing references to "alien" to "non-citizen"~~
- [x] Run Testing Checklist and confirm all tests pass

**Notes**:

- per @lfrohlich, we also may need to change references to "aliens" to "non-citizens" everywhere in the codebase. Change `On hold` pending OGC input. 

**Supporting Documentation:**
- per OFA TANF policy, SSP recipients can be non-qualified aliens. 
![Screenshot 2024-12-03 092653](https://github.com/user-attachments/assets/fced4c04-51f8-4e33-b2df-1089c5f69e3f)

**Comment by ADPennington** [comment]
@victoriaatraft @reitermb -- please note that this ticket is now in qasp and has release note language referenced in the ticket. Please include this with #3316

**Comment by ADPennington** [comment]
@elipe17 i missed the child-related cat 3 error in this ticket. updated the ticket.
