### ISSUE TITLE
Enhance GitHub Issues with upload and priority management

### ISSUE THREAD

**Issue by andrew-jameson** [raft-tech/TANF-app#3322]
### Background ###
Two scripts have been developed to interact with GitHub issues and manage them in a more user-friendly way. The first script, [gh-issues.bash](https://github.com/raft-tech/TANF-app/blob/admin/github-cli-tools/gh-issues.bash), and the second script, [gh-csv.py](https://github.com/raft-tech/TANF-app/blob/admin/github-cli-tools/gh-csv.py), allow for downloading GitHub issues and exporting them into a CSV format for easier manipulation in spreadsheets.

The next steps involve enabling the toolset to upload changes made within the spreadsheet back into GitHub issues, including the ability to manage priorities and labels. This will streamline issue management and allow for more efficient collaboration across teams.

### Acceptance Criteria ###
- [ ] Toolset can upload changes to github issues
- [ ] Toolset can set priority/ranking in a visible way
- [ ] Github are our source of truth
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [ ] Implement upload functionality
- [ ] Parse label blob
- [ ] Investigate if tool can create labels and assign tickets a priority "P{number}" label
- [ ] Tool could update pre-existing spreadsheet to keep it current
- [ ] Implement "conflicts" resolution
- [ ] Investigate other capabilities and recommend out-of-scope follow-on (such as recurring cronjob to sync nightly)
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by lhuxraft** [comment]
Lauren to discuss moving to Jira at next product sync

**Comment by lhuxraft** [comment]
No longer needed with Andrew's departure
