### ISSUE TITLE
As a user, I need to be re-authenticated after X time.  

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#333]
**Description:**
This issue will deliver forcing a user to re-authenticate after X time after serving a notification.

**Acceptance Criteria:** 

- [ ] System does not allow a user to stay on past X time without re-authentication. 
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [ ] Review ACF access control policy to determine when a FISMA moderate system would force re-authentication
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- No specific guidelines in the ACF Access Control Policy

**Supporting Documentation:**
[ACF access control policy](https://app.zenhub.com/files/281707402/7c409b5d-9bcc-4a4c-8da4-1ffcbd2f804c/download)

**Open Questions:**
-  What is the max session age? 
-  What notification does a user receive prior to being forced to re-authenticate

**Comment by shubhi-raft** [comment]
super seeded by session timeout #196. ready to be closed.
