### ISSUE TITLE
Deprecate Cat 4 validation checks for case closure

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#3342]
### Background ###
Based on feedback from end users and the data team, OFA has decided to drop the following Cat 4 validation checks that currently prevent records from being stored in the database:

- [M5/T5] People in states must have a valid value for REC_SSI.
- At least one person on the case must have employment status = 1: Yes in the same RPT_MONTH_YEAR if CLOSURE_REASON = 1: Employment/excess earnings.
- [M5/T5] People in states should not have a value of 1 for REC_AID_TOTALLY_DISABLED.
- At least one person who is head-of-household or spouse of head-of-household must have countable months toward the time limit >= 60, where CLOSURE_REASON = 03: Federal 5-year time limit.

STTs have encountered difficulties verifying and correcting these issues, and not having these records in the database makes it challenging for OFA to provide additional feedback on closed case files. Instead, these checks will now be performed against data stored in the database.

### Acceptance Criteria ###
- [ ] ` __validate_case_closure_employment()` deprecated
- [ ] `__validate_case_closure_ftl()` deprecated
- [ ] `__validate_t5_atd_and_ssi()` deprecated
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [x] Remove validation checks that are no longer needed
- [x] Add flag for deprecation of validators in the future (timebox for a day)
- [x] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
- _Originally posted by @ADPennington in https://github.com/raft-tech/TANF-app/pull/3234#discussion_r1871629384_
 ![image](https://github.com/user-attachments/assets/ca8f0ba5-998d-465f-809f-c4fe6becfaec)

**Comment by andrew-jameson** [comment]
Will first attempt the deprecate(d) flag and include the listed functions under that. If this proves more than 3-pt territory, will create follow-up work and just remove these functions.
