### ISSUE TITLE
[Example] As a tadpole I would like to have an example of an Epic with separate backend and frontend tickets associated to it.

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#336]
**Description:**
This is an example Epic to demonstrate how it might tie in FE and BE work, while still remaining user focused at that Epic level. 

**Acceptance Criteria:** 

- [ ] Frontend tickets are created and tied to the epic
- [ ] Backend tickets are created and tied to the epic
- [ ] Epic is demonstrated to the team
- [ ] Everyone has a party

**Frontend Tasks:**

- [ ] Write tests appropriate to give thorough and robust coverage
- [ ] Create screen to display data
- [ ] Create form to edit/delete data
- [ ] Validate form
- [ ] Run Testing Checklist and confirm all tests pass

**Backend Tasks:**

- [ ] Write tests appropriate to give thorough and robust coverage
- [ ] Create endpoint that provides data
- [ ] Create endpoint that creates data
- [ ] Create endpoint that updates data
- [ ] Create endpoint that deletes data
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- Tickets associated to this epic do not actually need to be completed. They are given for example purposes.

**Open Questions:**

- Does this allow us to accomplish what OFA needs?
- Does this help the development flow?

**Comment by shubhi-raft** [comment]
Issue was created to demo #329
