### ISSUE TITLE
Update the existing OFA access workflow to include regions

### ISSUE THREAD

**Issue by lhuxraft** [raft-tech/TANF-app#3384]
### Background ###
As part of refining user access and permissions within TDP, we are introducing a new set of regional users with ACF email domains who will be able to select the regions they are responsible for when requesting access, ensuring they only interact with relevant data. Currently, the system does not differentiate between regions, which could lead to confusion or inappropriate access to unrelated data. To address this, regional users will be presented with checkboxes to select one or more regions, defining their scope of access. Additionally, regional users will receive email notifications when their access is requested, approved, or denied, improving communication and transparency. This solution will also involve updates to the user model to allow multiple region selections and the possibility of null STTs for regions with no available data, as well as changes to the permissions model to align with roles like the Data Analyst to ensure consistent access control.

### Acceptance Criteria ###
- [ ] When a user with an ACF email domain, they should be presented with the region checkboxes
- [ ] Regional user is emailed when access is submitted, approved, and/or denied. 
- [ ] The regional user must select 1+ region(s). 
- [ ] DAC should allow regional user with null STTs if region is selected. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [x] Create "central vs. regional" checkboxes
- [x] Update email triggers
- [x] Update the user model to allow for multiple region select and null STTs
- [x] Update the role permissions (similar to Data Analyst role)
- [x] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxOQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7345ef8a45fb423df16408512a8401e39f8f1c83/image.png" alt="image.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBOQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad22e11ec045b4a184e0ef211ee2a231873312e/image.png" alt="image.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenROQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16eb157ab71ed7242cb0f62ee7f7cecef4dade5c/image.png" alt="image.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhOQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40a33329b0a555c57381c169fdf13fd16e31ff09/image.png" alt="image.png" />

- [Requested Email Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/regional-request-for-access.html)
- [Request Approved Email Template](https://reitermb.github.io/TDP-HTML-Email-Demo-Environment/regional-request-approved.html)
