### ISSUE TITLE
Update Data Files page for regional staff

### ISSUE THREAD

**Issue by lhuxraft** [raft-tech/TANF-app#3385]
### Background ###
Regional staff will soon be onboarded as new users of TDP. However, their access needs are more limited compared to other users, as they will only require access to specific sections of the platform—namely, the Submission History for STTs within their assigned region. Regional staff should not have access to upload or download data files across the system, as those actions are outside the scope of their responsibilities.

### Acceptance Criteria ###
- [x] Regional user can view submission history for STTs in their region.
- [x] Regional user can't upload files to any section of TDP. 
- [x] Regional user can't download data files from TDP. 
- [x] Clicking 'Search' automatically shows Submission History. 
- [ ] README is updated, if necessary

### Tasks ###
- [x] Change the search form to only include STTs in the regional user's region
- [x] In Submission History, update Data File links to only show file names. 
- [x] Write E2E tests in Cypress. 
- [x] Update the Fiscal Year label to 'Fiscal Year (October - September)'
- [x] Remove 'Associated' from 'Associated State, Tribe, & Territory'
- [ ] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxOQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7345ef8a45fb423df16408512a8401e39f8f1c83/image.png" alt="image.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenBOQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad22e11ec045b4a184e0ef211ee2a231873312e/image.png" alt="image.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenROQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16eb157ab71ed7242cb0f62ee7f7cecef4dade5c/image.png" alt="image.png" />
<img width="200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhOQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40a33329b0a555c57381c169fdf13fd16e31ff09/image.png" alt="image.png" />

### Notes ###
- We may want to evaluate Cypress test feasibility, as we have been running into recent issues with Cypress.
