### ISSUE TITLE
Update Citizenship/Immigration Status Acceptable Values (TANF only)

### ISSUE THREAD

**Issue by klinkoberstar** [raft-tech/TANF-app#3386]
### Background ###
OFA has updated the TANF data reporting instructions (ACF-199) to address a policy question raised by a state. This change adds a new acceptable value to Citizenship/Immigration Status:

3 = Non-qualified alien

The coding change is required in three specific items within the system:

- T2: Item 42 Citizenship/Immigration Status
- T3: Item 76 Citizenship/Immigration Status
- T5: Item 25 Citizenship/Immigration Status

### Acceptance Criteria ###
- [ ] Each TANF Active and Closed file T2, T3, and T5 allows 3 as a valid input for Citizenship/Immigration Status.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### Tasks ###
- [x] Update t2.py to accept value 3 at [Line 410](https://github.com/raft-tech/TANF-app/blob/62fde87631312c709a3915f2c7ed6dee764b514f/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t2.py#L410).
- [x]  Update t3.py to accept value 3 at [Line 295](https://github.com/raft-tech/TANF-app/blob/62fde87631312c709a3915f2c7ed6dee764b514f/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t3.py#L295).
- [x] Update t5.py to accept value 3 at [Line 357](https://github.com/raft-tech/TANF-app/blob/62fde87631312c709a3915f2c7ed6dee764b514f/tdrs-backend/tdpservice/parsers/schema_defs/tanf/t5.py#L357).
- [x] Run Testing Checklist and confirm all tests pass

### Supporting Documentation ###
- T2 Item 42. Citizenship/Immigration Status: 
![Screenshot 2024-12-18 140646](https://github.com/user-attachments/assets/a3f1ca0b-3d59-418c-809a-4613b012e666)

- T3 Item 76. Citizenship/Immigration Status: 
![Screenshot 2024-12-18 140631](https://github.com/user-attachments/assets/9639a9a1-8138-4200-af21-87eeeae5bd14)

- T5: Item 25 Citizenship/Immigration Status:
![Screenshot 2024-12-18 140659](https://github.com/user-attachments/assets/50a9d774-a112-4607-ad69-2af0efa12540)

**Comment by ADPennington** [comment]
@klinkoberstar i made minor edits. good to queue for backlog refinement 🥇

**Comment by lhuxraft** [comment]
May also want to perform a cursory check to ensure no references in the codebase were missed

**Comment by klinkoberstar** [comment]
@elipe17, thank you for flagging that there are some Cat 3 checks related to Citizenship/Immigration Status affected by this change. After discussing with the DIGIT team, we decided to add "3" as an acceptable value for the existing Cat 3 checks.

In T2:
	• When Item 30 (Family Affiliation) = 1, then Item 42 (Citizenship/Immigration Status) must be one of (1, 2, 3).
In T3:
	• When Item 67 (Family Affiliation) = 1, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3).
	• When Item 67 (Family Affiliation) = 2, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3, 9).
In T5:
	• When Item 14 (Family Affiliation) is 1, then Item 25 (Citizenship/Immigration Status) must be between 1 and 3.

Note: As part of this discussion, we identified the need for a new follow-on ticket to validate the specific cases where Citizenship = 3 is valid (only when Item 8 (Funding Stream) = 2) This new case consistency check is outside the scope of this ticket and will be addressed separately.

Tagging for visibility: @ADPennington

**Comment by lhuxraft** [comment]
> [@elipe17](https://github.com/elipe17), thank you for flagging that there are some Cat 3 checks related to Citizenship/Immigration Status affected by this change. After discussing with the DIGIT team, we decided to add "3" as an acceptable value for the existing Cat 3 checks.
> 
> In T2: • When Item 30 (Family Affiliation) = 1, then Item 42 (Citizenship/Immigration Status) must be one of (1, 2, 3). In T3: • When Item 67 (Family Affiliation) = 1, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3). • When Item 67 (Family Affiliation) = 2, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3, 9). In T5: • When Item 14 (Family Affiliation) is 1, then Item 25 (Citizenship/Immigration Status) must be between 1 and 3.
> 
> Note: As part of this discussion, we identified the need for a new follow-on ticket to validate the specific cases where Citizenship = 3 is valid (only when Item 8 (Funding Stream) = 2) This new case consistency check is outside the scope of this ticket and will be addressed separately.
> 
> Tagging for visibility: [@ADPennington](https://github.com/ADPennington)

@klinkoberstar Would you mind creating the ticket to address the gap you outlined and providing the link to the ticket? Thanks in advance!

**Comment by klinkoberstar** [comment]
> > [@elipe17](https://github.com/elipe17), thank you for flagging that there are some Cat 3 checks related to Citizenship/Immigration Status affected by this change. After discussing with the DIGIT team, we decided to add "3" as an acceptable value for the existing Cat 3 checks.
> > In T2: • When Item 30 (Family Affiliation) = 1, then Item 42 (Citizenship/Immigration Status) must be one of (1, 2, 3). In T3: • When Item 67 (Family Affiliation) = 1, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3). • When Item 67 (Family Affiliation) = 2, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3, 9). In T5: • When Item 14 (Family Affiliation) is 1, then Item 25 (Citizenship/Immigration Status) must be between 1 and 3.
> > Note: As part of this discussion, we identified the need for a new follow-on ticket to validate the specific cases where Citizenship = 3 is valid (only when Item 8 (Funding Stream) = 2) This new case consistency check is outside the scope of this ticket and will be addressed separately.
> > Tagging for visibility: [@ADPennington](https://github.com/ADPennington)
> 
> [@klinkoberstar](https://github.com/klinkoberstar) Would you mind creating the ticket to address the gap you outlined and providing the link to the ticket? Thanks in advance!

@lhuxraft sure - I'll get to this later today.

**Comment by klinkoberstar** [comment]
> > > [@elipe17](https://github.com/elipe17), thank you for flagging that there are some Cat 3 checks related to Citizenship/Immigration Status affected by this change. After discussing with the DIGIT team, we decided to add "3" as an acceptable value for the existing Cat 3 checks.
> > > In T2: • When Item 30 (Family Affiliation) = 1, then Item 42 (Citizenship/Immigration Status) must be one of (1, 2, 3). In T3: • When Item 67 (Family Affiliation) = 1, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3). • When Item 67 (Family Affiliation) = 2, then Item 76 (Citizenship/Immigration Status) must be one of (1, 2, 3, 9). In T5: • When Item 14 (Family Affiliation) is 1, then Item 25 (Citizenship/Immigration Status) must be between 1 and 3.
> > > Note: As part of this discussion, we identified the need for a new follow-on ticket to validate the specific cases where Citizenship = 3 is valid (only when Item 8 (Funding Stream) = 2) This new case consistency check is outside the scope of this ticket and will be addressed separately.
> > > Tagging for visibility: [@ADPennington](https://github.com/ADPennington)
> > 
> > 
> > [@klinkoberstar](https://github.com/klinkoberstar) Would you mind creating the ticket to address the gap you outlined and providing the link to the ticket? Thanks in advance!
> 
> [@lhuxraft](https://github.com/lhuxraft) sure - I'll get to this later today.

@lhuxraft @elipe17 Necessary updates to Cat 3 check captured here: #3431
