### ISSUE TITLE
3.7.7 Release Notes

### ISSUE THREAD

**Issue by lhuxraft** [raft-tech/TANF-app#3392]
**Description:**
This ticket is to track release notes to STTs on the TDP portal, relative Knowledge Center Updates and the release notes Email sent to STTs.

**AC:**
- [x] Content drafted in Gitbook
- [x] Changes staged in Knowledge Center Test environment
- [x] A11y tested

**Tasks:**
- [x] UX Create a Ticket for Release Notes + Email Template 
- [x] UX/OFA Generate Draft in GitBook 
- [x] Receive Content Feedback from PM/Dev/UX/OFA, schedule sync to finalize 
- [x] UX Update release notes section and/or knowledge center for test environment
- [x] UX Update release number on release note provided by dev
- [x] Attach proof of a11y pass. 
- [x] UX Create a project repo PR and request final-mile approval from OFA. 
- [x] Dev cuts release: [Can find release number here ](https://github.com/raft-tech/TANF-app/releases)
- [x] UX Makes final-mile edits to the PR/Test environment as needed until approved.
- [x] OFA approves PR
- [x] UX merges PR to Knowledge Center after release is pushed to production.
- [x] UX Create Email and send draft to Alex/Thomas for approval
- [ ] UX makes edits to email as applicable, sends final draft
- [ ] OFA sends email release notes to STTs

**Supporting Documentation and Links:**

![image2](https://github.com/user-attachments/assets/3e9d6a13-596d-4025-887b-4941c6a59179)

**Comment by victoriaatraft** [comment]
<img width="1442" alt="Screenshot 2025-01-14 at 7 49 01 AM" src="https://github.com/user-attachments/assets/0a1f1d7e-5ba6-4175-abbe-2dc9db40e598" />
<img width="1443" alt="Screenshot 2025-01-14 at 7 50 01 AM" src="https://github.com/user-attachments/assets/d0356871-66f1-4080-a85c-716d9a2bf09f" />

**Comment by victoriaatraft** [comment]
Update: Blocked until we can get clarity on #3383
