### ISSUE TITLE
As an admin, I can view a list of users in the system 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#349]
**Description:**
#### [breakout tasks in this issue to create new issues for epic #395]

This issue will deliver an admin viewing a list of all the users and associated email address, role, STT, ('Actions'?/).

**Acceptance Criteria:** 
- [ ] Admin can view a list of all the users, email address, role, STT, and ('Actions'??)
- [ ] Filter/combo box will be a placeholder ?
- [ ] New ticket is created for implementing filter/combo box functionality ?
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create MVP version based on #237
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- MVP version of #327 is needed to prior to starting work on this issue

**Open Questions:**
- Is filter/combo functionality needed for OFA MVP?
  - Not needed
- Should the list be filterable by STT or regions?
- For multi-select filtering for filtering regions/STT work, is there a USWDS component?
- What does clicking on 'Edit' do? Does it need to be defined for OFA MVP?

**Supporting Documentation:**
![Screen Shot 2020-10-20 at 9.46.25 PM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/49f7bbcf-4f20-49f1-8e60-e95e07fdc88f)

**Comment by shubhi-raft** [comment]
issues have been broken down and added to #395.
