### ISSUE TITLE
[Backend] Endpoint to return a list of users with STT and Region

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#352]
Description:
This issue will deliver a `GET` endpoint of users with no role assigned. 

### Tasks
- [ ] Tests to cover list of users with STT and Region endpoint
- [ ] Add STT and Region results to User Endpoint

### AC
- [ ] Demonstrated `GET` request will return results like the following
```
{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe",
  "stt": {
    "id": 1,
    "type": "state",
    "code": "AL",
    "name": "Alabama"
  },
  "region": 1
},
{
  "id": 2,
  "first_name": "Jane",
  "last_name": "Doe",
  "stt": {
    "id": 15,
    "type": "state",
    "code": "MI",
    "name": "Michigan"
  },
  "region": 3
}
```
### Notes
- An endpoint already exists for a list of users, so the task here is merely to add STT and region data to the results

**Comment by jtwillis92** [comment]
Closing this as it is no longer needed since we decided to use Django Admin: https://github.com/raft-tech/TANF-app/pull/432#issuecomment-782116514
