### ISSUE TITLE
[Backend] Endpoint with list of current roles and associated permissions

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#353]
### Description
The issue will deliver an endpoint that provides a list of current roles and associated permissions

### Tasks
- [x] Tests to cover list of roles and associated permissions endpoint
- [x] Create endpoint to return a list of roles and associated permissions

### AC
- [x] Demonstrated `GET` request will return results like the following
```
{
  "role": {
    "name": "Data Prepper"
    "permissions": {
        "data": "can create",
        "data": "can edit",
        "data": "can delete"
    }
  }
},
{
  "role": {
    "name": "OFA Admin"
    "permissions": {
        "data": "can create",
        "data": "can edit",
        "data": "can delete",
        "user": "can edit",
        "user": "can delete",
        "stt": "can create",
        "stt": "can edit",
        "stt": "can delete"
    }
  }
},
```
### Notes
- At this point I'm not exactly sure how the response will be shaped. My intent is just to return it in a default way to save time and effort, so I will update here once I have more certainty on that.

**Comment by carltonsmith** [comment]
@kniz-raft This was actually completed as part of #309 so it can be closed from my perspective

**Comment by kniz-raft** [comment]
@lfrohlich Based on Carl's comment, are you okay to close this?
