### ISSUE TITLE
[Backend] Endpoint to update the roles of a list of users

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#354]
### Description
This issue will deliver an endpoint to update the roles of a list of users

### Tasks
- [ ] Tests to cover updating the roles for a list of users
- [ ] Create endpoint to update a list of user with roles

### AC
- [ ] Endpoint exists at `/v1/users/update_roles`
- [ ] Demonstrated `PATCH` request with the following body returns a response like the one below
```
{
  "id": 1,
  "role": {
      "id": 4
  }
},
{
  "id": 2,
  "role": {
      "id": 3
  }
},
```
Response of `PATCH` request
```
{
  "id": 1,
  "first_name": "John",
  "last_name": "Doe",
  "role": {
    "id": 4,
    "name": "Data Prepper"
  },
  "message": "Success!"
},
{
  "id": 2,
  "first_name": "Jane",
  "last_name": "Doe",
  "role": {
    "id": 3,
    "name": "OFA Analyst"
  },
  "message": "Success!"
}
```

**Comment by lfrohlich** [comment]
@abottoms-coder  do we still need this?

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
