### ISSUE TITLE
[Frontend] Create Component for Assigning Roles

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#355]
### Description
This issue will deliver a route for admin users to assign roles to users. That route will render a new component (name TBD) that will contain a card for each user that needs to be assigned and will display their: name, email, associated STT and region. 

This issue will also add the `Admin` and `Profile` navigation links to the header and will create side navigation for the `Admin` user with `Users` and `Roles` options.

### Tasks
- [ ] Add `Admin` and `Profile` navigation links
- [ ] Add side navigation with `Active Users` `Inactive Users` `Access Requests` and `Reactivation Users` 
- [ ] Add `Assign Selected Roles` h1
- [ ] Create new component for assigning roles to users
- [ ] Create route for rendering component (possibly `/admin/roles/assign`)
- [ ] Add assign user card with name, email, stt and region
- [ ] Tests are created 

### Acceptance Criteria
- [ ] When visiting the route for the admin assignment component, a card will be visible with the user's name, email, stt and region
- [ ] Dropdown, Assign will be placeholders and dummy CTAs

### Notes
![Screen Shot 2020-11-20 at 6.50.26 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/96376a56-1885-47af-8de4-ee169578984c)
-

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
