### ISSUE TITLE
[Frontend] Role Selection Box

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#356]
### Description
This issue will add the `Select` element to the user card created in #355.  In order to populate the `Select` with options, a `GET` request will be implemented to get those values from the API. 

When the admin has selected a role to assign to the user, the information about that role will show up beneath the `Select` in line with the designs attached below.

### Tasks
- [ ] Add `Select` USWDS element for choosing user role
- [ ] Add fetch to get possible roles for user
- [ ] When role is selected populate card with information about role
- [ ] Tests are created

### Acceptance Criteria
- [ ] When visiting the route for the admin assignment page, there will be a `Select` element on the page.
- [ ] The fetch will be verifiable by the `Select` component having options.
- [ ] When a role is selected, the information about the role will be displayed beneath the `Select` element.

### Notes
![Screen Shot 2020-11-20 at 6.50.26 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/8558fae4-afa9-4e58-8894-3a63f6c1a7e9)

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
