### ISSUE TITLE
[Frontend] Send Role Information to Backend

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#358]
### Description
When the admin clicks the `Assign` button created in #357, it will call a `PATCH` endpoint to update the user with their assigned role. Once that `PATCH` call has completed successfully, a `Success` alert will be displayed.

### Tasks
- [ ] Add logic for the endpoint to assign a role
- [ ] Upon successful assignment of the role, a `Success` alert (https://designsystem.digital.gov/components/alert/) is displayed with the number of successful assignments, the names of the users who were successfully assigned, and their assigned role.
- [ ] Tests are created

### Acceptance Criteria
- [ ] When the `Assign` button is clicked, a success notification will be displayed.

### Notes
<img width="705" alt="Screen Shot 2020-10-28 at 3 40 10 PM" src="https://user-images.githubusercontent.com/23202538/97504314-e02cf000-1933-11eb-8d14-17a2559d062e.png">

**Comment by shubhi-raft** [comment]
@hilvitzs to update the description, tasks, and notes for this issue.

**Comment by amilash** [comment]
@abottoms-coder  is this functionality already done?

**Comment by abottoms-coder** [comment]
> @abottoms-coder is this functionality already done?

No, the screenshot is not the reality of the front-end. This is currently handled by the Django Admin Console's default user management. While the "admin" tab exists for "System Admin" users, it just links to "https://<hostname>:8080/admin/"

![image](https://user-images.githubusercontent.com/84722778/124291424-8fa10e80-db22-11eb-8e87-343ec64e683c.png)

**Comment by amilash** [comment]
Im marking this as V4 as in, we'll fix this when we port the UI out of django.

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
