### ISSUE TITLE
(Internal) Create milestone path to achieve OFA MVP Goal

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#373]
**Description:**
This issue will deliver creation of a milestone / sprint path to achieve OFA MVP goal. The milestone path will list all the user stories that must be completed to deliver each epic and a tentative timeline to complete each milestone.  

**Acceptance Criteria:** 

- [ ] Milestone/ Sprint path to OFA MVP is discussed and documented at a logical place (based on tasks)

**Tasks:**

- [x] Schedule a session to map out what next four sprints will accomplish to deliver OFA MVP
   - Discuss logical place to document milestone/sprint path (ZenHub milestones?)
- [x] Share with updated roadmap and milestone path with product team 

**Notes:**
- NA

**Supporting Documentation:**
- [Product Roadmap](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1592336604317/61159efd030645a74c267130ea19b2083f87dd09) 

**Open Questions:**
- NA

**Comment by shubhi-raft** [comment]
@lfrohlich the roadmap in zenhub board can suffice as our milestone path. once it has been updated with prioritizing w/ upload and download features, how do you feel about demoing that to the team in sprint 9?

**Comment by lfrohlich** [comment]
@shubhi-raft  it looks like the roadmap has been updated. I think would be good to demo to the team soon!

**Comment by lfrohlich** [comment]
Closing and incorporating goals into other issues
Update roadmap in docs as AC with research rounds https://github.com/HHS/TANF-app/blob/main/docs/Product-Strategy/Roadmap-and-Backlog.md
