### ISSUE TITLE
[Design] Update #164 mockup with design change to meet OFA MVP

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#376]
**Description:**
This issue will deliver updating left-hand tab navigation to screenshot below and remove card style. Content on card is being removed for MVP

**Tasks:**
- [x] Update left-hand navigation to include different user states (e.g., active, inactive, etc.)
- [x] Remove card style 
- [x] Remove `Cancel` button

**AC:**
- [x] Updates noted in tasks are complete

**Open Question(s):**
- Should we remove card style for MVP? 
  - Yes. We don't need to add card styles post MVP.

**Supporting Documentation:**
- NA

#### Deliverable(s):
Link to updated #164 [mockup](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

**Comment by lfrohlich** [comment]
This was completed
