### ISSUE TITLE
As a tadpole, I want to know the platform I use to login to TDP (new TDRS)

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#379]
**Description:**
Login.gov sandbox has been implemented to access the current (as of 10/28) version of TDP. OCIO wants TDP product team to evaluate ACF's centralized access management system () as a portal for ACF employees to login to TDP

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Consensus on timeline to integrate ACF's centralized access management system to TDP is formed and documented
- [ ] If applicable, impact of using ACF's centralized access management system for OFA MVP is documented and shared

**Tasks:**
- [ ] Lauren + Alex to discuss this more and engage @carltonsmith  to understand the impact 
- [ ] Evaluation of ACF's centralized access management system is complete and has been shared 
- [ ] Ask OCIO for more information, if necessary

**Notes:**
- [ACF Authentication Service Portal Documentation](https://teams.microsoft.com/l/file/01DDD7E9-B41B-4A21-BDAA-983467CA19E1?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=pptx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FACF%20Authentication%20Service.pptx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
- Can integration with the ACF's centralized system be done after OFA MVP?

**Comment by shubhi-raft** [comment]
@lfrohlich based on the recent discussions with OCIO, moving this back to be revisited post OFA MVP.

**Comment by alexsoble** [comment]
Can we close this one out thanks to @kniz-raft's work on Project brief and MVP?

**Comment by amilash** [comment]
Duplicate! Closing
