### ISSUE TITLE
As an OFA admin, I want users browsers to be forgotten for login.gov (AAL2-strict)

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#382]
**Description:**
Switch our login.gov Authentication Assurance Level (AAL) from AAL2-lite to AAL2-strict. We currently have login.gov set at AAL2-lite, which verifies that the user has a second factor login (could be any of the methods supported by login.gov). The "lite" part is that login.gov supports the user selecting to remember the browser for 30 days. 

**Acceptance Criteria:** 
- [x] AAL2- strict is implemented. 
- [x] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Make updates necessary to implement AAL2 -strict (TBD)
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
- Assumption: AAL2 will return the same data package as the current setup and the change will require simply changing the endpoints with minimal adjustments

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by shubhi-raft** [comment]
@carltonsmith could you please task this out and list out assumptions? Shubhi to create a spike issue.

**Comment by shubhi-raft** [comment]
- 11/24 demo feedback: 

'Remember Browser' is checked off when a user signs in and needs to authenticate separately (e.g, text message, google authenticate app, etc.). Tijan raised if that should be the case. Unclear whether this impacts any login related security control.

**Comment by jtwillis92** [comment]
All we need to do to enforce this across the board is change the value of the environment variable `ACR_VALUES` to: 
```
http://idmanagement.gov/ns/assurance/ial/2?strict=true
```
This gets set by default to `http://idmanagement.gov/ns/assurance/ial/1` in [common settings](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/tdrs-backend/tdpservice/settings/common.py#L18) so the only code change would be updating the default from there.

Then we'd just need to update or delete that environment variable in Cloud.gov for each environment.

**Comment by jtwillis92** [comment]
This actually didn't require any code changes as this setting gets configured through the Login.gov Dashboard:
![Screenshot from 2021-04-27 11-44-57](https://user-images.githubusercontent.com/22626085/116272348-d4897d00-a74e-11eb-8e39-e0af0a5cb6d9.png)
I updated the AAL level for all 4 Login.gov apps to set this as the default behavior:
```
AAL2 - MFA required + remember device is 12 hours
```
This was updated immediately on all the apps and I confirmed on both Development and Vendor Staging that I was re-prompted for MFA when I was still within the 30 day window from before.
