### ISSUE TITLE
As an OFA admin, I can deactivate user accounts

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#394]
**Description:**
This issue will deliver OFA admin deactivating accounts that have been inactive in the TDP system.

**Acceptance Criteria:** 

- [ ] 'Inactive Users' tab lists inactive users 
- [ ] Clicking on 'Manage' opens a new page that provides user profile and history
- [ ] Clicking on 'Deactivate' button, deactivates a user
- [ ] Success state notification is served upon successful deactivation 
- [ ] Frontend matches mockups
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by lfrohlich** [comment]
This could meet AC-02(07)	ACCOUNT MANAGEMENT | ROLE-BASED SCHEMES 
The organization:
(a) Establishes and administers privileged user accounts in accordance with a role-based access scheme that organizes allowed information system access and privileges into roles;
(b) Monitors privileged role assignments; and
(c) Takes [Assignment: organization-defined actions] when privileged role assignments are no longer appropriate.

**Comment by amilash** [comment]
I think the only thing left here is to update documenation.
