### ISSUE TITLE
As an OFA admin, I want to see a list of active users 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#395]
**Description:**
This issue will deliver a list of active users, profile information, affiliation, role, and action button(?) 

**Acceptance Criteria:** 

- [ ] Clicking on 'Active Users' tab displays list of users, name, email address, affiliation, and role.
- [ ] 'Manage' button is placeholder (depends on open question - see below)
- [ ] Frontend matches mockups (see supporting documentation)
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
![Screen Shot 2020-11-05 at 3.38.04 PM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/7c4c0070-1483-48b2-948b-f9ef182b7c4d)

**Open Questions:**
- Should clicking the action button do anything as part of this epic?

**Comment by carltonsmith** [comment]
@shubhi-raft #156 and #139 can be removed from the epic as they are accounted for in the remaining issues

**Comment by kniz-raft** [comment]
Removing from OFA MVP label for right now in favor of manual processes to get a list of active users

**Comment by amilash** [comment]
@abottoms-coder @ADPennington is this ticket still needed or is this work still done? Can you give us some details so @lfrohlich  and I can prioritize it properly? Thank you!

**Comment by ADPennington** [comment]
@amilash the work is incomplete. this was before my time but a couple of thoughts:
- the title could be renamed to mention `sys admin` instead of `ofa admin` since ofa admins do not have access to django admin. 
- it is possible for sys admins to see a list of all users but this list currently includes all approved users (some of whom could, in theory, be inactive or deactivated) as well as requesting users
- per dev sync on 6/30, we discussed the need for requesting user model so that we can maintain unapproved users separately. we also discussed the need to filter the approved user list to distinguish between active, short-term inactive, and long-term inactive ([ref](https://github.com/raft-tech/TANF-app/pull/930#issuecomment-866032809))
- given the above, i think this is related to #1001 and #960

cc: @abottoms-coder
