### ISSUE TITLE
As an OFA admin, I want to see a list of inactive users using Django's admin console (DAC)

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#396]
**Description:**
This issue will deliver a list of inactive users ~~profile information, affiliation, role, and action button(?)~~ using Django's admin console (DAC). The system will automatically deactivate users that have been inactive for over 120 days and will add them to the inactive user list.

**Acceptance Criteria:** 

- [ ] ~~Clicking on 'Inactive Users' tab displays list of users, name, email address, affiliation, and role.~~
- [ ] ~~'Manage' button is placeholder (depends on open question - see below)?~~
- [ ] ~~Frontend matches mockups (see supporting documentation)~~
- [ ] ~~New tickets are created for adding filtering, searching, and pagination~~ 
- [ ] ~~Testing Checklist has been run and all tests pass~~
- [ ] Demo list of inactive users using Django's admin console (DAC) 
- [ ] Update documentation with AU-02 security control (with screenshots using DAC, if necessary) 
- [ ] New issue is created to deliver this functionality via UI  

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
 - Manage Mockup #404 
- Supporting doc to be updated based on #404 approval
- Security control is AU2
- Will need to add a third party extension to allow filtering in Django Admin

**Assumptions:**
- A viable extension exists and can be implemented

**Supporting Documentation:**

<img width="729" alt="Screen Shot 2020-11-17 at 9 07 31 PM" src="https://user-images.githubusercontent.com/22622384/99473627-ef8ed000-2918-11eb-99ef-69fab882faad.png">

**Open Questions:**
- Does this UI meet the application log security control (AU2?)?

**Comment by shubhi-raft** [comment]
create new epic to flush out manage functionality @shubhi-raft

**Comment by kniz-raft** [comment]
Removing from OFA MVP for the first release in favor of other manual work-arounds to show a list of inactive users

**Comment by amilash** [comment]
@abottoms-coder @ADPennington Same question here- what is done and what is still needed here? @lfrohlich  and I want to prioritize this work or close the ticket if its complete. Thank you!

**Comment by amilash** [comment]
Closing this as will not do- we have a TDP permission epic that covers the remained of this work. Thanks
