### ISSUE TITLE
As an OFA admin, I want to see a list of users requesting reactivation in Django's admin console 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#397]
**Description:**
This issue will deliver a list of users requesting reactivation to TDP using Django's admin console (DAC). 

**Acceptance Criteria:** 

- [ ] ~~'Reactivation Requests' tab will show users that have requested re-access to TDP system~~
- [ ] ~~Clicking on 'Reactivate' button will ?~~ 
- [ ] ~~Success notification is served~~
- [ ] ~~Frontend is same as the mockups~~
- [ ] ~~Testing Checklist has been run and all tests pass~~
- [ ] Demo list of users requesting reactivation using Django's admin console (DAC) 
- [ ] Update documentation with IA-04(04) security controls (with screenshots using DAC, if necessary) 
- [ ] New issue is created to deliver this functionality via UI  

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Use 
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Mockup #404 

**Supporting Documentation:**
#### This is a placeholder and may get changed. 
![Screen Shot 2020-11-05 at 6.40.00 PM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/af86d14f-9b92-4e2d-ba1a-6a8d12cd0fb6)

**Open Questions:**
- Which security control is applicable?
- Can this functionality be delivered by Django's admin console? If so, update AC.

**Comment by kniz-raft** [comment]
Moving out of OFA MVP to a more manual solution, but this will need to be included in future releases.

**Comment by amilash** [comment]
@dk-ui  @reitermb is this considered part of the work for the request process? Or have we been considering it separately? @lfrohlich  and I are trying to see where to prioritize this work. It looks like the designs are done based on the ticketing. Thanks!

**Comment by reitermb** [comment]
@amilash 
> @dk-ui @reitermb is this considered part of the work for the request process? Or have we been considering it separately? @lfrohlich and I are trying to see where to prioritize this work. It looks like the designs are done based on the ticketing. Thanks!

This might need some refinement. This was originally for a TDP side admin interface, not django. In the longer term this seems like something that still makes sense in a TDP admin interface (given that we want regional folks to be able to admin their respective regions and we don't want them to do it through django). 

If we pursue this earlier rather than later we should also make sure to prioritize the more productized version of "As a deactivated user I want to request reactivation through TDP". Currently the "You are deactivated" message involves being kicked back to the homepage (logged out) and instructs the user to email an OFA address to request reactivation.

**Comment by robgendron** [comment]
@reitermb is this still needed?

**Comment by robgendron** [comment]
Deemed closed by team.
