### ISSUE TITLE
As an OFA admin, I can securely upload each section of a new TANF report

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#398]
**Description:**
This issue will deliver an OFA admin can securely uploading each section of new TANF report. 

**Acceptance Criteria:** 
- [ ] Data is uploaded, stored, and actions are logged per security controls 
- [ ] :smiling_imp: As an unauthenticated user, I cannot access the S3 bucket ~~upload to download files~~ through the command line
- [ ] :smiling_imp: As an OFA admin, I cannot upload an executable, or python, etc. file 
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
- [ ] Discuss reusing Tim's prototype functionality. 
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- OFA admin will act as a test users to upload data (consider creating a new epic for it for next backlog refinement)
-  Log of file being uploaded and replaced includes- file name, file type, when, who
- For MVP, we will focus on .txt file. Flat files have not extension and it will be treated as a .txt file.
- SC-08	(TRANSMISSION CONFIDENTIALITY AND INTEGRITY "The information system protects the [Selection (one or more): confidentiality; integrity] of transmitted information)
  - Store: Cloud.gov S3 implementation
  - Transmission - HTTPS/ 
- S3 buckets are encrypted by default 
- Protection of Information at Rest - https://cloud.gov/docs/services/s3/ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
- Confirm whether transmission is HTTPS - TLS 1.2?

**Comment by lfrohlich** [comment]
Following up on our discussion re: file type, for the OFA MVP we only need the app to accept flat files (with no extensions, but can be opened as .txt). It's fine if it accepts .xls/.xlsx or .csv, but those are not necessary for MVP.  @shubhi-raft  @carltonsmith

**Comment by kniz-raft** [comment]
Removing OFA MVP label, but this needs to be a fast follower (concept of uploading section by section)

**Comment by amilash** [comment]
This is done, as you can see by the closed subtasks.
