### ISSUE TITLE
[Frontend] Add Active Users Tab

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#411]

**Comment by carltonsmith** [comment]
**Description**
Add a tab to the user interface with the label "Active Users".

**Tasks**
- [ ] Add a tab to the user interface with the label "Active Users"
- [ ] Add tests as necessary

**Acceptance Criteria**
- [ ] User interface displays a tab labeled "Active Users"
- [ ] Clicking the tab displays a blank page
- [ ] All tests are passing
- [ ] Testing coverage exceeds 90%

**Comment by carltonsmith** [comment]
@hilvitzs Please update tasks if necessary

**Comment by amilash** [comment]
Closing. We will revisit when we move django admin console to UI

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
