### ISSUE TITLE
[Frontend] Add table to display users

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#412]

**Comment by carltonsmith** [comment]
**Description**
Add a table to the "Active Users" page that displays a list of users including name, email address, affiliation and role.

**Tasks**
- [ ] Consume backend users endpoint or mock data if the backend isn't ready yet
- [ ] Display users in a table in accordance with the design documented in the epic
- [ ] Add tests as needed

**Acceptance Criteria**
- [ ] Clicking "Active Users" tab displays a table with a list of users
- [ ] User list will contain the user's name, email address, affiliation and role
- [ ] Necessary tests are written
- [ ] Testing coverage exceeds 90%

**Comment by carltonsmith** [comment]
@hilvitzs Please update the tasks if needed

**Comment by amilash** [comment]
We will revisit when we move admin console out of django

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
