### ISSUE TITLE
[Backend] Add list users endpoint

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#413]
## Description
Add list users endpoint

## Acceptance Criteria
- [ ] Endpoint listing active users, including roles exists
- [ ] Endpoint listing inactive users exists
- [ ] Endpoint listing all users exists

## Tasks
- [ ] Update user view to add List mixin
- [ ] Leverage current user serializer to create list
- [ ] Update current user serializer to include roles
- [ ] Add active/inactive field to user model
- [ ] Add endpoint to list only active users
- [ ] Add endpoint to list only inactive users

## Notes
- All of these endpoints aren't needed for the Epic AC, but they will be needed down the line and it will be easiest to add them all at the same time

## Open Questions
1. Will this still be needed if we have XMS? My thinking is yes, since this is how you will see user profiles in the system and give access to change roles

**Comment by carltonsmith** [comment]
**Description**
Update the users `GET` endpoint to include user roles

**Tasks**
- [ ] Add roles to the user `GET` endpoint
- [ ] Adjust affected tests
- [ ] Add new tests as needed

**Acceptance Criteria**
- [ ] User `GET` endpoint returns the appropriate role for each user
- [ ] All tests are passing
- [ ] Testing coverage exceeds 90%

**Notes**
- Results from the endpoint should match the example JSON below
```
{
  "first_name": "John",
  "last_name": "Doe",
  "username": "johndoe@example.com",
  "stt": {
    "id": 23,
    "name": "Michigan",
    "codename": "MI",
    "type": "state"
  },
  "role": {
    "id": 3,
    "name": "Data Prepper"
  }
},
{
  "first_name": "Jane",
  "last_name": "Doe",
  "username": "janedoe@example.com",
  "stt": {
    "id": 1,
    "name": "Federal Government",
    "codename": "US",
    "type": "territory"
  },
  "role": {
    "id": 1,
    "name": "OFA Admin"
  }
}
```

**Comment by carltonsmith** [comment]
@riatzukiza Please update the tasks if needed

**Comment by ADPennington** [comment]
@Smithh-Co i believe this ticket can be closed as it is related to #2477 and #2551

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
