### ISSUE TITLE
[Frontend] Add Manage Button

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#414]

**Comment by carltonsmith** [comment]
**Description**
Add "Manage" button to "Active Users" page

**Tasks**
- [ ] Add "Manage" button to "Active Users" page

**Acceptance Criteria**
- [ ] "Manage" button is added to "Active Users" page
- [ ] Appearance conforms with mockups documented in Epic
- [ ] All tests are passing
- [ ] Test coverage exceeds 90%

**Note**
The button should not do anything at this point

**Comment by carltonsmith** [comment]
@hilvitzs Please update tasks if necessary

**Comment by robgendron** [comment]
@andrew-jameson and I deemed not needed, not aligned with the roadmap.
