### ISSUE TITLE
[Design] As a test user, I want to see dev-ready mockups for downloading report files

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#415]
#### Problem Statement:
This issue will deliver dev ready mockups to download flat files that are uploaded #398.

#### Questions:
- Will a download button suffice or do we need to show summary screen? 
   - Download button is ok  

#### AC: 
- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [x] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 
- [x] [User flow is updated](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

#### Tasks
- [x] Refine conceptual mockups #115 and #275 to make them dev ready mock-ups for #89.
- [x] Update user flow to include download files
- [x] Check for [accessibility](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

#### DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

#### Deliverables
Figma design: [Link](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2933%3A0)
User flow update: [Link](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=1277%3A8087)

**Comment by dk-ui** [comment]
@shubhi-raft Ready to Raft review

**Comment by lfrohlich** [comment]
Thanks for incorporating my comments, including adding the notations to the arrows between screens. This was completed and demoed as part of sprint 12/7
