### ISSUE TITLE
[Backend] Create endpoint to retrieve raw file

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#417]
## Description
As a user, I need a way to download raw files that have been previously uploaded to the application

## Acceptance Criteria
- [ ] Endpoint serves file to the frontend based on identifying information sent from the frontend
- [ ] `Data Prepper` users are able to download files except for their own STT
- [ ] `OFA Admin` users are able to download files for any STT

## Tasks
- [ ] Create endpoint that receives a request from the FE and fetches a file from S3 and returns the file as the response
- [ ] @riatzukiza to look into S3 feature to see what it logs when downloading files
- [ ] Write tests as needed

## Open Questions
* We need to determine if the backend is needed for this, as the frontend is able to pull the files from S3 directly
  * Do we need to log when a user downloads a file? Get clarification during IPT - Dec 11 @lfrohlich

**Comment by carltonsmith** [comment]
**Note**

Issue description, tasks and acceptance criteria will be added once the mockup is accepted and reviewed

**Comment by riatzukiza** [comment]
I feel like this one is also a duplicate of 431?
