### ISSUE TITLE
[Project Management] Create tickets for adding filtering, searching, and pagination

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#418]

**Comment by carltonsmith** [comment]
**Description**
Create tickets for adding filtering, searching and pagination on the "Active Users" page

**Tasks**
- [ ] Gather requirements for filtering, searching and pagination
- [ ] Create tickets for adding filtering, searching and pagination

**Acceptance Criteria**
- [ ] Tickets are created for filtering, searching and pagination

**Comment by shubhi-raft** [comment]
this has added as an AC to the epic #395.
