### ISSUE TITLE
Add roles to User model

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#420]
**Description:**

All other backend tasks for epic #9 will require that there is a role on the user model. This issue is to implement roles on the user model.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [ ] Add tests for user roles
- [ ] Add user roles utilizing djangos built in AbstractBaseUser role interface
- [ ] Role serializer(?)
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

```py
form django.contrib.auth.models import AbstractUser

class User(AbstractUser):
      DOCTOR = 1
      NURSE = 2
      SURGEN =3
      
      ROLE_CHOICES = (
          (DOCTOR, 'Doctor'),
          (NURSE, 'Nurse'),
          (SURGEN, 'Surgen'),
      )
      role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, blank=True, null=True)
      # You can create Role model separately and add ManyToMany if user has more than one role
```

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
