### ISSUE TITLE
As a Sys admin, I want to re-activate inactive users

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#426]
**Description:**
This issue will deliver reactivating inactive users though the user interface. 

**Acceptance Criteria:** 

- [ ] Clicking on 'Manage' button in Inactive users page opens a new page
- [ ] Clicking on 'Reactivate' button serves a success notification 
- [ ] Inactive page is updated
- [ ] Frontend matches mockups (see supporting documentation)

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
<img width="730" alt="Screen Shot 2020-11-17 at 9 09 05 PM" src="https://user-images.githubusercontent.com/22622384/99473728-28c74000-2919-11eb-89cf-8c2506c10a0b.png">

<img width="747" alt="Screen Shot 2020-11-17 at 9 10 37 PM" src="https://user-images.githubusercontent.com/22622384/99473817-5d3afc00-2919-11eb-8c43-5a87e7eccfe0.png">

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by amilash** [comment]
@dk-ui do we see this as part of later features, or is this/can this be part of the authentication/access request workflow considerations? thanks!

cc @lfrohlich

**Comment by amilash** [comment]
@ADPennington  @lfrohlich based on our conversations this week about Admin enhancements, is this an item that we want to build in Django before we have tribal users, or can it wait till our public release (v3?). Thanks! 
This may get covered within our Access request work also, so linking it to that epic until I hear back so we dont loose it.

**Comment by lfrohlich** [comment]
I believe this can be done in Django already, but i recall there being an issue with how to tell someone was inactive. Is that right @ADPennington ? The user interface itself could wait until V3, and I agree should be part of other conversations/epics around access flow.

**Comment by ADPennington** [comment]
@amilash @lfrohlich currently, sys admins have the ability to re-activate inactive users via unchecking the `deactivated` status in a user's profile--see [here](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Technical-Documentation/images/admin_users.png). when this is checked, the user sees an inactive status on frontend as shown [here](https://github.com/raft-tech/TANF-app/pull/930#issuecomment-866032809). 

i agree this can wait until V3, so long as we are not relying on anyone other than sys admins to manage users during tribal mvp. also, really like how clean this mockup looks!

**Comment by ADPennington** [comment]
@lfrohlich @valcollignon based on my most recent comment, i think this can be closed. We may need to revisit this again for regional staff user management, but i think that's a separate ticket.

**Comment by lfrohlich** [comment]
I agree, I think this can be closed
