### ISSUE TITLE
[Design] As a test user, I want to see dev-ready mockups to upload each section of a TANF report

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#427]
#### Problem Statement:
For OFA MVP,  test users acting as STTs need to upload each section of TANF report . This issue delivers dev ready mockups for choosing TANF report year between 2020 and 2021 and uploading files for each section of a TANF report for a quarter.

#### Questions:
- Do we need button to resubmit a TANF report? If so, update #119.
   - Yes, to replace uploaded files 
- Do we need progress bar to show percentage of upload for OFA MVP?
Answer: No
- How far back can a STT go to resubmit their report? This would helpful in determining whether we use a combobox or select (dropdown) component in design. 
Answer: Year is needed. Ask OFA data team about how far back can resubmit the TANF data report. Ask Robert Jolly whether combobox is needed if more than 15 options to display a list of years. 
- What does uploading look like for an OFA admin? Can you select which grantee? What is needed for OFA MVP?
  - Mockup for OFA admin uploading TANF report for grantees may look different. New issue #446 has been created and will be revisited post OFA MVP. 

#### AC: 
- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [x] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 
- [x] [User flow is updated](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

#### Tasks
- [x] Refine conceptual mockups #115 and #275 to make them dev ready mock-ups for #398. (Stepper is not going to be implemented in OFA MVP)
- [x] Update 'Validate File Details' to something to do with uploading files. 
- [x] Ask OFA data team about how far back can resubmit the TANF data report for drop down selection to select an year
- [x] Ask Robert Jolly whether combobox is needed if more than 15 options (accessibility check) to display a list of years. 
- [ ] Update #119 if we need resubmission button
- [ ] Check for [accessibility](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287)

#### DD
- [ ] Documentation: Design has been shared with the PO and team for feedback
- [ ] @lfrohlich has reviewed and signed off

#### Notes:
- User research findings: 
   - There were unfamiliar fields and layouts in the XLS template
   - Consider what header fields we actually need from the data submitter and which can be filled in by a default value or by OFA. For essential values, consider plain language labels to explain new concepts that are visible to data submitters.

Supporting documentation:
- #115 and #275
- [Figma Mockups](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2933%3A0)
- [User Flows](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=1277%3A8087)

Deliverable(s):
- [Link to Figma](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2933%3A0)

**Comment by lfrohlich** [comment]
Added comments in Figma re: removing Test Quarter placeholder language (which @reitermb already changed :) ) . For now, we only need 2019 and 2020. To discuss; what is uploading for an OFA admin? Can you select which grantee? What is needed for OFA MVP?

**Comment by lfrohlich** [comment]
Thanks for adding the notation to the arrows! This looks good and is ready to demo.
