### ISSUE TITLE
[Frontend] Add component to input single file

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#429]
**Description:**
Add [file input page USWDS component](https://designsystem.digital.gov/form-controls/08-file-input/) to input single files that are -.txt, .csv, or .xls/.xlsx. 

**Acceptance Criteria:** 

- [x] Files Input accepts a single file 
- [x] Input accepts only -.txt, .csv, or .xls/.xlsx file types
- [x] Upload button is a placeholder
- [x] Input displays a helpful error message when a wrong file type is uploaded 
- [x] Frontend matches #427 delivered and accepted mockup
- [x] Testing Checklist has been run and all tests pass

**Tasks:**

- [x] UX to pair with OFA data team to finalize acceptable file types
- [x] Pair with UX to finalize error message 
- [ ] Pair with Alex S and potentially Tim (original TANF prototype) to see what we can leverage/reuse code

- [x] Set values of file uploads to state for submission.
- [x] Add `form` to page that wraps all sections.
- [x] Run Testing Checklist and confirm all tests pass

- [x] Create path `/reports/[submission year]/upload`
- [x] Create new page with h1 `New TANF Report`
- [x] Create redux state module for files
- [x] Create action for file uploads
- [x] Create reducer for file uploads action
- [x] Create four sections
    - [x] `Section 1 - Active Case Data`
    - [x] `Section 2 - Closed Case Data`
    - [x] `Section 3 - Aggregate Data`
    - [x] `Section 4 - Stratum Data`
- [x] Create a `FileUpload` component to be reused inside of each of the four sections

**Notes:**
- [USWDS component](https://designsystem.digital.gov/form-controls/08-file-input/)
- Post MVP - .pdf and .doc

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
-

**Comment by kniz-raft** [comment]
Currently blocked by CORs issue.

**Comment by reitermb** [comment]
👍 on a11y raft review!

**Comment by carltonsmith** [comment]
@ADPennington @lfrohlich Are we accepting multiple file types for ATO, or just `txt` files right now?

**Comment by ADPennington** [comment]
> @ADPennington @lfrohlich Are we accepting multiple file types for ATO, or just `txt` files right now?

txt 😄
