### ISSUE TITLE
[Frontend] Add Submit Files button to upload files

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#430]
### Description:
Add `Submit Data Files` button to upload file page (updated based on final #427)

### Acceptance Criteria

- [x] There is a header with text "[The Selected Year]"
- [x] There are 4 sections for uploading documents
- [x] `Submit Data Files` button is added to the page (updated based on final #427)
- [x] The File Upload inputs accepts files that are not binary
- [x] Frontend matches #427 delivered and accepted mockup 
- [x] Files are sent to endpoint when clicking `Submit Data Files` button
- [x] All tests are passing
- [x] Test coverage exceeds 90%
- [ ] Create new issue for wiring stubbed endpoints to backend

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add `Button` component to upload page with text `Submit Data Files`
- [x] Create action, reducer, and state module for posting `uploaded` form to the back end
- [x] Create input wrapper validation component to only allow `.txt` and extension-less files to be uploaded to the file input
- [x] Upon submission, POST the files directly to the backend
- [x] Add stubbing layer for /reports backend endpoints
- [x] Add new tests where appropriate
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

- After discussion in the Mid-Sprint check-in, we decided to upload documents directly to the S3 bucket when the user uploads the file. This `Submit Data Files` button will submit the responses (with IDs) that we get back from S3 upon successfully uploading the document to the back end.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_
