### ISSUE TITLE
[Backend] Add endpoint for creating new file meta data

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#431]
## Description
Create an endpoint for uploading files. The frontend will send the file to the S3 bucket, but the endpoint created for this ticket will store the S3 data so the system knows where to retrieve the file

## Acceptance Criteria
- [x] `POST` Endpoint accepts a data package from the frontend with S3 data for the uploaded file
- [x] All tests are passing

## Tasks

- [x] Create Django App `reports`
- [x] Add fields to store file data to `reports` model (should include slug, fk to user, fk to stt
- [x] Add model class for reports logging (need to log updates to the file - date/time, operation (create or update) and fk to user and fk to report) (we can add file diff here later if/when that becomes a requirement)
- [x] Create `POST` endpoint to accept file data
  -  [x] Update `reports/views.py`
  - [x] Update `reports/serializers.py`
- [x] Create migrations for reports and logging
- [x] Add tests as needed

Note:
-   Log of file being uploaded and replaced is kept- file name, file type, when, who
- Files are not overwritten. We want flexibility to archive or serve different versions files later. 
- SC-28(01)

## Open questions
- [x] Will we be using an S3 bucket to store the files? **yes, this has been created**
- [x] Does cloud.gov support file storage?
   - Yes to both questions above, cloud.gov supports storage with S3 . https://developers.login.gov/faq/

**Comment by carltonsmith** [comment]
## Description
Create an endpoint for uploading files

## Acceptance Criteria
 - [ ] Endpoint accepts a single file
 - [ ] Input accepts only -.txt, .csv, or .xls file types
 - [ ] All tests are passing

## Tasks
- [ ] Add endpoint for uploading file
- [ ] Filter for .txt, .csv or .xls files
- [ ] Store file
- [ ] Add tests as needed

## Open questions
- [ ] Will we be using an S3 bucket to store the files?
- [ ] Does cloud.gov support file storage?
