### ISSUE TITLE
As a test user, I want to know permissions tied to my role

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#433]
**Description:**
For OFA MVP, there are two roles - test users acting as STT data preppers and OFA admins. This issue will deliver that will list permissions associated with a specific users role through command line interface (CLI). 

**Acceptance Criteria:** 

- [ ] Permissions defined in the mockup is same as the Django App 
- [ ] Security control documentation - AC-06 (#455) with screenshots using DAC is updated, if necessary

**Tasks:**

- [ ] @reitermb to provide permissions for both roles to @carltonsmith for configuring Django app
- [ ] Adding permissions to the system, as necessary
- [ ] Adding permissions to appropriate roles, as necessary
- [ ] Update Row 18 of [TDP FedRAMP Controls spreadsheet](https://teams.microsoft.com/l/file/14f87c6b-61ec-4c2d-a4b8-3d43c7427e38?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=xlsx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FATO%2FTDP-%20Selected-%20FedRAMP-Controls-MODERATE_CIS_20200916.xlsx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&messageId=1604681442523&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) is updated or docs folder is updated.

**Notes:**
- Row 18 in [TDP FedRAMP Controls spreadsheet](https://teams.microsoft.com/l/file/14f87c6b-61ec-4c2d-a4b8-3d43c7427e38?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=xlsx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FATO%2FTDP-%20Selected-%20FedRAMP-Controls-MODERATE_CIS_20200916.xlsx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&messageId=1604681442523&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) 
- 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
- Does using CLI meet the security control?
  - Yes. Document with screenshots.

**Comment by abottoms-coder** [comment]
@jtwillis92 We accomplished this on the welcome page, right? Closing ticket as done, please reopen if you feel I have missed the mark.
