### ISSUE TITLE
As a sys admin (dev), I want to assign and edit user roles through Django's admin control

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#442]
**Description:**
This issue will deliver assigning and editing user roles through Django admin console (DAC). 

**Acceptance Criteria:** 

- [ ] Demo of assign and edit user roles through DAC
- [ ] Update security control documentation for AC-02(07) (#455) and IA -04 security controls with screenshots using DAC) 

**Tasks:**
- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- #309 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
- Does assigning and edit user roles through CLI meet the AC-02(07) and IA -04 security controls? 
  - To meet the control, CLI screenshot + document how user roles will be assigned through CLI (describe screenshot, add narrative on how it addresses the security control, note that CLI would mimic UI - same commands/endpoints are being run etc).

**Comment by shubhi-raft** [comment]
dupe to #455
