### ISSUE TITLE
[Backend] Endpoint for summary list of roles and user counts

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#443]
## Description
OFA System Admins need high level information about the number of users in each role. This is issue will deliver number of roles and user counts.

## Acceptance Criteria
+ [ ] Endpoint exists that displays current list of roles and user counts assigned to each role
+ [ ] JSON returned matches shape of example below

**Example**
```
{
    "Superuser": 1,
    "OFA Admin": 1,
    "OFA Analyst": 1,
    "Data Prepper": 1,
}
```

Endpoint: `GET /api/v1/roles/summary/`

## Tasks
+ [ ] Test endpoint returns summary list
+ [ ] Test that only OFA Admins or Superusers can get the list of all users
+ [ ] Create endpoint to return summary list

**Comment by amilash** [comment]
we will revisit when we move django console into app ui

**Comment by lfrohlich** [comment]
@abottoms-coder  @ADPennington  is this covered by Django admin? Can we close?

**Comment by ADPennington** [comment]
> @abottoms-coder @ADPennington is this covered by Django admin? Can we close?

@lfrohlich no we do not yet have an endpoint with a count of users by permission group. Currently the roles endpoint will provide information about roles at the user level (screenshot below and endpoint details accessible [here](https://tdp-backend-staging.app.cloud.gov/swagger/)
![endptroles](https://user-images.githubusercontent.com/63075587/140178369-3b40f7d9-816f-40b0-aba5-4d6a2dc9978b.PNG)
)

I think this enhancement would be most useful when we real users. R2 assuming that release continues to be pretty lite.

**Comment by ADPennington** [comment]
@ADPennington will check with OCIO re: AU-2.

**Comment by robgendron** [comment]
Backlog Refinement, Alex deemed no longer needed.
