### ISSUE TITLE
[Frontend] Display list of roles with user counts

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#444]
## Description
OFA Admins need high level information about the number of users in each role. This is issue will deliver number of roles and user counts.

## Acceptance Criteria
+ [ ] The list indicates which how many users in each role
+ [ ] Follows design of first screen in UI #164 
+ [ ] Admin can view a summary list of roles and user accounts

## Tasks
 + [ ] Get list of users from endpoint and store in Redux Store
 + [ ] Total number of users by category
 + [ ] Add Add Role button
 + [ ] Create table using USWDS table component (https://designsystem.digital.gov/components/table/)

### Supporting Documentation:

![Screen Shot 2020-10-07 at 10.47.29 AM.png](https://images.zenhubusercontent.com/5f18d5aef8f52808880b2109/2287b48c-d410-4441-9d0d-4c085e4040ce)

**Comment by carltonsmith** [comment]
@hilvitzs please go ahead and task this out and estimate it when you get a minute. Not urgent at the moment.

**Comment by stevenino** [comment]
Closed as OBE per backlog refinement on 7/12/22
