### ISSUE TITLE
[Research] Document list of errors and warnings for grantees

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#449]
**Description:**
This issue will deliver a comprehensive list of errors and warnings for grantees for ~ Q2 2018 - Q22020. This list will be added to STT attributes spreadsheet and will be helpful in concept testing for future research. 

**Acceptance Criteria:** 

- [x] STT attributes spreadsheet is updated with the list of errors and warnings received from OFA
- [x] STT attributes spreadsheet contains a new sheet labeled "STT errors" that displays the most common errors and their descriptions for each STT.
- [x] Github repo has documentation on how this data was created and how it can be used for concept testing and future research. (This will be the start of a data glossary indicating what data sets have been captured and how they benefit research.)

**Tasks:**
- [x] Create a list of questions to understand what error data sets are possible to query.
- [x] Collaborate with OFA to pull reports that show fatal and warning errors by states, tribes and territories
- [x] Update the STT attributes spreadsheet to include the number of fatal and warning errors for each STT
- [x] Create a new sheet within STT attributes spreadsheet to display the 25 most common errors and 25 most frequent errors including their descriptions and severity.
- [x] Document how these comprehensive data sets were created and how they can be used for concept testing and future research.

**Deliverables:**
[Hack MD](https://hackmd.io/_PV7z3UAQmOPKbuFQ2BuOQ)
[STT Attributes Spreadsheet](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/doc2.aspx?sourcedoc=%7BF34F9CF0-70F3-46B4-A708-1764C5B3F4BC%7D&file=STTs%20Attributes%20(Current%20Version).xlsx&action=default&mobileredirect=true)
[STT Attribute Guide via hackmd.io](https://hackmd.io/_PV7z3UAQmOPKbuFQ2BuOQ#number-of-errors-discovered-from-tanf-reports-for-all-stts)
[STTs_Most Frequent Errors from the First Submission_Q3 2018 - Q2 2020](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7BE6487C87-E85B-47CA-9E37-50E68BA4BA99%7D&file=STTs_Most%20Frequent%20Errors%20from%20the%20First%20Submission_Q3%202018%20-%20Q2%202020.xlsx&action=default&mobileredirect=true)
[STTs_First and All Submission Errors_Q3 2018 - Q2 2020](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B4A62EF0A-65D5-47D9-AF88-E4495C33E9E7%7D&file=STTs_First%20and%20All%20Submission%20Errors_Q3%202018%20-%20Q2%202020.xlsx&action=default&mobileredirect=true)

**Open Questions:**
- Can we capture datasets that show errors found within the first submission only or are we limited to use datasets that combine all submissions/resubmissions?
  - Yes
- Will it be useful to include high level stats for each STT? @dk-ui 
  - Fatal and warning errors for each STT are numbers

**Comment by lfrohlich** [comment]
Made some comments in the hack.md. In general I encourage more attention to plain language, including active voice. 
Will the data glossary be only related to STT attributes or broader? Would be good to situate the markdown doc in a broader data glossary context.

**Comment by lfrohlich** [comment]
Is there a reason there isn't a column for All Submissions - Other errors in the STT attributes table?

**Comment by dk-ui** [comment]
@lfrohlich Really great comments in hack.md! The data set for "other errors for all submissions" was not apart of the original data set sadly and I didn't want to add more on Alex's plate right before Christmas. It is something we can capture in the future.

In sprint 11 @jenewingpierce and I are planning on correcting the plain language and active voice so I'll place this back to in-progress.

**Comment by dk-ui** [comment]
@shubhi-raft https://hackmd.io/_PV7z3UAQmOPKbuFQ2BuOQ ready for review

**Comment by lfrohlich** [comment]
The revisions look good, thanks! I think this is ready for PR to HHS main. Once that's in, we can close it out. @dk-ui @reitermb

**Comment by shubhi-raft** [comment]
@lfrohlich [PR](https://github.com/HHS/TANF-app/pull/126) has been created.

**Comment by lfrohlich** [comment]
Merged 1/12/21
