### ISSUE TITLE
(Internal) Retro 11/24 Commitments

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#451]
**Description:**
Document Retro action items/commitments from [11/24 Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1606238220126/8ed371ec064d3807602a8eea1789cfe294bc60e4) and create issues to address feedback.

**AC:**
- [ ] retro items action items have been documented and tasks have been completed

**Tasks for Sprint 9**
- [x] Miles to work on an async [workshop/generative tool on KPIs](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1609866324681/c9a02864edf8842af9356ed2653140758a5184d2) 🔒 
- [x] Carl to document plan for GitHub branching

**Supporting Documentation:**
(please include any relevant log snippets/ files/ screen shots here.)

**Open Questions:**

(any clarifying questions in support of the issue)

**Deliverables:**
- [PR](https://github.com/HHS/TANF-app/pull/102) for documenting branching  
-  [Roadmap KPI & Outcomes board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1609866324681/c9a02864edf8842af9356ed2653140758a5184d2) 🔒

**Comment by shubhi-raft** [comment]
Moving this to blocked until we have product management support onboarded.

**Comment by kniz-raft** [comment]
Will create another issue for KPIs and Outcomes for the next MVP separately
