### ISSUE TITLE
[Frontend] Add button to edit uploaded files

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#453]
**Description:**
Add `Edit Files` button to replace uploaded files to the All Reports post upload page (updated based on final #427)

**Acceptance Criteria:** 

- [ ] `Edit Files` button is added to the page (updated based on final #427)
- [ ] When `Edit Files` button is clicked, user follows flow documented in the [figma mockups](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2933%3A0)
~~- [ ] `Download Files` button is there but does not have any actions associated to it~~ 
- [ ] All tests pass (accessibility, linting, unit, integration)

**Tasks:**
- [ ] Implement a `GET` on the `Reports` page-load that checks to see if a report has been uploaded for that fiscal year
- [ ] Add `Edit Files` button to `Reports` page, if a report has been uploaded.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Refer to Sprint demo feedback #507 

**Supporting Documentation:**
_removed screenshot, refer to above Figma link for updated screens_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by carltonsmith** [comment]
@jenewingpierce @reitermb Do these ACs and mockups still match currently accepted designs?

**Comment by reitermb** [comment]
@carltonsmith These are out of date now—the new version deprecates any "Edit Files" button. In the new version when the user is looking at a given report they're also looking at the file picker components and can change files / upload missing ones and submit without clicking an edit button first.

We're still finalizing them this sprint but the core of the new flow and functionality is laid out [here](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=3588%3A800).
