### ISSUE TITLE
As a product owner, I want to document security controls for user roles and permissions

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#455]
**Description:**
This issue will deliver documenting security controls for  #309 and #442.

**Acceptance Criteria:** 

- [ ] PR is created to store documentation in docs folder with screenshots of Django Admin Control (DAC) for all of the controls noted in the Notes

**Tasks:**
- [x] Document security controls as provided in the notes
- [x] Share #309 security control in-progress documentation in the IPT on Dec 11 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Security controls to be documented 
  - AC-02
  - AC-02(07)
  - AC-05 #434
  - AC-06
  - IA-04

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by rnafarrete** [comment]
There is some details that need to be included/hashed out, but preliminary review of the information provide in the PR, I was able match the following controls:
- A user with built-in Django roles Staff and SuperUser is able to log in to the Django Admin Console (AC-2b, AC-6(2), AC-6(5), AC-6(10))
- In the Django Admin Console, all users' data can be updated including first_name, last_name, email and assigned roles (called Groups in the Django Admin) (AC-2c, AC-2d, AC-2f)
- Groups can be managed by updating permissions for each group (AC-2(7), AC-3(7), AC-5)
- All changes made in the Django Admin Console are logged and viewable within the console (AC-2(12), AC-6(9), AU-12)

**Comment by kniz-raft** [comment]
Closing this out and replacing with a different organizational method to track controls (each control group family has an epic and each control is an issue tied to the correct family epic)
