### ISSUE TITLE
(Internal) Define criteria for features to be acceptable for meeting the security controls using Django Admin Console for OFA MVP  

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#456]
**Description:**
This issue will deliver a criteria to determine when ~~command line interface (CLI)~~ Django admin console can be used to meet security controls in lieu of user interface (UI) for OFA MVP.  

**Acceptance Criteria:** 

- [x] Criteria to determine when ~~command line interface (CLI)~~ Django admin can be used to meet security controls in lieu of user interface (UI) is documented in docs
- [x] Acceptance criteria (AC) template with the criteria is drafted and documented in docs
- [x] Existing issues are updated with ~~CLI~~ DAC (Django Admin Console) tag and AC template
- [x] New issues are created, if necessary, and ~~CLI~~ DAC tag  and AC template is added

**Tasks:**

- [x] Breakout session to discuss where ~~CLI~~ DAC is enough and where UI is needed
- [x] Document and share with product team async ~~in standup~~
- [x] Issues are updated or new issues are created
- [x] Share with OCIO security our approach to document issues using ~~CLI~~  DAC

**Notes:**
 - AC template to include logging, scripts?, and documentation 

Deliverable(s):
- [PR](https://github.com/raft-tech/TANF-app/pull/483)

**Comment by shubhi-raft** [comment]
PR to merge the criteria in backend docs is waiting to be merged @carltonsmith.

**Comment by lfrohlich** [comment]
THis was merged into the Raft repo. Is the plan to open a PR for the HHS repo?

**Comment by shubhi-raft** [comment]
> THis was merged into the Raft repo. Is the plan to open a PR for the HHS repo?

Just created it - [PR](https://github.com/HHS/TANF-app/pull/127)

**Comment by kniz-raft** [comment]
PR was merged 1/15/2021
