### ISSUE TITLE
[Backend] Implement report file retrieval endpoint

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#485]
**Description:**

issue #431 Allows us to track file uploads and keep version histories, in order to access that data, there needs to be a new endpoint.

**Acceptance Criteria:** 

- [ ] There is an endpoint which will provide the most recent files for a report
- [ ] The endpoint requires authorization
- [ ] The endpoint has appropriate permissions
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add GET endpoint
- [ ] Run Testing Checklist and confirm all tests pass

**Note**

+ The frontend will require [#486](https://github.com/raft-tech/TANF-app/issues/486) to download the files from s3

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by riatzukiza** [comment]
I think this is a duplicate of the work for #431

**Comment by kniz-raft** [comment]
Reopening - was incorrectly marked as dupe and closed. Work is still needed.

**Comment by jtwillis92** [comment]
Closing this as we have shifted our download strategy such that we no longer use signed URLs. We will instead track the changes needed through https://github.com/raft-tech/TANF-app/issues/833
