### ISSUE TITLE
As a dev, I want to know how to store secrets and key variables locally so I can run the application

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#494]
**Description:**
There are some irregularities in how the `dotenv` implementation is working that causes some issues with new users getting the backend up and running. As a result, developers aren't sure how to handle secrets locally.

**Acceptance Criteria:** 
- [ ] Adopt standard `dotenv` implementation
- [ ] Remove `.env` files from source control
- [ ] Can launch backend with a local `.env` file populated with needed secret/key values
- [ ] Update documentation accordingly including README
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [ ] Add `.env` files to `.gitignore`
- [ ] Ensure that env variables are being set correctly regardless of deployment method 
- [ ] Remove `.env` files from source control (`git rm -r --cached .`)
- [ ] Add secret/key values to local `.env` file
- [ ] Run backend locally
- [ ] Troubleshoot any issues arising from the change
- [ ] Update backend README to reflect changes and help users run the backend locally
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by carltonsmith** [comment]
This is a duplicate issue - closing
