### ISSUE TITLE
As a new Tadpole, I want to see all of the information in docs so I can onboard easily 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#504]
**Description:**
This issue will deliver updating docs with all of our recent work and adding links as necessary. 

**Acceptance Criteria:** 

- [x] Tasks below have been completed

**Tasks:**

- [x] Add a note in Sprint Summary folder to clarify where to finds details on user stories that were completed in sprint 1-4
- [x] Review 'How we work' to ensure it reflects our current way of working 
- [x] Update product page with prioritization workshop and OFA MVP
- [x] Update team composition 
- [x] Add new file for Definition of Done pulling info from ['How we work'](https://github.com/HHS/TANF-app/blob/main/docs/How-We-Work/team-charter/manual-checks.md) and [manual checklist for QA QASP](https://github.com/HHS/TANF-app/blob/main/docs/How-We-Work/team-charter/manual-checks.md) 

**Notes:**
 - Issues for documenting research and design docs #501, #502, #503

**Comment by shubhi-raft** [comment]
@kniz-raft Added the definition of done task here.

**Comment by kniz-raft** [comment]
@lfrohlich I believe all the updated PRs have been merged - okay to close this one?

**Comment by lfrohlich** [comment]
This is done!
