### ISSUE TITLE
Sprint 11 Demo Feedback 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#507]
**Description:**
This issues documents all of the feedback we received during demo of sprint 11. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update TANF report mockup page to show 'Fiscal Year October 2020 - September 2021' 
- [ ] Evaluate whether dimension(s) that capture email communications / related aggregate values could be added to the STT attributes document and serve to better estimate the size of the eventual TDP userbase. 

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by amilash** [comment]
@lfrohlich this is old can we close it?
