### ISSUE TITLE
As a user, I want to know what architectural decisions were made

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#509]
**Description:**
This issue will deliver creating an architectural decision record (ADR) and documenting all of the architectural decisions thus far. 

**Acceptance Criteria:** 

- [x] ADR template is created and added to ADR folder in docs
- [x] ADR Folder is updated with S3 architectural decision
- [x] Dev issue template is updated to add updating ADR as an AC 

**Tasks:**

- [x] Create ADR folder in docs
- [x] Add ADR template 
- [x] Review system design document and align SDD with this docs folder
  - [x] Update ADR folder with S3 architecture details

#### Notes
- [System design document](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/SDLC/3_RAR_CDR_TRR/TDP_System%20Design%20Doc%20for%20CDR%201.14.21.docx?d=w56b21a41470a4082837f65d0a3274f75&csf=1&web=1&e=f4gGzi) - Section 2.1.2 (design decision) has some of this information. 

**Supporting Documentation:**
- [HeadStart's ADR template](https://github.com/HHS/Head-Start-TTADP/blob/ff2c81d8a5918595fc48d87dc551a985bf402224/docs/adr/template.md)
- [HeadStart's ADR Folder](https://github.com/HHS/Head-Start-TTADP/tree/ff2c81d8a5918595fc48d87dc551a985bf402224/docs/adr)

**Open Questions:**
- NA

**Comment by kniz-raft** [comment]
Submitted the last 2 from the SDD for review

**Comment by lfrohlich** [comment]
These were merged and can be found here: https://github.com/HHS/TANF-app/tree/main/docs/Architecture%20Decision%20Record
