### ISSUE TITLE
As a developer, I want a more coherent solution to handle environment variables

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#510]
**Description:**
Our current setup requires the developer to have environment variables loaded to their local system as well as leveraging a `dotenv` file. We would like to move to using `dotenv` only for all local environment variables and remove the reliance on `dotenv` from the deployment strategy to simplify setting up a local development environment.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] `dotenv` files are removed from the repositories with `.gitignore`
- [x] `dotenv` files are used locally for storing environment variables
- [x] Deployment strategy is updated to use another solution for handling environment variables
- [x] Testing Checklist has been run and all tests pass

**Tasks:**

- [x] Add `dotenv` files to `.gitignore`
- [x] Update local `dotenv` files with all environment variables
- [x] Update deployment strategy to load environment variables
- [x] Run Testing Checklist and confirm all tests pass

**Comment by alexsoble** [comment]
Met with Carl, John, Kati to discuss how to move forward on this issue. 

* Close out the frontend PR for now: https://github.com/HHS/TANF-app/pull/166
* Concentrate work on shipping the backend PR: https://github.com/HHS/TANF-app/pull/167
* Use a `docker-compose.local.yml` rather than a `docker-compose.override.yml` on the backend
* Change our approach to the frontend work since there are no secrets on the frontend

**Comment by alexsoble** [comment]
Great progress on the backend PR today! 

https://github.com/HHS/TANF-app/pull/167#issuecomment-776946306

**Comment by alexsoble** [comment]
Talking over the frontend side of 510 with devs in Dev Sync.

Right now we think that the only changes needed to satisfy 510 on the front end *might* just be documentation changes:

* Document how ENV variables are set locally on the frontend, what is the order of operations/precedence for ENV variables?
* Document how to adjust ENV variables locally on the frontend

**Comment by lfrohlich** [comment]
Backend was merged 2/10

**Comment by lfrohlich** [comment]
Frontend merged 2/25
