### ISSUE TITLE
Add Privacy Policy link to website

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#511]
**Description:**
The Privacy Impact Assessment requires a privacy policy to be included on the website since it is public facing. This is a requirement of the E-Government Act and OMB Memoranda. The ACF provides a privacy policy that we can use for this purpose: https://www.acf.hhs.gov/privacy-policy

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] A link is present on "All known major entry points (regardless of whether PII is collected)" of the website
- [ ] The link directs the user to https://www.acf.hhs.gov/privacy-policy in a new tab
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Conversation w/ UX to see how the privacy link can be added to footer (default to USWDS styling)
- [x] Add Privacy Policy link as a Primary Link item as shown in[ USWDS specification](https://designsystem.digital.gov/components/footer/)
- [x] Run accessibility testing checklist and confirm all tests pass

Notes:
- Example of the OFA footer with privacy policy included - https://www.acf.hhs.gov/ofa

**Comment by reitermb** [comment]
Updated with a nod to the USWDS component

**Comment by kniz-raft** [comment]
Makes sense to do this one with #704 if possible

**Comment by lfrohlich** [comment]
This was merged 4/2
