### ISSUE TITLE
(Internal) Add disclaimer notice when sites are not owned or operated by government

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#512]
**Description:**
As a requirement of the Privacy Impact Analysis, an individual needs to see an alert which says they are moving from a website which is controlled by the federal government to a website when is not controlled by the federal government every time they click one of those links.

**Acceptance Criteria:** 
- [ ] Users see disclaimer whenever the navigate to a non-gov't website
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
- [ ] Create disclaimer
- [ ] Evaluate whether this can be included in the content / style guide checklist
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
The alert could be a statement, appearing adjacent to the link or a pop-up, which says that viewers are being directed to a website which is not controlled by the federal government and may have different privacy policies from those of the agency’s official website.

Sample alert language:

> This hyperlink will direct you to a non-governmental website or application. The appearance of external hyperlinks does not constitute an
> endorsement by the United States Department of Health & Human Services (HHS) of the hyperlinked website or application, or the information, products, or services contained therein. Visitors to the hyperlinked website or application will be subject to that website or application’s privacy policies. These practices may be different than those of this HHS website

**Comment by kniz-raft** [comment]
@hursey013 Do you know of any links that we currently have that fall into this criteria?

**Comment by hursey013** [comment]
I don't believe we have any at the moment.

**Comment by valcollignon** [comment]
Discussed during 11.23.21 backlog refinement. Is this still a priority? Can we close this ticket? See comments above. @lfrohlich 
CC: @ADPennington

**Comment by stevenino** [comment]
Closed as OBE per backlog refinement on 7/12/22
