### ISSUE TITLE
[Frontend] Add STT ComboBox for OFA Admin Selection

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#530]
**Description**
OFA Admin users need an STT ComboBox to select the STT they would like to upload for

**Acceptance Criteria**
- [ ] ComboBox allows OFA Admin users to select STT
- [ ] Users without OFA Admin role do not see the ComboBox

**Tasks**
- [x] UX to update mockups to match decision to use combobox (from dev/design pairing) — [Updated Figma page](hhttps://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4124%3A0)
- [x] Build STT combobox component abstraction
- [x] Replace combobox on Edit Profile page with updated component
- [x] Add checks for user roles
- [x] Hide for users without `OFA Admin` role
- [x] Add combobox to reports page
- [x] Update payload to use combobox selected STT for the `stt` field for `OFA Admin` users, and the user's STT for other users

**Comment by shubhi-raft** [comment]
@reitermb to task it out for UX.

**Comment by jenewingpierce** [comment]
Who is responsible for testing the AC on this ticket @kniz-raft ?

**Comment by carltonsmith** [comment]
> Who is responsible for testing the AC on this ticket @kniz-raft ?

@jenewingpierce it depends on the stage
Raft Review: Me (Carl)
QASP Review: Alex and Lauren

**Comment by jenewingpierce** [comment]
@carltonsmith okay, thanks! don't hesitate to reach out if I can help with testing.

**Comment by kniz-raft** [comment]
@carltonsmith to pair with @jorgegonzalez  on building out tasks and evil user scenarios
