### ISSUE TITLE
As an ST user, I want to be invited to participate in research (round 4)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#540]
**Description:**
For round 4 of user research, plan, recruit and schedule ST (no tribes) workshop for Round 4.

**AC:** 
- [x] 5-9 STTs have been contacted (ccing RO contacts) to schedule workshop for Round 4. 
- [x] Email template from #170 is updated and followed followed

**Tasks:** 

- [x] Send out screener emails asking for STT volunteers
- [x] Confirm STT workshop
- [x] Schedule workshop for 02/12/21

Deliverable:
STT contact sheet with confirmed users for workshop: 

**DoD:**
- [x] Interviewees have been contacted to schedule workshop
- [x] Team knows when workshop is happening. 

**Deliverables**
Email for STT Participation ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B7113048B-3AA7-43DF-8AA8-B2B44A1B92FD%7D&file=Participant%20Email%20Templates.docx&action=default&mobileredirect=true))

**Resources**
#228 Email for STT Participation: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B645fcfdc-c65d-474a-9c57-d51f3c68ac96%7D&action=view))
Interview Logistics: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/doc2.aspx?sourcedoc=%7B0333313B-0F88-406B-B894-07687D32921B%7D&file=%23170%20STT%20Interview%20Protocol%20DRAFT.docx&action=default&mobileredirect=true))

**Comment by dk-ui** [comment]
@lfrohlich Email for reaching out to regional offices and STTS are updated in this link. Can you review before we begin contact. 

https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/Doc.aspx?sourcedoc=%7B7113048B-3AA7-43DF-8AA8-B2B44A1B92FD%7D&file=Participant%20Email%20Templates.docx&action=default&mobileredirect=true

**Comment by kniz-raft** [comment]
@dk-ui Is this ready to be moved into QASP review?

**Comment by dk-ui** [comment]
@kniz-raft Not yet, so far we have only gotten 4 contacts from the regional offices. I'll send a follow-up email tomorrow if they have still not gotten back to me.

**Comment by kniz-raft** [comment]
Blocked by waiting for regional offices

**Comment by jenewingpierce** [comment]
@dk-ui can you post updates here? Thanks.

**Comment by jenewingpierce** [comment]
@dk-ui I think this is all done, yes?

**Comment by dk-ui** [comment]
@jenewingpierce All set for review

**Comment by jenewingpierce** [comment]
@dk-ui thanks!

Have reviews been sent?

**Comment by shubhi-raft** [comment]
@lfrohlich this can be closed. STs were invited and participated in the ST workshop on Feb 12.

**Comment by lfrohlich** [comment]
Workshop happened 2/12
