### ISSUE TITLE
As a frontend developer, I want fast local builds with no unused packages installed

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#548]
**Description:**
While building this project locally there seems to be a slow down during the `yarn install` step of the docker build for the frontend. (Took 600 seconds on just the yarn step on @alexsoble's machine).

Running the [depcheck](https://www.npmjs.com/package/depcheck) utility in the project reveals the following:
```
Unused dependencies
* axios-cookiejar-support
* node-sass
* oidc-client
* redux-oidc
* typescript
* eslint-config-react-app
Unused devDependencies
* @testing-library/dom
* @testing-library/user-event
* @types/classnames
* http-get
* jsdoc
* node-sass
* start-server-and-test
* wait-on
Missing dependencies
* theme: ./src/index.scss
* media: ./src/assets/GovBanner.scss
* screen: ./src/assets/SplashPage.scss
```

It's possible that these unused packages contribute to the time the build process takes so that seems like a good starting point for improving build times.

Additionally, having unused packages contributes to more work for PR reviewers without any additional gains. Since Snyk is enabled on this repo to automatically keep packages up to date it will attempt to keep these unused packages up to date as well. This is shown in [this PR](https://github.com/raft-tech/TANF-app/pull/690) that went through the review process even though the package `oidc-client` is shown above as unused in the project.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Builds should be faster
- [ ] No unused dependencies should be installed in the project
- [ ] No unmet peer dependency warnings should be introduced during local builds
- [x] The yarn cache should be leveraged for local builds only
- [ ] Apart from removing unused packages, this should not change the build process for deployed environments.

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Remove unused packages
- [ ] Investigate other ways to speed up builds

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Are any of these unused dependencies planned for use?

**Comment by jtwillis92** [comment]
@jorgegonzalez when running with your modified Dockerfile.local for #691 have you noticed an improvement in local build times?

**Comment by jorgegonzalez** [comment]
I have not noticed improved local build times with my personal `Dockerfile.local`.

I think the `yarn cache clean` looks suspicious in the step `RUN yarn install && yarn cache clean` though I haven't tried without it yet.

**Comment by jtwillis92** [comment]
I agree @jorgegonzalez, it seems unnecessary to clear the cache after each install on local builds.

**Comment by jtwillis92** [comment]
As discovered by @jorgegonzalez in https://github.com/raft-tech/TANF-app/pull/734#issuecomment-790680745 we also don't need the packages `typescript` and `eslint-config-react-app`. We should also remove these packages as part of this work - since typescript in particular has a large footprint on app builds.
