### ISSUE TITLE
Retro Items for Sprint 13

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#554]
**Description:**
Document Retro action items/commitments from [01/19 Mural](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1610724955587/275a4416e4486f6d96afae81937d16890e09643e) and create issues to address feedback.

**AC:**
- [ ] retro items action items have been documented and tasks have been completed

**Tasks for Sprint 13**
- [x] Keep PRs small (app dev) but meaningful
- [x] Lauren/Jen/Kati connect on the research plan and communicate an update to the team
- [x] A few modifications to standups (Kati to document)
-  _Pairing for code reviews (Carl/Spencer/Miles)_ Ongoing process
- [x] Jen to ask for feedback on documents in teams (Jen)
~~Staging environment (Alex)~~ Carrying over to Sprint 14
- [x] Topic for tech sync: how to structure PRs (Carl)
- [x] More structure around OCIO/Security Control Documentation Plan (Kati/Romelo)

**Supporting Documentation:**
(please include any relevant log snippets/ files/ screen shots here.)

**Comment by kniz-raft** [comment]
Updated with where we were at finishing up Sprint 13.
