### ISSUE TITLE
As a developer, I no longer need to use the python-dotenv package

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#555]
**Description:**
With the changes to our deployment and local dev strategy we no longer need the `python-dotenv` package installed on the backend, so it should be removed.

**Acceptance Criteria:** 
- [ ] Application no longer loads the `python-dotenv` library
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] update pipfile with current library versions
- [ ] remove library
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- We've run into some issues attempting this, so it might be a little more effort than otherwise expected

**Comment by jtwillis92** [comment]
Also as a note, we are currently using `*` for the version number on most of the packages defined in the `Pipfile`. This is a particularly dangerous footgun, as it can lead to packages being updated unexpectedly and introduce breaking changes without our explicit awareness. It can also lead to dependency conflicts, which I believe contributes to this issue directly - as I ran into dependency conflicts trying to remove `python-dotenv` and re-lock the Pipfile.

For example, this application is currently compatible with pyjwt 1.7.1, but if a new `requirements.txt` file is generated from the current Pipfile then pyjwt will upgrade to v 2.0.1, which includes breaking changes related to return values from functions that we use in the project. Instead I'd suggest that we pin all packages to the specific versions that everything is currently working on and then upgrade packages individually as needed to get new features or security fixes.

**Comment by abottoms-coder** [comment]
@jtwillis92 Closing this as dupe. I recall you saying this was already done.
