### ISSUE TITLE
As a developer, I want API docs to be automatically generated in OpenAPI format

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#564]
**Description:**
Currently API documentation is manually written in markdown files. To speed up the development cycle we can put a solution in place to automatically generate API documentation using code annotations or view structure. These documents must meet OpenAPI standards and have the ability to be served over HTML in a browser.

**Acceptance Criteria:** 
- [x] API documentation must be automatically generated for all exposed endpoints
- [x] Documentation must meet OpenAPI standards
- [x] Generated documentation must be convertable to HTML format so that it can be served in a browser
- [x] Testing Checklist has been run and all tests pass

**Tasks:**
- [x] Implement solution to automatically generate API documentation
- [ ] Add any necessary code annotations or comments to all viewsets that will be documented as required by the implemented solution
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
- [Swagger](https://swagger.io/solutions/api-documentation/) is a potential solution

**Supporting Documentation:**

**Open Questions:**

**Comment by jtwillis92** [comment]
@omnipresent07 @carltonsmith do we want these API docs to be authenticated or open to the public?

**Comment by jtwillis92** [comment]
This library integrates with Django Rest Framework and will help make this generation automatic: https://drf-yasg2.readthedocs.io/en/stable/openapi.html

**Comment by carltonsmith** [comment]
@kniz-raft This will save a good amount of time in backend work and creates pretty great docs. Can we get this prioritized to discuss with OFA?
