### ISSUE TITLE
[SPIKE] As an OFA Employee, I would like to know how to run the application on my government Windows machine

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#600]
**Description:**
As an OFA Employee, I would like to know how to run the application on my government Windows machine.

Thomas brought up that the current instructions/links involve running the app in the Macintosh environment, but OFA Employees run Windows PCs, and he thought it would be useful if we could include instructions on how to run it in Windows.

**Timebox** 8hrs

**Acceptance Criteria:** 

- [ ] Update READMEs to include instructions on how to run in Windows
- [ ] Include links for Docker for Windows alongside current links to Docker for Mac

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Figure out how to run the app in Windows
- [ ] Document any difficulties/problems and how to overcome them
- [ ] Update docs to meet AC
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- Since I do my programming in a Mac, I haven't tried to do this before so I'm not sure how difficult it will be. I set the timebox to 8 hours for this reason. That said, in theory it should work just fine, so it may not take this much time.

**Comment by amilash** [comment]
@lfrohlich Does Thomas still need this info?

**Comment by lfrohlich** [comment]
@ADPennington  @abottoms-coder ?

**Comment by ADPennington** [comment]
can close @lfrohlich
