### ISSUE TITLE
Add GET endpoint that lists active users

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#624]
**Description:**

For the frontend to display a list of active users, it has to retrieve it from the backend. There should be little model work to be done for this ticket, as there is already an `is_active` field on users, and we just have to filter according to that.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] A route is added for the new view
- [ ] There is a test confirming the route is functional
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add a new view/view method to user/views.py
- [ ] Add integration tests for new view confirming behavior
- [ ] Add documentation for new endpoint
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

This will be very similar to another issue for 396 for creating a list view for all unactive users.
it may make sense to treat them as one issue.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Should there be a single view with a param for active/inactive users, and other similar such queries?

**Comment by amilash** [comment]
@abottoms-coder I think our django admin console makes this moot and I can close. Yes?
