### ISSUE TITLE
Create a user research plan for STTs for Aug-Sept 2020

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#63]
**Description:**
Create a draft user research plan to conduct next round of research (August - September 2020) with STTs.  Interview guide will be a next step. This will be reviewed after #228 is done. 

**AC:** 

- [x] Research plan is drafted and includes or links to: 
- #266 User research goals 
- #277 Expected outcomes
- #163 & #269 Recruitment criteria
- #228 Methods, ethics, email template
- #115 & #275 Conceptual mockups

**Tasks:** 

- [x] Synthesize OFA research #113
- [x] Create a draft research plan that addresses epics - Users can easily upload data and User can view uploads
- [x] List research goals
- [x] Determine method(s)
- [x] Develop recruitment criteria
- [x] Document ethics, privacy concerns
- [x] Draft expected outcome
- [x] Create email language template
- [x] Draft timeline

**DoD:** 

 - [x] Documentation: Draft research plan has been shared with the PO and team for feedback
 - [x] @cmajel has reviewed and signed off
 - [ ] @lfrohlich has reviewed and signed off
 

**Deliverables**

Research Plan: ([Link](https://hhsgov.sharepoint.com/:w:/r/sites/TANFDataPortalOFA-UserResearch/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B2e300237-f645-4446-b191-a9ee509026ef%7D&action=view))

**Comment by cmajel** [comment]
Recapping conversation from sprint planning. Some of the things that may inform what is covered in this STT research plan includes:
* What's coming up on the roadmap
* What we need to know to build a journey map / think about future task flows #165 
* What we want to dig into more after OFA synthesis is completed #110

**Comment by cmajel** [comment]
@matthewjdoty Thinking about this more, a key thing we should figure out is what we need from our MVP and how to best use this time with STTs. An essential part of making a useful MVP and unblocking STTs is them being able to upload new data, so digging in and testing that early concept could be helpful.

Also, wanted to note we have [this process map](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1593114727729/906879aaeb5467c27f0ae3dfbcf5fcfd9cf8ca89) from prior rounds of research (password sent in Teams) that reflects what the process looks like now. Might be helpful to review as we think about a future state.

**Comment by matthewjdoty** [comment]
@cmajel, YES this is on our radar as a potential item to include in our conversations with STT's. I'd love to see the research that led to the process map. Can you point me in the right direction?

**Comment by cmajel** [comment]
Yes! [Here's the readout on the wiki](https://github.com/HHS/TANF-app/wiki/2020,-Spring:-Understanding-the-local-experience) from the last round of research in Spring 2020, and [here's the synthesis mural](https://app.mural.co/t/officeoffamilyassistance2744/m/gsa6/1588017905984/5b76f21dd4e393392b549330c8f96133f821a06e) from that round of research.

**Comment by matthewjdoty** [comment]
added "Synthesize OFA research #113" to the list of tasks

**Comment by cmajel** [comment]
@matthewjdoty @dk-ui @reitermb, wanted to share a few resources that we used to develop the ACs here and what we used to review the last research plan. We've shared them in slack before and in the [user research guide on the wiki](https://github.com/HHS/TANF-app/wiki/User-research-guide), but sharing them here as well.

Templates / heuristics we've worked from before

- [18F UX Guide, Sample research plan](https://github.com/18F/ux-guide/blob/master/_pages/resources/research-plan.md)
- [18F UX Guide, Sample interview script](https://github.com/18F/ux-guide/blob/master/_pages/resources/interview-guide.md)
- [18F UX Guide, Usability test heuristics](https://github.com/18F/ux-guide/blob/master/_pages/resources/usability-test-quality.md)

Resources for writing good interview questions
* [Canadian Digital Service, A guide to research interviewing](https://digital.canada.ca/tools-and-resources/guide-interviewing/)
* [18F, Build empathy with stakeholder interviews, part 1: Preparation](https://18f.gsa.gov/2016/06/20/build-empathy-with-stakeholder-interviews-part-1-preparation/)

**Comment by matthewjdoty** [comment]
@reitermb will review today

**Comment by cmajel** [comment]
Recapping the comments from stand up, we should make sure we're all on the same page for research objectives for this next round before we get into details like which STTs to contact. This can help make sure we're not duplicating past work, that we're learning new things that help advance the roadmap, and can help inform what we may need to design in terms of concept testing (which is coming up).

Can you all share the draft research objectives that have been amongst Raft? It seems like there's a lot riding on this ticket for the next sprint, so making sure Raft and OFA are aligned will make the next sprint go smoother.

**Comment by shubhi-raft** [comment]
breaking this down into smaller stories: 

user research goals - #226
expected outcomes - #227
recruitment criteria - #163
methods, ethics, and email template - #228

**Comment by matthewjdoty** [comment]
@shubhi-raft I've made comments and tracked the changes I've made. Feel free to review

**Comment by shubhi-raft** [comment]
@dk-ui @reitermb moving this back to in progress to address feedback  

cc @matthewjdoty

**Comment by cmajel** [comment]
@reitermb @dk-ui @matthewjdoty 

👍 looks good. I added a few questions about the timeline and if some things could be done concurrently. I'm good signing off on this.

**Comment by lfrohlich** [comment]
@matthewjdoty  @shubhi-raft the only outstanding things here are a few question Christine had about the timeline. Is it possible that some of those activities could be done concurrently? If so, please update and comment here. Thanks!

**Comment by matthewjdoty** [comment]
Thanks, @lfrohlich! Responses added to the document.

**Comment by lfrohlich** [comment]
Thanks, @matthewjdoty ! CLosing this out
