### ISSUE TITLE
As a compliance person I would like to limit our boundary by eliminating DockerHub

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#635]
**Description:**
DockerHub is currently used as part of the deploy process to push Docker images of the frontend and backend. The images are then immediately pulled back from DockerHub and used for the deployment. This could potentially expand our security boundary to include DockerHub since code it is an integral part of our deployment process, stores copies of our code, and opens up another avenue for accidentally exposing secrets.

Rather than using DockerHub, it may be possible to use CircleCI alone to build the Docker image for use in the deployment.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] DockerHub footprint is removed from codebase
- [ ] DockerHub account is decommissioned 
- [ ] CircleCI deploys continue to work as expected

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Modify deploy scripts to eliminate DockerHub
- [ ] Remove any env vars, code, or documentation related to DockerHub
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Is this possible with CircleCI alone?

**Comment by hursey013** [comment]
Based on further research, it is not possible to use Cloud.gov Docker deploys without a Docker Registry (DockerHub).

From "Deploying an App with Docker :: Requirements": 

> The location of the Docker image on Docker Hub or another Docker registry.
> A registry that supports the Docker Registry HTTP API V2 and presents a valid certificate for HTTPS traffic. For more information, see the Docker Registry HTTP API V2 spec in the Docker documentation.

https://docs.cloudfoundry.org/devguide/deploy-apps/push-docker.html#requirements

**Comment by lfrohlich** [comment]
This is a duplicate
