### ISSUE TITLE
As a compliance person I would like to increase our security posture by using Cloud.gov buildpacks

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#636]
**Description:**
Right now we are using Docker images to deploy to Cloud.gov. While this works as expected and helps to create consistency with local envs, it does shift hardening Docker and taking on the responsibility of maintaining the container's stack to our team and also increases compliance work. By using Cloud.gov buildpacks we would be able to inherit automatic and continuous security updates and bug fixes as well as removing the dependency on DockerHub.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Deploy scripts use Cloud.gov buildpacks
- [ ] DockerHub dependency is remove from deploy scripts
- [ ] DockerHub account is decommissioned
- [ ] Local envs still support using Docker
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update build scripts to use Cloud.gov buildpacks and remove DockerHub
- [ ] Ensure local environments can still use Docker
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://cloud.gov/docs/getting-started/concepts/#buildpacks
- https://docs.cloudfoundry.org/buildpacks/
- https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html
- https://www.suse.com/c/cloud-foundry-builpacks-dockerfiles/

**Comment by lfrohlich** [comment]
As part of investigation, document with ADR

**Comment by kniz-raft** [comment]
As part of a spike, we will be breaking up the work into several tickets (#738 is the first) so this big ticket will no longer be needed. I'm leaving it open until we get those tickets created but then it will be closed.

**Comment by kniz-raft** [comment]
All smaller tickets have been created and are included in epic #783. Closing this one.
