### ISSUE TITLE
[backend] Endpoint for retrieving a list of years reports are available

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#643]
**Description:**

Frontend needs a way of knowing for which years reports are available to know whether or not to render an "Upload new report button", or present the option to "edit files" or "download them.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_
- [x] There is an endpoint which when gotten, provides a list of years for which there are reports for the given stt
- [x] This endpoint is available to data preppers for their own stt
- [x] This endpoint is available for OFA admin for all STT
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add an endpoint to get all years for which there are reports for a given STT
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
