### ISSUE TITLE
[SPIKE] Investigate Pros/Cons of using Cloud.gov buildpacks or AWS alternative for deployments to Cloud.gov

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#645]
**Description:**
Right now we are using Docker images to deploy to Cloud.gov. While this works as expected and helps to create consistency with local envs, it does shift hardening Docker and taking on the responsibility of maintaining the container's stack to our team and also increases compliance work. By using Cloud.gov buildpacks we would be able to inherit automatic and continuous security updates and bug fixes as well as removing the dependency on DockerHub.

Timebox: 8 hours

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Create an ADR documenting the decision to use Docker + Docker Registry (DockerHub) or Cloud.gov buildpacks 
- [x] Create user stories (and epic if needed) to complete the work
- [ ] Communicate potential impact on implementation

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Investigate steps needed to convert to using buildpacks
- [x] Determine impact on local development
- [x] Determine LOE to complete transition
- [x] Follow ADR process to document decision

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- https://cloud.gov/docs/getting-started/concepts/#buildpacks
- https://docs.cloudfoundry.org/buildpacks/
- https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html
- https://www.suse.com/c/cloud-foundry-builpacks-dockerfiles/
- https://cloud.gov/docs/technology/responsibilities/
- #635 can be referenced/reused if needed

**Comment by riatzukiza** [comment]
Is there something blocking this right now? Its been here for a while, and I believe the ADR for this was accepted quite some time ago.

We have had issues for it since monday of last week.

**Comment by jtwillis92** [comment]
No, I believe this one is good to be closed.
