### ISSUE TITLE
[backend] As a developer, I would like to automatically fix simple linting issues.

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#654]
**Description:**

We use a tool called `flake8` to check our python code for lint. We have instructions to use `black` to simple issues.
Currently, black does not totally agree with our configuration of flake8.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] There is a command documented in the README for the backend than when ran, automaticly fixes linting issues with out adding new ones.
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by valcollignon** [comment]
Closing per backlog refinement 12.21.21. OK to close per @ADPennington.
