### ISSUE TITLE
As a developer, I want to have automated a11y frontend tests successfully ran as part of the CI/CD

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#659]
**Description:**
The Pa11y tests being ran as part of our CI/CD test flow are currently not working as expected, returning an `Unhandled promise rejection` rather than successfully running through the testing process.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Automated a11y test runs during CI/CD without errors (specifically related to Pa11y itself)
- [ ] A proper exit code is provided in order for CircleCI to determine if the step should be pass/fail

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Determine the root cause of the `Unhandled promise rejection`
- [ ] Address root cause
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
- Example: https://app.circleci.com/pipelines/github/HHS/TANF-app/422/workflows/612b1ca2-f51c-4f5e-b701-d644b9bfaa76/jobs/799/parallel-runs/0/steps/0-107

**Supporting Documentation:**
```
cd tdrs-frontend; yarn test:accessibility
yarn run v1.22.4
$ concurrently -k -s first 'yarn start:ci' 'wait-on http://localhost:3000/' && yarn pa11y-ci --config .pa11yci.json
[0] $ CI=true HOST=localhost BROWSER=none yarn react-scripts start
[0] $ /root/tdp-apps/tdrs-frontend/node_modules/.bin/react-scripts start
[0] Attempting to bind to HOST environment variable: localhost
[0] If this was unintentional, check that you haven't mistakenly set it in your shell.
[0] Learn more here: https://cra.link/advanced-config
[0] 
[0] ℹ ｢wds｣: Project is running at http://localhost:3000/
[0] ℹ ｢wds｣: webpack output is served from 
[0] ℹ ｢wds｣: Content not from webpack is served from /root/tdp-apps/tdrs-frontend/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0] 
[0] Compiled successfully!
[0] 
[0] You can now view tdrs-frontend in the browser.
[0] 
[0]   http://localhost:3000
[0] 
[0] Note that the development build is not optimized.
[0] To create a production build, use yarn build.
[0] 
[1] wait-on http://localhost:3000/ exited with code 0
--> Sending SIGTERM to other processes..
[0] yarn start:ci exited with code SIGTERM
$ /root/tdp-apps/tdrs-frontend/node_modules/.bin/pa11y-ci --config .pa11yci.json
(node:298) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0208/161303.689666:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/tdp-apps/tdrs-frontend/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/root/tdp-apps/tdrs-frontend/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 27.11s.
CircleCI received exit code 0
```

**Comment by jtwillis92** [comment]
@valcollignon @abottoms-coder @ADPennington we've had this for awhile - this one could be closed.

**Comment by valcollignon** [comment]
+ @lfrohlich

**Comment by valcollignon** [comment]
Closing per backlog refinement 12.21.21. This is functioning now; pa11y tests are running properly. OK to close per @ADPennington.
