### ISSUE TITLE
[Backend] Add created at to endpoint for creating file

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#670]
**Description:**
The frontend needs a created at date to be a part of the frontend upload

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `created_at` is a part of a successful upload respoonse
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add created at to `ReportFileSerializer`
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by jtwillis92** [comment]
This was completed with https://github.com/raft-tech/TANF-app/pull/623
