### ISSUE TITLE
[frontend] As a developer, I would like the app to hot reload when running locally.

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#691]
**Description:**

We currently use `docker` and `docker-compose` to build and run the app; the `Dockerfile.local` that describes this process for the frontend is nearly identical to the `Dockerfile.dev` for higher environments. Thus locally, we end up having to build a production bundle for the frontend and serve it with `nginx`.

We should instead be using `yarn start` for local development, which automatically adds support for hot reloading, alleviates the need to rebuild the container when you want to see changes, and negates the need for `ngnix` as it runs a development server. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `docker-compose up` should serve the app at `http://localhost:3000` as before (this should not have changed)
- [ ] Local frontend code changes should trigger a hot reload
- [ ] Changes should be visible in UI after reload
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Remove `nginx` references from `Dockerfile.local`
- [x] Update `Dockerfile.local` to run `yarn start` instead of `yarn build`
- [x] Run the frontend with the new Dockerfile: `docker-compose up -d`
- [x] Make any arbitrary changes to visible UI code on the frontend
- [x] Ensure frontend reloads with new changes
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Make sure this can be demoed for Alex P/Lauren for sign off_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by jtwillis92** [comment]
+1 this would be a great improvement to the local dev experience and get us more in line with how CRA is meant to be used
