### ISSUE TITLE
Upgrade react-idle-timer

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#716]
**Description:**
The latest version of `react-idle-timer` is 4.5.5 and we are currently running 4.5.0

**Acceptance Criteria:** 

- [ ] `react-idle-timer` is upgraded to version 4.5.5
- [ ] Site, especially the functions that use the timer, works the same way
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- Are any code changes required, other than upgrading the timer?

**Comment by carltonsmith** [comment]
@jorgegonzalez Please update the tasks on this issue and assign story points. Wait until we move it into a sprint to do the work, though.

**Comment by valcollignon** [comment]
This can be closed as dependabot manages these updates. This ticket is outdated. Per @jorgegonzalez during backlog refinement 12.21.21.
OK to close per @ADPennington.
