### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#721]
## Context

See [Architecture Decision Record 14, Deployment Strategy Change](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Architecture%20Decision%20Record/014-deploy-strategy.md) for the latest deployment flow.

### Deploying the production site

+ [x] Create cloud.gov production space (Alex P)
+ [x] #726
+ [x] #914
+ [x] #895 +  setting correct `PROD` ENV variables on frontend/backend Cloud.gov apps + HHS CircleCI project settings (Alex P) 
+ [x] #1627
+ [x] #1628
+ [x] #897
+ [x] Update ATO docs [#1422]

#### Notes
- What is the timing of this? Things to consider? 
 -- There is code work that can be done before making this live
 -- We could build this out but not have it be live until we have a domain name

**Comment by ADPennington** [comment]
can this be closed @alexsoble?

**Comment by alexsoble** [comment]
See https://github.com/raft-tech/TANF-app/issues/723#issuecomment-822477180

**Comment by ADPennington** [comment]
Agree with @alexsoble that we should recycle these issues and use for setting up for prod!

**Comment by alexsoble** [comment]
@ADPennington Recycled this into a ticket for setting up the prod space, and simplified (a lot!)

**Comment by amilash** [comment]
@jtwillis92 @abottoms-coder Alex wants to start having this conversation tech sync this week.

**Comment by valcollignon** [comment]
Would like to discuss in next backlog refinement, if we have time.

**Comment by stevenino** [comment]
@ADPennington Can we close this epic?
