### ISSUE TITLE
As a dev/PO, I want to be able to visit a deployed gov staging site 

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#723]
## Context

For more information about the Gov Staging site and why we have one in our deployment flow, see [Architecture Decision Record #8, Deployment Flow](https://github.com/HHS/TANF-app/blob/main/docs/Architecture%20Decision%20Record/008-deployment-flow.md).

This is part of the Epic, "As a developer/PO, I want to have a gov staging site": https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/721

## Tasks

_These would be great tasks for @carltonsmith, @ADPennington, @alexsoble to pair on:_

+ [ ] Set up Gov Staging frontend/backend apps in the Staging Space on Cloud.gov. _Open question: @jtwillis92, would we want to use this as an opportunity to split the "new site setup" script from the "deploy new code" script?_
+ [ ] Set up new app for Gov Staging in the Login.gov dashboard.
+ [ ] Set correct ENV variables on frontend/backend Cloud.gov apps.

**Comment by ADPennington** [comment]
@kniz-raft @alexsoble can this be closed per this [comment](https://github.com/raft-tech/TANF-app/pull/823#issuecomment-816890781)?

**Comment by alexsoble** [comment]
We could either close, or just change this Epic from "set up gov staging" to "set up prod." 

A bunch of the tasks and notes in this Epic and sub-tickets are just as relevant to prod as they are to gov staging — for example, notes about improvements to the CircleCI processes and the HHS CircleCI setup.

**Comment by alexsoble** [comment]
Closing this one rather than recycling, because it would more or less be a duplicate of #721.
