### ISSUE TITLE
Generate OWASP ZAP report as part of the automated CI/CD process

### ISSUE THREAD

**Issue by hursey013** [raft-tech/TANF-app#730]
**Description:**
Right now we have OWASP ZAP running as part of our deployment process, however OCIO has requested a more readable format. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] OWASP ZAP continues to run on both frontend and backend
- [x] Generate and save report artifacts as part of CI/CD testing step
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Research implementation on https://github.com/HHS/Head-Start-TTADP/blob/main/.circleci/config.yml
- [x] Update CircleCI config and associated files
- [x] Run Testing Checklist and confirm all tests pass

**Comment by lfrohlich** [comment]
Merged and complete. Follow up #870 pa11y fix
