### ISSUE TITLE
[Frontend] Add Dropdown for Quarters Selection

### ISSUE THREAD

**Issue by jorgegonzalez** [raft-tech/TANF-app#738]
**Description:**
Users need to be able to select a Quarter (e.g. Q1, Q2, Q3, Q4) in addition to a year as part of the upload report process.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Dropdown allows user to select a Quarter on the Reports page.
- [x] Users see error statements when clicking Search without selecting a Year and STT and quarter

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Build Quarters dropdown with four options.
- [x] Add Dropdown to Reports page below the Years dropdown.
- [x] Update Redux  with a selectedQuarter state, and create related action(s).
- [x] Connect Dropdown to the Redux state.
- [x] Add appropriate UI and Redux tests.
- [x] Prevent users from clicking `Search` and rendering the Upload Report if they have not selected a year and STT
- [x] Run Testing Checklist and confirm all tests pass.

**Notes**
Related #627 
[Figma mockups](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=4124%3A0)

**Comment by jorgegonzalez** [comment]
@reitermb do you know if there's an updated mockup for this? For now I've listed the task as adding the component below the current Years dropdrown.

**Comment by jorgegonzalez** [comment]
> @reitermb do you know if there's an updated mockup for this? For now I've listed the task as adding the component below the current Years dropdown.

This was resolved and confirmed in a Dev/Design sync today.
