### ISSUE TITLE
[Backend] Update existing endpoints to support OpenAPI documentation

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#756]
**Description:**
Once the OpenAPI tools are implemented, we will need to update our existing endpoints to support the tools.

**Acceptance Criteria:** 

- [ ] Documentation for all existing endpoints are automatically generated in Swagger
- [ ] Previously existing endpoint documentation is removed
- [ ] ADR is issued to explain the decision
- [ ] Documentation is produced on how to access the Swagger docs
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Move API documentation from files in `tdrs-backend/docs/api/` in to code annotations in their correlated Views/Viewsets
- [ ] Add any necessary swagger decorators to customize the output of generated docs for viewsets
- [ ] Ensure that all endpoints documented in Swagger show a realistic example payload and response.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by valcollignon** [comment]
OK to close per @ADPennington during backlog refinement 12.21.21. This doesn't seem relevant anymore.
