### ISSUE TITLE
[Full Stack] Logging upload and download activity

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#762]
**Description:**
When user's upload or download files, we need to log this activity to the server logs for auditing purposes. Logs should include the following
- Username
- Activity (upload/download)
- Date and time
- File name on S3
- STT
- Year
- Section
- Quarter
- Original file name
- File version

Additionally, these upload and download activities should be viewable in Django Admin under the history for a Report item. This can be done using the Django model [LogEntry](https://docs.djangoproject.com/en/1.8/_modules/django/contrib/admin/models/)

References:
- [Blog post about adding LogEntry to Django Admin](https://medium.datadriveninvestor.com/monitoring-user-actions-with-logentry-in-django-admin-8c9fbaa3f442)
- [Open Source package for making LogEntry viewable in Admin](https://github.com/yprez/django-logentry-admin)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Demonstrate logs recording information listed above for upload and download activity
- [ ] Demonstrate upload and download activity can be seen in the Django Admin history page for a Report
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**

- [x] Add logging statement for uploads
- [ ] Add logging statement for downloads
- [x] Add ability to view logs in Django Admin
- [ ] Screenshot system logs recording data
- [ ] Post screenshots to associated PR
- [ ] Run Testing Checklist and confirm all tests pass

**Comment by jtwillis92** [comment]
@carltonsmith I believe this one is ultimately blocked by the Upload changes we discussed earlier and https://github.com/raft-tech/TANF-app/pull/499 - however, the common functionality can be implemented with https://github.com/raft-tech/TANF-app/issues/767 so by the time this is unblocked it will be a small lift.
