### ISSUE TITLE
[Full stack] Logging Client Alerts and Errors

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#767]
**Description:**

For AU-02 we need to log alerts and events on the client side. In order to do so, we will need to add a backend endpoint that writes logging messages sent by the frontend. Logs should contain the following information:

+ Username
+ Date/Time
+ Event (alert/error)
+ Message (reason for alert or error message)

The backend should be agnostic as to what the frontend is asking it to log, so this can be leveraged for potential other uses in the future.

**Acceptance Criteria:** 

- [ ] Endpoint for logging messages from the client exists
- [ ] Client is updated to send messages to the endpoint on errors and alerts
- [ ] Screenshot of logged alerts/errors is posted to the pull request
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Create logging endpoint that accepts JSON messages and logs them to the system
- [x] Create abstract logger function in the frontend to POST logs to this new endpoint
- [x] Run Testing Checklist and confirm all tests pass

**Comment by jtwillis92** [comment]
@carltonsmith I recall a discussion about logs showing up in Django admin, is that required as part of this issue?

**Comment by carltonsmith** [comment]
> @carltonsmith I recall a discussion about logs showing up in Django admin, is that required as part of this issue?

No, these just need to be written to the system logs. We want logs of uploads and downloads to be viewable in Django Admin.

**Comment by jtwillis92** [comment]
> No, these just need to be written to the system logs. We want logs of uploads and downloads to be viewable in Django Admin.

Makes sense, thanks for clarifying. I'll note that as an AC for https://github.com/raft-tech/TANF-app/issues/762
