### ISSUE TITLE
As a dev, I want to have a focused and easy to read deployment script

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#770]
**Description:**
Currently the script `deploy-cloudgov-docker.sh` is used to deploy new versions of the application to Cloud.gov. However, it also has some code mixed in for provisioning a new Cloud.gov app - which is incomplete (doesn't include S3 setup and a few other components).

As it stands, the incomplete provisioning code is intertwined into the script which makes it harder to follow what is going on and could lead to inadvertent changes. 

Ideally these scripts would be split into two - `provision-cloudgov-app.sh` and `deploy-cloudgov-docker.sh` where the former's sole purpose is to provision a new application within Cloud.gov along with all of the required components for both the frontend and backend (PostgreSQL, S3, etc) and the latter is responsible only for deploying new *application versions* to an already provisioned Cloud.gov environment.

This should be done before https://github.com/raft-tech/TANF-app/issues/609 which involves expanding the provisioning capabilities.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ]`deploy-cloudgov-docker.sh` handles only the deployment of new application versions
- [ ] A new script `provision-cloudgov-app.sh` contains the provisioning code taken from `deploy-cloudgov-docker.sh`
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Split `deploy-cloudgov-docker.sh` into two scripts - one for deploy and another for provisioning
- [ ] Confirm that the provisioning script works by provisioning a test app in Cloud.gov
- [ ] Confirm that the deploy script works by deploying to the Dev site with it
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by kniz-raft** [comment]
This ticket will be closed, provisioning work will be added to #609 and splitting out the scripts was completed in #844
