### ISSUE TITLE
[Frontend] Implement Buildpacks

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#781]
**Description:**

Frontend implementation of using buildpacks to deploy to cloud.gov

**Acceptance Criteria:** 

- [ ] The frontend deploy does not deploy a docker container
- [ ] The frontend deploy implements Cloud.gov buildpacks
- [ ] All deploy related documentation is updated to reflect the new process
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 
- [ ] Decide between staticfile build pack and nginx build pack
- [ ] build the buildpack - instructions in selected build packs github repo
- [ ] update `manifest.yml`
- [ ] Add new script for build pack deploy
- [ ] Test deployment on a live server using a build pack

**Supporting Documentation:**

- https://docs.cloudfoundry.org/buildpacks/staticfile/index.html
- https://docs.cloudfoundry.org/buildpacks/nginx/
- https://github.com/cloudfoundry/nginx-buildpack
- https://github.com/cloudfoundry/staticfile-buildpack
- https://direnv.net/

**Open Questions:**

- Pending approval of ADR 11

**Folder to serve files from**

root: YOUR-DIRECTORY-NAME

Example:
root: public 	Alternative root: Specifies a root directory other than the default. Use this option to serve index.html and other assets, such as HTML, CSS, or JavaScript files, from a location other than the root directory.

For example, you can specify an alternate folder such as dist or public. 

*Enforce HTTPS*
http_strict_transport_security: true 	HTTP Strict Transport Security (HSTS): Causes NGINX to respond to all requests with the header Strict-Transport-Security: max-age=31536000. This forces receiving browsers to make all subsequent requests over HTTPS. This setting defaults to a max-age of one year.

Note: Because this setting persists in browsers for a long time, only enable this setting after you ensure that you have completed your app configuration.

*Nginx config*

While the static file build pack may be enough, we do currently use an nginx config of our own.  We may choose instead to use the nginx build pack over the staticfile build pack. Developers disgression.

**Time Estimate:** 3-5 days
