### ISSUE TITLE
As a dev, I want to be on the latest stable version of Python

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#782]
**Description:**
The backend Dockerfiles currently use Python 3.7 which doesn't have some of the features introduced in later Python versions such as the walrus operator referenced [in this PR comment](https://github.com/raft-tech/TANF-app/pull/499#issuecomment-804216779)

Per the [Python 3.9.2 release notes](https://docs.python.org/release/3.9.2/whatsnew/changelog.html#changelog) the latest stable build also has some additional security fixes for things like a cache poisoning vulnerability. We should upgrade to that version to take advantage of newer features and fixes.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] All backend Dockerfiles run on Python 3.9.2
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update backend Dockerfiles to use Python 3.9.2
- [ ] Ensure no bugs are introduced by the upgrade
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by alexsoble** [comment]
@jtwillis92 Probably already on your radar, but just noting that @riatzukiza mentioned in standup that he is already breaking ground on the Cloud.gov buildpack work. 

So one way to address #782 would be getting to latest stable Python in our current Dockerfile setup; another would be to find out which version the backend buildpack is on, cut over to the buildbpack, and update the local/CI Docker setup to use that same version.

**Comment by jtwillis92** [comment]
> @jtwillis92 Probably already on your radar, but just noting that @riatzukiza mentioned in standup that he is already breaking ground on the Cloud.gov buildpack work.
> 
> So one way to address #782 would be getting to latest stable Python in our current Dockerfile setup; another would be to find out which version the backend buildpack is on, cut over to the buildbpack, and update the local/CI Docker setup to use that same version.

Agreed! I was discussing this with @riatzukiza and it looks like the buildpack defaults to 3.8.2 but I believe we can specify the version to the latest there as well. After the buildpack work this can serve to get the local environment up to the latest.

**Comment by alexsoble** [comment]
@jtwillis92 Perfect! And good catch on the 3.9 security fixes!

**Comment by jtwillis92** [comment]
Since this ticket was open we upgraded our docker python version to 3.8.9 and the current default version for buildpacks is 3.8.12. However, [Python 3.10](https://www.python.org/downloads/release/python-3100/) is the current LTS version. This is a lower priority upgrade but there are some security fixes and new features (like [structural pattern matching](https://www.inspiredpython.com/course/pattern-matching/mastering-structural-pattern-matching) :fire: )

**Comment by valcollignon** [comment]
Probably could be worked in January or February 2022 per @abottoms-coder in backlog refinement 12.21.21.
