### ISSUE TITLE
Migrate to buildpacks

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#783]
Currently we are deploying to cloud.gov using docker containers. We investigated the effort and consequence of switching to build packs and are firmly resolved we should be using them over containers so long as we are targeting cloud.gov. This will sever our dependence on dockerhub, as well as put our app on a fast track for acceptance because buildpacks are pre approved.

# Definition of Done

- [x] From the cloud.gov panel we can see that the backend is using a build pack
- [x] From the cloud.gov panel we can see that the frontend is using a build pack
- [x] Users are able to visit the website and perform all actions they previously could before switching to build packs
- [x] All backend api endpoints that previously functioned before switching can still be called with appropriate curl commands
- [x] All references to docker hub are removed

**Comment by lfrohlich** [comment]
last PR merged 5/24
Complete!
