### ISSUE TITLE
As a dev, I want to use a simulated AWS environment during tests and local dev

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#793]
**Description:**
_Provide a brief background and justification for this issue_
As noted in [this PR comment](https://github.com/raft-tech/TANF-app/pull/499#issuecomment-807371679) we are currently using a live AWS S3 instance during local development and testing. This can lead to issues with local development and incurs extra requests and resource utilization in AWS.

Instead we should utilize [localstack](https://github.com/localstack/localstack) - which simulates a full AWS environment inside of Docker. We can then point the app in local development mode or in CI to use this docker container instead of communicating with AWS directly.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Local dev, tests and CI use a simulated AWS environment instead of a live service.
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add `localstack` to the docker-compose configuration
- [x] Update local env configurations such that localstack is used for S3 instead of AWS
- [x] Update any documentation with the steps necessary to integrate the app locally with localstack.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
