### ISSUE TITLE
As a dev, I'd like to be able to retain my database contents between restarts

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#795]
**Description:**
_Provide a brief background and justification for this issue_
Currently whenever the backend's `postgres` container is torn down all of the data stored inside the PostgreSQL database is deleted. While this is useful for tests or resetting to a clean state it requires developers to unnecessarily be forced to re-create useful data that can help assist in troubleshooting or demoing a feature.

As an alternative, we can use [a docker volume](https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose) to persist the data to a local folder and mount that within our docker-compose. We'll need to make sure that this folder is explicitly ignored from Git so that we don't accidentally check in any local data. Additionally, it will be important to note in the README how to reset the database to the original state under the mounted volume (rm everything in the folder except .gitignore).

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] PostgreSQL data should persist between docker restarts for local environments
- [ ] PostgreSQL data should not be checked in to source control
- [ ] Developers should have instructions on how to reset local DB to original state if needed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add a mounted volume to the docker-compose configuration for `postgres` that points to a local folder
- [ ] Add a .gitignore into the mounted local directory that ignores everything except for itself
- [ ] Update README with information about how data is persisted and how to delete it
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [PostgreSQL DockerHub image](https://hub.docker.com/_/postgres)
- [Relevant stack overflow discussion](https://stackoverflow.com/a/62301253/9085243)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
