### ISSUE TITLE
As a reviewer, I want PR templates that provide best practices for our process

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#808]
**Description:**
As we continue to refine our internal processes we should ensure that we keep the PR template for this project up to date.

We have been working to implement (or re-implement) several best practices for which our PR template should be updated to account for:
* PR descriptions should include at least one GIF and/or screenshot showcasing the changes and how to test.
* A checklist item should be added to ensure that contextual comments are added where relevant in either the code directly or in GitHub comments.
* The deployment item for the preliminary QASP checklist should be updated to show that we can deploy before approval and mention steps on how to use the label based deployments to test.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] PR Template requests GIFs/screenshots
- [ ] PR Template enforces contextual comments
- [x] Update How to test section
- [ ] Preliminary QASP checklist outlines deployment process
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add a section to PR template for GIFs & screenshots
- [ ] Add a checklist item for adding context via comments
- [ ] Update preliminary QASP checklist deployment step with updated process
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
- [Relevant article about PR best practices](https://artsy.github.io/blog/2020/08/11/improve-pull-requests-by-including-valuable-context/)

**Supporting Documentation:**

**Open Questions:**

**Comment by amilash** [comment]
@jtwillis92 Do we still need an update on our PR template? Or are we 'up to snuff'?

cc @abottoms-coder

**Comment by jtwillis92** [comment]
This is still an outstanding TO-DO.

**Comment by amilash** [comment]
Thanks John
