### ISSUE TITLE
[DevOps] Add clamav to local and cloud.gov environments for virus scanning

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#817]
**Description:**
As decided in [our latest Anti Virus ADR](https://github.com/raft-tech/TANF-app/pull/813) we need to add a solution to our application so we can scan uploaded files for viruses prior to accepting them and saving them to S3.

[clamav-rest](https://hub.docker.com/r/ajilaag/clamav-rest) is a popular open source ClamAV REST implementation that exposes API endpoints that can be used to scan files. This solution is already in use in other government projects that have received ATO and is familiar to members of the OCIO team.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Local environments have a ClamAV REST server available to send files to
- [x] Cloud.gov environments have a ClamAV REST server available to send files to
- [x] Strategy for keeping ClamAV libraries up to date is documented
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add `clamav-rest` to our docker-compose
- [x] Add `clamav-rest` to our Cloud.gov manifest
- [x] Configure CircleCI to deploy clamav-rest alongside app deployments.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

- [Example cloud.gov manifest usage of clamav](https://github.com/usdoj-crt/crt-portal/blob/develop/manifest_dev.yaml#L23)
- [Example CircleCI configuration for clamav](https://github.com/usdoj-crt/crt-portal/blob/develop/.circleci/config.yml#L236)
- [Example Docker Compose configuration for clamav](https://github.com/usdoj-crt/crt-portal/blob/develop/docker-compose.yml#L44)

**Open Questions:**

**Comment by kniz-raft** [comment]
@ADPennington will update the boundary diagram, SSP and (CM-07)02 as part of QASP

**Comment by kniz-raft** [comment]
@jtwillis92 will update the README and ADR with how the libraries will be kept up to date

**Comment by lfrohlich** [comment]
@ADPennington  updated boundary diagram #853
