### ISSUE TITLE
As a product owner, I would like the file submit wired to a backend endpoint

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#826]
**Description:**

In the [original pull request](https://github.com/raft-tech/TANF-app/pull/732) for #430 we had the work completed, but there were changes to the strategy for the backend, so it wasn't ready to receive the submitted files. That PR went in with a stubbed endpoint. This issue is for removing that stub and actually submitting the files to the backend. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Files are sent from the frontend to the backend for processing
- [ ] Demonstrate the backend received and processed the files
- [ ] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Remove stubbed routes in `src/mirage.js`
- [ ] Update axios requests in actions to use proper endpoint URL
- [ ] Run through file upload flow, 'Submit Data Files', and check that a request was made to the local backend instance
- [ ] Validate the records were created in the backend database with curl or by looking at the reports table in postgres 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

**Comment by amilash** [comment]
@jorgegonzalez is file submit not working currently? Wondering if this ticket is relevant or complete.

**Comment by lfrohlich** [comment]
this is complete
