### ISSUE TITLE
[Backend] Add endpoint to download a file from S3

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#833]
**Description:**
As outlined in our [latest AV ADR](https://github.com/raft-tech/TANF-app/pull/813) we are moving to performing Data File downloads from the backend as opposed to downloading them directly from S3 pre-signed URLs. To accomplish this we need to add a new API endpoint that authorizes the user and provides them with the downloaded file.

**Acceptance Criteria:** 

- [ ] Data Files can be downloaded directly from our API
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Add a new API endpoint that prepares the file for download
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
