### ISSUE TITLE
As OFA tech lead, I'd like automated checking for unused dependencies for frontend+backend

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#838]
**Description:**
This is motivated by #768, which is focused on removing unused frontend dependencies and leveraging `depcheck` to check for these. It seems worth doing a similar audit and cleanup for any unused backend dependencies, and ideally building automation around this to monitor for us. 

**Acceptance Criteria:** 

- [ ] No unused dependencies should be installed in the project
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] _tbd (will discuss with dev team)_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- is there a python equivalent to JS devcheck (e.g. https://github.com/r1chardj0n3s/pip-check-reqs)? 
- what is the level of effort to build this into circleci?
- pre- or post- ATO?

**Comment by valcollignon** [comment]
Devs will revisit in December or January. Not a high priority.

**Comment by jorgegonzalez** [comment]
I think automating this is overkill unless it can be accomplished with very little work, ideally within an hour.

We already have constant eyes on our dependencies with Dependabot and our Processes™️. This ticket was not a high priority when written, and it is not a high priority now

**Comment by stevenino** [comment]
Closed as OBE per backlog refinement on 7/12/22
