### ISSUE TITLE
As an ACF user, I would like to be able to log in through ACF AMS

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#842]
**Description:**
ACF users should have the option to login through the ACF AMS

**Acceptance Criteria:** 

- [ ] Design and workflow for ACF login is provided by research/design
- [ ] User is able to choose whether to login through login.gov or ACF AMS
- [ ] Login.gov login works the same as it does now
- [ ] User is able to authenticate through ACF AMS
- [ ] User is able to log out regardless of the system used to log in

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Develop design and workflow that allows users a choice of how to log in
- [ ] Frontend tasks dependent upon design and workflow
- [ ] Add alternate logic for login to the backend
- [ ] Add logic to the backend so it knows what system it is logged in through
- [ ] Add alternate logic for logout to the backend
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

- Only users with a PIV card will be able to authenticate in both the staging and production environments
- Only users with a PIV card will be able to test this functionality
- Any developers working on this will need a PIV card to develop and test locally

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Authentication & Authorization folder](https://teams.microsoft.com/_#/files/compliance?threadId=19%3A3658d5183f3e4e648c0304832c1eafc4%40thread.skype&ctx=channel&context=Authentication%2520%2526%2520Authorization&rootfolder=%252Fsites%252FTANFDataPortalOFA%252FShared%2520Documents%252Fcompliance%252FAuthentication%2520%2526%2520Authorization)

**Open Questions:**

- If developers need a PIV card to log in, will they need to develop this on a government computer?
- If development will have to be done on a government computer, software such as PyCharm or VSCode will need to be installed

**Estimate**
- The documentation on implementing the ACF AMS is much more ambiguous than the login.gov documentation, so there will be quite a bit of "guess and check" type work
- If development needs to be done on a gov computer then setup time and time to get software installed will need to be added to this estimate
- I estimate this work will take about 2 sprints to complete, but the "guess and check" issue noted above could stretch it to 3 sprints
- This estimate does not include time to develop design and workflow, nor time for that work to be approved

**Comment by kniz-raft** [comment]
This ticket was generated as part of the Spike ticket #751

**Comment by abottoms-coder** [comment]
@amilash Is this a dupe of #1134 ?

**Comment by amilash** [comment]
Is duplicate, closing.
