### ISSUE TITLE
Move vendor-staging in the dev space to staging in the staging space

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#847]
**Description:**
As outlined in [this ADR](https://github.com/raft-tech/TANF-app/pull/823) we are moving the vendor-staging application in the Dev Cloud.gov space to the Staging space and renaming it to `staging` vs `vendor-staging`

**Acceptance Criteria:** 

- [ ] Dev space no longer has a Vendor Staging environment
- [ ] On merge to `raft-tdp-main` a deployment is made to the Gov Staging Space as the `staging` environment
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [x] Delete existing `vendor-staging` apps in Cloud.gov
- [ ] Provision a new `staging` application in Cloud.gov Staging space
- [x] Update `.circleci/config.yml` to point merges to `raft-tdp-main` to the staging space/app.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
