### ISSUE TITLE
As a Windows User, I would like to ensure my line endings are consistent and emojis are removed from code

### ISSUE THREAD

**Issue by carltonsmith** [raft-tech/TANF-app#850]
**Description:**
When attempting to launch the project in a Windows environment, Alex ran into issues because of emojis in the `waiting_for_postgres.py` file. Those emojis should be removed. Also, when developers work in mixed environments there can be issues with file formatting which can be controlled with the `.gitattributes` file. That file should be updated to prevent possible future issues.

**Acceptance Criteria:** 

- [ ] Emoji are removed from `waiting_for_postgres.py`
- [ ] `.gitattributes` file is updated with values appropriate to this project

**Tasks:**

- [ ] remove emoji
- [ ] Update `.gitattributes`
- [ ] Run Testing Checklist and confirm all tests pass
