### ISSUE TITLE
[A11y] Upload functionality improvements

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#858]
**Description:**
Follow-on from existing upload work (#430 , #530 , and #738) to enhance clarity and reduce distractions in the upload flow. Particularly impactful for screen reader users. 

**Acceptance Criteria:** 
- [x] File input "results" don't change or disappear unless "Search" is clicked
- [x] When (STT/Fiscal Year/Quarter) form has errors, focus shifts to error summary whenever "Search" is clicked
- [x] Changes to error summary continues to be announced as an alert as individual errors are resolved
- [x] Header shows undefined for the STT in some cases

**Tasks:**
- [ ] _Task 1_

**Notes:**
From pairing on the issue:
- Making sure nothing on screen changes without activating the search button (disappearing the file input section is preferable to the swapping out we initially did, making sure nothing happens until search is clicked is preferable to that)

- One tweak to the validation on STT/Year/Quarter inputs to move focus to the error summary when the search button gets clicked not just announce the error summary. **The Request Access form already behaves like this if a reference is helpful!**

**Supporting Documentation:**
![image](https://user-images.githubusercontent.com/28515874/115744803-e343ee80-a360-11eb-90c2-a70129922033.png)
Example of focused error summary in the Request Access form

**Open Questions:**
- _Open Question 1_

**Comment by reitermb** [comment]
cc @jorgegonzalez @kniz-raft
