### ISSUE TITLE
Add 404 routes to nginx config file

### ISSUE THREAD

**Issue by riatzukiza** [raft-tech/TANF-app#865]
**Description:**

We recently ran into an issue in the OWASP Scan

to fix this we would be adding the same routing rules we have using react-router to nginx. 
The main thing to be aware of will be that any new routes after we do this will have to be added 
in two places (tdrs-frontend/src/components/Routes.js and tdrs-frontend/nginx/nginx.conf)

we have to explicitly declare the valid paths, and treat everything else as 404, then implement a 
404 page, either a static html file, or as a react component, I would be leaning towards the react component.

![image.png](https://images.zenhubusercontent.com/5f8dd81f1445bab3bbb34891/abc4a027-161a-4293-96df-e8ad9287284f)

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] High risk zap scan item is no longer present
- [x] Routes we have not explicitly provided react routes for, should serve a 404
- [x] When the react app detects the page has been served with a 404 status, it should display a Not Found page instead of a blank one
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update nginx.conf file to be more selective about what pages are valid
- [x] Update nginx.conf file to emit a 404 response
- [x] Add 404 react component
- [x] Run Testing Checklist and confirm all tests pass
- [x] @ADPennington to update POAM

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

+ In the future, if we add routes, we will have to add them to both the routes.jsx file and the nginx.conf file

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

+ [No match react route example](https://reactrouter.com/web/example/no-match)

**Comment by ADPennington** [comment]
@riatzukiza @carltonsmith glad to hear about the progress being made on this one! in keeping with last week's discussion re: plain language descriptions of errors in owasp reports--could we include the plain language description of this error (what it means, why we should or shouldnt be concerned (even though we're fixing it now), etc.) in this issue description?
