### ISSUE TITLE
Update Pa11y configuration to check more URLs and store artifacts from screenshots

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#872]
**Description:**
Currently our `.pa11yci.json` configuration only tests these URLs:
```
    {
      "url": "http://localhost:3000",
      "screenCapture": "pa11y-screenshots/homepage.png"
    },
    {
      "url": "http://localhost:3000/edit-profile",
      "screenCapture": "pa11y-screenshots/edit-profile.png"      
    }
```
As the project has evolved we have a lot more pages that need to be checked for accessibility. (Also `edit-profile` may no longer be relevant)

Additionally, pa11y is configured to take screenshots of these pages - but does not store the artifacts outside of the Circle CI machine executor so they are not viewable by anyone after the fact. We need to add a `store_artifacts` command to the Circle CI `config.yml` to export these screenshots to the Job artifacts.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Pa11y runs accessibility tests on all relevant URLs
- [ ] Pa11y screenshots are persisted to a job via Circle CI artifacts
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Determine which URLs would benefit the most from accessibility testing
- [ ] Update `.pa11yci.json` to include the URLs identified in the task above
- [ ] Update `.circleci/config.yml` to store artifacts generated by Pa11y
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**
- [Storing Circle CI Artifacts](https://circleci.com/docs/2.0/artifacts/)
- [Pa11y URL Configuration](https://github.com/pa11y/pa11y-ci#url-configuration)

**Open Questions:**
