### ISSUE TITLE
OWASP: Exclude false positive alerts during CI/CD

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#879]
**Description:**
Some of the alerts thrown by the OWASP scanner during the Circle CI step are non-actionable due to the way the server is launched. For example, in this [generated report](https://6141-281707402-gh.circle-artifacts.com/0/tdrs-backend/reports/owasp_report.html) we see an error for `HTTP Only Site`. This will always be true in Circle CI as the server is being run on the `localhost` of the machine executor.

Instead we can use the built in ZAP configuration options to exclude these known false positives only when run in CI.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] False positive alerts are not shown in OWASP ZAP report
- [ ] Documentation is provided with reasoning for any excluded alerts
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create a ZAP configuration file that excludes false positive alerts
- [ ] Update `zap-scanner.sh` scripts to use that configuration file in CI
- [ ] Add documentation for any excluded alerts
- [ ] Run Testing Checklist and confirm all tests pass
- [ ] @ADPennington to update POAM

**Notes:**
- [Here](https://github.com/usdoj-crt/crt-portal/blob/4bc8c5ace36a99d5c63223203c30621aa084a8f7/.circleci/zap.conf) is an example ZAP configuration file with excluded alerts from another government project.

**Supporting Documentation:**

**Open Questions:**
