### ISSUE TITLE
CI/CD Health Check Template

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#880]
**Description:**
We would like to periodically review our Circle CI configuration to ensure that everything is working as expected and we are getting the full benefits of CI/CD. To help document this process and make it easier for future efforts we should create a template file that contains all the steps needed to audit Circle CI.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] CI/CD Health Checks can be performed with a re-usable audit template
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Create a template for CI/CD Health checks and commit it to the repo
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by abottoms-coder** [comment]
@ADPennington wants to pair on this ticket and wants to add a task here for reviewing code coverage reports.
