### ISSUE TITLE
As OFA tech lead, I need Incident Response Drills conducted for Release 1

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#885]
Before release 1 of TDP is completed, we should conduct a series of incident response drills ([examples](https://engineering.18f.gov/security/incident-response-drills/)) to help ensure we are prepared with a process to address standard high priority incidents expeditiously prior to going live and receiving data through TDP. 

ACs:
- All relevant drills conducted prior to completion of Release 1. 
- Incident response protocols per drill are documented and centralized in the repo 
- Incident Response Plan ATO [doc](https://teams.microsoft.com/l/file/7B139516-EB55-4592-8310-3FD2D8435DB4?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FSystem%20Security%20Plan%2FTDP_Security-IRP_ACF-OCIO_20210426%20(cm)_OFA20210513.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287) updated

Tasks:
- [x] Confirm drills most relevant for release 1, and create tickets to track completion of drill. 
- [x] Develop agenda for each incident response drill. 
- [x] Conduct drill. 
- [x] Create subdir in repo docs for incident response drill documentation. 
- [x] update incident response plan for release 1. 

---
Release 1 Drills:
- [x] #1642
- [x] #1750

**Comment by alexsoble** [comment]
@ADPennington @lfrohlich Worked with a few 18F teammates to create a template Incident Response Drill that we can re-use for TDP!

Website: https://engineering.18f.gov/security/incident-response-drills/

Pretty Markdown: https://github.com/18F/development-guide/blob/main/_pages/security/incident-response-drills.md

Raw Markdown: https://raw.githubusercontent.com/18F/development-guide/main/_pages/security/incident-response-drills.md

All of these drills use our stack: CircleCI, GitHub, cloud.gov. 

We could select one or two of these drills that feel most relevant for TDP, full in the blanks (there are only about one or two blanks per drill), and add to TDP docs either in GitHub or Teams. 

Depending on how high-priority this feels, we could either tackle this this week or next before I roll off, or leave this as a TODO for after I roll off. :sad:

**Comment by abottoms-coder** [comment]
- [ ] Update this doc 
https://teams.microsoft.com/l/file/7B139516-EB55-4592-8310-3FD2D8435DB4?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2Fcompliance%2FSystem%20Security%20Plan%2FTDP_Security-IRP_ACF-OCIO_20210426%20(cm)_OFA20210513.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:3658d5183f3e4e648c0304832c1eafc4@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287

**Comment by ADPennington** [comment]
Release 1 incident response tasks and related drills:
 - [ ] boundary diagram review to identify access points most vulnerable to unauthorized access or failure 
 - [ ] Potential drills:
   - [A deploy goes wrong](https://engineering.18f.gov/security/incident-response-drills/#scenario-a-deploy-goes-wrong)
   - [Secret key leakage](https://engineering.18f.gov/security/incident-response-drills/#scenario-api-keys-or-passwords-exposed)
   - [Accidentally erased S3 bucket](https://engineering.18f.gov/security/incident-response-drills/#scenario-oops-i-erased-the-s3-bucket)
   - TDP website down
   - TDP Release 1 (or prior) features not working:
     - Users cannot login
     - Users cannot upload files
     - Users cannot download files previously transmitted
     - Sys admins cannot manage users

**Comment by valcollignon** [comment]
@ADPennington and @abottoms-coder to sync on this epic in February 2022.

**Comment by ADPennington** [comment]
@valcollignon @lfrohlich 

@abottoms-coder and I met today (2/11) to discuss potential drills (Andrew had quite a few really good suggestions that are saved in our tech sync log). We'll be meeting next week to plan out 2 exercises related the following types of incidents:  
- a deploy has gone wrong (re: env variable key value pair mangling)
- sys admins cannot manage users (re: accounts compromised) 

There are also a couple of drills referenced above that do not require drills but need documentation added to the repo. We'll create follow-on issue to track those repo additions.

**Comment by ADPennington** [comment]
@abottoms-coder and I met today 2/16 to plan the incident response drill for `sys admins cannot manage users via TDP (re: accounts compromised)`. [hackmd](https://hackmd.io/Yyo_NiIzRp6tqIS-6gLC6w) with draft of the drill is ready for review. Once finalized, next steps are to:
- practice the drill with `system owner` and `system admins`
- add drill documentation to the repo via PR. 
cc: @lfrohlich

**Comment by stevenino** [comment]
@lfrohlich Can we close this?

**Comment by lfrohlich** [comment]
I think @ADPennington had one more drill in mind

**Comment by lfrohlich** [comment]
> > I think @ADPennington had one more drill in mind
> 
> Ok, in that case we will need a new ticket linked to this epic.

Converted task into an issue: https://github.com/raft-tech/TANF-app/issues/1750

**Comment by ADPennington** [comment]
this epic has been completed.
