### ISSUE TITLE
TDP Permissions Model

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#888]
Goal: The Goal is to create permissions hierarchy for Admins and users such that they can exist and have the proper credentials to enable other admins and or users.

Proposed tasks:
- [x] Define admin user hierarchy and needs #1058
- [x] Refactor backend to use default model permissions
- [x] Add migrations to configure groups to add permissions to different models 
- [x] Add developer group and configure for separate environments (doesn't require PIV/CAC for dev and staging, no dev group in production)
- [x] Review and reconfigure how "Super User" is assigned in DAC (blocked by the previous 3)

Permissions Matrix in One Note: https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FPermissions%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29

**Comment by abottoms-coder** [comment]
The current security control [here](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/Security-Compliance/Security-Controls/ac-5/index.md) documents the first draft of permissions.

Proposed Permissions Matrix Table:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/arb/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/arb/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>
<body link="#0563C1" vlink="#954F72">

  | Users | Regions | STTs | Data Files | Years/Quarters | Django Admin | Env*
-- | -- | -- | -- | -- | -- | -- | --
Developer | All | All | All | All | All | All | role won't exist in prod
OFA admin | V, Approve | V | V | All | V | V |  
Sys Admin | All | All | All | All | All | All |  
Regional Manager | All(in region) | V | V | All(in region) | V | None |  
Data Analyst (STT user) | V | V | V | A,C,D (in STT) | V | None |  
  |   |   |   |   |   |   |  
All= | Add, Change, Delete, View |  For some objects, delete just means   inactivate | For data files, change doesn't mean overwriting as we will be leveraging S3 versioning  |   |  
</body>
</html>

**Comment by amilash** [comment]
@dk-ui will you use the workshop to validate ^ assumptions of needs for admins?

**Comment by amilash** [comment]
Permissions Matrix in One Note: **https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Compliance.one%7Cd9b65ab8-bf29-476a-a652-d003714e50a4%2FPermissions%7C67b61c8f-b200-46e8-8e73-b5aa6382a19c%2F%29 **

**Comment by stevenino** [comment]
@ADPennington @lfrohlich can we close this epic? All associated tickets are closed.

**Comment by lfrohlich** [comment]
Yes, good to close
