### ISSUE TITLE
As an OFA Admin, I want an accessible, 508-compliant user interface for managing permissions

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#892]
Delivers a fully accessible (minimum of WCAG 2.0 AA standard) Django Admin experience for use in TDP (and potentially other projects)

## Context & Notes

TDP is currently using Django Admin for user administration and permission administration. 

We know that the Django Admin dashboard is not fully accessible. 

See Django Admin Ticket: [Improve overall admin accessibility #31617](https://code.djangoproject.com/ticket/31617).

## First steps for refinement

- [x] Talk through Miles' synthesis about findings as a team (link in comments)
- [x] Talk through recommendation in Dev Sync (May 26th)
- [ ] Connect with Janean (ACF OCIO) on implications/severity

**Comment by reitermb** [comment]
An initial synthesis of the biggest Sec 508 (and a few 508+) a11y issues: [https://hackmd.io/@mreiter/ryuHXhbuu](https://hackmd.io/@mreiter/ryuHXhbuu)

**Comment by kniz-raft** [comment]
@reitermb is going to create a ticket for this work and let us know when it's ready to be looked at

**Comment by reitermb** [comment]
> @reitermb is going to create a ticket for this work and let us know when it's ready to be looked at

#973 -- Now refining, but went ahead and created it so as to have a number to point to

**Comment by lfrohlich** [comment]
closing with #1392 as follow on
