### ISSUE TITLE
Audit Config & Inspection for Production Environment for v1.0 and v2.0

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#897]
#### v1.0 features:
 - login from `.acf.hhs.gov` frontend  via ACF AMS and login.gov 
 - user management from `app.cloud.gov` backend (i.e. tdp-backend-prod.app.cloud.gov)
 - request access for acf and non-acf users 
 - access to security scans for ocio 

#### v2.0 features:
most V1.0 features plus: 
 - user management now from `.acf.hhs.gov` backend (i.e. api-tanfdata.acf.hhs.gov)
 - owasp nightly scan running on production apps
 - FY22 data files can be submitted by real users 
 - virus scanner working properly
 - resource cards 
 - asterisk replaces "required" on request form
 
_note: file transfer from tdp to titan (#1133) will be included in a minor v2 release._

Since TDP is configured with environment variables, we need to ensure that all the appropriate key value pairs exist in production spaces for circleci and cloudgov. We also need to confirm that all the expected features of TDP for these early releases are in-place. 

**ACs**:
- [x] `production-deployment` workflow from HHS CI is successful. 
- [x] ACF user can login at https://tanfdata.acf.hhs.gov/ or [this site](https://tdp-frontend-prod.app.cloud.gov) 
- [x] non-ACF user can login at https://tanfdata.acf.hhs.gov/ [this site](https://tdp-frontend-prod.app.cloud.gov) 
- [x] ACF user can request access 
- [x] non-ACF user can request access
- [x] `OFA Sys Admin` can access all parts of DAC to manage users and data
- [x] `ACF OCIO` can login, request access, and access DAC Security Application
- [x]  non-ACF user can submit data files for FY22Q3

**Tasks**:
- [x] Run deployment workflow from HHS CI. 
- [x] Complete  v1.0 dry run on 7/27
- [x] Complete  v2.0 dry run on 8/9

**Notes**

- hackmd for release 1 demo: https://hackmd.io/V3px6xWeQJCm8OAgRIgAeA

**Comment by valcollignon** [comment]
Discussed during 11.23.21 backlog refinement. There are other issues in #721 epic that need to be completed first. @ADPennington to work on it at that time.

**Comment by ADPennington** [comment]
per 3/29 backlog, closing. will do this as a task with #895.

**Comment by ADPennington** [comment]
re-opening this. we will need to confirm that the appropriate env var key value pairs are set in prod. includes:

- sftp env vars (#1737)
- nextgen env vars (#1153)
- acf ams env vars (#1627)

**Comment by ADPennington** [comment]
### Notes re: prod deployment failure from HHS:master on 7/19/2022

@lfrohlich @andrew-jameson @stevenino the deployment workflow initially failed at the `deploy-instrastructure-prod` job, for a couple of reasons:
-  a formatting issue at the [`terraform fmt` step](https://app.circleci.com/pipelines/github/HHS/TANF-app/604/workflows/fce08fb6-e0e0-4f8a-9173-d56491bffab1/jobs/1272), which was resolved by [Aaron’s hotfix](https://github.com/HHS/TANF-app/commit/904019ed28872fd76caaf7436796183fba9cfe99).
- then, it failed at the  [`terraform apply` step](https://app.circleci.com/pipelines/github/HHS/TANF-app/606/workflows/7c88ce72-86fa-43ce-9d61-474e279741ea/jobs/1282), which appears at a glance to be because the services are trying to be created for the first time rather than refreshing. 

I deleted all these services and redeployed. The production deployment  workflow was ultimately **[successful](https://app.circleci.com/pipelines/github/HHS/TANF-app/606/workflows/28610242-da39-43a3-87a7-734177b5d22c)** after completing the following tasks :

1. followed the [guidance from cloud.gov support](https://cloud.gov/docs/services/s3/#interacting-with-your-s3-bucket-from-outside-cloudgov) to empty the `tdp-datafiles-prod` s3 prior to deleting it, then deleted all the other services. 
2. Reallocated 1GB of RAM from dev to prod since this was needed 
3. `cf restart` from terminal 
4. Re-ran circleci `production-deployment` workflow
5. `cf map-route tdp-frontend-prod tanfdata.acf.hhs.gov` from terminal

Note the following:
- deleting services in the prod space is not a good idea when we have real users. Not clear on why the infrastructure job at the above-mentioned steps failed and what to do if we run into this again when real users are onboard. 
- while the splash page is currently up, **logging into TDP prod** is not possible until [`ALLOWED_HOSTS`](https://github.com/raft-tech/TANF-app/blob/edea3cd7bdd69d277a91647e63d94c74d363326c/tdrs-backend/tdpservice/settings/cloudgov.py#L146) is updated with the `app.cloud.gov` backend route. cc: @riatzukiza

**Comment by ADPennington** [comment]
demo'd 7/27/2022 for TDP IPT meeting. this can be closed when first AC met. cc: @stevenino

**Comment by ADPennington** [comment]
Production deployment successful per [PR #400 to `HHS:master`](https://github.com/HHS/TANF-app/pull/400). Notes:

- v1.0 features were deployed with release 2.0 features with abovementioned PR. 
- #1133 will come in a minor release for v2. completion of this work was blocked by connectivity issues originating from NIH, who manages the Titan server. 
- owasp nightly scan in production is running successfully but the reports are not being stored in DAC. this is being tracked in #2054
