### ISSUE TITLE
As an administrator, I can assign a role to a new user via the Django's admin console

### ISSUE THREAD

**Issue by RafterGit** [raft-tech/TANF-app#9]
**Description:** 
Once a new user creates a profile and requests access, the system notifies an admin of users request for access. This epic will deliver an admin assigning an existing role to a new user using Django's admin console. 

**AC**:
- [ ] ~~Unassigned users can be assigned an existing role by selecting a role from the dropdown~~
- [ ] ~~Role can be assigned one user at a time or to multiple users~~ 
- [ ] ~~Selecting a role from the dropdown displays list of activities tied to the chosen role~~ 
- [ ] ~~Clicking on 'Assign' CTA assigns unassigned users a role and serves a success notification~~ 
- [ ] ~~Remove 'Cancel' CTA~~ 
- [ ] ~~Frontend matches the [mockup](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231) "# 164-updated"~~ 
- [x] Demo of assigning a role to a new user using Django's admin console (DAC) 
- [x] Update documentation with AC-02(07) and IA-04 security controls (with screenshots using DAC, if necessary) 
- [ ] New issue is created for assigning a role to a new user via the UI

**Tasks:**
The following tasks have been broken down into separate backend and frontend issues associated with the epic:

*Frontend*
- [ ] Create component for assigning roles #355 
    - [ ] Add `Admin` and `Profile` navigation links
    - [ ] Add side navigation with `Users` and `Roles`
    - [ ] Add `Assign Users` h1
    - [ ] Create new component for assigning roles to users
    - [ ] Create route for rendering component (possibly `/admin/roles/assign`)
    - [ ] Add assign user card with name, email, stt and region
    - [ ] Tests are created 
- [ ] Role Selection Box #356 
    - [ ] Add `Select` USWDS element for choosing user role
    - [ ] Add fetch to get possible roles for user
    - [ ] When role is selected populate card with information about role
    - [ ] Tests are created
- [ ] Add Buttons To Role Assignment Component #357 
    - [ ] Add `Assign` button
    - [ ] Tests are created
- [ ] Send Role Information to Backend #358 
    - [ ] Add logic for the endpoint to assign a role
    - [ ] Upon successful assignment of the role, a `Success` alert (https://designsystem.digital.gov/components/alert/) is displayed with the number of successful assignments, the names of the users who were successfully assigned, and their assigned role.
    - [ ] Tests are created

*Backend*
- [ ] Testing for endpoint to return a list of users with STT and Region
- [ ] Endpoint to return a list of users with STT and Region
- [ ] Testing for current roles and permissions endpoint
- [ ] Endpoint with list of current roles and associated permissions
- [ ] Testing for updating a list of users endpoint
- [ ] Endpoint to update the roles of a list of users (respond with success or error message)
- [ ] Run all tests and ensure all tests are passing

Note:
- This issue will not deliver an admin creating new role(s)
- Try to reframe as an epic (@carltonsmith) - done
- STT and Region are being pulled from backend
- Success notification will show screen as noted in supporting documentation

Open Question:
- Discuss where an admin should be redirected if he/she clicks 'Cancel' CTA
   - Cancel CTA will be post OFA MVP. [Mockup](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231) updated to remove 'Cancel CTA' 

Supporting Documentation:
- #### [164 - Updated](https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=2441%3A12231)

**Comment by lfrohlich** [comment]
@RafterGit  will break this down into smaller frontend & backend chunks that will ensure that the authorization is extensible.

**Comment by shubhi-raft** [comment]
@carltonsmith to use this issue and frame it as a thinly sliced epic.

**Comment by shubhi-raft** [comment]
Question for OCIO - security (@lfrohlich)
- Can the security controls be met if only we have one role for OFA MVP?

**Comment by amilash** [comment]
@abottoms-coder  can you take a look at this and confirm that the 'done' work here is accomplished by the Django admin features/functionality? Thanks! The rest we think is enhancement tickets that we will leave open for a later version (v4) as admin UI enhancements when we move the Django admin stuff into the AP UI. Thanks

**Comment by abottoms-coder** [comment]
> @abottoms-coder can you take a look at this and confirm that the 'done' work here is accomplished by the Django admin features/functionality? Thanks! The rest we think is enhancement tickets that we will leave open for a later version (v4) as admin UI enhancements when we move the Django admin stuff into the AP UI. Thanks

Understood, and yes, I believe the admin console covers the functionality for closed tickets.

**Comment by amilash** [comment]
This is done, closing.
