### ISSUE TITLE
[Dependencies] Remove @testing-library/user-event

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#925]
**Description:**
[@testing-library/user-event](https://github.com/testing-library/user-event) is currently unused in the project but is listed in devDependencies. As a result, Dependabot will attempt to [upgrade it](https://github.com/raft-tech/TANF-app/pull/919) which causes unnecessary review time to be spent by the team and contributes to a larger package size for the frontend application when built for local development. We should instead remove this and only add it back if it is explicitly used in the future. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] `@testing-library/user-event` is removed from the project
- [x] Testing Checklist has been run and all tests pass

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Run `yarn remove @testing-library/user-event` and commit the resulting package.json and yarn.lock files.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
