### ISSUE TITLE
[Frontend] Implement 404 page design

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#928]
**Description:**
As mentioned in #927 our current 404 page is not styled to fit with the rest of the app. Once we have a design for this page we will need to implement it in React.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] When visiting any nonexistent URL the custom designed 404 page is presented to the end user
- [ ] https://designsystem.digital.gov/templates/404-page/ 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update the `NoMatch` React component to utilize the styles provided in the design mockups.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
