### ISSUE TITLE
Prevent Dependabot version updates from running on HHS:main

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#932]
**Description:**
Recently a `dependabot.yml` file was added to this repo to configure Dependabot to automatically issue pull requests nightly for any dependencies listed in package.json or Pipfile. However, to keep with our current git flow we don't want these pull requests to be issued against the main HHS repository. Automatic security updates have already been disabled on the HHS repo but those work distinctly from version updates where the configuration file is the source of truth and as such those PRs still get opened.

To resolve this we can specify a [target_branch](https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#target-branch) in the configuration file so these version updates only check and issue PRs against the `raft-tdp-main` branch. Since this branch doesn't exist in HHS the PRs will not get opened. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Dependabot version update PRs do not get opened against HHS:main
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Add a `target_branch` configuration to the `dependabot.yml` configuration file
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- [Note about impact of this change](https://docs.github.com/en/code-security/supply-chain-security/customizing-dependency-updates#impact-of-configuration-changes-on-security-updates)

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_
