### ISSUE TITLE
Remove unused dependency `python-dotenv`

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#943]
**Description:**
Python dotenv was removed with #510 in favor of using the docker based `env_file` directive to load in environment variables from a file but the dependency was not removed from the Pipfile. We should remove this as its not needed in our project any more.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] `python-dotenv` is no longer a project dependency
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Remove `python-dotenv` from the Pipfile and Pipfile.lock
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

**Comment by abottoms-coder** [comment]
@jtwillis92 Says this was already removed and is no longer relevant.
