### ISSUE TITLE
Clean up duplicate ENV Variables related to AWS access keys

### ISSUE THREAD

**Issue by alexsoble** [raft-tech/TANF-app#947]

**Comment by alexsoble** [comment]
## Context 

We identified this issue during Dev Sync on 5/19; see Dev Notes > Env Vars in Teams. 

## Potentially duplicate ENV variables 

`AWS_ACCESS_KEY`, `AWS_ACCESS_KEY_ID`

## Tasks

+ [ ] Confirm if these are duplicates or not
+ [ ] If so, unify all references in the code to use one ENV variable name
+ [ ] Once the code expects a single ENV variable name, remove duplicate ENV variable from cloud.gov

**Comment by jtwillis92** [comment]
Completed with https://github.com/raft-tech/TANF-app/pull/1123
