### ISSUE TITLE
Evil journey map for security design guidance

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#954]
Description: This research first aligns the DIGIT and dev team around what is known about evil users and explores additional use cases not yet captured in past research. With a shared understanding, the team leverages two Eisenhower matrices (urgency/impact and control/definition) to discuss the priority levels of each use case so that in future versions of TDP, the team is aware of the largest potential risks. To assist in the understanding of the highest priority evil use cases, multiple journey maps will be created and used for role-playing out threats so that the team can gain a third-person perspective of how evil users think and how something innocuous can turn into something detrimental if not designed for. 

**AC:**
- [ ]  Team has shared understanding around potential threats to TDP from evil users

**Tasks:**

**Evil Use Case Prioritization Workshop**
- [x] (Dmitri) Schedule evil user journey workshop with DIGIT and dev team
- [x] (Dmitri) Complete evil user journey workshop board
- [x] (Jen) Prepares evil use cases and reviews them to the team prior to the workshop
- [x] (Jen) Run evil user journey workshop with the team
- [x] (Miles/Dmitri) Synthesis of workshops in the form of 1-2 journey maps, depicting the highest priority(s) for evil users
- [x] (Jen) Document additional scenarios that came up in the workshop

**Journey Map Workshop**
- [x] (Dmitri) Schedule journey map workshop with DIGIT team and dev team
- [x] (Dmitri) Create journey map workshop board
- [x] (Jen) Run journey map workshop
- [x] Miles/Dmitri) Synthesis of workshops by updating journey maps and documenting additional scenarios (might extend into planning sprint 23)

**DoD:** 
- [x] Synthesis and journey maps are presented at UX Sync 
- [x] @lfrohlich has signed off and moved journey map and prioritization workshop boards to an OFA mural board

**Deliverables:**
[Evil Use Case Prioritization Workshop Board](https://app.mural.co/t/raft2792/m/raft2792/1622052266137/9c2efc70dbf81eb8ad0a492354d3abafaa55677c)
[Evil User Role-Playing Workshop Board] (https://app.mural.co/t/raft2792/m/raft2792/1622549423164/8d45c7e7c1f3e89f7ca7f4be7ba08290937b3b6d) (Synthesis and Journey Maps for Review)
[OFA board](https://app.mural.co/t/officeoffamilyassistance2744/m/officeoffamilyassistance2744/1625085376648/ba7dd1a148fc1fb683d7378e8380b6e9a2038576?sender=laurenfrohlich3146)

**Comment by dk-ui** [comment]
@shubhi-raft moving this to qasp, top-line synthesis is comprehensive of the work done in the workshops and the next steps for future research.

**Comment by amilash** [comment]
@lfrohlich We're pretty sure this is approved. Can you confirm?

**Comment by lfrohlich** [comment]
This is complete and board has been copied to OFA
