### ISSUE TITLE
As a dev, I want an automated tool to prevent me from committing secret keys to the repo

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#965]
**Description:**
As a developer, it is fairly simple to accidentally commit secrets to the repo when using `git add .` on a working branch. We can prevent this from happening by utilizing a client-side [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to scan the staged files before creating a commit. This scan would need to look through the files and find anything which may be a secret key based on things like the entropy of a string, regex pattern matching, etc. Whatever solution we go with should allow a way to exclude false positives which may come up.

As a possible solution, [git-secrets](https://github.com/awslabs/git-secrets) is a library which provides a tool to do this scanning along with an installation step which would create and configure the git hooks for us.

**Acceptance Criteria:** 

- [ ] Before a developer can commit files staged by git they are scanned for possible secret keys
- [ ] No extra dependencies are added to the application, as this should happen on a developer's machine
- [ ] Developers have documentation indicating anything that needs to be installed locally for this to work
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Add a git hook that scans staged files for secret keys before committing to git.
- [ ] Update README steps for local development
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

- [Installing git-secrets](https://github.com/awslabs/git-secrets#installing-git-secrets)

**Open Questions:**

**Comment by jtwillis92** [comment]
Here is an additional library from cloud.gov/18F that installs and configures git hooks for secret key leakage prevention: https://github.com/cloud-gov/caulking

**Comment by abottoms-coder** [comment]
Hello all, I've been working on the git secrets ticket and it doesn't appear there's a totally automated way for this to work because we use regular old Github as our provider. While I have it up and running in my environment, a fresh clone on a different system does not retain the git configurations and git won't let you commit git configs to the repo BY DESIGN. It seems for these git hooks to be executed, a developer would need to manually set their git global config (once per system) or manually run some include commands on each fresh clone which seems prone to forgetfulness. While git does support server-side pre-receive or even update-based hooked and can reject these out of hand, github does not support this unless we get github enterprise and do some advanced configurations using their API. 

https://stackoverflow.com/questions/18329621/how-to-store-a-git-config-as-part-of-the-repository
https://stackoverflow.com/questions/22100581/github-server-side-git-hooks-i-e-pre-commit-and-post-commit

I will be coming up with a simple series of steps that developers should only have to run once on their development environments.

**Comment by ADPennington** [comment]
> Hello all, I've been working on the git secrets ticket and it doesn't appear there's a totally automated way for this to work because we use regular old Github as our provider. While I have it up and running in my environment, a fresh clone on a different system does not retain the git configurations and git won't let you commit git configs to the repo BY DESIGN. It seems for these git hooks to be executed, a developer would need to manually set their git global config (once per system) or manually run some include commands on each fresh clone which seems prone to forgetfulness. While git does support server-side pre-receive or even update-based hooked and can reject these out of hand, github does not support this unless we get github enterprise and do some advanced configurations using their API.
> 
> https://stackoverflow.com/questions/18329621/how-to-store-a-git-config-as-part-of-the-repository
> https://stackoverflow.com/questions/22100581/github-server-side-git-hooks-i-e-pre-commit-and-post-commit
> 
> I will be coming up with a simple series of steps that developers should only have to run once on their development environments.

@abottoms-coder thank you for this additional context! couple of questions:

- looks like the most recent update to git-secrets was in 2019. any concerns about on-going maintenance?
- any risk of false positives with this option (relative to any alternatives considered)?
- the ticket that follows (#966) will introduce secret detection in ci, so wondering if selecting the appropriate tool for that should complement or match the selection here (e.g. i understand trufflehog also works locally; caulking uses gitleaks, etc.)

**Comment by abottoms-coder** [comment]
1. That could be a concern but I did compare alternatives and found this has the best dev experience.
2. False positives can be handled using git-secrets --add function and would be included in the code review.
3. As we discussed on tech sync, I wasn't even aware that ticket existed which is why this pull request included the circleCI functionality. I'll have to discuss with @jtwillis92 on utility of adding on a history scanning tool like those mentioned in #966.
