### ISSUE TITLE
[DevOps] Add a Circle CI testing step that confirms no secret keys have been committed

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#966]
**Description:**
With #965 we will have a git hook that prevents secret keys from being committed by local developers. However, since this is run on the client side it could potentially be circumvented. Additionally, this hook isn't auditable for future assurance that the hook was indeed run and didn't find any secrets. If we add an additional step to the Circle CI `build_and_test` workflow to perform this checking in CI we can ensure that we both have auditability for these checks and that they were not circumvented on the client side.

**Potential Solutions:**
- [truffleHog](https://github.com/trufflesecurity/truffleHog)
- [gitleaks](https://github.com/zricethezav/gitleaks)

**Acceptance Criteria:** 

- [ ] Circle CI builds have a step that confirms no secret keys have been committed to the repo
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**

- [ ] Implement a solution like `truffleHog` or `gitleaks` as a step in the Circle CI `build_and_test` workflow
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
Remaining Estimate Sp 28: 3
