### ISSUE TITLE
[DevOps] Perform validation on Codecov Bash Uploader script during CI steps

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#968]
**Description:**
Codecov was recently the target of a [high profile breach](https://about.codecov.io/security-update/) that may or may not have affected our CI pipeline. As a precaution against potential similar attacks in the future Codecov has recommended that we perform some additional hash validation on the Bash Uploader script used to send coverage reports from CI to Codecov:
> The Codecov bash uploader is open source, and it can be validated for correctness by calculating the
SHASUM on download and comparing to the result we store in the GitHub repository.

**Acceptance Criteria:** 

- [x] Codecov bash uploader script is validated to ensure that it has not been tampered with before allowing it to execute in CI
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Add the code to check the `shasum` of the downloaded bash uploader script before running it to send coverage reports
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

- [Validating the bash uploader script](https://docs.codecov.io/docs/about-the-codecov-bash-uploader#validating-the-bash-script)

**Open Questions:**
