### ISSUE TITLE
As a dev, I want the authentication credentials used for testing to be dynamically generated

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#969]
**Description:**
Currently we utilize hard-coded access tokens that are tied to an environment variable `JWT_CERT_TEST` which is injected into several different tests to replace `JWT_KEY`. This makes our tests more brittle and less portable as a developer must retrieve the correct value before they can run any tests. Additionally, the code that utilizes these is repeated multiple times within tests which introduces undue risk when making changes to authentication code and can cause extra work for developers.

Instead we should find a way to dynamically generate a valid JWT_KEY used only for testing and access/ID tokens that go along with it. Additionally, we should update all the tests to utilize these in a [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) manner instead of repeating portions of code in multiple tests.

**Acceptance Criteria:** 

- [x] JWT_KEY (JWT_CERT_TEST) used for tests is dynamically generated along with any needed access tokens
- [x] Tests are updated to be more DRY
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Implement a fixture or factory that generates the required JWT_KEY and access tokens for tests
- [x] Update authentication tests to use the new fixtures/factories and consolidate/abstract repeated logic
- [x] Remove JWT_CERT_TEST env var from CircleCI and .env.example in the backend directory
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
