### ISSUE TITLE
[Backend] Utilize Django settings modules for non-sensitive environment variables that differ between deployed environments

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#970]
**Description:**
Currently we have the following settings modules in use in this project:
- `common.py` - houses the central entrypoint for all settings used in multiple environments
- `development.py` - contains overrides for sites deployed to the dev space in cloud.gov
- `local.py` - contains local development overrides for common settings
- `production.py` - currently unused
- `staging.py` - currently unused
- `test.py` - currently unused

NOTE: As of [this PR](https://github.com/raft-tech/TANF-app/pull/1123) we now have a `cloudgov` settings module to replace `development`, `production` and `staging` - with the individual settings classes defined inside that same module.

As shown above, the only settings modules in use are `development` and `local` - which is fine before we have a staging and production environment but will not be once those environments are in use. A number of these settings are defined via environment variables which get set in the deployment script `set-backend-env-vars.sh` which runs from CircleCI and passes in variables configured in project settings to the cloud.gov app. However, this presents a problem when the variables needed for deployments in different environments differ. Instead of defining multiple variables in Circle CI and deriving the correct one in the script we can utilize the distinct settings modules to provide defaults for the environment variables and then just not set them. In the future we would be able to set them as needed to override the defaults.

As a note, this would only be applicable to non-secret environment variables that differ between spaces - such as the following:
- CLIENT_ID
- OIDC_OP_AUTHORIZATION_ENDPOINT
- OIDC_OP_ISSUER
- OIDC_OP_JWKS_ENDPOINT
- OIDC_OP_LOGOUT_ENDPOINT
- OIDC_OP_TOKEN_ENDPOINT
- OIDC_RP_CLIENT_ID (possible dupe of CLIENT_ID)

From there we would just need to dynamically set the correct `DJANGO_CONFIGURATION` and `DJANGO_SETTINGS_MODULE` environment variables to point to the correct setting modules.

**IMPORTANT**: We should not remove the ability to override these defaults with environment variables.

**Acceptance Criteria:** 

- [x] Django settings modules contain defaults for non-secret environment variable based settings that are specific to their respective environments
- [x] The appropriate settings modules are used for each deployed environment (Completed with [this PR](https://github.com/raft-tech/TANF-app/pull/1123))
- [x] Direct usage of environment variables is replaced by Django settings
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Update Django settings modules with space specific defaults for the environment variables listed above (and possible others if found during this work)
- [x] Update `set-backend-env-vars.sh` to dynamically determine the appropriate settings module based on the space targetted along with removing any now unnecessary `cf set-env` commands (Partially completed with [this PR](https://github.com/raft-tech/TANF-app/pull/1123))
- [x] Update any direct environment variable usage to call Django settings instead.
- [x] Remove any unused variables from the Circle CI project settings.
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**
