### ISSUE TITLE
Deployed environments should pull AWS credentials from Cloud.gov provided environment variables

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#971]
**Description:**
Production environments currently leverage two sets of AWS related environment variables.

Data Files S3 Storage:
- AWS_ACCESS_KEY
- AWS_BUCKET
- AWS_SECRET_ACCESS_KEY

Django Staticfiles Storage:
- DJANGO_AWS_ACCESS_KEY_ID
- DJANGO_AWS_SECRET_ACCESS_KEY
- DJANGO_AWS_STORAGE_BUCKET_NAME

These are all defined in Circle CI Environment Variables as well so they can be passed in to new deployments. However, in the context of a Cloud.gov deployed application these are redundant. Everything we need to access the bound S3 services is exposed in the `VCAP_SERVICES` environment variable that is automatically available to the backend application.

There is some code in `tdpservice.settings.common` that attempts to reference these variables but it has not been updated to reflect the two distinct buckets. Additionally with the merge of https://github.com/raft-tech/TANF-app/pull/977 we'll have consistently named services that we can use to reference instead of collecting them via their index position. 

We should update the settings configuration for deployed environments such that all of the needed AWS settings are pulled from the `VCAP_SERVICES` environment variable. In the context of CI and locally hosted applications we only need to set `AWS_BUCKET` and `AWS_REGION_NAME` for usage in localstack and those can probably just get hardcoded in the docker-compose file but either way we will need to make sure that is accounted for with this settings change.

**Acceptance Criteria:** 

- [x] AWS credentials should not be stored in Circle CI
- [x] AWS credentials should be pulled from the services bound to the application in Cloud.gov environments
- [x] Uploaded Data Files and Django Admin static files get uploaded to separate S3 instances per the services configuration
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**

- [x] Update Django settings used by Cloud.gov deployments to pull in the appropriate settings from `VCAP_SERVICES` environment variable
- [x] Remove AWS credentials from Circle CI Project Settings
- [x] Ensure that local and CI continues to function correctly with localstack after removing the AWS credentials environment variables
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**

**Supporting Documentation:**

**Open Questions:**

**Comment by jtwillis92** [comment]
This came up during testing for #861 - currently the incorrect credentials are being retrieved for the Django Admin staticfiles causing the following stacktrace on the backend startup:
```
16:38:05.789: [APP/PROC/WEB.0]   File "manage.py", line 31, in <module>
16:38:05.789: [APP/PROC/WEB.0]     main()
16:38:05.789: [APP/PROC/WEB.0]   File "manage.py", line 27, in main
16:38:05.789: [APP/PROC/WEB.0]     execute_from_command_line(sys.argv)
16:38:05.789: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
16:38:05.789: [APP/PROC/WEB.0]     utility.execute()
16:38:05.789: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
16:38:05.789: [APP/PROC/WEB.0]     self.fetch_command(subcommand).run_from_argv(self.argv)
16:38:05.789: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
16:38:05.789: [APP/PROC/WEB.0]     self.execute(*args, **cmd_options)
16:38:05.789: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
16:38:05.790: [APP/PROC/WEB.0]     output = self.handle(*args, **options)
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
16:38:05.790: [APP/PROC/WEB.0]     collected = self.collect()
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
16:38:05.790: [APP/PROC/WEB.0]     handler(path, prefixed_path, storage)
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 338, in copy_file
16:38:05.790: [APP/PROC/WEB.0]     if not self.delete_file(path, prefixed_path, source_storage):
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 291, in delete_file
16:38:05.790: [APP/PROC/WEB.0]     self.storage.delete(prefixed_path)
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/storages/backends/s3boto3.py", line 452, in delete
16:38:05.790: [APP/PROC/WEB.0]     self.bucket.Object(name).delete()
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
16:38:05.790: [APP/PROC/WEB.0]     response = action(self, *args, **kwargs)
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
16:38:05.790: [APP/PROC/WEB.0]     response = getattr(parent.meta.client, operation_name)(*args, **params)
16:38:05.790: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
16:38:05.791: [APP/PROC/WEB.0]     return self._make_api_call(operation_name, kwargs)
16:38:05.791: [APP/PROC/WEB.0]   File "/home/vcap/deps/0/python/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
16:38:05.791: [APP/PROC/WEB.0]     raise error_class(parsed_response, operation_name)
16:38:05.791: [APP/PROC/WEB.0] botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied
```
It appears in this case Django just defaults to serving the staticfiles it generates and stores locally so the admin site still works but we are not leveraging the s3 service at all for staticfiles currently.

cc @abottoms-coder @ADPennington
