### ISSUE TITLE
Secret Key Leakage Mitigation for Release 1

### ISSUE THREAD

**Issue by jtwillis92** [raft-tech/TANF-app#972]
This epic houses issues related to findings from our Secret Keys post-mortem and is intended to lower the possibility and risk factors related to unintended secret key leakage.

[Post-Mortem Synthesis OneNote](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/15/Doc.aspx?sourcedoc={cbce2e75-17b2-4e70-b422-60d034fcd4af}&action=edit&wd=target%28Dev%20Notes.one%7C3dbb7d3a-694d-4f1c-a656-f907991c1f7d%2FSecret%20Key%20Leakage%20Post-Mortem%20Synthesis%7C0496800f-8810-4159-95e4-9fc605dc86d4%2F%29)

Tickets included in this epic: 
- Automated tool will be added to detect secret keys before local developers can commit changes to project repo ([#965](https://github.com/raft-tech/TANF-app/issues/965)) 
- Automated testing step will be added in CircleCI to check for secret keys and stop the CI process if keys are detected ([#966](https://github.com/raft-tech/TANF-app/issues/966))
- `DJANGO_SECRET_KEY` is automatically generated for initial deployments to Cloud.gov. This will ensure that the key is not shared across any environments and never needs to be exposed to developers or stored outside of Cloud.gov ([#967](https://github.com/raft-tech/TANF-app/issues/967))
- Perform validation on Codecov Bash Uploader script during CI steps to ensure that it has not been tampered with before allowing it to execute in CI. ([#968](https://github.com/raft-tech/TANF-app/issues/968))
- The `JWT_KEY (JWT_CERT_TEST)`  that is used for testing will be dynamically generated to allow us to reduce the number of keys stored in CI/CD environment variables. ([#969](https://github.com/raft-tech/TANF-app/issues/969))
- AWS credentials to our data files  to be removed from Circle CI as part of ([#971](https://github.com/raft-tech/TANF-app/issues/971))
- Secret keys will be rotated whenever team members rotate off the project. We will soon be leveraging Terraform to automate provisioning of services (e.g. S3, RDS) and eventually to manage users with access to our cloud.gov environments, so the vision is to automate the process of rotating secret keys whenever our user list changes.  ([#1004](https://github.com/raft-tech/TANF-app/issues/1004))

Other tasks:
- [x] @ADPennington should update [markdown](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/Secrey-Key-Mgmt.md) when last ticket for this epic addressed. 
- [ ] @abottoms-coder will update main markdown for onboarding developers and setting up their environment for mitigation (re: #965)
- [ ] @abottoms-coder to clean-up work related to #1004 (#1362 #1363, #1364, #1379)

**Comment by ADPennington** [comment]
updated epic description:

- removed this (`Add .dockerconfig file as an extra layer of security against accidentally leaking secrets as part of local development ([#544](https://github.com/raft-tech/TANF-app/issues/544)`)) per 7/27 backlog refinement
- added a task for myself to updated secret key management doc.

**Comment by ADPennington** [comment]
#1004 is also a part of this epic. is a spike needed to research how best to implement? @jtwillis92 @abottoms-coder

**Comment by ADPennington** [comment]
@abottoms-coder #1004 is the last ticket originally scoped for secret key mitigation work for release 1, and it spun out into #1362, #1363, #1364 and #1379. Some notes:

- We've paused on #1379, which I don't believe to be a priority for release 1. It is a nice-to-have optimization to consider after TDP has reached parity with TDRS (release 4+). I'd also be open to reconsidering priority if/when there is a big shift in team composition. Relatedly, in the spirit of keeping tech debt to a minimum, it seems prudent to revert changes from #1364 since we are no longer certain about the optimization strategy for here. Thoughts on this?
-  #1362 is the final ticket to address to close out this epic, and there is a suggestion in this ticket about building off of #1379 work, which makes me wonder if more research is needed to develop a strategy for 1362. If so, then I would suggest also shifting it down in the roadmap and creating a new ticket for us to manually rotate all secret keys before closing out Release 1 and fully documenting our manual process. The priority of this alternative ticket would be after we've completed all authentication-related integration work. Thoughts on this?
- Finally, once decisions have been agreed upon for the first 2 bullets herein, we'll need to tackle the _other tasks_ in the main summary of this ticket before closing this epic.

**Comment by jtwillis92** [comment]
I would advise closing this epic and tracking the remaining issue separately in the backlog, not necessarily tied to Release 1.

**Comment by ADPennington** [comment]
agree but i think the remaining tasks are worth addressing in release 1 to keep tech debt down. @jtwillis92 @valcollignon @abottoms-coder

**Comment by valcollignon** [comment]
Does it make sense to do one of the following to better track work being completed: 
1. close this epic, create a new epic for release 2 (Secret Key Leakage Mitigation for Release 2), and migrate all tasks and the remaining issue to that epic?
or
2. Keep this epic, but build out tickets for each task (and add them to this epic) so that they can be assigned out in a sprint to ensure they are done during Release 1 work?

**Comment by ADPennington** [comment]
> Does it make sense to do one of the following to better track work being completed:
> 
> 1. close this epic, create a new epic for release 2 (Secret Key Leakage Mitigation for Release 2), and migrate all tasks and the remaining issue to that epic?
>    or
> 2. Keep this epic, but build out tickets for each task (and add them to this epic) so that they can be assigned out in a sprint to ensure they are done during Release 1 work?

this is release 1 work, so i'd vote for option 2. plus all these tasks are relevant clean ups before adding someone to the team, which i suspect will happen before release 2 begins.

**Comment by stevenino** [comment]
This is preventing epic https://github.com/raft-tech/TANF-app/issues/972 from closing. Is this still required for v1?

**Comment by stevenino** [comment]
@lfrohlich @ADPennington Can we close this epic?

**Comment by ADPennington** [comment]
yes.
