### ISSUE TITLE
Django Admin a11y Fixes (Sprint 1)

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#973]
**Description:**
Delivers useful existing resources (USWDS theme for Django Admin) and optimizes them for use in our project, sets ground for testing. 

**Acceptance Criteria:** 
- [x] Django admin is more visually accessible (e.g. color, contrast) 
- [x] Testing Checklist has been run and all tests pass

**Tasks:**
- [x] Create fork of [https://github.com/fabiocaccamo/django-admin-interface](https://github.com/fabiocaccamo/django-admin-interface)
- - [x] [https://github.com/raft-tech/django-admin-interface](https://github.com/raft-tech/django-admin-interface)
- [x] Remove non-USWDS data and themes from fork
- [x] Publish initial version of fork as package to pypi under a Raft org
- [x] Install package to TANF, add to settings.py, and open PR

**Supporting Documentation:**
[https://hackmd.io/@mreiter/ryuHXhbuu](https://hackmd.io/@mreiter/ryuHXhbuu
) Contains task list for a11y fixes that will follow on from this ticket and complete #892

**Comment by jtwillis92** [comment]
If we fork [this plugin](https://github.com/fabiocaccamo/django-admin-interface#us-web-design-standards-theme) and do all the a11y updates on the fork then just install our modified plugin to TDRS Django we'd have most of the heavy lifting done for us

They have a USWDS theme which looks like it fixes the contrast issues (item 4 in `To Fix`) and most importantly it lays all the groundwork to hooking into Django and overriding the default admin templates so we'd just have to modify the templates in the plugin and publish it to pypi. Additionally it makes the admin responsive, which it is not by default (item 5 in `To Fix`).

**Comment by jorgegonzalez** [comment]
Yeah I was taking heavy guidance from that repo, but it would be far easier if I just forked it.

**Comment by jorgegonzalez** [comment]
Forked here https://github.com/raft-tech/django-admin-interface for now.

**Comment by amilash** [comment]
This is merged and done
