### ISSUE TITLE
Research on high vs low engagement STTs

### ISSUE THREAD

**Issue by SelenaJV** [raft-tech/TANF-app#99]
**Description:**
_This is a hold over from pre-Raft work._

From past research, we know that some STTs are more engaged with OFA and have more staff, resources and time to put towards TANF reporting, while others have limited engagement and fewer resources. 

This issue is to outline what we know about which STTs have high vs low engagement, which may help us with future recruiting techniques. 

**AC:** 

- [ ] Sample acceptance criteria

**Tasks:** 

- [ ] Review Path analysis / Yun notes on high vs low capacity states
- [ ] Create home for future list

**Supporting Documentation:**

(please include any relevant log snippets/ files/ screen shots here.)

**Open Questions:**

(any clarifying questions in support of the issue)

**Comment by shubhi-raft** [comment]
this may be a dupe #163. moving this to refinement Sprint 4/5 pipeline for discussion.

**Comment by matthewjdoty** [comment]
@lfrohlich, this has been marked as a duplicate, can we close it?

**Comment by lfrohlich** [comment]
Agree this is duplicative, closing
