### ISSUE TITLE
(Sprint 23) Round 7 UX Research Planning

### ISSUE THREAD

**Issue by dk-ui** [raft-tech/TANF-app#993]
**Description:**
(Sprint 23) Planning sprint for Sprints 24-26 is intended to synthesize and process the learnings from the prior research round and map out future goals for research and design in accordance with the Road Map and release schedule.

**AC:**
PO, PM, and Research and Design Team use the roadmap to agree on the actionable insights of the prior research round and also agree on the goals, outputs, and research methods for the next three sprints. Sprint 7 related tickets/epics are ready for backlog refinement. 

**Tasks:**

*Research Synthesis Workshop: To review findings from the DIGIT error category workshop, the DIGIT error slicing workshop, and the evil user workshop in order to synthesize into actionable insights and next step validations for round 7 research*
- [x] (Miles / Dmitri) Add each top-line synthesis from past 3 sprints to research synthesis workshop template
- [x] (Dmitri) Facilitate research synthesis workshop to align on next step validations
- [x] (Miles) Create a round Synthesis in [Hack MD](https://hackmd.io/KcgndJhvS5aEqVwBEz_PlQ) documenting the actionable insights from the prior Research Round

*Research Plan Workshop: To leverage what we learned in prior research and identify future validations to focus the deliverables for the next three sprints of research and design*
- [x] (Miles) Add results from the research synthesis workshop into the research plan workshop board
- [x] (Miles / Dmitri) Update aspirational state maps based on new learnings
- [x] (Dmitri/Miles) Facilitate research plan workshop

*Live Communications with Stakeholders*
- [x] (Dmitri) Create a presentation that can be sent to OFA RO staff (include research synthesis link to github)
- [x] (Miles) Ensure that format of presentation is 508 accessible
- [x] (Lauren) Schedule meeting for live communications
- [x] (Dmitri / Miles) Conduct presentation with stakeholders
- [x] (Dmitri) Send presentation recording and presentation link to Lauren to send to ROs

*Round 7 Ticketing*
- [x] (Dmitri/Miles) UX Research Round 7 Epic is created and filled out
- [x] (Dmitri/Miles) Sprint 24-26 stories are created and tentatively filled out

**DoD:**
- [x] presentation of synthesis, research plan, live comms presentation, and tickets
- [ ] @lfrohlich sign off

**Deliverables**
Round 6 Research Synthesis Board: [Link](https://app.mural.co/t/raft2792/m/raft2792/1621971341246/2f99fbea9db26da97a542b88c79c3fd2f2877d9a)
Round 6 Research Synthesis summary in docs: [Link](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/2021%2C%20Spring%20-%20Evil%20User%20Journeys%20%26%20TANF%20Data%20Errors%20(Round%206).md)
Research Plan Workshop Board: [Link](https://app.mural.co/t/raft2792/m/raft2792/1621971341246/2f99fbea9db26da97a542b88c79c3fd2f2877d9a) 
Live Comms Presentation: [Link](https://www.canva.com/design/DAEhjmRQZgk/N13nhwTuZV4hltRr-pF9EQ/edit)
Round 7 Epic: [Link](https://app.zenhub.com/workspaces/tdrs-product-backlog-5f2c6cdc7c0bb1001bdc43a5/issues/raft-tech/tanf-app/1017)
Sprint 24 (June 23 - July 6) Story: [Link](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/1018)
Sprint 25 (July 7 - July 20) Story: [Link](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/1019)
Sprint 26 (July 21 - August 3) Story: [Link](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/1020)

**Comment by dk-ui** [comment]
@lfrohlich ready for review

**Comment by lfrohlich** [comment]
Research synthesis was added to [docs](https://github.com/HHS/TANF-app/blob/main/docs/User-Research/2021%2C%20Spring%20-%20Evil%20User%20Journeys%20%26%20TANF%20Data%20Errors%20(Round%206).md)
